### ISSUE TITLE
train and test score all zero

### ISSUE THREAD

**Issue by nnzhan** [rusty1s/pytorch_geometric#10]
Hi,  thanks for sharing the code. When I run the example code, why train and test score are all zero all the time?

**Comment by rusty1s** [comment]
In order to help you, please let me know about your system:
* CUDA version
* Python version
* PyTorch version

**Comment by nnzhan** [comment]
My system is python 2.7

**Comment by rusty1s** [comment]
Ok, that makes sense. Thanks for letting me know.
