### ISSUE TITLE
Including Simple Graph Convolution

### ISSUE THREAD

**Issue by Tiiiger** [rusty1s/pytorch_geometric#100]
Thank you for maintaining such a great project here!

In our recent paper (https://arxiv.org/pdf/1902.07153.pdf), we discover a linear model (Simple Graph Convolution) that can be as effective as GCN while saving a lot of training time. We have our official implementation at https://github.com/Tiiiger/SGC. I would like to help or coordinate with you on having an example implementation of Simple Graph Convolution in this project. 

Perhaps somewhat different from other models, the propagation step in Simple Graph Convolution can be simplified as a preprocessing step and the model would be reduced to logistic regression. I am not sure how to implement such a preprocessing using the current API. Can you give me some pointers on how to start?

**Comment by rusty1s** [comment]
Hi,
I would love to see SGC in PyTorch Geometric.

I suggest adding a `cached` flag to the SGC constructor and using `propagate` in a for-loop:
```python
def __init__(self, in_channels, out_channels, hops=1, cached=False):
    self.hops = hops        
    self.cached = cached
    self.cached_result = None
    self.lin = Linear(in_channels, out_channels)

def forward(self, x, edge_index, edge_weight=None):
    if self.cached and self.cached_result = None:
        norm = ... # Compute
        for k in range(hops):
            x = self.propagate('add', edge_index, x=x, norm=norm)
        self.cached_result = x
    return self.lin(self.cached_result)

def message(self, x_j, norm):
    return norm.view(-1, 1) * x_j
```
Are you okay with this?
You are welcome to submit a pull request, otherwise, I would integrate it by myself.

**Comment by Tiiiger** [comment]
Looks great! It would be nice if you can help integrate it : )

**Comment by rusty1s** [comment]
[Implementation](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.conv.SGConv) + [Experiments](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/sgc.py). Results look good so far. Thanks for letting me know.

**Comment by Tiiiger** [comment]
Thank you for being so responsive!
