### ISSUE TITLE
ImportError: `SplineConv` requires `torch-spline-conv`

### ISSUE THREAD

**Issue by mwussow** [rusty1s/pytorch_geometric#1000]
## 🐛 Bug

When I try to train a network with a SplineConv layer (e.g. faust.py from example folder), I get the following error: ImportError: `SplineConv` requires `torch-spline-conv`. 

Previously this worked without throwing an error. This error started occuring after I freshly installed my environment incl. torch-geometric, torch-scatter, torch-sline-conv, torce-sparse and pytorch (for all version latest+cu100) on a free paperspace Gradient instance running the Free-GPU (Quadro M4000). Torch-spline-conv also appears in pip list with version 1.2.0.

## To Reproduce

1. Setup free instance at https://www.paperspace.com/console/notebooks
2. Select Free-GPU or Free-P5000
3. Install required packages and run fast.py from pytorch-geometric examples

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eae10ca85c2a> in <module>
----> 1 from faust import *

/storage/pytorch_geometric/examples/faust.py in <module>
     44 
     45 device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
---> 46 model = Net().to(device)
     47 target = torch.arange(d.num_nodes, dtype=torch.long, device=device)
     48 optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

/storage/pytorch_geometric/examples/faust.py in __init__(self)
     20     def __init__(self):
     21         super(Net, self).__init__()
---> 22         self.conv1 = SplineConv(1, 32, dim=3, kernel_size=5, aggr='add')
     23         self.conv2 = SplineConv(32, 64, dim=3, kernel_size=5, aggr='add')
     24         self.conv3 = SplineConv(64, 64, dim=3, kernel_size=5, aggr='add')

/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/spline_conv.py in __init__(self, in_channels, out_channels, dim, kernel_size, is_open_spline, degree, aggr, root_weight, bias, **kwargs)
     60 
     61         if SplineBasis is None:
---> 62             raise ImportError('`SplineConv` requires `torch-spline-conv`.')
     63 
     64         self.in_channels = in_channels

ImportError: `SplineConv` requires `torch-spline-conv`.

## Expected behavior

faust.py should have run without throwing an error

## Environment

* OS: Ubuntu V18.04.2 LTS ("Bionic Beaver")
* Python version: 3.6.8
* PyTorch version: 1.4.0+cu100
* CUDA/cuDNN version: NVCC Release 10.0 V10.0.130

**Comment by rusty1s** [comment]
Yes, I am aware of this. It is already fixed in master. Sorry!

**Comment by mwussow** [comment]
Thanks for the prompt reply! Can I just reinstall the packages and it should work or is there a special way to install from the master branch?

**Comment by rusty1s** [comment]
There is no new Pypi package for `torch-geometric` yet, but cloning `torch-geometric` and running `python setup.py install` should get you going.

**Comment by mwussow** [comment]
Alright, thanks!

**Comment by levulinh** [comment]
Hi, I tried installing from master branch but the problem seems to remain.

```
!pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
!pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
!pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
!pip install torch-cluster

!git clone https://github.com/rusty1s/pytorch_geometric.git
!python '/content/pytorch_geometric/setup.py' install
```
The procedure finished showing that I am using torch-geometric 1.4.2 now.
The error:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-9-29a3dbe53f42> in <module>()
>       1 device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> ----> 2 model = Net().to(device)
>       3 optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
> 
> 1 frames
> /usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/spline_conv.py in __init__(self, in_channels, out_channels, dim, kernel_size, is_open_spline, degree, aggr, root_weight, bias, **kwargs)
>      60 
>      61         if SplineBasis is None:
> ---> 62             raise ImportError('`SplineConv` requires `torch-spline-conv`.')
>      63 
>      64         self.in_channels = in_channels
> 
> ImportError: `SplineConv` requires `torch-spline-conv`.
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ---------------------------------------------------------------------------

**Comment by rusty1s** [comment]
Well there is no importing of `SplineBasis` in PyG master anymore, so it seems that Python does not load the PyG master version but instead uses an older one. Please try to uninstall all PyG versions first.

**Comment by levulinh** [comment]
> Well there is no importing of `SplineBasis` in PyG master anymore, so it seems that Python does not load the PyG master version but instead uses an older one. Please try to uninstall all PyG versions first.

Oh, it seemed to be a Google Colab caching problem. Thanks for quick replying.

**Comment by nairouzshehata** [comment]
Getting the same error
pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
pip install torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install -q torch-cluster -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install -q torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html 

pip install -q torch-geometric

Tried to uninstall and clone from GitHub but still the same.

**Comment by rusty1s** [comment]
Can you try to run `pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv` beforehand?

**Comment by nairouzshehata** [comment]
Have uninstalled all packages then `setup.py install` for torch-geometric. Now I'm getting
```
 import torch_geometric.transforms as T
ModuleNotFoundError: No module named 'torch_geometric'
```

even though pip show torch-geometric prints the location and all info.

**Comment by rusty1s** [comment]
That is super weird. Can you try to restart your Colab instance?

**Comment by nairouzshehata** [comment]
It is weird. Doesn't help no. Anyways my supervisor created a virtual environment and it is working fine.
Thanks @rusty1s !
