### ISSUE TITLE
Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by shijiehou** [rusty1s/pytorch_geometric#1004]
## 📚 Installation

*WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A1EFFC8>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A0F1048>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A0CFE88>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A1FB408>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A1FB4C8>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp37-cp37m-win_amd64.whl (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F00A1FBA08>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')) *

## Environment

* OS:win10
* Python version:3.7.4
* PyTorch version:1.4.0
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
Can you access https://pytorch-geometric.com/whl/torch-1.4.0.html and download the wheels from this website?
