### ISSUE TITLE
Better utils.to_networkx()?

### ISSUE THREAD

**Issue by tjiagoM** [rusty1s/pytorch_geometric#1005]
## 🚀 Feature

Hi, I have noticed two limitations from `utils.to_networkx()` which I was using in my project:

1. It can only return a directed DiGraph, whereas my original graph is actually undirected
2. It will always return the self loops for each node but I have them just for the sake of the message passing mechanism.

So, I was thinking about doing a PR with the changes I have made, but wanted to check with you first if you think this is something you'd like to include in pytorch geometric and whether you think I should make some changes first.

So far, the code I have is the following:
```python
def to_networkx(data, node_attrs=None, edge_attrs=None, to_undirected=False, remove_self_loops=False):
    r"""Converts a :class:`torch_geometric.data.Data` instance to a
    :obj:`networkx.DiGraph` if :attr:`to_undirected` is set to :obj:`True`, or an undirected
    :obj:`networkx.Graph` otherwise.

    Args:
        data (torch_geometric.data.Data): The data object.
        node_attrs (iterable of str, optional): The node attributes to be
            copied. (default: :obj:`None`)
        edge_attrs (iterable of str, optional): The edge attributes to be
            copied. (default: :obj:`None`)
        to_undirected (bool, optional): If set to :obj:`True`, it will return a :obj:`networkx.Graph`.
            In practice, the undirected graph will correspond to the upper triangle of the
            corresponding adjacency matrix. (default: :obj:`False`)
        remove_self_loops (bool, optional): If set to :obj:`True`, it will not include self loops in
            the returning graph.  (default: :obj:`False`)
    """

    if to_undirected:
        G = nx.Graph()
    else:
        G = nx.DiGraph()
    G.add_nodes_from(range(data.num_nodes))

    values = {key: data[key].squeeze().tolist() for key in data.keys}

    for i, (u, v) in enumerate(data.edge_index.t().tolist()):
        if to_undirected and v > u:
            continue
        if u == v and remove_self_loops:
            continue
        G.add_edge(u, v)
        for key in edge_attrs if edge_attrs is not None else []:
            G[u][v][key] = values[key][i]

    for key in node_attrs if node_attrs is not None else []:
        for i, feat_dict in G.nodes(data=True):
            feat_dict.update({key: values[key][i]})

    return G
```

I think the changes are very simple and easy to understand, also including from what I have put in the documentation, but basically I create a `Graph` if the user wants an undirected graph, and only include the upper triangle of the adjacency matrix (when u < v). I think the way it is now it is prepared for when you include edge attributes to be included in the nx graph, but maybe I forgot to cover some use case?

Looking forward to your comments!

**Comment by rusty1s** [comment]
Thanks for this issue. We could potentially do this. An alternative is just to call `G.to_undirected().remove_edges_from(G.selfloop_edges())` on the output networkx graph.

**Comment by tjiagoM** [comment]
Yes, I thought about that, but only calling those at the end would be less efficient but also I think potentially bring some strange behaviours because of the `edge_attrs` parameters that you have included in this function.
