### ISSUE TITLE
nn.DataParallel

### ISSUE THREAD

**Issue by bolinpu** [rusty1s/pytorch_geometric#101]
Hi,
I just would like to confirm If could use the "nn.DataParallel"  and how?

**Comment by rusty1s** [comment]
I do not think that is possible because we do not have a dedicated batch dimensionality :(
This is however a really important request and I leave this issue open till I come up with a way to tackle it.

**Comment by bolinpu** [comment]
we have data.batch. Hope you could solve it ASAP. Many thanks

**Comment by bolinpu** [comment]
Hi rusty1s,
Could you please tell me when  you are going to finish this?

**Comment by rusty1s** [comment]
Will look at it in more detail in the upcoming week.

**Comment by rusty1s** [comment]
Hey,
I implemented a first version of `torch_geometric.nn.DataParallel`. See [here](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#module-torch_geometric.nn.data_parallel) for the doc and [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/data_parallel.py) for an example. The basic idea is borrowed from PyTorch. However, as we allow variable sized input, I created a new dataloader (`torch_geometric.data.DataListLoader`) which outputs a list of data objects, and the `DataParallel` module converts these data objects to a batch per device. Let me know what you think.

**Comment by bolinpu** [comment]
@ @rusty1s  I will have a try ASAP. Many thanks

**Comment by bolinpu** [comment]
@rusty1s I got a error like the following:

RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 2 (while checking arguments for cudnn_batch_norm)

**Comment by rusty1s** [comment]
Can you show me a minimal example of your code?

**Comment by rusty1s** [comment]
Closed in favour of #137.
