### ISSUE TITLE
Can we install this with pytorch nightly build?

### ISSUE THREAD

**Issue by nikitamehrotra12** [rusty1s/pytorch_geometric#1017]
## ❓ Questions & Help

I am facing issues while installing PyTorch geometric with PyTorch nightly build. I am getting version mismatched error.

**Comment by rusty1s** [comment]
Currently no, sadly! This is one of the disadvantages of the newly provided Python wheels. You can try to install all the packages from source, and removing the version check in the `__init__.py` files. If you know of a better way to fix this, please let me know :)

**Comment by dvirginz** [comment]
It would help me as well:)
@nikitamehrotra12, have you tried building from source?

**Comment by devnkong** [comment]
Hi @rusty1s , I have the similar problem that I also wanna use the nightly Pytorch version. I have tried as you said to install PyG from the source. All the other four complementary packages seem to work well, but I encountered the error below:

```
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cmlscratch/kong/anaconda3/envs/graph-newest/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/cmlscratch/kong/anaconda3/envs/graph-newest/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 6, in <module>
    from .dataloader import DataLoader, DataListLoader, DenseDataLoader
  File "/cmlscratch/kong/anaconda3/envs/graph-newest/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 5, in <module>
    from torch._six import container_abcs, string_classes, int_classes
ImportError: cannot import name 'container_abcs' from 'torch._six' (/cmlscratch/kong/anaconda3/envs/graph-newest/lib/python3.7/site-packages/torch/_six.py)
```

This could be due to the removal of 'torch._six' from the nightly version. Do we have any plan to solve this? Thanks.

**Comment by rusty1s** [comment]
It might be possible that PyTorch nightly might destroy some of the current PyG functionality. We generally update those breaking changes once an official PyTorch release lands as we can't support both at the same time. I guess a simple fix is to just remove [these lines](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/dataloader.py#L26-L31) in PyG.

**Comment by devnkong** [comment]
It worked, thank you
