### ISSUE TITLE
Given a graph G, how to compute the FLOPS of single spline conv layer?

### ISSUE THREAD

**Issue by ganji15** [rusty1s/pytorch_geometric#1020]
## ❓ Questions & Help

Dear @rusty1s ,

I have a question about how to compute FLOPs of SplineConv for an input graph G.

As we know, given an image with a size of HxW, the FLOPs of a single convolution (with kernel size KxK) should be HxWxKxK. 

Given a graph G=(X, E, P) where X is node feature set and X \in Nxm, E is the edge set, and P is the pseudo coordinate set and P \in Nxd. For a spline convolution _S_ SplineConv(in_features=m, out_features=n, dim=d, kernel_size=k), how to compute the FLOPs of this spline convolution on graph G (i.e. Flops(_S_(G)))?

I think the key is how to compute the complexity of edge weight computation (i.e. Flops(W_e), where W_e is the edge weight of the edge e) since Flops(_S_(G)) = |E| x Flops(W_e). However, Flops(W_e) for SplineConv is a little complicated.

Could you please kindly help me? Thanks in advance.

**Comment by rusty1s** [comment]
Yeah, it is a bit more complicated. I do not have the exact number of FLOPs for you, but an upper limit for Flops(W_e) is O((m+1)^d), where m is the basis degree and d is the dimensionality of edge features. Therefore, compared to 2D CNNs, the number of FLOPs only differs by a constant factor.

**Comment by ganji15** [comment]
@rusty1s Actually, I want to know how exactly large is this constant factor (10x, 100x, or even 1000x?)? I feel that graph convolutions seem much slower than the conventional convolutions, and  I wonder whether the graph convolutions actually cost most of its time in the edge weight computation rather than the node feature aggregation (\sum_j X_i W_ij). Thanks.

**Comment by rusty1s** [comment]
Well, it is slower because conv2d operations are highly optimized, while GNN operators rely on PyTorch building blocks, aren't close to memory-efficient and rely on irregular access patterns.

**Comment by ganji15** [comment]
@rusty1s Thanks, and I get your point.  If we ignore CNN's shortcomings in computational speed and recognition performance, does GNN has its unique advantages than conv2d (i.g. lower computation complexity or memory consumption)? Take image classification as an example, given an image with a size of (64, 64), its grid representation has 4096 nodes and ~36864 imaginary edges, while its super-pixel graph representation may have only 200 nodes and ~4000 edges. So on this condition, would GNN  theoretically involve lower FLOPs and consume memories? This is exactly what I concern and why I need to know the exact FLOPs of GNN (i.g. SplineConv).

**Comment by rusty1s** [comment]
The number of FLOPs would be lower, the memory consumption is about the same, but the runtime should still be lower due to irregular access patterns. That's why #FLOPs might not be the best indicator to measure GNN performance.

**Comment by ganji15** [comment]
Thanks. Therefore, we cannot except a faster runtime speed from GNN due to its irregular access patterns. Meanwhile, since GNN needs to store edge indices while CNN does not, the edge indices may consume the most memories in GNN than its nodes. Is this why nearly the same memories are costed in the image classification example (i.g. Image with 64x64 vs. graph with 200 nodes and ~4000 nodes)?

**Comment by rusty1s** [comment]
Memory requirements for GNN ops are actually [num_edges, num_features], so that is why memory consumption for normal CNN and GNN are about the same in this case.

**Comment by ganji15** [comment]
@rusty1s Thanks a lot for your kind help and insightful discussion, and now I have a better understanding of GNN.
