### ISSUE TITLE
ChebConv notation is a bit misleading

### ISSUE THREAD

**Issue by dvirginz** [rusty1s/pytorch_geometric#1027]
I think you should change the equations notation to start from k=1, and maybe drop the "hop" word which can be misleading.
The reason I say that, is because when setting K=1 you actually using `out=X` which is "hop"=0. 
![image](https://user-images.githubusercontent.com/31047807/76699923-b1bb1700-66ba-11ea-8788-0412b4d975c0.png)

**Comment by rusty1s** [comment]
Yes, you are right. Fixed in master! Thanks.
