### ISSUE TITLE
torch-cluster Package not found

### ISSUE THREAD

**Issue by AnonymizedAccount** [rusty1s/pytorch_geometric#1029]
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

Hi everyone,
I tried to install pytorch but I had a problem with the torch-cluster installation. I got package not found error and I checked the provided link for torch-cluster installation and I didn't find the required whl link for it. 
Any help, please.

**Comment by rusty1s** [comment]
This one is on me, I fixed it and the links should soon be available. In the meantime, you can use this link: http://pytorch-geometric.com.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html

**Comment by AnonymizedAccount** [comment]
Thank you for your quick reply. But when I tried the above link I got the following error:
  ERROR: Cannot unpack file Private\AppData\Local\Temp\pip-unpack-vy9krt0
q\torch-1.4.0.html (downloaded from Private\AppData\Local\Temp\pip-req-bu
ild-7t7kr3bf, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of Private\AppData\Local\Temp\pip-
req-build-7t7kr3bf

**Comment by rusty1s** [comment]
Can you try https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html instead? Sorry!

**Comment by rusty1s** [comment]
Should be fixed!
