### ISSUE TITLE
batch vector parameter in to_dense_batch() 

### ISSUE THREAD

**Issue by ahmedmazariML** [rusty1s/pytorch_geometric#103]
Hi @rusty1s ,
Thank your for this very important work.

I have a question related to `batch` input parameter in  `to_dense_batch()`

https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/to_dense_batch.py#L18

Given` X` of dimension `(10,30,256)` where 10 is the batch size, 30 number of nodes and 256 the number of features per node. 
What does it mean by batch vector here ? and how do you get it. 

Thank you

**Comment by rusty1s** [comment]
Hi,

the method `to_dense_batch()` takes in a two-dimensional **sparse** batched node feature tensor and converts it to a dense. This structure is defined [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#mini-batches).

Your input `x` of dimension `(10,30,256)` therefore is actually the output of `to_dense_batch`. The input would be of dimension `(300,256)`, but using this method does not make a lot of sense when all graphs have the same size.
