### ISSUE TITLE
Error in TAGConv in batch mode of static graph

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1032]
## 🐛 Bug

Hello, I have a static graph and I want to use TAGConv in batch mode. More precisely, I followed the instruction on this [link](https://github.com/rusty1s/pytorch_geometric/issues/817). Imagine I have batched node features x with shape [B, N, in_channels], where B is the batch size and N is the number of nodes. Here is the sample code:

> import torch
> import torch_geometric
> 
> B = 2  # batch size
> N = 3   # number of nodes
> in_channels = 4
> out_channels = 8
> K = 2   # Number of hops
> 
> conv = torch_geometric.nn.TAGConv(in_channels=in_channels, out_channels=out_channels, K=K, node_dim=1)
> edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
> 
> x= torch.randn(B, N, in_channels)
> 
> out2 = conv(x, edge_index)

I get the following error:

> File "/site-packages/torch_geometric/nn/conv/tag_conv.py", line 50, in norm
>     deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
> RuntimeError: Invalid index in scatterAdd at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721
> The above operation failed in interpreter.
> Traceback (most recent call last):
>   File "/site-packages/torch_scatter/scatter.py", line 27
>             size[dim] = int(index.max()) + 1
>         out = torch.zeros(size, dtype=src.dtype, device=src.device)
>         return out.scatter_add_(dim, index, src)
>                ~~~~~~~~~~~~~~~~ <--- HERE
>     else:
>         return out.scatter_add_(dim, index, src)

I am not sure, but when I see inside the forward method of tag_conv.py I see that in the first line it is written:

> edge_index, norm = self.norm(edge_index, x.size(0), edge_weight, dtype=x.dtype)

Is it correct to use x.size(0)? Shouldn't it be x.size(self.node_dim)?

Moreover, something funny that I don't understand the reason is that I get this error with B=1 and B=2, but for B >=3 I don't have this error anymore.

## Environment

* OS: 16.04.6 LTS (Xenial Xerus)
* Python version: Python 3.6.2 :: Continuum Analytics, Inc.
* PyTorch version: 1.4.0 + cu9.2
* CUDA/cuDNN version: No CUDA
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Thanks for reporting. Should be fixed in master.

**Comment by navid-mahmoudian** [comment]
Now that you are fixing, I see in the norm method of tag_conv.py you are using 

> deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)

I don't know if this is again the same problem or not, but dim=0, to me, it looks like the same problem.

**More importantly, I see similar problem in SGConv (gcn_conv.py). **

**Comment by rusty1s** [comment]
This is no problem since `edge_index` is also expected to be of shape `[2, num_edges]`.

**Comment by navid-mahmoudian** [comment]
Thank you for your answer.

What about SGConv (gcn_conv.py)? I get the same error with this convolution as well.

**Comment by rusty1s** [comment]
Should be fixed there as well.

**Comment by navid-mahmoudian** [comment]
Thanks,

One last question in this regard. Since I am not familiar with packaging, am I going to see all the new changes you made in the master repository if I do 

> pip install torch-geometric


Or it takes time to change the code on pip?

**Comment by rusty1s** [comment]
Yeah, those changes are not on pip yet. But you can always clone the repo and just run python setup.py install.
