### ISSUE TITLE
Implementation problem of the GAT multi-head

### ISSUE THREAD

**Issue by yaoman3** [rusty1s/pytorch_geometric#1033]
## 🐛 Bug

Based on the original "Graph Attention Network" paper, The multi-head attention means calculate different attention coefficients for the same neighborhood. However, in the current implementation, 
it just reshapes the tensor, e.g.  `x.view(-1, self.heads, self.out_channels)`. It does not duplicate the node features by the number of head. I think the expected behavior should transform the size of input from the size (N, F) -> (N, H, F), which N is the number of nodes, H is the number of head, F is the number of features.

**Comment by rusty1s** [comment]
I do not see anything wrong with that. Note that before we reshape `x`, we transform it using a weight matrix, so we get differently features for each head. This is exactly what the [GAT paper](https://arxiv.org/pdf/1710.10903.pdf) is doing, see Eq. 5.

**Comment by yaoman3** [comment]
Thanks. I see the transformation of the weight matrix now.
