### ISSUE TITLE
GMMConV with Manifolds 

### ISSUE THREAD

**Issue by neolei** [rusty1s/pytorch_geometric#1036]
## ❓ Questions & Help

hello @rusty1s, i am a rookie in the usage of PyG, confused of GMMConv module with manifolds, how should face parameter of Data be handled?

**Comment by rusty1s** [comment]
The face parameter holds the information about faces in your mesh. For learning, you can always convert it to a graph using the `FaceToEdge` transform.

**Comment by neolei** [comment]
Thank your explanation @rusty1s. `Cartesian` transform is used to convert `POS` to pseudo?

**Comment by rusty1s** [comment]
Yes.
