### ISSUE TITLE
What is the corresponding version of prerequisites for cu90?

### ISSUE THREAD

**Issue by Coldog2333** [rusty1s/pytorch_geometric#1039]
## ❓ Questions & Help

Thanks for your efforts in PyG. :)

I notice there are instructions for cpu, cu92, cu10, cu101 in your README, but what about cu90?
What is the corresponding version for torch-sparse, etc.?

**Comment by rusty1s** [comment]
Since PyTorch does not provide cu90 binaries there is no reason for them to be included here.

**Comment by Coldog2333** [comment]
All right... I would update my cuda rather than build it from source.
Thank you!
