### ISSUE TITLE
scatter_order

### ISSUE THREAD

**Issue by bolinpu** [rusty1s/pytorch_geometric#104]
How about adding something like scatter_order

**Comment by rusty1s** [comment]
You mean `scatter_sort`?

**Comment by bolinpu** [comment]
Sometimes, we may want to order the neighbours of the node, according to some relationship score. It maybe useful, if we can order the neighbours. Now, we only have the scatter_max.

**Comment by rusty1s** [comment]
Ok, I understand. We do not have a dedicated CUDA kernel for this.
In the meantime I suggest you use [`to_dense_batch`](https://rusty1s.github.io/pytorch_geometric/build/html/modules/utils.html#torch_geometric.utils.to_dense_batch), sort the neighbors, and convert it back to a sparse layout.

**Comment by bolinpu** [comment]
how can I convert it back? Thanks

**Comment by rusty1s** [comment]
```python
row, col = edge_index
x = to_dense_batch(x, row, fill_value=1e8)
x = x.sort(dim=1)[0]
x = x.view(-1, channels)[x != fill_value]
```
This should work, however, it is not very efficient :(

**Comment by bolinpu** [comment]
cool, many thanks. you are awsome
