### ISSUE TITLE
Some questions in "Advanced Mini-Batching" chapter

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#1044]
## ❓ Questions & Help

hello @rusty1s :

I read advanced mini-batching chapter in https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html#pairs-of-graphs

![image](https://user-images.githubusercontent.com/37621591/77055018-469b7880-6a0b-11ea-9136-0a6d12e16ca7.png)

And I think ```x_s```'s shape should be 5. 

yours sincerely
@wmf1997

**Comment by rusty1s** [comment]
Oh, you are right. Thanks for letting me know. Should be fixed once the doc is re-built.
