### ISSUE TITLE
read_obj could not parse the faces of a Wavefront file

### ISSUE THREAD

**Issue by cristi191096** [rusty1s/pytorch_geometric#1045]
## 🐛 Bug

read_obj could not parse the faces of an `.obj` file due to the fact that there are two blank spaces between `f` and the first face index.

## To Reproduce

1.  A face in the `.obj` file should look like this: `f  1/1/1 2/2/2 3/3/3`
2. call `read_obj(file_path)`

The error stack is as follow: 
`Traceback (most recent call last):
  File "simplegan.py", line 268, in <module>
    data = process_mesh(catID, meshID[0])
  File "simplegan.py", line 109, in process_mesh
    return read_obj(mesh_filepath)
  File "C:\Users\Zaharia\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\io\obj.py", line 25, in read_obj
    for k, v in yield_file(in_file):
  File "C:\Users\Zaharia\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\io\obj.py", line 16, in yield_file
    yield ['f', [int(t.split("/")[0]) - 1 for t in triangles]]
  File "C:\Users\Zaharia\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\io\obj.py", line 16, in <listcomp>
    yield ['f', [int(t.split("/")[0]) - 1 for t in triangles]]
ValueError: invalid literal for int() with base 10: ''`

## Expected behavior

This function is expected to return a Data object that contains the positions and the faces from an `.obj` file.

## Environment

* OS:   Windows 10
* Python version:  3.6
* PyTorch version:  1.4.0
* CUDA/cuDNN version: No
* GCC version:
* Any other relevant information: PyTorch Geometric was installed using pip on a conda virtual environment

## Additional context

The problem I found is that the `triangles` list has an empty element at the beginning. The way I fixed this issue is by discarding the fist two elements in the list: `triangles = b.split(' ')[2:]`

**Comment by rusty1s** [comment]
We have a pull request open for this: https://github.com/rusty1s/pytorch_geometric/pull/1030
It would be great if you can verify that it is working correctly.
