### ISSUE TITLE
Any ideas on how to install pyg that supports pytorch 1.3?

### ISSUE THREAD

**Issue by HarveyYan** [rusty1s/pytorch_geometric#1046]
I installed the latest version of torch-geometric and it gives me:
RuntimeError: Expected PyTorch version 1.4 but found version 1.3.

I wondered if there is a way to install a version that supports an older version of pytorch. If there is, would anyone kindly guide me to the wheels of pyg that support pytorch 1.3? 

Btw, the only wheels I can in this link: https://pytorch-geometric.com/whl are for pytorch 1.4.

**Comment by rusty1s** [comment]
There are no wheels for PyTorch 1.3 since those were just introduced lately. If you want to install PyG with PyTorch 1.3 you need to install from source:
* `torch-scatter==1.4.0`
* `torch-sparse==0.4.3`
* `torch-cluster==1.4.5`
* `torch-spline-conv==1.1.1`

**Comment by HarveyYan** [comment]
Great thanks!
