### ISSUE TITLE
Installation guidelines for CUDA 10.2?

### ISSUE THREAD

**Issue by chi0tzp** [rusty1s/pytorch_geometric#1053]
Based on your [installation guidelines](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html), CUDA is supported up to version 10.1. 

**Is there any chance that we can also use CUDA 10.2?**

In other words, is there any way of installing the required packages (`torch-scatter` etc) without specifying the version of CUDA? That is, previously, you had a bit different installation guidelines (e.g., `pip install --verbose --no-cache-dir torch-scatter`), which worked just fine with CUDA 10.2. I changed to anaconda so I can use CUDA 10.1 but I had problems with DataParallel (it seems that PyTorch <=1.4.0-3 has problems with that) -- In any case, I'd like to anaconda when possible.

Thanks for your time.

**Comment by rusty1s** [comment]
You can still use `pip install torch-scatter` to manually build the extensions. The reason we do not support CUDA10.2 is that PyTorch does not provide any installations for it.

**Comment by chi0tzp** [comment]
@rusty1s thanks for the clarification!
