### ISSUE TITLE
RuntimeError: Invalid index in scatterAdd at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721

### ISSUE THREAD

**Issue by isjakewong** [rusty1s/pytorch_geometric#1063]
## ❓ Questions & Help
![image](https://user-images.githubusercontent.com/39873026/77523935-7d690700-6ec1-11ea-9e39-e1e293f0442c.png)
I have checked my dataset which has features and edges as gcn's inputs like this:
![image](https://user-images.githubusercontent.com/39873026/77524285-0b44f200-6ec2-11ea-805f-e3de1f97659f.png)
I don't understand how to solve this problem. Thanks for your reply.

**Comment by rusty1s** [comment]
Can you show me a code snippet to reproduce this?

**Comment by isjakewong** [comment]
Sorry for the bothering. I have checked my datasets. ,This error happens for I input a batch of graphs and some of them miss edges. Thanks for your reply.
