### ISSUE TITLE
nn\conv\message_passing.py: Required parameter edge_index is empty

### ISSUE THREAD

**Issue by jlmeunier** [rusty1s/pytorch_geometric#1064]
## 🐛 Bug

in the propagate method nn\conv\message_passing.py, the call to __collect__ on line 250 does not create a key 'edge_index', which the method __distribute__ requires.

Hope it helps in some way. I'm ready to test any potential fix, since I cannot share my code.

Thanks
JL

## To Reproduce
Unfortunately, I cannot share my code. Sorry about that.

  File "c:\Local\meunier\git\DocumentUnderstanding\TranskribusDU\gcn\pyg\convolutions.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_attr=edge_attr)
  File "C:\Anaconda3_pytorch\lib\site-packages\torch_geometric-1.4.3-py3.7.egg\torch_geometric\nn\conv\message_passing.py", line 262, in propagate
  File "C:\Anaconda3_pytorch\lib\site-packages\torch_geometric-1.4.3-py3.7.egg\torch_geometric\nn\conv\message_passing.py", line 185, in __distribute__
TypeError: Required parameter edge_index is empty.
## Expected behavior

Since edge_index  is provided to propagate, I expected (hoped) things to flow nicely. :)

## Environment

* OS: win10, Anaconda
* Python version: Python 3.7.3
* PyTorch version: 1.4.0
* CUDA/cuDNN version: cudatoolkit               10.1.243
* GCC version: 
* Any other relevant information:
I've seen the same problem with 1.4.3 and the commit cddd167ca54f7158dffdfeb874aea947e90b0657 (Thu Mar 26 12:48:04 2020 +0100)

## Additional context
torch 1.4.0
torch_scatter 2.0.4
torch_sparse 0.6.1
torch_cluster 1.5.3
torch_spline_conv 1.2.0

**Comment by rusty1s** [comment]
Yes, this was a minor change. You can instead reference `edge_index_i` and `edge_index_j` indices.

**Comment by jlmeunier** [comment]
Not sure to understand the answer: 
- the caller is required to pass edge_index, as I understand it
- then it is the "internal business" of the propagate method that fails.
But feel free to close this issue, I can move back to a previous version where my code should work. And later on, I'll get back to the latest version.
Thanks for the answer!

**Comment by rusty1s** [comment]
Well, I can always add this functionality back in, but I thought it would be more intuitive to remove it since source and target indices depend on the `flow` property. If you want your old behaviour back, you can always do:
```python
def message(self, edge_index_i, edge_index_j):
    edge_index = torch.stack([edge_index_j, edge_index_i], dim=0)
```

**Comment by jlmeunier** [comment]
ok, thanks!
let's close this then.
JL
