### ISSUE TITLE
Strange behavior of `NeighborSampler`

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [rusty1s/pytorch_geometric#1072]
Here is the code that produces result that I don't understand at all:
https://gist.github.com/WeirdKeksButtonK/d6c4436f5fdaa19def5feda346742c16

By the following line:
```python
sampler = NeighborSampler(data, size=1.0, num_hops=1, batch_size=2, bipartite=False)
```
I mean "Choose two random nodes (batch_size=2), add all their neighbors to the subgraph (by size=1.0 I mean 100%) and stop (num_hops=1)". In other words, I expect `subgraph.b_id` to equal `[0, 1]` (because shuffle=False) and `subgraph.n_id` to equal `[0, 1, 2, 3]` (because (1, 2) are neighbors of 0 and (2, 3) are neighbors of 1).

However, the result is so far from my expectations that I think I completely misunderstand the algorithm :) What is the correct interpretation of how `NeighborSampler` works?

torch==1.4.0              
torch-cluster==1.5.3              
torch-geometric==1.4.3              
torch-scatter==2.0.4              
torch-sparse==0.6.1              
torch-spline-conv==1.2.0
numpy==1.18.1

**Comment by rusty1s** [comment]
That looks correct to me. Note that `n_id` collects all edges that point to these nodes (that is the usual message passing flow). If you want the behaviour you described, pass `flow='target_to_source'` to the sampler class.

**Comment by WeirdKeksButtonK** [comment]
Oh, I see, thank you for the answer!
