### ISSUE TITLE
Problems with cluster vector in max_pool

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1078]
## ❓ Questions & Help

Inside the forward method of a network architecture, 
I would like to use [max_pool](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool/max_pool.html#max_pool). 
According to that [issue](https://github.com/rusty1s/pytorch_geometric/issues/758), I have written my code like that: 

```
def forward(self, data):
        mat = to_dense_adj(edge_index).squeeze()
        n_components, labels = connected_components(csgraph=mat, directed=False)

        tensorLables = torch.from_numpy(labels)
        data = max_pool(cluster=tensorLables, data=data)

        x1 = self.conv1(data.pos, data.edge_index)

        return x1

```

Labels maps each node, to a component (based on connectivity). It is a 1-dimensional array, that contains the exact same number of values as the graph inside data contains nodes.
Example:` labels = [0 0 0 0 1 1 1 1 2 2 2 (...)]`
Note, that for the connected components I have used the implementation of `scipi.sparse.csgraph.connected_components`.

if I pass `cluster=labels`, then I get the following error message: 
`TypeError: _unique2(): argument 'input' (position 1) must be Tensor, not numpy.ndarray`

I I convert the numpy array into a pytorch tensor (tensorLables) then I receive the following error message: 
```
RuntimeError: scatter_max() Expected a value of type 'Tensor' for argument 'src' but instead found type 'NoneType'.
Position: 0
Value: None
Declaration: scatter_max(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> ((Tensor, Tensor))
Cast error details: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'at::Tensor'
```
If I convert the lables array into a list by `labels = list(labels)` I receive the following error message (your example in the linked issue has comma-seperated items. That is the reason why I have tried out this): 
`TypeError: expected np.ndarray (got list)`

Can you explain me, what I do wrong with the cluster vector here?

Thank you in advance!

**Comment by rusty1s** [comment]
The second approach is the correct one. Are you sure `data.x` is set?

**Comment by evakrowarska** [comment]
`data.x` was `None`! Thank you :)
