### ISSUE TITLE
Undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by jun0wanan** [rusty1s/pytorch_geometric#1080]
## Environment

* OS:18.4
* Python version: 3.6
* PyTorch version:1.4
* CUDA/cuDNN version:10.0
* GCC version:7.4
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip wheel
* Any other relevant information:

_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py36_1  
cffi                      1.14.0           py36h2e261b9_0  
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
googledrivedownloader     0.4                      pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.9                      pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
intel-openmp              2020.0                      166  
isodate                   0.6.0                    pypi_0    pypi
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
llvmlite                  0.31.0                   pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2020.0                      166  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
ncurses                   6.2                  he6710b0_0  
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py36hfd86e86_0  
numba                     0.48.0                   pypi_0    pypi
numpy                     1.18.1           py36h4f9e942_0  
numpy-base                1.18.1           py36hde5b4d6_1  
olefile                   0.46                     py36_0  
openssl                   1.1.1e               h7b6447c_0  
pandas                    1.0.3                    pypi_0    pypi
pillow                    7.0.0            py36hb39fc2d_0  
pip                       20.0.2                   py36_1  
plyfile                   0.7.2                    pypi_0    pypi
pycparser                 2.20                       py_0  
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.6.10               hcf32534_1  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.4.0           cuda100py36h75a84eb_0  
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
rdflib                    4.2.2                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.1.1                   py36_0  
six                       1.14.0                   py36_0  
sqlite                    3.31.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torch-cluster             1.5.3                    pypi_0    pypi
torch-geometric           1.4.3                    pypi_0    pypi
torch-scatter             2.0.4                    pypi_0    pypi
torch-sparse              0.6.1                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchvision               0.2.1                    py36_0  
urllib3                   1.25.8                   pypi_0    pypi
wheel                     0.34.2                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ 1 ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

my problem like https://github.com/rusty1s/pytorch_geometric/issues/999

  File "main.py", line 2, in <module>
    from torch_geometric.datasets import TUDataset
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_sparse/__init__.py", line 23, in <module>
    raise OSError(e)
OSError: /home/xiejunlin/anaconda3/envs/graph/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

can you have any idea?

**Comment by jun0wanan** [comment]
I have install it for 4 days ... 😭😭  who can help me ?

**Comment by dongweidongwei** [comment]
I encounter this problem too. The installation of "pytorch_geometric" is a terrible, awful, and horrible experience ever!!!

**Comment by jun0wanan** [comment]
> I encounter this problem too. The installation of "pytorch_geometric" is a terrible, awful, and horrible experience ever!!!

Maybe because we are newer ....  Do you know if we only can use pytorch==1.4 >< ? I want to use pytorch=1.2......

**Comment by rusty1s** [comment]
If you want to use PyTorch 1.2, you can install older versions of the extensions, *e.g.*:
* `torch-scatter==1.4.0`
* `torch-sparse==0.4.3`
* `torch-spline-conv==1.1.1`
* `torch-cluster==1.4.5`
The latest version require `torch==1.4.0` though.

The error `undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs` usually indicates that you have multiple PyTorch versions installed.

For a better debugging experience, you can install the extensions from source, and post any errors in the installation log.

**Comment by dongweidongwei** [comment]
> > I encounter this problem too. The installation of "pytorch_geometric" is a terrible, awful, and horrible experience ever!!!
> 
> Maybe because we are newer .... Do you know if we only can use pytorch==1.4 >< ? I want to use pytorch=1.2......

I think that an excellent project should have a wonderful usability. Because we focus on our work efficiently via an easy-to-use software. However, compared with "DGL", the usability of "pytorch_geometric" is very terrible. According to the author, multiple versions of CUDA or pytorch coexisting in your OS may result in this problem, but I have only CUDA 10,1 and pytorch 1.4. I have no idea about this problem!

**Comment by rusty1s** [comment]
Well, I have tested all wheels on multiple platforms and they all ran fine, so I do not know exactly what the problem here is. You are invited to dig into this issue and find out why PyTorch cannot load the `_version.so` on your OS. 

 Furthermore, note that you do not need to use the wheels, you can always install from source.

**Comment by jun0wanan** [comment]
> Well, I have tested all wheels on multiple platforms and they all ran fine, so I do not know exactly what the problem here is. You are invited to dig into this issue and find out why PyTorch cannot load the `_version.so` on your OS.
> 
> Furthermore, note that you do not need to use the wheels, you can always install from source.

Thank your reply~~ This is a problem . Because I also have no other pytorch,and I only install one. Maybe can you put a  virtual environment to give others .. I think it will be fine to many newers

**Comment by jun0wanan** [comment]
> > > I encounter this problem too. The installation of "pytorch_geometric" is a terrible, awful, and horrible experience ever!!!
> > 
> > 
> > Maybe because we are newer .... Do you know if we only can use pytorch==1.4 >< ? I want to use pytorch=1.2......
> 
> I think that an excellent project should have a wonderful usability. Because we focus on our work efficiently via an easy-to-use software. However, compared with "DGL", the usability of "pytorch_geometric" is very terrible. According to the author, multiple versions of CUDA or pytorch coexisting in your OS may result in this problem, but I have only CUDA 10,1 and pytorch 1.4. I have no idea about this problem!

hello? You can download the environment to install it in cuda10.1... 
  https://pan.baidu.com/s/1TtMvo9haPegmtesECAmSCg        : vijp

then  use conda create -f  ****.yaml then you can use it
ref: https://blog.csdn.net/ft_sunshine/article/details/92215164

**Comment by dongweidongwei** [comment]
I have solved this problem. The reason is that: do not install pytorch via anaconda-navigator ! It will install both cpu and gpu versions, even though you only select the pytorch. You can download the specific version of the pytorch from: 

https://download.pytorch.org/whl/torch_stable.html, 

and this problem will be solved. All dependent packages are listed:
cu101/torch-1.4.0-cp38-cp38-linux_x86_64.whl
cu101/torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
torch_cluster-1.5.3+cu101-cp38-cp38-linux_x86_64.whl
torch_scatter-2.0.4+cu101-cp38-cp38-linux_x86_64.whl
torch_sparse-0.6.1+cu101-cp38-cp38-linux_x86_64.whl
torch_spline_conv-1.2.0+cu101-cp38-cp38-linux_x86_64.whl

The author is right! Multi-versions of pytorch (cpu and gpu) result in this problem! I am sorry about my comments in yesterday. Pytorch geometric is an excellent project !!!

**Comment by dongweidongwei** [comment]
> > > > I encounter this problem too. The installation of "pytorch_geometric" is a terrible, awful, and horrible experience ever!!!
> > > 
> > > 
> > > Maybe because we are newer .... Do you know if we only can use pytorch==1.4 >< ? I want to use pytorch=1.2......
> > 
> > 
> > I think that an excellent project should have a wonderful usability. Because we focus on our work efficiently via an easy-to-use software. However, compared with "DGL", the usability of "pytorch_geometric" is very terrible. According to the author, multiple versions of CUDA or pytorch coexisting in your OS may result in this problem, but I have only CUDA 10,1 and pytorch 1.4. I have no idea about this problem!
> 
> hello? You can download the environment to install it in cuda10.1...
> https://pan.baidu.com/s/1TtMvo9haPegmtesECAmSCg : vijp
> 
> then use conda create -f ****.yaml then you can use it
> ref: https://blog.csdn.net/ft_sunshine/article/details/92215164

I have solved this problem. The reason is that: do not install pytorch via anaconda-navigator ! It will install both cpu and gpu versions, even though you only select the pytorch. You can download the specific version of the pytorch from:

https://download.pytorch.org/whl/torch_stable.html,

and this problem will be solved. All dependent packages are listed:
cu101/torch-1.4.0-cp38-cp38-linux_x86_64.whl
cu101/torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
torch_cluster-1.5.3+cu101-cp38-cp38-linux_x86_64.whl
torch_scatter-2.0.4+cu101-cp38-cp38-linux_x86_64.whl
torch_sparse-0.6.1+cu101-cp38-cp38-linux_x86_64.whl
torch_spline_conv-1.2.0+cu101-cp38-cp38-linux_x86_64.whl

The author is right! Multi-versions of pytorch (cpu and gpu) result in this problem! I am sorry about my comments in yesterday. Pytorch geometric is an excellent project !!!

**Comment by dongweidongwei** [comment]
> Well, I have tested all wheels on multiple platforms and they all ran fine, so I do not know exactly what the problem here is. You are invited to dig into this issue and find out why PyTorch cannot load the `_version.so` on your OS.
> 
> Furthermore, note that you do not need to use the wheels, you can always install from source.

I have solved this problem. The reason is that: do not install pytorch via anaconda-navigator ! It will install both cpu and gpu versions, even though you only select the pytorch. You can download the specific version of the pytorch from:

https://download.pytorch.org/whl/torch_stable.html,

and this problem will be solved. All dependent packages are listed:
cu101/torch-1.4.0-cp38-cp38-linux_x86_64.whl
cu101/torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
torch_cluster-1.5.3+cu101-cp38-cp38-linux_x86_64.whl
torch_scatter-2.0.4+cu101-cp38-cp38-linux_x86_64.whl
torch_sparse-0.6.1+cu101-cp38-cp38-linux_x86_64.whl
torch_spline_conv-1.2.0+cu101-cp38-cp38-linux_x86_64.whl

You are right! Multi-versions of pytorch (cpu and gpu) result in this problem! I am sorry about my comments in yesterday. Pytorch geometric is an excellent project !!!

**Comment by jun0wanan** [comment]
> > 好吧，我已经在多个平台上测试了所有车轮，并且它们都运行良好，所以我不知道到底是什么问题。邀请您深入研究此问题，并找出为什么PyTorch无法`_version.so`在您的OS上加载。
> > 此外，请注意，您无需使用轮子，可以始终从源代码安装。
> 
> 我已经解决了这个问题。原因是：不要通过anaconda-navigator安装pytorch！即使您仅选择pytorch，它也会安装cpu和gpu版本。您可以从以下位置下载特定版本的pytorch：
> 
> https://download.pytorch.org/whl/torch_stable.html，
> 
> 并且这个问题将得到解决。列出了所有相关软件包：
> cu101 / torch-1.4.0-cp38-cp38-linux_x86_64.whl
> cu101 / torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
> torch_cluster-1.5.3 + cu101-cp38-cp38-cp38-linux_x86_64。 whl
> torch_scatter-2.0.4 + cu101-cp38-cp38-linux_x86_64.whl
> torch_sparse-0.6.1 + cu101-cp38-cp38-linux_x86_64.whl
> torch_spline_conv-1.2.0 + cu101-cp38-cp38-linux_x86_64.whl
> 
> 你是对的！pytorch的多版本（cpu和gpu）导致此问题！我对昨天的评论感到抱歉。Pytorch Geometric是一个出色的项目！

So we are newer ~~~ But I think if you have a friend who have installed it , you can ask him to copy the environment to you.Because it is faster .... Anyway ,thanks~~~~~~🙂

**Comment by dongweidongwei** [comment]
> > > 好吧，我已经在多个平台上测试了所有车轮，并且它们都运行良好，所以我不知道到底是什么问题。邀请您深入研究此问题，并找出为什么PyTorch无法`_version.so`在您的OS上加载。
> > > 此外，请注意，您无需使用轮子，可以始终从源代码安装。
> > 
> > 
> > 我已经解决了这个问题。原因是：不要通过anaconda-navigator安装pytorch！即使您仅选择pytorch，它也会安装cpu和gpu版本。您可以从以下位置下载特定版本的pytorch：
> > [https://download.pytorch.org/whl/torch_stable.html，](https://download.pytorch.org/whl/torch_stable.html%EF%BC%8C)
> > 并且这个问题将得到解决。列出了所有相关软件包：
> > cu101 / torch-1.4.0-cp38-cp38-linux_x86_64.whl
> > cu101 / torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
> > torch_cluster-1.5.3 + cu101-cp38-cp38-cp38-linux_x86_64。 whl
> > torch_scatter-2.0.4 + cu101-cp38-cp38-linux_x86_64.whl
> > torch_sparse-0.6.1 + cu101-cp38-cp38-linux_x86_64.whl
> > torch_spline_conv-1.2.0 + cu101-cp38-cp38-linux_x86_64.whl
> > 你是对的！pytorch的多版本（cpu和gpu）导致此问题！我对昨天的评论感到抱歉。Pytorch Geometric是一个出色的项目！
> 
> So we are newer ~~~ But I think if you have a friend who have installed it , you can ask him to copy the environment to you.Because it is faster .... Anyway ,thanks~~~~~~🙂

Do you mean that a "newer"  is a green hand? I am not a green hand, otherwise, I will not solve this problem independently. I just focus on my work attentively, but this problem makes me waste a lot of time.

**Comment by Ashappyboy** [comment]
on windows no gpu 
>>> import torch_geometric
Traceback (most recent call last):
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_sparse\__init__.py", line 15, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch\_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "G:\anaconda\envs\python3.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "G:\anaconda\envs\python3.6\lib\site-packages\torch_sparse\__init__.py", line 23, in <module>
    raise OSError(e)
OSError: [WinError 126] 找不到指定的模块。

**Comment by keshavd** [comment]
> > > 好吧，我已经在多个平台上测试了所有车轮，并且它们都运行良好，所以我不知道到底是什么问题。邀请您深入研究此问题，并找出为什么PyTorch无法`_version.so`在您的OS上加载。
> > > 此外，请注意，您无需使用轮子，可以始终从源代码安装。
> > 
> > 
> > 我已经解决了这个问题。原因是：不要通过anaconda-navigator安装pytorch！即使您仅选择pytorch，它也会安装cpu和gpu版本。您可以从以下位置下载特定版本的pytorch：
> > [https://download.pytorch.org/whl/torch_stable.html，](https://download.pytorch.org/whl/torch_stable.html%EF%BC%8C)
> > 并且这个问题将得到解决。列出了所有相关软件包：
> > cu101 / torch-1.4.0-cp38-cp38-linux_x86_64.whl
> > cu101 / torchvision-0.5.0-cp38-cp38-linux_x86_64.whl
> > torch_cluster-1.5.3 + cu101-cp38-cp38-cp38-linux_x86_64。 whl
> > torch_scatter-2.0.4 + cu101-cp38-cp38-linux_x86_64.whl
> > torch_sparse-0.6.1 + cu101-cp38-cp38-linux_x86_64.whl
> > torch_spline_conv-1.2.0 + cu101-cp38-cp38-linux_x86_64.whl
> > 你是对的！pytorch的多版本（cpu和gpu）导致此问题！我对昨天的评论感到抱歉。Pytorch Geometric是一个出色的项目！
> 
> So we are newer ~~~ But I think if you have a friend who have installed it , you can ask him to copy the environment to you.Because it is faster .... Anyway ,thanks~~~~~~🙂

This thread pops up on when googling the error. Just going to add my solution for this with the latest conda formula. I had to remove torch via pip and reinstall it. 

```
conda create -n pyg
conda install pyg -c pyg -c conda-forge
pip uninstall torch
pip install torch torchvision torchaudio
```

**Comment by G12311231** [comment]
> whltorch_spline_conv

But when you use the command “pip3 install pytorch_lightning”, the torch will be automatically upgraded from 1.11.0 to 2.3.0. How do you handle this? I would like to know what version of pytorch_lightning you installed.

**Comment by akihironitta** [comment]
@G12311231 I recommend referring to their compatibility matrix: https://lightning.ai/docs/pytorch/stable/versioning.html#compatibility-matrix
