### ISSUE TITLE
AttributeError: module 'torch_geometric.utils' has no attribute 'k_hop_subgraph'

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1086]
## ❓ Questions & Help

I would like to use the method [k_hop_subgraph](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/subgraph.html#k_hop_subgraph).

However, If I import `import torch_geometric.utils`:

and call it by: 
`substet, edge_index, mask = torch_geometric.utils.k_hop_subgraph(0, 1, data.edge_index)`

I get the following error: 

`AttributeError: module 'torch_geometric.utils' has no attribute 'k_hop_subgraph'`

I thought, that perhaps I am using an old version of PyTorch Geometric. 
That is why I uninstalled it, cloned the repository and reinstalled it. 
But the issue keeps appearing. 

I am using version 1.4.3 of PyTorch Geometric. 

What could be my issue or how can I import the function correctly?

Thank you in advance.

**Comment by rusty1s** [comment]
This function is currently only available on master. You should ensure that all PyG versions are removed by repeatedly calling `pip uninstall torch-geometric` and try again.

**Comment by evakrowarska** [comment]
Works fine, thanks. I did not now, that a package can still remain, even after uninstall.
