### ISSUE TITLE
Data Class source code 404

### ISSUE THREAD

**Issue by Raven013** [rusty1s/pytorch_geometric#109]
As mentioned in the title. Thanks for your effort.

**Comment by RobinFrcd** [comment]
Hi,
Could you give more details please ?

**Comment by rusty1s** [comment]
The [source] link in the documentation of `torch_geometric.data` fails with a 404 error. This is because we ignore `data/` dirs in `.gitignore`. Will fix is ASAP.

**Comment by rusty1s** [comment]
Fixed!
