### ISSUE TITLE
Training on multiple datasets

### ISSUE THREAD

**Issue by ferdisvea** [rusty1s/pytorch_geometric#1093]
## ❓ Questions & Help

Hi, I was not able to find a clear answer to this; I want to use multiple datasets to a train GNNs.  I am using the TUDataset class to import and preprocess my own datasets (that are in the TUDortmund format). Should I merge the datasets before the training into a combined dataset? And how do I merge them?
Or should I use Dataloader with a list over all my dataset (Dataloader(data_list)) during the training of the model? I assuming the latter is the best way to do it for my purpose, since I have a lot of different datasets and I want to combine them in different combinations. 
Thanks!

**Comment by rusty1s** [comment]
What about [`ChainDataset`](https://pytorch.org/docs/stable/data.html?highlight=dataset#torch.utils.data.ChainDataset)?

**Comment by ferdisvea** [comment]
Yeah I guess that could work :)
But in theory if I have two datasets loaded in with the TUDataset class. What is a easy way to combine them into one set of graphs?

**Comment by rusty1s** [comment]
I guess you can always do something like `list(dataset1) + list(dataset2)`.

**Comment by ferdisvea** [comment]
Ah cool. And if you want to transform that sum of list into a geometric Data object?

**Comment by ferdisvea** [comment]
Used collate on the  list(dataset1) + list(dataset2) to get it into a single torch_geometric.data.Data objet, but how do I go from here to get the merged dataset into the same format as what TUDataset returns?

**Comment by rusty1s** [comment]
I don't think I understand. The `TUDataset` is basically just a list of data objects. What functionality are you missing?

**Comment by ferdisvea** [comment]
Sorry for not being clear. I basically want to merge multiple datasets e.g.:
Dataset1(500) and Dataset2(400) into Dataset3(900). With the all same attributes as in TUDataset like Dataset3.num_nodes or Dataset3.data

**Comment by rusty1s** [comment]
Well, I don't know if this particular useful, but you can always do something like this:
```python
from torch_geometric.datasets import TUDataset

dataset1 = TUDataset('/tmp/ENZYMES', 'ENZYMES')
dataset1.data.x = None
print(dataset1)
print(dataset1[0])

dataset2 = TUDataset('/tmp/MUTAG', 'MUTAG')
dataset2.data.x = dataset2.data.edge_attr = None
print(dataset2)
print(dataset2[0])

class MergedTUDataset(TUDataset):
    def __init__(self, dataset1, dataset2, transform=None):
        super(TUDataset, self).__init__(None, transform)
        self.name = f'{dataset1.name}+{dataset2.name}'
        self.data, self.slices = self.collate(list(dataset1) + list(dataset2))

dataset3 = MergedTUDataset(dataset1, dataset2)
print(dataset3)
print(dataset3[0])

**Comment by ferdisvea** [comment]
Perfect! Thats exactly what I am looking for :D Thank you so much
