### ISSUE TITLE
GNNExplainer import error

### ISSUE THREAD

**Issue by enmce** [rusty1s/pytorch_geometric#1094]
## 🐛 Bug

Hello!
When i try to run [example]( https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gnn_explainer.py) of GNNExplainer given in docs, it produces error on import. I installed current version of pytorch geometric from master branch of this repo.

## To Reproduce

1.  Install latest version of library: pip install git+https://github.com/rusty1s/pytorch_geometric.git@master
2. Run example code as in https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gnn_explainer.py
Produces following error on from torch_geometric.nn import GCNConv, GNNExplainer line:
```
ImportError                               Traceback (most recent call last)
<ipython-input-13-80d130559e1e> in <module>
      5 from torch_geometric.datasets import Planetoid
      6 import torch_geometric.transforms as T
----> 7 from torch_geometric.nn import GCNConv, GNNExplainer
      8 from torch.nn import Sequential, Linear
      9 

ImportError: cannot import name 'GNNExplainer' from 'torch_geometric.nn' (/home/user/user_python3/lib/python3.7/site-packages/torch_geometric/nn/__init__.py)
```

## Expected behavior

Example code runs completely. 

## Environment

* OS: Ubuntu 18.04.3 LTS
* Python version: 3.7.5
* PyTorch version: 1.4.0
* CUDA version: CUDA 10.1
* GCC version: 7.4.0
* PyTorch Geometric version: 1.4.3

## Additional context
I found that GNNExplainer is in torch_geometric.nn.models.gnn_explainer, but then i try to import it from there, i get following error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-14-e19b74962d4b> in <module>
      7 from torch_geometric.nn import GCNConv#, GNNExplainer
      8 from torch.nn import Sequential, Linear
----> 9 from torch_geometric.nn.models.gnn_explainer import GNNExplainer
     10 
     11 dataset = 'Cora'

~/user_python3/lib/python3.7/site-packages/torch_geometric/nn/models/gnn_explainer.py in <module>
      7 from torch_geometric.nn import MessagePassing
      8 from torch_geometric.data import Data
----> 9 from torch_geometric.utils import k_hop_subgraph, to_networkx
     10 
     11 EPS = 1e-15

ImportError: cannot import name 'k_hop_subgraph' from 'torch_geometric.utils' (/home/vsvekolkin/user_python3/lib/python3.7/site-packages/torch_geometric/utils/__init__.py)
```

**Comment by rusty1s** [comment]
You need PyG from master and ensure that there do not exist any old versions of PyG, e.g., by repeatedly remove them via `pip uninstall torch-geometric`.

**Comment by enmce** [comment]
Tested on new venv, and it worked, i will try to elucidate which packages where specifically incompatible in original environment.

**Comment by enmce** [comment]
> You need PyG from master and ensure that there do not exist any old versions of PyG, e.g., by repeatedly remove them via `pip uninstall torch-geometric`.

Apparently, it helped, all is loading after i restart jupyter kernel.

**Comment by mlscmoulika** [comment]
For me changing the import statement to,
` from torch_geometric.explain.algorithm.gnn_explainer import GNNExplainer `
worked
