### ISSUE TITLE
ModelNet dataset only displays file names for ModelNet10 - not ModelNet40

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1098]
## 🚀 Feature

If I am not wrong the [ModelNet datase](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/modelnet.py)t only contains the raw file names for ModelNet10. If I change to ModelNet40 then these do not change. 
Looking at the code, there is a hard coded array with the file names of ModelNet10.

Question: Do the Id's of data.y in a network's forward pass correspond to a list sorted in ascending alphabetic order of the raw file names? So zero-based airplane would be with id 0 in ModelNet40 ?

Thank you in advance.

**Comment by rusty1s** [comment]
The order of the data objects is specified [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/modelnet.py#L92). I think we may want to add the filename to the `data` object though.

**Comment by evakrowarska** [comment]
Thanks for your help.
