### ISSUE TITLE
[Docs] Page not found for _modules

### ISSUE THREAD

**Issue by vfdev-5** [rusty1s/pytorch_geometric#11]
Hi,

If I click on [source] near [Data docs](https://rusty1s.github.io/pytorch_geometric/build/html/modules/data.html#torch_geometric.data.Data) than redirected page is not found. 
Maybe there is an issue with documentation generation with Sphinx when it can not properly import the current package.

**Comment by rusty1s** [comment]
I will look into this. Thanks!

**Comment by rusty1s** [comment]
Fixed!
