### ISSUE TITLE
About the example about Jumping Knowledge

### ISSUE THREAD

**Issue by xiangzhang1015** [rusty1s/pytorch_geometric#1102]
## ❓ Questions & Help

Hi Matthias,

I am trying to use Jumpling knowledge (torch_geometric.nn.models.jumping_knowledge) by modifying the [gcn example](https://github.com/rusty1s/pytorch_geometric/blob/926574f33dbce8d5089717e931ba85e6b634e55f/examples/gcn.py#L32) as setting:
```
self.conv1 = JumpingKnowledge(mode='lstm', channels=16, num_layers= 1 )
self.conv2 = JumpingKnowledge(mode='lstm', channels=dataset.num_classes, num_layers=1)
```

but got a series of errors. 

Could you please add a coding example showing how to call JumplingKnowledge?

Thank you so much!

**Comment by rusty1s** [comment]
You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/gin.py#L54).

**Comment by xiangzhang1015** [comment]
Got it. Thank you so much.
