### ISSUE TITLE
Wrong normalization of TAGConv

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1104]
Hello,
I see that in TAGConv you are calling GCNConv.norm to normalize the weights. However, GCNConv.norm adds self-loop to normalize the weights while in the formula you have written for TAGConv in the documentation there is no self-loop. Therefore, either the documentation or the code is wrong.  I also noticed that you have already written a norm function for TAGConv, but you don't call it in TAGConv.

**Comment by rusty1s** [comment]
Oh, you are right. That is a bug. Fixed in master.
