### ISSUE TITLE
Dockerfile miniconda download link broken

### ISSUE THREAD

**Issue by Laksh1997** [rusty1s/pytorch_geometric#1105]
## 🐛 Bug

Just tried to build the Dockerfile and found that the miniconda download link was broken.

## To Reproduce

Try building the Dockerfile

## Expected behavior

Should build

## To Fix

Simply replace 

```RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh \```

to 

```RUN curl -so ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \ ```

on line 93 of the Dockerfile.

## Another comment:

Should we replace the pip install steps with the new installation instructions? Namely replacing:

```pip install --verbose --no-cache-dir torch-scatter```

to 

```pip install torch-scatter==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.4.0.html```

and so on ...

**Comment by rusty1s** [comment]
Sounds good, do you want to submit a PR for this?

**Comment by rusty1s** [comment]
Fixed in master.
