### ISSUE TITLE
Cuda error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by neolei** [rusty1s/pytorch_geometric#1106]
## 📚 Installation

Version 1.3 no longer supporting Tesla K40m？ K40m has a compute capability of 3.5, which I believe we have dropped support of (https://developer.nvidia.com/cuda-gpus#compute). PyG needs pytorch 1.4 version. DOWNGRADED pytorch 1.2 version will be OK

**Comment by rusty1s** [comment]
You can use older versions of the extensions, *e.g.*:
* `torch-scatter==1.4.0`
* `torch-sparse==0.4.3`
* `torch-cluster==1.4.5`
They should work fine for GPUs with older compute capabilities.

**Comment by neolei** [comment]
like this？
` pip install torch-scatter==1.4.0+${CUDA}`
@rusty1s source build for PyTorch 1.4 may be one of the solutions，and Reminding GPU capabilities in install documentation should be better.
Thanks!
