### ISSUE TITLE
How to relate vertices after max_pool with vertices of the original cluster?

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1107]
## ❓ Questions & Help

During preprocessing, for every graph I have added a cluster labels, such that every vertex is assigned to a connected component of the graph. I did that with Scipy. 
Now, I am using [max_pool](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool/max_pool.html). Since Scipy assigns connected component graph id's for each graph seperately, I have the problem, that max_pool merges graphs together.
This issue arises, different graphs may have recurring id's within the cluster. E. g. Id 0 occurs in every graph, since every graph consists of at least one component. 

**Question**: Is that behavior intended?

An easy solution is to do the connected component calculation during the forward pass, calculating connected components for all graphs simultaneously. But doing that for every forward pass for the whole batch always leads my current network architecture into memory issues. So, I would try to avoid that. 

**Another question**: 
Are the graphs inside the batch in the same order after max_pool, as they were before max_pool? Because inside max_pool, there is consecutive_cluster called, which returns a variable perm. That reminds me a permutation. Unfortunately, I am not able to reverse-engineer the purpose of that method. 

I do intend to use something like data.to_data_list() to obtain single graphs. I would like to relate data of original graphs with graphs after max_pool. 

**Note**: Especially I would like to do some operations on the graph that results out of max_pool and then add the features of each vertex of this graph to all the vertices of the corresponding component of the original graph.

That leads me to the **last question:**
If I have a cluster list like [0,0,0,5,5, 2,2,4]
are the resulting vertices of max_pool finally in the order 0,2,4,5 (assuming that all vertices are averaged per component and labelled with the cluster label)? Or is there a different order?
How can I relate the vertices of the original component to the vertices after max_pool?

Sorry for the long post. But I have been trying to reverse-engineer you code for many hours already without getting a confident result. 

Thank you in advance.

**Comment by rusty1s** [comment]
Hi and sorry for the delay.
The call `consecutive_cluster` converts cluster ids to consecutive values (where the ordering stays the same), *e.g.*, `[0, 0, 0, 5, 5, 2, 2, 4]` converts to `[0, 0, 0, 3, 3, 1, 1, 2]`. In a mini-batch fashion, those cluster ids needs to be incremented for each additional graph in your mini-batch, *e.g.*, [[0, 0, 3, 2], [0, 5, 5, 2]]` should convert to `[[0, 0, 3, 2], [4, 9, 9, 6]]` before the consecutive call takes place. This can be achieved by overriding the `__inc__` method of the `Data`class as described [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html):
```python
class MyData(torch_geometric.data.Data):
    def __inc__(self, key, item):
        if key == 'cluster_id':
            return item.max().item() + 1
        return super(MyData, self).__inc__(key, item)
```

**Comment by evakrowarska** [comment]
Thank you for your reply. 

To use it inside my `DataLoader` do I have to write a wrapper-class or something?
Or do I have to copy the `DataLoader` code and create my own one importing `MyData`?

At the moment I am trying to create `MyDataLoader`, but I get the error message:
`TypeError: DataLoader found invalid type: <class 'torch_geometric.data.data.Data'>`

**Comment by rusty1s** [comment]
You can use the PyG `DataLoader` class.

**Comment by evakrowarska** [comment]
I am sorry, but I do not understand that. I mean, inside PyG `DataLoader` class there is still the Data object of` torch_geometric.data `used, isn't it? At which point do I incorporate `MyData`?

**Comment by rusty1s** [comment]
You feed `MyData` into it instead of PyG `Data` objects.

**Comment by evakrowarska** [comment]
I do create my `DataLoader` like this: 

```
test_dataset = ModelNet(root=pathManager.getDatasetPath(), name=pathManager.getModelNetDatasetNumber(), train=False,
                            pre_transform=T.NormalizeScale(), transform=T.SamplePoints(args.num_points))

test_loader = DataLoader(
    test_dataset, batch_size=args.test_batch_size, shuffle=False, num_workers=6)
```

So, do I have to modify the `ModelNet` dataset?
I am really sorry, for asking that much.

**Comment by evakrowarska** [comment]
Has anyone an idea on that?
Maybe that answer is too obvious, but I can't get around that, 
where I am supposed plug-in my custom `data` type.

Thanks for help in advance.

**Comment by rusty1s** [comment]
You can write a custom transform that converts your `Data` to `MyData`, *e.g.*:
```python
def convert(data):
    return MyData(x=data.x, ...)
```
