### ISSUE TITLE
why using add_self_loops when normalization is None in get_laplacian.

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1109]
Hello,

Thank you very much for providing this excellent library. Don't you think that it is better to replace add_self_loops with add_remaining_self_loops because in add_remaining_self_loops you already check if a node has a self-loop or not?
For example, in function get_laplacian if a node already has a self-loop, the function adds another self-loop to the node.

**Comment by rusty1s** [comment]
The Laplacian expects a graph without any self-loops. Instead, I added a remove self-loops call before any computation.
