### ISSUE TITLE
Updated geometric shapes

### ISSUE THREAD

**Issue by Yannick-S** [rusty1s/pytorch_geometric#111]
Hi,

Good job on the paper you just released!
I updates the geometric shapes. I added a few and made the names nicer. I wanted to implement a 'only 2d' or 'only 3d' option, but didn't get around doing that. Maybe i'll add a merge request later next week.
Here is the zip for the new objects:
https://github.com/Yannick-S/geometric_shapes

If you want, just exchange the zip with the one on your google drive for everythign to work as beofre.

**Comment by rusty1s** [comment]
Thank you. Will change the url ASAP.

**Comment by rusty1s** [comment]
Done! Thank you :)
