### ISSUE TITLE
Is it possible to make documents downloadable as pdf 

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [rusty1s/pytorch_geometric#1114]
Hello,

I am a big fan of pytorch geometric. Would it be possible to make [documents](https://readthedocs.org/projects/pytorch-geometric/downloads/) downloadable as pdf? I find my self sometimes need to read carefully about many different functions.

Many Thanks!

**Comment by rusty1s** [comment]
We use `sphinx` for creating documentation. All the related code lies in the `docs/` directory. If you know of a way to let sphinx generate PDF instead of HTML, you can generate the docs by yourself :)
