### ISSUE TITLE
Connection to s3.eu-central-1.amazonaws.com timed out. 

### ISSUE THREAD

**Issue by lizitong67** [rusty1s/pytorch_geometric#1116]
## ❓ Questions & Help

I run “pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.4.0.html”
and a warning occured: 

"  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015D5E85BC40>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcpu-cp38-cp38-win_amd64.whl"

what's wrong ?

**Comment by rusty1s** [comment]
Can you access https://pytorch-geometric.com/whl/torch-1.4.0.html and/or https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html in the browser?

**Comment by lizitong67** [comment]
I can access https://pytorch-geometric.com/whl/torch-1.4.0.html 
but  I can NOT access https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html in my browser.

**Comment by rusty1s** [comment]
Mh, that's interesting. Not sure what is causing this. As a workaround, you can install directly using the wheel url, *e.g.*:
```
pip install https://pytorch-geometric.com/whl/torch-1.4.0/torch_cluster-1.5.2%2Bcpu-cp37-cp37m-linux_x86_64.whl
```

**Comment by lizitong67** [comment]
Ok, It works!
Thx!

**Comment by neolei** [comment]
@rusty1s  amazon AWS service may be  inaccessible in China，and not friendly for Chinese users

**Comment by rusty1s** [comment]
Any advice on how to fix that?

**Comment by lizitong67** [comment]
> Any advice on how to fix that?

Not yet，I use a proxy server to access it in China，but it still inaccessible。

But I  can install directly using the wheel

**Comment by rusty1s** [comment]
I changed all links to access `https://pytorch-geometric.com`. Please try again :)

**Comment by lizitong67** [comment]
OK，It works.
Than you!
