### ISSUE TITLE
Metalayer functionality 

### ISSUE THREAD

**Issue by thinkingparticle** [rusty1s/pytorch_geometric#1118]
In the original paper (<a href="https://arxiv.org/abs/1806.01261"> Relational inductive biases, deep learning, and graph networks </a>) authors explain Attributes as "properties that can be encoded as a vector, set, or **even another graph**" . 

With the Metalayer implementation in pytorch_geometric, how can I define my model such that my nodes' attributes are a graph themselves? 

![64543763-06ac5800-d33b-11e9-8774-f8e219e78488](https://user-images.githubusercontent.com/17741554/79052530-5e51cf80-7c4c-11ea-8285-f47873f3bf66.png)

Can you provide an example implementation of attributes of nodes/edges of a graph, where each attribute is a graph?

**Comment by rusty1s** [comment]
The `MetaLayer`  in PyG is kind of restrictive in that sense that  it is limited to node, edge, and global vectors. If you want more specialized modeling, it should be no problem to create something like this by building upon the `MessagePassing` interface. There is no limitation to, e.g., integrate another graph in the computation scheme. However, it is hard for me to imagine a use-case for this, so I cannot give you a concrete example at the moment.
