### ISSUE TITLE
How to install newest torch_geometric  with conda environment?

### ISSUE THREAD

**Issue by asdassZY** [rusty1s/pytorch_geometric#1119]
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by aluo-x** [comment]
```
conda activate base
git clone --recursive https://github.com/rusty1s/pytorch_geometric.git
git clone --recursive https://github.com/rusty1s/pytorch_cluster.git
git clone --recursive https://github.com/rusty1s/pytorch_scatter.git
git clone --recursive https://github.com/rusty1s/pytorch_spline_conv.git
git clone --recursive https://github.com/rusty1s/pytorch_sparse.git
python ./pytorch_sparse/setup.py develop
python ./pytorch_spline_conv/setup.py develop
python ./pytorch_scatter/setup.py develop
python ./pytorch_cluster/setup.py develop
python ./pytorch_geometric/setup.py develop
```
I believe there are is also a dependency called METIS, but it is optional. If you need to satisfy conda dependencies, I usually just write stub meta.yaml in an empty folder with build.sh also doing nothing.

**Comment by rusty1s** [comment]
You can also just use the provided wheels for an easier installation.

**Comment by asdassZY** [comment]
Thank you for your help!
