### ISSUE TITLE
SparseTensor not exist in v0.4.3

### ISSUE THREAD

**Issue by neolei** [rusty1s/pytorch_geometric#1120]
## 🐛 Bug
when using the Spline module, error is
```
File "script.py", line 3, in <module>
    from torch_geometric.data import DataLoader
  File "/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 7, in <module>
    from .cluster import ClusterData, ClusterLoader
  File "/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_geometric/data/cluster.py", line 8, in <module>
    from torch_sparse import SparseTensor, cat
ImportError: cannot import name 'SparseTensor' from 'torch_sparse' (/home/xxx/anaconda3/envs/pyg/lib/python3.7/site-packages/torch_sparse/__init__.py)
```

## Environment

* OS: Linux
* Python version: 3.7
* PyTorch version: 1.2
* CUDA/cuDNN version: 9.2
* GCC version: 7.3
* Any other relevant information: 
```
torch                 1.2.0              
torch-cluster         1.4.5              
torch-geometric       1.4.3              
torch-scatter         1.4.0              
torch-sparse          0.4.3              
torch-spline-conv     1.1.0              
torchvision           0.4.0a0+9232c4a  
```

**Comment by rusty1s** [comment]
You need to either downgrade your torch-geometric to 1.4.0 or upgrade torch-scatter and torch-sparse.

**Comment by neolei** [comment]
It seems that orch-geometric 1.3.2，1.4.0 not exists

**Comment by rusty1s** [comment]
Are you sure? See [here](https://pypi.org/project/torch-geometric/1.3.2/).

**Comment by neolei** [comment]
> You need to either downgrade your torch-geometric to 1.4.0 or upgrade torch-scatter and torch-sparse.
downgrade your torch-geometric to 1.3.2？Thanks

**Comment by rusty1s** [comment]
Yes, sorry. That was a mistake.

**Comment by engrAsmasaattar** [comment]
facing same problem. any solution?

**Comment by rusty1s** [comment]
Which problem do you face exactly? This issue seems to be solved by upgrading torch-sparse or downgrading torch-geometric.

**Comment by engrAsmasaattar** [comment]
ImportError: cannot import name 'SparseTensor' from 'torch_sparse' (/home/xxx/miniconda3/lib/python3.7/site-packages/torch_sparse/__init__.py)

**Comment by rusty1s** [comment]
Well, then you don't have the latest `torch-sparse` installed.

**Comment by engrAsmasaattar** [comment]
torch-geometric           1.4.3                    pypi_0    pypi
torch-scatter             1.4.0            py37hf484d3e_2    ostrokach-forge
torch-sparse              0.4.3            py37hf484d3e_1    ostrokach-forge

**Comment by engrAsmasaattar** [comment]
but the latest version of torch-sparse os 0.4.3

**Comment by rusty1s** [comment]
It's not, see [here](https://github.com/rusty1s/pytorch_sparse/releases).

**Comment by engrAsmasaattar** [comment]
Can this be installable using conda?

**Comment by rusty1s** [comment]
You need to install via `pip`.
