### ISSUE TITLE
RuntimeError in HypergraphConv when DataLoader batch_sizes are modified.

### ISSUE THREAD

**Issue by tirtharajdash** [rusty1s/pytorch_geometric#1130]
## 🐛 Bug

While I set the batch_size to 1 in DataLoader, It always shows the following error. Sometimes, it shows the same error for other batch_sizes as well.

../python3.7/site-packages/torch_geometric/nn/conv/hypergraph_conv.py", line 103, in __forward__
    num_edges = hyperedge_index[1].max().item() + 1
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/THC/generic/THCTensorMathReduce.cu:85

## Expected behavior

When the convolution layer is not HypergraphConv (say, something other), it works fine. Can you please help me understand this?

## Environment

* OS: Linux
* Python version: 3.7.6
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1
* GCC version: 7.3.0
* Any other relevant information:

**Comment by rusty1s** [comment]
It seems that `hyperedge_index.numel()` is zero. Is that the case?

**Comment by tirtharajdash** [comment]
Yes... it returns 0. Why does this happen though? I could debug myself..but if you can give some ideas?

**Comment by rusty1s** [comment]
Are you using your own dataset?

**Comment by tirtharajdash** [comment]
Yes, I am using my own dataset, and I follow the format that is described in https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

**Comment by rusty1s** [comment]
So it seems that this format cannot be read properly. It is actually hard to debug for me what went wrong here.

**Comment by tirtharajdash** [comment]
It is read peopoerly. Because: it works well if I fiddle around with the batch sizes. 

There is no issue during training. But while I call `model = eval()` and then pass the data for evaluation `output = model(data)`, the runtime error comes depending on which batch size I have entered.

**Comment by rusty1s** [comment]
I see. So you have a `Data` object with zero edges, so using `batch_size=1` fails for this specific object. I added a check for this specific use-case in `hypergraph_conv.py`. Let me know if this fixes your issues :)

**Comment by tirtharajdash** [comment]
I see. I just added the new condition to the hypergraph_conv.py as you mentioned and it works. We can close the issue in a few moments. I will do it. Thank you so much.
