### ISSUE TITLE
Downloading the dataset failed.

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1131]
## 🐛 Bug

When I use code "dataset = Planetoid(root='/tmp/Cora', name='Cora')"to downloda the dataset which named cora,it has a bug

## To Reproduce

1.
1.
1.

socket.gaierror: [Errno 11004] getaddrinfo failed
During handling of the above exception, another exception occurred:
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
## Environment

* OS:
* Python version:3.6
* PyTorch version:1.4.0
* CUDA/cuDNN version:10.1
* GCC version:
* Any other relevant information:

**Comment by jiaruHithub** [comment]
How can I solve this probelm?Thank you very much!

**Comment by jiaruHithub** [comment]
Thank you.I have been solved this problem!

**Comment by buxiangqiming-666** [comment]
I have encountered the same problem. Could you tell me how to solve it?Thank you very much!

**Comment by jiaruHithub** [comment]
> I have encountered the same problem. Could you tell me how to solve it?Thank you very much!

download the all the files from https://github.com/kimiyoung/planetoid/raw/master/data, and put them inside the raw folder in the path that you specified for the Planetoid dataset.

U can look the url in the source code and change the url into https://github.com/kimiyoung/planetoid/raw/master/data.Then the problem can be done.

**Comment by buxiangqiming-666** [comment]
Although I didn't understand the details of the method, I successfully solved the problem with the method you mentioned.Amazing!Thank you very much for your help!

**Comment by rusty1s** [comment]
Since so many of you have problems with the download and it works just fine to me, it would be really helpful if someone could find out why this does not work for you guys. Is there a problem with the [`download_url`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/download.py) function?

**Comment by jiaruHithub** [comment]
> Since so many of you have problems with the download and it works just fine to me, it would be really helpful if someone could find out why this does not work for you guys. Is there a problem with the [`download_url`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/download.py) function?

I think maybe you 've written the Planetoid func url1 wrong.I check the url in planetoid is 
https://github.com/kimiyoung/planetoid/tree/master/data, but this url is 404.I think you can change it into https://github.com/kimiyoung/planetoid/row/master/data.
Hopeing it can help you.

**Comment by rusty1s** [comment]
It is the other way round for me, `row/master/data/` does not exist for me.

**Comment by jiaruHithub** [comment]
> It is the other way round for me, `row/master/data/` does not exist for me.

Maybe you can use 'try except' realize a result when one url dose not exist ,then code can use another url.

**Comment by rusty1s** [comment]
I just noticed that the currently used url is https://github.com/kimiyoung/planetoid/raw/master/data. Does this give you a 404?

**Comment by Hinlavic** [comment]
A proxy will be helpful.

**Comment by PaskalSunari** [comment]
"URLError: <urlopen error [Errno -3] Temporary failure in name resolution>" 
Are these problems same or what ? I am newbie in programming

**Comment by rusty1s** [comment]
I am not sure. Which example are you trying to run?
