### ISSUE TITLE
How do I load the local dataset?

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1132]
## ❓ Questions & Help

For example, I have a cora dataset in my local folder, how do I load this dataset for membership to GCN, etc.?which func to use？

**Comment by rusty1s** [comment]
I am not sure I understand. Is that related to https://github.com/rusty1s/pytorch_geometric/issues/1131#issuecomment-615025423?

**Comment by jiaruHithub** [comment]
> I am not sure I understand. Is that related to [#1131 (comment)](https://github.com/rusty1s/pytorch_geometric/issues/1131#issuecomment-615025423)?

Thank you.I have been solved this problem throughtout use another comment from you!
