### ISSUE TITLE
Example of APPNP

### ISSUE THREAD

**Issue by w-zm** [rusty1s/pytorch_geometric#1137]
## ❓ Questions & Help

Hi,
I want to test the method proposed in paper "Predict then Propagate: Graph Neural Networks meet Personalized PageRank", and PyG has implemented it as APPNP. But I can not find the example that introduces how to use it.
Thank you.

**Comment by rusty1s** [comment]
You can find an implementation in the [benchmark suite](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/appnp.py).

**Comment by w-zm** [comment]
> You can find an implementation in the [benchmark suite](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/appnp.py).

Thank you.
