### ISSUE TITLE
make max_pool available if data.x=None

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1139]
## 🚀 Feature

`max_pool` does not work if `data.x` is None. 

Would it be possible to add a case distinction here?

inside max_pool.py (line 64):
from  `x = _max_pool_x(cluster, data.x)`
to  `x = None if data.x is None else _max_pool_x(cluster, data.x)`

Or is there a specific reason not to allow this case?
Yes, I could call `pool_pos`, but then I miss the batch information. 
Adding this makes me copying nearly the complete `max_pool` function.

Thanks in advance!

**Comment by rusty1s** [comment]
Fixed in master!
