### ISSUE TITLE
GIN -> Rewritting the formula to Matrix Algebra

### ISSUE THREAD

**Issue by JanoschMenke** [rusty1s/pytorch_geometric#1144]
## ❓ Questions & Help
Couldn't the GIN propagation rule be rewritten to:

![CodeCogsEqn(2)](https://user-images.githubusercontent.com/44569965/79844783-6e8c4c00-83bc-11ea-8207-6b83ccc78444.gif)

Which is would show the similarity to older GNN, like the GCN by Kipf & Welling. 

Would this be the correct reformulation or did I miss something?

**Comment by rusty1s** [comment]
You can write it like that. However, the main contributions of GIN are the non-normalization of A and the non-linear transformation afterwards.

**Comment by JanoschMenke** [comment]
Yes maybe that is what I am getting stuck on. I understand the purpose of the non-normalization, or sum-aggregation rather than a "mean-aggregation". But I am not sure how the MLP is then applied.
Is it just: 

![CodeCogsEqn(3)](https://user-images.githubusercontent.com/44569965/79845411-4bae6780-83bd-11ea-91ac-bf8155998338.gif)
 obviously any other activation-function can be chosen, and you can also expand the MLP with more layers and BN etc. 

Because this too me looks still really similar to other GCNs just dropping normalization?
Or is this interpretation of the applied MLP wrong?

**Comment by rusty1s** [comment]
Well, in your formula, you only have a single layer, but the paper shows that applying MLPs indeed makes GIN more expressive than other GNNs.

**Comment by JanoschMenke** [comment]
Okay yes then I got it. Thanks for taking the time to answer.

I did not doubt the usefulness of the changes made by the GIN. I just wanted  to confirm that I am not wrong with the reformulation. I think maybe for some it is helpful to see the GIN formulated in a style similar to the GCN so the difference come more apparent. 

Greetings
Janosch

**Comment by rusty1s** [comment]
You are absolutely right :) I added this formulation to the documentation. Thanks!
