### ISSUE TITLE
ClusterData cannot deal with semi-supervised data

### ISSUE THREAD

**Issue by fgerzer** [rusty1s/pytorch_geometric#1145]
## 🚀 Feature

Currently, the code surrounding [ClusterData](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/cluster.py) (like the [cluster_gcn](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cluster_gcn.py) example) seem to assume that sufficient labels exist such that every batch has at least one non-masked label. This often fails for semi-supervised classification, and might (with an extremely low probability) even fail for supervised node classification.

## To Reproduce

1. In  [cluster_gcn](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cluster_gcn.py), replace the `Reddit` dataset (line 7) with
```
from torch_geometric.datasets import Planetoid
dataset = Planetoid('../data/Planetoid', "Cora")
```
2. On running this, a `RuntimeError` is raised with after a random number of batches, usually less than five.

```
Traceback (most recent call last):
  File "cluster_gcn.py", line 74, in <module>
    loss = train()
  File "cluster_gcn.py", line 45, in train
    loss = F.nll_loss(logits[data.train_mask], data.y[data.train_mask])
  File "torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 2: non-empty vector or matrix expected at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31
```
Inspection reveals `train_mask` has no `True` entries, and therefore no nodes are chosen.

## Motivation

There should be a simple way of using ClusterGCN for semi-supervised classification.

## Proposal

In my own code, I modified ClusterLoader to allow for masking of inputs. This requires modifying ClusterLoader's init function:

```python
class ClusterLoader(torch.utils.data.DataLoader):
    def __init__(self, cluster_data, valid_indices=None, batch_size=1, shuffle=False, **kwargs):
        if valid_indices is None:
            valid_indices = list(range(len(cluster_data)))

        class HelperDataset(torch.utils.data.Dataset):
            def __len__(self):
                return len(valid_indices)

            def __getitem__(self, idx):
                partidx = valid_indices[idx]
                start = int(cluster_data.partptr[partidx])
                length = int(cluster_data.partptr[partidx + 1]) - start

                data = copy.copy(cluster_data.data)
                num_nodes = data.num_nodes
                for key, item in data:
                    if item.size(0) == num_nodes:
                        data[key] = item.narrow(0, start, length)

                return data, partidx
    [...]
```
This can then be used to mask batches that do not contain train, val, or test data, depending on your need:
```
valid_indices = [i for i, cd in enumerate(cluster_data) if torch.sum(cd.mask).bool()]
loader = ClusterLoader(
    cluster_data, batch_size=self.batch_size, 
    shuffle=True, num_workers=self.num_workers, 
    valid_indices=valid_indices
)
```

Certainly, that's just one way of doing this, and you might find a better solution.

**Comment by rusty1s** [comment]
Hi, I agree that this might be a problem, but I am not sure if this should be handled directly inside the `ClusterLoader`. Another option might be to just skip batches if they do not contain any valid nodes inside the training loop.

**Comment by fgerzer** [comment]
That's a very good point, and might be more generally applicable than my solution above.

I'll keep using my solution privately for now, since I didn't build anything with the provision of skipping batches; accordingly, it's simpler for me to modify the loader. For the general case, though, manual batch skipping sounds fine, too.

I'll close this; maybe someone facing similar issues can reuse my code.
