### ISSUE TITLE
RuntimeError for CPU installation on Ubuntu 19.10

### ISSUE THREAD

**Issue by LindaSt** [rusty1s/pytorch_geometric#1153]
## 🐛 Bug

CPU installation of pytorch geometric does not seem to work. The installation went without error, but when I try to do an import like `from torch_geometric.nn import MessagePassing`, I get a RuntimeError (see traceback below).

## To Reproduce

1. Run the installation as specified with cpu instead of ${CUDA}
1. Run `from torch_geometric.nn import MessagePassing`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
>     import torch_geometric.nn
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
>     from .data_parallel import DataParallel
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
>     from torch_geometric.data import Batch
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
>     from .data import Data
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
>     from torch_sparse import coalesce
>   File "/home/linda/anaconda3/envs/gale/lib/python3.7/site-packages/torch_sparse/__init__.py", line 38, in <module>
>     f'Detected that PyTorch and torch_sparse were compiled with '
> RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.`
 

## Expected behavior

Import works without errors.

## Environment

* OS: Ubuntu 19.10
* Python version: 3.7.4
* PyTorch version: n/a
* CUDA/cuDNN version: n/a
* GCC version: 9.2.1
* Any other relevant information:

**Comment by rusty1s** [comment]
Well, the error message already identifies the issues. You have a CUDA PyTorch installation, so you also need to install a CUDA PyG installation.

**Comment by LindaSt** [comment]
My bad, thanks!
