### ISSUE TITLE
build pytorch_scatter in MacOS 10.13

### ISSUE THREAD

**Issue by oiwio** [rusty1s/pytorch_geometric#116]
I have used ```MACOSX_DEPLOYMENT_TARGET=10.13.6 CC=clang CXX=clang++ python setup.py install``` to install pytorch_scatter, but failed, here is the information of my system and log. Please help me to solve this problem, I want to use it to implement GNN in my paper.

Ps: I also used gcc, but still falied.

**System**
- OS: MacOS 10.13.6
- PyTorch version: 1.1.0
- How you installed PyTorch (conda, pip, source): source 
- Python version: Anaconda python 3.6.4
- CUDA/cuDNN version: CUDA 10.1
- GPU models and configuration: GeForce GTX 1080
- GCC version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.10.44.4)

**Log**

> MACOSX_DEPLOYMENT_TARGET=10.13.6 CC=clang CXX=clang++ python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing torch_scatter.egg-info/PKG-INFO
> writing dependency_links to torch_scatter.egg-info/dependency_links.txt
> writing top-level names to torch_scatter.egg-info/top_level.txt
> reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
> installing library code to build/bdist.macosx-10.7-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> building 'torch_scatter.scatter_cuda' extension
> clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kiwee/anaconda3/include -arch x86_64 -I/Users/kiwee/anaconda3/include -arch x86_64 -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/Users/kiwee/anaconda3/include/python3.6m -c cuda/scatter.cpp -o build/temp.macosx-10.7-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -std=c++11
> /usr/local/cuda/bin/nvcc -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/Users/kiwee/anaconda3/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.macosx-10.7-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -std=c++11
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/util/UniqueVoidPtr.h(69): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/Allocator.h(96): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(175): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(185): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(194): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(199): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(206): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(221): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(228): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(235): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/util/UniqueVoidPtr.h(69): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/Allocator.h(96): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(175): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(185): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(194): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(199): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(206): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(221): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(228): warning: attribute namespace "clang" is unrecognized
> 
> /Users/kiwee/anaconda3/lib/python3.6/site-packages/torch/include/c10/core/TensorOptions.h(235): warning: attribute namespace "clang" is unrecognized
> 
> clang++ -bundle -undefined dynamic_lookup -L/Users/kiwee/anaconda3/lib -arch x86_64 -L/Users/kiwee/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/cuda/scatter.o build/temp.macosx-10.7-x86_64-3.6/cuda/scatter_kernel.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.macosx-10.7-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-darwin.so
> ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
> ld: library not found for -lcudart
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> error: command 'clang++' failed with exit status 1
>

**Comment by rusty1s** [comment]
Hi,

As far as I know, you need clang 9.1.0 in order to compile/link with CUDA 10 by downgrading the command line tools.

**Comment by oiwio** [comment]
@rusty1s Thank you for your reply. Now I have downgraded my "Command Line Tools" to 9.1,
![image](https://user-images.githubusercontent.com/3225339/54152594-8afb4c80-4478-11e9-9311-c23b4154330c.png)
but still cannot work...

**Comment by rusty1s** [comment]
I created a [FAQ](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#frequently-asked-questions) for common installation errors. Let me know if this fixes your issues.

**Comment by oiwio** [comment]
@rusty1s Thank you for your advice! But as I know, the new version of clang is clang-1000...

**Comment by rusty1s** [comment]
A few more thoughts:
1. Ensure that CUDA ist ser in DYLP-LIBRARY_PATH.
2. Follow the CUDA installation guide (https://docs.nvidia.com/cuda/index.html) and verify that you can compile wirh nvcc.
3. It looks like you really need to use clang-

**Comment by rusty1s** [comment]
I am really sorry! Can you post the output of `ls /usr/local/cuda/lib`? Do you have a `lib64` dir?

**Comment by oiwio** [comment]
Hey, I noticed that I don't have the ```lib64``` dir, is it necessary? Can you tell me how can I get that, I installed CUDA by following the guide on the official website.
![image](https://user-images.githubusercontent.com/3225339/54268253-c6e7fc00-45b5-11e9-9f4d-42d3fada5b68.png)

**Comment by rusty1s** [comment]
No it is not necessary. It is called `lib64` on Linux and `lib` on macOS.

```
ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
ld: library not found for -lcudart
```

The error message suggest that it however expects a lib64 directory. You can maybe create a symlink from `lib` to `lib64`. 

Alternatively, maybe this [thread](https://askubuntu.com/questions/510176/usr-bin-ld-cannot-find-lcudart) or [this one](https://stackoverflow.com/questions/9633881/usr-bin-ld-cannot-find-lcudart) can help you.

**Comment by oiwio** [comment]
@rusty1s Wow, it works!!! Thanks for your help and patience. I just use ```sudo ln -s /usr/local/cuda/lib /usr/local/cuda/lib64``` , and install all packages with prefix ```MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++```.

**Comment by junjiez** [comment]
> @rusty1s Wow, it works!!! Thanks for your help and patience. I just use `sudo ln -s /usr/local/cuda/lib /usr/local/cuda/lib64` , and install all packages with prefix `MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++`.

A bit curious about the MACOSX_DEPLOYMENT_TARGET setting: will it cause any differences in the compiling when setting MACOSX_DEPLOYMENT_TARGET=10.13 or MACOSX_DEPLOYMENT_TARGET=10.9? 

Why in the official guideline and the github page, both write MACOSX_DEPLOYMENT_TARGET=10.9?

Build (from: https://pytorch.org/get-started/locally/)
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```

On macOS (from: https://github.com/pytorch/pytorch)
```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```

**Comment by rusty1s** [comment]
As far as I know, `MACOSX_DEPLOYMENT_TARGET` should at least be set to `10.9`. There should be no differences.
