### ISSUE TITLE
cannot import name 'GNNExplainer' from 'torch_geometric.nn'

### ISSUE THREAD

**Issue by hongxuenong** [rusty1s/pytorch_geometric#1164]
## 🐛 Bug
Got this error why try to import GNNExplainer:

cannot import name 'GNNExplainer' from 'torch_geometric.nn' (/home/gpu-user-02/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_geometric/nn/__init__.py)

## To Reproduce

Run following python code:
1.from torch_geometric.nn import GNNExplainer
1.
1.

## Environment

* OS: Ubuntu
* Python version: 3.8.2
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.2
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
It's currently only available on master and not yet via `pip`, so you need to clone the repo and run `python setup.py install` to get this functionality.

**Comment by hongxuenong** [comment]
Thanks. It solves the problem
