### ISSUE TITLE
Question about PointNet2 classfication

### ISSUE THREAD

**Issue by crea397** [rusty1s/pytorch_geometric#1166]
## ❓ Questions & Help

Hi,

Question about 'examples/pointnet2_classification.py'.

In line 102, 'T.SamplePoints(1024)', 1024 is specified. Why is this?

Is there a fixed number of input points for PointNet++?

If the number of input point clouds is determined, and I want to run 'pointnet2_classification.py' for a sparse dataset with fewer than 1024 point clouds, what do I do?

Thanks!

**Comment by rusty1s** [comment]
There is not a fixed number of inputs points for PointNet++ in general. Even if you trained the network on point clouds of size 1024, you can still apply it to different sizes. We just follow the experimental protocol of PointNet++ here.

**Comment by crea397** [comment]
Thank you very much for your reply!

When training on the original dataset, should the number of points in the dataset be the same before inputting them into PointNet++?

Is it okay to have fewer point clouds when training?
For example, each data in a dataset has 300 points.

**Comment by rusty1s** [comment]
You can do this, but it might hurt the performance of your model.
