### ISSUE TITLE
AUC does not change during the Autoencoder training

### ISSUE THREAD

**Issue by ZihanChen1995** [rusty1s/pytorch_geometric#1167]
## ❓ Questions & Help

Hi, I'm a beginner to GNNs, and I'm trying to implement this technique in my recent researches. Thank you for this great library!

I met a question when I try to use the Autoencoder to embedding my dataset. I found no matter how I change the dataset or hyper-parameters, the AUC didn't change during the training process. Could you mind help me out with this issue? My code is following.

Firstly, I try to simulate an edge list.
```
rec_node = list(np.random.randint(0,3000, size=10000))
sen_node = list(np.random.randint(0,3000, size=10000))
```

Then I use LabelEncoder to figure out the unique node in this edge list, then use it to simulate node_feature matrix.
```
from sklearn.preprocessing import LabelEncoder

item_encoder = LabelEncoder()
list_fit = list(set(rec_node+sen_node))
item_encoder.fit(list_fit)

# get the label
rec_node = item_encoder.transform(rec_node)
sen_node = item_encoder.transform(sen_node)


# the number of x features (unique x in this data)
x_num = len(set(list(rec_node)+list(sen_node)))
```

Next step, I use the previous data to build: node feature matrix, then use Data to generate data input.
```
from torch_geometric.data import Data

# the edge index
edge_index = torch.tensor([rec_node, sen_node], dtype=torch.long)

# initalize a x node feature matrix here (we don't have any since now)
node_feature_dimen = 10
x_feature = torch.zeros([x_num,10], dtype=torch.float)

# build the data based on this
pyg_data = Data(x=x_feature, edge_index=edge_index)
```
Things looks fine here, the output looks like this:
```
Data(edge_index=[2, 10000], x=[2999, 10])
```

Then I build the Autoencoder:
```
class Encoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(Encoder, self).__init__()
        self.conv1 = pyg_nn.GCNConv(in_channels, 2 * out_channels, cached=True)
        self.conv2 = pyg_nn.GCNConv(2 * out_channels, out_channels, cached=True)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        return self.conv2(x, edge_index)

def train(epoch):
    model.train()
    optimizer.zero_grad()
    
    z = model.encode(x, train_pos_edge_index)
    loss = model.recon_loss(z, train_pos_edge_index)
    loss.backward()
    optimizer.step()
    
    writer.add_scalar("loss", loss.item(), epoch)

def test(pos_edge_index, neg_edge_index):
    model.eval()
    with torch.no_grad():
        z = model.encode(x, train_pos_edge_index)
    return model.test(z, pos_edge_index, neg_edge_index)


data = pyg_data

channels = 8
dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# encoder: written by us; decoder: default (inner product)
model = pyg_nn.GAE(Encoder(node_feature_dimen, channels)).to(dev)
```
And split data using train_test_split_edges:
```
data = train_test_split_edges(data)
x, train_pos_edge_index = data.x.to(dev), data.train_pos_edge_index.to(dev)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
```
Finally, I train the model:
```
for epoch in range(1, 201):
    train(epoch)
    auc, ap = test(data.test_pos_edge_index, data.test_neg_edge_index)
    
    if epoch % 10 == 0:
        print('Epoch: {:03d}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, auc, ap))
```
Sadly, the problem happens: 
```
Epoch: 010, AUC: 0.5000, AP: 0.5000
Epoch: 020, AUC: 0.5000, AP: 0.5000
Epoch: 030, AUC: 0.5000, AP: 0.5000
Epoch: 040, AUC: 0.5000, AP: 0.5000
Epoch: 050, AUC: 0.5000, AP: 0.5000
Epoch: 060, AUC: 0.5000, AP: 0.5000
Epoch: 070, AUC: 0.5000, AP: 0.5000
Epoch: 080, AUC: 0.5000, AP: 0.5000
Epoch: 090, AUC: 0.5000, AP: 0.5000
Epoch: 100, AUC: 0.5000, AP: 0.5000
Epoch: 110, AUC: 0.5000, AP: 0.5000
Epoch: 120, AUC: 0.5000, AP: 0.5000
Epoch: 130, AUC: 0.5000, AP: 0.5000
Epoch: 140, AUC: 0.5000, AP: 0.5000
Epoch: 150, AUC: 0.5000, AP: 0.5000
Epoch: 160, AUC: 0.5000, AP: 0.5000
Epoch: 170, AUC: 0.5000, AP: 0.5000
Epoch: 180, AUC: 0.5000, AP: 0.5000
Epoch: 190, AUC: 0.5000, AP: 0.5000
Epoch: 200, AUC: 0.5000, AP: 0.5000
```

I check everywhere, but cannot find where I made a mistake. (The problem still happens if I use real-world data but not simulation one. I guess there might be some problems during my data-transferring.)

Could you please help me with this issue? Thank you a lot in advance for your help.I really appreciate it!

**Comment by rusty1s** [comment]
Since you do not have any node features, this is to be expected. This is a requirement for `GCNConv` and the paper suggest to use an identity matrix as input. If you solely want to learn from graph-structure, you can also make use of the `GINConv` and use one-hot degrees as input features.

**Comment by ZihanChen1995** [comment]
Thank you for your reply! Yes, this is the problem. I switch it into the identity matrix and it works now. May I ask two further questions?

1. When you suggest using one-hot degrees to learn graph-structure solely, the "degree" you mentioned is the "degree concept" we use in social network analysis?(The measurement of the total number of edges connected to a particular vertex?)

2. If our node has both features of one-hot (like female/male) and numerical one (like age), can we simply concat these features together when we input node feature? (Like (0, 1, 25) for one row? First two are one-hot for the gender, last one is for the age)

Thank you so much for your time, Matthias!

**Comment by rusty1s** [comment]
1. Well, you are free to use any "synthetic" features you like. I was referring to using the node degrees as input features (encoded as a one-hot vector), see `transforms.OneHotDegree`, but there may be better choices.
2. Yes.

**Comment by ZihanChen1995** [comment]
Got it! Your explanation is very helpful and clear. Thank you so much for your time and help! Have a great week.

**Comment by rusty1s** [comment]
You too :)

**Comment by tomlincr** [comment]
Appreciate this is closed/old, but sharing here as this is one of the only results for this error on Google and this may help someone else.

This issue occurred for me when I had **inadvertently included the node index in the node feature matrix**, removing the index immediately resolved the problem!
