### ISSUE TITLE
OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ldepn** [rusty1s/pytorch_geometric#1170]
## ❓ Questions & Help
When I run import Data, it shows the errors 'OSError: libtorch_cpu.so: cannot open shared object file: No such file or directory' 
my code is following:
`import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)
>>> Data(edge_index=[2, 4], x=[3, 1])`

How to fix?

**Comment by ldepn** [comment]
This is caused by the PyTorch version is no match.

**Comment by ysl208** [comment]
What pytorch version should it be? Mine is 1.4.0 and cuda 10.1:
```
python -c "import torch; print(torch.__version__)"
> 1.4.0
python -c "import torch; print(torch.version.cuda)"
> 10.1
```
