### ISSUE TITLE
RuntimeError: Cached 3366 number of edges, but found 5000. Please disable the caching behavior of this layer by removing the `cached=True` argument in its constructor.

### ISSUE THREAD

**Issue by ZihanChen1995** [rusty1s/pytorch_geometric#1173]
## ❓ Questions & Help

Hi Matthias! I used the train_pos_edge_index to train my Autoencoder. However, when I tried to implement this Autoencoder model on the entire dataset, it turned out the error:
```
RuntimeError: Cached 3366 number of edges, but found 5000. Please disable the caching behavior of this layer by removing the `cached=True` argument in its constructor.
```
Is this because the edge_index I use to train has a different shape with the one I try to encode? Normally Autoencoder can transfer the new input into the same size latent variables, even it didn't see it before. May I ask why can't we do the same thing here?

And if I want to encode an entire network's nodes, should I just bring the entire graph (the original edge_index) into the training process, and use the test_pos and test_neg edge index to evaluate it?

The last question is: If I have an already-trained Autoencoder, and now I have some new nodes and new edges emerge in this network. How can I encode these new nodes, if the encoder input must have the same shape as the training one?

Thank you so much for your time. (Some details can be found following)

(Some details of model)

My original data shape:
```
Data(edge_index=[2, 5000], x=[4741, 4741])
```
The data shape after train_test_split_edges:
```
Data(test_neg_edge_index=[2, 210], test_pos_edge_index=[2, 210], train_neg_adj_mask=[4741, 4741], train_pos_edge_index=[2, 3366], val_neg_edge_index=[2, 105], val_pos_edge_index=[2, 105], x=[4741, 4741])
```
Training process:
```
x, train_pos_edge_index = data.x.to(dev), data.train_pos_edge_index.to(dev)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1, 201):
    train(epoch)
    auc, ap = test(data.test_pos_edge_index, data.test_neg_edge_index)
    
    if epoch % 10 == 0:
        print('Epoch: {:03d}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, auc, ap))
```
Finally encode process:
```
model.eval()
z = model.encode(x,original_data.edge_index)
```
Then error happens:
```
RuntimeError: Cached 3366 number of edges, but found 5000. Please disable the caching behavior of this layer by removing the `cached=True` argument in its constructor.
```

**Comment by rusty1s** [comment]
The `cached` argument in `GCNConv` caches the normalization of the adjacency matrix (for faster computation), and complains if it encounters a different adjacency matrix. Just removing the`cached` argument in `GCNConv` should fix this. You can, of course, use a different connectivity :)

**Comment by ZihanChen1995** [comment]
Great!! Thank you a lot for your reply, Matthias! It's very helpful.   : D
