### ISSUE TITLE
Error in the implementation of SortPool

### ISSUE THREAD

**Issue by LeviBorodenko** [rusty1s/pytorch_geometric#1174]
## ❓ Questions & Help

In the [docs](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.glob.global_sort_pool) for the SortPool layer, it says that:

> [...] node features are first **sorted individually** and then sorted in descending order based on their last features.

I believe that first sorting all features individually (implemented as `x = x.sort(dim=-1)`) is wrong and should not be done. In the [original paper](https://www.cse.wustl.edu/~muhan/papers/AAAI_2018_DGCNN.pdf), Zhang et al. describe SortPool as:

![Description of SortPool](https://user-images.githubusercontent.com/9279320/80618913-e9e4a200-8a3b-11ea-8437-fb3485ad7438.png)

Which to me means that we only sort the rows according to the last channel (alias continuous WL colours). Furthermore, in the [original implementation](https://github.com/muhanzhang/DGCNN/blob/master/SortPooling.lua) there also seems to be no sign of first sorting features individually.

**Comment by rusty1s** [comment]
The paper states "the input is first sorted row-wise according to Z", and the official implementation also sorts node features individually, see [here](https://github.com/muhanzhang/DGCNN/blob/master/SortPooling.lua#L26). Am I missing something?

**Comment by LeviBorodenko** [comment]
> first sorted row-wise according to Z^h

I believe that means that we sort the rows according to the entries in Z^h and not that we sort the entries of each row.

The comment above the line that you referenced in the original implementation says 

```
-- sort the last channel of input in descending order
 
local sorted, allIndices = input[{{}, {sc}}]:sort(1, true)
```

I think that he is sorting the last channel and collecting the permuted indices after sorting to then sort the rows accordingly -- though I am not sure I am understanding his code correctly.

**Comment by rusty1s** [comment]
You are right, I was wrong here. That line indeed sorts rows according to the last channel (LUA indexing starts at one :D). That should be fixable by just removing the `x.sort(dim=-1)` call.

**Comment by LeviBorodenko** [comment]
:)
Do you mind if I fix that in PR?

**Comment by rusty1s** [comment]
Oh, I already fixed it :(
