### ISSUE TITLE
Using GAE or its variants for multiple graphs

### ISSUE THREAD

**Issue by ioannisa92** [rusty1s/pytorch_geometric#1176]
## ❓ Questions & Help

First, I would like to say I am a new user of torch_geometric. It is great! You guys have done a great job.

I have a library of chemical compounds (~4.5k) and I would like to use GAE or its variants to reconstruct these in batches. For example, passing 32 graphs as a mini-batch to GAE, and having it reconstruct those 32 graphs.

Is this something that is possible? Or is it advised that only one graph be reconstructed?

Thank you for your time

**Comment by rusty1s** [comment]
You can do this with PyTorch Geometric, but I currently the `GAE` model does only allow a single graph (following the paper). In general, there is nothing that prevents you from applying GAE to multiple graphs. You just need to reshape your embedding into format [batch_size, num_nodes, num_hidden].

**Comment by ioannisa92** [comment]
So you are saying that I would need to make a modified version of the currently offered GAE of my own right? To implement reshaping the embedding.

Thank you!
