### ISSUE TITLE
Easy and efficient method for getting all outgoing edges of a vertex in edge_index?

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1178]
## ❓ Questions & Help
Is there an easy and efficient way, of getting all outgoing edges of a vertex in `edge_index`?
For example, getting all neighbors of vertex with `id = 1`?
Doing this with Python loops appears to be very slow for large graphs and makes it unusuable for me.

Thanks for help in advance.

**Comment by rusty1s** [comment]
```python
row, col = edge_index
mask = row == id
edge_index = edge_index[:, mask]
```
