### ISSUE TITLE
Converting two directions edges to one

### ISSUE THREAD

**Issue by tiberium24** [rusty1s/pytorch_geometric#1181]
I have an undirected graph. That means I have created an edge list with edges of both directions. After some operations I need to be able to keep only one of the two directions edges. How should this be done? Is there a function for this? Am I supposed to do it manually and take their average (aka edge attributes)?

The existence of these two edges creates a problem and overhead computation for me.

@rusty1s

**Comment by rusty1s** [comment]
Well, that surely depends on how you exactly want to filter. IMO, you have many possible options to do so:
1. Create a `mask` that dictates which edge you want to keep: `edge_index = `edge_index[:, mask]`
2. Just keep one direction:
```
row, col = edge_index
mask = row < col
edge_index = edge_index[:, mask]
```
3. Aggregate both directions into a single edge:
```
N = data.num_nodes
row, col = edge_index
mask = row < col
edge_attr1 = edge_attr[mask]
(row, col), edge_attr = torch_sparse.transpose(edge_index, edge_attr)
mask = row < col
edge_attr2 = edge_attr[mask]
edge_attr = edge_attr1 + edge_attr2
```

**Comment by tiberium24** [comment]
I understand, I was thinking about something similar. Thank you very much!

**Comment by tiberium24** [comment]
> Well, that surely depends on how you exactly want to filter. IMO, you have many possible options to do so:
> 
> 1. Create a `mask` that dictates which edge you want to keep: `edge_index = edge_index[:, mask]`
> 2. Just keep one direction:
> 
> ```
> row, col = edge_index
> mask = row < col
> edge_index = edge_index[:, mask]
> ```
> 
> 1. Aggregate both directions into a single edge:
> 
> ```
> N = data.num_nodes
> row, col = edge_index
> mask = row < col
> edge_attr1 = edge_attr[mask]
> (row, col), edge_attr = torch_sparse.transpose(edge_index, edge_attr)
> mask = row < col
> edge_attr2 = edge_attr[mask]
> edge_attr = edge_attr1 + edge_attr2
> ```

I believe tranpose needs two additional arguments.

**Comment by rusty1s** [comment]
That's of course correct. I haven't tested it by myself :)
