### ISSUE TITLE
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory ( torch_geometric/utils/loop.py) 

### ISSUE THREAD

**Issue by AugF** [rusty1s/pytorch_geometric#1183]
## 🐛 Bug
when I use 'nsys' to profile torch's code, get this bug:
```
File "/home/xxx/anaconda3/envs/pyg/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 132, in add_remaining_self_loops
    edge_weight = torch.cat([edge_weight[mask], loop_weight], dim=0)
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory: 
```
command
```
nsys profile -t cuda,osrt,nvtx -o baseline -e LD_LIBRARY_PATH -w true python gcn/train_cora.py
```
I tried to use the way in https://github.com/pytorch/pytorch/issues/31554#issue-541403748, that is `export LD_LIBRARY_PATH=/home/xxx/anaconda3/envs/pyg/lib/python3.8/site-packages/torch:${LD_LIBRARY_PATH} ` , but failed.
## Environment

```
Linux
Anaconda3-2019.10-Linux-x86_64.sh
torch 1.5.0
python 3.8
cuda 10.1
torch_geometric 1.4.3
```

**Comment by rusty1s** [comment]
Is this a PyTorch Geometric bug? Does it only occur in PyG? Otherwise, you might want to ask the PyTorch devs for help on this one.

**Comment by AugF** [comment]
Sorry to bother you, thank you very much!
