### ISSUE TITLE
Congratz

### ISSUE THREAD

**Issue by rchavezj** [rusty1s/pytorch_geometric#119]
Dude first of all, congrats on making this library open source. Also, you should register to have your work on the ecosystem home page (https://pytorch.org/ecosystem).

**Comment by rusty1s** [comment]
Thank you! I just applied :)

**Comment by rchavezj** [comment]
I was wondering if there are any "hands-on" tutorials on using your library (PyG) with an existing dataset? I'm writing a book, and I would love to mention your work.

**Comment by rusty1s** [comment]
You mean a basic tutorial on how to train Graph Neural Networks? I wrote a short section about this [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#learning-methods-on-graphs). If you tell me exactly what you need, I may be able to provide better help.

**Comment by rchavezj** [comment]
Are you referring to the blog post within the short section (https://tkipf.github.io/graph-convolutional-networks/)? Looks promising! 

By any chance do you know if your library can support the Alphafold challenge (https://deepmind.com/blog/alphafold/) or should I just utilize PyTorch directly? I have a picture of examples done with Geometric Deep Learning. 

![geometric](https://user-images.githubusercontent.com/10482151/54276712-3aa0ef00-454b-11e9-8846-c994ee52c75b.png)
