### ISSUE TITLE
A question on generate my own dataset

### ISSUE THREAD

**Issue by juanshu30** [rusty1s/pytorch_geometric#1193]
## ❓ Questions & Help

What is the self.processed_paths[0] used for? 

The following is my code, Could you help me what mistake I made? I have one graph and I already create the feature matrix, edge index and the label.

# code
class DiseaseGeneDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(DiseaseGeneDataset, self).__init__(root, transform,
                                                 pre_transform)
         self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return []

    @property
    def processed_file_names(self):
        return []

    def download(self):
        pass

    def process(self):

        data_list = []

        data = Data(x=feature_matrix, edge_index=edge_index, y=label)
        data_list.append(data)

        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])

**Comment by rusty1s** [comment]
It corresponds the the path of the names provided in `processed_file_names`. So basically `{root_dir}/processed/{processed_file_names[0]}`. For your  example to work, you need to set 
```python
`def processed_file_names(self):
    return ['data.pt']
```

**Comment by juanshu30** [comment]
> It corresponds to the path of the names provided in `processed_file_names`. So basically `{root_dir}/processed/{processed_file_names[0]}`. For your example to work, you need to set
> 
> ```python
> def processed_file_names(self):
>     return ['data.pt']
> ```

Thanks！It works. I have another question that when there is an error: CUDA out of memory, does that mean I need to use Dataset but not InMemoryDataset?

**Comment by rusty1s** [comment]
That seems not related to datasets since they aren‘t saved on GPU.

**Comment by juanshu30** [comment]
> That seems not related to datasets since they aren‘t saved on GPU.

Sorry for unclear questions. I can create this data and when I use GPU to run the code of a GNN, the error said CUDA out of memory. In this case, Dataset is better than nMemoryDataset, right?

**Comment by rusty1s** [comment]
No, it‘s just that your graph/batch size is too large to fit into GPU memory.

**Comment by juanshu30** [comment]
> No, it‘s just that your graph/batch size is too large to fit into GPU memory.

Can I ask what is the batch in GCN? I use loader but I find the model still use the entire graph to train. The batch is on nodes or the edges? Thanks

**Comment by rusty1s** [comment]
The batch is on examples if you use `DataLoader`. If you want to create mini-batches out of nodes, please have a look at `examples/reddit.py` with `NeighborSampler` or `examples/cluster_gcn.py` with `ClusterLoader`.
