### ISSUE TITLE
Reuse adjacency graph over samples

### ISSUE THREAD

**Issue by Padarn** [rusty1s/pytorch_geometric#1196]
## ❓ Questions & Help

Hi team

I'm reading the documentation here: https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches

In my use case I wish to reuse the same `A` matric across all samples: Is this possible in the library now? The `A` matrix in my problem is on the order of millions of non-zero entries, so repeating it across baches would be expensive.

**Comment by rusty1s** [comment]
Yes, you can do this via the `node_dim` option of message passing modules:
```python
conv = GCNConv(32, 32, node_dim=1)
# x: [batch_size, num_nodes, num_features)
out = conv(x, edge_index)
# out: [batch_size, num_nodes, num_features)
```

**Comment by Padarn** [comment]
Sorry I didn't quite follow this: I meant that I have multiple instances of the same Graph. For example a single training example could be `(A_1,  X_1, Y_1)` and I wish to run against a batch defined by
```
(A_1,  X_1, Y_1)
(A_1,  X_2, Y_2)
(A_1,  X_2. Y_2)
...
```

**Comment by rusty1s** [comment]
Yes, that's what I mean, so:
```python
X = torch.stack([X1, X2, X3], dim=0)
conv(X, A_1)
```
with `conv.node_dim=1` (which says that nodes are of the same graph are in the first dimension).

**Comment by Padarn** [comment]
Ahhh right. Sorry I misunderstood. Thanks a lot.
