### ISSUE TITLE
Installation for cuda 10.2

### ISSUE THREAD

**Issue by SriCharanB** [rusty1s/pytorch_geometric#1197]
## ❓ Questions & Help

My system has cuda version 10.2. I've downloaded pytorch 10.2 already. Couldn't install PyG.
Is there any possible solution?

**Comment by rusty1s** [comment]
What's the error?

**Comment by SriCharanB** [comment]
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

This is what I get when I try to run.

**Comment by rusty1s** [comment]
Seems like it is looking for some CUDA 10.1 libs. Do you have multiple PyTorch versions installed (with different CUDAs) or multiple CUDA versions installed?

**Comment by SriCharanB** [comment]
Multiple CUDA versions installed except 10.1. (Installed: 10.0,10.2 and 9.2)
PS: I'm working on remote ssh with no sudo permissions.

**Comment by SriCharanB** [comment]
Thanks. Got Solved. Just changed to different hardware where 10.1 installed. But still, it can be resolved in future where mutilple CUDAs installed.
