### ISSUE TITLE
Batch training doubts

### ISSUE THREAD

**Issue by UTpH** [rusty1s/pytorch_geometric#1198]
## ❓ Questions & Help

I am trying to train a network with GCNConv layers. My batch_size is 4, the graph has 293 nodes(1 feature each) and the same edge_index. I used the following to initialize the network and in the fwd methods:-

`self.conv1 = GCNConv(293*batch_size, 256, node_dim=1) 
  self.conv2 = GCNConv(256, 1)`

`def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = x.view(batch_size,293, -1)
        print(x.shape, edges_index.shape) #[4, 293, 1]
        x = self.conv1(x, edge_index)`

I get a size mismatch error:-
`size mismatch, m1: [1172 x 1], m2: [1172 x 256]`
Unsure where I am going wrong. I read the [docs](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches) and referred to a [related issue](https://github.com/rusty1s/pytorch_geometric/issues/973) as well, but couldn't solve my issue.

**Comment by rusty1s** [comment]
Is this resolved? You need to define `GCNConv` as `GCNConv(1, 256)`.

**Comment by UTpH** [comment]
I solved the (1,256) part.
So if I have a batch_size of 4, do I just have to pass
`GCNConv(1, 256, node_dim=1)`
and resize in the forward function? 
Also, do I need `node_dim=1` in the second layer as well?

**Comment by rusty1s** [comment]
Yes, resize to format [batch_size, num_nodes, num_features] and you are good to go. All `conv`s that operate on those batches should have `node_dim=1` set.

**Comment by UTpH** [comment]
So the resize needs to happen before feeding to each GCNConv?

**Comment by UTpH** [comment]
I went ahead with resizing x everytime before a conv layer but I get a cuda memory access error in scatter.py
` 
     Traceback of TorchScript (most recent call last): File 
       "/home/ph1391/.conda/envs/simclr/lib/python3.7/site-packages/torch_scatter/scatter.py", line 23, in scatter_sum

            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE

    else:
        return out.scatter_add_(dim, index, src)

     RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at 
     /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:296`

My inputs are correctly shaped as well. I would appreciate any help!
