### ISSUE TITLE
Returning plt instead of figure in visualize subgraphs

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#1199]
https://github.com/rusty1s/pytorch_geometric/blob/dab4f5fa4ff09b0ca714d3802e2141c0bb535f91/torch_geometric/nn/models/gnn_explainer.py#L243

**Comment by rusty1s** [comment]
Yeah, I decided to do it that way, so that users can either save the file or show it. Do you have any suggestions to make this better?

**Comment by jlevy44** [comment]
If you are returning plt, then you would be returning the actual pyplot module itself: (import matplotlib.pyplot as plt)
I think returning ax would be helpful, and in addition, returning the subgraph G would also be very helpful, perhaps even as some intermediate method that is called before plotting G so users can just export the networkx graph and optionally plot.

This is great though! I'm really happy that you have an implementation of this and is very impressive. 

I may create a separate issue for this, but it does not seem to work with GATConv, only GCNConv as the base convolutional operator.

**Comment by rusty1s** [comment]
Yeah, please create a separate issue for this. I will look into this :)
For visualization, I guess you are right (it seems like I am a complete matplotlib noob :D). I will return `ax` and the `networkx` graph.
