### ISSUE TITLE
关于pytorch_geometric，可加群857449786 注明（pytorch_geometric）共同学习，谢谢  已经解决了win10下关于pytorch_geometric下训练自己数据集的问题，如有不了解的，可以交流

### ISSUE THREAD

**Issue by QQ1282898768** [rusty1s/pytorch_geometric#1200]
关于pytorch_geometric，可加群857449786 注明（pytorch_geometric）共同学习，谢谢

已经解决了win10下关于pytorch_geometric下训练自己数据集的问题，如有不了解的，可以交流

**Comment by rusty1s** [comment]
Can you translate that into English?

**Comment by kunshouout** [comment]
It's not appropriate to put ads here @QQ1282898768
