### ISSUE TITLE
Integrating source_to_target and target_to_source flow in bipartite graph.

### ISSUE THREAD

**Issue by arushi-08** [rusty1s/pytorch_geometric#1210]
## ❓ Questions & Help

Hello! Thank you for building such a well-documented and well-maintained library. I'm new to Graph Neural Networks, and I am learning to build a bipartite graph network, for the following nodes:
![github_issue](https://user-images.githubusercontent.com/40266350/81548309-bb02f000-939a-11ea-916f-e1e46f98da65.jpeg)

I have gone through issues page to understand how to integrate source_to_target and target_to_source flows for some nodes. 
So currently, I made 2 BipartiteData objects, where edge_index is defined differently: 

```
x_s = ... # size [7, 300]
x_t = ... # size [7, 11]
edge_index_1 = torch.tensor([[0, 1, 4, 4, 4, 4, 6], [3, 1, 0, 2, 5, 6, 4]], dtype=torch.long) #for source_to_target
edge_index_2 = torch.tensor([0, 1, 2, 3, 4, 5, 6], [0, 1, 2, 3, 4, 5, 6]], dtype=torch.long) #for target_to_source
graph_data_1 = BipartiteData(x_s=x_s, edge_index=edge_index_1, x_t=x_t)
graph_data_2 = BipartiteData(x_s=x_s, edge_index=edge_index_2, x_t=x_t)
```

Then, `graph_data_1`  and `graph_data_2` are passed through separate GCN layers; where one overrides `MessagePassing` with `flow = 'source_to_target'` and the other overrides `MessagePassing` with `flow = 'target_to_source'`. 

Is this a good approach to this problem? Also, how do I further join the outputs of the 2 GCN layers and get an overall node representation?

Your clarification will be appreciated :)

**Comment by arushi-08** [comment]
Hi @rusty1s I will elaborate and reframe my problem here for you:

Aim: I need to find the node representations of source nodes, from this bipartite graph.

Question 1: Does the MessagePassing network only flow from target_to_source or source_to_target? (Note: I don't need undirected graph as shown in the image above)

If so, then I need to define 2 BipartiteData objects with different edge_indices for the forward and backward flow (example shown in the code above). I defined 2 MessagePassing Networks and sent one BipartiteData object to one of the networks.

Question 2: How do I arrive at the correct representation of source nodes? Should I aggregate the outputs of the above 2 networks? But the output of the source_to_target flow network will be the node representation of target nodes.

What do you suggest?

**Comment by rusty1s** [comment]
Hi and sorry, I missed that one!

First of all, you do not need to `data` objects, you can also store them in a single `data` object, *e.g.*, via `data.edge_index_s2t` and `data.edge_index_t2s`. However, your approach works fine as well.

Furthermore, I don't think you need to consider different flow directions at all. Just pass messages using the two different edge indices, *e.g.*:
```python
x_new_s = conv((x_t, x_s), edge_index_t2s, size=(x_t.size(0), x_s.size(0))
x_new_t = conv((x_s, x_t), edge_index_s2t, size=(x_s.size(0), x_t.size(0))
... # repeat
```
If you are only interested in reading out representations of source node, you can then use the final representation of `x_s` to make predictions. 

I hope this helps!

**Comment by arushi-08** [comment]
I understand. But how do I add the two `edge_index`(for s_t and t_s)  into one Bipartite object? Since it is defined as:
```
class BipartiteData(Data):
    def __init__(self, edge_index, x_s, x_t):
        super(BipartiteData, self).__init__()
        self.edge_index = edge_index
        self.x_s = x_s
        self.x_t = x_t
```
That means I can pass only one edge_index in one BipartiteData: 
`x = BipartiteData(edge_index, x_s, x_t)`

**Comment by rusty1s** [comment]
You can also define it as
```python
class BipartiteData(Data):
    def __init__(self, edge_index_s2t, edge_idnex_t2s, x_s, x_t):
        super(BipartiteData, self).__init__()
        self.edge_index_s2t = edge_index_s2t
        self.edge_index_t2s = edge_index_t2s
        self.x_s = x_s
        self.x_t = x_t

    def __inc__(self, key, item):
        ...
```
There is no limitation in how many attributes you can store in `data`.

**Comment by arushi-08** [comment]
Right! I modeled BipartiteData class accordingly. 

I now have doubt: you mentioned above that we can input tuple `(x_t,x_s)` in conv layer:
`x_new_s = conv((x_t, x_s), edge_index_t2s, size=(x_t.size(0), x_s.size(0)))`
However, there is no `conv` layer in `torch_geometric.nn`  that accepts input as tuple because the first operation in forward function is matmul: `x = torch.matmul(x, self.weight)`
Is there an example or any conv class that works with input tuple?

**Comment by rusty1s** [comment]
Please look at `SAGEConv` at `GATConv`. It is correct that not all operators support this (e.g. `GCNConv`, but this is something that I want to implement. Any help appreciated on that one :)

**Comment by arushi-08** [comment]
Sure! I will try to help out as much as I can!
And yes thank you for your response! I saw it in another issue that `SAGEConv` and `GATConv` are used for bipartite.

I have another question now. What should the `in_channels` be for initializing the bipartite graph? 
As in my case x_s is of size [7,300] and x_t is of size [7,11] so I did this:
```
conv1 = GATConv(300, 256) # (size of input nodes (x_s) , output node size)
conv2 = GATConv(11, 256) # (size of input nodes (x_t) , output node size)
x_new_t = conv1((x_s, x_t), edge_index_s2t, size=(x_s.size(0), x_t.size(0)))
x_new_s = conv2((x_new_t, x_s), edge_index_t2s, size=(x_new_t.size(0), x_s.size(0)))
```

I am getting size mismatch error in this line of `GATConv`'s forward function:
```
x = (None if x[0] is None else torch.matmul(x[0], self.weight),
        None if x[1] is None else torch.matmul(x[1], self.weight))
```
Error is: `RuntimeError: size mismatch, m1: [574 x 11], m2: [300 x 256] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41`

**Comment by arushi-08** [comment]
I think I should modify the GATConv layer and add another self.weight in init function:
```
# in_channels_s = 300
self.weight_1 = Parameter(torch.Tensor(in_channels_s,  heads * out_channels))
# in_channels_t = 11
self.weight_2 = Parameter(torch.Tensor(in_channels_t, heads * out_channels))
```

This way I can do this in GATConv forward function:
```
x = (None if x[0] is None else torch.matmul(x[0], self.weight_1),
        None if x[1] is None else torch.matmul(x[1], self.weight_2))
```

Is this correct?

**Comment by arushi-08** [comment]
Okay I made the above changes but I am getting this error again in the same place:
`RuntimeError: size mismatch, m1: [651 x 256], m2: [11 x 256] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41`

**Comment by arushi-08** [comment]
Is it possible to split the final node representation (giant graph) `x of size [sum of nodes, node size]` into sub-graphs `x of size [nodes of one graph, node size]` after all operations?
And then is it possible to add padding to these sub-graphs and make a final Tensor of size: `[padding + nodes of one graph, node size]`?

**Comment by rusty1s** [comment]
What about using PyG's `to_dense_batch`:
```python
x = to_dense_batch(x, batch)  # `x` now has shape [batch_size, num_nodes, num_features]
```

**Comment by arushi-08** [comment]
Hey, Thank you for the suggestion!
When I called the `Dataloader(list of Bipartite_graph objects, batch_size)` object, its batch attribute is showing None, however batch attribute was not None when I ran the Bipartite example (shown here: https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html?highlight=bipartite#bipartite-graphs)
And I think that is because of my __inc__() function in Bipartite_graph class. I may have not correctly overridden it:
```
def __inc__(self, key, value):
      # Returns the incremental count to cumulatively increase the value
      # of the next attribute of :obj:`key` when creating batches.
      if (key == 'edge_index_s2t' or key == 'edge_index_t2s'):
          return torch.tensor([[self.x_s.size(0)], [self.x_t.size(0)]])
      else:
          return super(BipartiteData, self).__inc__(key, value)
```
Is this right?

I have compared my code to the bipartite example and this line may be the problem: 
```
if (key == 'edge_index_s2t' or key == 'edge_index_t2s'):
          return torch.tensor([[self.x_s.size(0)], [self.x_t.size(0)]])
```

**Comment by rusty1s** [comment]
Yeah, the batch object is known because PyG cannot identify how to create it. You can pass the `follow_batch` argument to the `DataLoader` to signal PyG which batches it should track:
```python
def __inc__(self, key, value):
      # Returns the incremental count to cumulatively increase the value
      # of the next attribute of :obj:`key` when creating batches.
      if (key == 'edge_index_s2t':
          return torch.tensor([[self.x_s.size(0)], [self.x_t.size(0)]])
      elif (key == 'edge_index_t2s':
          return torch.tensor([[self.x_t.size(0)], [self.x_s.size(0)]])
      else:
          return super(BipartiteData, self).__inc__(key, value)


loader = DataLoader(dataset, batch_size=..., follow_batch=['x_s', 'x_t'])
```

**Comment by arushi-08** [comment]
Hey! Thank you so much for solving so many issues.
I will close this thread now.

**Comment by jiaqian** [comment]
@arushi-08 Hi, did you manage to solve the dimension mismatch issue (`Error is: RuntimeError: size mismatch, m1: [574 x 11], m2: [300 x 256] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41`)? I am facing the same problem.

**Comment by rusty1s** [comment]
Where does this issue happen?

**Comment by jiaqian** [comment]
Hi, I have two types of nodes (their node attributes defined as x_s, x_t) with different dimensions, say **m** and **n**. So I define two SAGEConv layers with in_channel equal to **m** and **n**. The mismatch issue happens when I run conv1((x_s, x_t), edge_index_s2t, size=(x_s.size(0), x_t.size(0))).

**Comment by rusty1s** [comment]
Do you have a small example for me to reproduce? This is definitely not intended.

**Comment by jiaqian** [comment]
I have solved the mismatch issue, but actually I have another problem.
`class BipartiteData(Data):
    #
    def __init__(self, edge_index_s2t=None, edge_index_t2s=None, x_s=None, x_t=None):
        super().__init__()
        self.edge_index_s2t = edge_index_s2t
        self.edge_index_t2s = edge_index_t2s
        self.x_s = x_s
        self.x_t = x_t
        self.num_feas = (x_s.size(1), x_t.size(1))

    def __inc__(self, key, value):
        # Returns the incremental count to cumulatively increase the value
        # of the next attribute of :obj:`key` when creating batches.
        if key == "edge_index_s2t":
            return torch.tensor([[self.x_s.size(0)], [self.x_t.size(0)]])
        elif key == "edge_index_t2s":
            return torch.tensor([[self.x_t.size(0)], [self.x_s.size(0)]])
        else:
            return super(BipartiteData, self).__inc__(key, value)
data = BipartiteData(edge_index_s2t, edge_index_t2s, x_s, x_t)
loader = DataLoader(data, batch_size=1, follow_batch=["x_s", "x_t"])
print(next(iter(loader)))`

the last row gives me error, I think data is not iterable.
Thanks in advance.

**Comment by rusty1s** [comment]
`DataLoader` can create mini-batches out of a list of `data` objects:
```python
loader = DataLoader([data], batch_size=1, follow_batch=["x_s", "x_t"])
```
If you want to create subgraphs from a single `data` object, have a look at `NeighborLoader`.

**Comment by jiaqian** [comment]
Is there any tutorial about creating sub-bipartite-graphs from a single `data` object?

**Comment by rusty1s** [comment]
The easiest solution is to represent your bipartite graph as a `HeteroData` object with two node types. You can then use the `NeighborLoader` to create mini-batches out of this. See [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html) for the tutorial.
