### ISSUE TITLE
number of edges for planetoid is different from paper

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [rusty1s/pytorch_geometric#1215]
Hello,

It seems that the number of edges for cora in pyG is 100556/2=5278 while the GCN paper report that cora has 5429 edges. The edge number difference also holds for citeseer and PubMed. Why is the edge number different from the paper?

**Comment by rusty1s** [comment]
Please see https://github.com/rusty1s/pytorch_geometric/issues/852.
