### ISSUE TITLE
Number of parameters in each layer

### ISSUE THREAD

**Issue by arshishir** [rusty1s/pytorch_geometric#1216]
Is there a way to print out the number of parameters in each layer something like model.summary() offered by kears?
Also, is there a way to visualize the neural network something like this (https://user-images.githubusercontent.com/1444164/49574693-51e8a300-f984-11e8-9394-3db4e6df07a7.png) ?

Thanks

**Comment by rusty1s** [comment]
Well, you can print out your model or use tensorboard to visualize it. In the end, all helper tools available for PyTorch can be also used for PyTorch Geometric, e.g. PyTorch Lightning (which supports summary())

**Comment by arshishir** [comment]
Thanks @rusty1s. I am using `model.parameters()` to count parameters.  I will look into PyTorch lightning.

**Comment by arshishir** [comment]
I just found that `https://pypi.org/project/pytorch-model-summary`/ gives you a nice way to view the model summary.
