### ISSUE TITLE
Is it possible to have edge_weight for GINConv?

### ISSUE THREAD

**Issue by shi27feng** [rusty1s/pytorch_geometric#1217]
The question is as the title:

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{x}^{\prime}_i&space;&=&space;h_{\mathbf{\Theta}}&space;\left(&space;(1&space;&plus;&space;\epsilon)&space;\cdot&space;\mathbf{x}_i&space;&plus;&space;\sum_{j&space;\in&space;\mathcal{N}(i)}&space;\mathbf{x}_j&space;\right)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\mathbf{x}^{\prime}_i&space;&=&space;h_{\mathbf{\Theta}}&space;\left(&space;(1&space;&plus;&space;\epsilon)&space;\cdot&space;\mathbf{x}_i&space;&plus;&space;\sum_{j&space;\in&space;\mathcal{N}(i)}&space;\mathbf{x}_j&space;\right)" title="\mathbf{x}^{\prime}_i &= h_{\mathbf{\Theta}} \left( (1 + \epsilon) \cdot \mathbf{x}_i + \sum_{j \in \mathcal{N}(i)} \mathbf{x}_j \right)" /></a>

if possible, it becomes

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{x}^{\prime}_i&space;=&space;h_{\mathbf{\Theta}}&space;\left(&space;w_i&space;\cdot&space;\mathbf{x}_i&space;&plus;&space;\sum_{j&space;\in&space;\mathcal{N}(i)}&space;w_j&space;\cdot&space;\mathbf{x}_j&space;\right)" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\mathbf{x}^{\prime}_i&space;=&space;h_{\mathbf{\Theta}}&space;\left(&space;w_i&space;\cdot&space;\mathbf{x}_i&space;&plus;&space;\sum_{j&space;\in&space;\mathcal{N}(i)}&space;w_j&space;\cdot&space;\mathbf{x}_j&space;\right)" title="\mathbf{x}^{\prime}_i = h_{\mathbf{\Theta}} \left( w_i \cdot \mathbf{x}_i + \sum_{j \in \mathcal{N}(i)} w_j \cdot \mathbf{x}_j \right)" /></a>

and, is it an unnormalized GCNConv?

**Comment by rusty1s** [comment]
I suggest to copy-paste the `GINConv` class and add this functionality to it. I would rather not implement this in `GINConv` directly as this layer is not defined that way.

**Comment by shi27feng** [comment]
Thank you for the prompt response.
