### ISSUE TITLE
Incorrect arguments in instanciation of Planetoid in examples/gnn_explainer.py

### ISSUE THREAD

**Issue by afshinrahimi** [rusty1s/pytorch_geometric#1219]
## 🐛 Bug

The argument T.NormalizeFeatures() is used as a positional argument while it should have been used as a keyword argument e.g. transform=T.NormalizeFeatures(). Otherwise it assumes it is the split argument and the assertion in line 59 is triggered.
## To Reproduce
python gnn_explainer.py

1.python gnn_explainer.py
1.
1.

## Expected behavior

The argument T.NormalizeFeatures() is used as a positional argument while it should have been used as a keyword argument e.g. transform=T.NormalizeFeatures(), e.g. Planetoid(path, dataset, transform=T.NormalizeFeatures()) instead of Planetoid(path, dataset, T.NormalizeFeatures()) in line 13 of gnn_explainer.py
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Thanks! `Planetoid` got a few new arguments which broke the examples. It is fixed now!
