### ISSUE TITLE
OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OrdinaryCrazy** [rusty1s/pytorch_geometric#1220]
## 📚 Installation

OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory

## Environment

* OS: Ubuntu16.04
* Python version: 3.6.3
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 9.0.176
* GCC version: 5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): source
* Any other relevant information: install pytorch and torchvision from source

## Checklist

- [ y] I followed the installation guide.
- [ y] I cannot find my error message in the FAQ.
- [ y] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ y] I have cloned the repository and tried a manual installation from source.
- [ y] I do have multiple CUDA versions on my machine.
- [ y] I checked if the official extension example runs on my machine.
- [ n] The offical extension example runs on my machine.

## Additional context

run on remote machine without sudo privilege

**Comment by rusty1s** [comment]
I do not think PyTorch supports CUDA 9.0 anymore, it instead looks for CUDA 9.2. any chance you can upgrade your CUDA?

**Comment by OrdinaryCrazy** [comment]
right, so I am applying for another machine

**Comment by OrdinaryCrazy** [comment]
> I do not think PyTorch supports CUDA 9.0 anymore, it instead looks for CUDA 9.2. Any chance you can upgrade your CUDA?

I got nividia 384 driver, sad, can not support cuda 9.2
