### ISSUE TITLE
from_networkx and to_networkx doesn't return the right result.  

### ISSUE THREAD

**Issue by hugovergnes** [rusty1s/pytorch_geometric#1221]
## 🐛 Bug

When I use from_networkx and to_networkx following each other I don't get the right answer. As I expect to get the same output and input. 

## To Reproduce
```
from torch_geometric.utils import *
pos = torch.tensor([[1,1],[0,0]])
edge_index = torch.tensor(([[0],[1]]))

G = to_networkx(Data(pos=pos, edge_index=edge_index))
data = from_networkx(G)

print(from_networkx(G).pos is None)
True
```

I expect to have the pos atribute unchanged. 

## Environment

* OS: Ubuntu 18.04
* Python version: python 3.7.7
* PyTorch version:1.4.0
* CUDA/cuDNN version:101

**Comment by rusty1s** [comment]
Easy fix :)
```
G = to_networkx(Data(pos=pos, edge_index=edge_index), node_attrs=['pos'])
```
