### ISSUE TITLE
Retrieve the Node embedding

### ISSUE THREAD

**Issue by elbasir** [rusty1s/pytorch_geometric#1226]
Hi all,

My question is about how I can retrieve the node embedding that is learned either in GCN, GAT or any other optimized GCN technique? Is there any way to return it and save it? I want to use the node embedding for clustering and use it as well as an input to a machine learning algorithm for classification.

Thanks,

**Comment by rusty1s** [comment]
If I understand you correctly, you can just save/return the output of `GCNConv` or `GATConv` in your model.

**Comment by elbasir** [comment]
Does it return the entire graph embedding or every node embedding? I am interested in saving each node embedding and use it later for clustering. 

For example, if my graph has 5000 nodes, what's the mechanism to return each node embedding that corresponds to each node in the graph?

**Comment by rusty1s** [comment]
Well, each `conv` returns node embeddings, so in your model you can do the following:
```python
def forward(self, x, edge_index):
    xs = [x]
    xs += [conv(xs[-1], edge_index)
    xs += [conv(xs[-1], edge_index)
    return xs
```

**Comment by elbasir** [comment]
Thanks, I will try it and let you know. Will it return each node embedding individually or in batches?
