### ISSUE TITLE
What does each attention weight refer to in GATConv?

### ISSUE THREAD

**Issue by douglasrizzo** [rusty1s/pytorch_geometric#1227]
## ❓ Questions & Help

Hello there. I saw that, in the master branch, GATConv has an option to return the attention weights after a call to `forward()`. The number of attention weights is equal to the number of edges + added self loops.

How do I know which attention weight belongs to which edge? Are they returned in the same order as `edge_index`? Where are the weights regarding self loops added? Thanks in advance.

---
I made an example with 4 nodes and 7 edges, which returned 11 weights, but I can't figure to which edge each weight refers to.

```python
import torch
import torch_geometric as pyg

torch.manual_seed(0)
l = pyg.nn.GATConv(6,6)
x = torch.distributions.normal.Normal(0,1).sample((4,6))
ei = torch.tensor([[1,2,2,0,3,0,1],
                   [0,0,1,2,2,3,3]],dtype=torch.long)

x, alpha = l(x,ei,return_attention_weights=True)

print(alpha)
```
```
tensor([[0.2542],
        [0.2742],
        [0.5898],
        [0.4758],
        [0.2371],
        [0.6427],
        [0.1914],
        [0.4715],
        [0.4102],
        [0.2871],
        [0.1659]], grad_fn=<DivBackward0>)
```

**Comment by douglasrizzo** [comment]
I think I'm finding the answer myself. By calling:

```python
edge_index = torch.tensor([[1,2,2,0,3,0,1],
                   [0,0,1,2,2,3,3]],dtype=torch.long)

edge_index, _ = pyg.utils.loop.remove_self_loops(edge_index)
edge_index, _ = pyg.utils.loop.add_self_loops(edge_index)
```

just like GATConv does, I realized the self loops are added at the end of `edge_index`. So I'd guess the weights from `alpha` refer to the edges in `edge_index` with self loops added to the end, in order.

**Comment by rusty1s** [comment]
That's correct. I agree that this is not really elegant. What do you think about removing the attention scores of self-loops before returning them?

**Comment by douglasrizzo** [comment]
I'm consulting the GAT paper. They never mention adding self loops to the input graph before doing a forward pass, i.e. all operations are done in `N(i)` and not `N(i) U {i}`. Maybe GATConv should only generate and use attention weights for the loops (and self loops) that are declared in the `edge_index` that is provided to `forward()`. This way, if/when GATConv returns `alpha`, the outside code can use the existing `edge_index` to know where each weight comes from.

Unless there is a good reason to always add self loops. Then I believe `forward()` could 
`return x, alpha, edge_index` or save `edge_index` into an object attribute (just like it is done with `alpha`) and provide it alongside with `alpha` via an outside method, such as

```python
def get_attention_weights(self):
    return self.alpha, self.edge_index
```

Anyway, it doesn't look correct to not return the attention weights of the self loops. After all, they are used by the network and others might find it useful to have access to them.

**Comment by rusty1s** [comment]
You are right! I like your solution and will implement something like
```python
def get_attention_weight(self, x, edge_index):
    # ...
    return self.edge_index, self.alpha
```

Regarding addition of self-loops: Although the GAT paper never mentions that, it is clear that self-loops need to be added to make GAT work (due to maintaining central node information). This is also shown in Fig. 1 in the paper.

**Comment by rusty1s** [comment]
Done, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gat_conv.py#L127-L134).

**Comment by douglasrizzo** [comment]
In this implementation, the network needs to make a forward pass in order to return the attention weights. Why not save `self.__edge_index__` alongside `self.alpha` inside forward when `return_attention_weights==True`, just as was being done previously and, when a user calls `get_attention_weight()`, the network returns the weights from the previous forward pass? This prevents the network from having to do two forward passes if the user wants both the outputs and the attention weights...

If someone wants the attention weights for a specific input, they can call `forward()` themselves to update `self.__edge_index__` and `self.alpha` and then call `get_attention_weight()`.

I say this because I myself access the attention weights at training time and this implementation would mean having to do twice the number of forward passes.

Also, I saw the self loops in the picture, in the paper. You seem to be right about adding the self loops.

**Comment by douglasrizzo** [comment]
Do you mind if I give a shot at a PR?

**Comment by rusty1s** [comment]
Personally, I am not a big fan of this because I feel like internal state is always a bad thing and does not really mimic the functional API of PyTorch. Note that with the current approach you can also just set `conv.__save_att__ = True` and access the alpha scores after a forward pass - you do not need double the number of forward passes - but I agree, this isn't good design either. Feel free to make a PR and we can discuss the details there.
