### ISSUE TITLE
edge representation of directed graph

### ISSUE THREAD

**Issue by Elizabeth1997** [rusty1s/pytorch_geometric#1230]
## ❓ Questions & Help

Hi @rusty1s , if one directed graph's edge index is presented by this  
`edge_index = torch.tensor([[0, 1], [1, 2]], dtype=torch.long)`  
Does it mean there is an edge from node 0 pointing to node 1 or node 1 pointing to node 0?

**Comment by rusty1s** [comment]
An edge from node 0 pointing to node 1, and an edge from node 1 pointing to node 2.

**Comment by Elizabeth1997** [comment]
Got it. Many thanks for your reply :)
