### ISSUE TITLE
Samples about GAT

### ISSUE THREAD

**Issue by xiangzhang1015** [rusty1s/pytorch_geometric#1231]
## ❓ Questions & Help

I love your elegant code at

> https://github.com/snap-stanford/ogb/blob/eb3e87434ef2a1c90461ec0cb65b10259a0bea1e/examples/nodeproppred/arxiv/full_batch.py#L16

, where you provided the Class of `GCNConv `and `SAGEConv`. I found that sometimes they work better than the Class at torch_geometric.nn.GCNConv.

May I know where to find more samples on other GNN models (e.g., GAT, GIN) in this way? In specific, I mean the GATConv/GINConv Class inherent `torch.nn.Module` instead of `torch_geometric.nn.conv.MessagePassing`.  

If there was not more examples, may I know what's the `g` represents at here 

> https://github.com/rusty1s/pytorch_geometric/blob/9d3df0eb4842514fbaa857afb75f23d9345148f5/benchmark/runtime/dgl/gat.py#L11
Is that activation function?

Thanks a lot.

**Comment by rusty1s** [comment]
This is something I am currently working on, and will be included in PyG 2.0. Please stay tuned! :)

**Comment by xiangzhang1015** [comment]
Thank you for answering. Looking forward to PyG 2.0~~
