### ISSUE TITLE
Add warning if edge_index tensor has wrong datatype

### ISSUE THREAD

**Issue by deklesen** [rusty1s/pytorch_geometric#1235]
## 🚀 Feature

If a user creates a Data() object with edge_index being e.g. a float tensor, provide him with a warning or even an error.

## Motivation

I was frustrated because I accidentally used floats in my edge_index tensor and the TAGConv layer gave me this cryptic error:
![image](https://user-images.githubusercontent.com/19559859/82163381-15281780-98ab-11ea-82ef-b82b90e72fa8.png)

Thanks for all the work, really liking this so far, except for some small hickups here and there :)

**Comment by rusty1s** [comment]
Done, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/data.py#L80-L88).
Note that for more advanced data checking, you can also use `data.debug()`.
