### ISSUE TITLE
 Does torch_geometric.nn.conv.gcn_conv method has 'padding' method?

### ISSUE THREAD

**Issue by yuanjames** [rusty1s/pytorch_geometric#1237]
## ❓ Questions & Help

Hi, the input of graphs may have different size (e.g. different nodes number), does gcn_conv will use zero-padding on them, to keep every graph same?

**Comment by rusty1s** [comment]
No, we don't need to use padding in PyG. Separation of graph objects is done via the `batch` tensor. You can read more about it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches).

**Comment by yuanjames** [comment]
> No, we don't need to use padding in PyG. Separation of graph objects is done via the `batch` tensor. You can read more about it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches).

Many thanks for your reply and support, I see the example in the document, each batch packs 32 graphs, would the edge_index variable has a different size in per enumeration, as another 32 graphs total number of edges may vary?

**Comment by rusty1s** [comment]
Yes.

**Comment by yuanjames** [comment]
> No, we don't need to use padding in PyG. Separation of graph objects is done via the `batch` tensor. You can read more about it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches).



> Yes.

Thank you so much. It's very cool and smart!

The formulation (DADXW) looks does not require each graph in the same size. The output size will be always (nodes number, W.shape[1] ), right? But, if we will flatten them into a fully-connected NNs to do regression, they must be in same size.

**Comment by rusty1s** [comment]
If you want to flatten them, you need to pad them with zeros, *e.g.*, with `torch_geometric.utils.to_dense_batch`. However, as long as the permutation of your graph does not have a special meaning, I wouldn't recommend flattening at all.

**Comment by yuanjames** [comment]
> If you want to flatten them, you need to pad them with zeros, _e.g._, with `torch_geometric.utils.to_dense_batch`. However, as long as the permutation of your graph does not have a special meaning, I wouldn't recommend flattening at all.

Got it, thanks

**Comment by yuanjames** [comment]
> > If you want to flatten them, you need to pad them with zeros, _e.g._, with `torch_geometric.utils.to_dense_batch`. However, as long as the permutation of your graph does not have a special meaning, I wouldn't recommend flattening at all.
> 
> Got it, thanks

Hi, just to supplement the reason why I need to flatten them, I need to do a regression task for each graph, output a property of the graph.

**Comment by rusty1s** [comment]
This is commonly done by `global_pooling` methods, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.glob).

**Comment by yuanjames** [comment]
> This is commonly done by `global_pooling` methods, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.glob).

Agree with you, not padding, using mean or other fixed-size value(s) to further computing
