### ISSUE TITLE
update the edgeweight of undirected graph

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [rusty1s/pytorch_geometric#1239]
Hello,

I have a gnn that will assign edge weight based on the topology of the subgraph. For each batch, I will update say 16 edge weights of one graph. Since the graph is undirected, it is expected that when edge weight (stored in the g.edge_weight as a tensor of size (n_edge)) corresponding to edge [1, 2] is updated, the weight of edge [2, 1] will be 'automatically' updated.   

Do you know what's a good way to force the weight of two edges to be the same all the time? If this can not be done, I probably will have to find the location of edge [2, 1] when updating edge [1, 2] and it seems quite awkward.  

Thank you very much!

**Comment by rusty1s** [comment]
One possible way to achieve this is to only save one direction in `edge_index` and use a custom GNN operator where you `propagate` twice (with different flows):
```python
self.flow = 'source_to_target'
h= self.propagate(edge_index, x=x, edge_weight=edge_weight)
self.flow = 'target_to_source'
h= h + self.propagate(edge_index, x=x, edge_weight=edge_weight)
```

**Comment by Chen-Cai-OSU** [comment]
Thank you very much!
