### ISSUE TITLE
I hope to see GGNN model in here

### ISSUE THREAD

**Issue by ahzz1207** [rusty1s/pytorch_geometric#124]
Microsoft released the GGNN model for code understanding last year. Although it has been open-source, I don't know why I haven't seen it in this repository. I hope I can get its pytorch implementation!
thank you

**Comment by rusty1s** [comment]
* [Code](https://github.com/Microsoft/gated-graph-neural-network-samples)
* [Paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/programGraphs.pdf)

**Comment by rusty1s** [comment]
Pushed to master! See [here](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.conv.GatedGraphConv) for its documentation. Does this fit your needs?
