### ISSUE TITLE
Training graphs with different topology in batches

### ISSUE THREAD

**Issue by nshervt** [rusty1s/pytorch_geometric#1243]
## ❓ Questions & Help

I have a dataset of molecular graphs. Before, I used to work with a graph network that took weight matrix of fixed size as input [batch, node, node]. Now, I'm trying to use `GCNConv` (or any other method) for comparison. I have noticed that this method takes a matrix of connectivity with size [2, num_edges]. This means that I have inputs of different sizes. I was wondering how can we pass these in batches? Is there an example for this on the repository?

**Comment by rusty1s** [comment]
Our `DataLoader` supports batch-mode automatically. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py), and a short tutorial [here](/).

**Comment by nshervt** [comment]
Thanks for the links. So from what I understand, I need to turn my data into `x, edge_index, edge_attr` format and from there I can use `DataLoader`.

**Comment by nshervt** [comment]
Thanks for the links. So from what I understand, I need to turn my data into `x, edge_index, edge_attr` format and from there I can use `DataLoader`. Just to confirm, by 'automatically' you don't mean that it extracts `edge_index` and `edge_attr` from a batch of weight matrices. Correct?

**Comment by rusty1s** [comment]
It does not necessarily need to be `x` or `edge_attr`, any naming/feature is allowed. What I mean by automatically is that the PyG DataLoader cares about correctly forming batches of graphs, and there is generally no manual intervention necessary.
