### ISSUE TITLE
On VAE encoder in the examples

### ISSUE THREAD

**Issue by nshervt** [rusty1s/pytorch_geometric#1244]
## ❓ Questions & Help

I'm trying to use the [encoder](https://github.com/rusty1s/pytorch_geometric/blob/d44a2f8e8bed21e2e5a84ccee223039c0bd6de82/examples/autoencoder.py#L33) in the VAE example. I wrote the function as
```
def encode(self, x, edge_index):
    x = F.relu(self.conv1(x, edge_index))
    return self.conv_mu(x, edge_index), self.conv_logvar(x, edge_index)
```
where
```
self.conv1 = GCNConv(num_node_features, 2 * self.z_dim, cached=True)
self.conv_mu = GCNConv(2 * self.z_dim, self.z_dim, cached=True)
self.conv_logvar = GCNConv(2 * self.z_dim, self.z_dim, cached=True)
```
and `x` has dimensions `[num_nodes, num_node_features]` where `num_nodes` is the sum of number of nodes in all the graphs. My question is, given latent space
```
z = model.encode(x, edge_index)
```
 I'm expecting to get a single point in the latent space for each graph. However, the implementation gives me a point in the latent space for each node (output shape `[num_nodes, z_dim]`). I was wondering how should I modify this network to get a single point representing each graph rather than node? Thanks.

**Comment by rusty1s** [comment]
Yes, the official `GAE` is not meant to reduce the node dimension. If you want to do that, you need to pool your graph into a graph representation (*e.g.* via `global_mean_pool`), and try to reconstruct adjacency matrices from there (via your own decoder implementation).

**Comment by nshervt** [comment]
Thanks!
