### ISSUE TITLE
Graph Generation

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#125]
How suitable is pytorch_geometric for graph generation? Looking to generate adjacency A from A and X using an autoregressive and/or autoencoding method, and wanted to see how it preserves transitivity versus other ERGM-based methods. I think convincing others that these models are preserving transitivity and do not rely on conditional independence is essential in moving this science forward.

Thanks!

**Comment by jlevy44** [comment]
In addition, I'm wondering if netGAN and graphRNN could be implemented with an option to input covariate matrices as well as more traditional graph summary statistics.

**Comment by jlevy44** [comment]
I think what I'm having trouble getting past is that there is not a ConvTranspose2d, if I wanted to implement graphVAE, as in the standard pytorch library. Is that even needed?

**Comment by rusty1s** [comment]
Hi,
Let‘s discuss this in https://github.com/rusty1s/pytorch_geometric/issues/98#issuecomment-472083487
