### ISSUE TITLE
CUDA10.2 install problem (OSError: libcusparse.so.10)

### ISSUE THREAD

**Issue by hcw0098** [rusty1s/pytorch_geometric#1253]
I install the PyG and meet the following problem:
OSError: libcusparse.so.10:

Cuda version =10.2 , but advised command only contains cuda 10.1, so I install PyG using following conmands  :
$ pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
$ pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
$ pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
pip install torch-geometric
And I export the PATH with command:
export PATH=/usr/local/cuda-10.2/bin:$PATH

Don't know where i did wrong.Hope you could help me

**Comment by hcw0098** [comment]
Oh , I try to solve the problem by changing the cuda version in the command to cu102, it did,'t work. 
So the actual error info is :
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by rusty1s** [comment]
Awesome. I think this is resolved.
