### ISSUE TITLE
NeighborSampler / DataFlow question

### ISSUE THREAD

**Issue by MilesCranmer** [rusty1s/pytorch_geometric#1255]
## ❓ Questions & Help

Hi, I am a bit confused about the definition of `n_id` in NeighborSampler's output blocks. From what I can tell, it should be the nodes referred to by edge_index. However, I verified by hand that if I take that as the definition, the nodes are not connected. 

Basically, I have a large sparse graph which I then sample (single layer around each node) with NeighborSampler using:

```
sampler = NeighborSampler(Data(
    X,
    edge_index=edge_index,
    y=y),
    size=1.0, num_hops=1, batch_size=32, shuffle=True)
```

Then, when I take a sample like this:
```
for subgraph in trainloader():
    break
```

I observe that none of the nodes in subgraph.n_id are in subgraph.blocks[0].n_id:

```
np.isin(
    subgraph.n_id.numpy(),
    subgraph.blocks[0].n_id.numpy())
> array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])
```

So, my question is: what is the difference between n_id in subgraph and blocks[0].n_id? They are both very large sets of numbers so I assume they are indexes for nodes in my original graph, but curiously neither overlaps. 

Another way of solving this: is there a way to convert this subgraph (a dataflow) into a new `Data` object? I have been trying to do this manually but I'm not sure which `n_id` correspond to what edge.

Thank you!
Best,
Miles

**Comment by MilesCranmer** [comment]
Let me see if I understand it:

subgraph.n_id is the receiving nodes.

subgraph.blocks[0].n_id is the sending nodes.

subgraph.blocks[0].edge_index[0] indexes the sending nodes.

subgraph.blocks[0].edge_index[1] indexes the receiving nodes.

is this correct?

Thanks!
Miles

**Comment by rusty1s** [comment]
That is correct! However, I agree that the `NeighborSampler` interface was quite unintuitive. I completely revamped the interface in master. It is now much cleaner and way faster than before, even allowing for `num_workers` attributes to allow generation of subgraphs in parallel. Please have a look [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.NeighborSampler) and the examples and tell me if there are any questions.

**Comment by MilesCranmer** [comment]
Fantastic, thanks! I will install the latest version. Thanks for all your work, this library is awesome!!
