### ISSUE TITLE
Message passing for directed graphs

### ISSUE THREAD

**Issue by jzhou316** [rusty1s/pytorch_geometric#126]
Hi, thanks for the great package. I find some potential unclarity of the message passing mechanism when applied to directed graphs. In particular, the `edge_index` includes pairs of `(i, j)` in the edge set, but the aggregation associated with the `MessagePassing` class works by aggregating features from `x_j` to `x_i`, i.e. from target nodes to source nodes. This is fine for undirected graphs, but for directed graphs, we actually want to aggregate features flowing into a node (usually not the opposite way), so `x_j` should be the "source node" and `x_i` should be the "target node". I find these terminologies in the documentation about "source" and "target" a bit misleading. 

Perhaps if not changing the aggregation direction in the `MessagePassing` code, in the definition of `edge_index`, we should make it clear that a pair `(i, j)` in `edge_index` means that there is an edge from `j` to `i`, i.e. in the direction of `j -> i`. This does not influence undirected graphs but helps to reduce errors in dealing with directed graphs.

**Comment by rusty1s** [comment]
Hi, I definitively understand your concerns. However, the message passing interface is based on the [Neural Message Passing paper](https://arxiv.org/pdf/1704.01212.pdf) (Eq. 1), which implements the aggregation from target nodes to source nodes. In addition, the standard equation GCN equation `AXW` also implements the aggregation from target nodes to source nodes.

**Comment by jzhou316** [comment]
Thanks for the prompt reply. I see, but it seems these equations mainly focus on general undirected graphs. For directed graphs, the neighborhood `N(i)` is usually defined as `{j: j -> i}`, i.e. all the nodes pointing to `i`, which I think makes more sense, such as in https://openreview.net/pdf?id=SJexcZc8G. But I agree it could also be a matter of user choices.

**Comment by rusty1s** [comment]
I think we have two options here:
1. Add a flag to the `MessagePassing` interface to denote its message passing direction.
2. Add a remark to the documentation.
Which option do you prefer?

**Comment by jzhou316** [comment]
Both are fine. 1 is perhaps more systematic? Seems can do a minimal change by modifying `edge_index` to `edge_index[torch.LongTensor([1, 0])]` in `MessagePassing.propagate()` according to the direction flag.

**Comment by rusty1s** [comment]
Added to current master!

**Comment by tformal** [comment]
Hi,

Actually, I think the "source" and "target" notations are still misleading. From the doc "Constructs messages to node i in analogy to ϕ for each edge in (j,i)∈E if flow="source_to_target" and (i,j)∈E if flow="target_to_source"", but intuitively I would have done the opposite...

**Comment by rusty1s** [comment]
I think it is much more natural to think of `i` (or `v`) as the central node which aggregates and `j` (or `w`) as the neighboring nodes which get aggregated. This follows the convention of most GNN papers.

**Comment by jzhou316** [comment]
Hi @tformal, I was confused at beginning as well. But after checking the implementation, I think the better way of understanding the document could be the following: fix the notation `i` as the node to gather features to, and the `flow` flag determines how you map the notation `i` and `j` into the source and target nodes. If `source_to_target`, use `j` for the source node and `i` for the target node, and use the opposite otherwise.

**Comment by tformal** [comment]
Hi, thank you both for you answers !
@rusty1s : I totally agree with that, yet I was still confused (I think it was due to the way I interpreted "source" and "target")
@jzhou316  : thanks, I think it indeed helps to understand !
