### ISSUE TITLE
How can I compute a degree of a graph with all nodes?

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1261]
## ❓ Questions & Help

@rusty1s 
I want to compute a degree of graph and I found a func that torch_geometric.utils.degree.
But the func use a parameters named index,I don't know what is index.
Can u tell how to get this 'index' and how to compute the degree of a graph with all nodes?
Thank you very mach!

For example,the code as follow

`from torch_geometric.datasets import TUDataset

from torch_geometric.utils import degree

dataset = TUDataset(root='./data/DD', name='DD')

data = dataset[0]

deg = degree(?????)#how can I use this func to compute data's degree with all nodes?`

**Comment by kkonevets** [comment]
`degree(data.edge_index[0])`

**Comment by jiaruHithub** [comment]
> `degree(data.edge_index[0])`

Thank you very mach!I immediately try your method.It's right!
