### ISSUE TITLE
How can i bulid a graph by superpixel?

### ISSUE THREAD

**Issue by zhenwang1219** [rusty1s/pytorch_geometric#1264]
## ❓ Questions & Help

Hi @rusty1s , your PY_G tool is so great.But i am new to this frame.I want to know how can i build a graph by superpixel. I have use the method **ToSLIC from torch_geometric.transforms** to exatract superpixel information,but i don't know how to get the **edge_index** and **edge_attr**. According torch_geometric.datasets.MNISTSuperpixels , each graph have 75 nodes , but their  edge_index are not the same.
So could you give me some advice about this?

**Comment by rusty1s** [comment]
You can use [`torch_geometric.transforms.RadiusGraph`](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.RadiusGraph) to build a graph using between the superpixels.

**Comment by zhenwang1219** [comment]
> You can use [`torch_geometric.transforms.RadiusGraph`](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.RadiusGraph) to build edges between the superpixels.

OK, thank you so much!
