### ISSUE TITLE
Edge Index for MNIST Superpixels

### ISSUE THREAD

**Issue by koustav123** [rusty1s/pytorch_geometric#1268]
## ❓ Questions & Help

The SplineConv paper applies it to three datasets. FAUST, Cora and MNIST Superpixels. As I understood from the code, for FAUST the edge index is computed from the face vertex representation. For Cora, edge index corresponds to the citation links. I am curious how the edge index is constructed for MNIST superpixels or MNIST Grid representation. 

From mnist_superpixels.py, it seems like the edge index is provided by the authors of "_Geometric Deep Learning on  Graphs and Manifolds Using Mixture Model CNNs_" and loaded here directly.

    def process(self):
        for raw_path, path in zip(self.raw_paths, self.processed_paths):
            x, edge_index, edge_slice, pos, y = torch.load(raw_path) # loads here
            edge_index, y = edge_index.to(torch.long), y.to(torch.long)
            m, n = y.size(0), 75
            .....

My dataset is similar to MNIST Superpixels and I would like to construct my edge index from the image. I couldn't understand how they do it from the paper. Is it based on K-neighbourhood? 

Thanks in advance.

**Comment by rusty1s** [comment]
It‘s actually radius-based, although k-NN should work equally well.

**Comment by koustav123** [comment]
Thanks. I guess I could use KNNGraph or RadiusGraph from utils.
