### ISSUE TITLE
Implementation of Line graph Transformation

### ISSUE THREAD

**Issue by pgtgrly** [rusty1s/pytorch_geometric#127]
Greetings,
I believe that a transform that manipulates a graph stored Data variable and transforms it to it's [line graph](https://en.wikipedia.org/wiki/Line_graph) can be useful. The Networkx implementation for the same can be found [here](https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/generators/line.html#line_graph).

I am working on a regression problem where nodes are featureless and the edges contain a scalar feature (Strength between two nodes). 
Going through the documentation, I was not able to find a convolution layer that uses edge attributes, rather than node attributes (I am quite new to the field of Geometric DL, If there is then please let me know) and thus I plan to use Line graph. I believe that there can be many such cases.

**Comment by rusty1s** [comment]
Hi, This is a good request and would be a nice contribution to PyG. I plan to integrate it. In the meantime, you can write your own `transform` in which you convert your graph to the `networkx` format, call the `line_graph` functionality and convert the data back. This may not be very fast dependent on your dataset size, but may work as a first starting point. I recommend using this transform as `pre_transform`.

**Comment by pgtgrly** [comment]
Hey Matthias,
Thank you, I will do the same.
I am also interested in contributing to PyG and would be glad to implement this as a learning experience.
Please let me know if it is feasible.

**Comment by rusty1s** [comment]
Sure, contributions are always welcome :) I actually think this can be implemented within a few lines of code using just PyTorch and the `edge_index` tensor. Let me know if you need any help.

**Comment by pgtgrly** [comment]
Hey Matthias!
I have implemented the same for the Directed graph, I will do this for undirected along  with the tests and send a PR by this weekend.

**Comment by rusty1s** [comment]
Any update on this?

**Comment by kolia** [comment]
Hi @pgtgrly,
I'm finding myself needing a `line_graph` transform as well.  I'm happy to help if you've started, or start on it if you haven't.

**Comment by pgtgrly** [comment]
Hey @rusty1s @kolia,
I have implemented this for directed graphs, I need to do it for undirected graphs.
I will be sending a PR for the same by this Thursday/ Early Friday. I hope that is alright?

**Comment by kolia** [comment]
Sound good to me, thanks for putting in the work.  If you want early feedback on the directed version, i'm happy to help.

For now i'm doing `to_networkx` and back as @rusty1s suggested.

**Comment by pgtgrly** [comment]
I have created a PR #165 as implementation of Line Graphs
