### ISSUE TITLE
Efficient way to convert normal minibatch to Batch?

### ISSUE THREAD

**Issue by Wang-Tianyu** [rusty1s/pytorch_geometric#1278]
I am wondering what's the best way to convert a normal minibatch of points with shape (batch_size, num_feature, num_points_pre_batch) to the Batch data structure provided by PyG?
It seems that I need to convert the minibatch manually to multiple Data then call Batch.from_data_list to get a Batch.

Can I directly assign Batch.x, Batch.pos, and Batch.batch ?

**Comment by rusty1s** [comment]
All you need to do is to permute your points to shape (batch_size * num_points_per_batch, num_features).For creating `batch`, you can do the following:
```
batch = torch.arange(batch_size).view(-1, 1).repeat(1, num_nodes).view(-1)
```

**Comment by Wang-Tianyu** [comment]
> All you need to do is to permute your points to shape (batch_size * num_points_per_batch, num_features).For creating `batch`, you can do the following:
> 
> ```
> batch = torch.arange(batch_size).view(-1, 1).repeat(1, num_nodes_per_batch).view(-1)
> ```

Cool.
Thanks for your reply.
Also, thank you for making this really good package.
