### ISSUE TITLE
Error: AssertionError in argva_node_clustering.py 

### ISSUE THREAD

**Issue by iimlearning** [rusty1s/pytorch_geometric#1279]
## 🐛 Bug

When running "!python argva_node_clustering.py" in "colab".

 **This occurs:**
Traceback (most recent call last):
  File "argva_node_clustering.py", line 18, in <module>
    dataset = Planetoid(path, dataset, T.NormalizeFeatures())
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/planetoid.py", line 58, in __init__
    **assert self.split in ['public', 'full', 'random']**

**I look the error codes：**
dataset = Planetoid(path, dataset, T.NormalizeFeatures())
**This lead to the error:** 
"T.NormalizeFeatures()" 
because T.NormalizeFeatures() is not in ['public', 'full', 'random'].

**I change T.NormalizeFeatures() to 'public', the code will run successfully.
I think I should tell you this, maybe you can look and modify the code to make it better.**

**Comment by rusty1s** [comment]
Thank you. It is now fixed :)

**Comment by lvjiujin** [comment]
`
dataset = Planetoid(path, dataset, T.NormalizeFeatures())
torch_geometric\datasets\planetoid.py", line 59, in __init__ assert self.split in ['public', 'full', 'random'] AssertionError`

**Comment by rusty1s** [comment]
You need to replace that with `dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())`.

**Comment by mpanpan** [comment]
> You need to replace that with `dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())`.

很有用，谢谢
