### ISSUE TITLE
GraphSage with edge features

### ISSUE THREAD

**Issue by kkonevets** [rusty1s/pytorch_geometric#1282]
## ❓ Questions & Help

Any ideas of how to use edge features with GraphSage? I don't know how to update edge features in this case because number of edges is different in each aggregation block of GraphSage. I tried to 
```python
row, col = edge_index
new_edge_attr = torch.cat([x[row], edge_attr, x[col]])
x = scatter(new_edge_attr,
            col,
            dim=0,
            dim_size=x_traget.size(0),
            reduce="mean")
```
where `edge_attr` are static edge features which are not updated between aggregations in GraphSage while going down to target nodes. But it works worse than when I use only node features. Is it because features are static?

Please, give advice.

**Comment by rusty1s** [comment]
Your code looks correct to me. Instead of concatenation, you can also use summation, which might perform better in some cases:
```
new_edge_attr = F.relu(x[row] + edge_attr @ self.weight)
```

**Comment by kkonevets** [comment]
Could not increase my score, guess my edge features are bad. But the machinary of constant edge features and GraphSage is clear anyway.
Thanks for feedback.
