### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by 964918993** [rusty1s/pytorch_geometric#1284]
## ❓ Questions & Help

When I run the code "sgas/gcn_point", I have the error:
RuntimeError: No such operator torch_cluster::random_walk

Can you help me? Thanks!

**Comment by rusty1s** [comment]
What‘s sgas/gcn_point? I believe it requires an older version of `torch-cluster`, so please downgrade it to the required version.

**Comment by 964918993** [comment]
> What‘s sgas/gcn_point? Do you have `torch-cluster` installed?

Thanks for your reply.
'SGAS' is a project that need the pytorch_geometric(https://github.com/lightaime/sgas).
And I have installed 'torch-cluster==1.4.5'.

**Comment by amiltonwong** [comment]
@964918993 ,
How do you solve the error `RuntimeError: No such operator torch_cluster::random_walk`? I came across the same error as yours.

**Comment by rusty1s** [comment]
Looks like an installation issue to me, where the corresponding kernels, *e.g.*, `random_walk.so` are not compiled, and therefore cannot be found. How did you install `torch-cluster`?
