### ISSUE TITLE
examples proteins_topk_pool.py and enzymes_topk_pool.py are identical

### ISSUE THREAD

**Issue by vraimonds** [rusty1s/pytorch_geometric#1285]
## 🐛 Bug

Example files **proteins_topk_pool.py** and **enzymes_topk_pool.py** are identical

## To Reproduce

I double checked with diffchecker: https://www.diffchecker.com/p068fpev

## Expected behavior

Either delete the redundant file or replace with the expected changes.

**Comment by rusty1s** [comment]
Thanks. I removed the `ENZYMES` example.
