### ISSUE TITLE
Can pytorch_geometric handle node classification for multiple graphs?

### ISSUE THREAD

**Issue by Leungfranklin** [rusty1s/pytorch_geometric#1286]
## ❓ Questions & Help

In the examples, I can only find either (a) node classification for one big graph just like CORA and the data is stored in dataset[0] or (b) graph classification for many graphs like PROTEINS, Yet can I do node classification for many graphs with multiple nodes, e.g. dataset[0], dataset[1] ... with each containing a graph with multiple nodes and I want to classify those nodes?

**Comment by rusty1s** [comment]
Sure, examples/ppi.py contains such an example.

**Comment by Leungfranklin** [comment]
Thanks, it works perfectly for my scenario
