### ISSUE TITLE
about the norm in GCN

### ISSUE THREAD

**Issue by chengsen** [rusty1s/pytorch_geometric#129]
## ❓ Questions & Help

The norm function in GCN GCNConv doesn't check if there are self-loops in the edge_index.  Should it add this check?

**Comment by rusty1s** [comment]
You mean in case there are already self-loops in the graph?

**Comment by chengsen** [comment]
> You mean in case there are already self-loops in the graph?

yes, maybe you should do a description or check.

**Comment by rusty1s** [comment]
Fixed in current master. Thanks!
