### ISSUE TITLE
Data Load Speed Huge Drop from InMemoryDataset to Dataset

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#1294]
## ❓ Questions & Help

Hi, I have a task that needs to do graph classification on many small graphs. I used to put them in a InMemoryDataset. I change it to normal Dataset recently and the training speed drops hugely. Batchsize is 128. The last line is for InMemoryDataset and others for Dataset.
![image](https://user-images.githubusercontent.com/17882988/83735457-c55f9380-a693-11ea-8b1a-30b9c489ca7e.png)

May I ask about the reason or any suggestion?

**Comment by tchaton** [comment]
Dear @RuihongQiu,

As explained in the name of the dataset, InMemoryDataset means all the graphs are loaded in memory, so access is much faster.

On the contrary, Dataset is re-loading graphs for your storage everytime it is forming a batchSize.
If your dataset was small enough to fit within a InMemoryDataset, you should stick with it.

**Comment by RuihongQiu** [comment]
Thanks for your reply. I know the difference between the memory and the hard disk. But the speed gap is like 1k times. It's a little bit weird to me.

**Comment by rusty1s** [comment]
You can increase speed by making use of the `num_workers` argument in the `DataLoader`.

**Comment by RuihongQiu** [comment]
Still far too slow😂 I will just stick with the InMemory one. Almost taking up all my memory

**Comment by rusty1s** [comment]
Another approach to circumvent this is to load big mini-batches from disk, and generating smaller mini-batches in the `DataLoader`. This way, you get the best of both worlds: Reduced RAM memory and fast mini-batch generation. This is something which is not supported though.

**Comment by RuihongQiu** [comment]
I will have a try. Many thanks!

**Comment by srikanthmalla** [comment]
Hi @rusty1s and @RuihongQiu ,
Did you implement the below idea you mentioned. If you please do share here as an example as it will be helpful.
> Another approach to circumvent this is to load big mini-batches from disk, and generating smaller mini-batches in the `DataLoader`. This way, you get the best of both worlds: Reduced RAM memory and fast mini-batch generation. This is something which is not supported though.

Best,
Srikanth
