### ISSUE TITLE
Autoencoder - Decoder Matrix Size 

### ISSUE THREAD

**Issue by shehan-perera** [rusty1s/pytorch_geometric#1296]
## ❓ Questions & Help

**To anyone who understands the autoencoders, your help is appreciated:**
Question: The encoder of a graph autoencoders take the feature matrix X and the Adjacency matrix A as input. Here the Adjacency Matrix is of size [2 rows, m columns]. I am wondering why the decoder given by equation [ZZ^T] only produces a [1 row, m columns] output. How can I relate that to the original Adjacency Matrix? 

Thank you so much in advance

**Comment by rusty1s** [comment]
The Decoder generates a *dense* adjacency matrix of shape [num_nodes, num_nodes]. To relate it to its sparse version encoded in `edge_index`, you need to convert it to a dense one too:
```python
dense_adj = torch.zeros((N, N))
dense_adj[edge_index[0], edge_index[1]] = 1
```

**Comment by shehan-perera** [comment]
Thank you so much :)
