### ISSUE TITLE
Getting node wise embeddings from a specific layer of SageConv

### ISSUE THREAD

**Issue by 1byxero** [rusty1s/pytorch_geometric#1297]
## ❓ Questions & Help

For visualization purposes I would like to obtain embedding of each node of the graph from a specific layer. 
I am using neighbor sampler for mini batching.
Can you help me with this?
P.S. I am using version 1.4.3 if thats important to know

**Comment by rusty1s** [comment]
This is a bit tricky when using `NeighborSampler`. The most elegant way I am aware of is to compute embeddings layer-wise for the whole graph, using a 1-hop sampler which takes in the complete neighborhood of nodes. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py#L47-L71), but may need to modify it for PyG 1.4.3.

**Comment by 1byxero** [comment]
Tried to port the code to latest version of PyG.
Following code snippet resulted in an `AttributeError`
```
loader = NeighborSampler(
    data.edge_index, node_idx=data.train_mask, sizes=[25, 25, 15], 
    batch_size=1024, shuffle=True, num_workers=12, add_self_loops=True
)
```

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

```
<ipython-input-7-b1d1949a18b6> in <module>()
      7 loader = NeighborSampler(
      8     data.edge_index, node_idx=data.train_mask, sizes=[25, 25, 15],
----> 9     batch_size=1024, shuffle=True, num_workers=12, add_self_loops=True
     10 )
     11 

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/sampler.py in __init__(self, edge_index, sizes, node_idx, num_nodes, flow, **kwargs)
     79         N = int(edge_index.max() + 1) if num_nodes is None else num_nodes
     80         edge_attr = torch.arange(edge_index.size(1))
---> 81         adj = SparseTensor.from_edge_index(edge_index, edge_attr, (N, N),
     82                                            is_sorted=False)
     83         adj = adj.t() if flow == 'source_to_target' else adj

AttributeError: type object 'SparseTensor' has no attribute 'from_edge_index'


```

Can you please help with this?

**Comment by jchaykow** [comment]
@1byxero `from_edge_index` is a method on `SparseTensor` using PyTorch 1.5 and corresponding torch-sparse. `NeighborSampler` uses this method. Essentially, just update `torch-sparse` and `scatter`:

```
pip install torch-scatter==latest+cu102 torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
```

**Comment by rusty1s** [comment]
Yeah, this one is on me. It's already fixed in PyG master. Sorry!

You can replace the `SparseTensor.from_edge_index` call with
```python
        adj = SparseTensor(row=edge_index[0], col=edge_index[1],
                           value=edge_attr, sparse_sizes=(N, N),
                           is_sorted=False)
```
which should be an easy fix for PyTorch 1.4.0 without re-installing anything.

**Comment by 1byxero** [comment]
@rusty1s Does the implementation of SageConv in PyG 1.5 Inherently concats the feature of previous layer representation?

**Comment by rusty1s** [comment]
Yes. If you do not want this behaviour, you can use the more general GraphConv with root_weight=False.

**Comment by 1byxero** [comment]
@rusty1s Thanks!
I will close this issue

**Comment by khaled-rahman** [comment]
Thanks! Good discussion. I found it helpful.
