### ISSUE TITLE
error in using k_hop_subgraph

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1298]
## 🐛 Bug

Hello,
Sometimes (not always) when I run k_hop_subgraph I get the following error:

> *** Error in `python': double free or corruption (!prev): 0x00000000012da980 ***

## Environment

* OS: Debian GNU/Linux 8.10 (jessie)
* Python version: Python 3.6.5
* PyTorch version: 1.4
* CUDA/cuDNN version: V10.0.130 (NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0)
* GCC version: gcc (GCC) 9.1.0
* Any other relevant information: I am running on a cluster

**Comment by navid-mahmoudian** [comment]
Hello,
I solved the issue. In case anyone else has the same problem.  The workaround is to do

`pip install --no-binary=:all: numpy`

I found the solution in this [link](https://github.com/tensorflow/tensorflow/issues/6968). Even though this post is related to TensorFlow, the solution worked for me. It seems that there is a problem with OpenBLAS and the older version of Debian. So either you have to upgrade your Debian (which I was not able because I am running on a cluster),  or you have to install numpy as follows:

`pip install --no-binary=:all: numpy`

or

`pip install --no-binary=:all: --force-reinstall numpy,`

**Comment by rusty1s** [comment]
Awesome :) Thanks for letting me know.
