### ISSUE TITLE
Any plan to support PyTorch 0.5? 

### ISSUE THREAD

**Issue by ducha-aiki** [rusty1s/pytorch_geometric#13]
So far compilation of torch_scatter gives an error:

> torch_scatter/src/generic/cpu.c: In function ‘scatter_mul_Float’:
/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH/THTensorDimApply.h:46:47: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
   if( (DIMENSION < 0) || (DIMENSION >= TENSOR1->_dim()) ) \

**Comment by rusty1s** [comment]
Hey,

Actually, there is no version 0.5 for PyTorch, so I do not know what you mean there.
For your installation problems, please refer to the [installation guide](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html) and report back.

**Comment by ducha-aiki** [comment]
Sorry. I meant actually current master, which I thought already was released :(
Regarding installation problem - just latest ATen signatures are different
