### ISSUE TITLE
Error in Installation: Could not find correct version for torch-scatter

### ISSUE THREAD

**Issue by SubhajitDuttaChowdhury** [rusty1s/pytorch_geometric#1301]
## 📚 Installation
Hello,

I am trying to install pytorch_geometric. When I try to run **pip install torch-scatter==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.5.0.html** I get the following error:
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+ (from versions: latest+cpu, latest+cu92, latest+cu101, latest+cu102, 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.4, 2.0.4+cpu, 2.0.4+cu101, 2.0.4+cu102, 2.0.4+cu92)
ERROR: No matching distribution found for torch-scatter==latest+

## Environment

* OS:Ubuntu 18.04
* Python version:Python 3.7.4
* PyTorch version:1.5.0
* CUDA/cuDNN version:10.2
* GCC version:gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):pip
* Any other relevant information:

## Checklist

- [ Yes ] I followed the installation guide.
- [ Yes ] I cannot find my error message in the FAQ.
- [ Yes ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ No ] I have cloned the repository and tried a manual installation from source.
- [ No ] I do have multiple CUDA versions on my machine.
- [ No ] I checked if the official extension example runs on my machine.
- [ No ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
You need to replace {CUDA} with either cpu, cu92, cu101 or cu102, depending on which CUDA version you have installed.

**Comment by SubhajitDuttaChowdhury** [comment]
Thank you for the reply.
