### ISSUE TITLE
GEDDataset ALKANE has no train/test GED values

### ISSUE THREAD

**Issue by Skarfrael** [rusty1s/pytorch_geometric#1303]
Hello!

When loading the dataset I noticed that while for (AIDS, LINUX, IMDB) `ged` provide GED values for train/train and train/test pairs, for ALKANE only train/train values are provided. Train/test values are `inf`.

This can be seen in the below screenshot. My code works fine for the other sets.

Is this expected or known behavior? If yes, it could be mentioned in the documentation?

Thanks

![image](https://user-images.githubusercontent.com/40795688/83966855-6aad7e00-a8c5-11ea-998b-2583aa23de69.png)

**Comment by rusty1s** [comment]
Mh, you are right. We are using datasets and ground-truth values from [here](https://github.com/yunshengb/SimGNN), and ALKANE is missing train/test GED pairs. Not much I can do about it :(

**Comment by Skarfrael** [comment]
Yeah, I expected that. Obviously, don't worry about it :P I guess the only solutions on your side is maybe referring to this in the documentation. Other than that maybe sometime in the future, these ged values could be added on top of the info downloaded from original repo's cloud files, extending it.

**Comment by rusty1s** [comment]
I added a note to the documentation. Thank you!
