### ISSUE TITLE
To include more attribute type?

### ISSUE THREAD

**Issue by jzhou316** [rusty1s/pytorch_geometric#1307]
Hi this may be a small corner case, but I ran into the following error with some particular dataset of my own

https://github.com/rusty1s/pytorch_geometric/blob/58ff9037e4c3dd4653aa37a387c03a37a8f0d546/torch_geometric/data/batch.py#L76

The reason was that I fed some attributes in the Data object that are of type `numpy.int64`, which were read from some large database storing the graph information. I ignored this error by manually commenting it out since whether it is `int` or `numpy.int64`, after being passed to `torch.tensor()` in 

https://github.com/rusty1s/pytorch_geometric/blob/58ff9037e4c3dd4653aa37a387c03a37a8f0d546/torch_geometric/data/batch.py#L74

the tensor will be of the same type. I also tried to manually check the data types and make them compatible with the types here whenever they are just scalars

https://github.com/rusty1s/pytorch_geometric/blob/58ff9037e4c3dd4653aa37a387c03a37a8f0d546/torch_geometric/data/batch.py#L73

However, I found it not being a very structured way of handling these small details. Could you also give it a bit thinking and maybe include more scalar types, such as those from numpy scalar types? Or maybe converting them to `int` or `float` somewhere under the hood if that's better?

**Comment by rusty1s** [comment]
Are you using an older PyG version? This one is already fixed, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py#L69-L75).

**Comment by jzhou316** [comment]
Oh I see. Yeah my version is older. Sorry. Thanks for pointing out!
