### ISSUE TITLE
fp16 Support?

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_geometric#1308]
## 🚀 Feature

Do we have fp16 support in `pytorch-geometric`?

## Additional context

/cc @rusty1s

**Comment by rusty1s** [comment]
Custom kernels currently do not support fp16 since their implementation is more complex. I have plans to support it, but it's not really top-prio. We have an open PR for `torch-scatter` though, see [here](https://github.com/rusty1s/pytorch_scatter/pull/137).

**Comment by mingloo** [comment]
Thanks for your quick reply. 

Closed.
