### ISSUE TITLE
RuntimeError: Not compiled with METIS support

### ISSUE THREAD

**Issue by prashantpandey** [rusty1s/pytorch_geometric#1313]
## ❓ Questions & Help

I am trying to use ClusterData and ClusterLoader. However, it results in a runtime error that I can't seem to find anything online.

What might be causing this problem?

```
Compute METIS partitioning...
Traceback (most recent call last):
  File "/global/homes/p/prashant/metagnn/src/meta_gnn.py", line 397, in <module>
    save_dir=dataset.processed_dir)
  File "/global/homes/p/prashant/.local/cori/pytorchv1.5.0-gpu/lib/python3.7/site-packages/torch_geometric/data/cluster.py", line 45, in __init__
    adj, partptr, perm = adj.partition(num_parts, recursive)
  File "/usr/common/software/pytorch/v1.5.0-gpu/lib/python3.7/site-packages/torch_sparse/metis.py", line 37, in partition
    recursive)
RuntimeError: Not compiled with METIS support
```

**Comment by rusty1s** [comment]
METIS is not correctly installed. I suggest to install the wheels or to follow the installation instructions [here](https://github.com/rusty1s/pytorch_sparse#from-source).

**Comment by psh9002** [comment]
I installed METIS by your recommendation [link](http://glaros.dtc.umn.edu/gkhome/metis/metis/download), but I got the same RuntimeError.
I tried to install the METIS through the official link, anaconda, and pip.

Is there another solution?

**Comment by rusty1s** [comment]
METIS comes pre-built when using our wheels. If you want to manually install, you need to install METIS (as you did) and run the setup with
```
WITH_METIS=1
```

Your example looks correct to me though. `rowptr.size(0)` denotes the number of nodes + 1, and `rowptr[-1]` denotes the number of edges in your graph.

**Comment by LuisaWerner** [comment]
Hi @rusty1s , I have the same Error with METIS (not compiled with METIS support). I tried to install it manually given the instructions in install.txt file. Even though I've installed GNU make and CMAKE, I don't manage to corrently install METIS by executing "make" according to the instructions in the install.txt file. 

Is there an alternative way to make use of METIS ? If it comes pre-build with your wheels, how can I make use of it? 

I am on MAC OS. 

Thanks in advance.

**Comment by rusty1s** [comment]
It comes indeed pre-built with our wheels but we do not provide them yet for mac M1. As such, you will need to install it manually in this case, sorry :(

**Comment by LuisaWerner** [comment]
Hi @rusty1s , unfortunately I still have problems with the installation of METIS. I followed the instructions to install the package manually and built the package with 'make'. 

(The only point where I derivated from the instructions is for the installation of ```cmake```: the recommended ```cmake```version in the ```install.txt``` wasn't available for MAC OS, so I took ```3.19.3``` which is the closest one to the recommended version ```2.8```). Don't know if this matters. )

When I tried to install torch-sparse with ```WITH_METIS = 1```, I got the following error: 

```
(virtual_env) (base) luisas-mbp:ogb werner$ export WITH_METIS=1
(virtual_env) (base) luisas-mbp:ogb werner$ echo $WITH_METIS
1
(virtual_env) (base) luisas-mbp:ogb werner$ pip install torch-sparse torch-scatter ```

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (g++) is not compatible with the compiler Pytorch was
    built with for this platform, which is clang++ on darwin. Please
    use clang++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using g++, and then you can also use
    g++ to compile your extension.
    
    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

In order to tackle this issue, I used clang as an compiler for METIS with the commands
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
make config cc=clang
```

After that, the installation of torch-sparse passed without problems, but I got the issue described [here]
(https://github.com/pyg-team/pytorch_geometric/issues/4044)
After reinstalling as indicated in the link above, I got a MAC OS specific error 
```Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)``` 
that is supposed to indicate a bug in the interpreter or in an extension module. 

Do you have any ideas how I could make torch-sparse work with the METIS extension and solve my issues?  Did I maybe oversee something evident or miss an important step in the installation? 

Thanks a lot in advance

**Comment by rusty1s** [comment]
If the installation succeeds, but you see an error similar to #4044, this might indicate that you may have an old version of `torch-sparse` installed. You could try to repeatedly uninstall `torch-sparse` and install again.

**Comment by rusty1s** [comment]
I can also confirm that you will need `clang` to install the package.

**Comment by LuisaWerner** [comment]
Thanks for the help. In the end, I installed torch-sparse with the instructions given for installing the binaries and made sure that I have the right versions.

```pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+${CUDA}.html```

Python ```3.9```
torch ```1.12.0```
torch geometric ```2.0.4```
torch-scatter ```2.0.9```
torch-sparse  ```0.6.14```

METIS-support works now for me but I haven't tested it on M1 chip yet.

**Comment by FantasyJXF** [comment]
> https://data.pyg.org/whl

Do not work for me.

pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu101.html

Python 3.6
torch 1.8.0
torch geometric 2.3.0
torch-scatter 2.0.9
torch-sparse 0.6.12

anyone can help?

**Comment by rusty1s** [comment]
What's the log when running 
```
pip install --verbose torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu101.html

**Comment by FantasyJXF** [comment]
> 
I reinstalled torch 1.8.1+cuda10.1  and still can not use METIS.

```
 pip install --verbose torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.8.1+cu101.html

Using pip 20.2.2 from /home/web_server/anaconda3/envs/pyg/lib/python3.6/site-packages/pip (python 3.6)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-jvk_31x3
Created temporary directory: /tmp/pip-req-tracker-a1jg526v
Initialized build tracking at /tmp/pip-req-tracker-a1jg526v
Created build tracker: /tmp/pip-req-tracker-a1jg526v
Entered build tracker: /tmp/pip-req-tracker-a1jg526v
Created temporary directory: /tmp/pip-install-pb_x3i7f
Looking in indexes: https://pypi.corp.kuaishou.com/kuaishou/prod/+simple/
Looking in links: https://data.pyg.org/whl/torch-1.8.1+cu101.html
Requirement already satisfied: torch-scatter in /home/web_server/anaconda3/envs/pyg/lib/python3.6/site-packages (2.0.9)
Requirement already satisfied: torch-sparse in /home/web_server/anaconda3/envs/pyg/lib/python3.6/site-packages (0.6.12)
Requirement already satisfied: scipy in /home/web_server/anaconda3/envs/pyg/lib/python3.6/site-packages (from torch-sparse) (1.5.4)
Requirement already satisfied: numpy>=1.14.5 in /home/web_server/anaconda3/envs/pyg/lib/python3.6/site-packages (from scipy->torch-sparse) (1.19.5)
Removed build tracker: '/tmp/pip-req-tracker-a1jg526v'
```

**Comment by rusty1s** [comment]
Looks like the wheels are not picked up due to the outdated PyTorch version. Try
```
 pip install --verbose --no-index torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.8.1+cu101.html
```

**Comment by marcosbodio** [comment]
If someone comes here because of issue related to PyG + METIS running on Apple chips, I recommend reading https://medium.com/@beppe2hd/a-simple-guide-to-set-up-pyg-with-metis-support-on-mac-and-linux-378e833d4de3 ... I wish that was part of the documentation!

In addition to what is describe in that guide, I had to do the following:
```
cd /path/to/where/you/compiled/METIS
cp build/Darwin-arm64/libmetis/libmetis.dylib /root/path/of/your/python/project
```
