### ISSUE TITLE
Link prediction with different feature sizes

### ISSUE THREAD

**Issue by snisher** [rusty1s/pytorch_geometric#1314]
## ❓ Questions & Help

Hi, I'm working on link prediction on a network that has two kinds of nodes (genes and diseases) and I'm trying to predict links between the two. The two kinds of nodes have different numbers of features. I have a kind of hacky model based on the link_pred example that has 2 separate GCNConvs at the start, and the two outputs are concatenated and put through two more GCNConvs. 

It trains and gets decent results, but I'm wondering if anyone has any tips for a model like this that has inputs of different sizes? It seems like most standard examples only use 2 graph conv layers, is it a mistake to use 3? Model definition:

```python
num_disease_features = disease_data.num_features # 1124
num_gene_features = gene_data.num_features # 8769

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.disease_conv = GCNConv(num_disease_features, 256)
        
        self.gene_conv = GCNConv(num_gene_features, 256)
        
        self.conv2 = GCNConv(256, 128)
        self.conv3 = GCNConv(128, 64)

    def forward(self, pos_edge_index, neg_edge_index):
        
        x_disease = F.relu(self.disease_conv(disease_data.x, disease_data.edge_index))
        
        x_gene = F.relu(self.gene_conv(gene_data.x, disease_data.edge_index))

        x = torch.cat((x_disease, x_gene), dim=0) # stack the two latent feature matrices
        
        x = F.relu(self.conv2(x, disease_gene_data.train_pos_edge_index))
        x = self.conv3(x, disease_gene_data.train_pos_edge_index)

        # concatenates positive and negative edge indices
        total_edge_index = torch.cat([pos_edge_index, neg_edge_index], dim=-1)
        x_j = torch.index_select(x, 0, total_edge_index[0]) # set of node encodings at start of edges
        x_i = torch.index_select(x, 0, total_edge_index[1]) # set of node encodings at end of edges
        return torch.einsum("ef,ef->e", x_i, x_j) # row wise dot product
```

Thanks!

**Comment by rusty1s** [comment]
This seems like a perfect valid way to tackle this problem :) Other approaches involve operating on heterogeneous graphs, with separate transformations for different edge types. I'm working on a better support for this :)

**Comment by snisher** [comment]
Good to hear, I just needed some validation :smile:

Looking forward to more heterogenous graph support! Cheers
