### ISSUE TITLE
Suggestion for adding links to method examples

### ISSUE THREAD

**Issue by dtchang** [rusty1s/pytorch_geometric#1317]
Currently each item on the list of implemented methods provides links to both the method class and the published paper:
    GraphConv from, e.g., Morris et al.: Weisfeiler and Leman Go Neural: Higher-order Graph 
    Neural Networks (AAAI 2019)
which is very nice.

On the method class API:
    class GraphConv(in_channels, out_channels, aggr='add', bias=True, **kwargs)[source]
currently there is a link to its source, which again is very nice.

Please additionally provides a link to its example, e.g., [example].

**Comment by rusty1s** [comment]
That‘s a good idea. I will work on it.

**Comment by dtchang** [comment]
Thanks much.

Dan

Sent from Mail for Windows 10

**Comment by rusty1s** [comment]
Done :)
