### ISSUE TITLE
A failure in running `python setup.py test` for pytorch-scatter

### ISSUE THREAD

**Issue by wanpifeng4ever** [rusty1s/pytorch_geometric#132]
## ❓ Questions & Help

When I check the error message by installing torch-scatter from source and run 'python setup.py install', the following error occurs.
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
build/temp.linux-x86_64-3.7/cpu/scatter.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

Thanks for any help!

**Comment by rusty1s** [comment]
That is a link error. Can you post your [system configurations](https://github.com/rusty1s/pytorch_geometric/blob/master/.github/ISSUE_TEMPLATE/installation.md)?

**Comment by wanpifeng4ever** [comment]
Thank you so much for your prompt reply! Below is the information.
## Environment

* OS: CentOS
* Python version: 3.7
* PyTorch version: 1.0.1.post2
* CUDA/cuDNN version: 8.0, V8.0.44/ 5.0
* GCC version: 5.5.0
* How you tried to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:
I success with the code on gcn but fail on gat, which reports segmentation fault. So I tested the pytorch-scatter as suggested, and got the error which said a higher version of gcc is needed. So I upgraded gcc from 4.85 to 5.50. Then I got a new error mentioned above.

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I have cloned the repository and tried a manual installation from source.
- [x] I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

**Comment by rusty1s** [comment]
Thanks for the detailed information. This helps a lot. As far as I know, you also need to reinstall PyTorch when changing gcc versions (gcc version must be consistent for all PyTorch packages). I will add this information to the doc.

**Comment by wanpifeng4ever** [comment]
Hi~ After reinstalling pytorch, I still got the same problem. Below is the complete error when running python setup.py install (or test).
PS: I created a new conda environment with python 3.6 so the error message is slightly different from the previous.
Also thanks again for your patience.
```
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/my_name/anaconda3/envs/pytorch/compiler_compat -L/home/my_name/anaconda3/envs/pytorch/lib -Wl,-rpath=/home/my_name/anaconda3/envs/pytorch/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/scatter.o -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
/home/my_name/anaconda3/envs/pytorch/compiler_compat/ld: build/temp.linux-x86_64-3.6/cpu/scatter.o: unable to initialize decompress status for section .debug_info
/home/my_name/anaconda3/envs/pytorch/compiler_compat/ld: build/temp.linux-x86_64-3.6/cpu/scatter.o: unable to initialize decompress status for section .debug_info
/home/my_name/anaconda3/envs/pytorch/compiler_compat/ld: build/temp.linux-x86_64-3.6/cpu/scatter.o: unable to initialize decompress status for section .debug_info
/home/my_name/anaconda3/envs/pytorch/compiler_compat/ld: build/temp.linux-x86_64-3.6/cpu/scatter.o: unable to initialize decompress status for section .debug_info
build/temp.linux-x86_64-3.6/cpu/scatter.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

**Comment by rusty1s** [comment]
Maybe related? https://github.com/pytorch/pytorch/issues/16683

**Comment by wanpifeng4ever** [comment]
Yes! Finally, I made it work. Thank you so much for all your help!
