### ISSUE TITLE
The question of func to_dense_batch

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1328]
## ❓ Questions & Help

I use a dataset that every batch has N graphs and every graph with n_i nodes has a feature matrix(dimension is n_i*d).

Fisrst, When I use the func pytorch_geometric.utils.to_dense_batch,I hope I give a batch matrix A[dimension is (N*n_i)*d] then the func return a matrix B[dimension is N*(n_i*d)]

I use the code as fellow:
```python
dataset = TUDataset(root='./data/DD', name='DD')
num_training = int(len(dataset)*0.8)
num_val = int(len(dataset)*0.1)
num_test = len(dataset) - (num_training+num_val)
training_set,validation_set,test_set = random_split(dataset,[num_training,num_val,num_test])

train_loader = DataLoader(training_set, batch_size=50, shuffle=True)

@torchsnooper.snoop()
def test():
        for i, data in enumerate(train_loader):
                a, b = to_dense_batch(data.x)

test()
```

but I got two matrix like this:
```python
00:15:47.791810 call       189 def test():
00:15:47.792774 line       190         for data in train_loader:
New var:....... data = Batch(batch=[13186], edge_index=[2, 65626], x=[13186, 89], y=[50])
00:15:47.809728 line       191                 a, b = to_dense_batch(data.x)
New var:....... a = tensor<(1, 13186, 89), float32, cpu>        
New var:....... b = tensor<(1, 13186), bool, cpu>
00:15:47.809728 line       190         for data in train_loader:
Modified var:.. data = Batch(batch=[14140], edge_index=[2, 70690], x=[14140, 89], y=[50])
00:15:47.830673 line       191                 a, b = to_dense_batch(data.x)
Modified var:.. a = tensor<(1, 14140, 89), float32, cpu>
Modified var:.. b = tensor<(1, 14140), bool, cpu>
```
If I set the batch_size is 50,I think I should get matrix that dimension is (50,(MAX(n_i)*89)),did I misunderstand?
Looking forward to your reply. Thank you very much!

**Comment by rusty1s** [comment]
You need to also pass data.batch to to_dense_batch.

**Comment by jiaruHithub** [comment]
> You need to also pass data.batch to to_dense_batch.

It's work.Your reply is so useful.Thank you!

I have another question:If in one batch, MAX(n_i) = 500, some graphs's n_i<500 so that vector's size(0) of these graphs may less then 500.
Is the func to_dense_batch use '0' fill the vector make it's size(1) become 500?

**Comment by rusty1s** [comment]
Yes, and the second tensor holds information about valid nodes too.

**Comment by jiaruHithub** [comment]
> Yes, and the second tensor holds information about valid nodes too.

Ok,I try to think a question:If we make MAX(n_i) in every batch be equality,is there any methods can realize it?

**Comment by rusty1s** [comment]
In that case, you can simply reshape your tensor to `[batch_size, num_nodes, num_features]`.

**Comment by jiaruHithub** [comment]
> In that case, you can simply reshape your tensor to `[batch_size, num_nodes, num_features]`.

But in this case,every graph has different number of nodes that means ```python [batch_size, num_nodes, num_features]``` of every batch is different,isn't it?

**Comment by rusty1s** [comment]
If you do not now the number of nodes for a batch in advance, you can do:
```
x = x.view(data.num_graphs(), -1, out_channels)
```
where `-1` indicates that `num_nodes` should be automatically inferred.

**Comment by jiaruHithub** [comment]
> .num_graphs(), -1, out_c

Is there ```x``` means the first tensor returned of to _dense_batch?
If ```x``` is the first tensor returned of to _dense_batch, the ```out_channels``` should be pre-computed in every batch.Is this feasible?

**Comment by rusty1s** [comment]
Out_channels corresponds to the size of the last dimension

**Comment by jiaruHithub** [comment]
> Out_channels corresponds to the size of the last dimension

em......I'm sorry.
the size of last dimension is feature_num?

**Comment by rusty1s** [comment]
Yes

**Comment by jiaruHithub** [comment]
> Yes
Thank you for taking the time to reply,I try it success!
