### ISSUE TITLE
Adding faces and edges to 3D Mesh graph doesn't work

### ISSUE THREAD

**Issue by amir-abdi** [rusty1s/pytorch_geometric#133]
## 🐛 Bug

I am trying to create a new Dataset class, which inherits from `InMemoryDataset`.
It is for 3D mesh files and I want to introduce the `faces` attribute. However, when the `faces` and `edges` attributes are both addded, the `self.collate` method crashes with the following error:

    RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 100592 and 263568 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307

## Environment

* OS: Ubuntu 16.04
* Python version: 3.5.2
* PyTorch version: 1.0
* CUDA/cuDNN version: 10.0

**Comment by rusty1s** [comment]
I see, will fix ASAP.

**Comment by rusty1s** [comment]
I was in a bit of a rush, actually, I can't reproduce your error (see [this testcase](https://github.com/rusty1s/pytorch_geometric/blob/master/test/data/test_dataset.py). Are you sure you use the right shapes for `edge_index` (`[2, num_edges]`) and `face` (`[3, `num_faces]`)?

**Comment by amir-abdi** [comment]
Yes, here are some sample sizes:

    edges.shape torch.Size([2, 301776])
    vertices.shape torch.Size([50368, 3])
    data.faces.shape torch.Size([3, 100592])

    vertices.shape torch.Size([131710, 3])
    data.faces.shape torch.Size([3, 263568])
    edges.shape torch.Size([2, 901260])

The test case you provided replicates the same Data as the two samples; therefore, the number of edges/faces in both are the same. Could this be the reason why your test passes?

**Comment by rusty1s** [comment]
Use 'data.edge_index' for egdes and `data.face` for faces.

**Comment by amir-abdi** [comment]
I replaced `faces` with `face` and the problem is now solved. 
My bad.
Thanks

**Comment by rusty1s** [comment]
Cool! If you have a better way to encode this, please let me know.
