### ISSUE TITLE
cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by shangguan91** [rusty1s/pytorch_geometric#1348]
## ❓ Questions & Help

Hey, after i run `!python benchmark/points/mpnn.py` for testing the benchmark experienment.
This error occurs. any other .py file has this problem, what can i do

**Comment by rusty1s** [comment]
Which Python version are you using? I pushed a fix into master. Can you please re-try with the updated version?

**Comment by a060146251** [comment]
https://docs.python.org/3/library/typing.html

```
class typing.OrderedDict(collections.OrderedDict, MutableMapping[KT, VT])
A generic version of collections.OrderedDict.

New in version 3.7.2
```

**Comment by shangguan91** [comment]
i am using google colab which has version of 3.6.9, could you give me some recommendation for better platform?  i am new to this.
