### ISSUE TITLE
unable to execute u':/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc'

### ISSUE THREAD

**Issue by JialeTao** [rusty1s/pytorch_geometric#135]
## Environment

* OS: Ubuntu
* Python version:  2.7
* PyTorch version: 1.0
* CUDA/cuDNN version:  9.0.176/7.2.1
* GCC version:  5.4.0
* How you tried to install PyTorch Geometric and its extensions (pip, source):  pip
* Any other relevant information:

## Checklist

- [ yes ] I followed the installation guide.
- [ yes ] I cannot find my error message in the FAQ.
- [ unknown ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ no ] I have cloned the repository and tried a manual installation from source.
- [ no ] I do have multiple CUDA versions on my machine.
- [ no ] I checked if the official extension example runs on my machine.
- [ no ] The offical extension example runs on my machine.

## Additional context
I follow the installation guide and the series PATH variable is as follow

$PATH
/usr/local/cuda/bin:/data3/home/taojiale/anaconda3/envs/py27/bin:/data3/home/taojiale/anaconda3/bin:/usr/local/cuda-9.0/bin:/usr/local/matlab/R2015b/bin:/usr/lib/jvm/jdk1.7.0_80/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-9.0/bin:/snap/bin

$CPATH
/usr/local/cuda/include:/usr/local/cuda-9.0/include:

$LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda-9.0/lib64::/usr/local/cuda-9.0/lib64:/usr/local/cuda/extras/CUPTI/lib64

When I run “pip install --upgrade torch-scatter”
The final error is as follow

unable to execute u':/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command u':/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

Do you have any idea?

**Comment by rusty1s** [comment]
Hi, it seems that it can not find your nvcc binaries. Does `nvcc —version` work?

**Comment by JialeTao** [comment]
Yeah, it works as follow, and the version is the same with cuda


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by rusty1s** [comment]
Du you use system Python with `sudo`? [This](https://github.com/cudamat/cudamat/issues/98) might be related.

**Comment by JialeTao** [comment]
Yeah, I use anaconda and I don't have a sudo permission

**Comment by rusty1s** [comment]
The easiest way to identify the error is to check if you can compile the CUDA samples (see [here](https://docs.nvidia.com/cuda/index.html) for the tutorial).
