### ISSUE TITLE
IndexError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1363]
## 🐛 Bug

I use SAGPool to creat a modle, but it has report a error
```Traceback (most recent call last):
  File "main.py", line 107, in <module>
    test_acc,test_loss = test(model,test_loader)
  File "main.py", line 73, in test
    out = model(data)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/DYTPool1/networks.py", line 51, in forward
    x, edge_index, _, batch, _ = self.pool3(x, edge_index, None, batch)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/DYTPool1/layers.py", line 34, in forward
    perm = topk(score, self.ratio, batch)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch_geometric/nn/pool/topk_pool.py", line 18, in topk
    num_nodes = scatter_add(batch.new_ones(x.size(0)), batch, dim=0)
IndexError: dimension specified as 0 but tensor has no dimensions
```
x is the data.x,I don't know why.
In the same training, sometimes it get an error, sometimes it don't
## To Reproduce

1.
1.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
What's the output of `x.size(0)`?

**Comment by jiaruHithub** [comment]
> What's the output of `x.size(0)`?

Is the output of ```x.size(0)``` the number of rows?

**Comment by jiaruHithub** [comment]
> What's the output of `x.size(0)`?

It's equal to data.x.size(0).
I think it's the number of feature_matrix rows

**Comment by rusty1s** [comment]
Yes, it's the number of nodes. Just want to make sure that it's not zero.

**Comment by jiaruHithub** [comment]
> Yes, it's the number of nodes. Just want to make sure that it's not zero.

Yes!you are right!
I find after the second pooling layer, there is only one node left!
So how do I solve this?

**Comment by rusty1s** [comment]
Can you show me minimal example to reproduce this? I will look into it.

**Comment by rusty1s** [comment]
+ a minimal code would be great

**Comment by jiaruHithub** [comment]
> plus a minimal code to reproduce would be great

Fine,sometimes it get an error, sometimes it don't,I avoid this error through I meet the 1 nodes graph that I will not pool this graph.
If these days I have time,I will reproduce this code and find this error. Then I will contact you.
I usually use torch_geometric to do the experments.
That make me very greatful for your contribution and I will try to find this error and tell you!
Thank you vey match!
