### ISSUE TITLE
What is the relationship between DGL and PyG?

### ISSUE THREAD

**Issue by roholazandie** [rusty1s/pytorch_geometric#1365]
## ❓ Questions & Help

I wanted to implement some graph deep learning algorithm and I was confused about which one should I use? [DGL](https://github.com/dmlc/dgl) or Pytorch Geometric? I specifically want to make it easier to load data and sampling from the graph. Is this library lower level compared to DGL or is it a higher-level and easier?

**Comment by rusty1s** [comment]
The short answer is that you may want to try out both and see which one do you prefer. It's hard for me to give an unbiased opinion on that. Both libraries provide similar features, and it basically comes down to user preferences. In terms of performance, they are also similar (some GNNs are a bit faster on PyG and some are a bit slower). However, DGL has a better memory management for GNNs that can be expressed as a sparse matrix multiplication, but PyG will soon catch up.

I personally feel that DGL is designed as a low-level graph library, but most of its core is hidden behind a C++ API and hard to modify. Most of its high-level support is outsourced to its examples. PyG provides both low-level (in the form of utility functions, message passing interfaces, sampling interfaces, and GNN implementations) and high-level APIs (in the form of models).

DGL has great sampling support. PyG recently also added better support for sampling via `NeighborSampler`, `GraphSAINT` and `ClusterGCN`. 

In terms of data handling, it boils down to the question whether you like `networkx` or not. DGL has a similar graph interface to `networkx`, where as PyG provides all data as pure PyTorch tensors.

**Comment by roholazandie** [comment]
This is a very good and unbiased opinion I think. After working with both of them for almost two weeks I think PyG is better suited for me because it is more high-level and pythonic compared to DGL. I am very excited to see more features will be added to this great library!

**Comment by brando90** [comment]
@rusty1s what is the support for distributed computations (especially training) for Pytorch Geometric? Is it mainly Pytorch's distributed library (e.g. I often use DDP and would be nice if that worked out of the box with PyG...not sure how that works for DGL).

----

Btw, in my search for a comparison of libraries I collected a list of perhaps relevant links:

Comparison of DGL vs PyG by original developers
- https://discuss.dgl.ai/t/dgl-vs-pytorch-geometric/346/7 
- https://github.com/rusty1s/pytorch_geometric/issues/1365 

Question asking to compare DGL vs PyG
- https://www.reddit.com/r/pytorch/comments/n4xdy0/what_are_the_advantages_and_disadvantages_of/ 
- https://www.quora.com/unanswered/What-are-the-advantages-and-disadvantages-of-PyTorch-Geometric-vs-Deep-Graph-Library-DGL 
- https://www.quora.com/unanswered/What-is-the-best-Graph-Neural-Network-GNN-library-as-of-now-2021-for-PyTorch 
3rd party comparison:
- https://blog.paperspace.com/geometric-deep-learning-framework-comparison/ 
- https://trends.google.com/trends/explore?date=2017-09-03%202021-05-04&q=Deep%20Graph%20Library,Pytorch%20Geometric,Graph%20Nets 
DDP with DGL:
- https://discuss.dgl.ai/t/is-dgl-compatible-with-ddp-distributed-data-parallel/1956

**Comment by rusty1s** [comment]
We do not have a distributed graph storage layer yet, but distributed training is fully supported (either via [pure DDP PyTorch capabilities](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/multi_gpu) or [PyTorch Lightning](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/pytorch_lightning)).
