### ISSUE TITLE
Required parameter edge_index is empty #1064

### ISSUE THREAD

**Issue by dtchang** [rusty1s/pytorch_geometric#1369]
## 🐛 Bug

  File "C:\Anaconda3\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 180, in __distribute__
    raise TypeError(f'Required parameter {key} is empty.')

TypeError: Required parameter edge_index is empty.

## To Reproduce

See nn\conv\message_passing.py: Required parameter edge_index is empty #1064

## Expected behavior

This error should not happen since it is internal to PyG.

## Additional context

The source code is third party. It is not clear how to apply the suggested 'fix' in #1064, which is cryptic to a non-expert.

**Comment by rusty1s** [comment]
Can you share some information why you need `edge_index` in the message passing interface? Note that you can access `index`, which denotes all edges that belong to the same destination node.

**Comment by dtchang** [comment]
Here is a snippet of the related code (not mine, available on Github):
    def forward(self, x, edge_index, edge_attr, edge_attr_cutoffs=None
        ...
        return self.**propagate**(edge_index, size=(x.size(0), x.size(0)), x=x,  
            edge_attr=edge_attr, edge_attr_cutoffs=edge_attr_cutoffs)
    def **message**(self, x_j, edge_index, size, edge_attr, edge_attr_cutoffs):
        if self.make_bidirectional:
            # back to unidirectionality for reduced learning time
            row, col = edge_index[:,:int(edge_index.shape[1]/2)]
        else:
            row, col = edge_index
        ...

It meets the interface requirement of the message() method of MessagePassing:
     **message**(x_j: torch.Tensor) → torch.Tensor[source]
        Constructs messages from node j to node i in analogy to ϕΘ for each edge in 
        edge_index. **This function can take any argument as input which was initially 
        passed to propagate().** ...

I think PyG ought to honor the interface contract between message() and propagate(), since it is basic to programming.

In the meantime, if there is a workaround to remove edge_index from the message() interface and to get edge_index in its body, please let me know. Thanks.

**Comment by rusty1s** [comment]
This logic should be moved outside/before the `propagate` call. Modifying `edge_index` in `message` results in weird behaviour, and has certainly no effect in message propagation.

**Comment by dtchang** [comment]
The referenced code is not mine  and I don't know its implementation to be able to do what you suggested.

In any case, I think PyG ought to honor the interface contract between message() and propagate(), as documented, since this is basic to programming. PyG apparently did in 1.2.0, for which the referenced code was implemented. (The same apparently for issue #1064.)

**Comment by rusty1s** [comment]
I added it back in :)

**Comment by dtchang** [comment]
Thanks for your prompt response and action.
