### ISSUE TITLE
Is my code wrong or I don't konw the scatter's mechanism?

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1370]
## ❓ Questions & Help

I want to use ```scatter``` to generate a matrix.
My code is:
```    
x, (edge_index, edge_wight), batch = data.x, add_remaining_self_loops(data.edge_index), data.batch
        
xi, xj = x[edge_index[0]], x[edge_index[1]]    
x_neig = xi-xj

#compute max(xi-xj)
x_max = scatter(x_neig, edge_index[0], dim=0, reduce='max')
```
I think ```x_neig```'s dimension is```(num_nodes,num_feature)```

But it reported error:
```RuntimeError: The expanded size of the tensor (4014) must match the existing size (4021) at non-singleton dimension 0.  Target sizes: [4014].  Tensor sizes: [4021]  
The above operation failed in interpreter.
Traceback (most recent call last):
  File "\lib\site-packages\torch_scatter\scatter.py", line 31
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
  File "\lib\site-packages\torch_scatter\scatter.py", line 12, in scatter_sum
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
            ~~~~~~~~~ <--- HERE
    if out is None:
        size = src.size()
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\utils.py", line 13, in broadcast
    for _ in range(src.dim(), other.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
          ~~~~~~~~~~~~~ <--- HERE
    return src
```
And I ues ```torchsnooper.snoop()``` to tracked tensor:
```
tarting var:.. x = tensor<(4021, 128), float32, cuda:0, grad>
Starting var:.. edge_index = tensor<(2, 11652), int64, cuda:0>
Starting var:.. edge_attr = None
Starting var:.. batch = tensor<(4021,), int64, cuda:0>
22:14:17.365985 call        19     def forward(self, x, edge_index, edge_attr=None, batch=None):
22:14:17.367979 line        20         if batch is None:
22:14:17.371970 line        23         x = x.unsqueeze(-1) if x.dim() == 1 else x
22:14:17.373963 line        24         xi, xj = x[edge_index[0]], x[edge_index[1]]
New var:....... xi = tensor<(11652, 128), float32, cuda:0, grad>
New var:....... xj = tensor<(11652, 128), float32, cuda:0, grad>
22:14:17.374960 line        25         x_neig = xi-xj
New var:....... x_neig = tensor<(11652, 128), float32, cuda:0, grad>
22:14:17.377953 line        28         x_neig_max = scatter(x_neig, edge_index[0], dim=0, reduce='max')
New var:....... x_neig_max = tensor<(4014, 128), float32, cuda:0, grad>
```
Can you tell me why?
Thank you!

**Comment by jiaruHithub** [comment]
And I use dataset that ```Mutagenicity```. In other datasetlike ```DD/PROTEINS/NCI1/NCI109```, it is not report  this error.

**Comment by rusty1s** [comment]
Seems like a TorchScript issue. Seems weird, as I cannot reproduce and it does only occur on that dataset.

You can try to remove the `@torch.jit.script` annotations in `D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\utils.py` and `D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\scatter.py` to see if that fixes the issue.

**Comment by jiaruHithub** [comment]
> Seems like a TorchScript issue. Seems weird, as I cannot reproduce and it does only occur on that dataset.
> 
> You can try to remove the `@torch.jit.script` annotations in `D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\utils.py` and `D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\scatter.py` to see if that fixes the issue.

If I comment all ```@torch.jit.script```,it report error:
```
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    out = model(data)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\muqian\code\SAGPool-master333333333333333333\SAGPool-master\networks.py", line 41, in forward
    x = F.relu(self.conv1(x, edge_index))
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 102, in forward
    self.node_dim), edge_weight, self.improved, x.dtype)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 80, in norm
    deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\scatter.py", line 31, in scatter_add
    return scatter_sum(src, index, dim, out, dim_size)
  File "D:\anna\Anaconda\envs\torch1.4.0\lib\site-packages\torch_scatter\scatter.py", line 16, in scatter_sum
    size[dim] = dim_size
TypeError: 'torch.Size' object does not support item assignment
```
If I only comment ```utils``` and ```scatter.scatter_max``` it stall get the same error of dimension.
Do you have another methods?It bothered me for a few days.
Thank you very match!

**Comment by rusty1s** [comment]
You can try replacing line 14 in `scatter.py` with `size = list(src.size())`. This might be a hacky fix, but I am absolutely unsure what may cause this.

**Comment by jiaruHithub** [comment]
> You can try replacing line 14 in `scatter.py` with `size = list(src.size())`. This might be a hacky fix, but I am absolutely unsure what may cause this.

I'm sorry.It's still get an same error of dimension.
Is line14 used to be ```size = src.size()``` in ```scatter_sum```?
I try to print the ```size```(after replace) and I find the size from 11659 become 11652(I use ---------- to note).
```
------ [11659]
------ [11659, 128]
Starting var:.. self = SAGPool(  (score_layer): GCNConv(128, 1))
Starting var:.. x = tensor<(4021, 128), float32, cuda:0, grad>
Starting var:.. edge_index = tensor<(2, 11652), int64, cuda:0>
Starting var:.. edge_attr = None
Starting var:.. batch = tensor<(4021,), int64, cuda:0>
18:44:46.323857 call        19     def forward(self, x, edge_index, edge_attr=None, batch=None):
18:44:46.325852 line        20         if batch is None:
18:44:46.326848 line        23         x = x.unsqueeze(-1) if x.dim() == 1 else x
18:44:46.327847 line        24         xi, xj = x[edge_index[0]], x[edge_index[1]]
New var:....... xi = tensor<(11652, 128), float32, cuda:0, grad>
New var:....... xj = tensor<(11652, 128), float32, cuda:0, grad>
18:44:46.328843 line        25         x_neig = xi-xj
New var:....... x_neig = tensor<(11652, 128), float32, cuda:0, grad>
18:44:46.331836 line        28         x_neig_max = scatter(x_neig, edge_index[0], dim=0, reduce='max')
New var:....... x_max = tensor<(4014, 128), float32, cuda:0, grad>
18:44:46.335856 line        31         if x.size(0) == 1:
18:44:46.343804 line        49             score = selx.score_layer(x_max,edge_index).squeeze()
------ [11652]
------ [11652, 1]
New var:....... score = tensor<(4014,), float32, cuda:0, grad>
18:44:46.352780 line        52             perm = topk(score, self.ratio, batch)
18:44:46.357766 exception   52             perm = topk(score, self.ratio, batch)
```
I really don't know why.
Could you figure it out?

**Comment by rusty1s** [comment]
Ah, I see. You are talking about a wrong output shape, so the computation runs through by now. You should pass the `dim_size` attribute to the `scatter` call, otherwise it guesses the output shape based on the highest value it finds in `edge_index`:
```python
x_max = scatter(x_neig, edge_index[0], dim=0, dim_size=x.size(0), reduce='max')
```

**Comment by jiaruHithub** [comment]
> ```python
> x_max = scatter(x_neig, edge_index[0], dim=0, dim_size=x.size(0), reduce='max')
> ```

You are right!Grateful to you!
Let me think about the principle again.

I use func ```add_remain_self_loop```.So I think the highest value of ```edgae_index``` is equal to highest value of ```num_nodes```.But after pooling, there maybe remove the nodes that highest value of index.So we need use ```dim_size```.
Am I right?

**Comment by rusty1s** [comment]
I see. You should also pass `num_nodes` to `add_remaining_self_loops`.

**Comment by jiaruHithub** [comment]
> I see. You should also pass `num_nodes` to `add_remaining_self_loops`.

```add_remaining_self_loop(data.num_nodes)```,is this your mean?

**Comment by rusty1s** [comment]
`add_remaining_self_loops(data.edge_index, num_nodes=data.num_nodes)`

**Comment by jiaruHithub** [comment]
> `add_remaining_self_loops(data.edge_index, num_nodes=data.num_nodes)`

If like this, I don't need use ```dim_size```?
Anyway, thank you so much.

**Comment by rusty1s** [comment]
You should still use `dim_size` for faster computation, but it is not mandatory.

**Comment by jiaruHithub** [comment]
yes!Thank you for your precious answer!
I wish you have a happy life!
