### ISSUE TITLE
ClusterData for R-GCN (passing edge_type)

### ISSUE THREAD

**Issue by shaanchandra** [rusty1s/pytorch_geometric#1373]
## ❓ Questions & Help

Hi,
Thank you for the amazing library and documentation!

I am trying to use R-GCN for my project but am running into memory issues. Until now I was working with the full graph but now want to try `ClusterData`.

However, I do not see any option to pass the `edge_type` to create the `Data` object which will later be used by `ClusterData`. I see there is the `edge_attr` but I do not think they are the same (looking at the expected sizes of both these parameters).

Or do you believe that one way would be to convert `edge_type` into `edge_attr` by for example making it one-hot? And later before passing it to the `forward` of `RGCNConv` make it `[num_edges]` shape again from `[num_edges, num_edge_features]` ??

Or am I completely missing something? 

PS: I find the out of memory issue slightly weird too. I have a graph of 22k nodes and 750k edges with 4 relations. Even when I set the `num_bases` to less than 4 it does not help. It says "Tried to allocate 1300GB...". Which does not seem right to me. Any thoughts?

**Comment by rusty1s** [comment]
Hi, you can simply pass your `edge_type` to `edge_attr`. I see that this is not really intuitive, but it works. I will try to figure out a better way to achieve this. 

For the latter problem. This is mainly an issue with the current`RGCN` implementation, which maps the `weight` matrix to a huge `[num_edges, in_channels, out_channels]` tensor. If you're number of relations is relatively small, this is absolutely not necessary. A more simple fix is to use a loop to iterate over your relations, *e.g.*, like:
```python
class MyOwnRGCNConv(torch.nn.Module):
    def __init__(self, in_channels, out_channels, num_rels):
        super(MyOwnRGCNConv, self).__init__()
        self.num_rels = num_rels
        self.convs = torch.nn.ModuleList([SAGEConv(in_channels, out_channels) for _ in range(num_rels)])

    def forward(self, x, edge_index, edge_type):
         out = 0
         for i in range(self.num_rels):
             mask = edge_type == i
            out += self.convs[i](x, edge_index[:, mask])
        return out
```
I have plans though to improve the `RGCNConv` (should be coming in the next week) :)

**Comment by shaanchandra** [comment]
Hi,

Ok yes. I see that now. 
I think your suggestions should work well for now! I will give it a try.
Thanks a ton :)
