### ISSUE TITLE
Question about reset_parameters().

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1383]
> ## ❓ Questions & Help

I found a func in [https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/train_eval.py](url) line34 that named reset_parameters().
I did't found the source code.
I don't know the func's principle of realization.
Could show me the source code of ```reset_parameters```?

**Comment by rusty1s** [comment]
It's defined in each model, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/gcn.py#L28-L30).

**Comment by jiaruHithub** [comment]
> It's defined in each model, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/gcn.py#L28-L30).

Fine,think you.
I wish you a happy life,friends
