### ISSUE TITLE
Add additional data in torch_geometric.data

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_geometric#1390]
## ❓ Questions & Help

The doc says we can add additional data while using `torch_geometric.data` from [link](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html).

```
The data object is not restricted to these attributes and can be extented by any other additional data.

Example:

data = Data(x=x, edge_index=edge_index)
data.train_idx = torch.tensor([...], dtype=torch.long)
data.test_mask = torch.tensor([...], dtype=torch.bool)
```

However, the additional data will be changed when enumerating the dataloader.
Is it possible to add additional data which will NOT changed when enumerating the dataloader?

/cc @rusty1s

**Comment by rusty1s** [comment]
What do you mean with the data will be changed? I am not sure I understand that. Can you give me an example?

**Comment by mingloo** [comment]
Hi @rusty1s,

After double check the code, I think the root cause is I added the additional data named "*_index" to the `Data` class.  
When creating batches, the incremental count of this attribute is cumulatively increased. See below for details.

```
    def __inc__(self, key, value):
        r""""Returns the incremental count to cumulatively increase the value
        of the next attribute of :obj:`key` when creating batches.

        .. note::

            This method is for internal use only, and should only be overridden
            if the batch concatenation process is corrupted for a specific data
            attribute.
        """
        # Only `*index*` and `*face*` should be cumulatively summed up when
        # creating batches.
        return self.num_nodes if bool(re.search('(index|face)', key)) else 0
```

**Comment by rusty1s** [comment]
Yes, that‘s correct. If you have an attribute named `index` that indices specific nodes or edges, one would expect it to behave correctly for mini-batches.

**Comment by mingloo** [comment]
@rusty1s 

Thanks for your confirmation.

Closed.
