### ISSUE TITLE
Question about dataset `FRANKENSTEIN` and `Mutagenicity`

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1395]
## ❓ Questions & Help

I found in func ```TUDdatset``` has tow dataset ```FRANKENSTEIN``` and ```Mutagenicity```.
In graph pooling papers like SAGPool and ASAP they always use dataset ```FRANKENSTEIN``` in paper's table.
But I found in it's source code,it only has dataset ```Mutagenicity``` has no ```FRANKENSTEIN```.
Does that mean they're the same dataset?If thay are nat same,What is the difference between them?And why those papers source code only use dataset ```Mutagenicity```?
It bothered me for a few days.
Thanky very mach!friends

**Comment by rusty1s** [comment]
I don't know the details of those datasets, but they are not the same as indicated [here](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets).

**Comment by jiaruHithub** [comment]
> I don't know the details of those datasets, but they are not the same as indicated [here](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets).

Fine, Thank you!
