### ISSUE TITLE
Should the ‘concat’ parameter in line 20 of 'pytorch_geometric/examples/gat.py' be 'False'?

### ISSUE THREAD

**Issue by maqy1995** [rusty1s/pytorch_geometric#1396]
the code is below:
https://github.com/rusty1s/pytorch_geometric/blob/a6ed9c20da8784f4f39bd2e0eb062d9c87bbfb13/examples/gat.py#L20-L21

At the last layer, is it necessary to mean the output, that is, set 'cancat' to "False"?

**Comment by rusty1s** [comment]
No, it's not mandatory in case `heads=1`, but it might be if you add more heads.

**Comment by rusty1s** [comment]
It's changed in master now :)

**Comment by maqy1995** [comment]
Thanks for your prompt reply, I will close this issue.
