### ISSUE TITLE
FixedPoints transformation not working as intended

### ISSUE THREAD

**Issue by pvnieo** [rusty1s/pytorch_geometric#1402]
## 🐛 Bug

Hi,
I was using FixedPoints from a while ago, it was working well until I reinstalled pytorch geometric on a new machine, and it not working any more as intended.

When I checked the source, I found that when using `replace=False`, the normal behavior as described in the documentation is to sample a fixed number of points `num`  if it's smaller that the total points of the pointcloud `num_nodes`, otherwise keep the duplicate to a minimum. However, what's happening is when `num_nodes` is smaller than `num`, only `num_nodes` will be returned.

Here's the old source That was working for me:
```
       if self.replace:
            choice = np.random.choice(num_nodes, self.num, replace=True)
        else:
            choice = torch.cat([
                torch.randperm(num_nodes)
                for _ in range(math.ceil(self.num / num_nodes))
            ], dim=0)[:self.num]
```

and here's the new one:
```
       if self.replace:
            choice = np.random.choice(num_nodes, self.num, replace=True)
        else:
            choice = torch.cat([
                torch.randperm(num_nodes)
                for _ in range(math.ceil(self.num / num_nodes))
            ], dim=0)[:min(self.num, num_nodes)]
```
we can notice that instead of returning `[:self.num]` it returns the min, which is not the behaviour described in the documentation.

Is this changement intended?

**Comment by rusty1s** [comment]
I agree. This is not in line with the documentation. How about we add an option to allow duplicates or not. Would that be fine for you?

**Comment by pvnieo** [comment]
Thank you for your response. Is this version released yet?

**Comment by rusty1s** [comment]
No, it's currently only in master. I will release a new version in the upcoming week.

**Comment by pvnieo** [comment]
closing the issue since this will be solved in the next release!
