### ISSUE TITLE
Question about scatter

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1405]
## ❓ Questions & Help

Hi, friends
If I had a one graph as input.I writte a code as follow:
```
x, edge_index= data.x, data.edge_index
x_i, x_j= x[edge_index[0]], x[edge_index[1]]
x = x_i + x_j
a = scatter(x, edge_index[0], dim=0, reduce='max')
b = scatter(x, edge_index[1], dim=0, reduce='max')
```
I think every row in ```a``` is the maximum of every node's ```x_i+x_j```(j is the all neighbor of node i).
Am I right?
I dont't know what dose ```b``` stand for.
Could you tell me what is difference of ```a``` and ```b```?
Thank you very much!

**Comment by rusty1s** [comment]
There is no difference between the two formulations in case your graph is undirected. However, in case it is directed, `a` stands for a message passing flow from target to source, and `b` stands for a message passing flow from source to target.

The difference is which indices are used to aggregate. `edge_index[1]` denotes the target indices of each edge, and `edge_index[0]` denotes the source nodes of each edge.

**Comment by jiaruHithub** [comment]
Fine, thank you !
