### ISSUE TITLE
How does GNNExplainer handle edge_attr in message passing layers?

### ISSUE THREAD

**Issue by Wuyxin** [rusty1s/pytorch_geometric#1406]
## ❓ Questions & Help

Question is above,  and GNNExplainer is actually use module.__edge_mask__  of message passing mechanism to learn edge_mask. Further, I have checked the code in class MessagePassing(line 261)

```
if mp_type == 'edge_index' or not self.__fuse__ or self.__explain__:
            msg_kwargs = self.__distribute__(self.__msg_params__, kwargs)
            print(msg_kwargs)
            out = self.message(**msg_kwargs)
            
            if self.__explain__:
                edge_mask = self.__edge_mask__.sigmoid()
                if out.size(0) != edge_mask.size(0):
                    loop = edge_mask.new_ones(size[0])
                    edge_mask = torch.cat([edge_mask, loop], dim=0)
                assert out.size(0) == edge_mask.size(0)
                out = out * edge_mask.view(-1, 1)
                
            aggr_kwargs = self.__distribute__(self.__aggr_params__, kwargs)
            out = self.aggregate(out, **aggr_kwargs)

```

And i found edge_attr is actually in msg_kwargs['pseudo'], wihch i think may not be transferred into the model.
Is it a bug in the code or i misunderstand something?

many thanks!

**Comment by rusty1s** [comment]
The `GNNExplainer` module finds meaningful edges that are necessary to maintain the same prediction. It therefore weights each message by this edge weight before aggregating. You can still use edge attributes in your model, *e.g.* the `message` function.

**Comment by Wuyxin** [comment]
> The `GNNExplainer` module finds meaningful edges that are necessary to maintain the same prediction. It therefore weights each message by this edge weight before aggregating. You can still use edge attributes in your model, _e.g._ the `message` function.
 I just print msg_kwargs:
```
{'x_j': tensor([[0.0498, 0.0000, 0.6326, 0.1092, 0.0000, 0.6929],
        [0.0731, 0.0000, 0.6274, 0.1142, 0.0000, 0.6927],
        [0.0731, 0.0000, 0.6274, 0.1142, 0.0000, 0.6927],
        [0.0000, 0.0000, 0.6050, 0.1315, 0.0000, 0.6978]], device='cuda:0',
       grad_fn=<IndexSelectBackward>), 'pseudo': tensor([[ 0.5289, -0.4522],
        [ 0.5289,  0.4217],
        [-0.5265,  0.0259],
        [-0.5265, -0.4318]], device='cuda:0', grad_fn=<PermuteBackward>)}
```

So you mean that for
```
explain_node(node_idx, x, edge_index, **kwargs)
```
I just need to feed edge_attr into **kwargs, and then it will distribute it to the message passing layers after the "Gate Operation"?

**Comment by rusty1s** [comment]
Yes, exactly!

**Comment by Wuyxin** [comment]
and how could it recognizes 'pseudo' as edge_attr?  e.g. NNConv, there are some other parameters except for edge_attr.

**Comment by rusty1s** [comment]
If your model's forward method is defined as `def forward(self, x, edge_index, edge_attr)`, you can call `GNNExplainer.explain_node(node_idx, x, edge_index, edge_attr)`.

**Comment by Wuyxin** [comment]
gotcha! thx 👍

**Comment by Wuyxin** [comment]
btw, "for key, item in kwargs" seems to trigger some Bug, and "for key, item in kwargs.items():" works for me.

···
def __subgraph__(self, node_idx, x, edge_index, **kwargs):
        num_nodes, num_edges = x.size(0), edge_index.size(1)
        
        subset, edge_index, mapping, edge_mask = k_hop_subgraph(
            node_idx, self.__num_hops__(), edge_index, relabel_nodes=True,
            num_nodes=num_nodes, flow=self.__flow__())
        
        self.subset = subset
        x = x[subset]
        for key, item in **kwargs.items()**:
            
            if torch.is_tensor(item) and item.size(0) == num_nodes:
                item = item[subset]
            elif torch.is_tensor(item) and item.size(0) == num_edges:
                item = item[edge_mask]
            kwargs[key] = item

        return x, edge_index, mapping, edge_mask, kwargs
···

**Comment by rusty1s** [comment]
Thanks for letting me know. Fixed in master :)
