### ISSUE TITLE
multi GPU training

### ISSUE THREAD

**Issue by trinayan** [rusty1s/pytorch_geometric#1417]
## ❓ Questions & Help

Hi,

For the examples provided under PyTorch Geometric, do all of them support multi-GPU trainng?. Or do we need to modify them to enable multi-GPU support training. Thank you.

Best,
Trinayan

**Comment by rusty1s** [comment]
We currently only provide multi-GPU training for a set of graph objects via `DataParallel`. An example can be found in `examples/data_parallel.py`. Distributed training is in the pipeline though :)

**Comment by trinayan** [comment]
thanks a lot

**Comment by trinayan** [comment]
Sorry need to reopen this again.  You mentioned distributed training is in the pipeline. I wanted to know if there are any issues or known limitations on wrapping the models in the available examples with DistributedDataParallel from pytorch since it is more performant than DataParallel?. I am not really looking for any optimization at the moment. Just some basic way to get some of the examples working with multi-GPU.  Thanks again

**Comment by rusty1s** [comment]
We cannot use the `DistributedDataParallel` from PyTorch directly since we don't have a real batch dimension. Therefore, we need to implement our own logic to split the data to multiple GPUs.

**Comment by trinayan** [comment]
Got it. Looking forward to the distributed training :). Thanks for the great work

**Comment by pyli0628** [comment]
> We cannot use the `DistributedDataParallel` from PyTorch directly since we don't have a real batch dimension. Therefore, we need to implement our own logic to split the data to multiple GPUs.

Seems that DistributedDataParallel worked with DistributedSampler from Pytorch split the raw data to multiple GPUs according to the index and then batch the data on each GPU, rather than directly split the batch data to GPUS. So the DistributedDataParallel from pytorch can be directly used. Correct me if I'm wrong.

**Comment by pyli0628** [comment]
> We cannot use the `DistributedDataParallel` from PyTorch directly since we don't have a real batch dimension. Therefore, we need to implement our own logic to split the data to multiple GPUs.

Seems that DistributedDataParallel worked with DistributedSampler from Pytorch split the raw data to multiple GPUs according to the index and then batch the data on each GPU, rather than directly split the batch data to GPUS. So the DistributedDataParallel from pytorch can be directly used. Correct me if I'm wrong.

**Comment by rusty1s** [comment]
Thanks for letting me know. I will look into it. Feel free to submit a PR if you got it working :)

**Comment by nghorbani** [comment]
> We cannot use the `DistributedDataParallel` from PyTorch directly since we don't have a real batch dimension. Therefore, we need to implement our own logic to split the data to multiple GPUs.

training on DDP with pytorch-geometric data loader is very needed and a tutorial is much appreciated.

**Comment by rusty1s** [comment]
It's in the pipeline for PyG 1.7.0. Please stay tuned :)

**Comment by rusty1s** [comment]
You can now find examples of distributed training both for learning on multiple graphs and single giant graphs [here](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/multi_gpu).

**Comment by diamondspark** [comment]
@rusty1s How do I train on a subset of available GPUs?
Thank You!

**Comment by diamondspark** [comment]
> @rusty1s How do I train on a subset of available GPUs? Thank You!

To anyone stumbling upon this following is how I solved this
from torch_geometric.nn import DataParallel
model = DataParallel(model,  device_ids= [0,1,2])

**Comment by trinayan** [comment]
If you dont want to make source changes u can also use environment variable
CUDA_VISIBLE_DEVICES which starts from 0 to N-1 to achieve the same
functionality.

**Comment by HelloWorldLTY** [comment]
Hi all, I wonder if there are any methods I can use for one large graph with multi-gpu training. Must I change it into subgraph? Thanks a lot.

**Comment by rusty1s** [comment]
See https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py

**Comment by Alicia1688** [comment]
> See https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py
hi, are there any examples of DDP (DistributedDataParallel) now?

**Comment by akihironitta** [comment]
@Alicia1688 Yes, please have a look: https://github.com/search?q=repo%3Apyg-team%2Fpytorch_geometric%20DistributedDataParallel&type=code

**Comment by Alicia1688** [comment]
> @Alicia1688 Yes, please have a look: https://github.com/search?q=repo%3Apyg-team%2Fpytorch_geometric%20DistributedDataParallel&type=code

Thanks a lot, are there any applications currently using DDP for graph classification? My dataset is composed of many graphs. I'm currently treating them as normal data and training successfully using DDP, but I'm not quite sure if my modifications are correct.

**Comment by Alicia1688** [comment]
> @Alicia1688 Have you had a chance to loook at this example by chance? https://github.com/pyg-team/pytorch_geometric/blob/2.4.0/examples/multi_gpu/distributed_batching.py

Thank you very much, I'm going to take a look at this example.

**Comment by HanChen-HUST** [comment]
@akihironitta, Hi, I tried to use this link: https://github.com/pyg-team/pytorch_geometric/blob/2.4.0/examples/multi_gpu/distributed_batching.py in the Cora dataset, but the communication speed is extremely slow, could you analysis the reason？

**Comment by akihironitta** [comment]
@HanChen-HUST How did you measure the communication latency in your script? Assuming you're using NVIDIA GPUs, can you make sure `nccl` is used instead of `gloo`? Also, what's the output of `nvidia-smi topo -m`?

**Comment by HanChen-HUST** [comment]
yes, i will create a new one and close this one.
