### ISSUE TITLE
type mismatch when using batched_negative_sampling

### ISSUE THREAD

**Issue by v1093** [rusty1s/pytorch_geometric#1418]
Hi, I am doing few experiments with batched negative sampling strategy using multiple graphs. I have an edge_index tensor representing 4 fully connected graphs and these are categorized into 3 examples using batch tensor.

When batched_negative_sampling, I see two results what I don't expect.

1. type mismatch: negative_edge_indices contains first two empty tensors which are of float32 dtype and third tensor with int64 dtype. So [torch.cat](https://github.com/rusty1s/pytorch_geometric/blob/29e2dac7554b6a2a652d07de15d9682cdc941a50/torch_geometric/utils/negative_sampling.py#L163) raises:
`RuntimeError: Expected object of scalar type float but got scalar type __int64 for sequence element 2.`

2. first two tensors being empty is ok but the third tensor contains positive edge indices as well inside negative_edge_indices.

To reproduce:
```
edge_index = torch.tensor([[0, 1, 2, 1, 2, 3, 4, 3, 4, 5, 6, 5, 6], 
                                            [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]])

batch = torch.tensor([0, 1, 1, 2, 2, 2, 2])

neg_edge_index = batched_negative_sampling(edge_index, batch)
```

**Comment by rusty1s** [comment]
Thanks for reporting, this is now fixed in master.
