### ISSUE TITLE
Create new dataset creation and process multiple graphs simultaneously

### ISSUE THREAD

**Issue by chu525** [rusty1s/pytorch_geometric#142]
## ❓ Questions & Help

Hello, Thank you for your great contribution. I have a problem. I have 60,000 graphs ,Let's say I have a total of m graphs, for example,
"""
nodes：[[[1],[2],[4],[5],[7]], [[5],[6],[7],[8]], [[3],[4],[5],[8],[7],[10]], ...., [[5],[6],[7],[8]]], Represents the set of all the edges of each m graph.  [[1],[2],[4],[5]], Represents all nodes of one of the diagrams
edges：[[[1,2],[3,4],[5,6],[9,10],[0,1]], [[1,2],[3,4],[5,6]], ...., [[1,2],[3,4]]] ,Represents the set of all the edges of each m graph , [[1,2],[3,4],[5,6],[9,10],[0,1]]  Represents the set of all the edges of one of the graphs
"""
I try to use the **data** in the **torch_geometric.data**  function ,But this can only be passed in graph by graph,_I want to use **batch size** to process batch size graphs simultaneously._ ,I checked the document and tried various ways, but failed to process the data successfully into the GCN model. May I ask what I should do? Thank you

**Comment by rusty1s** [comment]
We provide the `torch_geometric.data.DataLoader` for automatic creation and processing of mini-batches, *e.g.*:
```python
from torch_geometric.data import DataLoader

data_list = [Data(...), Data(...), Data(...)]  # Alternatively, create a `torch_geometric.data.Dataset`.

loader = DataLoader(data_list, batch_size=32, shuffle=True)
for batch in loader:
    print(batch)
```
You can read more about mini-batches [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#mini-batches). I hope I understood your question correctly.

**Comment by chu525** [comment]
Thanks for your reply，This solution can solve my problem. Thank you very much .
