### ISSUE TITLE
ERROR: torchvision 0.6.0+cu101 has requirement torch==1.5.0, but you'll have torch 1.5.1 which is incompatible.

### ISSUE THREAD

**Issue by LiCHOTHU** [rusty1s/pytorch_geometric#1421]
## Environment

* OS: Ubuntu 18.04
* Python version: 3.6
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.1
* GCC version: 7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
* Any other relevant information:

## Checklist

- [~ ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ ~] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ~] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ~] I do have multiple CUDA versions on my machine.

## Additional context

I am trying to install torch_geometric on my conda environment but always get this error,
ERROR: torchvision 0.6.0+cu101 has requirement torch==1.5.0, but you'll have torch 1.5.1 which is incompatible.
But I have checked my torch==1.5.0 
At the beginning of the installation, it starts collecting torch==1.5.1
    Downloading torch-1.5.1-cp36-cp36m-manylinux1_x86_64.whl (753.2 MB)

**Comment by rusty1s** [comment]
I'm not sure I understand the issue. Is that PyTorch Geometric related? In case you install PyTorch 1.5.1, you need torchvision 0.6.1.
