### ISSUE TITLE
Question about global_max_pooling

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1426]
## ❓ Questions & Help

I found the func ```global_max_pooling``` use torch_scatter to implement.
I want know how to compute the max value of a feature_matrix?
Is it use absolute value or other func to select the max value of feature matrix?
Could you tell me the principle of implementation?Thank you very mach!

**Comment by rusty1s** [comment]
The maximum is taken over the reduce dimension, hence it uses the absolute value encountered for same indices:
```python
x = [[3, 4], [5, 2], [2, 1]]
index = [0, 0, 1]
out = scatter(x, index, dim=0, reduce='max')
>>> [[5, 4], [2, 1]]
```

**Comment by jiaruHithub** [comment]
Fine,thank you for your answer.
But I can't understank how to correspond ```index``` and ```dim``` to ```x```,in this case.
Could you tell me more about it?It troubled me a few days.
Thank you very mach!

**Comment by rusty1s** [comment]
`dim` denotes along which axis we want to aggregate. For an input tensor of shape `[E, D]`, and an index tensor of shape `[E]`, a `scatter` operation in dimension `0` will reduce the tensor to a shape of `[N, D]`, where `N = index.max() + 1`. Basically, you need to ensure that `index.size(0) == inputs.size(dim)`.

**Comment by jiaruHithub** [comment]
Fine!thank you!I know it.
