### ISSUE TITLE
Nods Classification or Signal Classification?

### ISSUE THREAD

**Issue by hojaeklee** [rusty1s/pytorch_geometric#143]
## ❓ Questions & Help

Hi, I was looking GCNConv and ChebConv, and was wondering if they are meant to be used for node classification only? Is it possible to do a signal classification based on signal over a feature graph?

**Comment by rusty1s** [comment]
You mean like graph classification? The GCNConv and ChebConv is less often seen in those inductive scenarios demue to their motivation from spectral graph theory. The domain-dependent Fourier bases restrict generalization to inputs with identical graph connectivity.
