### ISSUE TITLE
reshape data after Sampling

### ISSUE THREAD

**Issue by shangguan91** [rusty1s/pytorch_geometric#1433]
![image](https://user-images.githubusercontent.com/64595972/87673327-a9f8a580-c774-11ea-9999-6ebac989c446.png)

how could i extract all pos in data. then turn that list into array, then use np.stack?

**Comment by rusty1s** [comment]
If I understand you correctly, this should work:
```python
torch.stack([data.pos for data in data_list], dim=0)
```
