### ISSUE TITLE
Block diagonal as part of custom collate

### ISSUE THREAD

**Issue by mshuaibii** [rusty1s/pytorch_geometric#1436]
## ❓ Questions & Help

Hi @rusty1s ,

My Data objects contain matrices of variable size that I wish to construct a block diagonal matrix as part of the batching process. Something like this works fine if the objects have the same dimensions:

```
def collate_block(data_list):
   batch = Batch.from_data_list(data_list)
   block_matrix = block_diag([data.mtx for data in data_list])
   batch.mtx = block_matrix
   return batch
```

However, I have scenarios where `data.mtx` are not always the same dimension (in both dimensions) and padding them seems out of the way if I need construct this. Is there anyway to skip this key perse in the default batch and allow myself to feed it in directly?

Thanks!

**Comment by rusty1s** [comment]
I see. We do not have support for ignoring specific keys at the moment. So, an alternative would be to remove the attribute first and add it back in later:
```python
def collate_block(data_list):
   mtxs = []
   for data in data_list:
       mtxs.append(data.mtx)
        data.mtx = None
   batch = Batch.from_data_list(data_list)
   block_matrix = block_diag(mtxs)
   batch.mtx = block_matrix
   return batch
```
