### ISSUE TITLE
How to debug inside process function in dataset creation

### ISSUE THREAD

**Issue by LanceKnight** [rusty1s/pytorch_geometric#1439]
## ❓ Questions & Help
Hello, I'm a newbie and I found my print didn't work inside process for my dataset class. A simplified demo is below:

class MyDataset(InMemoryDataset):

    def __init__(self, root, transform=None, pre_transform=None):
        super(SynDataset, self).__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return ['dataSetB']
    @property
    def processed_file_names(self):
        return ['processed_data.dataset']

    def download(self):
        pass
    
    def process(self):
        print('this is a test')

**Comment by rusty1s** [comment]
This shouldn't be the case. At least, I cannot reproduce this issue. It prints "this is a test" for me. Note that you need to pass `MyDataset` not `SynDataset` in your `__init__` call . Do you have a complete script to reproduce?

**Comment by LanceKnight** [comment]
Hi, rusty1s, sorry I forgot to mention that I was using Colab. The complete script is shown as follows:

class SynDataset(InMemoryDataset):
  def __init__(self, root, transform=None, pre_transform=None):
    super(SynDataset, self).__init__(root, transform, pre_transform)
    self.data, self.slices = torch.load(self.processed_paths[0])

  @property
  def raw_file_names(self):
    return ['dataSetB']
  @property
  def processed_file_names(self):
    return ['processed_data.dataset']

  def download(self):
    pass
  
  def process(self):
    num_mul_products_rxn = 0
    mul_products_rxn_list=[]
    num_valid_products = 0 # number of main products
    num_none_mol = 0 # number for SMILES that cannot be convert to adjacency matrix
      
    curated_training = []

    for i in range(num_exp_data):
      rxn = rdChemReactions.ReactionFromSmarts(exp_data[i])
      products=rxn.GetProducts()
      print('reaction '+str(i) +' has ' + str(len(products)) + ' products')
      if(len(products)>1):
        num_mul_products_rxn+=1
        mul_products_rxn =(i, len(products))
        # print('rxn_id' + ', num_products:'+ str(mul_products_rxn))
        mul_products_rxn_list.append(mul_products_rxn)

      for j in range(len(products)):
        product_smile = rdmolfiles.MolToSmiles(products[j])
        if len(product_smile)<byproduct_cutoff:
          # cprint(str(len(product_smile))+':'+ product_smile,'green')
          continue
        else:
          # first_curated.append(product_smile) # add main product to curated training data
          num_valid_products+=1
          cprint(str(len(product_smile))+':'+ product_smile,'blue')
          if SMILES2Adjacency(product_smile) is not None:
            A = SMILES2Adjacency(product_smile) # get adjacency matrix of the product, in numpy.matrix 
            num_nodes = len(A) # get the num of nodes
            sA = sparse.csr_matrix(A) # convert A from numpy.matrix to scipy sparse matrix
            edge_index, edge_weight=convert.from_scipy_sparse_matrix(sA) # convert from scipy sparse matrix to edge_index
            x = torch.tensor([[1]*num_nodes]).t()
            y = 1
            data = Data(x=x, edge_index=edge_index, y=y)
            # print('data:'+str(data))
            # print(edge_index)
            curated_training.append(data)
          else:
            num_none_mol+=1
            continue
    
    data, slices = self.collate(curated_training)
    torch.save((data, slices), self.processed_paths[0])

**Comment by rusty1s** [comment]
And what‘s not working? Note that process will get skipped in case the processed files already exist. You may want to delete those prior to debugging the process method.

**Comment by LanceKnight** [comment]
Aha! That was the issue! My codes were simply not executed due to the existence of the processed files. What a dumb question! Thank you very much rusty1s!!

**Comment by rusty1s** [comment]
Great!
