### ISSUE TITLE
How to load train_dataset and batch in 'larger' datasets 

### ISSUE THREAD

**Issue by feiwww** [rusty1s/pytorch_geometric#144]
## ❓ Questions & Help

 Thanks for your awesome code!

I got some problems when starting to create my own 'larger' datasets. As PyG document, a “larger” datasets was constructed. It seems that every graph was saved into a file(data_*.pt). I know in InMemoryDataset we have slice to split test_dataset and train_dataset. But how to get  test_dataset and train_dataset(or load testbatch, train batch) in 'larger' datasets easily.

Can you give me a few guidance? Thanks!

**Comment by rusty1s** [comment]
Hi, good question! Either predefine test/train splits and load them from respective `train` and `test` folders or load them based on a predefined permutation, *e.g.*:
```python
class MyDataset(Dataset):
    def __init__(self, train=True):
        ...
        perm = torch.randperm(num_examples) # for fixed splits, save/load this.
        if not train:
            self.perm = perm[:1000]
        else:
            self.perm = perm[1000:]

    def __len__(self):
         return self.perm.size(0)

    def get(self, idx):
         idx = perm[idx].item()
         return torch.load('data_{}.pt'.format(idx))
```

**Comment by feiwww** [comment]
Thanks for your effective reply! 
I load my test&train dataset successfully. In my demo dataset, len(train_dataset) =2 and len(test_dataset) =2
But I got another error about 'train_loader' in train function...

```
# load dataset
path = osp.join(osp.dirname(osp.realpath(__file__)), 'data', 'MyDataset')
train_dataset = MyDataset(path, True)
test_dataset = MyDataset(path, False)

# load batch data
test_loader = DataLoader(test_dataset)
train_loader = DataLoader(train_dataset)
```

```
Traceback (most recent call last):
  File "/home/wangfeiabn/WANGFEI/Dev/Python/bigCode/GNN.py", line 140, in <module>
    train_loss = train(epoch)
  File "/home/wangfeiabn/WANGFEI/Dev/Python/bigCode/GNN.py", line 116, in train
    for data in train_loader:
  File "/home/wangfeiabn/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/wangfeiabn/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataloader.py", line 24, in <lambda>
    collate_fn=lambda data_list: Batch.from_data_list(data_list),
  File "/home/wangfeiabn/anaconda3/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 44, in from_data_list
    batch[key], dim=data_list[0].cat_dim(key, batch[key][0]))
TypeError: expected Tensor as element 0 in argument 0, but got int
```

Thanks!

**Comment by rusty1s** [comment]
Data objects need to hold tensors, not ints. You should therefore add labels as `data.y = torch.tensor([class])`. I'll change that as soon as I have time.

**Comment by feiwww** [comment]
Label defined as torch.tensor is also understandable, but it should be clarified in documents. 
Many thanks! This is a awesome library.

**Comment by rusty1s** [comment]
`int` and `float` are now allowed as data attributes in current master.
