### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 1 and 2

### ISSUE THREAD

**Issue by SYSUHPK** [rusty1s/pytorch_geometric#1441]
## ❓ Questions & Help

Hello, I just add edge_attr data into the very simple model and it reports error
" File "/home/nvidia/anaconda3/envs/pyg102/lib/python3.7/site-packages/torch_geometric/utils/loop.py", line 135, in add_remaining_self_loops edge_weight = torch.cat([edge_weight[mask], loop_weight], dim=0)
RuntimeError: Tensors must have same number of dimensions: got 1 and 2"

The code is shown bellow:
![Snipaste_2020-07-19_19-40-25](https://user-images.githubusercontent.com/47689665/87873895-d7a15100-c9f7-11ea-9a85-a30dfcdc5a51.png)

text-------
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
import numpy as np
from torch_geometric.data import Data

class Net(torch.nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = GCNConv(1,1)
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        edge_attr = data.edge_attr
        x = self.conv1(x, edge_index, edge_attr)
        return x 

edge_index = torch.tensor([[0, 1, 1, 2, 2, 0],[1, 0, 2, 1, 0, 2]], dtype=torch.long)
x = torch.tensor([[71.1], [66.], [64.6]], dtype=torch.float)
edge_attr = torch.tensor([[3165.94],[8731.54],[3165.94],[5625.76],[8731.54],[5625.76]],dtype=torch.float)

data = Data(x=x, edge_index=edge_index,edge_attr=edge_attr)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = data.to(device)

model.train()
out = model(data)
print(out)

what 's wrong?

**Comment by rusty1s** [comment]
That should succeed if you pass `edge_attr.flatten()` into the model.

**Comment by SYSUHPK** [comment]
It works！ Thanks a lot！I just start to learn it and write it according to the pyg website. I don't understand why it works for edge_index and x, but reports error for edge_attr? What's more, does the GCN model  just calculate the **1** neighbor information  of vertex i ? Or the k(k>=2) neighbor?

**Comment by rusty1s** [comment]
Some operators only support an `edge_weight` tensor (which should be one-dimensional), corresponding to the weight of an edge. This is not really clear from the documentation though. I will try to improve it :)

One `GCNConv` corresponds to one round of neighborhood aggregation (k=1).

**Comment by SYSUHPK** [comment]
OK, thanks a lot!
