### ISSUE TITLE
Why do datasets not predefine a specific train/val/test split? 

### ISSUE THREAD

**Issue by FabianFalck** [rusty1s/pytorch_geometric#1442]
## ❓ Questions & Help

I am new to this repo (what an incredible effort! thank you for everyones' work!) and am trying to conceptually think through the logic and structure how *datasets* are coded up. I read the documentation on how to create my own dataset, read in detail the most important classes, such as `Dataset` and `InMemoryDataset` and also went through several example usages of datasets. 

My question is: **Why are the datasets not (or at least not always) specifying a train/val/test split?** I would find this split always useful if one directly wants to compare two models' performance: You want to use the exact same split to train, validate and test on (one could argue that the validation dataset is user- rather than pre-defined, and taken from the train-dataset, but even then, at least the train/test split should be predefined). - I would find this feature to be important for proper usage of the datasets as fair benchmarks to compare against. Are there any other efforts in this repo towards this that I am not aware of?

Thinking about how this could be roughly implemented, it would probably require a dedicated "benchmark" class for every "dataset" that contains `Dataset` objects (3 of them) as attributes.

**Comment by rusty1s** [comment]
Hi and thanks for this issue. Most of our datasets actually come with pre-defined train/val/test splits, either via the `train` argument, the `split` argument, or via masking of nodes in single graph datasets. For datasets that do not provide a train/test/val split, we don't do it either. These datasets are usually evaluated on random splits across multiple runs. This is fairly easy to implement via:
```python
dataset = dataset.shuffle()
train_dataset = dataset[:num_train]
val_dataset = dataset[num_train:num_train+num_val]
test_dataset = dataset[num_train+num_val:]
```

**Comment by FabianFalck** [comment]
Thank you very much for your quick answer!

I now in detail reread multiple datasets and now understand how the splits are specified. - Related to this, I'd have one further question: If I understand the logic of datasets correctly, datasets are downloaded and processed (`download()` and `process()`) very conveniently by calling the super constructor and there two private functions whenever a dataset class is instantiated. Let's assume a `split` or `train` attribute is present, then the resulting dataset object will only contain data from either the train, val or test "partition". However, the `download()` and `process()` function do donwload and process *all* "partitions", no matter how the attribute (split/train) was chosen. **Why did you make the design decision to have only a "partition"'s data part of a dataset object and not all partitions (then as part of some hypothetical `benchmark` class)?**  - Conceptually, the functions `download()` and `process()` would make more sense in such a benchmark class, and it would also enforce a stricter, more transparent benchmarking setup (e.g. require a train/test split in every benchmark, since otherwise, methods are not comparable). Yet, I can see the simplicity of your design, which is also much closer to what other libraries such as `torchvision` or `torchtext` do.

**Comment by rusty1s** [comment]
Yes, this is inline on what torchvision is doing with its dataset. In the end, this is no restriction. You can well implement `download` and `process` individually for each split, *e.g.*:
```python
def processed_file_names(self):
    return f'{split}.pt'

def process(self):
    # Only needs to implement process for current split.
```
To follow-up on your question, having multiple data instances is convenient for applying different transforms:
```python
train_dataset = MyDataset(train=True, transform=AugmentData())
test_dataset = MyDataset(train=False)
```
Implementing `download` and `process` as class methods makes a lot of sense though, will thing about it!

**Comment by FabianFalck** [comment]
Many thanks :-) Got it, makes sense!

I will further dig through the ideas in your repo and the other pytorch dataset repos and might get back if I have further comments/ideas/questions. I close this.

**Comment by FabianFalck** [comment]
One commend on making `download` and `process` with `@classmethod` decorators: I just tried whether this would work and it turns out that it doesn't: the `@decorator` attributes will no longer work (the exact error is `TypeError: 'property' object is not subscriptable`). This makes somewhat sense, since a classmethod is not supposed to get or set attributes of instances which were not created. So while this idea would have been conceptually pleasing, I'd suggest we keep the implementation as is :-)

**Comment by rusty1s** [comment]
That's true. There is some internal state used in the `download` and `process` methods, e.g., the root folder, which currently prevents it from being a class method.

**Comment by FabianFalck** [comment]
Closing this, noting that I think there is no space for improvement here. 

Just for completeness, I think using custom `@classproperty` (https://stackoverflow.com/questions/5189699/how-to-make-a-class-property) instead of `@property` decorators might solve my error above, but as you correctly say, other instance variables like `root` require an instance be created.
