### ISSUE TITLE
All equations in the documentation be written with edge weight matrix

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1449]
Hello,
It would be very nice if you could write in the documentation the equation related to all convolutions **with the edge weights** for better understanding. For example in GraphConv documentation you have written:

> \mathbf{x}^{\prime}_i = \mathbf{\Theta}_1 \mathbf{x}_i + \sum_{j \in \mathcal{N}(i)} \mathbf{\Theta}_2 \mathbf{x}_j.

However, if the user provides the edge_weight you will multiply the edge weight by the feature vector, which is not clear in the documentation. This provides a better understanding of how each Graph convolution is working.

**Comment by rusty1s** [comment]
That's a great idea. Thanks for pointing this out. Will see what I can do :)

**Comment by navid-mahmoudian** [comment]
> That's a great idea. Thanks for pointing this out. Will see what I can do :)

Thank you. You can also make the difference between `source_to_target` and `target_to_source` clearer by using transposed or non-transposed version of edge weight matrix. For example, if I am not mistaken, for `source_to_target` the formula of GraphConv is:
`\mathbf{x}^{\prime}_i = \mathbf{\Theta}_1 \mathbf{x}_i + \sum_{j \in \mathcal{N}(i)} \mathbf{\Theta}_2 \mathbf{W}^T \mathbf{x}_j`

, where `\mathbf{W}^T` is the transpose of edge weight matrix. Similarly, for `target_to_source` we use the non-transposed version
`\mathbf{x}^{\prime}_i = \mathbf{\Theta}_1 \mathbf{x}_i + \sum_{j \in \mathcal{N}(i)} \mathbf{\Theta}_2 \mathbf{W} \mathbf{x}_j`

Maybe I am making a mistake, and it is the reverse (you know it better).

**Comment by rusty1s** [comment]
This is now added to the documentation.
