### ISSUE TITLE
MessagePassing with edge feature updates

### ISSUE THREAD

**Issue by kolia** [rusty1s/pytorch_geometric#145]
## ❓ Questions & Help

I am trying to implement a message passing scheme where the features that get updated are the edge features, not the node features.

I was thinking I could try to use a `MessagePassing` layer and modify edge features in place in `update`, but would in-place modifications play nicely enough with pytorch auto grad?

Alternatively I could transform my graph somehow.  I could turn my original graph with `N` nodes and `M` edges into a bipartite graph where edges in the original become `M` nodes alongside the original `N`.  Or I could transform my graph by converting edges to nodes and converting nodes to cliques of edges (but that would blow up the number of edges for graphs with high-degree nodes.)

Any recommendations?

**Comment by rusty1s** [comment]
Hi,

as a rule of thumb, in-place modifications play nicely with PyTorch as long as you do not get an error when running `backward()`. Sometimes it works, and sometimes it does not.

Concerning your question. This depends on how you define "Message Passing with edge feature updates". For example, the [GraphNet paper](https://arxiv.org/abs/1806.01261) defines edge feature updates as integral part of a GraphNet Block (Equation 1). In PyG, this can be easily achieved via:
```python
row, col = edge_index
e = custom_op(x[row], x[col], e)
```
If you define "Message Passing with edge feature updates" as updating edge features based on their adjacent edges, it may be best to convert your graph into a [line graph](https://en.wikipedia.org/wiki/Line_graph) first and perform message passing on the resulting nodes. We have an open issue regarding line graph transformation [here](https://github.com/rusty1s/pytorch_geometric/issues/127). I will check its status.

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/147.

**Comment by kolia** [comment]
I'll be needing to update edge features based on their adjacent edges, so I'll track progress on the open line graph issue.

Thanks!
