### ISSUE TITLE
Does pyG have a roadmap about new version?

### ISSUE THREAD

**Issue by maqy1995** [rusty1s/pytorch_geometric#1457]
## ❓ Questions & Help

Such as planning for new features, etc.

**Comment by rusty1s** [comment]
Thanks for the issue. Currently not, but I am planning to do so for future releases :)

**Comment by rusty1s** [comment]
I create an issue to track further progress, which will get enhanced over time, see https://github.com/rusty1s/pytorch_geometric/issues/1465.

**Comment by maqy1995** [comment]
cool! I will close this issue.
