### ISSUE TITLE
Something may be wrong with pypi packaging in v1.6.0

### ISSUE THREAD

**Issue by tklijnsma** [rusty1s/pytorch_geometric#1459]
## 🐛 Bug

Installing `torch_geometric 1.6.0` from pypi gives me the following error when trying to call `torch_geometric.nn.EdgeConv.jittable`:

```
File "/home/klijnsma/miniconda3/envs/triton/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 358, in jittable
    with open(osp.join(root, 'message_passing.jinja'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/klijnsma/miniconda3/envs/triton/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.jinja'
```

Installing from source solves the problem:

```
git clone https://github.com/rusty1s/pytorch_geometric.git -b 1.6.0
pip install -e pytorch_geometric/
```

**Comment by rusty1s** [comment]
You are right. The `ninja` template does not get included when installing via `pip`. This is fixed now in master (see https://github.com/rusty1s/pytorch_geometric/commit/eca4f44052081760f365da5f9fc679743c0558a3), and I will release a new version as soon as possible. Thanks for letting me know!
