### ISSUE TITLE
ModelNet40 loading error

### ISSUE THREAD

**Issue by 1zb** [rusty1s/pytorch_geometric#146]
## 🐛 Bug

Error when loading (processing) ModelNet40

## To Reproduce
Code:
```
from torch_geometric.transforms import Compose, FaceToEdge, NormalizeScale
from torch_geometric.datasets import ModelNet

transformation = Compose([NormalizeScale()])
dataset = ModelNet(root='~/Dataset/ModelNet40', name='40', train=True, transform=transformation, pre_transform=FaceToEdge())
```
Error:
```
ValueError: invalid literal for int() with base 10: ''
```
The errors happens at line 27 of `torch_geometric/read/off.py`

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7
* PyTorch version: 1.0.1
* CUDA/cuDNN version: 10.0
* GCC version: 7.3
* Any other relevant information:

**Comment by rusty1s** [comment]
The error occurred in `/raw/guitar/test/guitar_0255.off`. I fixed it in master. Thank you!
