### ISSUE TITLE
Undesired output for avg_pool and avg_pool_x when batched

### ISSUE THREAD

**Issue by wentaoveggiebird** [rusty1s/pytorch_geometric#1462]
## ❓ Questions & Help

Hello, 
I'm having undesired output tensors from avg_pool and avg_pool_x. The batched input tensor has the shape [batch_size*num_nodes, num_node_features]. 

I think the output tensor is supposed to have shape of [batch_size, num_clusters, num_node_features].

 However, the actual output tensor has shape of [num_clusters, num_node_features]. I think the pooling function also pooled the data in a mini batch because they have the same cluster number.

**Comment by rusty1s** [comment]
`cluster` values should be different across examples inside your batch. You can enforce that by increasing cluster values using the cumulated sum:
```python
cluster_max = cluster.max().item() + 1
cluster = torch.arange(batch_size) * cluster_max + cluster
x = avg_pool_x(x, cluster, size=batch_size * cluster_max)
x = x.view(batch_size, cluster_max, -1)
```

**Comment by wentaoveggiebird** [comment]
Thanks. I think this solves the problem. I have one additional question about avg_pool and avg_pool_x:

Is the order of the output consistent with the sorted cluster numbers in ascent order? i.e., is the output in the form of  
```
[cluster_0_feature, cluster_1_feature, cluster_2_feature, ..., cluster_k_feature]? 
```
I'm asking this because I need to use a fully connected layer to process the output. In order to do this, the order of the clusters should be determined.

**Comment by rusty1s** [comment]
No, the order is deterministic. It‘s just that the order of aggregation for the same index is non-deterministic, which I wouldn‘t worry too much about.

**Comment by wentaoveggiebird** [comment]
> No, the order is deterministic. It‘s just that the order of aggregation for the same index is non-deterministic, which I wouldn‘t worry too much about.

Thanks! All my problems are solved!

**Comment by rusty1s** [comment]
If each `cluster` has a different cluster index, you can directly do `global_mean_pool(x, cluster)`.
