### ISSUE TITLE
Nodes with no Node Features for GCNs.

### ISSUE THREAD

**Issue by reshinthadithyan** [rusty1s/pytorch_geometric#1464]
## ❓ Questions & Help

Say I have a Graph, with Nodes which doesn't hold individual Node Features. How can I pass it through a GCNs?

**Comment by rusty1s** [comment]
In case no node features are given, you have multiple options:
1. Use synthetic node features like node degree, *e.g.*, via `transforms.OneHotDegree()`
2. You can use the identity matrix
3. You can use learnable embeddings for each node via `torch.nn.Embedding`.
The first option is a good choice in inductive training scenarios, while the latter two are good choices in transductive/semi-supervised learning tasks.

**Comment by reshinthadithyan** [comment]
Thank you, @rusty1s .
