### ISSUE TITLE
How can I obtain the samples index of Classification error?

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1467]
## ❓ Questions & Help

in graph pooling, we have some samples will be classified wrong,how can I get those index of wrong samples？
Thank you very mach!

**Comment by rusty1s** [comment]
You can get them directly inside your evaluation procedure, *e.g.*:
```python
def test():
    model.eval()
    wrong_indices = []
    for i, data in enumerate(test_dataset):
        out = model(data)
        if out.argmax(dim=1).item() != data.y.item():
            wrong_indices.append(i)
    return wrong_indices
```

**Comment by jiaruHithub** [comment]
> You can get them directly inside your evaluation procedure, _e.g._ via the following snippet (untested):
> 
> ```python
> def test():
>     model.eval()
>     wrong_indices = []
>     for i, data in enumerate(test_dataset):
>         out = model(data)
>         if out.argmax(dim=1).item() != data.y.item():
>             wrong_indices.append(i)
>     return wrong_indices
> ```

Thank you!I will try it!

**Comment by jiaruHithub** [comment]
> ```python
> data.y.item()
> ```

In your method,I found the error as fellow:
```
Traceback (most recent call last):
  File "test.py", line 237, in <module>
    logger=None,
  File "test.py", line 92, in cross_validation_with_val_set
    accs.append(eval_acc(model, test_loader))
  File "test.py", line 184, in eval_acc
    if out.argmax(dim=1).item() == data.y.item():
ValueError: only one element tensors can be converted to Python scalars
```
I think it because of ```out``` is not only one element in it.
Am I right?

**Comment by rusty1s** [comment]
Are you tackling graph classification? In this case, `out.argmax` should contain only a single element, am I right?

**Comment by jiaruHithub** [comment]
Yse,It's graph pooling.
But in ```out.argmax``` contain number of elements equal to number of graphs in test set.

**Comment by rusty1s** [comment]
Since you are passing a single `data` object to the `model`, I would expect the model to return only a single prediction.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.

**Comment by jiaruHithub** [comment]
Fine,but PyG has mini batch,it is very useful.
Now I use ```torch.ne``` to find the index of error samples.
Thank you for your help.
