### ISSUE TITLE
unique with sorted=True or False in k_hop_subgraph?

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_geometric#1469]
## 🐛 Bug

Hello, 
In your `k_hop_subgraph` function you are using Pytorch `unique` function:

```
subset, inv = torch.cat(subsets).unique(return_inverse=True)
inv = inv[:node_idx.numel()]
```

I figured out that in [Pytorch documentation for unique function](https://pytorch.org/docs/master/generated/torch.unique.html#torch-unique), in the example, when they do not provide the `sorted` argument, the function acts as `sorted=False` as the default value. However, the weird thing is that in my Pytorch installation the default of `sorted=True`. Moreover, I figured out that the output of 

`torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=False)`
is
`tensor([2, 3, 1])`

, which means that it doesn't even keep the order of occurrence. So I think in your `k_hop_subgraph` when you are using unique function care must be taken, especially because you are using `inv = inv[:node_idx.numel()]` which if you need to keep the order of occurrence then this way of using is not problematic. 

## Environment

* PyTorch version: 1.4.0+cpu
* CUDA/cuDNN version: No Cuda

**Comment by rusty1s** [comment]
Hi and thanks for this issue! IMO, this is not a problem since we are using `inv = inv[:node_idx.numel()]`, not `subset = subset[:node_idx.numel()]`. Note that `inv` maps each entry in `torch.cat(subsets)` to the respective index in the output vector.

**Comment by navid-mahmoudian** [comment]
Ahaan. Ok. You are right. Thanks.
