### ISSUE TITLE
I am running pytorch_geometric on MacOSX with no Cuda or Nvidia gpu installed. I have successfully installed torch-sparse and torch-scatter, but when I try to import torch_geometric, I get the following error:  OSError: dlopen(/Users/jonnycook/anaconda3/envs/MisinformationDetection/lib/python3.7/site-packages/torch_sparse/_convert.so, 6): Symbol not found: __ZN3c104impl24ExcludeTensorTypeIdGuardC1ENS_12TensorTypeIdE   Referenced from: /Users/jonnycook/anaconda3/envs/MisinformationDetection/lib/python3.7/site-packages/torch_sparse/_convert.so   Expected in: flat namespace  in /Users/jonnycook/anaconda3/envs/MisinformationDetection/lib/python3.7/site-packages/torch_sparse/_convert.so

### ISSUE THREAD

**Issue by jonathan-cook235** [rusty1s/pytorch_geometric#1480]
## To Reproduce

1.
1.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Can you give me some more description about the installation? Did you install via binaries or from source? Which macOS/PyTorch version are you using?

**Comment by jonathan-cook235** [comment]
I am using macOS Mojave version 10.14.6 and PyTorch version 1.6.0. I installed torch-geometric, torch-sparse and torch-scatter via pip install.

**Comment by rusty1s** [comment]
I see. PyTorch 1.6.0 is not supported yet (it got released yesterday), so you are better of jumping back to 1.5.0 for now. I'm currently working on PyTorch 1.6.0 support.

**Comment by jonathan-cook235** [comment]
Ahhh sorry. I am using PyTorch 1.5.1. I am using torch-geometric 1.6.0

**Comment by rusty1s** [comment]
Ok, then it might be that you are using an unsupported compiler. Have you tried installing the wheels for `torch-scatter`, ...? This might be the easiest way to fix it.

**Comment by jonathan-cook235** [comment]
I have not tried this. What is the process for doing so? And thanks for your help

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_geometric#pytorch-150151

**Comment by jonathan-cook235** [comment]
Worked perfectly. Thanks!
