### ISSUE TITLE
Small question about GAE

### ISSUE THREAD

**Issue by Elizabeth1997** [rusty1s/pytorch_geometric#1482]
## ❓ Questions & Help

Hi, hope you are doing great! I have a small question about function `def recon_loss(self, z, pos_edge_index):` in GAE class. Because the positive training and test edges are split from the original edges of the graph, so there may exist overlap between negative edges sampled for training and positive test edges? Please correct me if my understanding is incorrect. Thank you very much for replying in advance!

**Comment by rusty1s** [comment]
That's correct. It's unavoidable since we do not know about true positive test edges in advance.

**Comment by Elizabeth1997** [comment]
Got it. Many thanks!
