### ISSUE TITLE
Reshaping batches to Conv2D style

### ISSUE THREAD

**Issue by legohyl** [rusty1s/pytorch_geometric#1483]
## ❓ Questions & Help

Hi, I was wondering if my model has 2 parts, a MPNN module, and a custom algorithm module, whether it's possible to handle batching when the MPNN modules stacks the batches to form a large adjacency matrix, but my algorithm processes batches by `[batch, n_nodes, n_nodes]` instead of stacking everything together. Perhaps a concrete example is something like this: we have 2 graphs of each of n_nodes, processing them in a batch size of 2 gives my node feature matrix `[2* n_nodes, feat_dim]`. After MPNN is done, I want to reshape it to `[batch, n_nodes, feat_dim]` instead. Will `.view(batch, n_nodes, feat_dim)` do it sufficiently or do I have to keep track of the batch indexes as well?

**Comment by rusty1s** [comment]
You can use view in case your number of nodes is the same for each graph. In case it is not, please have a lool at the to_dense_batch method.

**Comment by legohyl** [comment]
Thanks a lot!
