### ISSUE TITLE
GAE module missing

### ISSUE THREAD

**Issue by freesinger** [rusty1s/pytorch_geometric#149]
## ❓ Questions & Help

When running the example `autoencoder.py` , I come across this problem: `ImportError: cannot import name 'GAE'`, wondering if this module changed or has been removed?
Any help will be appreciated!

**Comment by rusty1s** [comment]
You need to re-install PyG when pulling from master.

**Comment by freesinger** [comment]
> You need to re-install PyG when pulling from master.

I re-installed it but it still doesn't work, it seems command `pip install pytorch-geometric` couldn't get the latest version, I must configure it manually.

**Comment by rusty1s** [comment]
Yes, the GAE model is not officially released yet. It can be only used when installing from source via `python serup.py install`.

**Comment by freesinger** [comment]
Problem solved! Thanks a lot!
