### ISSUE TITLE
Unsupervised GraphSAGE

### ISSUE THREAD

**Issue by yuanx749** [rusty1s/pytorch_geometric#1491]
## ❓ Questions & Help

Hi, I would like to implement unsupervised GraphSAGE in the GraphSAGE paper. Is there a function in PyG for sampling the negative node indices? ```torch_geometric.utils.negative_sampling``` is used to sample edges but not nodes.

**Comment by rusty1s** [comment]
Hi and thanks for your interest! We do not have an example for this yet, but you can follow [this issue](https://github.com/rusty1s/pytorch_geometric/issues/1420) to track its progress.

**Comment by yuanx749** [comment]
@rusty1s I have implemented unsupervised GraphSAGE, using ```torch_cluster.randow_walk``` to sample neighbors and ```NeighborSampler```to generate mini-batch, and another ```NeighborSampler``` to randomly shuffle the nodes for negative sampling. 

Could you have a look at the code below? It would be great that it could be added to the examples.
https://gist.github.com/yuanx749/de835f92f4e44a9cf825a5638968e7e5

**Comment by arunavsk** [comment]
Hey @yuanx749 - I have a simpler version of this https://gist.github.com/arunavsk/7a4091ccddcbfa6eb31c35c5ce7fe462

**Comment by rusty1s** [comment]
Both versions look fine to me. We can definitely integrate it into the PyG examples. Feel free to send a PR.
