### ISSUE TITLE
about the upper triangular portion

### ISSUE THREAD

**Issue by 649459021** [rusty1s/pytorch_geometric#1492]
## ❓ Questions & Help

torch_geometric/utils/train_test_split_edges.py 
```python
# Return upper triangular portion.
    mask = row < col
    row, col = row[mask], col[mask]
```

Why return upper triangular portion ? Treat as undirected graph by default?
Why not judge whether the graph has a direction? I noticed that line 48 is directly processed as an undirected graph

**Comment by rusty1s** [comment]
Hi! You are right, the current `train_test_split_edges` can only handle undirected edges. This stems from the fact that it is used inside the `GAE` model, which can only handle undirected edges. I think it would be great to enhance this method for directed graphs.

**Comment by 649459021** [comment]
Thanks！
