### ISSUE TITLE
torch sparse version bug

### ISSUE THREAD

**Issue by shangguan91** [rusty1s/pytorch_geometric#1494]
```
! pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
! pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
! pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
! pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
! pip install torch-geometric
```
normally, it works.
I can not import any from torch_geometric.
Error

**OSError: /usr/local/lib/python3.6/dist-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs**

**Comment by asalimih** [comment]
the same problem on Google Colab.

first I wanted to install torch-geometric using this code (based on versions of pytorch and cuda):
```
%pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
%pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
%pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
%pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
%pip install torch-geometric
```
but torch-sparse and torch-cluster couldn't be installed because of following Error:
```
ERROR: No matching distribution found for torch-cluster==latest+cu101
```

so I Uninstalled all and reinstalled using:
```
%pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-geometric
```
which installed properly. but this time when I import torch-geometric I get the following error:
```
OSError: /usr/local/lib/python3.7/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```

**Comment by rusty1s** [comment]
Seems like a versioning conflict. Are you sure that you are using torch<1.6.0 when using the 1.5.0 wheels?

**Comment by shangguan91** [comment]
in addition, when i run e.g. dgcnn_classification.py, it shows i should use pytorch 1.4.0, then i follow the instruction delete torch and install. but 1.4.0 complie only with cuda 9.2.

**Comment by rusty1s** [comment]
Why does it say you should install torch==1.4.0? And what‘s the problem with this?

**Comment by shangguan91** [comment]
i think i found the problem, with following install code:
%pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
%pip install torch-geometric

my torch version shows 1.6.0+cu101.
after running pip install torch-geometric, it will install the torch.1.6.0 automatically instead of 1.5.0. Is there anyway to fix this?

**Comment by shangguan91** [comment]
> Seems like a versioning conflict. Are you sure that you are using torch<1.6.0 when using the 1.5.0 wheels?

i delete torch.1.6.0, install torch. 1.5.0,  OSError: is gone. but new error occurs.
![image](https://user-images.githubusercontent.com/64595972/89159726-30ccc100-d570-11ea-988a-82029b5c50e6.png)

**Comment by shangguan91** [comment]
> Why does it say you should install torch==1.4.0? And what‘s the problem with this?
it said that support 1.4.0 not 1.6.0. 
one week ago, everything works fine. i think the problem is between colab and your new update.

**Comment by shangguan91** [comment]
@asalimih 
do you know other platform with GPU other than colab? i really need run some test within this week

**Comment by rusty1s** [comment]
Your installation if torch==1.5.0 is fine, the problem is within torchvision. You either need the correct torchvision version for PyTorch 1.5.0, or uninstall it completely for PyG (it‘s not really needed).

**Comment by shangguan91** [comment]
> Your installation of torch==1.5.0 is fine, the problem is within torchvision. You either need the correct torchvision version for PyTorch 1.5.0, or uninstall it completely for PyG (it‘s not really needed).
@asalimih 
Fixed by following
pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
