### ISSUE TITLE
failure to create softlink when create container from image

### ISSUE THREAD

**Issue by westzhicanchen** [rusty1s/pytorch_geometric#150]
## Environment
I have successfully pulled the docker image shengwenliang/pytorch_graph

## Additional context
Hi there, as mentioned above, I have successfully pulled the image mentioned above. However, when I tried to create a container from the image with a soft link as below, I got some problem entering my folder:

zchen12@sbbdmaplp003:~$ sudo docker run -it --name='westGCNPyTorch' -v /home/zchen12:/westhome/ shengwenliang/pytorch_graph
user@c01e76f8ab82:/app$ cd /
user@c01e76f8ab82:/$ ls
app  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  westhome
user@c01e76f8ab82:/$ cd westhome/
bash: cd: westhome/: Permission denied

It seems that I don't have permission to do that:

user@872746764b85:~$ ls -l
total 12
drwxr-xr-x  1 user       user       4096 Feb 15 06:01 miniconda
drwxr-xr-x 13 user       user       4096 Feb 15 06:03 pytorch_scatter
drwx------ 10 1828858574 1828858574 4096 Mar 25 16:33 westhome

Can anyone help me with that? Also, I'm pretty new to github, so feel free to point out if my method of questioning should be improved. Thanks!

**Comment by rusty1s** [comment]
Maybe @shengwenLeong can help?

**Comment by westzhicanchen** [comment]
Also, I wonder if this package PyTorch Geometric (PyG) is already installed in the image or not? Cause i tried to git clone it to the root directory but failed with:

user@872746764b85:/$ ls
app  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
user@872746764b85:/$ git clone https://github.com/rusty1s/pytorch_geometric.git
fatal: could not create work tree dir 'pytorch_geometric': Permission denied

Any further instruction with the docker usage? Much appreciated.

**Comment by shengwenLeong** [comment]
Hi, when you download this image for docker hub, you can use this command to run this container. 
`docker run --rm -it --init --runtime=nvidia --ipc=host --network=host --volume=$PWD:/app -e NVIDIA_VISIBLE_DEVICES=0 shengwenliang/pytorch_graph /bin/bash`
the PyTorch Geometric (PyG) is not installed in the images. you can download from the internet.

**Comment by westzhicanchen** [comment]
Hi shengwenleong!

The good news is that now I could successfully do the mounting within the container, but not exactly with the command you provided. I'd like to share some of my experience here just in case someone else may have the same issue:

At first I tried Shengwenleong's solution, but got the following error:

`zchen12@sbbdmaplp003:~$ sudo docker run --rm -it -v $PWD:/app shengwenliang/pytorch_graph /bin/bash  
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/app\") set in config.json failed: permission denied": unknown.`

This time the error is much more resourceful than previous ones, so I googled it and found the following [solution:](https://github.com/jupyter/docker-stacks/issues/323)

Then it occured to me to check my access to the local home directory(on the server), and ahh, I really don't have full authority(I only put relevant part here):

`
zchen12@sbbdmaplp003:~$ ls /home -l
drwx------ 11 zchen12    zchen12    4096 Mar 26 10:42 zchen12
zchen12@sbbdmaplp003:~$ ls /home/zchen12 -l
drwxrwxr-x 2 zchen12 zchen12 4096 Mar 26 10:30 PyTorchGCN
`

It seems that the error is that: when I tried to create a container with a mount from my /home/zchen12 directory to somewhere inside the container, the container want to do some changes to my local home directory, which I don't have access to do, but if instead I mount it from /home/zchen12/PyTorchGCN, now I do have full authority and it works!

`
user@25c62d23f2e6:/app$ cd ..
user@25c62d23f2e6:/$ ls
app  bin  boot  dev  etc  home  lib  lib64  media  mnt  myhome  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
user@25c62d23f2e6:/$ cd myhome/
user@25c62d23f2e6:/myhome$ ls
test.py
`
 
I guess images could vary from case to case, previously I always directly mount /home/zchen12 into the container and it always works, but this time it doesn't, so maybe there is some difference between my previous image and this one.

Anyway, thanks everyone for the quick response and help!

**Comment by westzhicanchen** [comment]
A little add-on:

I also found I don't have permission to write/create inside the container, so I git cloned PyTorch Geometric (PyG) inside my local directory which is mounted to somewhere inside the container, instead of directly git clone it inside the container. And now it works.

**Comment by westzhicanchen** [comment]
To conclude, I've encountered several issues running this container, all of them related to permission:

- local directory permission issue: when mounting local folder inside the container, we need to be careful whether or not we have write/create permission to the **local folder**

- container directory permission issue: the only place where I had write/create permission inside the container is /tmp(no wonder its color is different...). We don't have permission to write anywhere else, especially not in the mounted folder(even if you put it under /tmp). 

However, I still wonder if I want to have write/create permission to the mounted folder inside the container, who should I reach out to? The manager of local directory or author of this image, i.e. shengwenliang? Can anyone help me with that?

**Comment by rusty1s** [comment]
I'm actually no docker user, so it would be great if @shengwenLeong could answer all docker related questions and keep on improving the image.
I see no reason why we do not allow write permissions. In addition, it would be great if the readme or documentation could get enhanced by more detailed docker instructions.

**Comment by westzhicanchen** [comment]
Hi @shengwenLeong:

Could you please provide more detailed instruction on how to use this docker image? I just met another problem:

`
user@d8044e9b2dbf:/tmp/PyTorchGCN/pytorch_geometric/examples$ python cora.py
Traceback (most recent call last):
  File "cora.py", line 5, in <module>
    from torch_geometric.datasets import Planetoid
ModuleNotFoundError: No module named 'torch_geometric'
user@d8044e9b2dbf:/tmp/PyTorchGCN/pytorch_geometric/examples$
`

It seems that I still have to pip install torch_geometric with this image, I'm not sure if this is a common practice(I'm also new to docker usage)?

Much appreciated!

**Comment by westzhicanchen** [comment]
> Hi, when you download this image for docker hub, you can use this command to run this container.
> 
> **`docker run --rm -it --init --runtime=nvidia --ipc=host --network=host --volume=$PWD:/app -e NVIDIA_VISIBLE_DEVICES=0 shengwenliang/pytorch_graph /bin/bash`**
> 
> the PyTorch Geometric (PyG) is not installed in the images. you can download from the internet to your local folder or in the contianer. When download in local folder, the project file will appear at /app folder in the container.
> 
> if you have any question, please free contact to me by email:
> [liangshengwen@ict.ac.cn](mailto:liangshengwen@ict.ac.cn)
> Thanks.

Hi @shengwenLeong , I just take a second look at your reply, I'm not quite sure how this 'appear in /app' works. So I git cloned PyG into local directory and then mounted it inside /tmp folder inside the container:

`user@d8044e9b2dbf:/tmp/PyTorchGCN$ ls
pytorch_geometric  test.py
`

not quite sure if this is what you mean

But I found nothing inside /app folder:

`user@d8044e9b2dbf:/tmp/PyTorchGCN/pytorch_geometric/examples$ cd /app
user@d8044e9b2dbf:/app$ ls
user@d8044e9b2dbf:/app$ ll
total 8
drwxr-xr-x 1 user user 4096 Dec 10 05:08 ./
drwxr-xr-x 1 root root 4096 Mar 26 16:48 ../
`

**Comment by shengwenLeong** [comment]
OK，I will check it and upload a new image that contain the project pytorch_geometric.

**Comment by shengwenLeong** [comment]
> OK，I will check it and upload a new image that contains the project pytorch_geometric.

Dear, @westzhicanchen , recently, i am busy for something. So I could help you solve the problem on March 31. I am so sorry. Once the work is done, I will inform you. Thanks for your support.

**Comment by westzhicanchen** [comment]
> > OK，I will check it and upload a new image that contains the project pytorch_geometric.
> 
> Dear, @westzhicanchen , recently, i am busy for something. So I could help you solve the problem on March 31. I am so sorry. Once the work is done, I will inform you. Thanks for your support.

Hi @shengwenLeong , no worries, please take your time. Actually I also tried to to build this from a standard NVIDIA pytorch image, basically I just followed the instructions provided here, and it worked out pretty well. Therefore, at least I got an environment that's working now, so no hurries.

Thanks for help all the same.

**Comment by shengwenLeong** [comment]
@westzhicanchen  I upload the dockerfile to this project. so you can download it and build container in the local machine. 
Meanwhile, this dockerfile also contains the pytorch_geometirc project. Thanks.

**Comment by rusty1s** [comment]
Feel free to reopen in case of any further questions.

**Comment by westzhicanchen** [comment]
> @westzhicanchen I upload the dockerfile to this project. so you can download it and build container in the local machine.
> Meanwhile, this dockerfile also contains the pytorch_geometirc project. Thanks.

Thanks for that! Will try later.
