### ISSUE TITLE
Which methods can be used to extract a feature vector from a point cloud?

### ISSUE THREAD

**Issue by cisprague** [rusty1s/pytorch_geometric#1504]
I have a set of `n` `m`-dimensional points contained in a pointcloud `P` , where `P.shape == (n, m)` and `n` can vary.
I want to map `P` to a feature vector `v`, like the global feature vector in the PointNet paper, where `v.shape == (1024,)`.
Is there a straightforward way to recreate the original PointNet with this library?
And, are there any other comparable models that are easily recreatable?

Cheers!

**Comment by rusty1s** [comment]
Recreating the original PointNet architecture is straightforward in PyG since we also provide common readout functions, *e.g.* `global_max_pool`:
```python
def forward(self, pos, batch):
    h = self.mlp_1(pos)
    h = global_max_pool(h, batch)
    return self.mlp_2(h)
```
For a more sophisticated architecture, you can check our [PointNet++ example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_classification.py).

**Comment by cisprague** [comment]
@rusty1s, awesome, thank you!
Also, could you recommend another model within your library that has better performance in classification?

**Comment by rusty1s** [comment]
You might be also interested in the `XConv` operator, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/points/point_cnn.py).

**Comment by cisprague** [comment]
Perfect! Thanks again.
Lastly, can you comment on the speed of those PointNet++ and PointCNN implementations?
My application is a bit time-sensitive.

**Comment by tchaton** [comment]
@cisprague Have a look at https://github.com/nicolas-chaulet/torch-points3d

**Comment by limllzu** [comment]
> 我有一组 -dimensional 点包含在点云 中，其中 和 可以变化。我想映射到一个特征向量 ，就像 PointNet 论文中的全局特征向量一样，其中 。有没有一种简单的方法可以用这个库重新创建原始的 PointNet？还有，还有其他易于复制的类似模型吗？`n``m``P``P.shape == (n, m)``n``P``v``v.shape == (1024,)`
> 
> 干杯！

你好，麻烦问一下，使用pyg构建一个提取点云文件中特征向量的pointnet++网络，我应该如何使用现成的pyg进行构建，非常感谢
