### ISSUE TITLE
What is the format of edge index?

### ISSUE THREAD

**Issue by richardrl** [rusty1s/pytorch_geometric#1506]
Given a graph of (batch_size, num_nodes, 3),
How do I create edge_indices such that the graph is fully connected?

It would help if the documentation has explicit descriptions of the expected sizes of things like edge_index for GATConv

**Comment by richardrl** [comment]
https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html

**Comment by rusty1s** [comment]
In case of a fully connected graph, your edge index would look like
```
edge_index = torch.ones(num_nodes, num_nodes).nonzero().t()
```
which holds all possible index pairs in a tensor of shape [2, num_edges]. However, I would advise against using a sparse formulation for a fully-connected graph. In this case, it is way faster to write a dense GAT conv formulation from scratch, using PyTorch dense matrices. In its current form, PyG is designed to operate on sparse adjacencies.
