### ISSUE TITLE
Different results of radius_graph() when input in different data type

### ISSUE THREAD

**Issue by Patrickwhj** [rusty1s/pytorch_geometric#1509]
## 🐛 Bug

Different results of radius_graph() when input in different data type (i.e., long and double)
## To Reproduce

```python
data = Data()
batch_size = 2
num_nodes = 4 
x_dis = torch.arange(batch_size*num_nodes).view(batch_size*num_nodes,-1)
batch = torch.arange(batch_size).view(-1,1).repeat(1,num_nodes).view(-1)
from torch_geometric.nn import radius_graph
rg = radius_graph(x_dis, 1, batch)
print(rg)
```

## Expected behavior

`tensor([[1, 0, 2, 1, 3, 2, 5, 4, 6, 5, 7, 6],
        [0, 1, 1, 2, 2, 3, 4, 5, 5, 6, 6, 7]])`
but I got 
`tensor([], size=(2, 0), dtype=torch.int64)`

If I change the data type of  `x_dis` to double, the output is as expected
## Environment

* OS: Ubuntu 16.04.6
* Python version: 3.6.1
* PyTorch version: 1.5.1
* CUDA/cuDNN version: 10.1
* GCC version: 7.3.0

**Comment by rusty1s** [comment]
That looks like an issue with `nanoflann` which we use for computing the ball query. `nanoflann` finds the output indices via `dist < radius` and casts the radius to an integer. I'm not sure if it is fixable though. I feel like it is a lot safer to just do not use integer values when computing distances.
