### ISSUE TITLE
Temporal Graph Network (TGN), a general encoder architecture to learn on dynamic graphs represented as a stream of events

### ISSUE THREAD

**Issue by benelot** [rusty1s/pytorch_geometric#1512]
## 🚀 Feature

Many interesting real-world graphs are dynamic and evolving in time, with prominent examples including social networks, financial transactions, and recommender systems. In many cases, it is the dynamic behaviour of such systems that conveys important insights, otherwise lost if one considers only a static graph.

Temporal Graph Network (TGN) is a general encoder architecture that can be applied to various problems of learning on dynamic graphs represented as a stream of events. In a nutshell, a TGN encoder acts by creating compressed representations of the nodes based on their interactions and updates them upon each event.

https://towardsdatascience.com/temporal-graph-networks-ab8f327f2efe
https://arxiv.org/abs/2006.10637

https://github.com/twitter-research/tgn

## Motivation

We are working on graph data that changes over time and we would be highly interested to predict changes of the graph structure into the future. As the pytorch geometric library is so convenient to use, we would love to have the TGN as part of the library.

**Comment by rusty1s** [comment]
Thanks for this issue. TGN is on my TODO list, and I have plans with @emalgorithm to integrate it ASAP in PyG :) We can use this issue to track further progress.

**Comment by benelot** [comment]
Best answer I could hope for (except for "it is already there, you just did not see it"). Thanks!

**Comment by rusty1s** [comment]
`TGN` is now available in master :)

**Comment by benelot** [comment]
@rusty1s Again the best moment in time this answer could come up. Thanks for all your efforts!
