### ISSUE TITLE
Add `follow_batch` argument to nn.DataParallel

### ISSUE THREAD

**Issue by twcostain** [rusty1s/pytorch_geometric#1527]
## 🚀 Feature

In `torch_geometric.nn.data_parallel` there is no way to pass follow batch to the `Batch.from_data_list` method.
Add an argument to `data_parallel` such that the `follow_batch` keyword can be used.

## Motivation

For certain architectures, this could be very helpful (i.e. pre-computing multiple scales).
As now, in parallel operation, there is no way to access the batch mapping for tensors that have a different `num_nodes` to the main (x/pos) tensors.

**Comment by rusty1s** [comment]
That's correct! It's indeed a missing feature :) I will try to add it in.

**Comment by rusty1s** [comment]
Implemented in master via `DataParallel(model, follow_batch=[...])`.

**Comment by twcostain** [comment]
Thanks very much!
