### ISSUE TITLE
Unable to download MNIST Superpixel: 404 error, page not found

### ISSUE THREAD

**Issue by jamesbayne** [rusty1s/pytorch_geometric#1528]
Hi there,

I'm trying to download the MNIST Superpixel dataset but the url where it was hosted (https://ls7-www.cs.tu-dortmund.de/cvpr_geometric_dl/mnist_superpixels.tar.gz) doesn't seem to contain it anymore.

Do you know where I can find it? I'm a bit of an intermediate-level programmer so was hoping to avoid having to regenerate the data from MNIST.

Thanks!

**Comment by rusty1s** [comment]
I will look into it.

**Comment by rusty1s** [comment]
This is now fixed in master, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/mnist_superpixels.py#L33-L34). You can manually update the link if you do not want to update to master.

**Comment by jamesbayne** [comment]
Amazing, thank you for such a fast fix!
