### ISSUE TITLE
index out of range in self

### ISSUE THREAD

**Issue by srikanthmalla** [rusty1s/pytorch_geometric#1529]
Hi @rusty1s ,
I am getting following error for random batch:
....nn/conv/message_passing.py", line 127, in __lift__     return src.index_select(self.node_dim, index)

error screen shot:
![question](https://user-images.githubusercontent.com/8193784/90203031-5f2e7580-dd94-11ea-9c0e-0717b1f6cd52.png)

Please let me know if there is an easy way to debug this.

Best Regards,
Srikanth

**Comment by rusty1s** [comment]
Can you confirm that `edge_index.max() < x.size(0)`?

**Comment by srikanthmalla** [comment]
Hi @rusty1s ,
That is exactly what happening, but because of some other issue (edge_index doesn't update in conv message passing) I mentioned it in the issue: https://github.com/rusty1s/pytorch_geometric/issues/1530#issue-678927874

Please let me know, if that is an actual issue (with varying size of input, it doesn't work?)

Thank you,
Srikanth

**Comment by rusty1s** [comment]
I'm not really sure what you mean by "edge_index doesn't update".

**Comment by srikanthmalla** [comment]
I mean the shape of edge_index is always same as first batch as shown in https://github.com/rusty1s/pytorch_geometric/issues/1530#issue-678927874

If the next batch has smaller size of data, then index goes out of range. Does this make sense?

**Comment by rusty1s** [comment]
I see. Please diable the `cached` argument of the `GCNConv`.

**Comment by srikanthmalla** [comment]
Hi @rusty1s ,
That solved! Thank you so much. I am new to this library. But thank you so much for you effort.
