### ISSUE TITLE
Edge Attributes when using ClusterGCN

### ISSUE THREAD

**Issue by j-petit** [rusty1s/pytorch_geometric#1533]
## 🐛 Bug

Edge attributes are not treated correctly when splitting up a graph into several clusters as done when using ClusterGCN. The reason for this is that edges are permuted two times (once when the data is loader into `ClusterData` object and then when `__getitem__` is executed) which leads to wrong edge attributes in the subgraph.

[I modified the test](https://github.com/rusty1s/pytorch_geometric/pull/1532) in `test_cluster.py` to contain also edge attributes, it now fails.

## To Reproduce

1. Add edge attributes to the test of `test_cluster.py`.
2. Run test with assert statements about the edge attributes.
3. Test fails.

## Expected behavior

I expect that the correct `edge_attr` are selected for a cluster. 

## Environment

* OS: CentOS Linux release 7.8.2003
* Python version: 3.7.7
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.2
* GCC version: 8.3

**Comment by rusty1s** [comment]
Fixed in https://github.com/rusty1s/pytorch_geometric/pull/1532.
