### ISSUE TITLE
GCN normalization

### ISSUE THREAD

**Issue by Nifury** [rusty1s/pytorch_geometric#1536]
Hello, I found an inconsistency in GCN adjacency matrix normalization. 

Here `deg` is a column-wise sum
https://github.com/rusty1s/pytorch_geometric/blob/d48ca38895d4334bc2bf164ea35352d94f7989d4/torch_geometric/nn/conv/gcn_conv.py#L41

but here `deg` is a row-wise sum.
https://github.com/rusty1s/pytorch_geometric/blob/d48ca38895d4334bc2bf164ea35352d94f7989d4/torch_geometric/nn/conv/gcn_conv.py#L62

**Comment by rusty1s** [comment]
IMO, I think this is correct since `adj_t` is the transposed adjacency matrix of `edge_index`.

**Comment by Nifury** [comment]
Ah I see, thank you so much!
