### ISSUE TITLE
[BUG] knn_graph number of edges not equal to N*k (cosine=True)

### ISSUE THREAD

**Issue by lizichao7** [rusty1s/pytorch_geometric#1548]
## ❓ Questions & Help

Suppose the node feature matrix X is N by F, then the number of edges in the edge_index returned by knn_graph(X, k) should be k*N, right? Because there are N nodes, and for each node we add k edges, and the edges are directed. Am I missing something about the definition of knn graph? 

To be more specific, I am using cosine=True, and N = 7400, F = 1024, k = 10. I should be getting 74000 edges, but I got 81389 edges. I would really appreciate any help that could explain the difference.

**Comment by rusty1s** [comment]
Yeah, I can reproduce this. This is indeed an issue with `cosine=True`. The reason for it is that the current implementation computes `k+1` nearest neighbors and removes self-loops in a post-processing step. However, for `cosine=True`, self-loops are not always added.

**Comment by lizichao7** [comment]
> Yeah, I can reproduce this. This is indeed an issue with `cosine=True`. The reason for it is that the current implementation computes `k+1` nearest neighbors and removes self-loops in a post-processing step. However, for `cosine=True`, self-loops are not always added.

Just to be more clear, you are saying for `cosine=True`, self-loops should be added (because the cosine similarity of two identical vectors should be 1), but in your implementation they are not always added right?

**Comment by lizichao7** [comment]
Actually, I took a closer look at the `edge_index` returned by the `knn_graph`, and the result does not make sense. To be more specific, for every node as the source, the `knn_graph` function always selects the first k nodes as the k nearest nodes, regardless of how large or small the cosine distance between them are. I think there is a serious bug in the implementation of `knn_graph` when `cosine=True`, and I sincerely hope it could be fixed soon. Thanks for your effort in advance.

**Comment by rusty1s** [comment]
Yes, you're absolutely right. I identified the bug and fixed it in `pytorch-cluster/master`. Thank you, that was very helpful :)

**Comment by ranahanocka** [comment]
I am experiencing a similar issue (although __I am not using__ cosine=True).
For some examples the result of knn_graph is not N*k (rather, it is N*k + 1). Could this be related? 
FWIW, following this thread, I installed the latest version from `pytorch-cluster/master`, but that did not seem to fix the problem.

**Comment by rusty1s** [comment]
Can you show me a minimal example to reproduce? This should IMO only occur if you have a lot of duplicated points in your point cloud.

**Comment by dd292** [comment]
Hey, I am getting a similar issue (Not using the cosine=True). 
The exact problem is I have a point cloud of 2000 points. When using knn_graph with k=3 ideally I should consistently get [2,6000] but its not the case. My second dimension is between 6000-7000 but its varying a lot.
Do you know why that might be?
I do have repeated points in my dateset.

**Comment by rusty1s** [comment]
Yeah, that's caused by the repeating points in your dataset, since currently we simply filter out self-loops after computing the `knn` graph for `k+1`.
