### ISSUE TITLE
Error running VGAE

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#155]
## 🐛 Bug

There seems to be a problem running the encoder.
```
data=graph.graph

gvae= VGAE(Encoder(data.num_features,5))

model=gvae

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)


def train():
    model.train()
    optimizer.zero_grad()
    print(x)
    print(edge_index)
    z = model.encode(x, edge_index)
    print(z)
    loss = model.recon_loss(model.decoder(z), data.train_pos_edge_index,
                            data.train_neg_adj_mask)
    loss.backward()
    optimizer.step()


def test(pos_edge_index, neg_edge_index):
    model.eval()
    with torch.no_grad():
        z = model.encode(x, edge_index)
    return model.test(model.decoder(z), pos_edge_index, neg_edge_index)


for epoch in range(1, 201):
    train()
    auc, ap = test(data.val_pos_edge_index, data.val_neg_edge_index)
    print('Epoch: {:03d}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, auc, ap))

auc, ap = test(data.test_pos_edge_index, data.test_neg_edge_index)
print('Test AUC: {:.4f}, Test AP: {:.4f}'.format(auc, ap))
```
Got this error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-44-ae936215182e> in <module>()
     25 
     26 for epoch in range(1, 201):
---> 27     train()
     28     auc, ap = test(data.val_pos_edge_index, data.val_neg_edge_index)
     29     print('Epoch: {:03d}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, auc, ap))

<ipython-input-44-ae936215182e> in train()
      9     print(x)
     10     print(edge_index)
---> 11     z = model.encode(x, edge_index)
     12     print(z)
     13     loss = model.recon_loss(model.decoder(z), data.train_pos_edge_index,

/anaconda2/envs/py36/lib/python3.6/site-packages/torch_geometric-1.0.3-py3.6.egg/torch_geometric/nn/models/autoencoder.py in encode(self, *args, **kwargs)
     31     def encode(self, *args, **kwargs):
     32         r"""Runs the encoder and computes latent variables for each node."""
---> 33         return self.encoder(*args, **kwargs)
     34 
     35     def decode(self, z):

/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-26-cb395993d852> in forward(self, x, edge_index)
     28 
     29     def forward(self, x, edge_index):
---> 30         x = F.relu(self.conv1(x, edge_index))
     31         return self.conv2(x, edge_index)
     32 

/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/anaconda2/envs/py36/lib/python3.6/site-packages/torch_geometric-1.0.3-py3.6.egg/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
     94             edge_index, norm = GCNConv.norm(edge_index,
     95                                             x.size(0), edge_weight,
---> 96                                             self.improved, x.dtype)
     97             self.cached_result = edge_index, norm
     98 

/anaconda2/envs/py36/lib/python3.6/site-packages/torch_geometric-1.0.3-py3.6.egg/torch_geometric/nn/conv/gcn_conv.py in norm(edge_index, num_nodes, edge_weight, improved, dtype)
     81 
     82         row, col = edge_index
---> 83         deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
     84         deg_inv_sqrt = deg.pow(-0.5)
     85         deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

/anaconda2/envs/py36/lib/python3.6/site-packages/torch_scatter/add.py in scatter_add(src, index, dim, out, dim_size, fill_value)
     70                [2, 4, 4, 0, 0, 0]])
     71     """
---> 72     src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
     73     return out.scatter_add_(dim, index, src)

/anaconda2/envs/py36/lib/python3.6/site-packages/torch_scatter/utils/gen.py in gen(src, index, dim, out, dim_size, fill_value)
      9         index_size = list(repeat(1, src.dim()))
     10         index_size[dim] = src.size(dim)
---> 11         index = index.view(index_size).expand_as(src)
     12 
     13     # Generate output tensor if not given.

RuntimeError: shape '[340]' is invalid for input of size 307

**Comment by rusty1s** [comment]
A `VGAE` encoder needs to return two latent variables: `mu` and `logvar`.

**Comment by jlevy44** [comment]
Still no luck. The VGAE lacks a proper encode method. The encoder does not work. I can try to PR.

It's failing at model.encode

**Comment by jlevy44** [comment]
Needs mu, logvar layers. Are these two GCN layers?

**Comment by rusty1s** [comment]
The `encoder` should be fine, e.g.:
```python
class Encoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(Encoder, self).__init__()
        self.conv1 = GCNConv(in_channels, 2 * out_channels)
        self.conv_mu = GCNConv(2 * out_channels, out_channels)
        self.conv_logvar = GCNConv(2 * out_channels, out_channels)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        return self.conv_mu(x, edge_index), self.conv_logvar(x, edge_index)
```

**Comment by jlevy44** [comment]
Oh, sorry not thinking right now. Thanks!

**Comment by jlevy44** [comment]
Let me try it.

**Comment by jlevy44** [comment]
Still same error. It's in the first connv layer

**Comment by rusty1s** [comment]
Runs fine for me on Cora. Are you using a different dataset?

**Comment by jlevy44** [comment]
Yeah. 33 node network with attribute matrix

**Comment by jlevy44** [comment]
Why would this error come up?

**Comment by rusty1s** [comment]
Seems like: `edge_index.max().item() + 1 > x.size(0)`

**Comment by jlevy44** [comment]
What's a good solution here?

**Comment by rusty1s** [comment]
You need to fix your dataset.

**Comment by jlevy44** [comment]
x.size()
torch.Size([33, 17])

edge_index.size()
torch.Size([2, 307])

Why is it looking for index 340?

**Comment by rusty1s** [comment]
What's the output of `edge_index.max().item()`?

**Comment by jlevy44** [comment]
32

**Comment by jlevy44** [comment]
Weird...

**Comment by jlevy44** [comment]
edge_index.max().item() + 1 > x.size(0)

False

**Comment by jlevy44** [comment]
I think my data set should be fine

**Comment by jlevy44** [comment]
The GAE implementation is now no longer working as well.

**Comment by jlevy44** [comment]
It was working earlier with this dataset.

**Comment by jlevy44** [comment]
I looked into why there was an error. Seems like the problem is here: torch.cat([edge_weight, loop_weight], dim=0)

in 

```
 @staticmethod
    def norm(edge_index, num_nodes, edge_weight, improved=False, dtype=None):
        if edge_weight is None:
            edge_weight = torch.ones(
                (edge_index.size(1), ), dtype=dtype, device=edge_index.device)
        edge_weight = edge_weight.view(-1)
        assert edge_weight.size(0) == edge_index.size(1)
 
        edge_index, _ = remove_self_loops(edge_index)
        edge_index = add_self_loops(edge_index, num_nodes)
```

**Comment by jlevy44** [comment]
This expands size from 307 -> 340

But when running scatter_add, the incoming src, edge_weight is 340, while row is 307
```
deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
```
The size of these two must agree.

I think norm must be modified to make sure dimensionality of edge_weight and row agree

**Comment by jlevy44** [comment]
The addition of looop weight is not reflected in row

**Comment by jlevy44** [comment]
Is it the removal of self loops? That's causing length of row to be less than edge weights?

**Comment by rusty1s** [comment]
Mh, I do not see a problem with the addition of self-loops.
1. We create edge weights (if not given) with the same dimensionality as `edge_index`.
2. We first remove and (re-)add self-loops, causing `edge_index` to grow by `num_nodes`.
3. We add loop weights to edge weights, causing `edge_weight` to grow by `num_nodes`.
Hence, `edge_weight` and `edge_index` should have the same dimensionality after adding self-loops.

**Comment by rusty1s** [comment]
Ah, I see. This fails when edge indices already contain self-loops. I will fix it.

**Comment by rusty1s** [comment]
Fixed in master!
