### ISSUE TITLE
ARMA example running failed

### ISSUE THREAD

**Issue by JunweiSUN** [rusty1s/pytorch_geometric#1556]
## 🐛 Bug
Dear @rusty1s , thanks for this amazing repo! However, I have some trouble running the official ARMAConv [example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/arma.py).
I'm using pytorch 1.5.0 and torch_geometric 1.6.0, ubuntu 16.04, cuda 10.0
The error message is `IndexError: index 0 is out of bounds for dimension 0 with size 0`.
Could you please check this for me? Thanks!

## To Reproduce

```
git clone https://github.com/rusty1s/pytorch_geometric.git
cd examples
python arma.py
```
## Expected behavior
This code can run report result normally.

## Environment

* OS: ubuntu 16.04
* Python version: 3.6.10
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.2
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Thanks for letting me know. It is now fixed in master.
