### ISSUE TITLE
Embeddings from GCNConv

### ISSUE THREAD

**Issue by niklasamslgruber** [rusty1s/pytorch_geometric#1559]
## ❓ Questions & Help

I have a two-layer GCN and would like to visualize the embeddings using Sklearn's TSNE. However, I do not find the raw embeddings data in the GCNConv class. Is there a way to get them?

**Comment by rusty1s** [comment]
The raw embeddings correspond to the output of the GCN layers. To get them, you can use PyTorch hooks or additionally return them in your model's `forward` method, *e.g.*, as follows:
```python
def forward(self, x, edge_index):
     x1 = self.conv1(x, edge_index)
     x2 = self.conv2(F.relu(x1), edge_index)
     return x2.log_softmax(dim=-1), x1
```

**Comment by niklasamslgruber** [comment]
Awesome, thank you very much @rusty1s
