### ISSUE TITLE
No data assigned to some GPUs when using DataParallel

### ISSUE THREAD

**Issue by 1zb** [rusty1s/pytorch_geometric#156]
## 🐛 Bug
```
TypeError: descriptor 'union' of 'set' object needs an argument
```
Line 23 of `torch_geometric/data/batch.py`

## To Reproduce

This error happens when using `torch_geometric.nn.DataParallel`.

Suppose we have 4 GPUs and 4 graphs (`num_nodes`: `[2, 3, 10, 4]`). The function `scatter` from `torch_geometric/nn/data_parallel.py` gives `split=[0, 2, 2, 3, 4]`, which means we assign two graphs to `GPU:0` and no graph to `GPU:1`.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Fixed in master! Thank you.
