### ISSUE TITLE
Back-propagating through limited number of Nodes having Target.

### ISSUE THREAD

**Issue by reshinthadithyan** [rusty1s/pytorch_geometric#1560]
### Problem Setting
Say I have a Graph with Nodes: [a,b,c,d,e]. Out of which only [a,c,e] have targets [0,1,0](Node Classification).
Edge_Index goes like [[a,b,c,d,e],[b,d,e,a,e]].
How do I use this and to learn an unified feature extractor in such a setting?

**Comment by rusty1s** [comment]
I think the `examples/gcn.py` example covers this use-case pretty well. You basically just train your model based on the nodes you have labels for (but still use all other nodes to gather information).

**Comment by reshinthadithyan** [comment]
Thanks. This would still allow me to use the Feature Extractor for the Nodes with no Label right?

**Comment by rusty1s** [comment]
Yes, exactly. This is known as semi-supervised learning. You can have a look at the [GCN paper](https://arxiv.org/abs/1609.02907) for a more detailed explanation.
