### ISSUE TITLE
Weighted GraphSAGE

### ISSUE THREAD

**Issue by yuanx749** [rusty1s/pytorch_geometric#1563]
## ❓ Questions & Help

Hi,
It seems that edge_weight is not used in the ```SAGEConv```. Is it possible to make it support weighted graph?

**Comment by juntingzh** [comment]
They used to support edge weight but removed it in https://github.com/rusty1s/pytorch_geometric/commit/e93e3c58c4edb433cd0ee4e56805369e2d051380. I am not sure if simply revert this commit for the sage_conv.py works.

**Comment by rusty1s** [comment]
I think what you're looking for is the [`GraphConv`](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GraphConv), which is able to take in `edge_weight` as an additional parameter to `forward`.

**Comment by yuanx749** [comment]
Thank you! I'll look into it.
