### ISSUE TITLE
Support for edge attributes (or kwargs) in message() method of MessagePassing base class

### ISSUE THREAD

**Issue by agamemnonc** [rusty1s/pytorch_geometric#1566]
## 🚀 Feature / Motivation

On certain occasions, one might want to construct messages that also take into account edge attributes along with node features. 

Would it be worth including `edge_attr` as an additional argument in `message()` method (with default set to `None`)? Obviously, one can just override the method in child class and use additional arguments, e.g. `edge_attr`. However this would violate the Liskov substitution principle (see discussion [here](https://stackoverflow.com/questions/6034662/python-method-overriding-does-signature-matter)).
Alternatively, the `message()` method could support `kwargs` for an even more general case. 

Happy to submit a PR in case of a positive response.

**Comment by rusty1s** [comment]
In practice, one can already access every value passed to `propagate` in `message`, and some ops make already use of `edge_attr` to create messages, *e.g.*, [this one](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gin_conv.py#L145-L146).

**Comment by agamemnonc** [comment]
Indeed, this is exactly the case I am referring to. 

One potential issue is that in this case the signature of the child class is different to the one in the base class. This is typically OK (including my own case), but can sometimes prove problematic. Copying from the [source](https://stackoverflow.com/a/54155637) provided above:

`So, what if you change the signature of the overridden method in the derived class? Everything works correctly if the call is on the derived instance but if you make the call on the base instance, you will get an error because the base class uses a different signature for that same method name.`

I acknowledge that this is a nit-pick and wouldn't of course mind rejection of my suggestion :)

**Comment by rusty1s** [comment]
I personally think that this is not problematic at all, since `message` is an internal function which is never called directly by the user.

One can also relate it to the solution presented in your thread. You can see the arguments passed to `propagate` as `**kwargs`, and you have access to those arguments in `message`.

**Comment by agamemnonc** [comment]
> I personally think that this is not problematic at all, since `message` is an internal function which is never called directly by the user.

Fair enough, please feel free to close this issue in this case.


> **Edit:** One might also think of implementing `message` in the base class as:
> 
> ```python
> def message(self, **kwargs):
>     raise NotImplementedError
> ```
> 
> which wouldn't violate the Liskov substitution principle.

This is exactly what I was suggesting, but requires modifying the `MessagePassing` base class method.

**Comment by rusty1s** [comment]
Yeah, I could do that, but it might break some external code.

**Comment by agamemnonc** [comment]
In that case probably not worth it, but up to you.
