### ISSUE TITLE
data.num_features = 0 for  imdb-b, reddit-b and collab

### ISSUE THREAD

**Issue by andac-demir** [rusty1s/pytorch_geometric#1567]
## ❓ Questions & Help

Hi, when I run `pytorch_geometric/benchmark/kernel/statistics.py` num_features for imdb-b, reddit-b and collab datasets are displayed 0. Is this a bug?

**Comment by rusty1s** [comment]
That's not a bug at all. It's just that these datasets do not come with pre-defined node features.

**Comment by andac-demir** [comment]
So do they have a variable number of node features?

**Comment by rusty1s** [comment]
No, they have zero node features. The task is to classify those graphs solely based on their graph structure. Since GNNs require some kind of node features, a good choice is to use the (one-hot encoded) node degree as input node features.

**Comment by andac-demir** [comment]
Thanks a lot for the clarification. Is there an example script?

**Comment by rusty1s** [comment]
You can use [this code](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/datasets.py#L21-L38) to add node degrees as input features.
