### ISSUE TITLE
How to build the doc

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [rusty1s/pytorch_geometric#1577]
## ❓ Questions & Help
Hi @rusty1s ,

I hope you are doing great! I really like the doc, would it be possible to see how it was built?

Cheers,

Francesco

**Comment by rusty1s** [comment]
You can build the docs by installing `sphinx` and `sphinx_rtd_theme`, and run `make html` inside the `docs` folder.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you,  I am not sure how to get your output inside the `./docs/source/modules`. I am familiar with `sphinx` and I usually use `sphinx-apidoc` but I was not able to match your output

**Comment by rusty1s** [comment]
Does the build complete? It should automatically build the modules page via `autodoc`.
