### ISSUE TITLE
Error with examples/autoencoder

### ISSUE THREAD

**Issue by humble-gambler** [rusty1s/pytorch_geometric#158]
I have run the given scripts in the examples folder and some scripts such as gcn, gat and infomax are fine, but fail in running autoencoder.

The error is: 
ImportError: cannot import name 'GAE'.
But I have checked the module path: torch_geometric.nn.models.autoencoder, the class GAE exists and all __init__ files are correct.

So I am curious about why the problem happens.

**Comment by rusty1s** [comment]
After pulling from master, you need to re-install the package, either via
```
python setup.py install
```
or
```
python setup.py develop
```

**Comment by humble-gambler** [comment]
Thanks for reply. 
But I have already installed the package, so I am wonder why the problem will happen. 😂

**Comment by rusty1s** [comment]
I just released version `1.1.0`. Hopefully, this fixes your issue.
