### ISSUE TITLE
Unsupervised GraphSAGE

### ISSUE THREAD

**Issue by johnny12150** [rusty1s/pytorch_geometric#1582]
## ❓ Questions & Help

Is there an example of GraphSAGE trained with the unsupervised task such as link predictions?

**Comment by rusty1s** [comment]
Hey, we have two open PRs ready for this:
1. https://github.com/rusty1s/pytorch_geometric/pull/1514
2. https://github.com/rusty1s/pytorch_geometric/pull/1515

**Comment by johnny12150** [comment]
Tks! I will try it.
