### ISSUE TITLE
Data clusters of ClusterData have wrong number of nodes

### ISSUE THREAD

**Issue by tobiasbernecker** [rusty1s/pytorch_geometric#1587]
## 🐛 Bug

Hi @rusty1s ,

the torch_geometric.data.Data clusters computed and contained in a torch_geometric.data.ClusterData instance all have the same number of nodes as the original torch_geometric.data.Data, but the expected behavior here is to have a smaller number of nodes if num_parts > 1, just like the size of the first dimension of the node features x, which works as intended, or the indices contained in edge_index, which also works as intended.

Example:
graph is the original torch_geometric.data.Data instance with graph.num_nodes = 24 and graph.x.size() = torch.Size([24, 21]).
Then graph is clustered into num_parts = 3 clusters with subgraphs = torch_geometric.data.ClusterData(...). The subgraphs of type torch_geometric.data.Data all have subgraphs[i].x.size() = torch.Size([8, 21]) and all indices contained in subgraphs[i].edge_index are in the range [0, 7], but subgraphs[i].num_nodes = 24, which should also be 8 in this case.

Best regards,
Tobias

**Comment by rusty1s** [comment]
Hi and thanks for reporting. This is now fixed in master :)
