### ISSUE TITLE
Cuda 11.0

### ISSUE THREAD

**Issue by jhonygiraldo** [rusty1s/pytorch_geometric#1593]
Hi, really nice work,

I have successfully installed geometric PyTorch on a CPU-based machine and on a cu101 machine. However, I need to install geometric PyTorch on a machine with cuda 11, and I do not have the permission to change the GPU drivers. Is there a way to install geometric PyTorch with cuda 11.0? I have PyTorch 16.0 and Cuda 11.0 (Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0). Thanks.

**Comment by rusty1s** [comment]
Not yet, since it currently isn't yet supported in PyTorch. I'm not sure if there are any adjustments to make for CUDA 11, so you get around this by simply trying to install the external packages from source, *e.g.*:
```
pip install torch-scatter
```

**Comment by todpole3** [comment]
I tried installing from source and got this error:
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.7/site-packages/torch_scatter/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationESs
```

**Comment by rusty1s** [comment]
It seems like that is not yet possible (at least not easily), since the PyTorch CUDA version needs to match with your local CUDA version. The only way I can think of is to install PyTorch from source with CUDA 11 support. As far as I know, official CUDA 11 support for PyTorch is planned for PyTorch 1.7.0.

**Comment by jhonygiraldo** [comment]
Hi @rusty1s, yes you are right, I tried to install PyTorch from the source but it was a nightmare. What I did at the end was to install PyTorch in a conda environment as follows:
$ conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
When you do that inside a conda environment, you will install CUDA 10.2 and cudnn binaries within the Conda environment, so the system-installed CUDA 11 will not be used at all.
Finally, I installed Geometric Pytorch and worked just fine. Thank you.

**Comment by rusty1s** [comment]
That sounds great :) Awesome!

**Comment by Randl** [comment]
Hi,
as for now pytorch already supports CUDA 11. Moreover, from my understanding, it's the only way to use pytorch with 30XX GPUs. It would be nice to be able to run pytorch-geometric on those.

**Comment by rusty1s** [comment]
Yes, we now support CUDA 11 since PyTorch 1.7.0 landed :)

**Comment by SultanIsaly** [comment]
Hi, @rusty1s 
I tried to install torch-sparse from source (https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html), but faced with OSError (libcudart.so.10.2: cannot open shared object file: No such file or directory). 
I have used torch 1.7.0+cu110 and cuda 11.0; What could be the problem, that torch-sparse refers to cuda 10.2?
