### ISSUE TITLE
Workflow for distributing wheels for multiple CUDA versions.

### ISSUE THREAD

**Issue by duncster94** [rusty1s/pytorch_geometric#1599]
## ❓ Questions & Help

Hi, I'm in the process of packaging my code for distribution and I would like to build wheels for multiple CUDA versions. I see you've built PyTorch Geometric wheels for different CUDA/Python/OS specifications and I was wondering what your workflow is?

For a bit of context, my project relies on PyTorch Geometric, so I would like to do something similar to what you have, i.e. one example distribution of my project would be `my_project-latest+cu102-cp38-cp38-linux_x86_64.whl` which would rely on the underlying `torch_sparse`, `torch_cluster` and `torch_scatter` wheels with the same specifications (i.e. wheels ending in `cu102-cp38-cp38-linux_x86_64`).

Do you know if this is possible, or should I have an install process that essentially asks the user to do
```$ pip install torch-scatter==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.6.0.html
$ pip install torch-sparse==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.6.0.html
$ pip install torch-cluster==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.6.0.html
$ pip install torch-spline-conv==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.6.0.html
$ pip install torch-geometric
```
first, followed by a `pip install` of my package?

Thanks!

**Comment by rusty1s** [comment]
The PyG workflow for building wheels for different CUDA versions can be found in the [travis config](https://github.com/rusty1s/pytorch_scatter/blob/master/.travis.yml).

Regarding the installation process: The only way I know of how to group those packages into a single installation command is via `conda`. I'm fairly certain that this cannot be done via `pip`, and that's the reason users need to install the external packages in advance for PyG.

As such, your suggested solution should work fine (even if it is a bit cumbersome), but I will work on conda support in the future.

**Comment by duncster94** [comment]
Great, thanks!
