### ISSUE TITLE
 TORCH_GEOMETRIC.IO.TU 

### ISSUE THREAD

**Issue by GazelleThr** [rusty1s/pytorch_geometric#1601]
Hi there,

I am trying to read my data using TORCH_GEOMETRIC.IO.TU code. My data type is exactly similar to the enzymes dataset. However, the program stops with the Illegal instruction (core dumped) error at this line "node_slice = torch.cumsum(torch.from_numpy(np.bincount(batch)), 0)" in the split function. It seems that the problem is with the dimension but I can't figure out what the solution is. I received a similar error in "node_labels = node_labels - node_labels.min(dim=0)[0]" line. I added the node labels to the node attribute to avoid using this part of the code. Could you please help with this. I have also attached my data to this post for your reference.

here are my specifications installed for pytorch:
torch 1.6.0
tensorflow 2.2.0
cuda 10.1
nvcc  10.1 

[file_A.txt](https://github.com/rusty1s/pytorch_geometric/files/5168253/file_A.txt)
[file_edge_attributes.txt](https://github.com/rusty1s/pytorch_geometric/files/5168254/file_edge_attributes.txt)
[file_graph_indicator.txt](https://github.com/rusty1s/pytorch_geometric/files/5168255/file_graph_indicator.txt)
[file_graph_labels.txt](https://github.com/rusty1s/pytorch_geometric/files/5168256/file_graph_labels.txt)
[file_node_attributes.txt](https://github.com/rusty1s/pytorch_geometric/files/5168257/file_node_attributes.txt)

Please note, I installed the package exactly as it is mentioned in the document.

Also, in the split function, the comment says that "Edge indices should start at zero for every graph.". However, the edge index starts at 1 and the numbering continues for all graphs. Could please clarify this as well.

Thanks

**Comment by rusty1s** [comment]
I cannot reproduce this. Putting the files inside a folder `TU/file/raw` and running:
```python
from torch_geometric.datasets import TUDataset

dataset = TUDataset('~/Downloads/file', name='file')
print(dataset[0])
```
works as expected. Can you process other TUDatasets?

**Comment by GazelleThr** [comment]
Thanks for your help. It works now.

**Comment by GazelleThr** [comment]
Hi Matthias,

Sorry to bother you again. 

I read my dataset with "train_data = read_tu_data(folder,prefix)" and the output is as bellow ( I copied everything to clarification, I have 364 graphs):

 (Data(edge_attr=[56289, 1], edge_index=[2, 56289], x=[18763, 9], y=[18763]), {'edge_index': tensor([    0,   201,   357,   519,   684,   855,  1032,  1188,  1323,  1500,
         1638,  1812,  1932,  2094,  2256,  2448,  2607,  2784,  2949,  3078,
         3201,  3369,  3501,  3666,  3813,  3972,  4074,  4260,  4422,  4593,
         4773,  4947,  5124,  5331,  5514,  5670,  5805,  5979,  6126,  6249,
         6450,  6633,  6807,  6984,  7128,  7266,  7446,  7590,  7674,  7830,
         8007,  8178,  8346,  8511,  8691,  8811,  8976,  9129,  9246,  9339,
         9486,  9648,  9798,  9960, 10071, 10251, 10434, 10599, 10716, 10887,
        11064, 11253, 11412, 11580, 11757, 11904, 12060, 12258, 12432, 12540,
        12684, 12849, 13026, 13191, 13299, 13455, 13611, 13764, 13956, 14142,
        14322, 14505, 14664, 14835, 14970, 15144, 15321, 15495, 15600, 15711,
        15852, 16014, 16170, 16329, 16488, 16647, 16800, 16995, 17112, 17274,
        17388, 17556, 17715, 17874, 18075, 18219, 18369, 18528, 18660, 18837,
        18939, 19101, 19218, 19386, 19521, 19644, 19779, 19929, 20076, 20211,
        20388, 20544, 20715, 20898, 21078, 21234, 21393, 21576, 21750, 21915,
        22083, 22230, 22368, 22503, 22662, 22806, 22950, 23091, 23271, 23406,
        23583, 23721, 23859, 24042, 24198, 24372, 24546, 24672, 24885, 25068,
        25167, 25350, 25533, 25716, 25872, 26028, 26199, 26310, 26442, 26613,
        26724, 26850, 27033, 27198, 27366, 27519, 27684, 27867, 27993, 28146,
        28299, 28437, 28635, 28794, 28956, 29136, 29310, 29499, 29601, 29724,
        29850, 29988, 30165, 30276, 30441, 30561, 30732, 30912, 31086, 31275,
        31446, 31605, 31743, 31860, 32013, 32184, 32283, 32424, 32583, 32730,
        32871, 33042, 33216, 33369, 33498, 33660, 33825, 33975, 34101, 34266,
        34377, 34527, 34701, 34884, 35070, 35247, 35388, 35490, 35661, 35793,
        35964, 36084, 36213, 36375, 36534, 36639, 36777, 36885, 37017, 37203,
        37383, 37506, 37671, 37821, 37977, 38100, 38283, 38406, 38502, 38643,
        38829, 38931, 39069, 39276, 39456, 39585, 39741, 39867, 40020, 40173,
        40326, 40494, 40662, 40809, 40956, 41100, 41232, 41361, 41502, 41667,
        41775, 41943, 42108, 42258, 42435, 42537, 42696, 42834, 42957, 43068,
        43200, 43320, 43470, 43575, 43689, 43854, 43962, 44148, 44307, 44439,
        44586, 44745, 44895, 45069, 45171, 45285, 45396, 45585, 45714, 45870,
        46041, 46191, 46329, 46524, 46701, 46836, 47007, 47121, 47277, 47415,
        47592, 47712, 47871, 48003, 48183, 48312, 48480, 48618, 48783, 48945,
        49116, 49311, 49458, 49629, 49800, 49974, 50109, 50277, 50433, 50562,
        50742, 50925, 51105, 51288, 51429, 51582, 51765, 51933, 52116, 52254,
        52425, 52578, 52713, 52881, 53067, 53244, 53442, 53559, 53676, 53844,
        53994, 54156, 54258, 54402, 54570, 54747, 54921, 55107, 55254, 55452,
        55632, 55755, 55950, 56112, 56289]), 'x': tensor([    0,    67,   119,   173,   228,   285,   344,   396,   441,   500,
          546,   604,   644,   698,   752,   816,   869,   928,   983,  1026,
         1067,  1123,  1167,  1222,  1271,  1324,  1358,  1420,  1474,  1531,
         1591,  1649,  1708,  1777,  1838,  1890,  1935,  1993,  2042,  2083,
         2150,  2211,  2269,  2328,  2376,  2422,  2482,  2530,  2558,  2610,
         2669,  2726,  2782,  2837,  2897,  2937,  2992,  3043,  3082,  3113,
         3162,  3216,  3266,  3320,  3357,  3417,  3478,  3533,  3572,  3629,
         3688,  3751,  3804,  3860,  3919,  3968,  4020,  4086,  4144,  4180,
         4228,  4283,  4342,  4397,  4433,  4485,  4537,  4588,  4652,  4714,
         4774,  4835,  4888,  4945,  4990,  5048,  5107,  5165,  5200,  5237,
         5284,  5338,  5390,  5443,  5496,  5549,  5600,  5665,  5704,  5758,
         5796,  5852,  5905,  5958,  6025,  6073,  6123,  6176,  6220,  6279,
         6313,  6367,  6406,  6462,  6507,  6548,  6593,  6643,  6692,  6737,
         6796,  6848,  6905,  6966,  7026,  7078,  7131,  7192,  7250,  7305,
         7361,  7410,  7456,  7501,  7554,  7602,  7650,  7697,  7757,  7802,
         7861,  7907,  7953,  8014,  8066,  8124,  8182,  8224,  8295,  8356,
         8389,  8450,  8511,  8572,  8624,  8676,  8733,  8770,  8814,  8871,
         8908,  8950,  9011,  9066,  9122,  9173,  9228,  9289,  9331,  9382,
         9433,  9479,  9545,  9598,  9652,  9712,  9770,  9833,  9867,  9908,
         9950,  9996, 10055, 10092, 10147, 10187, 10244, 10304, 10362, 10425,
        10482, 10535, 10581, 10620, 10671, 10728, 10761, 10808, 10861, 10910,
        10957, 11014, 11072, 11123, 11166, 11220, 11275, 11325, 11367, 11422,
        11459, 11509, 11567, 11628, 11690, 11749, 11796, 11830, 11887, 11931,
        11988, 12028, 12071, 12125, 12178, 12213, 12259, 12295, 12339, 12401,
        12461, 12502, 12557, 12607, 12659, 12700, 12761, 12802, 12834, 12881,
        12943, 12977, 13023, 13092, 13152, 13195, 13247, 13289, 13340, 13391,
        13442, 13498, 13554, 13603, 13652, 13700, 13744, 13787, 13834, 13889,
        13925, 13981, 14036, 14086, 14145, 14179, 14232, 14278, 14319, 14356,
        14400, 14440, 14490, 14525, 14563, 14618, 14654, 14716, 14769, 14813,
        14862, 14915, 14965, 15023, 15057, 15095, 15132, 15195, 15238, 15290,
        15347, 15397, 15443, 15508, 15567, 15612, 15669, 15707, 15759, 15805,
        15864, 15904, 15957, 16001, 16061, 16104, 16160, 16206, 16261, 16315,
        16372, 16437, 16486, 16543, 16600, 16658, 16703, 16759, 16811, 16854,
        16914, 16975, 17035, 17096, 17143, 17194, 17255, 17311, 17372, 17418,
        17475, 17526, 17571, 17627, 17689, 17748, 17814, 17853, 17892, 17948,
        17998, 18052, 18086, 18134, 18190, 18249, 18307, 18369, 18418, 18484,
        18544, 18585, 18650, 18704, 18763]), 'edge_attr': tensor([    0,   201,   357,   519,   684,   855,  1032,  1188,  1323,  1500,
         1638,  1812,  1932,  2094,  2256,  2448,  2607,  2784,  2949,  3078,
         3201,  3369,  3501,  3666,  3813,  3972,  4074,  4260,  4422,  4593,
         4773,  4947,  5124,  5331,  5514,  5670,  5805,  5979,  6126,  6249,
         6450,  6633,  6807,  6984,  7128,  7266,  7446,  7590,  7674,  7830,
         8007,  8178,  8346,  8511,  8691,  8811,  8976,  9129,  9246,  9339,
         9486,  9648,  9798,  9960, 10071, 10251, 10434, 10599, 10716, 10887,
        11064, 11253, 11412, 11580, 11757, 11904, 12060, 12258, 12432, 12540,
        12684, 12849, 13026, 13191, 13299, 13455, 13611, 13764, 13956, 14142,
        14322, 14505, 14664, 14835, 14970, 15144, 15321, 15495, 15600, 15711,
        15852, 16014, 16170, 16329, 16488, 16647, 16800, 16995, 17112, 17274,
        17388, 17556, 17715, 17874, 18075, 18219, 18369, 18528, 18660, 18837,
        18939, 19101, 19218, 19386, 19521, 19644, 19779, 19929, 20076, 20211,
        20388, 20544, 20715, 20898, 21078, 21234, 21393, 21576, 21750, 21915,
        22083, 22230, 22368, 22503, 22662, 22806, 22950, 23091, 23271, 23406,
        23583, 23721, 23859, 24042, 24198, 24372, 24546, 24672, 24885, 25068,
        25167, 25350, 25533, 25716, 25872, 26028, 26199, 26310, 26442, 26613,
        26724, 26850, 27033, 27198, 27366, 27519, 27684, 27867, 27993, 28146,
        28299, 28437, 28635, 28794, 28956, 29136, 29310, 29499, 29601, 29724,
        29850, 29988, 30165, 30276, 30441, 30561, 30732, 30912, 31086, 31275,
        31446, 31605, 31743, 31860, 32013, 32184, 32283, 32424, 32583, 32730,
        32871, 33042, 33216, 33369, 33498, 33660, 33825, 33975, 34101, 34266,
        34377, 34527, 34701, 34884, 35070, 35247, 35388, 35490, 35661, 35793,
        35964, 36084, 36213, 36375, 36534, 36639, 36777, 36885, 37017, 37203,
        37383, 37506, 37671, 37821, 37977, 38100, 38283, 38406, 38502, 38643,
        38829, 38931, 39069, 39276, 39456, 39585, 39741, 39867, 40020, 40173,
        40326, 40494, 40662, 40809, 40956, 41100, 41232, 41361, 41502, 41667,
        41775, 41943, 42108, 42258, 42435, 42537, 42696, 42834, 42957, 43068,
        43200, 43320, 43470, 43575, 43689, 43854, 43962, 44148, 44307, 44439,
        44586, 44745, 44895, 45069, 45171, 45285, 45396, 45585, 45714, 45870,
        46041, 46191, 46329, 46524, 46701, 46836, 47007, 47121, 47277, 47415,
        47592, 47712, 47871, 48003, 48183, 48312, 48480, 48618, 48783, 48945,
        49116, 49311, 49458, 49629, 49800, 49974, 50109, 50277, 50433, 50562,
        50742, 50925, 51105, 51288, 51429, 51582, 51765, 51933, 52116, 52254,
        52425, 52578, 52713, 52881, 53067, 53244, 53442, 53559, 53676, 53844,
        53994, 54156, 54258, 54402, 54570, 54747, 54921, 55107, 55254, 55452,
        55632, 55755, 55950, 56112, 56289]), 'y': tensor([    0,    67,   119,   173,   228,   285,   344,   396,   441,   500,
          546,   604,   644,   698,   752,   816,   869,   928,   983,  1026,
         1067,  1123,  1167,  1222,  1271,  1324,  1358,  1420,  1474,  1531,
         1591,  1649,  1708,  1777,  1838,  1890,  1935,  1993,  2042,  2083,
         2150,  2211,  2269,  2328,  2376,  2422,  2482,  2530,  2558,  2610,
         2669,  2726,  2782,  2837,  2897,  2937,  2992,  3043,  3082,  3113,
         3162,  3216,  3266,  3320,  3357,  3417,  3478,  3533,  3572,  3629,
         3688,  3751,  3804,  3860,  3919,  3968,  4020,  4086,  4144,  4180,
         4228,  4283,  4342,  4397,  4433,  4485,  4537,  4588,  4652,  4714,
         4774,  4835,  4888,  4945,  4990,  5048,  5107,  5165,  5200,  5237,
         5284,  5338,  5390,  5443,  5496,  5549,  5600,  5665,  5704,  5758,
         5796,  5852,  5905,  5958,  6025,  6073,  6123,  6176,  6220,  6279,
         6313,  6367,  6406,  6462,  6507,  6548,  6593,  6643,  6692,  6737,
         6796,  6848,  6905,  6966,  7026,  7078,  7131,  7192,  7250,  7305,
         7361,  7410,  7456,  7501,  7554,  7602,  7650,  7697,  7757,  7802,
         7861,  7907,  7953,  8014,  8066,  8124,  8182,  8224,  8295,  8356,
         8389,  8450,  8511,  8572,  8624,  8676,  8733,  8770,  8814,  8871,
         8908,  8950,  9011,  9066,  9122,  9173,  9228,  9289,  9331,  9382,
         9433,  9479,  9545,  9598,  9652,  9712,  9770,  9833,  9867,  9908,
         9950,  9996, 10055, 10092, 10147, 10187, 10244, 10304, 10362, 10425,
        10482, 10535, 10581, 10620, 10671, 10728, 10761, 10808, 10861, 10910,
        10957, 11014, 11072, 11123, 11166, 11220, 11275, 11325, 11367, 11422,
        11459, 11509, 11567, 11628, 11690, 11749, 11796, 11830, 11887, 11931,
        11988, 12028, 12071, 12125, 12178, 12213, 12259, 12295, 12339, 12401,
        12461, 12502, 12557, 12607, 12659, 12700, 12761, 12802, 12834, 12881,
        12943, 12977, 13023, 13092, 13152, 13195, 13247, 13289, 13340, 13391,
        13442, 13498, 13554, 13603, 13652, 13700, 13744, 13787, 13834, 13889,
        13925, 13981, 14036, 14086, 14145, 14179, 14232, 14278, 14319, 14356,
        14400, 14440, 14490, 14525, 14563, 14618, 14654, 14716, 14769, 14813,
        14862, 14915, 14965, 15023, 15057, 15095, 15132, 15195, 15238, 15290,
        15347, 15397, 15443, 15508, 15567, 15612, 15669, 15707, 15759, 15805,
        15864, 15904, 15957, 16001, 16061, 16104, 16160, 16206, 16261, 16315,
        16372, 16437, 16486, 16543, 16600, 16658, 16703, 16759, 16811, 16854,
        16914, 16975, 17035, 17096, 17143, 17194, 17255, 17311, 17372, 17418,
        17475, 17526, 17571, 17627, 17689, 17748, 17814, 17853, 17892, 17948,
        17998, 18052, 18086, 18134, 18190, 18249, 18307, 18369, 18418, 18484,
        18544, 18585, 18650, 18704, 18763])})

 Then I load it by "train_loader = DataLoader(train_data, batch_size=32, shuffle=True)" which the output is an object <torch_geometric.data.dataloader.DataLoader object at 0x7f2c20bc67c0>

However, when I want to iterate through train_loader by 
   for batch in train_loader:
       print('This is the batch inside the loop', batch)
and 
for batch, (data, target) in enumerate(train_loader, 1): 

But I receive this error:
Traceback (most recent call last):
  File "GCNN.py", line 328, in <module>
    for batch in train_loader:
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 35, in __call__
    return self.collate(batch)
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 16, in collate
    return Batch.from_data_list(batch, self.follow_batch)
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 33, in from_data_list
    keys = [set(data.keys) for data in data_list]
  File "/home/taherzadehg/.conda/envs/AAG/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 33, in <listcomp>
    keys = [set(data.keys) for data in data_list]
TypeError: 'builtin_function_or_method' object is not iterable

I tried different ways such as next(iter(train_loader)), but still, receive errors.

I can't figure out what the problem is. Do you think I should read the information for each graph separately? I followed the enzyme dataset example. Could you please help with this issue. 

Thank you for your time.

**Comment by rusty1s** [comment]
Yeah, that cannot work since `read_tu_data` does not return a list of data objects. It groups them all together into a single one :)

You can do
```python
class MyDataset(InMemoryDataset):
    super(MyDataset, self).__init__(root, transform=None)
    self.data, self.slices = read_tu_data(root)
```
as a workaround.

**Comment by GTaherzadeh** [comment]
Hi Matthias,

Thanks for the solution. I did as you suggested and it seems the program reads my data correctly. However, when I want to pass the data to the model I receive "Illegal instruction (core dumped)" after calling the optimizer. I am not sure why this error happens and would be great if you can help with this too.
here is the piece of code to train the model: 
model, train_loss, valid_loss = train_model(model, batch_size, patience, n_epochs)

def train_model(model, batch_size, patience, n_epochs):
    # to track the training loss as the model trains
    train_losses = []
    # to track the validation loss as the model trains
    valid_losses = []
    # to track the average training loss per epoch as the model trains
    avg_train_losses = []
    # to track the average validation loss per epoch as the model trains
    avg_valid_losses = []
    # initialize the early_stopping object
    early_stopping = EarlyStopping(patience=patience, verbose=True)
    for epoch in range(1, n_epochs + 1):
         ###################
        # train the model #
        ###################
        model.train() # prep model for training
        for batch, data in enumerate(train_dataset, 1):
            target = data.y
            # clear the gradients of all optimized variables
            optimizer.zero_grad()
            # forward pass: compute predicted outputs by passing inputs to the model
            output = model(data) # Error happens here
            # calculate the loss
            loss = criterion(output, target)
            # backward pass: compute gradient of the loss with respect to model parameters
            loss.backward()
            # perform a single optimization step (parameter update)
            optimizer.step()
            # record training loss
            train_losses.append(loss.item())

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(9, 16) #dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, 2) #16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

Thank you for your help.

**Comment by rusty1s** [comment]
You're code looks fine to me, so I'm not really sure yet. It would be great if you could dig a little bit deeper which call exactly produces this error.

**Comment by youdar** [comment]
I am trying to follow the example in 
https://colab.research.google.com/drive/1BRPw3WQjP8ANSFz-4Z1ldtNt9g7zm-bv?usp=sharing

and getting the error when doing 
`from torch_geometric.datasets import TUDataset`   

I tried to restart runtime and try to run this again, but get the same error

``` 
OSError                                   Traceback (most recent call last)
<ipython-input-3-62bf19b3e6f9> in <module>()
----> 1 from torch_geometric.datasets import TUDataset

6 frames
/usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py in <module>()
      2 from importlib import import_module
      3 
----> 4 import torch_geometric.data
      5 import torch_geometric.loader
      6 import torch_geometric.transforms

/usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py in <module>()
----> 1 from .data import Data
      2 from .hetero_data import HeteroData
      3 from .temporal import TemporalData
      4 from .batch import Batch
      5 from .dataset import Dataset

/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py in <module>()
      1 from typing import (Optional, Dict, Any, Union, List, Iterable, Tuple,
      2                     NamedTuple, Callable)
----> 3 from torch_geometric.typing import OptTensor, NodeType, EdgeType
      4 from torch_geometric.deprecation import deprecated
      5 

/usr/local/lib/python3.7/dist-packages/torch_geometric/typing.py in <module>()
      2 
      3 from torch import Tensor
----> 4 from torch_sparse import SparseTensor

OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor5zero_Ev
```

**Comment by rusty1s** [comment]
I think you need to upgrade the installation commands of `torch-scatter` and `torch-sparse` to:
```
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```
