### ISSUE TITLE
QM9 and ZINC Element to Index Mapping

### ISSUE THREAD

**Issue by alstonlo** [rusty1s/pytorch_geometric#1605]
## ❓ Questions & Help

Hi, I am using the `torch_geometric.datasets.ZINC` dataset. From my understanding, calling `data.x` will retrieve the node features, one of which is an index representing the element identity. It would be helpful (for visualization purposes) if I could also see the index to element mapping used to create the ZINC dataset, and similarly for the other chemistry-based datasets. 

Is there anywhere I can look to find these mappings? Sorry, I couldn't seem to find it on the docs or source code. Thanks for your help!

**Comment by rusty1s** [comment]
The indices in `data.x` correspond to the atomic number of the element.
