### ISSUE TITLE
Weighted Graph Edge Index Matrix

### ISSUE THREAD

**Issue by andac-demir** [rusty1s/pytorch_geometric#1608]
Hi,
I have a graph where I don't have access to the location proximity and distance between nodes. I first assumed it is an unweighted graph and created an edge index matrix with 0's and 1's, but I want to train my GNN models on weighted graphs. To begin with I will change my edge index matrix manually to have values between 0 and 1. Later I want to design a method to that learns these edge weights. I appreciate if you have any suggestions on GNN training with weighted graphs and you can lead me to an example script/paper. Thanks a lot.

**Comment by rusty1s** [comment]
In case you want to operate on a fully-connected graph where you want to learn the probability of an edge, it might be best to use/modify the dense GNN operators provided in PyG. Nonetheless, you can still learn/incorporate edge weights using the `edge_index` format. While you cannot backpropgate through `edge_index`, you can store an additional attribute `edge_weight` and use it in conjunction with `edge_index` for message passing. There are some ops that can make use addtional edge weights, *e.g.*, `GraphConv` or `GCNConv`.
