### ISSUE TITLE
read_ply using openmesh

### ISSUE THREAD

**Issue by GostInShell** [rusty1s/pytorch_geometric#1610]
## To Reproduce

1.
[tr_reg_039.txt](https://github.com/rusty1s/pytorch_geometric/files/5177713/tr_reg_039.txt)
from torch_geometric.io import read_ply
data = read_ply('\path\to\tr_reg_039.ply')
print(f'number_nodes:{data.num_nodes}')

## Expected behavior
The element vertex should be 3446, and it sure is when using plyfile, meshlab, cloudcompare... to load it. However, when using openmesh to load it, data.number_nodes=3449.

## Environment

* OS:Ubuntu 16.04
* Python version:3.7
* PyTorch version:1.4.0
* CUDA/cuDNN version:10.0
* torch_geometric:1.6.0

**Comment by rusty1s** [comment]
Thanks for reporting. I'm not sure though how to handle this issue. This looks like an openmesh issue to me. Do you know what's preventing openmesh to read it correctly?

**Comment by GostInShell** [comment]
Sorry, I've done some tests but still cannot find the answer. Here are some conclusions:

- Pretty sure it's an openmesh issue.
- The extra three points are actually true points and from one same face. (Found by printing the data.pos.)
- The result is consistent and repeatable, which makes me think perhaps something's wrong with the .ply. I load it with Meshlab and convert it into an Ascii file (not sure whether Meshlab has done any changes) and nothing is wrong. (I'm not familiar with the convertion of binary files, maybe convert it directly into a readable file can get a confirm answer on this problem. )

ps: openmesh version 1.1.4.post18 installed using pip.
