### ISSUE TITLE
Custom Pos and Neg Edge Index in VGAE and GAE

### ISSUE THREAD

**Issue by reshinthadithyan** [rusty1s/pytorch_geometric#1614]
## ❓ Questions & Help

As the Title suggests, how can I add my custom Pos,Neg Edge Indices for recon_loss in GAE?

**Comment by rusty1s** [comment]
You may want to override `recon_loss` and pass it both `pos_edge_index` and `neg_edge_index` as arguments.

**Comment by reshinthadithyan** [comment]
Say, 
Edges = (A,B),(A,C),(P,Q),(P,R) are the actual Graph Edges.
I have a positive edge (B,Q). Is this mathematically valid to bring B and Q closer?

**Comment by rusty1s** [comment]
I'm not sure I understand. Maybe you can elaborate a bit more. From what you're saying, I feel like if (B, Q) is a positive edge, it's natural to infer that B and Q should be closer to each other than A and Q.

**Comment by reshinthadithyan** [comment]
Am I safe to assume, B and Q being Closer than A and B, If I have another Positive Edge, A and P?

**Comment by rusty1s** [comment]
That's hard to tell actually and it's definitely not safe to assume. You can just verify that experimentally.

**Comment by reshinthadithyan** [comment]
Thanks. I'll close .
