### ISSUE TITLE
Unable to run arma.py in examples/

### ISSUE THREAD

**Issue by jungla88** [rusty1s/pytorch_geometric#1619]
## 🐛 Bug

Arma example seems not work due to IndexError. 

## To Reproduce

Run arma.py:

$ python arma.py

File "arma_conv.py", line 106, in forward
    out = out @ self.weight[0 if self.shared_weights else t - 1]
IndexError: index 0 is out of bounds for dimension 0 with size 0 

## Environment

* OS: Kubuntu 20.04 Linux 5.4
* Python version: Python 3.8.5
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.2
* GCC version: 9.3.0

**Comment by rusty1s** [comment]
Which PyG version are you using? This should have been fixed in PyG 1.6.1.

**Comment by jungla88** [comment]
$ pip list | grep torch

torch                         1.6.0
torch-cluster                 1.5.7
torch-geometric               1.6.1
torch-scatter                 2.0.5
torch-sparse                  0.6.7
torch-spline-conv             1.2.0
torchvision                   0.7.0

**Comment by rusty1s** [comment]
Sry, it seems to be only fixed in master. Running
```
pip install --upgrade git+https://github.com/rusty1s/pytorch_geometric.git
```
should help.

**Comment by jungla88** [comment]
Thank you. It works.
