### ISSUE TITLE
question about adding self-loops

### ISSUE THREAD

**Issue by Zhiyu-Chen** [rusty1s/pytorch_geometric#1622]
https://github.com/rusty1s/pytorch_geometric/blob/3234dbf0b4fdce06b3fb1a54f75792c4b09f603c/torch_geometric/utils/loop.py#L84

Is it assumed that for every graph the node indices should be a range starting from 0 ? I may have graphs that have nodes with indices 2,5,6.

**Comment by rusty1s** [comment]
Hey. In PyG, node indices should correspond to the the size of your node feature matrix, *e.g.*, `x[0]` corresponds to node 0, and so on. Therefore, values in `edge_index` needs to be in the interval `[0, ..., num_nodes - 1]`. In your case, you may need to relabel your graph to this format.

**Comment by Zhiyu-Chen** [comment]
> Hey. In PyG, node indices should correspond to the the size of your node feature matrix, _e.g._, `x[0]` corresponds to node 0, and so on. Therefore, values in `edge_index` needs to be in the interval `[0, ..., num_nodes - 1]`. In your case, you may need to relabel your graph to this format.

thanks for the clarification!
