### ISSUE TITLE
ShapeNet baseline data can't be download

### ISSUE THREAD

**Issue by tbonewmy** [rusty1s/pytorch_geometric#1630]
## 🐛 Bug
When using torch geometric's default way to download Shapenet, the following message pops up.
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

Apparently, when downloading, the shapenet website requires register now. I can bypass the error by manually download the data and tweak some code in the input function. But then I will need to tweak them back when I need to download other data. Is there some fix to that? Does anyone know if I can just pass my username and password inside python function so that it can download again?
## To Reproduce
from torch_geometric.datasets import ShapeNet
`dataset = ShapeNet(root=<the directory that you want to download to>, categories=['Airplane'], pre_transform=T.KNNGraph(k=6),transform=T.RandomTranslate(0.01))`

**Comment by SilvioGiancola** [comment]
I am facing the same issue, have you found a solution?
Is this problem independent of pytorch geometric?

**Comment by tbonewmy** [comment]
> I am facing the same issue, have you found a solution?
> Is this problem independent of pytorch geometric?

The issue is `https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip` this URL require credential to download. and the `urllib.request.urlopen()` function inside download.py may not be able to pass credentials. I am not 100% sure, because I can't find source code for this function.   

A bypass is to manually download the data. 

1. Just paste the URL to your browser. It leads you to the shapenet website. you need to register an account there. 
2. After making sure you can login to the website, you can paste the address to the browser again to download the data. 
3. You then create a folder called `ShapeNet`. Inside it, you create another folder called `raw`. Put the downloaded zip file inside `raw` and run the `ShapeNet()` function, make sure the path point to the zip file.

**Comment by tchaton** [comment]
Dear @SilvioGiancola @tbonewmy,

It is a simple ssl error. The bug has been solved there: https://github.com/nicolas-chaulet/torch-points3d

Best regards,
T.C

**Comment by tbonewmy** [comment]
> Dear @SilvioGiancola @tbonewmy,
> 
> It is a simple ssl error. The bug has been solved there: https://github.com/nicolas-chaulet/torch-points3d
> 
> Best regards,
> T.C

Thanks @tchaton . Have one last question for you though. Will there be a conflict if I install both torch-geometric and torch-point3d? Do you know?

**Comment by rusty1s** [comment]
This is now also fixed in PyG master :)

**Comment by uservinu** [comment]
root shall be the folder not the zip file.
dataset = ShapeNet(root='/home/user/datasets/ShapeNet/raw/', categories=['Airplane'],
                    pre_transform=T.KNNGraph(k=6),
                    transform=T.RandomTranslate(0.01))

**Comment by ftlong6666** [comment]
@rusty1s I still found the similar issues about the SSL Error.

**Comment by rusty1s** [comment]
Are you running on PyG from master?
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
I will craft a new release with all updates/bugfixes soon.
