### ISSUE TITLE
Atom types of ZINC datasets.

### ISSUE THREAD

**Issue by JinheonBaek** [rusty1s/pytorch_geometric#1632]
## ❓ Questions & Help

Hello,

I'm using the QM9 and ZINC datasets for visualization purposes.
In the case of QM9 (torch_geometric.datasets.QM9), there are some pre-defined types that describe the mapping from data.x to atom number.

However, in the case of ZINC (torch_geometric.datasets.ZINC), there are no such pre-defined types.
I tried matching indicies in data.x to atomic number of elements as suggested in #1605, but it fails to construct the valid molecule.

Is there any atom_type dictionary that maps index to atomic number in ZINC dataset?

Thanks!

**Comment by JinheonBaek** [comment]
I found the answer in other repo, such that I close this issue.

ref. https://github.com/graphdeeplearning/benchmarking-gnns/issues/42#issue-700553516

Thanks. :)

**Comment by rusty1s** [comment]
Awesome :)
