### ISSUE TITLE
Segmentation fault when using h5py

### ISSUE THREAD

**Issue by dr-stringfellow** [rusty1s/pytorch_geometric#1634]
## 📚 Installation

The install of the packages seem fine. But I get a Segmentation fault with no additional information when doing:

`import h5py; from torch_geometric.data import Dataset` 

Importing h5py on its own or Dataset on its own works fine, only in combination I get a SegFault.

## Environment

* OS: CentOS 7.6.1810
* Python version: 3.8.3
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.2
* GCC version: 8.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): source
* Any other relevant information:

## Checklist

- [x ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Which version of `h5py` are you using? Maybe you can downgrade it and see if the error disappears.

**Comment by dr-stringfellow** [comment]
I am using 2.10.0 and tried downgrading to 2.7.x, but without success. I just discovered however that explicitly including

`import sklearn`

anywhere in the code (e.g. at the top of the executable) fixes the Segmentation fault.
