### ISSUE TITLE
Support for sparse node features

### ISSUE THREAD

**Issue by alexmirrington** [rusty1s/pytorch_geometric#1635]
## ❓ Questions & Help

Hi there,

I am looking at GCNs for visual question answering, a problem which requires efficient embedding of up to thousands of different object classes. I have experimented with `torch.nn.functional.one_hot` encodings of objects, however such large node feature dimensions cause a large slowdown when compared to lower-dimensional dense features such as those retrieved from CNNs. My question is two-fold:

1. Is there support for sparse node features in PyG?
2. What kind of alternatives to one-hot vectors would be worth trying? My background is mainly in DL and NLP, where we mainly deal with dense feature representations.

Cheers,
Alex.

**Comment by rusty1s** [comment]
There is some kind of sparse node feature matrix support in PyG, for example, `GCNConv` should work fine when inputting a `torch.sparse_coo_tensor` as node feature matrix `x`, but that's not the case for all GNN operators.
To fix, one could also make use of an initial simple `Linear` layer to reduce the dimensions of your high-dimensional sparse features.

**Comment by alexmirrington** [comment]
Thanks so much, that's good to know about the GCNConv layers, I'll make sure to check the source on a case-by-case basis. As a side note, thank you so much for all the hard work put into this library, I look forward to being able to contribute to it in the near future!
