### ISSUE TITLE
Neighbor Sampler system memory usage

### ISSUE THREAD

**Issue by johnny12150** [rusty1s/pytorch_geometric#1637]
## ❓ Questions & Help

I have a little question about high memory usage when calling `Neighbor Sampler` in each batch.
First, I thought the memory will be free after the batch is ended, however, it seems that the memory usage is straightly increasing after I repeatedly calling the `Neighbor Sampler` across the batches within the same epoch.
The purpose of calling the `Neighbor Sampler` once in a batch is to gather the neighbors of a certain list of nodes, which is showed in the below code.
```python
def compute_scores(self, all_interest_emb, targets,train):
        if train==True:
            targets = torch.Tensor(targets).cuda(int(os.environ['gpu'])).long()
            targets_len = targets.shape[1]
            targets = targets.flatten()
            targets_loader = NeighborSampler(
                self.edge_index, node_idx=targets,
                sizes=[25], batch_size=targets.shape[0], shuffle=False,
                num_workers=0)
            for (batch_size_, u_id, adjs_u) in targets_loader:
                adjs_u = adjs_u.to('cuda:' + os.environ['gpu'])
                u_id = self.embedding(u_id.cuda(int(os.environ['gpu'])))
                targets_emb = self.G_SAGE(u_id, adjs_u)
                targets_emb = targets_emb.view([-1, targets_len, self.opt.hiddenSize])
```

Is it normal that the memory will only be free till the epoch is ended?
Or is there any recommended way to handle my goal which I need to find all neighbors of a list of nodes in batches?

The full version of the code could be found below.
https://gist.github.com/johnny12150/06d81d3f2935dbdf07f6fc0c52a813a1

**Comment by rusty1s** [comment]
I tested that and for me, the memory allocation is fixed across steps and epochs. The garbage collector may hold on to the memory, and may free it any time, so it's quite hard to tell actually.

If you only want to find the 1-hop neighbors around a batch of nodes, please also have a look at the `k_hop_subgraph` method in `torch_geometric.utils`.

**Comment by johnny12150** [comment]
So,  the major difference between `Neighbor Sampler` the `k_hop_subgraph` will also return all neighbors?
I will test the difference in the memory usage of these two methods.

**Comment by johnny12150** [comment]
The above behavior happened only on my ubuntu 18.04 machine, that the memory allocated by the `neighbor sampler` won't be free even the batch ended.
I test the same code on Windows 10 machine, but the memory used by the `neighbor sampler` would immediately free as the below picture.

![image](https://user-images.githubusercontent.com/22369387/93312209-8667df00-f839-11ea-9505-606e862b3c07.png)
