### ISSUE TITLE
There is a question about a theta in ChebConv.

### ISSUE THREAD

**Issue by SeongJinAhn** [rusty1s/pytorch_geometric#1638]
## ❓ Questions & Help

![image](https://user-images.githubusercontent.com/37531907/93182206-5f93a500-f774-11ea-8847-b94dea2eddf7.png)

In the paper [ https://papers.nips.cc/paper/6081-convolutional-neural-networks-on-graphs-with-fast-localized-spectral-filtering.pdf ], the theta is said to be a vector of polynomial coefficients.
Hence, I understood that theta_k should be a constant.

However, it seems that theta_k is a matrix in complemented codes.
Is there any reason to complement in this way?
Or theta should be revised to matrices in R^KxMxN?

**Comment by rusty1s** [comment]
Here, `theta_k` corresponds to the trainable parameters of the `ChebConv`. Note that the formulation in the paper is solely based on 1-dimensional inputs (to 1-dimensional outputs). It's generalization leaves us with a tensor `theta_k` of shape [k, in_channels, out_channels]`. Hope this clarifies your issue :)
