### ISSUE TITLE
How to load big data into the model

### ISSUE THREAD

**Issue by chu525** [rusty1s/pytorch_geometric#164]
## ❓ Questions & Help

Hello, author, I met a problem，I have 60,000 graphs. Each graph has an average of 5,000 nodes. 
 I used  it
>data_list = [Data(...), Data(...), Data(...)]

 data is too large. How should I read it into the model? Do you have any good solutions?

**Comment by rusty1s** [comment]
Given the amount of data, it is best to only load a graph on demand. You can have a look at the [dataset documentation](https://rusty1s.github.io/pytorch_geometric/build/html/notes/create_dataset.html#creating-larger-datasets) for more details.

**Comment by chu525** [comment]
I tried the method you said, it was successful, thank you very much.
