### ISSUE TITLE
GATConv: attention computation for i-nodes and j-nodes should be distinct

### ISSUE THREAD

**Issue by aTamaz** [rusty1s/pytorch_geometric#1642]
## 🐛 Bug

In `GATConv`, if the feature input `x` in the `forward(..)` function is a Tensor (as opposed to a tuple of tensors), the attention weights `alpha_r` and `alpha_l` are computed with the same parameter vector `self.att_l`. Instead, it seems that they should be computed with _different_ parameters `self.att_r` and `self.att_l`. This would follow the original paper's formulation, where concatenated features `h_i'` and `h_j'` are dot-multiplied with a parameter vector (which has as many entries as `h_i'` and `h_j'` combined).

If I understood correctly, this [line](https://github.com/rusty1s/pytorch_geometric/blob/2b303b9ff504e073d2b4fc6d1c82edf7cd198da6/torch_geometric/nn/conv/gat_conv.py#L125):

```
alpha_l = alpha_r = (x_l * self.att_l).sum(dim=-1)
```

has to be replaced by

```
alpha_l = (x_l * self.att_l).sum(dim=-1)
alpha_r = (x_r * self.att_r).sum(dim=-1)
```
(the features `x_l` and `x_r` are indeed the same).

I hope I haven't overlooked anything! Not sure if any tests need to be adapted.

**Comment by rusty1s** [comment]
Yes, you are right. Thanks for reporting. This bug got introduced in PyG 1.6.0, but it is now fixed :)

**Comment by zcajiayin** [comment]
There is a typo in the corrected code:
`alpha_r = (x_l * self.att_r).sum(dim=-1)` -> `alpha_r = (x_r * self.att_r).sum(dim=-1)`

**Comment by rusty1s** [comment]
Yeah, it's indeed a typo, but I did not cause any harm since `x_l = x_r`. It is now fixed.
