### ISSUE TITLE
MNISTSuperpixel broken URL (again)

### ISSUE THREAD

**Issue by viduzz84** [rusty1s/pytorch_geometric#1644]
## 🐛 Bug

MNISTSuperpixel dataset has a broken download URL.
Even if it was fixed recently, I think the URL is changed again.
The correct one is:
https://graphics.cs.tu-dortmund.de/fileadmin/ls7-www/misc/cvpr/mnist_superpixels.tar.gz

## To Reproduce

from torch_geometric.datasets import MNISTSuperpixels
train_dataset = MNISTSuperpixels(path, True, transform=transform)

>>HTTPError: HTTP Error 404: Not Found

**Comment by rusty1s** [comment]
Thanks for letting me know. I changed the URL once again in master. The old URL still works for me though:
https://ls7-www.cs.tu-dortmund.de/fileadmin/ls7-www/misc/cvpr/mnist_superpixels.tar.gz
