### ISSUE TITLE
Default values for batch attributes

### ISSUE THREAD

**Issue by mariolinovIC** [rusty1s/pytorch_geometric#1647]
Hi,

Let's say I have an object of the class Data and I create a batch with it:
```
data = Data()
batch = Batch.from_data_list([data])
```
In this case `data.x = None `, and by default  `batch.x = None`. I would like get also this behaviour for other attributes. For instance, I would like to get:

```
data = Data()
data.glob = None
batch = Batch.from_data_list([data])
print(batch.glob) = None
```
However, I get that batch.glob is not defined. How can I get the same behaviour than with x.

Cheers

**Comment by rusty1s** [comment]
Should be fixed in master :)
