### ISSUE TITLE
Dose pytorch geometric support graph pooling in torchscript?

### ISSUE THREAD

**Issue by weijian-sun** [rusty1s/pytorch_geometric#1653]
## ❓ Questions & Help

recently, i'm deploy my gnn model in a real-time/user level system, but it seems that last version of torch geomtric dose not support graph pooling method for torchscript, [see here](https://github.com/rusty1s/pytorch_geometric/issues/434)  However, graph pooling is realy important in my gnn model. I just want to know dost the lastest version support graph pooling or any solution to work around it?

**Comment by rusty1s** [comment]
Which graph pooling method is missing support for TorchScript?

**Comment by weijian-sun** [comment]
Actually i have a model like this:

```

class EdgeConv(MessagePassing):
    def __init__(self, aggr: str = 'max', **kwargs):
        super(EdgeConv, self).__init__(aggr=aggr, **kwargs)
        self.nn = Sequential(Linear(10, 10),
                            LayerNorm(10),
                            ReLU())
    def forward(self, x: Union[Tensor, PairTensor], edge_index: Adj) -> Tensor:
        if isinstance(x, Tensor):
            x: PairTensor = (x, x)
        return self.propagate(edge_index, x=x, size=None)

    def message(self, x_i: Tensor, x_j: Tensor) -> Tensor:
        return self.nn(torch.cat([x_i, x_j], dim=-1))

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = EdgeConv().jittable()
        self.conv2 = EdgeConv().jittable()
        self.conv3 = EdgeConv().jittable()
        self.g_conv = EdgeConv().jittable()
    def forward(self, data):
        data.x = self.conv1(data.x, data.edge_index)
        data.x = self.conv2(data.x, data.edge_index)
        data.x = self.conv3(data.x, data.edge_index)
        clu = GenerateBatchCluster(data, data.pos)
        global_graph = max_pool(clu, data)

```

when i try to call jit.script, i got:
```
model = Net()
it =torch.jit.script(model)
```

![image](https://user-images.githubusercontent.com/13504794/93740820-d2da6280-fc1d-11ea-9fbc-7e04f93cb5bb.png)

**Comment by rusty1s** [comment]
For TorchScript, you cannot pass `data` to the `forward` call, but instead need to pass each attribute separately, *e.g.*:
```python
def forward(self, x, edge_index, pos)
    ...
```

**Comment by weijian-sun** [comment]
> Which graph pooling method is missing support for TorchScript?

Maybe it's not a graph pooling related problem, but a torchscript related issue, see the following:

**Comment by weijian-sun** [comment]
> For TorchScript, you cannot pass `data` to the `forward` call, but instead need to pass each attribute separately, _e.g._:
> 
> ```python
> def forward(self, x, edge_index, pos)
>     ...
> ```

yes, but in max_pool, we cannot pass the attribute, but the 'data' type, how to implement that?

**Comment by rusty1s** [comment]
Yeah, that's a current limitation. Any method that takes `data` as input is currently not "jittable". You can get around it by re-implementing the functionality of `max_pool` without passing `data` objects around.
