### ISSUE TITLE
OSError undefined symbol when using Pytorch built from source

### ISSUE THREAD

**Issue by marwage** [rusty1s/pytorch_geometric#1657]
## ❓ Questions & Help

Hi,

The PyG project is great! Keep up the good work!

I would like to change some parts inside Pytorch and therefore need to build Pytorch from source.
The tag I am using to build Pytorch is `v1.6.0`
[https://github.com/pytorch/pytorch/releases/tag/v1.6.0](https://github.com/pytorch/pytorch/releases/tag/v1.6.0).

If I build Pytorch from source and then install the necessary packages for PyG, I get the following error when `import torch_geometric.transforms as T` is executed:
```python
OSError: /home/ubuntu/gpu_memory_reduction/torch-source/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationESs
```

My installation is in a `virtualenv`, the CUDA version is 10.2, and the versions of the packages are:
```text
torch                 1.6.0a0+b31f58d
torch-cluster         1.5.7
torch-geometric       1.6.1
torch-scatter         2.0.5
torch-sparse          0.6.7
torch-spline-conv     1.2.0
```
Only `torch` is built from source. The other packages are installed with the binaries.

I get the same error if I install everything in a `conda` environment.

If I use the current binary of Pytorch, I do not get the error and my code just runs.

I saw the other issues where it is pointed out that there might be two versions of Pytorch but I do not see where the second version should be and I installed everything in a clean virtual environment.

Does anyone have an idea what the issue might be?
Any help is highly appreciated!

**Comment by rusty1s** [comment]
The error usually occurs when external libraries are compiled with a different PyTorch version than the one you are using (which makes sense in your case). Your best bet is to also install `torch-scatter` and `torch-sparse` from source, either via `pip install torch-scatter` or by cloning the GitHub repo and running `python setup.py install`.

**Comment by marwage** [comment]
Thank you for your answer!

I needed to install every `torch-*` package from source.
The order seems to be important as well. Reinstalling the package that was currently throwing the error solved the issue for me.
