### ISSUE TITLE
RuntimeError: result type Floatcan't be cast to the desired output type Long

### ISSUE THREAD

**Issue by LanceKnight** [rusty1s/pytorch_geometric#1660]
## ❓ Questions & Help

<type error when using GCNConv>

```python
import rdkit

from torch_geometric.datasets import MoleculeNet

dataset = MoleculeNet(root='/tmp',name = 'HIV')


import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)

print(torch.cuda.is_available())
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
print(type(dataset))
print("dataset:",dataset[0])
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

model.eval()
_, pred = model(data).max(dim=1)
correct = float (pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))
```

```
**Error:**

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-5-b875e5d5d8e5> in <module>()
>      39 for epoch in range(200):
>      40     optimizer.zero_grad()
> ---> 41     out = model(data)
>      42     loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
>      43     loss.backward()
> 
> 4 frames
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> <ipython-input-5-b875e5d5d8e5> in forward(self, data)
>      21         x, edge_index = data.x, data.edge_index
>      22 
> ---> 23         x = self.conv1(x, edge_index)
>      24         x = F.relu(x)
>      25         x = F.dropout(x, training=self.training)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> /usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
>     146                     edge_index, edge_weight = gcn_norm(  # yapf: disable
>     147                         edge_index, edge_weight, x.size(self.node_dim),
> --> 148                         self.improved, self.add_self_loops, dtype=x.dtype)
>     149                     if self.cached:
>     150                         self._cached_edge_index = (edge_index, edge_weight)
> 
> /usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in gcn_norm(edge_index, edge_weight, num_nodes, improved, add_self_loops, dtype)
>      61         row, col = edge_index[0], edge_index[1]
>      62         deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)
> ---> 63         deg_inv_sqrt = deg.pow_(-0.5)
>      64         deg_inv_sqrt.masked_fill_(deg_inv_sqrt == float('inf'), 0)
>      65         return edge_index, deg_inv_sqrt[row] * edge_weight * deg_inv_sqrt[col]
> 
> RuntimeError: result type Floatcan't be cast to the desired output type Long
```

**Comment by rusty1s** [comment]
Please have a look [here](https://github.com/rusty1s/pytorch_geometric/issues/1537). I will try to make that more clear in the documentation.

**Comment by LanceKnight** [comment]
Hi, Rusty1s, thanks for the suggestion. That problem is gone but "x = self.emb(x)" gave me a new error. Sorry I'm new to machine learning.

Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

**Comment by rusty1s** [comment]
Please see my answer [here](https://github.com/rusty1s/pytorch_geometric/issues/1660#issuecomment-698559538).

**Comment by LanceKnight** [comment]
Hi, Rusty1s, adding emb() fixed the above problem but introduced a new one. (now I'm trying to use CPU since GPU also gives me other problems.)

```
import rdkit
from ogb.graphproppred.mol_encoder import AtomEncoder
from torch_geometric.datasets import Planetoid
from torch_geometric.datasets import MoleculeNet
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import global_max_pool
from torch_geometric.data import DataLoader


dataset = MoleculeNet(root='/tmp',name = 'HIV')
batch_size = 64


class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.emb = AtomEncoder(16)
        self.conv1 = GCNConv(16, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.emb(x)
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        
        return global_max_pool(F.log_softmax(x, dim=1), batch = data.batch)

device = torch.device('cuda' if not torch.cuda.is_available() else 'cpu')
print(f"device:{device}")
model = Net().to(device)

dataset= dataset[:1000]
train_dataset = dataset[:500]
test_dataset = dataset[500:]

data = dataset[0]
print(f"data.x:{dataset.num_classes}")

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.L1Loss()

for data in train_loader:  # Iterate in batches over the training dataset.

        print(f"data.x.size():{data.x.shape}")
        data.to(device)

        out = model(data)  # Perform a single forward pass.
        data.y = data.y.long()
        print(f"out.shape:{out.shape}, data.y:{data.y.shape}, out.type():{out.type()}, data.y.type():{data.y.type()}")
        loss = criterion(out, data.y ) # Compute the loss.
        loss.backward()  # Derive gradients.
        optimizer.step()  # Update parameters based on gradients.
        optimizer.zero_grad()  # Clear gradients.



model.eval()
_, pred = model(data).max(dim=1)
correct = float (pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))
```

> device:cpu
> data.x:1
> data.x.size():torch.Size([1465, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1374, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1335, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1088, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1415, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1313, 9])
> out.shape:torch.Size([64, 1]), data.y:torch.Size([64, 1]), out.type():torch.FloatTensor, data.y.type():torch.LongTensor
> data.x.size():torch.Size([1344, 9])
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-17-7cd0ea4a05c2> in <module>()
>      53         data.to(device)
>      54 
> ---> 55         out = model(data)  # Perform a single forward pass.
>      56         data.y = data.y.long()
>      57         print(f"out.shape:{out.shape}, data.y:{data.y.shape}, out.type():{out.type()}, data.y.type():{data.y.type()}")
> 
> 6 frames
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> <ipython-input-17-7cd0ea4a05c2> in forward(self, data)
>      23     def forward(self, data):
>      24         x, edge_index = data.x, data.edge_index
> ---> 25         x = self.emb(x)
>      26         x = self.conv1(x, edge_index)
>      27         x = F.relu(x)
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> /usr/local/lib/python3.7/site-packages/ogb/graphproppred/mol_encoder.py in forward(self, x)
>      20         x_embedding = 0
>      21         for i in range(x.shape[1]):
> ---> 22             x_embedding += self.atom_embedding_list[i](x[:,i])
>      23 
>      24         return x_embedding
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py in forward(self, input)
>     124         return F.embedding(
>     125             input, self.weight, self.padding_idx, self.max_norm,
> --> 126             self.norm_type, self.scale_grad_by_freq, self.sparse)
>     127 
>     128     def extra_repr(self) -> str:
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
>    1812         # remove once script supports set_grad_enabled
>    1813         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
> -> 1814     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
>    1815 
>    1816 
> 
> IndexError: index out of range in self

The weird thing is that the output of out.shape got printed different times in each execution. Like here, it was printed 7 times, while it could be printed 3, 2, or other times. This inconsistency makes it hard for me to debug and I'm also wondering why it was okay to have a complete run without index out of range?

**Comment by rusty1s** [comment]
You can use the following `AtomEncoder` instead of the one provided by OGB:
```python
class AtomEncoder(torch.nn.Module):
    def __init__(self, hidden_channels):
        super(AtomEncoder, self).__init__()

        self.embeddings = torch.nn.ModuleList()

        for i in range(9):
            self.embeddings.append(torch.nn.Embedding(100, hidden_channels))

    def reset_parameters(self):
        for embedding in self.embeddings:
            embedding.reset_parameters()

    def forward(self, x):
        if x.dim() == 1:
            x = x.unsqueeze(1)

        out = 0
        for i in range(x.size(1)):
            out += self.embeddings[i](x[:, i])
        return out
```

**Comment by LanceKnight** [comment]
Worked! Thank you so much!
