### ISSUE TITLE
Autoencoder decoder output shape size

### ISSUE THREAD

**Issue by SasCezar** [rusty1s/pytorch_geometric#1663]
## ❓ Questions & Help

Hi, I'm using the Autoencoder example from the examples ([autoencoder.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py)). However, when using the decoder to reconstruct the adjacency matrix, I only get an output of shape [Num_Edges], and not [2 Num_Edges] as for the edge_index. My question is, how can I reconstruct the adjacency matrix to see what edge is missing. My clue is that the output is a binary label on whether or not the model reconstructed the edge in the same position in the edge_index. Is this correct, or I'm missing out something?

**Comment by reshinthadithyan** [comment]
It gives you probability if a given Edge_Index is constructed between two Nodes. That's why it is of shape [Num_Edges]
