### ISSUE TITLE
XConv: knn_graph() got an unexpected keyword argument 'num_workers'

### ISSUE THREAD

**Issue by chenzhaiyu** [rusty1s/pytorch_geometric#1673]
## To Reproduce

1. Define an XConv layer
https://github.com/rusty1s/pytorch_geometric/blob/04143195eaa52dcfa56e8656e72df57c36a76367/benchmark/points/point_cnn.py#L24

2. The forward operation on this layer throws the error
https://github.com/rusty1s/pytorch_geometric/blob/04143195eaa52dcfa56e8656e72df57c36a76367/benchmark/points/point_cnn.py#L37

where `pos.shape == torch.Size([960000, 3])` and `batch.size = 960000` (`tensor([0, 0, 0, ..., 63, 63, 63])`).

Error sessage:
```
...
  File "...\modelPCR.py", line 112, in forward
    x = self.conv1(None, pos, batch)
  File "...\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "...\lib\site-packages\torch_geometric\nn\conv\x_conv.py", line 127, in forward
    num_workers=self.num_workers)
TypeError: knn_graph() got an unexpected keyword argument 'num_workers'

Process finished with exit code 1
```

## Expected behavior

No error.

## Environment

* OS: Win10
* Python version: 3.6.10
* PyTorch version: 1.4.0
* CUDA version: 10.1
* torch-geometric: 1.6.1
* torch-cluster: 1.5.4
* torch-scatter: 2.0.4
* torch-sparse: 0.6.1
* torch-spline-conv: 1.2.0

**Comment by chenzhaiyu** [comment]
Downgrading torch-geometric to 1.5.0 solved the problem.

**Comment by rusty1s** [comment]
Perfect :)
