### ISSUE TITLE
Question about plot

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1676]
## ❓ Questions & Help

PyG is a powerful frame in graph representation field.
I want to know how to draw a picture that can reflected the clustering ability of a model.
Thank you!

**Comment by rusty1s** [comment]
For this, most people typically use the node embeddings produced by your GNN and visualize them via `T-SNE`. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/node2vec.py#L50-L67).

**Comment by jiaruHithub** [comment]
> For this, most people typically use the node embeddings produced by your GNN and visualize them via `T-SNE`. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/node2vec.py#L50-L67).

Fine,thank you!
The number of elements in ```colors``` should be equaled to ```num_classes```.
Am I right?

**Comment by rusty1s** [comment]
That's correct.
