### ISSUE TITLE
Question about the cuda version.

### ISSUE THREAD

**Issue by Boltzmachine** [rusty1s/pytorch_geometric#1679]
## ❓ Questions & Help

I use Arch Linux, and I looked up my cuda version through package management
```
pacman -Q cuda
cuda 11.0.3-1
```

However, when I run
```
python -c "import torch; print(torch.version.cuda)"
10.2
```
The cuda version is inconsistent. I think maybe pytorch automatically install a cuda version for me?

But when I import pytorch_geometric
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-3482cc0f8637> in <module>
      5 
      6 from tqdm.notebook import tqdm
----> 7 import torch_geometric
      8 
      9 from sklearn.model_selection import RepeatedKFold, RepeatedStratifiedKFold

~/.local/lib/python3.8/site-packages/torch_geometric/__init__.py in <module>
      1 from .debug import is_debug_enabled, debug, set_debug
----> 2 import torch_geometric.nn
      3 import torch_geometric.data
      4 import torch_geometric.datasets
      5 import torch_geometric.transforms

~/.local/lib/python3.8/site-packages/torch_geometric/nn/__init__.py in <module>
      1 from .meta import MetaLayer
----> 2 from .data_parallel import DataParallel
      3 from .reshape import Reshape
      4 from .conv import *  # noqa
      5 from .norm import *  # noqa

~/.local/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py in <module>
      3 
      4 import torch
----> 5 from torch_geometric.data import Batch
      6 
      7 

~/.local/lib/python3.8/site-packages/torch_geometric/data/__init__.py in <module>
----> 1 from .data import Data
      2 from .batch import Batch
      3 from .dataset import Dataset
      4 from .in_memory_dataset import InMemoryDataset
      5 from .dataloader import DataLoader, DataListLoader, DenseDataLoader

~/.local/lib/python3.8/site-packages/torch_geometric/data/data.py in <module>
      5 import torch
      6 import torch_geometric
----> 7 from torch_sparse import coalesce, SparseTensor
      8 from torch_geometric.utils import (contains_isolated_nodes,
      9                                    contains_self_loops, is_undirected)

~/.local/lib/python3.8/site-packages/torch_sparse/__init__.py in <module>
     10         '_saint', '_sample', '_relabel'
     11 ]:
---> 12     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
     13         library, [osp.dirname(__file__)]).origin)
     14 

~/.local/lib/python3.8/site-packages/torch/_ops.py in load_library(self, path)
    103             # static (global) initialization code in order to register custom
    104             # operators with the JIT.
--> 105             ctypes.CDLL(path)
    106         self.loaded_libraries.add(path)
    107 

/opt/miniconda3/lib/python3.8/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 
    372         if handle is None:
--> 373             self._handle = _dlopen(self._name, mode)
    374         else:
    375             self._handle = handle

OSError: libcusparse.so.10: cannot open shared object file: No such file or directory
```
So how to solve it? I have no problem when I was working with pytorch.

**Comment by rusty1s** [comment]
In case your local CUDA version and the PyTorch CUDA version do not match, it's best to point the CUDA paths to the CUDA installed via (mini)conda. See [here](https://github.com/rusty1s/pytorch_geometric/issues/1476).

**Comment by Boltzmachine** [comment]
Well, I installed an extra cuda 10.2 version in /usr/local end set the ``LD_LIBRARY_PATH`` . And it was imported without error. Hope it still works when doing the training task.

**Comment by Boltzmachine** [comment]
If I do not encounter with further problems of the version in the next three days. I will come here to close the issue. Thank you very much!

**Comment by rusty1s** [comment]
Perfect :)

**Comment by jmandivarapu1** [comment]
@rusty1s  I am also facing the same issue. I looked at the other link which you mentioned above but ```LD_LIBRARY_PATH```  is empty and I can't find any cuda libararies folder in my local. I tried all possible solutions but none of it worked out. Can you help us with this? 

I tried looking for cuda library https://discuss.pytorch.org/t/where-is-cudatoolkit-path-when-installed-via-conda/47791/5

<img width="783" alt="Screen Shot 2020-09-30 at 3 33 16 PM" src="https://user-images.githubusercontent.com/21245519/94731130-45d88d00-0332-11eb-8169-0d3ff5538e28.png">

**Comment by rusty1s** [comment]
There should at least exist a `cudatoolkit` installed by conda which you can link to.

**Comment by Boltzmachine** [comment]
maybe you can download an extra cuda instead.

**Comment by jmandivarapu1** [comment]
> There should at least exist a `cudatoolkit` installed by conda which you can link to.

I searched for cuda in anaconda. these are my search results can you tell me which path to export/


<img width="775" alt="Screen Shot 2020-10-02 at 9 32 08 AM" src="https://user-images.githubusercontent.com/21245519/94928883-50119d00-0492-11eb-9f1a-27c429d49477.png">

**Comment by jmandivarapu1** [comment]
> maybe you can download an extra cuda instead.

Can you let me know that process if this path doesn't workout I will try that

**Comment by rusty1s** [comment]
Mine is located in `miniconda3/lib`, you can run `find . -name "libcublas*"` to find yours.

**Comment by jmandivarapu1** [comment]
I got below and tried to set it as export LD_LIBRARY_PATH= ```~/anaconda3/lib/ or export LD_LIBRARY_PATH=~/anaconda3/lib/libcublas.so.10.0.130.'```  Both didn't work. Can you help in which of the below to set as path?

<img width="775" alt="Screen Shot 2020-10-02 at 10 05 24 AM" src="https://user-images.githubusercontent.com/21245519/94932237-cca67a80-0496-11eb-8ae2-990256e3db79.png">

**Comment by jmandivarapu1** [comment]
working now. Here is the below commands followed Incase if anyone need

```
conda create --no-default-packages -n myenv python=3.7
conda activate myenv
conda install pytorch torchvision -c pytorch
conda install torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-cluster==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-spline-conv==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-geometric
```

I have one question?
when I do ```echo $LD_LIBRARY_PATH``` is empty inside the python environment

and when I deactive the conda deactivate

```echo $LD_LIBRARY_PATH  gives output as home/jmandivarapu1/anaconda3/lib/libcublas.so.10.0.130```.

Hope that won't be an issue in future
