### ISSUE TITLE
Local result is inconsistent with torch_geometric tutorial on colab !

### ISSUE THREAD

**Issue by Boltzmachine** [rusty1s/pytorch_geometric#1684]
## ❓ Questions & Help

In the pytorch_geometric colab's tutorial  [1. Introduction.ipynb](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing#scrollTo=zF5bw3m9UrMy)
I ran the cell and got
```
from torch_geometric.datasets import KarateClub

dataset = KarateClub()
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')
```
> Dataset: KarateClub():
======================
Number of graphs: 1
Number of features: 34
**Number of classes: 4**

However, after I cloned the notebook to my local machine, I ran the same cell and got
```
from torch_geometric.datasets import KarateClub

dataset = KarateClub()
print(f'Dataset: {dataset}:')
print('======================')
print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')
```
> Dataset: KarateClub():
======================
Number of graphs: 1
Number of features: 34
**Number of classes: 2**

As you can see the number of classes is inconsistent. On colab it is 4 while on my local machine it is 2.

Also, I ran and got
```
data = dataset[0]  # Get the first graph object.

print(data)
print('==============================================================')

# Gather some statistics about the graph.
print(f'Number of nodes: {data.num_nodes}')
print(f'Number of edges: {data.num_edges}')
print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
print(f'Number of training nodes: {data.train_mask.sum()}')
print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
print(f'Contains isolated nodes: {data.contains_isolated_nodes()}')
print(f'Contains self-loops: {data.contains_self_loops()}')
print(f'Is undirected: {data.is_undirected()}')
print(data)
```
> Data(edge_index=[2, 156], x=[34, 34], y=[34])
==============================================================
Number of nodes: 34
Number of edges: 156
Average node degree: 4.59
---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
<ipython-input-12-24e294a21966> in <module>
      8 print(f'Number of edges: {data.num_edges}')
      9 print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
---> 10 print(f'Number of training nodes: {data.train_mask.sum()}')
     11 print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
     12 print(f'Contains isolated nodes: {data.contains_isolated_nodes()}')

**AttributeError: 'Data' object has no attribute 'train_mask'**

## library version
cuda 10.2
pytorch 1.6.0
pytorch_geometric 1.6.1

**Comment by rusty1s** [comment]
Please install PyG from source for the updated KarateClub dataset:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by Boltzmachine** [comment]
So is the old version PyG wrong?

**Comment by rusty1s** [comment]
No, the dataset just got enhanced by the training objective introduced in the GCN paper.

**Comment by Boltzmachine** [comment]
Ok, I have not read so many papers yet. Thanks for your reply!

**Comment by rusty1s** [comment]
Sure, feel free to ask any questions that might occur :)
