### ISSUE TITLE
segmentation fault when running example/qm9_nn_conv.py

### ISSUE THREAD

**Issue by chentingpc** [rusty1s/pytorch_geometric#169]
Hi Matthias, thanks for the awesome project! I am able to run most of examples, except for qm9_nn_conv.py, which I encountered segmentation fault (without further error message). Just wondering if anyone else has the same issue?

**Comment by rusty1s** [comment]
Hi,
the segmentation fault error is sadly an error message which is hard to debug. Have you looked at  [similar issues](https://github.com/rusty1s/pytorch_geometric/search?q=segmentation+fault&type=Issues) regarding PyTorch Extensions? As far as I remember, nearly all of them could be resolved by setting up a clean conda environement and following the installation guide.

**Comment by rusty1s** [comment]
Closed in favour of https://github.com/rusty1s/pytorch_geometric/issues/120.
