### ISSUE TITLE
Size mismatch when using GCNConv with batch size > 1

### ISSUE THREAD

**Issue by guiolpei** [rusty1s/pytorch_geometric#1690]
## 🐛 Bug

When using batch training with GCNConv and batch size > 1, a size mismatch error occurs.

## To Reproduce

We have defined a NN using GCNConv. It is made up of two graphs with 24 nodes each, both are the same graph (same positions and edges) but with different values.

The stack trace of the error is:

```
Traceback (most recent call last):
  File "trainStabilityPredictor.py", line 673, in <module>
    stability_model, stability_losses = train_stability_model_cv(stability_model_params)
  File "trainStabilityPredictor.py", line 420, in train_stability_model_cv
    output_ = stability_model(sample)
  File "/xxx/anaconda2/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/xxx/training/network/gcn_network.py", line 43, in forward
    data.x = self.fc1(data.x.view(-1))
  File "/xxx/anaconda2/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/xxx/anaconda2/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/xxx/anaconda2/envs/pytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

It works fine when batch size is 1.

Batch generation seems wrong. When batch is 1:

`Batch(batch=[24], edge_index=[2, 130], pos=[24, 3], x=[24, 2], y=[1])`

But when batch is 10:

`Batch(batch=[240], edge_index=[2, 1300], pos=[240, 3], x=[240, 2], y=[10])`

It seems it is not correctly generated, instead the elements have been concatenated.

## Environment

* OS: Ubuntu 16.04 LTS
* Python version: 3.8.5
* PyTorch version: 1.6
* CUDA/cuDNN version: 9.2/7.6.3
* GCC version: 7.3.0
* PyTorch Geometric version: 1.6.1

## Code

Network definition:

```
class GCN_test(torch.nn.Module):

    def __init__(self, numFeatures, numClasses):

        super().__init__()

        self.conv1 = GCNConv(numFeatures, 8)
        self.conv2 = GCNConv(8, 8)
        self.conv3 = GCNConv(8, 16)
        self.conv4 = GCNConv(16, 16)
        self.conv5 = GCNConv(16, 32)
        self.fc1 = torch.nn.Linear(768, 128)
        self.fc2 = torch.nn.Linear(128, numClasses * 1)

    def forward(self, data):
        data.x = F.relu(self.conv1(data.x, data.edge_index))
        data.x = F.relu(self.conv2(data.x, data.edge_index))
        data.x = F.relu(self.conv3(data.x, data.edge_index))
        data.x = F.relu(self.conv4(data.x, data.edge_index))
        data.x = F.relu(self.conv5(data.x, data.edge_index))

        log.debug(data.x.view(-1).size())
        data.x = self.fc1(data.x.view(-1))
        #data.x = F.dropout(data.x, training=self.training)
        data.x = self.fc2(data.x)
        #data.x = F.dropout(data.x, training=self.training)
        log.debug(data.x.size())
        data.x = F.log_softmax(data.x.view(1, 2), dim=1)
        log.debug(data.x.size())
        return data.x
```

DataLoader:

```
train_sampler_ = RandomSampler(training_fold_idx_)

train_loader_ = DataLoader(stability_dataset, batch_size=batch_size, sampler=train_sampler_,
                         num_workers=train_params['num_workers'])
```

Code where the error occurs:

```
for batch in train_loader_:

                samples = [batch]

                for sample in samples:

                    sample = sample.to(device)
                    optimizer_.zero_grad()
                    **output_ = stability_model(sample)**
```

## Disclaimer

This may not be a bug, instead some problem with our implementation. 

Any insight will be much appreciated. Thanks in advance.

**Comment by rusty1s** [comment]
The line `self.fc1(data.x.view(-1))` is causing this issue here and is typically something which you do not want to do in GNNs (since you lose out on permutation-invariance). An alternative to this is to use global readout layers, such as `global_mean_pool`.

However, in case you want to do that nonetheless, you need to reshape `x` to `[batch_size, num_nodes * num_features]`, *e.g.* via:
```
data.x = self.fc1(data.x.view(data.batch_size, -1))
```
Note that this only works for graphs with the same number of nodes.

**Comment by guiolpei** [comment]
Thank you for the answer, that did the trick.

We are also testing different network configuration using global readout layers.

All our samples have the same structure with all graphs having the same number of nodes.
