### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Book1996** [rusty1s/pytorch_geometric#1692]
## 🐛 Bug

cannot import name 'ToSparseTensor' from 'torch_geometric.transforms.to_sparse_tensor'

**Comment by Book1996** [comment]
In torch_geometric.transforms.to_sparse_tensor ,  there are only one class named "edge_indexToSparseTensor". Do you have same bug?

**Comment by rusty1s** [comment]
Which version of PyG are you using? The `ToSparseTensor` transform was introduced in 1.6.0, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/transforms/to_sparse_tensor.py).

**Comment by Book1996** [comment]
the version of pyg is 1.6.1, but the version is on the cpu. does the problem emerge for the version on the cpu

**Comment by rusty1s** [comment]
No, that should not happen. Did you modify its source code?

**Comment by Book1996** [comment]
no, i didn't chnage that. and i also found there is not gcnnorm class in transform modul. but i can sure the version is 1.6.1

**Comment by rusty1s** [comment]
Can you de-install `torch-geometric` and run:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
That may fix your issues.

**Comment by Book1996** [comment]
thanks, i will try  after a while.
