### ISSUE TITLE
Issue about ClusterLoader

### ISSUE THREAD

**Issue by JunweiSUN** [rusty1s/pytorch_geometric#1697]
## ❓ Questions & Help
Dear @rusty1s, I‘m using `ClusterLoader` to run my experiment, and I have a question about the `batch_size` parameter in `ClusterLoader`. For example, if I set `num_parts` to 100 in `ClusterData`, then the original graph will be partitioned into 100 subgraphs. In the original cluster-gcn paper, some subgraphs will be merged to a bigger batch before training, is this specificed by `batch_size` in `ClusterLoader`, i.e., if `num_parts` = 100 and `batch_size` = 4, there will be 25 elements in `ClusterLoader` ?

Best regrads

**Comment by rusty1s** [comment]
Yes :)

**Comment by JunweiSUN** [comment]
@rusty1s Thanks a lot!
