### ISSUE TITLE
Batch inner product decoder for VGAE

### ISSUE THREAD

**Issue by dskoda** [rusty1s/pytorch_geometric#17]
Hi,

Do you guys have any idea on how to implement an inner product decoder for architectures such as [VGAE]( https://arxiv.org/pdf/1611.07308.pdf) (Eq. 2) using mini-batches in `torch_geometric`?

Thank you!

**Comment by rusty1s** [comment]
Hi,

This is a tricky one. For graphs with equal number of nodes you can simply reshape Z to [batch_size, num_nodes, num_features] and make use of batch-wise matrix multiplication. However, I still have to think about an elegant way for a dynamic number of nodes.

**Comment by dskoda** [comment]
Thank you for your reply, @rusty1s !

After a few changes in your code, it was possible to make it. Here's what worked for me:

```python
row = torch.arange(0, data.num_nodes, dtype=torch.long)
col = data.batch
index = torch.stack([row, col], dim=0)
value = Z.new_ones(data.num_nodes)
size = torch.Size([data.num_nodes, data.batch[-1].item() + 1]) # added one to the index of last batch
assignment = torch.sparse_coo_tensor(index, value, size).to_dense() # converted sparse matrix to dense

mask = torch.matmul(assignment, assignment.t())

out = torch.matmul(Z, Z.t())
out = out * mask # masking with element-wise multiplication
```

I couldn't make the line `torch.matmul(assignment, assignment.t())` work for sparse matrices. It returned the following error: `RuntimeError: Sparse tensors do not have strides.`

I suppose this way is not the optimal, since performing dense matrix operations instead of sparse ones will take more time.

**Comment by rusty1s** [comment]
Yeah, this is exactly what I meant to wrote down. Closing this for now. If i can think of a better idea, I will reopen this issue.

**Comment by dskoda** [comment]
Right, thanks a lot!

**Comment by A11en0** [comment]
hi, about using the sparse tensor for matmul, did you even thought a better choice?

**Comment by rusty1s** [comment]
Can you clarify what you mean? As of now, utilizing `to_dense_batch` is probably the better one:
```python
z, mask = to_dense_batch(z, batch)
z @ z.transpose(1, 2)
```

**Comment by A11en0** [comment]
I mean wether `torch.matmul(assignment, assignment.t())` can be using a sparse matrix instead?

**Comment by rusty1s** [comment]
Yes, that should be possible. If using `SparseTensor` from `torch-sparse`, you need to write
```
assignment @ assignment.t()
```
though.

**Comment by johnnytam100** [comment]
Hi Matthias, I am testing your implementation of mini-batches and would like to know how to prepare `data.batch`, that I tried:

```
from torch_scatter import scatter_mean
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

for data in loader:
  
    row = torch.arange(0, data.num_nodes, dtype=torch.long)
    col = data.batch
    index = torch.stack([row, col], dim=0)
    value = Z.new_ones(data.num_nodes)
    size = torch.Size([data.num_nodes, data.batch[-1].item() + 1]) # added one to the index of last batch
    assignment = torch.sparse_coo_tensor(index, value, size).to_dense() # converted sparse matrix to dense

    mask = torch.matmul(assignment, assignment.t())

    out = torch.matmul(Z, Z.t())
    out = out * mask # masking with element-wise multiplication
```

but got:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-71-6231971f6068>](https://localhost:8080/#) in <module>()
     18 
     19     out = torch.matmul(Z, Z.t())
---> 20     out = out * mask # masking with element-wise multiplication

RuntimeError: The size of tensor a (3327) must match the size of tensor b (1034) at non-singleton dimension 1
```

I will be grateful if you can demonstrate how to arrive at `data.batch` with the `ENZYMES` dataset?
Thanks in advance! ^__^

**Comment by rusty1s** [comment]
Since this is a pretty old issue, there now exists a better way to do this via `to_dense_batch`:
```python
Z = ...  # [num_nodes, num_features]
Z, mask = to_dense_batch(Z, data.batch)
adj = Z @ Z.transpose(1, 2)
```
Let me know if this works for you.

**Comment by JhngirKhn** [comment]
Hello Sir,
I hope everyone is doing well.
I have designed the Encoder part of VGAE for my model in a certain way. Could you please suggest how I can design the inner product decoder for this?

class Encoder(torch.nn.Module):
    def __init__(self,Drug_features=78, dropout=0.1, output_dim = 128):
        super(Encoder, self).__init__()
        self.conv1 = GCNConv(Drug_features, Drug_features * 2)
        self.conv2 = GCNConv(Drug_features * 2, Drug_features * 4)
        self.mu = GCNConv(Drug_features * 4, Drug_features * 4)
        self.logvar = GCNConv(Drug_features * 4, Drug_features * 4)
        self.fc_g1 = torch.nn.Linear(Drug_features * 4, 1024)
        self.fc_g2 = torch.nn.Linear(1024, output_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(dropout)
    
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        z = mu + eps * std
        return z

    def forward(self, data):
       x, edge_index, batch = data.x, data.edge_index, data.batch
       x = self.conv1(x, edge_index)
       x = self.relu(x)
       actual = self.conv2(x, edge_index)
       x = self.relu(actual)
       mu = self.mu(x, edge_index)
       logvar = self.logvar(x, edge_index)
       x1 = self.reparameterize(mu, logvar)
       x2 = gmp(actual, batch)  
       x2 = self.fc_g1(x2)
       x2 = self.relu(x2)
       x2 = self.dropout(x2)
       fc = self.fc_g2(x2)
       return x1, mu, logvar, fc
       
Thank you

**Comment by rusty1s** [comment]
The inner product decoder would need to map batch-wise node features to a dense adjacency matrix representation. This would look similar to
```python
x_dense, mask = to_dense_batch(x, batch)

adj = x_dense @ x_dense.transpose(1, 2)
```

**Comment by JhngirKhn** [comment]
Sir, could you please verify this?

class Decoder(nn.Module):
    def __init__(self, input_dim):
        super(Decoder, self).__init__()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x, batch):
        # Convert to dense batch representation
        x_dense, mask = to_dense_batch(x, batch)
        # Calculate adjacency matrix
        adj = torch.matmul(x_dense, x_dense.transpose(1, 2))
        # Apply sigmoid activation to get adjacency probabilities
        adj_prob = self.sigmoid(adj)
        return adj_prob

**Comment by JhngirKhn** [comment]
Additionally, I obtained the adjacency information using the following method

def smile_to_graph(smile):
    mol = Chem.MolFromSmiles(smile)
    
    c_size = mol.GetNumAtoms()
    
    features = []
    for atom in mol.GetAtoms():
        feature = atom_features(atom)
        features.append(feature / sum(feature))

    edges = []
    for bond in mol.GetBonds():
        edge_feats = bond_features(bond)
        edges.append((bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), {'edge_feats': edge_feats}))
        
    g = nx.Graph()
    g.add_edges_from(edges)
    g = g.to_directed()
    edge_index = []
    edge_feats = []
    for e1, e2, feats in g.edges(data=True):
        edge_index.append([e1, e2])
        edge_feats.append(feats['edge_feats'])
        
    return c_size, features, edge_index, edge_feats

**Comment by rusty1s** [comment]
I think this looks pretty good :)

**Comment by JhngirKhn** [comment]
But sir when i run its give me this error 

  File "/googledrive/My Drive/colabdrive/root/.local/share/code-server/experiments/VGAE_exp/training.py", line 196, in <module>
    experiment(FLAGS)
  File "/googledrive/My Drive/colabdrive/root/.local/share/code-server/experiments/VGAE_exp/training.py", line 154, in experiment
    model = train(model, device, train_loader, optimizer, mse_f, epoch, train_data, FLAGS)
  File "/googledrive/My Drive/colabdrive/root/.local/share/code-server/experiments/VGAE_exp/training.py", line 43, in train
    loss = loss_f(x, x_hat, mu, log_var)
  File "/googledrive/My Drive/colabdrive/root/.local/share/code-server/experiments/VGAE_exp/training.py", line 20, in loss_f
    recon_loss = F.mse_loss(x_hat, x, reduction='mean')
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3294, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.10/dist-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (46) must match the size of tensor b (94) at non-singleton dimension 2

**Comment by rusty1s** [comment]
You need to convert your original adjacency matrix to a dense one, e.g., via `to_dense_adj` from `torch_geometric.utils`. Then you can do binary cross entropy on top.

**Comment by JhngirKhn** [comment]
yes sir i did

**Comment by JhngirKhn** [comment]
Thank you sir 
However, now it completes only 3 or 4 epochs before encountering the size mismatch error once more

Epoch 1: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 193/193 [00:45<00:00,  4.23it/s, MSE=1.12, Train_cindex=0.564, loss=10.1]
Epoch 2: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 193/193 [00:35<00:00,  5.49it/s, MSE=0.962, Train_cindex=0.573, loss=2.78]
Epoch 3: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 193/193 [00:35<00:00,  5.39it/s, MSE=0.859, Train_cindex=0.585, loss=2.76]
Epoch 4:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 191/193 [00:35<00:00,  5.32it/s, MSE=0.929, Train_cindex=0.561, loss=2.75]
Traceback (most recent call last):
  File "training.py", line 210, in <module>
    experiment(FLAGS)
  File "training.py", line 165, in experiment
    model = train(model, device, train_loader, optimizer, mse_f, epoch, train_data, FLAGS)
  File "training.py", line 46, in train
    loss = loss_f(adj_matrix, x_hat, mu, log_var)
  File "training.py", line 22, in loss_f
    recon_loss = F.binary_cross_entropy(x_hat, x, reduction='mean')
  File "/home/shah/GraphDTA-master2/env/lib/python3.8/site-packages/torch/nn/functional.py", line 3074, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([14155, 14155])) that is different to the input size (torch.Size([14156, 14156])) is deprecated. Please ensure they have the same size.

**Comment by rusty1s** [comment]
This seems to be an issue with isolated nodes potentially. You may be able to fix this by passing `max_num_nodes` to `to_dense_adj`.
