### ISSUE TITLE
Citeseer dataset isolated nodes

### ISSUE THREAD

**Issue by indritnallbani** [rusty1s/pytorch_geometric#1700]
Hello,  thank you for your hard work.
In the citeseer dataset, we have some isolated nodes. This creates a problem when splitting the dataset and sometimes result in dataset size mismatch. Is there any method available to fix those self-isolated nodes?
In Kipf's code, he manually fixes them when loading the datasets but since I use the Planetoid data loader, I don't know how to fix it.

Thank you.

From Kipf's loading code:

if dataset == 'citeseer':
        # Fix citeseer dataset (there are some isolated nodes in the graph)
        # Find isolated nodes, add them as zero-vecs into the right position
        test_idx_range_full = range(
            min(test_idx_reorder), max(test_idx_reorder) + 1)
        tx_extended = sp.lil_matrix((len(test_idx_range_full), x.shape[1]))
        tx_extended[test_idx_range - min(test_idx_range), :] = tx
        tx = tx_extended

**Comment by fansariadeh** [comment]
> Can you elaborate on what's the problem when splitting your dataset? This shouldn't be a problem at all.

Hi there! 
I am going to run Citeseer as Kipf mentioned in his papaer. 
I have not the code snnipet for fixing the issue of isolated nodes. Could you please share it with me? I also have issue with running this for Nell dataset. Could you please share the code for this? Many tnax... I am struggling for two months for now.

**Comment by fansariadeh** [comment]
> Hello, thank you for your hard work.
> In the citeseer dataset, we have some isolated nodes. This creates a problem when splitting the dataset and sometimes result in dataset size mismatch. Is there any method available to fix those self-isolated nodes?
> In Kipf's code, he manually fixes them when loading the datasets but since I use the Planetoid data loader, I don't know how to fix it.
> 
> Thank you.
> 
> From Kipf's loading code:
> 
> if dataset == 'citeseer':
> # Fix citeseer dataset (there are some isolated nodes in the graph)
> # Find isolated nodes, add them as zero-vecs into the right position
> test_idx_range_full = range(
> min(test_idx_reorder), max(test_idx_reorder) + 1)
> tx_extended = sp.lil_matrix((len(test_idx_range_full), x.shape[1]))
> tx_extended[test_idx_range - min(test_idx_range), :] = tx
> tx = tx_extended

Hi... 
I am so happy seeing this question! I am also tryinh to implement pygcn for citeseer and nell dataset but what Kipf has provided in hid Github is not working. Can you please give me a hand in this? Cheers!

**Comment by rusty1s** [comment]
You can find the same pre-processing technique as in `tkipf/gcn` [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/io/planetoid.py#L25-L36).

**Comment by fansariadeh** [comment]
> You can find the same pre-processing technique as in `tkipf/gcn` [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/io/planetoid.py#L25-L36).

But this part does not fit in pytorch implementation of Kipf paper. I was wondering how we can work with isolated nodes in pygcn. Do you have the code that Nell dataset works for? Please share it with me I had a couple months of struggling...

**Comment by fansariadeh** [comment]
> You can find the same pre-processing technique as in `tkipf/gcn` [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/io/planetoid.py#L25-L3The issue is that here the data set is allx, tx, x,... I am working with citeseer.cites and citeseer.content. Do you have any idea?

**Comment by rusty1s** [comment]
I'm not sure what you are trying to do. What is the exact problem with reading `citeseer.cites` and `citeseer.content`?
If you want to run `tkipf/pygcn` with CiteSeer, it's also maybe a good idea to ask for help there.
