### ISSUE TITLE
Defining a propagate_type on Data objects for transforming a metamodel to TorchScrip

### ISSUE THREAD

**Issue by jahawk** [rusty1s/pytorch_geometric#1701]
## ❓ Questions & Help
Hi,

I've been testing the library to implement a meta-model capable of learning on time&space dependent data. I used the ARMAConv network to create my layers and for the input of my meta model I create a Data object (from torch_geometric.data import Data) to represent a Mesh = Graph coordinates+Graph connectivity+fields. So the forward would look like "def forward(self,Mesh):"

It works pretty well in CPU and GPU, now I'm trying to use JIT to converte the model into a TorchScript to test the performance gains.

In the examples on how to transform the scripts ( https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html?highlight=jit#converting-gnn-models ) it is shown how to proceed in case the inputs are for instance (x: Tensor, edge_index: Tensor). Would it be possible to also state a propagate_type on a Data object that contains the Tensors?

Thanks in advance!

**Comment by rusty1s** [comment]
This is not yet possible since the JIT support for custom classes is still rather limited. You may get around this problem by converting your `data` object into a `NamedTuple`.

**Comment by jahawk** [comment]
Hi @rusty1s Thanks for the advise! 

I tried using the namedtuples as you suggested, while it compiles the problem I found is that by using namedtuples I lost the possibility of modifying the tensors afterwards

So I tried a different approach by creating an object as follows:

# Dummy object
from torch import Tensor
class MyTorchMesh():
       def __init__(self,x: Tensor, edge_index: Tensor):
               self.x = x
               self.edge_index = edge_index

from where it is possible then the redefine the forward pass as:

def forward(self, Mesh: MyTorchMesh ) -> Tensor:
     x = Mesh.x
     edge_index = Mesh.edge_index 
     # propagate_type: (x: Tensor, edge_index: Tensor )

This will compile using torch.jit.script() and also enables the possibility of modifying the tensors if needed

Thanks again!
