### ISSUE TITLE
ToSparseTensor for custom Dataset?

### ISSUE THREAD

**Issue by pohjie** [rusty1s/pytorch_geometric#1706]
## ❓ Questions & Help

Hello, the example in the documentation for `ToSparseTensor` currently uses data from torch_geometric.datasets, which has the parameter `transform`

May I know how should I get a sparse tensor if the code for the dataset is implemented as:
```
GCNData_pro = DATA.Data(x=torch.Tensor(target_features),
                                     edge_index=torch.LongTensor(target_edge_index).transpose(1, 0),
                                     y=torch.FloatTensor([labels]))
```
where DATA is `from torch_geometric import data as DATA`.
Thank you!

**Comment by rusty1s** [comment]
```python
import torch_geometric.transform as T

data = T.ToSparseTensor()(data)
```

**Comment by pohjie** [comment]
It's working, thanks so much for the awesome work and fast response.
