### ISSUE TITLE
cannot import name 'GatedGraphConv' from 'torch_geometric.nn'

### ISSUE THREAD

**Issue by MaeThird** [rusty1s/pytorch_geometric#171]
## Environment

* OS:Linux-5.0.3-arch1-1-ARCH
* Python version:3.7
* PyTorch version:1.1.0a0+a4f83ff
* CUDA/cuDNN version:10.0.130/7.0
* GCC version:8.2.1
* How you tried to install PyTorch Geometric and its extensions (pip, source):both
* Any other relevant information:

## Checklist

- [Y ] I followed the installation guide.
- [ Y] I cannot find my error message in the FAQ.
- [ Y] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ Y] I have cloned the repository and tried a manual installation from source.
- [ N] I do have multiple CUDA versions on my machine.
- [ N] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

import torch
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from torch_geometric.nn import GatedGraphConv

It can import GATConv but not GatedGraphConv which said **ImportError: cannot import name 'GatedGraphConv' from 'torch_geometric.nn' (/usr/lib/python3.7/site-packages/torch_geometric/nn/__init__.py)**
I tried install it from pip and source.

**Comment by rusty1s** [comment]
Hi,
This seems kinda weird. Are you sure python does not refer to the pip installation (there is no `GatedGraphConv` in the version of pip yet) of refering to the installation from source? You can verify this by checking if
```
/usr/lib/python3.7/site-packages/torch_geometric/nn/conv/gated_graph_conv.py
```
exists. When installing from source, first ensure that PyG has been uninstalled:
```
pip uninstall torch-geometric
```

**Comment by MaeThird** [comment]
Hi,`/usr/lib/python3.7/site-packages/torch_geometric/nn/conv/gated_graph_conv.py` doesn't exist on the disk. Thanks for your hard working.Waiting for your new version.

**Comment by rusty1s** [comment]
You can alternatively clone the repo and install from source.

**Comment by rusty1s** [comment]
PyG `1.1.0` just released.
