### ISSUE TITLE
Dataset not found [Reddit and PPI]

### ISSUE THREAD

**Issue by snash4** [rusty1s/pytorch_geometric#1720]
Hi, 
 The dataset for cluster examples (cluster_gcn_reddit.py and cluster_gcn_PPI.py) throws "HTTP Error 404: Not Found"
For reddit, it tries to download from
Downloading https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/reddit.zip
Has the dataset moved, or I am doing something wrong?
Thanks.

**Comment by rusty1s** [comment]
This is now fixed in master. You can simply re-install via:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
Thanks for reporting!

**Comment by snash4** [comment]
this give following error:
_ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall_

**Comment by rusty1s** [comment]
Mh, that's interesting, and I believe it has something do to with `numba`. Can you please try again?

**Comment by snash4** [comment]
it works, thanks
