### ISSUE TITLE
Metis [segmentation Fault on ClusterData ]

### ISSUE THREAD

**Issue by snash4** [rusty1s/pytorch_geometric#1721]
Hello, 
 I am creating a data object like this:
data = Data()
data.edge_index = data.train_edges
and clustering it as:
cluster_data = ClusterData(datacluster, num_parts=4, recursive=False, save_dir=None)

I get a segmentation fault. 
I am running my code with these libarires:
torch                              1.5.0
torch-cluster                      1.5.7
torch-geometric                    1.5.0
torch-scatter                      2.0.5
torch-sparse                       0.6.7
torch-spline-conv                  1.2.0
torchvision                        0.7.0

However, I run the same code snippet on pytorch_geometric 1.6.1. It runs without any problems.

But, due to limitations, I can't run the code on the latest PyTorch geometric.

Please, point to me where I am doing wrong.

Thanks.

**Comment by rusty1s** [comment]
Can you try to make your graph undirected and see if that fixes the issue?

**Comment by snash4** [comment]
Making it undirected works

Thanks Matthais.
