### ISSUE TITLE
C/C++ of pytorch_geometric

### ISSUE THREAD

**Issue by ihmc3jn09hk** [rusty1s/pytorch_geometric#1724]
## ❓ Questions & Help

Hi, pytorch_geometric has rich features related to geometric processing. Yet I couldn't find the C/C++ part in the repository. Someone please share the link/reference for the C/C++ examples of pytorch_geometric ?

**Comment by rusty1s** [comment]
There are no C++ examples of PyTorch Geometric. PyG is purely Python-based. Nonetheless, with release 1.6.0, we support TorchScript, which should help you to run your models in non-Python environments. You can find some basic examples [here](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/jit) and a short tutorial [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html).

**Comment by ihmc3jn09hk** [comment]
> There are no C++ examples of PyTorch Geometric. PyG is purely Python-based. Nonetheless, with release 1.6.0, we support TorchScript, which should help you to run your models in non-Python environments. You can find some basic examples [here](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/jit) and a short tutorial [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html).

Thanks @rusty1s  for the reply. I am sorry that C/C++ is not an option here.

**Comment by ihmc3jn09hk** [comment]
Hi @rusty1s , I recognized there is a [repo.](https://github.com/rusty1s/pytorch_cluster) from you which is based on C/C++. I would like to reimplement the "pointnet2", e.g. [the classification ](https://github.com/rusty1s/pytorch_geometric/blob/c56a50eb2f17a41c4b52d837eb66a44d8efbfee5/examples/pointnet2_classification.py#L12) and [segmentation](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py) examples in C/C++. Could you please kindly share with me the extra C/C++ modules in torch_geometric I would need to do it?

**Comment by rusty1s** [comment]
You would need to implement the `PointConv` via `scatter_max` from the `torch-scatter` package. Everything else can be implemented via `torchlib` and `torch-cluster`.

**Comment by ihmc3jn09hk** [comment]
@rusty1s Thx for the advices.
