### ISSUE TITLE
Handling a graph with global property

### ISSUE THREAD

**Issue by Junyoungpark** [rusty1s/pytorch_geometric#173]
## ❓ Questions & Help

Hi! 
I'm wondering whether I can transform graph data with global property in Data object.
For instance, the meta layer implemented in 'torch_geometric.nn' employs graph level property to process graph data. However, I can't find a way for packing the global properties of graphs in Data object.

thanks :+1:

**Comment by rusty1s** [comment]
Simply add your global data properties to your data object, e.g.:
```
data.u = torch.randn(1, 64)
```

**Comment by Junyoungpark** [comment]
That's awesome!

**Comment by Junyoungpark** [comment]
> Simply add your global data properties to your data object, e.g.:
> 
> ```
> data.u = torch.randn(1, 64)
> ```

Is these approach fully compatible with the custom dataset?

**Comment by Junyoungpark** [comment]
> > Simply add your global data properties to your data object, e.g.:
> > ```
> > data.u = torch.randn(1, 64)
> > ```
> 
> Is these approach fully compatible with the custom dataset?

self-reply: It seems so

**Comment by rusty1s** [comment]
Yes :)
