### ISSUE TITLE
Concatenation as aggregation function?

### ISSUE THREAD

**Issue by dvirginz** [rusty1s/pytorch_geometric#1734]
I understand that as most graphs have a varying number of neighbors for each vertex, one can't expect to have concatenation as the aggregation function.
But, If we assume that all graph nodes have exactly k edges (e.g as in the case of `dynamicedgeconv`), can I somehow use `edge_index` and the output of the `propagate` function to create a new feature vector where
```
x.shape V,F
edge_index.shape 2,E (assume all nodes have k neighs)
conv.propagate(x,edge_index).shape V,F,K
```
Any solution or direction would be super helpful. Thanks:)

**Comment by rusty1s** [comment]
Yes, given that our edge indices are sorted based on destination nodes, you can define a custom aggregation function via `aggregate`, *e.g.*:
```python
def aggregate(self, inputs):  # [num_edges, num_features]
    # Reshape to [num_nodes, k, num_features]
    inputs = inputs.view(-1, k, inputs.size(-1))
    ...
```

**Comment by dvirginz** [comment]
@rusty1s you are something special:)
