### ISSUE TITLE
torch.jit.frontend.NotSupportedError  when creating jittable GNN operators（message passing）

### ISSUE THREAD

**Issue by jnyuan** [rusty1s/pytorch_geometric#1745]
## ❓ Questions & Help

I followed the docs/TorchScript Support to convert the model to Torchscript model. 
It raised an error as follows,
compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
File ".\torch_geometric\nn\conv\message_passing.py", line 186
   def propagate(self, edge_index: Adj, size: Size=None, **kwargs):
                                                                                       ~~~~~~~~<----HERE
My code:
class GraphLayer(MessagePassing):
propagate_type = {'x': Tensor}
def foward(self, x: Tensor, edge_index: Tensor) -> Tensor:
       x: Tensor = self.mlp(x)
      return self.propagate(edge_index, x=x, size=(x.size(0),x.size(0)))

Environment:
pytorch 1.6.0
torch_geometric 1.6.1

How can I solve this problem without modifying "message_passing.py"?

**Comment by jnyuan** [comment]
I have solved the aboved mentioned problem. I can convert a GNN operator to jittable operator.
I used the  GNN operator as a layer in another torch.nn model and want to convert the model into torchscript model.
However, it raised a RuntimeError: 
forward(__torch__.GraphLayerPropJittable_a5efec.GraphLayerPropJittable_a5efec self, Tensor x, Tensor edge_index) -> (Tensor):
Argument edge_index not provided.
Code: 
x: Tensor = layer(x, edge_index)

**Comment by rusty1s** [comment]
Can you show me an example to reproduce?

**Comment by jnyuan** [comment]
from torch_geometric.data import Data
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch_geometric.nn import MessagePassing, max_pool
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pdb
import os
from torch import Tensor


class SubGraph(nn.Module):
    """
    Subgraph that computes all vectors in a polyline, and get a polyline-level feature
    """

    def __init__(self, in_channels, num_subgraph_layres=3, hidden_unit=64):
        super(SubGraph, self).__init__()
        self.num_subgraph_layres = num_subgraph_layres
        self.layer_seq = nn.Sequential()
        for i in range(num_subgraph_layres):
            t1='(Tensor,Tensor)->Tensor'
            self.layer_seq.add_module(
                f'glp_{i}', GraphLayerProp(in_channels, hidden_unit).jittable(t1))
            in_channels *= 2

    def forward(self, sub_data: Data)->Tensor:
        """
        polyline vector set in torch_geometric.data.Data format
        args:
            sub_data (Data): [x, y, cluster, edge_index, valid_len]
        """
        x: Tensor= sub_data.x
        edge_index: Tensor = sub_data.edge_index
        for name, layer in self.layer_seq.named_modules():
            if isinstance(layer, GraphLayerProp):
                x = layer(x, edge_index)
        sub_data.x = x
        out_data = max_pool(sub_data.cluster, sub_data)
        # try:
        assert out_data.x.shape[0] % int(sub_data.time_step_len[0]) == 0
        # except:
            # from pdb import set_trace; set_trace()
        out_data.x = out_data.x / out_data.x.norm(dim=0)
        return out_data

        # node_feature, _ = torch.max(x, dim=0)
        # # l2 noramlize node_feature before feed it to global graph
        # node_feature = node_feature / node_feature.norm(dim=0)
        # return node_feature

# %%


class GraphLayerProp(MessagePassing):
    """
    Message Passing mechanism for infomation aggregation
    """

    propagate_type={'x':Tensor}

    def __init__(self, in_channels:int, hidden_unit:int=64, verbose:bool=False):
        super(GraphLayerProp, self).__init__(
            aggr='max')  # MaxPooling aggragation
        self.verbose = verbose
        self.mlp = nn.Sequential(
            nn.Linear(in_channels, hidden_unit),
            nn.LayerNorm(hidden_unit),
            nn.ReLU(),
            nn.Linear(hidden_unit, in_channels)
        )

    def forward(self, x: Tensor, edge_index: Tensor)->Tensor:
        if self.verbose:
            print(f'x before mlp: {x}')
        x: Tensor = self.mlp(x)
        if self.verbose:
            print(f"x after mlp: {x}")
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j: Tensor)->Tensor:
        return x_j

    def update(self, aggr_out, x:Tensor)->Tensor:
        if self.verbose:
            print(f"x after mlp: {x}")
            print(f"aggr_out: {aggr_out}")
        return torch.cat([x, aggr_out], dim=1)


if __name__ == "__main__":
    data = Data(x=torch.tensor([[1.0], [7.0]]), edge_index=torch.tensor([[0, 1], [1, 0]]))
    print(data)
    layer = GraphLayerProp(1, 1, True)
    for k, v in layer.state_dict().items():
        if k.endswith('weight'):
            v[:] = torch.tensor([[1.0]])
        elif k.endswith('bias'):
            v[:] = torch.tensor([1.0])
    y = layer(data.x, data.edge_index)

    model=SubGraph(6,1,10)
    jit_model=torch.jit.script(model)

**Comment by rusty1s** [comment]
I identified two issues:
1. You cannot pass `data` to the GNN `forward` since `data` is not jittable. You need to pass the used tensors individually, *e.g.*:
```python
def forward(self, x: Tensor, edge_index: Tensor):
     ...
```
2. It looks like `Sequential` makes some problems here. The code runs through if I replace `Sequential` with `ModuleList`, *e.g.*:
```python
self.layer_seq = nn.ModuleList()
        for i in range(num_subgraph_layres):
            t1='(Tensor,Tensor)->Tensor'
            self.layer_seq.add_module(
                GraphLayerProp(in_channels, hidden_unit).jittable(t1))

for  layer in self.layer_seq:
        x = layer(x, edge_index)
```

**Comment by jnyuan** [comment]
The model can be successfully converted to a torchscript model. 
Thank you very much for taking the time to help me solve the problem! ^_^

**Comment by rotk27** [comment]
Hi, @jnyuan , Finally, how you solved this problem? I tried the 2 methods above, but still cant' solve it.

**Comment by rusty1s** [comment]
What's the issue you are experiencing? Do you have a minimal example to reproduce?

**Comment by rotk27** [comment]
Hi！Thanks, I used the same code as above! I have replaced Sequential with ModuleList. For the first issue you mentioned, since data is not jittable, I passed the used tensors individually, but  when u see the code, it used Maxpool which must need data to pass into, so what can I do? Thanks so much
<img width="391" alt="image" src="https://user-images.githubusercontent.com/101614871/158540033-f25c33dd-6614-4bc8-8bc7-15bb5ac0cf26.png">

**Comment by rusty1s** [comment]
I see. `max_pool` is indeed not jittable at the moment since it TorchScript cannot handle our custom `data` type. A simple workaround is to implement [`max_pool`](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/pool/max_pool.py#L47-L79) by yourself which expects tensors as input rather than a single `data` object (and returns a tuple of tensors as output rather than a modified `data` object).

**Comment by vietanh-tran** [comment]
> I have solved the aboved mentioned problem. I can convert a GNN operator to jittable operator. 

I am running into the same problem that you had. Would it be possible for you to show how you solved it?
