### ISSUE TITLE
assert value.device == col.device Assertion Error

### ISSUE THREAD

**Issue by netphantom** [rusty1s/pytorch_geometric#1748]
## 🐛 Bug

I have this error when I try to create a subgraph_loader object from the NeigborSampler class. The interpreter raises this error when I run it on a GPU (CUDA), while on CPU I don't get this error. 
It happens with different graphs, not only the one reported below.

## To Reproduce

The error is raised when:
```python
from torch_geometric.data import Data, NeighborSampler
subgraph_loader = NeighborSampler(self.data.edge_index, sizes=[-1], shuffle=False, num_workers=12, batch_size=1024)
```
Where `self.data.edge_index` is a  `tensor([[    0,     0,     0,  ..., 10232, 10232, 10233], [    1,     2,     3,  ..., 10229, 10231,  9217]], device='cuda:0')`

It raises this error:
```
  File "/home/netphantom/graphnn/graphnn/py_geom/trainers.py", line 57, in __init__
    subgraph_loader = NeighborSampler(self.data.edge_index, sizes=[-1], shuffle=False, num_workers=12,
  File "/home/netphantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/data/sampler.py", line 82, in __init__
    adj = SparseTensor(row=edge_index[0], col=edge_index[1],
  File "/home/netphantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_sparse/tensor.py", line 20, in __init__
    self.storage = SparseStorage(row=row, rowptr=rowptr, col=col,
  File "/home/netphantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_sparse/storage.py", line 78, in __init__
    assert value.device == col.device
AssertionError
```

## Expected behavior

The creation of an istance of NeigbhorSampler on CUDA

## Environment

* OS: Linux
* Python version: 3.8
* PyTorch version: 1.6
* CUDA/cuDNN version: 10.1

**Comment by netphantom** [comment]
I think that the error could be in the line
`edge_attr = torch.arange(edge_index.size(1))` of `NeighborSampler` because in the next line 
```
adj = SparseTensor(row=edge_index[0], col=edge_index[1],
                           value=edge_attr, sparse_sizes=(N, N),
                           is_sorted=False)
```
edge_index is on CUDA while edge_attr is on CPU

**Comment by rusty1s** [comment]
The `NeighborSampler` expects `edge_index` to be a CPU tensor, I will try to make that more clear.

**Comment by netphantom** [comment]
Thank you for the answer, so I just passed the tensor to `NeighborSampler` like `self.data.edge_index.to("cpu")`
