### ISSUE TITLE
Question about triplets() function in DimeNet 

### ISSUE THREAD

**Issue by tuanle618** [rusty1s/pytorch_geometric#1749]
Dear @rusty1s , thank you very much for the implementation of DimeNet. 
I am currently trying to implement a directional message passing network, similar to DimeNet, but less complex.
Could you elaborate on the triplets() class function within DimeNet? Particularly
https://github.com/rusty1s/pytorch_geometric/blob/caf5f57bf10f9b697b418ea7ec50594ee7a21b73/torch_geometric/nn/models/dimenet.py#L413-L433

I assume `col` to be the target index, `row` the source index. In my case, I want the (directional) MPNN to propagate directed messages `m_ji` from source node `j` to target node `i`.
To compute the aggregated message `m_ji`, I first need to aggregate the (hidden) edge-states `h_kj` from all nodes `k` that are connected to `j` except for the target node `i`, resulting to equation (1) : `m_ji = \sum_{k \in N(j) \  i} h_kj`. (similar to the network introduced in https://pubs.acs.org/doi/pdf/10.1021/acs.jcim.9b00237). 
So I was wondering what exactly the `triplets()` function is returning, as I need those indices latter, to call the `torch_scatter.scatter` function to aggregated tensors. 

What I don't understand are the indices `idx_kj` and `idx_ji` which I need for the scattering operation.
Namely gathering all hidden edge-states from `k->j` as done in equation (1) and then later updating

So far, in my implementation I used the code snippet you provided.
Now in DimeNet, one copies the messages from sources and targets, by selecting the `col`and `row`, resulting into a tensor of len(num_edges) 
Lets say I have hidden (edge-embeddings)
`h_ji`, which are similarly created as done in the `EmbeddingBlock`, by concatenating
`[x_j, x_i, e_ji]`, where `x_j,i` are the corresponding node features and `e_ji` is the edge-attribute, and then transforming that concatenation with any neural network.
https://github.com/rusty1s/pytorch_geometric/blob/caf5f57bf10f9b697b418ea7ec50594ee7a21b73/torch_geometric/nn/models/dimenet.py#L137 

Within the `InteractionBlock`, the tensors are copied/selected based on `idx_kj`
https://github.com/rusty1s/pytorch_geometric/blob/caf5f57bf10f9b697b418ea7ec50594ee7a21b73/torch_geometric/nn/models/dimenet.py#L208-L209
and then sum-scattered based on the `idx_ji`indices.

Maybe you could help me understanding the indices `idx_ji` and `idx_kj` better, as the length of those vectors, are also longer than the number of edges, i.e. `len(idx_ji) > len(edge_index)`

Thanks in advance!

**Comment by rusty1s** [comment]
I agree. `triplets` is far from easy to understand. I created a simple example that should make things more clear:
```
row tensor([0, 0, 1, 1, 2, 2])
col tensor([1, 2, 0, 2, 0, 1])

idx_i tensor([1, 2, 0, 2, 0, 1])
idx_j tensor([0, 0, 1, 1, 2, 2])
idx_k tensor([2, 1, 2, 0, 1, 0])

idx_kj tensor([4, 2, 5, 0, 3, 1])
idx_ji tensor([0, 1, 2, 3, 4, 5])

```
As one can see, `(idx_i, idx_j, idx_k)` defines all possible triplets in the graph. `idx_kj` and `idx_ji` denote, for each pair in `(idx_k, idx_j)` and `(idx_j, idx_i)` respectively, the original index in `(row, col)`. For example, the first pair in `(idx_k, idx_j)` is `(2, 0)`, which corresponds to the fourth entry in `(row, col)`.

**Comment by tuanle618** [comment]
Awesome, Matthias! Thank you very much for the quick answer and your example. Indeed, starting with a simple graph, often helps to understand it better. I extended your example with an additional node to further confirm and understand the code. Now I see the relationship between the indices `idx_kj` and `idx_ji` to the corresponding triplets `idx_k`, `idx_j`, `idx_i` where `idx_ji` is then needed in the end, to aggregate messages from all `k \in {N(j)\i}` to `j`, to have `m^{t+1}_ji` to update  
`h^{t+1}_ji = U(m^{t+1}_ji, h^{t}_ji)`
```
j (row) -> i (col), aka. the edge_index: 
 tensor([[0, 0, 1, 1, 2, 2, 1, 3],
        [1, 2, 0, 2, 0, 1, 3, 1]])


idx_k:  tensor([2, 1, 2, 3, 0, 3, 1, 0, 0, 2])
idx_j:  tensor([0, 0, 1, 1, 1, 1, 2, 2, 1, 1])
idx_i:  tensor([1, 2, 0, 0, 2, 2, 0, 1, 3, 3])


idx_kj:  tensor([4, 2, 5, 7, 0, 7, 3, 1, 0, 5])
idx_ji:  tensor([0, 1, 2, 2, 3, 3, 4, 5, 6, 6])
```
