### ISSUE TITLE
Handling a grpah with multiple edge types

### ISSUE THREAD

**Issue by Junyoungpark** [rusty1s/pytorch_geometric#175]
## ❓ Questions & Help

Hi.

I'm wondering whether are there any approaches to transform 'mutliDigraph' from networkx to torch_geometric.Data object. 

One possible way would be to concatenating every attribute on multiple edges into one attribute and use Data class. However, it looks quite ugly and not straight forward to get back the original graph.

Thanks in advance.

**Comment by rusty1s** [comment]
Not quite sure I understand your question correctly. `MultiDigraph` can be easily implemented by just stacking them in `edge_index` (and `edge_attr`).

**Comment by Junyoungpark** [comment]
On data processing, I require to differentiate which edge_index dedicates for which types of edges. 
For instance, in some gnn, I want to selectively update the edges which have the first edge type. Can I still use your option? 

And thanks for this awesome library.

**Comment by Junyoungpark** [comment]
> Not quite sure I understand your question correctly. A `MultiDigraph` can be easily implemented by just stacking duplicated edges in `edge_index` (and `edge_attr`).

yes. you did

**Comment by rusty1s** [comment]
Yes, we do this in our `R-GCN` example, where nodes with different edge types are transformed differently.

**Comment by Junyoungpark** [comment]
> Yes, we do this in our `R-GCN` example, where nodes with different edge types are transformed differently.

That's cool. I definitely check the example. Thanks

**Comment by Junyoungpark** [comment]
Sorry for keep bothering. However, I couldn't find the example which use
```python
edge_index  = edge_index[:, edge_type == 0]
```
Also. to me, it is not straightforward how can I pass the 'edge_type' values to `Data` object.

**Comment by rusty1s** [comment]
In the [R-GCN Conv](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/rgcn_conv.py), we pass an `edge_type` LongTensor of shape `[E]` to its `forward` method which indicates the type of each edge. In Column 84, we select the specific weights corresponding to the correct `edge_type`.

**Comment by Junyoungpark** [comment]
I start to fall in love with Pytorch_geometric :p 
Thanks
