### ISSUE TITLE
Use case: CPU at test time and for local development, GPU in production

### ISSUE THREAD

**Issue by kkleidal** [rusty1s/pytorch_geometric#1750]
## ❓ Questions & Help

Thank you for making this package!

In my current use case, I need to be able to run unit tests locally on a CPU-only machine and run production code on a GPU machine. I need to use the same Docker image for both use cases.

I have the GPU-enabled package installed, but when importing on the CPU-only machine I get a DLL loading error:
```
File "/usr/local/lib/python3.6/dist-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.6/dist-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib/python3.6/dist-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory
```

It would be great if the package could fallback to the CPU-compiled instructions if a GPU is not available at runtime, like PyTorch does, for instance.

For now, I've been trying to work around it by installing the CPU packages by default and the GPU packages in a separate directory. At runtime, I dynamically change my `sys.path` to point at the GPU packages if a GPU is present. Even doing that, I run into the problem:
```
File "/usr/local/lib/python3.6/dist-packages/torch_cluster/__init__.py", line 28, in <module>
Detected that PyTorch and torch_cluster were compiled with '
RuntimeError: Detected that PyTorch and torch_cluster were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_cluster has CUDA version 0.0. Please reinstall the torch_cluster that matches your PyTorch install.
```
which I can hack around if I change the `torch_cluster/__init__.py` line 26 to:
```python
if not (major == 0 and minor == 0) and (t_major != major or t_minor != minor):
```
and make a similar change to torch_spline_conv, but I feel like I'm taking the safety rails off by doing that.

Is there any plan to support the use case of having a package that works both on GPU machines and CPU machines without needing to install separate packages? Any suggestions for how to work around my problem, bearing in mind I need to use the same Docker image on both CPU and GPU machines?

Thank you!

**Comment by rusty1s** [comment]
That's an interesting suggestion. I will look into it, but I'm actually not sure if that is possible at all. `torch-sparse` will always look for `libcusparse` in case it is installed with CUDA support, see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/setup.py#L42-L45).

An alternative to modifying `__init__.py` directly would be to install both CPU und CUDA `torch` packages (just as you do with the external packages).

**Comment by kkleidal** [comment]
Thanks! I was thinking a patch like this might do the trick, where we build all the extensions, but with `_gpu` and `_cpu` suffixes on the name. Then at runtime, we can choose which ones to load. I'm happy to make PRs to the relevant repos, if you'd like. I have a patch ready for `pytorch_scatter` and `pytorch_sparse` already, and unit tests seem to be passing for me locally.

**Comment by kkleidal** [comment]
Whoops, forgot to link the patch: https://github.com/kkleidal/pytorch_scatter/commit/cb07dba18d44348220cd3ef806c4b77243a61086

**Comment by kkleidal** [comment]
- https://github.com/kkleidal/pytorch_cluster/commit/80d844949075a9a898eacaf0b8dedd5a88008f83
- https://github.com/kkleidal/pytorch_spline_conv/commit/a63da521d5a853f4ce0e487c3b44660970ae3320
- https://github.com/kkleidal/pytorch_sparse/commit/dca4827b0b6f90675922d00c77139c6bc11b091f
- https://github.com/kkleidal/pytorch_scatter/commit/cb07dba18d44348220cd3ef806c4b77243a61086

I'm happy to make MRs if you think this approach would work! Unit tests seem to be passing for those repos. I'm still testing out how it works with pytorch_geometric.

**Comment by rusty1s** [comment]
Thanks for digging in. This looks pretty good. However, it looks like it requires to build the extensions twice, leading to increased build times. Is that correct?

**Comment by kkleidal** [comment]
Yes, that’s correct.

For my use case, that’s a fine tradeoff because I can just build the wheels once.

Do you think the longer build times would be a problem?

**Comment by rusty1s** [comment]
I personally would like to avoid that, since build times are already quite long. Not sure if there is a solution to your problem that avoids this though.

**Comment by kkleidal** [comment]
For users of the published wheels, it's not really a factor. Are you concerned about development velocity? Maybe we could add an option to disable building the CPU binaries when building GPU binaries, to speed things up for development. I do think having the CPU binaries packaged with the GPU binaries is the right way to approach my use case, and is consistent with other ML packages.

Also, I didn't look too closely, but if any of the extensions don't require the GPU flags to run on GPU (i.e. ones that are written in C++, not CUDA), we could build common versions of them rather than build them twice. I was just trying to keep the diffs simple to convey the idea.

**Comment by kkleidal** [comment]
Bump. I have the code ready to go. We've been maintaining our own forks of your 5 repos for a month now, and would very much like to merge upstream to avoid that maintenance cost. I could see running GNN models on either CPU or GPU using the same docker image being a very useful feature for people.

**Comment by rusty1s** [comment]
Sorry for late reply and thanks for the reminder. Can you send a PR to `torch-scatter` with the applied changes?

**Comment by kkleidal** [comment]
No worries! Thanks for the quick response. Here is a PR: https://github.com/rusty1s/pytorch_scatter/pull/180

**Comment by kkleidal** [comment]
Fixed in https://github.com/rusty1s/pytorch_scatter/pull/180 . Thank you!
