### ISSUE TITLE
Cuda 11 and RTX 30 Series GPU Support

### ISSUE THREAD

**Issue by johnny12150** [rusty1s/pytorch_geometric#1758]
## ❓ Questions & Help

Is there going to be a new version that supports Cuda 11 above and RTX 30 Series GPUs soon?

**Comment by rusty1s** [comment]
CUDA 11 should be supported when manually installing from source. We will officially support it once PyTorch 1.7.0 lands.

**Comment by aluo-x** [comment]
Should be any day now. For some reason I seem to have errors with using `.jit` when combined with forward/dataparallel, same network with conv2d doesn't fail :/ Hopefully python 1.7.0 fixes this.

**Comment by kunshouout** [comment]
Really look forward to CUDA 11 support.

**Comment by aluo-x** [comment]
I was under the impression that CUDA 11 had some bugs (I think slow performance on tensor cores for 3D conv), that were fixed in CUDA 11.1 (or the new cudnn?).

There's a bunch of [similar bugs](https://github.com/pytorch/pytorch/issues/47039) in the pytorch bug tracker.

**Comment by johnny12150** [comment]
![image](https://user-images.githubusercontent.com/22369387/98442815-15122180-2142-11eb-8896-935ce07099a2.png)

It seems that PyTorch 1.7.0 has landed.

**Comment by aluo-x** [comment]
I just upgraded my dev environment to CUDA 11.1/cudnn 8/pytorch 1.7.0. 
Aside from having to modify the magma build scripts, I was able to install pytorch + pytorch geometric without additional patches.
