### ISSUE TITLE
`pip install torch-scatter` ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by zhangxiann** [rusty1s/pytorch_geometric#1759]
## To Reproduce

1. ```
    pip install torch-scatter
    ```

<!-- If you have a code sample, error messages, stack traces, please provide it here as well. -->

## Expected behavior
Install successfully!
<!-- A clear and concise description of what you expected to happen. -->

## Environment

* OS: raspberry 3B+ : `Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux`
* Python version: 3.5.3
* PyTorch version: 1.0.0
* CUDA/cuDNN version: None
* GCC version: 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)
* Any other relevant information:
 error log
```
Collecting torch-scatter
  Using cached torch_scatter-2.0.2.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ouo5zip/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ouo5zip/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-08vhar41
         cwd: /tmp/pip-install-4ouo5zip/torch-scatter/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4ouo5zip/torch-scatter/setup.py", line 47
        sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
                                                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
## Additional context

<!-- Add any other context about the problem here. -->

**Comment by rusty1s** [comment]
We use Python's f-string functionality, so you need to upgrade to Python 3.6.

**Comment by zhangxiann** [comment]
Thanks, I will try

**Comment by zhangxiann** [comment]
> We use Python's f-string functionality, so you need to upgrade to Python 3.6.

I have used python 3.6, but still the same error.

**Comment by zhangxiann** [comment]
> We use Python's f-string functionality, so you need to upgrade to Python 3.6.

How can I install torch geometric on raspberry Pi ?

**Comment by rusty1s** [comment]
If I am not mistaken, there runs a Linux distribution on the Pi, so you should be able to install it via the Linux wheels.

**Comment by zhangxiann** [comment]
> If I am not mistaken, there runs a Linux distribution on the Pi, so you should be able to install it via the Linux wheels.

I use pip to install, there is error.
```
Collecting torch-scatter
  Using cached torch_scatter-2.0.2.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ouo5zip/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ouo5zip/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-08vhar41
         cwd: /tmp/pip-install-4ouo5zip/torch-scatter/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4ouo5zip/torch-scatter/setup.py", line 47
        sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
                                                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rusty1s** [comment]
Are you sure `pip` is referring to a Python 3.6 distro?

**Comment by zhangxiann** [comment]
> referring

I have uninstalled Python2. The syetem now only has Python3.6.1

**Comment by zhangxiann** [comment]
> Are you sure `pip` is referring to a Python 3.6 distro?

Can I build this reposity on raspberry (ARM)?
