### ISSUE TITLE
GRAPH-CNN FOR 3D POINT CLOUD

### ISSUE THREAD

**Issue by iSarmad** [rusty1s/pytorch_geometric#176]
## ❓ Questions & Help
Hi, This is truly amazing work you have done here. I see that there is a quick start tutorial for processing point cloud directly with Pointnet and Pointnet ++. But, I was wondering Is there a tutorial to convert point cloud data into graphs format first and then process those graphs using GCN layer or EdgeConv layers etc. 
As an example, I am talking about something similar to work done here
Paper: https://arxiv.org/pdf/1812.01711.pdf
Code: https://github.com/maggie0106/Graph-CNN-in-3D-Point-Cloud-Classification

**Comment by rusty1s** [comment]
Sure, just have a look at the [point cloud benchmark scripts](https://github.com/rusty1s/pytorch_geometric/tree/master/benchmark/points). An example on using the `EdgeConv` layer can be found [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/points/edge_cnn.py).

**Comment by iSarmad** [comment]
Thank you, this is what I was looking for.

**Comment by jlevy44** [comment]
Does your edge cnn script allow comparisons of multiple point clouds?

I'm looking to compare point clouds of 600-1200 points at a time, and show that overall, the point clouds are different and can be classified into different categories.

**Comment by rusty1s** [comment]
What do you mean with comparison? The point cloud benchmark script is only suited for classification. If you want to implement something different, e.g., triplet loss, you need to adapt it.

**Comment by rusty1s** [comment]
The point cloud benchmark script can be easily used for classification tasks. You only need to provide your own datasets. If you want to implement something different, e.g., triplet loss, you need to adapt it further.
