### ISSUE TITLE
Metapath in MetaPath2Vec seems not correct?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#1777]
## ❓ Questions & Help

After I read the document and the code, it seems metapath in MetaPath2Vec only supports a single metapath?
E.g., if I input `[(A, r1, B), (B, r2, C), (C, r3, A)]` it's actually metapath ABCA

**Comment by rusty1s** [comment]
That is correct. We only support a single metapath scheme (following the model definition from the official paper).

**Comment by mrbeann** [comment]
Yeah, it's right.
