### ISSUE TITLE
Bug in NeighbourSampler

### ISSUE THREAD

**Issue by DavideBuffelli** [rusty1s/pytorch_geometric#1779]
I'm using Pytorch Geometric 1.6.1 on MacOS, and I'm trying to run the reddit example (https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py). 

However the code terminates with the following message:

> Traceback (most recent call last):
>   File "reddit.py", line 129, in <module>
>     loss, acc = train(epoch)
>   File "reddit.py", line 90, in train
>     for batch_size, n_id, adjs in train_loader:
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
>     return self._process_data(data)
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
>     data.reraise()
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
>     raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/Users/yyy/opt/anaconda3/envs/geometric_16/lib/python3.6/site-packages/torch_geometric/data/sampler.py", line 109, in sample
>     adj, n_id = self.adj.sample_adj(n_id, size, replace=False)
> AttributeError: 'SparseTensor' object has no attribute 'sample_adj'

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/1770.
