### ISSUE TITLE
Include dependencies in package definition

### ISSUE THREAD

**Issue by parkererickson** [rusty1s/pytorch_geometric#1783]
## 🚀 Feature

Hopefully this hasn't already been discussed, but I think it would be great if there was a way to install all pyTorch Geometric dependencies (torch-scatter, torch-sparse, etc.) with one pip install. This information is incorporated in the pacakge's __init__.py.

## Motivation

The barrier to entry for new pyTorch Geometric users would be lower, as automatically installing the dependencies would be a lot easier than the current process.

Thanks!

**Comment by rusty1s** [comment]
This is on the [roadmap](https://github.com/rusty1s/pytorch_geometric/issues/1465) and we are trying to provide a single conda package in the near future.

**Comment by parkererickson** [comment]
Ah, I missed that. Thanks!
