### ISSUE TITLE
Slack invitation link no longer active

### ISSUE THREAD

**Issue by desktable** [rusty1s/pytorch_geometric#1788]
## 🐛 Bug

The slack invitation link on the front page (README.md) is no longer active.

## To Reproduce

1. Go to: https://github.com/rusty1s/pytorch_geometric
2. Click on "Click here to join our Slack community!" (https://torchgeometricco.slack.com/join/shared_invite/zt-hn9vter8-EQn4L4wLfE7PZEYbLMlw~Q#/)
3. Slack shows:
> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.
 

## Expected behavior

I expected to be able to join the Slack community for pytorch_geometric.

## Environment

* OS: Windows
* Browser: Chrome

**Comment by rusty1s** [comment]
This should be fixed now. Thanks for letting me know.

**Comment by lightaime** [comment]
It seems the link is no longer active again.

**Comment by rusty1s** [comment]
Should be fixed. Sadly, I need to edit it every 30 days.

**Comment by alex-vinnik-sp** [comment]
@rusty1s please fix the slack invite. I would like to join.

**Comment by rusty1s** [comment]
Should be fixed.

**Comment by andytwigg** [comment]
Hi, does the link need refreshing? Seems broken again!

**Comment by rusty1s** [comment]
Fixed :) Thanks for reporting.
