### ISSUE TITLE
Colab notebook given in the docs not running!

### ISSUE THREAD

**Issue by ASKanse** [rusty1s/pytorch_geometric#1796]
## ❓ Questions & Help

I was checking out the Colab notebook given for Graph Classification but after installing pytorch geometric in the first block. I get this error when I run second block.

`OSError: /usr/local/lib/python3.6/dist-packages/torch_sparse/_convert.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
`

So I checked the other note books and i still get the error. I don't understand why this is happening because this seemed to work  a while ago. 
Is there some issue withe torch_geometric installation?

**Comment by rusty1s** [comment]
Should be fixed by now. Colab updated its PyTorch version to 1.7.0, which caused this error.

**Comment by ASKanse** [comment]
> Should be fixed by now. Colab updated its PyTorch version to 1.7.0, which caused this error.

Oh didn't notice that, it's working now, thanks!
