### ISSUE TITLE
Is SEAL test work properly?

### ISSUE THREAD

**Issue by SeongJinAhn** [rusty1s/pytorch_geometric#1798]
## ❓ Questions & Help

I think that in seal_link_pred code, it works same with DGCNN.

Since the function process is not called, the Double-Radius node Labeling features are not added and subgraphs are not enclosed.
Then it is same with DGCNN.

**Comment by rusty1s** [comment]
`process` gets called internally by `__init__` of `InMemoryDataset`.

**Comment by SeongJinAhn** [comment]
> `process` gets called internally by `__init__` of `InMemoryDataset`.
Thanks a lot
