### ISSUE TITLE
Loading saved data with custom Dataset

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_geometric#1802]
## ❓ Questions & Help

I am trying to use a custom dataset that I created, following the guide on Pytorch Geometric (one that does not fit into memory). It seems, though, that every time I start a run, processing of the data occurs, even though I am processing the same data and saving the same data. I suspect that the class inherits methods to check file data existence based on the processed file names: 
```
class WLDynamicDataset(Dataset):
    def __init__(self, root, data, split_edge, num_hops, percent=100, split='train', 
                 use_coalesce=False, node_label='drnl', ratio_per_hop=1.0, 
                 max_nodes_per_hop=None, **kwargs):
...
    @property
    def processed_file_names(self):
```
However, in my processing, I often do not know how many files I will produce; this is a function of the processing. As such, the file name list I provide will be empty as a result, and the Dataset will regenerate the same files again. However, it is difficult to define the processed names beforehand with some index parameter in the name. Is there a way I can do this more cleanly in Pytorch Geometric?

**Comment by rusty1s** [comment]
I see. This is indeed a bit tricky. One way to get around this problem is to overwrite `_process` instead of `process` and simply ensure that the `process` directory is not empty:
```python
import glob
from torch_geometric.data.makedirs import makedirs

def _process(self):
    makedirs(self.processed_dir)
    if len(glob.glob(osp.join(self.processed_dir, '*.pt')) > 0:
        return

    # Start processing data...
```

**Comment by vymao** [comment]
Is this all the list of processed files is used for? Or is it also used for reading in the data through `get`? If so, then I will need to also store all the file names as well.

**Comment by rusty1s** [comment]
My bad. You are right. `_process` will not get called in case `process` is not implemented. You can implement it as follows:
```python
    def _process(self):
        makedirs(self.processed_dir)
        if len(glob.glob(osp.join(self.processed_dir, '*.pt'))) > 0:
            return
        self.process()

    def process(self)
        for idx in tqdm(range(len(self.links))):
            src, dst = self.links[idx]

            if self.labels[idx]: status = "pos"
            else: status = "neg"

            tmp = k_hop_subgraph(src, dst, self.num_hops, self.A, status, self.ratio_per_hop, 
                                 self.max_nodes_per_hop, node_features=self.data.x)
            data = construct_pyg_graph(*tmp, self.node_label)

            torch.save(data, osp.join(self.processed_dir, 'data_{}_{}.pt'.format(idx, self.split)))
            self.datalist.append('data_{}_{}.pt'.format(idx, self.split))
```
In general, you are responsible for implementing the logic in `get`. I suggest to hold a mapping from `idx` to filename to implement this.
