### ISSUE TITLE
Use radius to get points within a range

### ISSUE THREAD

**Issue by logsea** [rusty1s/pytorch_geometric#1803]
## ❓ Questions & Help

The `radius` function in `pytorch_geometric.nn` can connect nodes within a distance to center point. 
Is there a way to get points that the distance to the center points is between `(r1, r2)` rather than `(0, r)`.

**Comment by rusty1s** [comment]
You can do this in two steps:
```python
edge_index = radius(x, r=r2, max_num_neighbors=...)
row, col = edge_index
dist = torch.norm(x[row] - x[col], dim=-1)
edge_index = edge_index[:, dist > r1]
```

**Comment by logsea** [comment]
Thank you for your reply, it works.
By the way, I want to know if I choose neighbors that the distance is over `r1` from the `group(r2)` that the distance is bwlow `r2` and the `group(r2)` have few points such as 32, is it possible that all sampling points will be removed, or it is something like uniform sampling?
If not, will it require lots of sampling points if I divide `r2` into more small areas?
The `x` and `x0` for `radius` is in CUDA enviroment.

**Comment by rusty1s** [comment]
`radius` is like uniform sampling, it does not sort points according to their distance (at least not on GPU).

**Comment by logsea** [comment]
That means I can slice the area use `radius` only 1 time.
Thank you so much.
