### ISSUE TITLE
Get edge_index list of individual graphs from dataset.data.edge_index list.

### ISSUE THREAD

**Issue by LindaSt** [rusty1s/pytorch_geometric#1805]
## ❓ Questions & Help

Hi!

I want to do some additional computations on the graphs when I have them loaded as a `dataset` object (e.g. `TUDataset`). However, I'm having trouble separating the edge_index (from `dataset.data.edge_index`) into the different graphs again. Is there an easy way to do this?

Thanks!

**Comment by rusty1s** [comment]
One can access individual edge indices by iterating over the dataset:
```python
[data.edge_index for data in dataset]
```

**Comment by LindaSt** [comment]
Thanks a lot (you are always so fast in repyling, I really appreciate that)! I'll def a look at the transforms.
