### ISSUE TITLE
Exception has occurred: HTTPError HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by yuanjames** [rusty1s/pytorch_geometric#1808]
## To Reproduce

1.data = datasets.MoleculeNet(root='.',name='FreeSolv')
Dataset Download is forbidden.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Please see https://github.com/rusty1s/pytorch_geometric/issues/1794.

**Comment by yuanjames** [comment]
thanks

**Comment by yuanjames** [comment]
> Please see #1794.
Hi,  I think the address changed again. I found the new address should be "https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/SAMPL.csv"
