### ISSUE TITLE
is there any way of change the original code of 'SAGEConv'?

### ISSUE THREAD

**Issue by pixar0407** [rusty1s/pytorch_geometric#1809]
## ❓ Questions & Help

I want to change the original code of SAGEConv.
for example, I want to change the only behavior of 'def message_and_aggregate' of 'class SAGEConv'.
So, i try in this way.

in my execution code, i add class my_SAGEConv(SAGEConv):

```
class my_SAGEConv(SAGEConv):
    def __init__(self, in_channels: Union[int, Tuple[int, int]],
                 out_channels: int, normalize: bool = False,
                 bias: bool = True, **kwargs):  # yapf: disable
        kwargs.setdefault('aggr', 'mean')
        super(SAGEConv, self).__init__(**kwargs)'

    def reset_parameters(self):
        super(SAGEConv, self).reset_parameters()

    def forward(self, x: Union[Tensor, OptPairTensor], edge_index: Adj,
                size: Size = None) -> Tensor:
        print("##############################")
        super(SAGEConv, self).forward(x: Union[Tensor, OptPairTensor], edge_index: Adj,
                size: Size = None)
    def message(self, x_j: Tensor) -> Tensor:
        super(SAGEConv, self).message(x_j: Tensor)
    def message_and_aggregate(self, adj_t: SparseTensor,
                              x: OptPairTensor) -> Tensor:
        "something what i want .... and return "
    def __repr__(self):
       super(SAGEConv, self).__repr__()
```

but i am not sure this is the right way of override your original code.
for example, 
1) the only change point is 'def message_and_aggregate', but i override all the other 'def's using 'super'.
2) the way of using 'super' : should i specify all the variable which had been specified in original code?

and i got error like this
![image](https://user-images.githubusercontent.com/26530798/98429301-44487480-20e9-11eb-8248-041ab28aa02f.png)

3) Or is there any example code that breach the original code?
I attach the whole code (it is a python code, but i have to zip it for uploading).
[example_graph_sage.zip](https://github.com/rusty1s/pytorch_geometric/files/5504167/example_graph_sage.zip)

4) Lastly, is there any way that i can find the installed pytorch_geometric library files and i modified that code for my project locally?

thank you! :)

**Comment by rusty1s** [comment]
Hi,

1. you do not need to override all the other methods. In fact,
```python
class my_SAGEConv(SAGEConv):
    def message_and_aggregate(self, adj_t, x):
        ...
```
is sufficient.
2. No need to. I cannot reproduce your error though.
3. Your code looks fine to me.
4. Yes, you can directly apply your changes locally. For me, that would be `$MINICONDA_PATH/lib/python3.7/site-packages/torch_geometric`.

**Comment by pixar0407** [comment]
Hello, i hope you are doing healthy and okay in this covid-19 situation.

1. Thank you! 
2. okay! i will fix the error. don't worry.
3. alright! I will post my code someday for others, hopefully.
4. I found it! 

I appreciate your help!
I will close this issue :)
