### ISSUE TITLE
AttributeError: module 'torch_geometric.transforms' has no attribute 'NNGraph'

### ISSUE THREAD

**Issue by HanochZzhou** [rusty1s/pytorch_geometric#181]
Hi, 
 Thanks for sharing the lib. I am learning the code following instruction by example, but in data transform it occurred an error that module 'torch_geometric.transforms' has no attribute 'NNGraph'.
The following are your code :

import torch_geometric.transforms as T
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', category='Airplane',
                    pre_transform=T.NNGraph(k=6))
looking for reply ,thanks!

**Comment by rusty1s** [comment]
Ah, I see. That's a typo. It is called `T.KNNGraph(k=6)` (see [here](https://rusty1s.github.io/pytorch_geometric/build/html/modules/transforms.html#torch_geometric.transforms.KNNGraph)). Will fix ASAP. Thanks for letting me know.
