### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric'

### ISSUE THREAD

**Issue by omria503** [rusty1s/pytorch_geometric#1811]
## 📚 Installation

While trying to run the following section:

**from torch_geometric.data import Data**

I got the following error:
**Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ModuleNotFoundError: No module named 'torch_geometric'**

## Environment

* OS: windows 10
* Python version: 3.7.9
* PyTorch version: 1.7.0
* CUDA/cuDNN version: 10.2
* GCC version: g++ (MinGW.org GCC-6.3.0-1) 6.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
I've created anaconda env with python 3.7.9 and installed the packages using the following:

pytorch installation: 
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

pip install torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-cluster==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-spline-conv==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.7.0.html
pip install torch-geometric 

checking the versions:
python -c "import torch; print(torch.__version__)"
>>> 1.7.0

python -c "import torch; print(torch.version.cuda)"
>>> 10.2

nvcc --version
>>> nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

## Checklist

- [ V ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ V ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ V ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ X ] I do have multiple CUDA versions on my machine.

Appreciate your help

**Comment by rusty1s** [comment]
That's weird. I guess that you also cannot find those packages in `$CONDA_PATH/lib/pythonxxx/site-packages`? Are you sure you did not install via system-wide `pip`?

**Comment by omria503** [comment]
Running in anaconda prompt the command: conda list
I get the following (only relevant packages):
pytorch                   1.7.0           py3.7_cuda102_cudnn7_0    pytorch
torch-cluster             1.5.8                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.8                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchaudio                0.7.0                      py37    pytorch
torchvision               0.8.1                py37_cu102    pytorch

I do see the packages in $CONDA_PATH\envs\myenv\Lib\site-packages:
torch
torch-1.7.0-py3.7.egg-info
torch_cluster
torch_cluster-1.5.8.dist-info
torch_geometric
torch_geometric-1.6.1.dist-info
torch_scatter
torch_scatter-2.0.5.dist-info
torch_sparse
torch_sparse-0.6.8.dist-info
torch_spline_conv
torch_spline_conv-1.2.0.dist-info
torchaudio
torchaudio-0.7.0-py3.7.egg-info
torchvision
torchvision-0.8.1-py3.7.egg-info

What did I do wrong?
I installed it using anaconda prompt but with the pip install commands as mentioned above.

Thanks!

**Comment by rusty1s** [comment]
Mh, not really sure what causes this. Can you install other packages via `pip`?

**Comment by omria503** [comment]
Yes, pip works OK.
I just realized that everything works great if I run the following section from anaconda terminal:
>>> import torch
>>> from torch_geometric.data import Data
>>> edge_index = torch.tensor([[0, 1],
...                            [1, 0],
...                            [1, 2],
...                            [2, 1]], dtype=torch.long)
>>> x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
>>> data = Data(x=x, edge_index=edge_index.t().contiguous())
>>> data
Data(edge_index=[2, 4], x=[3, 1])

I tried to run this section from my project in pycharm with the same environment and got the stated errors (but not when I use clear new project).

**Comment by rusty1s** [comment]
Seems like PyCharm is misconfigured and uses a different Python version than the one provided by anaconda.

**Comment by omria503** [comment]
No, I don't think this was the problem. 
I've installed everything from scratch and now everything works.
Thanks for the help!

**Comment by Austinzhenghua** [comment]
> No, I don't think this was the problem.
> I've installed everything from scratch and now everything works.
> Thanks for the help!

I got the same problem as you, So, do I need a new enviroiment?

**Comment by maliozer** [comment]
I have the same issue, it doesnt work on jupyter-lab but works fine when i run as python script on same env.
on colab also get the same error;

`ImportError: cannot import name 'PygGraphPropPredDataset' from 'ogb.graphproppred' (/usr/local/lib/python3.7/dist-packages/ogb/graphproppred/__init__.py)`

**Comment by Austinzhenghua** [comment]
check your env list. if you use conda. You should make sure you install it on the right place. hua zheng ***@***.*** 签名由 网易邮箱大师 定制 On 07/12/2021 00:31, Mehmet Ali Özer wrote: I have the same issue, it doesnt work on jupyter-lab but works fine when i run as python script on same env. on colab also get the same error; ImportError: cannot import name 'PygGraphPropPredDataset' from 'ogb.graphproppred' (/usr/local/lib/python3.7/dist-packages/ogb/graphproppred/__init__.py) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maliozer** [comment]
The problem is not about env, just check this colab notebook, 

[Colab ogb-getting started example with PygGraphPropPredDataset error](https://colab.research.google.com/drive/1y0zzKMyJN_-IPuGo9nq15I3yfd0LKGjX?usp=sharing)

Data Loaders code from ogb homepage.

**Comment by rusty1s** [comment]
If you want to load an OGB dataset in PyG format, you need to install PyG as well. See [here](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing) on how to do so in Google Colab.

**Comment by Initiated0** [comment]
@rusty1s 
The command gives the following error:

 Could not install packages due to an OSError: HTTPSConnectionPool(host='data.pyg.org', port=443):.........

**Comment by rusty1s** [comment]
Mh, weird. Can you access https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html?

**Comment by LanternCode** [comment]
It seems the issue still persists, @rusty1s solution to also include "torch-cluster torch-spline-conv torch-geometric" in pip installation solved it for me (Colab notebooks). Thanks.

**Comment by LeiHHHuang** [comment]
Ran into the exact same issue. After adding `!pip install torch-geometric` in jupyter notebook, it showed requirement already satisfied and then successfully imported torch_geometric.

**Comment by amp1590** [comment]
`pip install torch-geometric`
This solved the error for me. After running the above command, run the command:
`conda list`
You should see the "torch_geometric" on the list.
