### ISSUE TITLE
input batch_size doesn't match target batch_size

### ISSUE THREAD

**Issue by Bowenduan** [rusty1s/pytorch_geometric#1813]
## ❓ Questions & Help

I train my graph classification model with batch size 64.
```python
train_loader = torch_geometric.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
```
The first epoch goes well, but during the second epoch, the following error occurs.
```python
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    train()
  File "train.py", line 120, in train
    loss = criterion(out, data.y)
  File "/home/wbl/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbl/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/wbl/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/functional.py", line 2215, in nll_loss
    raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
ValueError: Expected input batch_size (63) to match target batch_size (64).
```
It shows the number of graphs doesn't match the number of labels in a batch. I guess `torch_geometric.data.DataLoader` goes wrong, so I print out the number of graphs and the number of labels in every step as follows.
```python
for data in train_loader:
    print('Num of graphs: {}, Num of labels: {}'.format(data.num_graphs, data.y.shape[0]))
```
The output becomes:
```python
Num of graphs: 64, Num of labels: 64  
...
...                                                                                          
Num of graphs: 63, Num of labels: 64
Traceback (most recent call last):
# The error shows above
```
I have tried to reduce the batch size, but the same error still occurs.
How is that possible?

**Comment by rusty1s** [comment]
Do you have graphs in your dataset with zero nodes?

**Comment by Bowenduan** [comment]
Yes... I think I know the problem. But why didn't this error occur during the first epoch?

**Comment by rusty1s** [comment]
Because this error only occurs in case the last graph in the batch has zero nodes, which is not always the case due to random shuffling of the data. In the end, applying GNNs on a graph with zero nodes is undefined behaviour (you cannot produce a feature vector out of nothing), so I suggest to simply remove all graphs with no nodes first.

**Comment by Bowenduan** [comment]
OK, I'll remove graphs with zero nodes. Thank you!!

**Comment by rusty1s** [comment]
`data.num_graphs` should now always report the correct number of graphs.
