### ISSUE TITLE
Is Pytorch Geometric available through conda?

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_geometric#1819]
## ❓ Questions & Help

Is Pytorch Geometric available through conda?

**Comment by rusty1s** [comment]
Not yet, but this is on the [roadmap](https://github.com/rusty1s/pytorch_geometric/issues/1465).

**Comment by mmcdermott** [comment]
I'd like to upweight this issue -- right now, as far as I can tell, installing pytorch geometric in any conda environment that _already_ has pytorch installed in the typical way will result in a broken installation. As a MWE, on a fresh machine I just created a new conda envrionment, installed pytorch (per pytorch's recommended instructions, e.g. `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`) then installed `pytorch_geometric` according to the instructions on the main page, and then running `python` and `from torch_geometric.datasets import Planetoid` yields:
```
>>> from torch_geometric.datasets import Planetoid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /crimea/conda_envs/pytorch_geometric_install_test/lib/python3.8/site-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```

This makes it very difficult to design portable environments that use `pytorch_geometric`; having a conda-safe install would markedly help. On the other hand, if I'm doing something stupid in setting up an environment in this way, I'd welcome any corrections.

**Comment by rusty1s** [comment]
Mh, I've never had any issues with combining a conda PyTorch installation with a pip PyTorch Geometric installation. How do you install the external packages?

I definitely see the need for a conda installation though. I'm trying my best to integrate it.

**Comment by mmcdermott** [comment]
@rusty1s thanks; I wonder what about my setup is so strange if this hasn't been a problem for you. To clarify though, what I described above was a MWE. The only packages in the conda environment were pytorch (installed from their main directions) followed by installing pytorch geometric through pip. That's it, and then the import gives the error listed above.

**Comment by rusty1s** [comment]
I'm really not sure what went wrong for you there :( You can see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/.travis.yml#L113-L117) that we setup PyTorch via conda and install `torch-scatter` afterwards.

**Comment by jeffwillette** [comment]
I got this same error with just pip and torch 1.8.1+cu102

**Comment by rusty1s** [comment]
PyG is now available through conda, see [here](https://github.com/rusty1s/pytorch_geometric#installation).
