### ISSUE TITLE
Error installing pytorch-geometric dependencies (torch-sparse, torch-scatter, torch-cluster)

### ISSUE THREAD

**Issue by noncomputable** [rusty1s/pytorch_geometric#1826]
## 📚 Installation

I am trying to install pytorch-geometric in a conda environment.

When I try to install any of the dependencies with `pip install torch-sparse`, I get this error: https://dpaste.org/O5Uq. It ends with "ValueError: underlying buffer has been detached". Same thing for the other dependencies, torch-scatter and torch-cluster.

I also tried downloading and building the wheels directly (from [here](https://pytorch-geometric.com/whl/torch-1.6.0.html)), but first pip errors that the wheel names are invalid, then after renaming it in wheel format (e.g. torch-scatter-latest-cpu-cp37-cp37m-win_amd64.whl), pip writes "ERROR: torch-scatter-latest-cpu-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform".

How can I get pytorch-geometric installed on this computer?

## Environment

* OS: 64-bit Windows 10
* Python version: 3.7.9
* PyTorch version: 1.6.0
* CUDA/cuDNN version: cpu
* How did you try to install PyTorch Geometric and its extensions (wheel, source): pypi

## Checklist

- [yes ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [yes ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [no] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [no] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Hopefully, [this thread](https://stackoverflow.com/questions/28568070/filename-whl-is-not-supported-wheel-on-this-platform) is helpful to you.

**Comment by noncomputable** [comment]
As far as I saw on pytorch-geometric.com, that wheel is the only available one that matches the environment.
Do you have any idea about the issue with installing from pypi with `pip install torch-sparse`?

**Comment by noncomputable** [comment]
I successfully installed it with a bash script using the standard method after fixing an issue with the windows environment.

**Comment by Kunind27** [comment]
> Hopefully, [this thread](https://stackoverflow.com/questions/28568070/filename-whl-is-not-supported-wheel-on-this-platform) is helpful to you.

The link does not work :/
