### ISSUE TITLE
About the speed of DGCNN

### ISSUE THREAD

**Issue by logsea** [rusty1s/pytorch_geometric#1829]
## ❓ Questions & Help

I implement an DGCNN follow the original [architecture](https://github.com/WangYueFt/dgcnn) (which contains `DynamicEdgeConv` 4 times rather than 2 times in the example). Each graph contains 256 nodes, and with the batch_size of 32, I need around 12s for a batch. 
Compare to other network layers, it is too slow. Is there anything wrong?
The cpu is i9-9900K and gpu is RTX 2080Ti.

Here is my code:
```
class DGCNN(torch.nn.Module):
    def __init__(self, node_per_graph):
        super(DGCNN, self).__init__()
        self.conv1 = DynamicEdgeConv(MLP([4*2, 64]), 20)
        self.conv2 = DynamicEdgeConv(MLP([64*2, 64]), 20)
        self.conv3 = DynamicEdgeConv(MLP([64*2, 128]), 20)
        self.conv4 = DynamicEdgeConv(MLP([128*2, 256]), 20)
        self.lin1 = MLP([512, 1024])
        self.mlp = Seq(
            MLP([2048, 512]), Dropout(0.5), MLP([512, 256]), Dropout(0.5),
            Lin(256, 40))

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x1 = self.conv1(x)
        x2 = self.conv2(x1)
        x3 = self.conv3(x2)
        x4 = self.conv4(x3)
        out = self.lin1(torch.cat([x1, x2, x3, x4], dim=1))
        out = torch.cat([gmp(out, batch), gap(out, batch)], dim = 1)
        out = self.mlp(out)
        x = F.log_softmax(out, dim=-1)
        return x
```

**Comment by rusty1s** [comment]
I think you are missing the `batch` argument in the `DynamicEdgeConv`s `forward` call. Currently, you are creating a single graph, where nodes in distinct graphs can be connected. Can you see if this helps reducing the runtime?

**Comment by logsea** [comment]
Oh, yes! I miss the `batch` argument. After add it the speed increase to around 5 batch per second.

Thank you so much for your answer and find a bug I did not nitice.!
