### ISSUE TITLE
how to process the multi subject graph?

### ISSUE THREAD

**Issue by tanjia123456** [rusty1s/pytorch_geometric#1830]
Hello，I have 80 people's data, which is 80 subjects, and each subject is a graph. My subject is to use graph neural network to do image segmentation, I think it should be analogous to node classification task.
Each graph has 10242 nodes, 8 features, 76 categories, and each node has a label. For example, in the code of GAT, the cora dataset used has only one graph. If I use 60 graphs of my data as the training set and 20 as the test set, and set the batch-size to 60, the dimensions will not match. Error, how can I solve it?

**Comment by rusty1s** [comment]
Which dimensions do not match? As long as your nodes across graphs have the same feature dimensionality, this should just work fine. Can you show me the error message?

**Comment by tanjia123456** [comment]
`import time
import numpy as np
import tensorflow as tf
import os

from models import GAT
from utils import process

checkpt_file = 'pre_trained/data/mod_data.ckpt'

pathname = 'data/subject*'
num_subject = process.get_num_subjects(pathname)  # 12

# training params
batch_size = 10#num_subject=12  train_subject=10
nb_epochs = 100
patience = 100# not change
lr = 0.005  # learning rate
l2_coef = 0.0005  # weight decay
hid_units = [8] # numbers of hidden units per each attention head in each layer
n_heads = [8, 1] # additional entry for the output layer
residual = False
nonlinearity = tf.nn.elu
model = GAT

print('pathname: ' + pathname)
print('----- Opt. hyperparams -----')
print('batch_size:'+str(batch_size))
print('lr: ' + str(lr))
print('l2_coef: ' + str(l2_coef))
print('----- Archi. hyperparams -----')
print('nb. layers: ' + str(len(hid_units)))
print('nb. units per layer: ' + str(hid_units))
print('nb. attention heads: ' + str(n_heads))
print('residual: ' + str(residual))
print('nonlinearity: ' + str(nonlinearity))
print('model: ' + str(model))


features_data,labels_data,adj_data=process.generate_3D_data(num_subject)
#feature_data(12,10242,8)  labels_data(12,10242,76)  adj_data(12,10242,10242)

# save the memory
features_data=features_data.astype('float16')
labels_data=labels_data.astype('float16')
adj_data=adj_data.astype('float16')

#train_subject_index是从1开始的;train_list是从0开始的
#K-fold交叉验证，K=6
train_list, test_list,y_train,y_test,train_mask,test_mask,x_train,x_test=process.split_data(
    num_subject,6, features_data, labels_data, adj_data)
#
#train_mask: [[ True  True False  True  True  True  True False  True  True  True  True]] <class 'numpy.ndarray'> bool



#features_data(num_subject,nb_node,feature_size);
#labels(num_subject,nb_node,nb_classes)
nb_nodes = features_data.shape[1]
ft_size = features_data.shape[2]
nb_classes = y_train.shape[2]

biases = process.adj_to_bias(adj_data, [nb_nodes], nhood=1)



with tf.Graph().as_default():
    with tf.name_scope('input'):
        ftr_in = tf.compat.v1.placeholder(dtype=tf.float32, shape=(batch_size, nb_nodes, ft_size))
        bias_in =tf.compat.v1.placeholder(dtype=tf.float32, shape=(batch_size, nb_nodes, nb_nodes))
        lbl_in = tf.compat.v1.placeholder(dtype=tf.int32, shape=(batch_size, nb_nodes, nb_classes))
        #msk_in = tf.compat.v1.placeholder(dtype=tf.int32, shape=(batch_size, nb_nodes))
        #self.msk_in = tf.placeholder(dtype=tf.int32, shape=(self.batch_size))
        msk_in = tf.compat.v1.placeholder(dtype=tf.int32, shape=(1,num_subject))#mask_in(1,12)
        attn_drop =tf.compat.v1.placeholder(dtype=tf.float32, shape=())
        ffd_drop = tf.compat.v1.placeholder(dtype=tf.float32, shape=())
        is_train = tf.compat.v1.placeholder(dtype=tf.bool, shape=())

    logits = model.inference(ftr_in, nb_classes, nb_nodes, is_train,
                                attn_drop, ffd_drop,
                                bias_mat=bias_in,
                                hid_units=hid_units, n_heads=n_heads,
                                residual=residual, activation=nonlinearity)

    log_resh = tf.reshape(logits, [-1, nb_classes])
    lab_resh = tf.reshape(lbl_in, [-1, nb_classes])
    msk_resh = tf.reshape(msk_in, [-1])
    loss = model.masked_softmax_cross_entropy(log_resh, lab_resh, msk_resh)
    accuracy = model.masked_accuracy(log_resh, lab_resh, msk_resh)

    train_op = model.training(loss, lr, l2_coef)
    saver = tf.compat.v1.train.Saver()

    init_op = tf.group(tf.compat.v1.global_variables_initializer(), tf.compat.v1.local_variables_initializer())

    vlss_mn = np.inf
    vacc_mx = 0.0
    curr_step = 0

    with tf.compat.v1.Session() as sess:
        sess.run(init_op)

        train_loss_avg = 0
        train_acc_avg = 0
        #ts_loss_avg = 0
        #ts_acc_avg = 0

        for epoch in range(nb_epochs):
            tr_step = 0
            #tr_size = features_data.shape[0]#12
            '''tr_step就是从0，'''
            #将训练集中的数据一个一个的进行送入即可，遍历train_mask中的数据，再一个一个送进来即可
            #while tr_step * batch_size < tr_size:

            _, loss_value_tr, acc_tr,pred_tr = sess.run([train_op, loss, accuracy,log_resh],
                feed_dict={
                    ftr_in: x_train,
                    bias_in: biases[train_mask,:,:],
                    lbl_in: y_train,
                    msk_in: train_mask,
                    is_train: True,
                    attn_drop: 0.6, ffd_drop: 0.6})
            train_loss_avg += loss_value_tr
            train_acc_avg += acc_tr
            #tr_step += 1
            #print('Training: loss = %.5f, acc = %.5f' % (train_loss_avg / tr_step, train_acc_avg / tr_step))
            print('epoch= d%,Training: loss = %.5f, acc = %.5f'%(epoch ,loss_value_tr, acc_tr))


        #ts_size = features_data.shape[0]
        #ts_step = 0
        ts_loss = 0.0
        ts_acc = 0.0

        #while ts_step * batch_size < ts_size:
        loss_value_ts, acc_ts,pred_ts = sess.run([loss, accuracy,log_resh],
            feed_dict={
                ftr_in: features_data[test_mask,:,:],
                bias_in: biases[test_mask,:,:],
                lbl_in: y_test,#labels_data[test_mask,:,:]
                msk_in: test_mask,
                is_train: False,
                attn_drop: 0.0, ffd_drop: 0.0})
        ts_loss += loss_value_ts
        ts_acc += acc_ts
        #ts_step += 1

        print('Test loss:', loss_value_ts, '; Test accuracy:', acc_ts)

        sess.close()
`


the error message is :
Traceback (most recent call last):
  File "execute_data.py", line 87, in <module>
    loss = model.masked_softmax_cross_entropy(log_resh, lab_resh, msk_resh)
  File "/home/tj/codes/GAT_tensorflow/split_all_subject/GAT-master-8/models/base_gattn.py", line 49, in masked_softmax_cross_entropy
    loss *= mask
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 899, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6701, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/tj/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 102420 and 12 for 'mul' (op: 'Mul') with input shapes: [102420], [12].

**Comment by tanjia123456** [comment]
By the way, someone says set the batch_size=1 and input the graph one by one.
But I think to do image segmentation should input all the train graphs.

**Comment by rusty1s** [comment]
Is this a PyTorch Geometric code? It doesn't look like it :)

I suggest you look for the reason `masked_softmax_cross_entropy` reports a dimension mismatch error:
```python
log_resh = tf.reshape(logits, [-1, nb_classes])
lab_resh = tf.reshape(lbl_in, [-1, nb_classes])
msk_resh = tf.reshape(msk_in, [-1])
```
In particular, this means that the first dimension of these tensors need to match.

**Comment by tanjia123456** [comment]
yes, I have found the error. I use the gat source code.
now I input the graph one by one, and set the batch_size=1. Now I use 12 graphs, 10 graphs for train, 2 graphs for test
`        for epoch in range(nb_epochs):
            tr_step = 0
            #############trainset#########################
            x_train=features_data[train_list,:,:]#(10,10242,8) ------ 10 is the train graphs
            y_train=labels_data[train_list,:,:]#(10,10242,76)
            bias_1=biases[train_list,:,:]#(10,10242,10242)
            tr_size = x_train.shape[0]#10
            #input the graph one by one, and extract the graph from trainset
            while tr_step * batch_size < tr_size:
                for i,j in enumerate(train_list):
                    #i is serial number starting from 0，j is the value in list

                    _, loss_value_tr, acc_tr,pred_tr = sess.run([train_op, loss, accuracy,log_resh],
                    feed_dict={
                        ftr_in: x_train[i,:,:][np.newaxis],
                        bias_in:bias_1[i,:,:][np.newaxis],
                        lbl_in: y_train[i,:,:][np.newaxis],
                        msk_in: process.all_node_mask(nb_nodes),#(1,10242)   <class 'numpy.ndarray'> bool
                        is_train: True,
                        attn_drop: 0.6, ffd_drop: 0.6})
                    train_loss_avg += loss_value_tr
                    train_acc_avg += acc_tr
                    tr_step += 1
            #这个训练的loss和acc究竟是怎么做的呢?
            #avg_loss, avg_acc = sum(losses) / n_samples, sum(accs) / n_samples
            print('epoch=%d|Training: loss = %.5f, acc = %.5f' % (epoch,
                            train_loss_avg / (tr_step*len(train_list)),train_acc_avg / (tr_step*len(train_list))))`
But the acc and loss keep rising, I think there may be a problem. Is it possible that the print is wrong?

This is the training output:
`epoch=65|Training: loss = 26.67443, acc = 0.50751
epoch=66|Training: loss = 27.07137, acc = 0.51624
epoch=67|Training: loss = 27.46832, acc = 0.52499
epoch=68|Training: loss = 27.86530, acc = 0.53359
epoch=69|Training: loss = 28.26222, acc = 0.54234
epoch=70|Training: loss = 28.65909, acc = 0.55100
epoch=71|Training: loss = 29.05578, acc = 0.55964
epoch=72|Training: loss = 29.45261, acc = 0.56844
epoch=73|Training: loss = 29.84929, acc = 0.57722
epoch=74|Training: loss = 30.24609, acc = 0.58597
epoch=75|Training: loss = 30.64269, acc = 0.59476
epoch=76|Training: loss = 31.03919, acc = 0.60344
epoch=77|Training: loss = 31.43594, acc = 0.61211
epoch=78|Training: loss = 31.83249, acc = 0.62084
epoch=79|Training: loss = 32.22913, acc = 0.62954
epoch=80|Training: loss = 32.62576, acc = 0.63828
`

**Comment by rusty1s** [comment]
Well, that's hard to say. You can try decreasing your learning rate to see if that helps.

**Comment by tanjia123456** [comment]
OK, any way thanks for your help. I will try it
