### ISSUE TITLE
Torchscript support for network with fixed `edge_index`

### ISSUE THREAD

**Issue by joel99** [rusty1s/pytorch_geometric#1831]
## ❓ Questions & Help

Hi, I'm not sure if this is a bug or just unsupported, but I run into an issue jitting `self.propagate` when I have a fixed Tensor `edge_index`. I have a `nn.Module` that inherits `MessagePassing`.
```
    def forward(self, inputs: Tensor, state: Tensor) -> Tensor:
        r"""
            Will create messages from state and message neighbors. Nodes step recurrent state based on messages and input.
            Args:
                inputs: B x N x input_size or B x input_size
                state: node state. B x N x h
            Returns:
                state: node state. B x N x h
        """
        ...
        m = self.state_to_message(state)
        m = self.propagate(self.graph, x=m)
        ...
        state = self.rnn(m.view(-1, self.hidden_size), state.view(-1, self.hidden_size)).view(b, self.n, -1)
        return state
```
Here, the `edge_index` is a fixed Tensor (`self.graph`). I'm trying to JIT this module, and when I provide
`propagate_type = {'x': Tensor}` it seems to expect `self.graph` to be a sparse tensor. The trace is a little ambiguous, though.
![image](https://user-images.githubusercontent.com/14226466/99280435-54560780-27ff-11eb-86af-f1a4fc2cd8e4.png)

When I declare `propagate_type = {'x': Tensor, 'edge_index': Tensor}`, I get a duplicate definition error.
![image](https://user-images.githubusercontent.com/14226466/99280507-69cb3180-27ff-11eb-92ed-51be07b7ccdc.png)

Thanks for the wonderful framework! Let me know if I can provide more information that would help.

**Comment by rusty1s** [comment]
TorchScript requires that all arguments of `propagate` are actually passed (I guess due to the way overloads are handled in PyTorch). The following should fix your issue:
```python
import torch
from torch import Tensor
from torch_geometric.nn import MessagePassing

class MyConv(MessagePassing):
    def __init__(self):
        super(MyConv, self).__init__(aggr='mean')

    def forward(self, edge_index: Tensor, x: Tensor) ->             …Tensor:
        # propagate_type: (x: Tensor)
        return self.propagate(edge_index, x=x, size=None)


conv = MyConv().jittable()
conv = torch.jit.script(conv)
```

**Comment by joel99** [comment]
Yep, I think that solved it, thanks!
