### ISSUE TITLE
GCNconv fails when used with normalize=False

### ISSUE THREAD

**Issue by mitchell-joblin** [rusty1s/pytorch_geometric#1833]
## 🐛 Bug

GCNconv fails when used with normalize=False

## To Reproduce

1. Run a model with GCNconv setting the normalize layer parameter to false.
1. Observed errors is: 
def message(self, x_j: Tensor, edge_weight: Tensor) -> Tensor:
>       return edge_weight.view(-1, 1) * x_j
E       AttributeError: 'NoneType' object has no attribute 'view'
1.

## Environment

* OS:mac
* Python version: 3.7
* PyTorch version: 1.6.1
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

## Additional context

Seems the behavior has changed since v.1.5.0. Based on a short look at the code its seems the edge_weights are equal to none if normalize=True is not selected.

**Comment by rusty1s** [comment]
You're right. Thanks for reporting. This is now fixed in master. You can install it via:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
