### ISSUE TITLE
Data object to Dataset or InMemoryDataset object

### ISSUE THREAD

**Issue by omgmax** [rusty1s/pytorch_geometric#1834]
## ❓ Questions & Help

Hello, I have a Data object. How do I turn that into a Dataset or InMemoryDataset object?

Also, how do I then save this dataset to disk, so I can load it another time? Is there a benefit of working with Dataset vs Data objects? 

Thank you for your help

Edit:
I see in [#issue1359](https://github.com/rusty1s/pytorch_geometric/issues/1359#issue-643208483) that I can turn a list of Data objects to a Dataset object so that answers my first question, but I am still wondering about the other ones.

**Comment by rusty1s** [comment]
In general, it is not needed to transform a `data` object into a dataset. You can just save it to disk via `torch.save(data, path)`. The only functionality you are missing out is `dataset.num_classes` and transforms.

Nonetheless, you can turn it into a dataset via:
```python
class MyDataset(InMemoryDataset):
    def __init__(self, root, transform):
        super(MyDataset, self).__init__(root, transform)
        self.data, self.slices = torch.load(self.processed_paths[0])

    def processed_file_names(self):
        return ['data.pt']

    def process(self):
        # Generate data here or except it to be in global scope.
        self.collate([data], self.processed_paths[0])
```

**Comment by omgmax** [comment]
Thank you so much for your quick reply!

**Comment by ForrestPi** [comment]
> In general, it is not needed to transform a `data` object into a dataset. You can just save it to disk via `torch.save(data, path)`. The only functionality you are missing out is `dataset.num_classes` and transforms.
> 
> Nonetheless, you can turn it into a dataset via:
> 
> ```python
> class MyDataset(InMemoryDataset):
>     def __init__(self, root, transform):
>         super(MyDataset, self).__init__(root, transform)
>         self.data, self.slices = torch.load(self.processed_paths[0])
> 
>     @property
>     def processed_file_names(self):
>         return ['data.pt']
> 
>     def process(self):
>         # Generate data here or expect it to be in global scope.
>         torch.save(self.collate([data]), self.processed_paths[0])
> ```

Hi, how to save self.data, self.slices  when I try to save data like
```python
class MeshInMemoryDataset(InMemoryDataset)
           data,slice = self.collate(train_data)     
           torch.save(self.collate(train_data), self.processed_paths[0]) 
```
Killed occurred

**Comment by rusty1s** [comment]
Can you clarify? Your code seems to be missing a `__init__`. And you also need to assign `data` and `slices` to `self.data` and `self.slices`.
