### ISSUE TITLE
InMemoryDataset: RAM or GPU memory?

### ISSUE THREAD

**Issue by omgmax** [rusty1s/pytorch_geometric#1835]
## ❓ Questions & Help

The description for InMemoryDataset is: Dataset base class for creating graph datasets which fit completely into memory. See here for the accompanying tutorial.

Is this referring to RAM or GPU memory?

Thank you!

**Comment by rusty1s** [comment]
This is referring to RAM. I will make this more clear in the documentation.

**Comment by omgmax** [comment]
Thanks for clearing that up!
