### ISSUE TITLE
Are the features returned by GatConv.forward method already the updated node embeddings or the update to the node embeddings?

### ISSUE THREAD

**Issue by JonathanSchmidt1** [rusty1s/pytorch_geometric#1836]
## ❓ Questions & Help
Just a quick question:
Are the features returned by GatConv.forward method already the updated node embeddings or the update to the node embeddings?
thank you very much for any answers.

**Comment by rusty1s** [comment]
Not sure if I understand you correctly. The output represents the updated node representations based on message passing based on the previous node representations.

**Comment by JonathanSchmidt1** [comment]
I think I understand now. Please correct me if I am wrong. 
The GatConv is implemented such that one enters the edge_index describing the neighborhood which will be responsible for the \sum alpha_i,j x_j and then selfloops are added that are responsible for the +alpha_i,i x_i and in order to include i  in the calculation of the attention coefficients where we use ∑k∈N(i)∪{i} in the demoninator.

Therefore if I would like to change it to just return the \sum_{i!=j} alpha_i,j x_j instead of   alpha_i,i*x_i + \sum_{i!=j} alpha_i,j x_j I would have to remove the selfloops after the calculation of the alpha_i,j or set the corresponding alpha_i,i to zero to mask them out.

**Comment by rusty1s** [comment]
If you do not want to include self-loops, you can set `add_self_loops=False` for `GATConv`.

**Comment by JonathanSchmidt1** [comment]
Thank you so much for your quick answer.
If I add_self_loops= False will it still calculate the attentio coefficients as : αi,j=exp(LeakyReLU(a⊤[Θxi∥Θxj]))/∑k∈N(i)∪{i}exp(LeakyReLU(a⊤[Θxi∥Θxk])) or will it remove the ∪{i} from the denominator as well?

**Comment by rusty1s** [comment]
No, it will calculate attention coefficients solely based on the neighboring nodes, i.e. it will drop ∪{i} completely.

**Comment by JonathanSchmidt1** [comment]
Ok thank you very much than I will just mask out the \alpha_i,i in the last step.
