### ISSUE TITLE
Built in parallelization of Dataset processing?

### ISSUE THREAD

**Issue by vymao** [rusty1s/pytorch_geometric#1837]
## ❓ Questions & Help

Is there a built in way to process data for Dataset creation? I was just going to use the `multiprocessing` module if not.

**Comment by rusty1s** [comment]
The most easiest way to achieve that is to use `multiprocessing.Pool`. As an example, we do make use of that [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/geodesic.py#L74).
