### ISSUE TITLE
Include colab notebooks here

### ISSUE THREAD

**Issue by MohsenFazaeli** [rusty1s/pytorch_geometric#1839]
## 🚀 Feature

I'm new user to this package, and I usually do experiments on Colab. Unfortunately, I can not open the sample notebooks shared in the package website. It will be great if we could have them in github here pr a new repository.

**Comment by rusty1s** [comment]
Do you mean the Colabs from [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html)? Why can't you access them?

**Comment by MohsenFazaeli** [comment]
Yes, I mentioned these notebooks. Nothing was loaded and a "Fetch" error popped out. Btw now I see them. 
Thanks.
