### ISSUE TITLE
Sufficient number of tests to pass when contributing

### ISSUE THREAD

**Issue by harrygcoppock** [rusty1s/pytorch_geometric#1842]
## ❓ Questions & Help 

Hi! I am looking to contribute to the pytorch_geometric codebase - specifically add an example script for inductive DeepGraphInfomax.

Before I start on my contribution I want to check my installation is correct so I ran the tests
`python setup.py test`

I fail 3 out of the 226 tests and have a reported code coverage of 86%. I was wondering if this is sufficient? In the contribution documentation it says a coverage of close to 100% is required however on the main README it is detailed that there is only 87% code coverage.

Here is the summary of the test
`
-------------------------------------------------------------------------
TOTAL                                                  7755   1060    86%

=========================== short test summary info ============================
FAILED test/transforms/test_to_superpixels.py::test_to_superpixels - ImportEr...
FAILED test/utils/test_convert.py::test_trimesh - ImportError: Package `trime...
FAILED test/utils/test_geodesic.py::test_geodesic_distance - ImportError: Pac...
==== 3 failed, 223 passed, 1 skipped, 498871 warnings in 288.09s (0:04:48) =====
`
I basically want to check if I need to do anything more before I start adding code/functionality.

Thank you in advance for your time.

Also LOVE the library!

**Comment by harrygcoppock** [comment]
<img width="772" alt="Screenshot 2020-11-19 at 17 30 00" src="https://user-images.githubusercontent.com/59699137/99694568-dd35a300-2a8c-11eb-8602-f59667dc8c59.png">
Here is better formatting of test summary

**Comment by rusty1s** [comment]
Please do not worry about the test coverage when contributing. The test run looks fine to me but note that there are some tests that require additional packages such as trimesh.

**Comment by harrygcoppock** [comment]
Thank you for your speedy reply. That's great will get started right away. Is there a list of the extra packages required?

**Comment by rusty1s** [comment]
See [here](https://github.com/rusty1s/pytorch_geometric/blob/master/.travis.yml#L22-L26).
