### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED when download ShapeNet dataset

### ISSUE THREAD

**Issue by caozhzh** [rusty1s/pytorch_geometric#1849]
## 🚀 ERROR
cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:  Issued certificate has expired

## Ignore certificate check
torch_geometric/data/download.py line 31 
    data = urllib.request.urlopen(url)
CHANGE TO
    import ssl
    context = ssl._create_unverified_context()
    data = urllib.request.urlopen(url, context=context)

**Comment by rusty1s** [comment]
This should be already fixed in master. You can install it via
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by caozhzh** [comment]
OK,thanks
I installed using this command in the docs:
pip install torch-spline-conv==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-${TORCH}.html
