### ISSUE TITLE
How to get every batch as a Data object within a Batch?

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#185]
## ❓ Questions & Help
My dataset is consists of multiple directed graphs. For every graph, there is actually an order for every node when constructing a `Data` object. So my question is when I use a `DataLoader` to get a batch of graphs, how to get every single graph for some specific computation? Is the only way to use `batch.batch`?

**Comment by rusty1s** [comment]
Interesting question. Yes, you need `batch.batch` in order to achieve this. I additionally suggest to use `torch.split` to split the data object, *e.g.* (untested):
```python
sections = torch.bincount(data.batch)
xs = torch.split(x, sections)

row, col = edge_index
sections = torch.bincount(data.batch[row])
rows = torch.split(row, sections)
cols = torch.split(col, sections)
```

**Comment by RuihongQiu** [comment]
Impressive!
Thank you for such a quick respond!
