### ISSUE TITLE
I am a newbie and want to ask about GlobalAttentionPooling

### ISSUE THREAD

**Issue by lyj1998** [rusty1s/pytorch_geometric#1852]
## ❓ Questions & Help

How do gate_nn and nn construct the network effect will be better?
Is it used like this, for example：
```
    gate_nn = nn.Sequential(nn.Linear(in_channels, in_channels), nn.ReLU(), nn.Linear(in_channels, 1))
    in_channels = embedding_size = 4
    fea_nn = nn.Sequential(nn.Linear(in_channels, in_channels), nn.ReLU(), nn.Linear(in_channels, in_channels))
    global_attn = GlobalAttention(gate_nn, fea_nn)
    x = torch.tensor([[1.3, 3.4, 3.4, 4.4],[1.3, 3.4, 3.4, 4.4],[1.3, 2.4, 2.2, 4.4],[1.3, 1.4, 3.4, 5.4]])
    batch = torch.tensor([0, 0, 1, 2])
    res = global_attn(x, batch)
    print(res)
```
thank you very much!

**Comment by rusty1s** [comment]
Your usage is correct, although I'm not sure what's the actual question :)

`gate_nn` is used to compute a node feature importance score. A high value indicates that the corresponding node feature vector has a high impact in the resulting output vector. `nn` is used to transform each node feature separately (and can be `None`).
