### ISSUE TITLE
Bug: ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by JunweiSUN** [rusty1s/pytorch_geometric#1858]
## 🐛 Bug

Hi @rusty1s , I'm trying the node2vec [example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/node2vec.py). It seems that if I use pytorch v1.6.0 and pyg v1.6.1, it runs good. However, if I use pytorch v1.7.0 and pyg v1.6.1, an ValueError raised.
`ValueError: optimizer got an empty parameter list`
Maybe there is a compatibility problem between pytorch 1.7 and pyg.

**Comment by rusty1s** [comment]
This seems to be a newly introduced bug in PyTorch, see [here](https://discuss.pytorch.org/t/valueerror-optimizer-got-an-empty-parameter-list-when-its-clearly-not-empty/102264/2).

Fixable by replacing
```python
optimizer = torch.optim.SparseAdam(model.parameters(), lr=0.01)
```
with
```python
optimizer = torch.optim.SparseAdam(list(model.parameters()), lr=0.01)
```
I fixed it in the `node2vec` example.
