### ISSUE TITLE
Shape mismatch between sigma and mu in Monet

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [rusty1s/pytorch_geometric#186]
Dear @rusty1s ,

First of all, thank you for the amazing framework!

There is probably an error in the implementation of Monet from "Geometric deep learning on graphs and manifolds using mixture model CNNs". 

Here

https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gmm_conv.py#L44

you define sigma to have the same shape as mu while in the paper, they have two different shapes, [d,d] and [d,1] respectively.

![image](https://user-images.githubusercontent.com/15908060/55561904-40759480-56f3-11e9-9dc6-e0230e767021.png)

Cheers,

Francesco Saverio

**Comment by rusty1s** [comment]
This is not a bug, because \sigma has only diagonal elements.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you for the fast answer :) 

Sorry, I am not sure I understand. In the paper they were very clear, it should be a [d,d]. Probably I am missing something, can you help me to understand why it is not wrong?

**Comment by rusty1s** [comment]
The paper states: „We further restrict the covariances to have diagonal form, resulting in 2d parameters per kernel.“ So instead of d^2 parameters for sigma, we just have d parameters denoting its diagonal elements.

**Comment by FrancescoSaverioZuppichini** [comment]
So, it should be just a [d,1] like mu? I am correct?

**Comment by rusty1s** [comment]
Yes.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you a lot, really. We can close it, sorry to misunderstood the paper.

**Comment by rusty1s** [comment]
No problem :) Glad I could help.
