### ISSUE TITLE
AutoEncoder on whole graphs : Index out of range

### ISSUE THREAD

**Issue by weimdall** [rusty1s/pytorch_geometric#1861]
## ❓ Questions & Help

This question is similar to #1606 

I am trying to train an auto-encoder on a dataset that contains several graphs.

In the example [autoencoder.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py), the auto-encoder is trained on a dataset that contains only one graph, 
when I tried to adapt the code to my problem, I got a weird error after a random number of iteration : Index out of range in self

You can check my code on [Google Colab](https://colab.research.google.com/drive/1SZzrh5zhCN9nThmE9pkDT0tlbllg83jl?usp=sharing)

Am I doing something wrong, or is it a bug ?

Thank you in advance

**Comment by rusty1s** [comment]
You need to remove the `cached=True` argument in `GCNConv` when operating on multiple graphs. 

Furthermore, note that `optimizer.zero_grad()` needs to be placed inside the data iterator routine.

**Comment by weimdall** [comment]
Sorry, I forgot to answer.
Thank you a lot, that worked :partying_face:
