### ISSUE TITLE
DISJOINT GRAPHS BATCH TRAINING

### ISSUE THREAD

**Issue by tulasiram58827** [rusty1s/pytorch_geometric#1863]
## ❓ Questions & Help

I am working on TV station political advertising disclosure forms data where I am constructing each form(document) as a graph where nodes represent words similarly for each node(word in this case) I created some features. I have multiple documents and each document has different nodes. So for example assuming I has 5 documents and for each node we have 10 features. We need to classify each node into one of the available classes. (Assume we have 5 classes)

This is how it looks:

|Document No    |           Adjacency matrix shape      |       Features shape             |          Labels      |
| :------------------- | :------------------------------------------   |  ----------------------------------- |----------------------|
|Document 1      |                (110X100)                       |          (110X10)                     |             (110X5) |
|Document 2      |                (117X117)                       |          (117X10)                     |             (117X5) |
|Document3       |                (125X125)                       |         (125X10)                     |             (125X5) |

Lets say we have around 1000 documents in similar fashion. Now to train any GCN on this type of data how to batch the data and how to train any GCN

**Comment by rusty1s** [comment]
This is quite similar to the `PPI` dataset, which contains multiple graphs on which you want to label each node (see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ppi.py) for an example).
In general, all you need to do is pass your `dataset` into a `torch_geometric.data.DataLoader` and iterate over your dataset in batches:
```python
loader = torch_geometric.data.DataLoader(dataset, batch_size=..., shuffle=True)

for batch in loader:
     # Train just as you would do on a normal node classification task
```

**Comment by tulasiram58827** [comment]
I am getting this error:
>          
               size[dim] = int(index.max()) + 1
               out = torch.zeros(size, dtype=src.dtype, device=src.device)
               return out.scatter_add_(dim, index, src)
                        ~~~~~~~~~~~~~~~~ <--- HERE
               else:
                     return out.scatter_add_(dim, index, src)
               RuntimeError: index 221 is out of bounds for dimension 0 with size 201

This is the sample data object for your reference:
> 
     Data(edge_index=[2, 346], x=[201, 16], y=[201, 5])

**Comment by tulasiram58827** [comment]
That was my mistake while preparing data. I resolved it. Thanks for the pointers.
