### ISSUE TITLE
radius_graph wrong with 34 input points

### ISSUE THREAD

**Issue by mariogeiger** [rusty1s/pytorch_geometric#1867]
## 🐛 Bug

`radius_graph` gives wrong results when the number of point is greater or equal to 34. 

## To Reproduce

```
import torch
from torch_geometric.nn import radius_graph

n = 34
index = radius_graph(torch.randn(n, 3), 10.0, None)

edges = {(a.item(), b.item()) for a, b in zip(*index)}
for a, b in edges:
    assert (b, a) in edges, (a, b)
```

## Expected behavior

I expect the edge (a,b) and (b,a) to be present in the output.

## Environment

* OS: linux
* Python version: 3.8.2
* PyTorch version: 1.7.0
* CUDA/cuDNN version: none
* GCC version: do you really need that?
* Any other relevant information: I tried on two machines

**Comment by rusty1s** [comment]
You can set `max_num_neighbors` in `radius_graph` to a higher value. The default one is `32`, which limits the number of neighbors to 32.

**Comment by mariogeiger** [comment]
Oh noo, my bad then, sorry
