### ISSUE TITLE
AttributeError: 'TUDataset' object has no attribute '__data_list__'

### ISSUE THREAD

**Issue by m-Tajari** [rusty1s/pytorch_geometric#1883]
## ❓ Questions & Help

**hi,
when i tried to use pytorch_geometric in colab, i'm getting the following error message :|
is there any solution to this problem?**

/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/tu_dataset.py in __init__(self, root, name, transform, pre_transform, pre_filter, use_node_attr, use_edge_attr, cleaned)
     63         self.cleaned = cleaned
     64         super(TUDataset, self).__init__(root, transform, pre_transform,
---> 65                                         pre_filter)
     66         self.data, self.slices = torch.load(self.processed_paths[0])
     67         if self.data.x is not None and not use_node_attr:

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     52                  pre_filter=None):
     53         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 54                                               pre_filter)
     55         self.data, self.slices = None, None
     56         self.__data_list__ = None

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     90 
     91         if 'process' in self.__class__.__dict__.keys():
---> 92             self._process()
     93 
     94     def indices(self):

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py in _process(self)
    163 
    164         makedirs(self.processed_dir)
--> 165         self.process()
    166 
    167         path = osp.join(self.processed_dir, 'pre_transform.pt')

/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/tu_dataset.py in process(self)
    140 
    141         if self.pre_transform is not None:
--> 142             data_list = [self.get(idx) for idx in range(len(self))]
    143             data_list = [self.pre_transform(data) for data in data_list]
    144             self.data, self.slices = self.collate(data_list)

/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/tu_dataset.py in <listcomp>(.0)
    140 
    141         if self.pre_transform is not None:
--> 142             data_list = [self.get(idx) for idx in range(len(self))]
    143             data_list = [self.pre_transform(data) for data in data_list]
    144             self.data, self.slices = self.collate(data_list)

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py in get(self, idx)
     68 
     69     def get(self, idx):
---> 70         if self.__data_list__ is None:
     71             self.__data_list__ = self.len() * [None]
     72         else:

AttributeError: 'TUDataset' object has no attribute '__data_list__'

**Comment by rusty1s** [comment]
Which version of PyG are you using?

**Comment by m-Tajari** [comment]
torch-cluster                   1.5.8
torch-geometric             1.6.2
torch-scatter                   2.0.5
torch-sparse                   0.6.8
torch-spline-conv           1.2.0

**Comment by rusty1s** [comment]
Oh shit, you are right. It fails when using `pre_transform`. This is now fixed in master. I will update the version soon. Meanwhile, please install from master via:
```python
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by m-Tajari** [comment]
thank you
