### ISSUE TITLE
Whether the size of edge_index must be (2, num_edges) or not?

### ISSUE THREAD

**Issue by fanyangfanyang** [rusty1s/pytorch_geometric#1884]
## ❓ Questions & Help
The docs said that the size of edge_index could be (row, col). However, it always reports an error because of the codes in Function \___check_input\___ , "assert edge_index.size(0) == 2" .  Is it possible to make GNNConv layer accept the input of edge_index with size (row, col)?

**Comment by rusty1s** [comment]
This is a design decision that is hard to fix by now. What's the problem with converting your tuple to a `torch.Tensor`?

**Comment by fanyangfanyang** [comment]
> This is a design decision that is hard to fix by now. What's the problem with converting your tuple to a `torch.Tensor`?

It works well. I just found something inconsistent with the description in docs, and wondered whether I used it in a wrong way.  Thank you for your reply.
