### ISSUE TITLE
how to flip the adj matrix in tensor type back to edge_index and edge_ attr

### ISSUE THREAD

**Issue by alienx-zero** [rusty1s/pytorch_geometric#1888]
## ❓ Questions & Help

Hi, folks, I use to_dense_adj convert batched sparse adjacency matrices given by edge indices and edge attributes to a single dense batched adjacency matrix, but later how to convert it back to corresponging edge indices and edge attributes. Does any function bulit-in supply this work?

**Comment by rusty1s** [comment]
You can do this by making use of `nonzero`, e.g.:
```python
adj = ... # [num_nodes, num_nodes]
edge_index = adj.nonzero(as_tuple=False).t()
edge_weight = adj[edge_index[0], edge_index[1]]
```

**Comment by alienx-zero** [comment]
> You can do this by making use of `nonzero`, e.g.:
> 
> ```python
> adj = ... # [num_nodes, num_nodes]
> edge_index = adj.nonzero(as_tuple=False).t()
> edge_weight = adj[edge_index[0], edge_index[1]]
> ```

great, thanks for sharing
