### ISSUE TITLE
Download links of Entities datasets are invalid.

### ISSUE THREAD

**Issue by VirtueHX** [rusty1s/pytorch_geometric#1889]
## 🐛 Bug
I tried to use torch_geometric.datasets.Entities, but the download link of it, such as the AIFB dataset link https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/aifb.tgz, was not valid. 

The information returned is as follows:
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>dgl.ai</BucketName>
<RequestId>87AD425AD45221F2</RequestId>
<HostId>wZvb5nsx9RbJMCadoP3czTH7FKpRBAfK450jVIRNOzHcwxTS5F8vGD7nKLyKGJucXog+cnqxrl8=</HostId>
</Error>
```
It seems that this bucket cannot visit.
Could you find another download URLs?

**Comment by rusty1s** [comment]
This should have been already fixed with PyG >= 1.6.2.
