### ISSUE TITLE
enzymes_topk_pool error

### ISSUE THREAD

**Issue by neon5d** [rusty1s/pytorch_geometric#189]
## 🐛 Bug

return aggr_out + self.lin(x)
The size of tensor a (1600) must match the size of tensor b (1601) at non-singleton dimension 0

## To Reproduce
run enzymes_topk_pool example

1.
1.
1.

## Environment

* OS: Windows
* Python version: 3.6.2
* PyTorch version: 1.0.1
* CUDA/cuDNN version: 10.1
* GCC version: VS 2017
* Any other relevant information:
torch-scatter 1.1.2

**Comment by rusty1s** [comment]
Hi, I can not reproduce your error. What `torch-geometric` version/commit are you using?

**Comment by rusty1s** [comment]
Ah, reproducible with current `torch-geometric` from pip, but already fixed in master. I crafted a new bugfix release with 1.1.2. Please upgrade :)

**Comment by neon5d** [comment]
Thank you. It works.
