### ISSUE TITLE
Inconsistency of documentation with actual code in DeepGCNLayer

### ISSUE THREAD

**Issue by THinnerichs** [rusty1s/pytorch_geometric#1890]
## 🐛 Bug

```DeepGCNLayer``` [documentation states](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.models.DeepGCNLayer) that is does 

GraphConv→Normalization→Activation→Res/Dense/Plain→Dropout

if ```block='res'/'dense'/'plain' ```. However, the tailing dropout is never applied in the [forward method](https://github.com/rusty1s/pytorch_geometric/blob/e135248eb7abc27ff3ca5b5b74107fad48424288/torch_geometric/nn/models/deepgcn.py#L67) and is thus somewhat misleading. Sorry for if I misunderstood or missed anything.

**Comment by rusty1s** [comment]
Good spot! Fixed in master.

**Comment by THinnerichs** [comment]
You are welcome :)
