### ISSUE TITLE
ShapeNet dataset classes

### ISSUE THREAD

**Issue by AronNoren** [rusty1s/pytorch_geometric#1891]
## dataset.num_classes is 50 when we only use 2 categories for ShapeNet
Hi, I am new to Pytorch geometric and was trying to recreate the point cloud classification example but with ShapeNet instead of GeometricShapes. Anyways, when downloading the ShapeNet dataset I have some issues understanding the dataset parameters. 
Example code:
````
from torch_geometric.datasets import ShapeNet


dataset = ShapeNet(root='data/ShapeNet',categories = ['Airplane','Car'])
print(dataset)
print(dataset[0])
print('first 10 class labels for first graph: ' + str(dataset[0].y[0:10]))
print('num classes: ' + str(dataset.num_classes))
````
ShapeNet uses one label per node, intuitively I thought these labels would all be the same for each graph, either Airplane (0) or Car (1). Furthermore, I was expecting dataset.num_classes would be '2' as we only have Airplanes and Cars.
The outputs are however

```
ShapeNet(3089, categories=['Airplane', 'Car'])
Data(category=[1], pos=[2518, 3], x=[2518, 3], y=[2518])
first 10 class labels for first graph: tensor([0, 0, 3, 3, 0, 0, 1, 1, 3, 3])
num classes: 50
```
I have probably misunderstood something, but how come n_Classes is 50 and dataset[0].y corresponds to numerous classes?
Thankful for any insight :)

**Comment by rusty1s** [comment]
The ShapeNet dataset is a segmentation dataset, so each point has a label instead of each graph. For example, `Airplane` has labels such as "wing".

**Comment by AronNoren** [comment]
Oh, I see, that makes sense, 
Thank you for the quick answer!
