### ISSUE TITLE
Cannot download whl files

### ISSUE THREAD

**Issue by zlpure** [rusty1s/pytorch_geometric#1892]
Hi, when I install pytorch geometric via Binaries according to the official installation guide:
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
```
I got the following errors:
```
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff5fc8fb990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
But there was no such problem before.

**Comment by rusty1s** [comment]
Can you access [https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl](https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl)?

**Comment by zlpure** [comment]
> Can you access https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl?

Yes, I can.  Thanks for your help.

**Comment by rusty1s** [comment]
Does `pip install https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl` work for you?

**Comment by zlpure** [comment]
> Does `pip install https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp37-cp37m-linux_x86_64.whl` work for you?

Yes, it works.
