### ISSUE TITLE
Mutag dataset node feature

### ISSUE THREAD

**Issue by Jo-wang** [rusty1s/pytorch_geometric#1896]
## ❓ Questions & Help

Hi, I'm new in GNN area and just a bit confused about how to change the node feature in mutag dataset back to the representation of atoms.

Thanks.

**Comment by rusty1s** [comment]
The README of `MUTAG` defines the mapping:
```
Node labels:

  0  C
  1  N
  2  O
  3  F
  4  I
  5  Cl
  6  Br

Edge labels:

  0  aromatic
  1  single
  2  double
  3  triple
```

**Comment by Jo-wang** [comment]
Thank you!
