### ISSUE TITLE
ShapeNet part dataset in torch geometric from col 3 to 6 represent the what?

### ISSUE THREAD

**Issue by aGIToz** [rusty1s/pytorch_geometric#1898]
Hello,

The shapnet part dataset which comes with torch_geoemtric, the 0:3 columns represents the position, last 7 column represents the class of the each node (point), col 3:6 represents the signal on the node, but what signal? Is it the color, normal?

Best

**Comment by aGIToz** [comment]
It seems that col 3:6 rather represents the vertex normal of the node. Does the torch_geometric comes with any 3d dataset in signal on the node is rather color (texture)?

**Comment by rusty1s** [comment]
That's correct. Those are the normal vectors of points. Currently, we do not provide a point cloud dataset with texture information.
