### ISSUE TITLE
Did you change the way for storing the wheels on the server?

### ISSUE THREAD

**Issue by pafi-code** [rusty1s/pytorch_geometric#1903]
## 📚 Installation

We are using pytorch-geometrics for our projects. Since this week it takes ages to install the dependencies like `torch-scatter` in the build pipeline of our CI.
We assume that the packages are actually build on the server during installation. Was it always like this?
We changed the installation to

`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html`

Our CI pipeline took around 20 mins previously. Now it is at 60 mins.
We are only using cpu versions for the pipelines.

Do you have any suggestions?
Thanks in advance!

**Comment by rusty1s** [comment]
Yeah, the wheel links changed due to recent `pip` changes. In your case, it does look like it cannot find a wheel that matches with your OS/Python version, so it will try to compile the dependencies from source. What is your OS/Python version?

**Comment by pafi-code** [comment]
Hey there we are using the python3.6 docker image from bitbucket. They say that they are using the default official python docker images. It's probably [this one](https://github.com/docker-library/python/blob/c15acf875a4d4ae760bcd793742906873fd9e57b/3.6/buster/Dockerfile).

However I don't know currently what processor architecture is used by bitbucket...

**Comment by rusty1s** [comment]
Thanks. Can you do me a favour and test if the same problem occurs when using PyTorch 1.6.0 or PyTorch 1.7.0?

**Comment by rusty1s** [comment]
You can alternative try to use
```
pip install --verbose --no-index torch-scatter -f ...
```
and let me know the output.

**Comment by pafi-code** [comment]
Sorry for the late response. We probably need to make some time to test this properly. I don't think that this will happen anytime soon, since vacations are starting.
Regarding the pip install output, I will have a look asap.

**Comment by pafi-code** [comment]
So I tried your pip install. It seems like `--no-index` does the trick. Unfortunately I couldn't figure out why? Is it wrong installation order by pip else? Meaning that it first looks in Pypi and then in `--find-links`?

**Comment by rusty1s** [comment]
This isn't the case for me but I'm not sure. It's good to know that `--no-index` fixes it though :)

**Comment by pafi-code** [comment]
Hmm that's weird. The pip change log is also not really helping to find what caused this, because it was working without `--no-index` before.
Yes, maybe you can add it as a note in your ReadMes for trouble shooting :)
Should we close the issue?

**Comment by rusty1s** [comment]
Just added a comment to the installation doc :)
