### ISSUE TITLE
Why does GATConv model keep changing GPU RAM allocation?

### ISSUE THREAD

**Issue by chunyuma** [rusty1s/pytorch_geometric#1906]
## ❓ Questions & Help

Hi @rusty1s, I'm using [GATConv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GATConv) layer to train my model. Here is the forward part of the model:
```python
def forward(self, x, adjs, n_id):
    for i, (edge_index, size) in enumerate(adjs):
        device = 'cuda:'+ str(i % torch.cuda.device_count())
        x = x.to(device)
        x_target = x[:size[1]].to(device)
        edge_index = edge_index.to(device)
        x = self.convs[i]((x, x_target), edge_index)
        x = F.elu(x)
        x = F.dropout(x, p=self.dropout_p, training=self.training)
```

I have around 400 batches (each one is a 3-hop-layer subgraph). 

For the first batch, its subgraph structure is like this:
```
[(edge_index=tensor([[    0,     0,     0,  ..., 31739, 31740, 31741],
          [   98,    99,   100,  ..., 22819, 22819, 22819]]),
  size=(31742, 22833)),
 edge_index=(tensor([[    0,     0,     0,  ..., 22831, 22832, 22832],
          [   98,    99,   100,  ...,  2892,  2894,  2895]]),
  size=(22833, 2897)),
 edge_index=(tensor([[   5,    5,   26,  ..., 2894, 2895, 2896],
          [   6,   20,    6,  ...,   97,   97,   97]]),
  size=(2897, 98))]
```
The model trained on this subgraph consumed ~3837M GPU RAM. 

Then when I trained on the second subgraph with structure:
```
[(edge_index=tensor([[    0,     0,     0,  ..., 32140, 32141, 32142],
          [    9,    13,    16,  ..., 24157, 24174, 24174]]),
  size=(32143, 24177)),
 (edge_index=tensor([[    0,     0,     0,  ..., 24174, 24175, 24176],
          [    9,    13,    16,  ...,  3490,  3490,  3490]]),
  size(24177, 3492)),
 (edge_index=tensor([[   0,    0,    0,  ..., 3489, 3490, 3491],
          [   9,   13,   16,  ...,   95,   95,   95]]),
  size=(3492, 96))]
```
the GPU RAM usage reached to ~6565M.

The GPU RAM usage didn't change when I trained the model on the third batch. But for the forth batch, its subgraph structure is:
```
[(edge_index=tensor([[    0,     0,     0,  ..., 33620, 33621, 33622],
          [   94,    95,    96,  ..., 25829, 25836, 25850]]),
  size=(33623, 25914)),
 (edge_index=tensor([[    0,     0,     0,  ..., 25911, 25912, 25913],
          [   94,    95,    96,  ...,  4846,  4846,  4847]]),
  size=(25914, 4848)),
 (edge_index=tensor([[   1,    7,    7,  ..., 4845, 4846, 4847],
          [  41,   24,   50,  ...,   93,   93,   93]]),
  size=(4848, 94))]
```
The GPU RAM usage reached to ~9349M. And this value didn't change until the model was trained on the 200th batch. For the 200th subgraph, its structure is:

```
[(edge_index=tensor([[    1,     1,     1,  ..., 33882, 33883, 33884],
          [  416,   417,   418,  ..., 25862, 25886, 25888]]),
  size=(33885, 25891)),
 (edge_index=tensor([[    1,     1,     1,  ..., 25888, 25889, 25890],
          [  416,   417,   418,  ...,  4650,  4651,  4651]]),
  size=(25891, 4652)),
 (edge_index=tensor([[  10,   10,   19,  ..., 4649, 4650, 4651],
          [  21,   93,   45,  ...,   97,   98,   98]]),
  size=(4652, 99))]
```

and the GPU RAM usage reduced to ~3963M. And then it was also changed to ~6366M. 

For the second epoch, this value didn't change and stay in ~6366M. 

As you might see, the sizes of these subgraphs are almost the same. But the strange thing here is that the `GATConv` layer consumes different GPU RAM for different subgraphs. For some smaller subgraphs, it even used more GPU RAM. I investigated the source code of `GATConv` but didn't find something special. Do you have any ideas why the execution of `GATConv` layer on the similar subgraphs causes huge different GPU RAM usage? And why GPU RAM usage didn't change in the second epoch for the same sets of subgraphs? Thank you!

**Comment by rusty1s** [comment]
How did you benchmark memory usage? Did you use the PyTorch memory profiler or did you simply run `nvidia-smi`? In case of the latter, this might be expected since CUDA needs to allocate more memory for the second batch since it is a little bit bigger.

**Comment by chunyuma** [comment]
Thanks for your reply, @rusty1s. I just simply used `nvidia-smi` to benchmark memory usage. I understand that `nvidia-smi` might not be a professional tool for benchmarking memory usage but I think it might tell use something. I'm still curious about based on what factor the `GATConv` layer use gpu memory. If the GPU memory usage depends on the size of subgraph of each batch, I'm wondering why it dramatically decreased to ~3963M in the 200th batch in my case because the size of subgraph of 200th batch is actually a little bigger than the second one. 

Also, in the second epoch in my case, it is strange that the memory usage didn't change across all batches. This seems like contradict the assumption that the `GATConv` layer depends on the subgraph size to use gpu memory.

**Comment by rusty1s** [comment]
I'm not that familiar with PyTorch/CUDA memory management, but as far as i know, PyTorch/CUDA will allocate new memory in case the freed memory is not sufficient for the current batch. In case there is enough GPU memory left, it will potentially allocate completely new memory for the current batch (not re-using the old one). There is also the Python garbage collector doing it's work, which might not be called immediately once a batch is finished, which might lead to those effects.

I'm keen to look into it if you can provide a small benchmark snippet. However, IMHO, I'm still of the opinion that benchmarking memory is better done using Python/PyTorch tools.

**Comment by chunyuma** [comment]
Thanks @rusty1s.
