### ISSUE TITLE
How is the 'sparse block diagonal adjacency matrices (defined by edge_index and edge_attr)' described in the documentation created ?

### ISSUE THREAD

**Issue by lzzhaha** [rusty1s/pytorch_geometric#191]
Hi,

This is a fantastic library with very clear instruction. But I am just curious about a missing detail in the Mini-Batch Section of the documentation (https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#mini-batches). 

The documentation claims that a 'sparse block diagonal adjacency matrices (defined by edge_index and edge_attr)' will be created, but does not say any word about  **how they are defined**. The block was depicted as follows in the documentation:

![block](https://user-images.githubusercontent.com/23102813/55663797-cc073680-5855-11e9-99b7-59d07a1b4cf8.png)

And when I look at the example code right below it, it seems that no such block diagonal adjacency matrices is created at all except a **concatenated edge index array over all the graphs in the batch**. The code is as follows:

![block](https://user-images.githubusercontent.com/23102813/55663847-b21a2380-5856-11e9-8ad3-3ac136571cf4.png)

When I look further into the source code of DataLoader class (https://rusty1s.github.io/pytorch_geometric/build/html/_modules/torch_geometric/data/dataloader.html) and Batch class(https://rusty1s.github.io/pytorch_geometric/build/html/_modules/torch_geometric/data/batch.html#Batch.from_data_list), there seems to be no implementation of building the so-called 'sparse block diagonal adjacency matrices (defined by edge_index and edge_attr)'.

So how exactly is this 'sparse block diagonal adjacency matrices' created? And how does the edge index and edge feature matrices stored in the batch?

Thank you very much

**Comment by rusty1s** [comment]
Hi,
the block diagonal matrix is also only sparsely defined via `edge_index` (and `edge_attr`). Given the `edge_index` for each adjacency matrix in a python list `edge_indices`, the sparse diagonal matrix is defined by:
```python
diagonal_edge_indices = []
cumsum_nodes = 0
for edge_index in edge_indices:
    diagonal_edge_indices.append(edge_index + cumsum_nodes)
    cumsum_nodes += num_nodes  # (e.g. via edge_index.max() + 1
diagonal_edge_index = torch.cat(diagonal_edge_indices, dim=1)
```

**Comment by lzzhaha** [comment]
Thanks.  

But I am still confused about how you can **stack** the edge index by just adding scalars to a matrix with shape [2, num_edge]? Is it related to some specific way of storing sparse matrix? 

 And where did you put this piece of code in the library ?

**Comment by rusty1s** [comment]
`edge_index` denote the coordinates of all nonzero values in the adjacency matrix (known as the [COO format](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html#scipy.sparse.coo_matrix). By adding scalars to these tensors, the indices ger shifted to the stacked diagonal form. You can find the code for stacking esge indices [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py).

**Comment by lzzhaha** [comment]
Hi,

Thank you so much for your explanation. I understand it now. 

But from the definition of __cumsum__ function of Data object and the source  [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py), it is apparent that the edge_attr would be concatenated in the same way as node feature matrix instead of being stacked diagonally.

So I suggest that you modified the documentation accordingly.

Thanks.

**Comment by fffii** [comment]
> Hi, the block diagonal matrix is also only sparsely defined via `edge_index` (and `edge_attr`). Given the `edge_index` for each adjacency matrix in a python list `edge_indices`, the sparse diagonal matrix is defined by:
> 
> ```python
> diagonal_edge_indices = []
> cumsum_nodes = 0
> for edge_index in edge_indices:
>     diagonal_edge_indices.append(edge_index + cumsum_nodes)
>     cumsum_nodes += num_nodes  # (e.g. via edge_index.max() + 1
> diagonal_edge_index = torch.cat(diagonal_edge_indices, dim=1)
> ```
> 
> Note that we add the cumulated number of nodes to the current `edge_index` to stack them diagonally.

thanks so much, you are my hero!
