### ISSUE TITLE
Relative paths in pypi pages

### ISSUE THREAD

**Issue by trapexit** [rusty1s/pytorch_geometric#1919]
I work at a firm which uses Artifactory as a proxy for PyPi and we've looked to proxy pytorch-geometric's pypi wheel page and packages. The problem comes in that due to absolute links Artifactory is unable to proxy the wheel files. Is it possible to have relative links and use the webserver to redirect to S3 as you currently link to?

**Comment by rusty1s** [comment]
The wheel page now supports relative paths. Please let me know if this fixes your issues :)

**Comment by trapexit** [comment]
Looks to be working for us. Thanks. 

Is it not possible to leverage the main pypi repo for all of these? Seems like some projects put all variations of their libs into pypi such as mxnet.

**Comment by rusty1s** [comment]
This is sadly not an option since we need to provide wheels for the product of PyTorch and CUDA versions.

**Comment by trapexit** [comment]
Ah. Just too many versions. Certainly easier if you only need versions per CUDA version.

Thanks again.
