### ISSUE TITLE
Can't download any .whl from https://pytorch-geometric.com/whl/

### ISSUE THREAD

**Issue by hong-gaofeng** [rusty1s/pytorch_geometric#1920]
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information:

## Checklist

- [ ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

Can't download any .whl from https://pytorch-geometric.com/whl/     
ConnetTimeoutError

**Comment by hong-gaofeng** [comment]
> ## 📚 Installation
> ## Environment
> * OS:
> * Python version:
> * PyTorch version:
> * CUDA/cuDNN version:
> * GCC version:
> * How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
> * Any other relevant information:
> 
> ## Checklist
> * [ ]  I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
> * [ ]  I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
> * [ ]  I set up CUDA correctly and can compile CUDA code via `nvcc`.
> * [ ]  I do have multiple CUDA versions on my machine.
> 
> ## Additional context
> Can't download any .whl from https://pytorch-geometric.com/whl/
> ConnetTimeoutError



> ## 📚 Installation
> ## Environment
> * OS:
> * Python version:
> * PyTorch version:
> * CUDA/cuDNN version:
> * GCC version:
> * How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
> * Any other relevant information:
> 
> ## Checklist
> * [ ]  I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
> * [ ]  I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
> * [ ]  I set up CUDA correctly and can compile CUDA code via `nvcc`.
> * [ ]  I do have multiple CUDA versions on my machine.
> 
> ## Additional context
> Can't download any .whl from https://pytorch-geometric.com/whl/
> ConnetTimeoutError

**Comment by rusty1s** [comment]
https://github.com/rusty1s/pytorch_geometric/issues/1922
