### ISSUE TITLE
Cannot import name 'gcn_norm' from 'torch_geometric.nn.conv.gcn_conv'

### ISSUE THREAD

**Issue by gamzeakyol** [rusty1s/pytorch_geometric#1926]
I would like to use GCNNorm class from torch_geometric.transforms library but when I import 
**from torch_geometric.nn.conv.gcn_conv import gcn_norm** 
to use this class, I encountered this error. How can I use this class, could you give an example usage?

In addition, are all augmentations included in torch_geometric.transforms library or is there any other library that includes augmentation methods?

Thank you.

Best,

**Comment by rusty1s** [comment]
Which PyG version are you using?

**Comment by gamzeakyol** [comment]
I am using torch-geometric version 1.4.1.

**Comment by rusty1s** [comment]
I see. That method does not exist in PyG 1.4.1 yet. You can use `GCNConv.norm(...)` instead, see [here](https://github.com/rusty1s/pytorch_geometric/blob/1.4.1/torch_geometric/nn/conv/gcn_conv.py#L68).

**Comment by gamzeakyol** [comment]
Thank you. Can I use it for normalization?

**Comment by gamzeakyol** [comment]
The function returns not the data, but two different outputs. What are the outputs stand for?

**Comment by rusty1s** [comment]
The outputs are the new `edge_index` and `edge_weight`. Therefore, you can do:
```python
data.edge_index, data.edge_weight = GCNConv.norm(data.edge_index, data.num_nodes, data.edge_weight)
```

**Comment by gamzeakyol** [comment]
Okay, thank you so much.
