### ISSUE TITLE
Question about data snooping problem when spliting train / test data

### ISSUE THREAD

**Issue by hoangph-1744** [rusty1s/pytorch_geometric#1928]
Hi, thank you for the awesome library, but I have a question about the train/test split process in the example code

For example, in [GCN example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gcn.py#L40), 

```python
    def forward(self):
        x, edge_index, edge_weight = data.x, data.edge_index, data.edge_attr
        x = F.relu(self.conv1(x, edge_index, edge_weight))
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index, edge_weight)
        return F.log_softmax(x, dim=1)
```

it seems like a data snooping problem here, you trained on all data. And when evaluated on test data, you only get the corresponding result by boolean index filtering!

```python
@torch.no_grad()
def test():
    model.eval()
    logits, accs = model(), []
    for _, mask in data('train_mask', 'val_mask', 'test_mask'):
        pred = logits[mask].max(1)[1]
        acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
        accs.append(acc)
    return accs
```

Is there any incorrect with the example code? Thank you :bow:

**Comment by rusty1s** [comment]
There is no data snooping going on. While we use all node features in the model, during training, the model is only trained using training nodes (`out[data.train_mask]`). The same holds true while testing.

**Comment by hoangph-1744** [comment]
@rusty1s ah, I got it, thank you so much :bow:
