### ISSUE TITLE
A problem when changing the content of norm function in gcn_conv.py

### ISSUE THREAD

**Issue by mamengyiyi** [rusty1s/pytorch_geometric#193]
## ❓ Questions & Help

I tried to modify the `norm` function in `nn/conv/gcn_conv.py`. I test this function using same examples and got the same output. For example, below is one of my graph:
![0](https://user-images.githubusercontent.com/23417331/55706296-6fea1100-5a13-11e9-9248-759d75d7b624.png)
And I got the same output both in the modified `norm` function and un-modified `norm` function although the order of indices and value are different:
![1](https://user-images.githubusercontent.com/23417331/55706464-dd963d00-5a13-11e9-85da-ef96fffffeba.png)
But when I tried to use this modified `norm` function in the `Cora.py` example, I got a output of below:
![3](https://user-images.githubusercontent.com/23417331/55706686-63b28380-5a14-11e9-843a-9b733b80cdd9.png)
There is a problem that all the outputs are the same. I'm wondering what might cause this problem? Can you give me some help please?

**Comment by rusty1s** [comment]
I do not understand your question. Your `norm2` function looks exactly like our `norm` function. I wonder why the output of `norm` would be sorted. We do not do this in `GCNConv`.

**Comment by mamengyiyi** [comment]
norm2 is your norm function. I found what caused the error, thanks for your reply!

**Comment by rusty1s** [comment]
Ok :) Do you mind sharing?
