### ISSUE TITLE
Size Mismatch when trying to get node embedding and for link prediction task 

### ISSUE THREAD

**Issue by elbasir** [rusty1s/pytorch_geometric#1939]
## ❓ Questions & Help

I am trying to run a simple GCN to get the embedding of each node in the graph. My graph consists of 29289 nodes, 59225 edges and the feature size for each node is 436. If I define my features to be based on the identity matrix whose shape is 29289 * 29289 assuming no other features are available it works fine. However, using the current features of 436 for each node, I am getting a size mismatch error. Below is my simple code and the error I am getting.

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(features.shape[0], 436)
        self.conv2 = GCNConv(436, 128)

    def forward(self):        
        xs = [data.x]
        s = self.conv1(xs[-1], data.edge_index)
        s = self.conv2(s, data.edge_index)
        return s

    
    optimizer.zero_grad()

    x, edge_index = data.x, data.edge_index

    node_embd = model()
    loss = F.binary_cross_entropy_with_logits(embed, data.x)
    loss.backward()
    optimizer.step()
    embedding.append(embed)

---------------------------------------------------------------------------

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-41-bec854094da8> in <module>
>       2 embed = 0
>       3 for epoch in range(1, 501):
> ----> 4     embed = train()
>       5     embedding.append(embed)
> 
> <ipython-input-40-1681a51ef620> in train()
>       5     x, edge_index = data.x, data.edge_index
>       6 
> ----> 7     node_embd = model()
>       8     print("X: ", node_embd)
>       9     #link_labels = get_link_labels(pos_edge_index, neg_edge_index)
> 
> ~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> <ipython-input-37-24855032fa0b> in forward(self)
>      11         xs = [data.x]
>      12         #print(xs[-1].shape)
> ---> 13         s = self.conv1(xs[-1], data.edge_index)
>      14         xs = self.conv2(s, data.edge_index)
>      15         return xs
> 
> ~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> ~/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
>      85     def forward(self, x, edge_index, edge_weight=None):
>      86         """"""
> ---> 87         x = torch.matmul(x, self.weight)
>      88 
>      89         if self.cached and self.cached_result is not None:
> 
> RuntimeError: size mismatch, m1: [29289 x 436], m2: [29289 x 436] at 
> /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
> 

I also have tried to do run a code for link prediction using the same graph with its nodes, edges, and features, I keep getting the same error. I hope you can help me solve this issue, thanks.

**Comment by rusty1s** [comment]
What's the input shape of `x`? It seems to be `[29289, 436]` while `GCNConv` expects input shape of `[29289, 29289]` (at least you define it that way). Note that `GCNConv` takes two arguments: the input and output feature dimensionality, not the number of nodes.

**Comment by elbasir** [comment]
True, the input of x is [29289, 436], should I change the shape of x to what?

**Comment by rusty1s** [comment]
Just define `self.conv1` as `self.conv1 = GCNConv(436, 436)`.

**Comment by elbasir** [comment]
I got this error for now when I used `self.conv1 = GCNConv(436, 436)`

> AttributeError: 'NoneType' object has no attribute 'size'

**Comment by rusty1s** [comment]
That should not be caused by the command above. Did you change anything else?

**Comment by elbasir** [comment]
No, here is what I got when I used that line of code

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-61-2689a1856a0d> in <module>
>      20 x, edge_index = data.x, data.edge_index
>      21 
> ---> 22 node_embd = model()
>      23 loss = F.binary_cross_entropy_with_logits(node_embd, data.x)
>      24 loss.backward()
> 
> ~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> <ipython-input-61-2689a1856a0d> in forward(self)
>       7     def forward(self):
>       8         xs = [data.x]
> ----> 9         s = self.conv1(xs[-1], data.edge_index)
>      10         s = self.conv2(s, data.edge_index)
>      11         return s
> 
> ~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     530             result = self._slow_forward(*input, **kwargs)
>     531         else:
> --> 532             result = self.forward(*input, **kwargs)
>     533         for hook in self._forward_hooks.values():
>     534             hook_result = hook(self, input, result)
> 
> ~/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
>      96 
>      97         if not self.cached or self.cached_result is None:
> ---> 98             self.cached_num_edges = edge_index.size(1)
>      99             if self.normalize:
>     100                 edge_index, norm = self.norm(edge_index, x.size(self.node_dim),
> 
> AttributeError: 'NoneType' object has no attribute 'size'

**Comment by rusty1s** [comment]
Is `data.edge_index=None`?

**Comment by elbasir** [comment]
Yes it is None because I had to split my data using`data = train_test_split_edges(data)`

**Comment by rusty1s** [comment]
Well, then you need to pass `data.train_pos_edge_index`.

**Comment by elbasir** [comment]
Thanks, I have passed `data.train_pos_edge_index`  and the new error is related to the output where it asks me to have the same size for the target and input

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-6-00687ff954d4> in <module>
>      10     node_embd = model(x, train_pos_edge_index)
>      11     print(node_embd.shape)
> ---> 12     loss = F.binary_cross_entropy_with_logits(node_embd, data.x)
>      13     loss.backward()
>      14     optimizer.step()
> 
> ~/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
>    2122 
>    2123     if not (target.size() == input.size()):
> -> 2124         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
>    2125 
>    2126     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
> 
> ValueError: Target size (torch.Size([29289, 436])) must be the same as input size (torch.Size([29289, 128]))

**Comment by rusty1s** [comment]
Yes, there is a size mismatch in the loss function. Your second GCN needs to map to the correct output dimension: in that case 436 (if you want to reconstruct features?)

**Comment by elbasir** [comment]
My purpose here is to get the embedding of each node through GCN but not through for example Graph-Autoencoder!

**Comment by rusty1s** [comment]
Well, then the last GCN layer needs to output a feature dimensionality of 436:
```python
self.conv2 = GCNConv(input_channels, 436)
```

**Comment by elbasir** [comment]
Thanks for your answer, my objective is to have a smaller dimensionality, i.e. 8 or 16, would that be possible?

**Comment by rusty1s** [comment]
You need to decrease the hidden feature dimensionality for this, so that node features go through a bottleneck. The output dimension should be 436 nonetheless since you want to train against your initial features.

**Comment by elbasir** [comment]
Thanks for your time, I appreciate it a lot.
