### ISSUE TITLE
Program is stuck when importing torch_geometric!

### ISSUE THREAD

**Issue by csyhy1986** [rusty1s/pytorch_geometric#1943]
## Environment

* OS: windows 10
* Python version: 3.7.8
* PyTorch version: 1.7.0
* CUDA/cuDNN version:cu110
* GCC version: None
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-geometric
* Any other relevant information:

## Checklist

- [ √] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [√ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [√ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [× ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Mh, can you run `torch.jit._state.disable()` before importing `torch_geometric`?

**Comment by csyhy1986** [comment]
> Mh, can you run `torch.jit._state.disable()` before importing `torch_geometric`?

It doesn't work, and it sticks here all night.

**Comment by csyhy1986** [comment]
![捕获](https://user-images.githubusercontent.com/42562649/102864887-dfb26080-446f-11eb-826a-0b4aa3b83b87.JPG)

**Comment by rusty1s** [comment]
Mh, does the same happen if you only import `torch-scatter`, `torch-sparse` and so on?

To track down the issue, it would be great to see which subpackage is causing this by manually importing them, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/__init__.py).

**Comment by csyhy1986** [comment]
No, only torch_geometric can not be imported, other modules have no problem.
![捕获](https://user-images.githubusercontent.com/42562649/103046506-82c7bf00-45c3-11eb-9d3f-06839a1a740b.JPG)

**Comment by rusty1s** [comment]
Ok, great! And what about importing the [PyG submodules](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/__init__.py) one-by-one?

**Comment by csyhy1986** [comment]
![捕获](https://user-images.githubusercontent.com/42562649/103091926-a412c480-4630-11eb-814d-47db822f68c3.JPG)
An error happens when importing .debug.

**Comment by rusty1s** [comment]
Yeah, you can safely ignore that and proceed with the other ones.

**Comment by csyhy1986** [comment]
Some times only torch_geometric.nn can not be imported, sometimes all of them can not be imported.

**Comment by XikunZhang** [comment]
[All these 4 submodules](https://github.com/rusty1s/pytorch_geometric/blob/343e64798b08d33078dc037642bda34ae40ae626/torch_geometric/__init__.py#L4-L7) got stuck for me.

I use cuda 10.1 and python 3.7. I try both pytorch 1.8.0 and pytorch 1.4.0 and in both cases, this issue occurs.

**Comment by rusty1s** [comment]
Can you install PyG from source and try again?
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
Do all of these submodules cannot be imported?

**Comment by XikunZhang** [comment]
Problem solved. Thanks a lot, @rusty1s! Just curious: does this installation from source automatically figure out what cuda version I want to use or just build it for all the cuda versions available on my machine?

**Comment by jshepp27** [comment]
Hi @rusty1s - I have the exact same issue. Installing from source didn't work. When running import torch_geometric, my machine hangs for eternity ....

**Comment by rusty1s** [comment]
Is it possible to debug at which import/in which file they program gets stuck?
