### ISSUE TITLE
Questions about mixing pytorch and pytorch_geometric

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#1944]
## ❓ Questions & Help

Can PyTorch and pytorch_geometric be used together? If I want to use Pytorch to extract the feature vectors of several individuals in a certain image and build a graph with them to obtain the feature matrix ```X ```and the adjacance matrix ```A```, can I continue to use pytorch_geometric to process these two matrices in the network?Such as convolution and pooling and so on. They're in the same network, of course

Thank you for your answer!

**Comment by rusty1s** [comment]
What do you mean with XS? PyTorch and PyTorch Geometric can be mixed with no problems. You can use, e.g., a CNN to extract features from an image and input those into a GNN in an end-to-end fashion.

**Comment by jiaruHithub** [comment]
> What do you mean with XS? PyTorch and PyTorch Geometric can be mixed with no problems. You can use, e.g., a CNN to extract features from an image and input those into a GNN in an end-to-end fashion.

Thank you. 
XS is my Spelling mistakes, sorry
