### ISSUE TITLE
Make Batch.from_data_list a @classmethod instead of @staticmethod

### ISSUE THREAD

**Issue by jatentaki** [rusty1s/pytorch_geometric#1948]
## 🚀 Feature

As in the title.

## Motivation
I would like to subclass `Batch`, in order to add some custom properties and metadata but since from_data_list (the main way of creating `Batch`es) is implemented via `@staticmethod`, the following does not work:

```python
class GraphBatch(tg.data.Batch):
    def m_nn(self):
        return torch.cat([self.m_12, self.m_21], dim=1)

...

data_loader = DataLoader(..., collate_fn=GraphBatch.from_data_list)
```

because GraphBatch.from_data_list is actually the same as the original `tg.data.Batch`. If `Batch` used the `@classmethod` annotation, it would be automatically updated to the subclass that it is actually being called from.

**Comment by rusty1s** [comment]
You are right. It makes more sense to implement that as a `@classmethod`. I already changed it in master.
