### ISSUE TITLE
Fastest way to index into a batch

### ISSUE THREAD

**Issue by richardrl** [rusty1s/pytorch_geometric#1954]
What's the fastest way? I know we can turn the batch into a datalist, index that list, and re-batch it, but that seems slow.

**Comment by rusty1s** [comment]
That's indeed missing. I just pushed a `Batch.get_example(idx)` method to master.

**Comment by richardrl** [comment]
Shouldn't the API allow us to index a subset of the Batch? Like allowing arbitrary list style indexing (as if the Batch was a list object)

**Comment by rusty1s** [comment]
Good point. `Batch` does now support indexing and slicing:
```python
batch[0]
batch[2:4]
```
