### ISSUE TITLE
Import error in torch-scatter, torch-sparse and torch-geometric

### ISSUE THREAD

**Issue by Hibb-bb** [rusty1s/pytorch_geometric#1956]
## 📚 Installation

I install these packages through 

`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
`pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
`pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
`pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
`pip install torch-geometric`

And when I try to import torch-sparse and torch-geometric
it shows
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hibb1126/g2t/lib/python3.6/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/hibb1126/g2t/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory`

## Environment

* OS: Ubuntu 18
* Python version: 3.6
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 11.0
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source): pip3
* Any other relevant information:
Also, I was doing this in the virtual environment, and I **can** import torch_scatter without any error, but I cannot import other packages above.

**Comment by dwbressler** [comment]
I also have run into this problem repeatedly. Have spent >6 hours trying to install, no luck so far.

**Comment by dwbressler** [comment]
Also, setting LD_LIBRARY_PATH does not work.

**Comment by Hibb-bb** [comment]
> Also, setting LD_LIBRARY_PATH does not work.

Yeah, I’ve done that but it did not work.
And I still don’t know why my torch-scatter is fine but others are not.

**Comment by rusty1s** [comment]
Does `libcusparse.so.11` exists, and where is it located? What's the path of `LD_LIBRARY_PATH`?

**Comment by dwbressler** [comment]
I finally got mine working! I think it had to do with nvcc / cuda not being properly installed. Here's the full sequence of commands I needed to do on a fresh aws g4dn:

# STEP 1... correctly install nvcc / cuda (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions, and https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal) 

sudo apt-get install linux-headers-$(uname -r)
sudo apt autoremove

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb
sudo apt-key add /var/cuda-repo-10-2-local-10.2.89-440.33.01/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda

export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

nvcc --version

# STEP 2: install / create aliases for python, pip

#add "alias python=python3" to .bashrc
#source .bashrc 

sudo apt -y install python3-pip

#add "alias pip=pip3" to .bashrc
#source .bashrc

pip install --upgrade pip

# STEP 3: Install correct versions of torch, pyg, and other needed packages 

pip install torch==1.7.0 -f https://download.pytorch.org/whl/cu102/torch_stable.html

pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-$1.7.0+$cu102.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-$1.7.0+$cu102.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-$1.7.0+$cu102.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-$1.7.0+$cu102.html
pip install torch-geometric

**Comment by Hibb-bb** [comment]
> Does `libcusparse.so.11` exists, and where is it located? What's the path of `LD_LIBRARY_PATH`?

I did not find  `libcusparse.so.11`, and  `LD_LIBRARY_PATH` is `/usr/local/cuda/lib64:` . However, I am running my code on a server with gpu, not locally, so I'm not sure if that will be a problem.

**Comment by rusty1s** [comment]
So `libcusparse.so.11` does not exist in `/usr/local/cuda/lib64` on the server? That's a problem, since it needs to find it in order to run the code. If you do not have access rights to install CUDA, you can point `LD_LIBRARY_PATH` to the `cudatoolkit` version installed miniconda/PyTorch. Mine is located in `miniconda_path/lib`.

**Comment by PolarisRisingWar** [comment]
I find a similiar question.  
By command "nvcc -V" in bash, I find that my cuda version is 10.0. But coz other package depends on PyTorch version >=1.7, I installed PyTorch 1.7.1 with cuda version 9.2. Besides I used conda to install package cuda92. And I can use "import torch" without jumping error. But after installing torch_geometric (cuda92,pytorch1.7.1) , it gives me this bug: "OSError: libcusparse.so.9.2: cannot open shared object file: No such file or directory"  
And I used "export LD_LIBRARY_PATH="/home/(myusername)/anaconda3/lib:$LD_LIBRARY_PATH" in `.bashrc`, but it doesn't work. Besides, I find in `/home/(myusername)/anaconda3/lib` there is not libcusparse.so.9.2 too.  
And I used cloud server, too. It's hard for me to install CUDA in another version.

**Comment by rusty1s** [comment]
The conda PyTorch installation will install the `cudatoolkit` as well, so somewhere in your conda folder there needs to be such a file (it may also be in one of your conda environments).

**Comment by PolarisRisingWar** [comment]
OK, I solved my problem!  
I think it may because I used pip to install PyTorch, so I didn't install correct `cudatoolkit` package. And then I installed a false `cuda92` package (I used another anaconda mirror rather than by `-c pytorch`). So I especally installed it by `conda install cudatoolkit=9.2 -c pytorch`, and it works!

**Comment by Hibb-bb** [comment]
Hi, I solved my problem by downgrading pytorch and torch-geometric cuda11.0 to cuda10.2
it seems like when typing nvidia-smi, the GPU cuda version only shows the driver version of it. But I think mthe installed package
