### ISSUE TITLE
Help with modifying edge_index in multiple graph dataset such as TUDataset

### ISSUE THREAD

**Issue by msqiqi10** [rusty1s/pytorch_geometric#1957]
## ❓ Questions & Help

Is there a convenient way of modifying the edge_index in each graph in a multigraph dataset such as MUTAG in TUDataset?
It seems by directly accessing dataset[i]['edge_index'] in each data in the dataset is not modifying the dataset['edge_index'] in the dataset.

**Comment by rusty1s** [comment]
That's correct. Changes to `dataset[i]` do not effect the underlying dataset. You can use `transform` and `pre_transform` to implement that.

**Comment by rusty1s** [comment]
To follow up:
```
class MyPreTransform(object):
    def __call__(self, data):
        # Modify `data.edge_index`
        return data

dataset = TUDataset(root, 'MUTAG', pre_transform=MyPreTransform())
```

**Comment by msqiqi10** [comment]
> To follow up:
> 
> ```python
> class MyPreTransform(object):
>     def __call__(self, data):
>         # Modify `data.edge_index`
>         return data
> 
> dataset = TUDataset(root, 'MUTAG', pre_transform=MyPreTransform())
> ```

Thanks for your reply!
