### ISSUE TITLE
Torch-scatter installation error: fatal error C1083: Cannot open compiler generated file: '': Invalid argument

### ISSUE THREAD

**Issue by Morgam** [rusty1s/pytorch_geometric#1958]
## 🐛 Bug

When I run 

pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html

I get the following error (text removed under ...):

... 
... ivalue_inl.h(389): warning C4101: 'e': unreferenced local variable
... common.h(106): warning C4005: 'HAVE_SNPRINTF': macro redefinition
... pyerrors.h(315): note: see previous definition of 'HAVE_SNPRINTF'
... segment_coo_cpu.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
... cl.exe' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-scatter

## Environment

* OS:  Windows 10 (OS Build 19042.685)
* Python version: 3.8.5
* PyTorch version: 1.7.1
* CUDA/cuDNN version: cuda_11.2.r11.2 (with "nvcc --version" command)
* GCC version: "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64" with cl command

How to continue?

**Comment by rusty1s** [comment]
There are no 1.7.1 binaries yet, but the 1.7.0 should work as well. Try to uninstall `torch-scatter` and run:
```python
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
```

**Comment by Morgam** [comment]
I installed PyTorch 1.7.0 on CUDA 11.0 and now it works :) Thanks for hints.
