### ISSUE TITLE
Point cloud augmentation

### ISSUE THREAD

**Issue by neon5d** [rusty1s/pytorch_geometric#196]
## ❓ Questions & Help

I want to augment data with transform functions like 
transform = T.RandomScale (and T.RandomRotate)
But The transform functions seem to directly overwrite the transformed position to the original position (eg. data.pos = data.pos * scale).
My question is how I can use these transform functions for augmentation.

**Comment by rusty1s** [comment]
I do not see a problem here. Following PyTorch conventions, data objects are "re-initialized" upon every access. We use `RandomRotate` to augment our datasets all the time.

**Comment by neon5d** [comment]
Thank you for clarification.
How to add multiple transforms (e.g. RandomScale and RandomRotate)?
transform = T.RandomScale ??? T.RandomRotate

**Comment by neon5d** [comment]
I got it. Thank you.
