### ISSUE TITLE
Training speed up possible?

### ISSUE THREAD

**Issue by guiolpei** [rusty1s/pytorch_geometric#1960]
## ❓ Questions & Help

I have been performing some tests on hyperparameter optimization, trying to find the best combinations for my own scenario.

I first started using a server with a GeForce GTX 1080 Ti 11GB, but, recently, we have acquired an NVIDIA DGX A100 system where I have been assigned one of the eight A100-SXM4-40GB GPUs it contains.

My model consists of a 24 node graph with two features per node that outputs a binary classification. Network info and training is somewhat detailed at #1690.

Currently, all the data is only using a fraction of the GPU memory.

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> +-------------------------------+----------------------+----------------------+
> |   1  A100-SXM4-40GB      On   | 00000000:0F:00.0 Off |                    0 |
> | N/A   29C    P0    59W / 400W |   1498MiB / 40537MiB |     12%      Default |
> |                               |                      |             Disabled |
> +-------------------------------+----------------------+----------------------+

Is there any way to parallelize training to speed it up? 

There is a lot of GPU memory unused right now, could it be possible to duplicate the dataset in memory to perform training faster? I have tried different values for number of workers in the dataset loader class, with a value of 4 or 8 resulting in faster training. As far as I understand, this enables multi-process data loading, but all of the processes access the same dataset, not impacting GPU memory usage.

**Comment by rusty1s** [comment]
How big is your dataset actually? In order to increase GPU memory, you can always use larger batch sizes, but 14GB seems to be a lot to me already. `num_workers` indeed enables multi-processing, and might be definitely needed in case of small graphs with a large batch size.

**Comment by guiolpei** [comment]
My dataset contains only text files with a size of around 300 bytes per sample. I am using 12000 samples for training and 2000 samples for test. It is not very large in size.

Independently of batch size used for training (been testing for values of 1, 10 and 100), GPU usage is shown as `1498MiB / 40537MiB`. When using a batch size of 10, training is obviously much faster than using a batch size of 1.

**Comment by rusty1s** [comment]
Yeah, I see. But what's the problem with that? I'm not sure I understand.

**Comment by guiolpei** [comment]
I am just wondering if it would be possible to reduce training time by using more GPU memory (e.g. loading several times the dataset), since GPU memory is underused (only 1.5GB used out of 40GB available). Is there any way this could be done?

**Comment by rusty1s** [comment]
The only way to make training in this regard faster is to use a larger batch size.

**Comment by guiolpei** [comment]
Thank you, I proceed to close this issue.
