### ISSUE TITLE
size of data object

### ISSUE THREAD

**Issue by pvnieo** [rusty1s/pytorch_geometric#1966]
Hi, 

Is there a way to get the size that occupies `Data` object on cpu or gpu?

I know that `__repr__` should compute this, but when I `print(repr(my_data_object))`, it only returns the composition of the object?

Thank you in advance!

**Comment by pvnieo** [comment]
I just realized that `__repr__` returns the composition of the objects. Is there a method that returns the size on memory?

**Comment by rusty1s** [comment]
You can iterate over each attribute and sum up it size:
```python
return sum([v.element_size() * v.numel() for k, v in data])
```

**Comment by pvnieo** [comment]
Hi @rusty1s 
Thank your for your response. This answers my question!
Closing the issue!
