### ISSUE TITLE
A trivial typo. Should be post_layers instead of pre_layers.

### ISSUE THREAD

**Issue by phucdoitoan** [rusty1s/pytorch_geometric#1968]
https://github.com/rusty1s/pytorch_geometric/blob/3d454a374a1292f54f7b89f362f6a8107ddd6de5/torch_geometric/nn/conv/pna_conv.py#L118

**Comment by rusty1s** [comment]
What do you mean?

**Comment by rusty1s** [comment]
Ah, I see. It needs to iterate over the number of  post_layers.
