### ISSUE TITLE
How update works in torch_geometric?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#1969]
## ❓ Questions & Help
I found now most methods implemented in this repo do not include the `update` function. What is the mechanism behind this?

**Comment by rusty1s** [comment]
While the `update` method is still supported, it isn't really needed, since everything `update` does can also be performed in `forward` after `self.propagate`. Therefore, we dropped the `update` function in most of our implementations.

**Comment by mrbeann** [comment]
Thanks for clarify.
