### ISSUE TITLE
What should the edge_index be for a single node graph?

### ISSUE THREAD

**Issue by LanceKnight** [rusty1s/pytorch_geometric#1972]
## ❓ Questions & Help

Hi, I'm using PyG to deal with molecules. What if I only have one atom, i.e. one node, so there will be no edge, and what should the edge_index be?

**Comment by rusty1s** [comment]
Simply create an empty tensor:
```
torch.tensor(2, 0, dtype=torch.long)
```

**Comment by LanceKnight** [comment]
Oh, that's convienent. Thank you!
