### ISSUE TITLE
Time Series Dataset

### ISSUE THREAD

**Issue by ArashJavan** [rusty1s/pytorch_geometric#1978]
## ❓ Questions & Help

Hi and happy new year,

I am working on time-series data and would like to use this great repo to model the system as a GCNN (possibly with RNNs later).
At the moment I am struggling with the dataset preparation since I could not find any support for this type of dataset in pyGeo. My questions are:

1) How can create a dataset where each data is a sequence of the shape dim=(seq-length, #nodes, #features)?
2) How can I create a Batch of the shape dim=(batch-size, seq-len, #nodes, #features)?

Thanks!

**Comment by rusty1s** [comment]
I suggest to save the data as `[#nodes, seq-length, #features]`. With that, everything should work as expected without any further modification.

**Comment by tyua321** [comment]
Hi,

I am curious how you implement GNN on time series dataset, say how to generate the node and the edge? Can you please give little hint? Thank you!

**Comment by rusty1s** [comment]
What do you mean with generating the nodes and the edges? These should be provided by the dataset. If you can give more details, I might be able to help.

**Comment by tyua321** [comment]
I am new to the graph and just curious how time series data can be represented in a graph.
1. If every node represents one time step, the sequence is represented  as a graph, the graph is built as the node linked one by one from the start-time node to the end-time as a single line, but this kind of graph seems meaningless.
2.  if you treat one time series sequence as one node then generate some edges between each time series sequence.
Or can you provide some example of time series graph dataset?

**Comment by rusty1s** [comment]
In general, temporal graphs refers to graphs were nodes, edges or their features change over time. For example, you can think of a static graph with temporal node information. In addition, one could think of a stream of events (e.g. person A follows person B), that builts a graph over time (based on past events).

**Comment by ArashJavan** [comment]
> I suggest to save the data as `[#nodes, seq-length, #features]`. With that, everything should work as expected without any further modification.

Thanks for reply, dim=`[#nodes, seq-length, #features] seems to work 👍 
I will work on the dataset.  So for now I will close this thread.

Thanks
Arash
