### ISSUE TITLE
How to update the edge feature using attention attribute?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#1986]
## ❓ Questions & Help
I want to implement the transformer structure [here](https://arxiv.org/abs/2012.09699), but got a problem when I want to update the edge feature using the attention weight, it seems directly return it in message function not work.

**Comment by rusty1s** [comment]
You can only "return" modified edge features in a slightly hacky way or directly modify them outside of `message`:
```python
def forward(self, ...):
    out = self.propagate(edge_index, ...)
    edge_attr = self.__edge_attr__
    self.__edge_attr__ = None
  
def message(self, ...)
    edge_attr = ...  # Modify edge features
    self.__edge_attr__ == edge_attr
     ...
```

**Comment by mrbeann** [comment]
Thank you for your answer. To my understanding this may work more like this,
```python
transformer = TransConv()
for _ in range(100): 
    x, edge_attr = transformer(x, edge_index=edge_index, edge_attr=edge_attr)
```
Do this seems reasonable?

**Comment by rusty1s** [comment]
Yes, if you return both updated node and edge features in `forward`, that's how you would use it in a network architecture (although you might want to add non-linearities to both `x` and `edge_attr`).
