### ISSUE TITLE
Implementation of UNet-like architecture with Feature Steered Convolution as in original article

### ISSUE THREAD

**Issue by scarpma** [rusty1s/pytorch_geometric#1993]
## ❓ Questions & Help

Hi Matthias @rusty1s , your library is really beautiful. Thank you so much for your fantastic work.

**I need to implement the UNet-like architecture shown in the FeaStConv** [article](https://arxiv.org/abs/1706.05206). I already implemented the down-sampling part by using the pytorch_geometric's FeaStConv layer and Graclus clustering. My Question is how to implement the up-sampling done in the article (that, btw, is not very clear).

It seems to me that they apply a "standard" 1d transposed convolution to node features, since they use the graclus clustering algorithm to sort the nodes. Despite this I'm still a bit confused about:

1. what is the convenient way to apply the transposed convolution (I tried using _"torch.nn.ConvTranspose1d"_ by creating a dense batch with _"torch_geometric.utils.to_dense_batch"_, but I'm skeptical about the results) ;

2. how to convert _dense_batch_ back to _sparse_batch_;

3. how to match the number of nodes between the output of the transposed convolution and the features from the down-sampling part for concatenation (since graclus algorithm does not exactly halves the number of nodes the output of the transposed convolution has many more nodes than the down-sampling counterpart).

Thank you very much for your help !

**Comment by rusty1s** [comment]
Thanks for your interest!
IMO, from the paper, it is not exactly clear how the authors implemented the unpooling step. My guess is that they simply gather the features from super nodes back to the previous layer and apply a skip-connection. Does that sound correct to you?

In case you want to achieve that, there is no need to convert your node features into a dense representation via `to_dense_batch`. You can simply use `cluster` obtained from `graclus` to do that, *e.g.*:
```python
data.x = conv1(...)  # Run a FeaStConv layer...
cluster = graclus(...)
coarsened_data = max_pool(cluster, data, ...)
# coarsened_data.x = conv2(...) Run a FeaSTConv layer...

# Unpooling:
data.x = data.x + coarsened_data.x[cluster]
```

Regarding your additional question:
2. You can convert a `dense_batch` back to sparse via:
```python
dense_x, mask = to_dense_batch(x, batch)
x_orig = dense_x[mask]
```

**Comment by scarpma** [comment]
Thank you very much !

So, if I understand correctly, in this way you are "doubling" the coarsened data in order to match the previous shape. It seems correct to me !

In addition to this, in the mean time I was trying to follow the already implemented ` GraphUNet`. It seems to me that it performs something like a transposed strided convolution since the array is filled with zeros:
[ref](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/graph_unet.html#GraphUNet)
```
# UP SAMPLING PART
for i in range(self.depth):
    j = self.depth - 1 - i

    res = xs[j]                                   # COMING FROM PREVIOUS DOWNSAMPLING PART
    edge_index = edge_indices[j]    # COMING FROM PREVIOUS DOWNSAMPLING PART
    edge_weight = edge_weights[j] # COMING FROM PREVIOUS DOWNSAMPLING PART
    perm = perms[j]                         # COMING FROM PREVIOUS DOWNSAMPLING PART

    up = torch.zeros_like(res)
    up[perm] = x
    x = res + up if self.sum_res else torch.cat((res, up), dim=-1)

    x = self.up_convs[i](x, edge_index, edge_weight)
    x = self.act(x) if i < self.depth - 1 else x

return x
```

my doubt is "what is `perm`"and how can be computed from cluster. Would you think that this method would be better ?

Thank you very much again !

**Comment by rusty1s** [comment]
The GraphUNet implementation performs Top-k Pooling (which drops some nodes based on computed attention coefficients). Therefore, during upsampling, all nodes that got dropped are filled with zero values.

**Comment by scarpma** [comment]
Thanks,

anyway `coarsened_data.x[cluster]` gives me `IndexError: index 58439 is out of bounds for dimension 0 with size 38187`. 
In fact, `torch.max(cluster)` gives a value that exceeds `coarsened_data.x.shape[0]`.

I thought that `cluster` contained the index of each cluster for every node, and so `torch.max(cluster) = coarsened_data.x.shape[0] - 1`, but it appears to be different

**Comment by rusty1s** [comment]
Yeah, you need to call [`consecutive_cluster()`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/pool/consecutive.py) on the `cluster` vector before using it for indexing. Sorry, I missed that :)

**Comment by scarpma** [comment]
Thank you very much Matthias !

**Comment by scarpma** [comment]
Hi Matthias,
sorry but I have some doubts about another issue.

In the article I was mentioning (FeaStConvolution [link](https://arxiv.org/abs/1706.05206)) they apply a "linear layer" i.e. a convolution with a 1x1 kernel, with n output channels.

How can I implement this ? Maybe it is a dumb question, but I'm new to Pytorch and pytorch_geometric (I always worked with Tensorflow) .

Do I need to use a FeaStConv layer (with add_self_loops=True) with an empty adjacency matrix (or diagonal), or there is a more immediate way ?

Thank you again very much

**Comment by rusty1s** [comment]
A `1x`1 convolution on graphs just refers to using a `Linear` layer on the node features, e.g.:
```python
conv = FeaSTConv(...)
lin = torch.nn.Linear(...)

x = conv(x, edge_index).relu()
x = lin(x).relu()
```

**Comment by scarpma** [comment]
Thank you very much Matthias... Sorry for the dumb question !

**Comment by scarpma** [comment]
Hello @rusty1s  Matthias, thank you again for your help.

I did as you said, so I have this pseudo-code which works on cpu, but on gpu keeps giving me errors:

```python
def consecutive_cluster(src):
    unique, inv = torch.unique(src, sorted=True, return_inverse=True)
    perm = torch.arange(inv.size(0), dtype=inv.dtype, device=inv.device)
    perm = inv.new_empty(unique.size(0)).scatter_(0, inv, perm)
    return inv, perm

# down path
data.x = conv(data.x, data.edge_index)
cluster = graclus(data.edge_index)
cluster, _ = self.consecutive_cluster(cluster)
coarsened_data = max_pool(cluster, data)
coarsened_data.x = conv(coarsened_data.x, coarsened_data.edge_index)

# up path
upsampled_x = coarsened_data.x[cluster]
x = torch.cat((res, upsampled_x), dim=-1)
x = conv(x, data.edge_index)
```

and the error is the following:
```python
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    model.train(epochs,batch_size,num_workers=num_workers, lr=lr)
  File "/home/bcl/Martino/wssnet/trainer_wp.py", line 127, in train
    trnMetrics_t = self.doTraining(epoch_idx, train_dl)
  File "/home/bcl/Martino/wssnet/trainer_wp.py", line 154, in doTraining
    loss_var = self.computeBatchLoss(batch_idx, batch_tup, train_dl.batch_size, trnMetrics_g)
  File "/home/bcl/Martino/wssnet/trainer_wp.py", line 185, in computeBatchLoss
    prediction_g = self.model(data_)
  File "/opt/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bcl/Martino/wssnet/Unet_FeaStConv.py", line 81, in forward
    cluster = self.graclus(edge_index)
  File "/opt/miniconda3/lib/python3.8/site-packages/torch_geometric/nn/pool/graclus.py", line 35, in graclus
    return graclus_cluster(edge_index[0], edge_index[1], weight, num_nodes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/torch_cluster/graclus.py", line 48, in graclus_cluster

    # To CSR.
    perm = torch.argsort(row)
           ~~~~~~~~~~~~~ <--- HERE
    row, col = row[perm], col[perm]
RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
```

preceded by many error of this type:
```
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [463,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
```

Do you have an easy explanation of the problem ?  I don't think the problem is with the dataset because it has worked in gpu with models  that don' t have graclus pooling (they have no pooling at all, actually). Moreover, this code is working on cpu...

Thank you very much !

**Comment by rusty1s** [comment]
Not sure what's going wrong here TBH. What's the shape of `data.edge_index`? Does it work when removing the `@torch.jit.script` annotation in `torch_cluster/graclus.py` for the `graclus_cluster` method?

**Comment by scarpma** [comment]
Hi Matthias, thank you for your time and patience. I have found that it could be a problem with `torch.rand_perm()` function. Sometimes it gives values far outside the range of the edge_index length. I'm Trying to understand why by writing a small piece of code that reproduces the error. I will let you know.

**Comment by scarpma** [comment]
If I print the "perm" array after
```python
perm = torch.randperm(row.size(0), dtype=torch.long, device=row.device)
```
I get 
```python
...
262363
262364
262365
262366
262367
262368
262369
262370
[ CUDALongType{255794} ]
```
and then the errors. What is this `CUDALongType`?

**Comment by scarpma** [comment]
If I remove `, device=row.device` then it works... Very strange...

**Comment by rusty1s** [comment]
This is interesting. Not sure why `torch.randperm` is buggy for you. It might be worth it to report that problem to PyTorch directly.

**Comment by scarpma** [comment]
Yeah, you're right. Thanks for the help !
