### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by ewwll** [rusty1s/pytorch_geometric#1994]
## ❓ Questions & Help

FileNotFoundError: Could not find module 'D:\360Downloads\anaconda\Lib\site-packages\torch_sparse\_convert.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
how can i do something

**Comment by rusty1s** [comment]
Not really sure about this. I guess there is a path issue. Can you check if the following file exists:?
```
D:\360Downloads\anaconda\Lib\site-packages\torch_sparse\_convert.pyd
```

**Comment by ewwll** [comment]
Thanks for your answer, I am sure that all the files existed in this path but this error occurs when importing the package about pyg

**Comment by rusty1s** [comment]
Can you do me a favor and test that in a fresh miniconda enviroment? I'm actually clueless and kept googling myself :(

**Comment by ewwll** [comment]
hello I solve this question 。After the installation of pyg is complete, it prompts sparse problem, which cannot be downloaded through regular pip install Go here http://pytorch-geometric.com/whl/torch-1.4.0.html to download the corresponding torchsparse directly

**Comment by rusty1s** [comment]
Awesome :)
