### ISSUE TITLE
The copy method of the InMemoryDataset has bug?

### ISSUE THREAD

**Issue by EminentGeek** [rusty1s/pytorch_geometric#1996]
```
    def copy(self, idx=None):
        if idx is None:
            data_list = [self.get(i) for i in range(len(self))]
        else:
            data_list = [self.get(i) for i in idx]
        dataset = copy.copy(self)
        dataset.__indices__ = None
        dataset.__data_list == data_list
        dataset.data, dataset.slices = self.collate(data_list)
        return dataset
```
<https://github.com/rusty1s/pytorch_geometric/blob/3ed0024333e8713f1ba32bd7b81a09f0525bad4f/torch_geometric/data/in_memory_dataset.py#L145>
Maybe `dataset.__data_list == data_list` should be `dataset.__data_list__ = data_list`?

**Comment by rusty1s** [comment]
You're right. Fixed in master!

**Comment by EminentGeek** [comment]
> You're right. Fixed in master!

The fix is still wrong…………
**`=`**
