### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by rusty1s** [rusty1s/pytorch_geometric#2]

**Comment by rusty1s** [comment]
![logo](https://user-images.githubusercontent.com/6945922/32413706-b83b5530-c217-11e7-83ef-43da79b8b5aa.png)

**Comment by rusty1s** [comment]
[Ohne Titel.pdf](https://github.com/rusty1s/pytorch_geometric/files/1463578/Ohne.Titel.pdf)

**Comment by vfdev-5** [comment]
@rusty1s just wonder whether you implemented something to handle images as graphs or something like that...

**Comment by rusty1s** [comment]
There is a grid method in torch_geometric.utils, which generates a grid graph of user-defined height and width. Besides this, you need to manually provide appropriate image to graph transforms, e.g., by creating your own dataset.
