### ISSUE TITLE
Question about "collate"

### ISSUE THREAD

**Issue by zhangyk18** [rusty1s/pytorch_geometric#2005]
```python
    def collate(self, batch):
        elem = batch[0]
        if isinstance(elem, Data):
            return Batch.from_data_list(batch, self.follow_batch)
        elif isinstance(elem, torch.Tensor):
            return default_collate(batch)
        elif isinstance(elem, float):
            return torch.tensor(batch, dtype=torch.float)
        elif isinstance(elem, int_classes):
            return torch.tensor(batch)
        elif isinstance(elem, string_classes):
            return batch
        elif isinstance(elem, container_abcs.Mapping):
            return {key: self.collate([d[key] for d in batch]) for key in elem}
        elif isinstance(elem, tuple) and hasattr(elem, '_fields'):
            return type(elem)(*(self.collate(s) for s in zip(*batch)))
        elif isinstance(elem, container_abcs.Sequence):
            return [self.collate(s) for s in zip(*batch)]
```

Thanks for your great repository!
I have questions about the `collate` function. Maybe the `isinstance(elem, Data)` is the most common case, but my requirement is very close to  `isinstance(elem, tuple) and hasattr(elem, '_fields')`. I don't understand when the `_fields` attribute comes up. Could you please introduce the logic of using `isinstance(elem, tuple) and hasattr(elem, '_fields')`?

**Comment by rusty1s** [comment]
`hatasstr(elem, _fields)` is a common way to check for `NamedTuple`s. If this is the case, we recursively apply the `collate` function on every element of the tuple.

**Comment by zhangyk18** [comment]
@rusty1s 
"recursively apply the collate function on every element of the tuple",
OK, that's what I want.
Thanks for your reply.

This issue will be closed later.
