### ISSUE TITLE
Save model with TorchScript

### ISSUE THREAD

**Issue by lianxh** [rusty1s/pytorch_geometric#2010]
## ❓ Questions & Help

I want to convert `pytorch` model to `TorchScript`  by using `torch.jit.script(model)` and save it by `torch.jit.save`.

However, I find there are many types in `pyg` which are not supported by `TorchScript`, for example, 

`Adj = Union[Tensor, SparseTensor]`

and type `Union` haven`t been supported by [TorchScript](https://pytorch.org/docs/master/jit_language_reference.html#unsupported-typing-constructs)

so, how can I fix this conflict?

**Comment by rusty1s** [comment]
`MessagePassing.jittable` will take care of that. In fact, it casts the usage of `Union` into `torch.jit.overload` annotations.

That should work just fine, or did you encounter any issues while using `torch.jit.script` on PyG models?

**Comment by lianxh** [comment]
> `MessagePassing.jittable` will take care of that. In fact, it casts the usage of `Union` into `torch.jit.overload` annotations.
> 
> That should work just fine, or did you encounter any issues while using `torch.jit.script` on PyG models?

I did encounter this problem on PyG models, for example, the `GENConv` model. How can I solve this problem?

Thanks for u suggestion about using `MessagePassing.jittable`, it seems an alternative method to achieve my goal if I cannot use PyG models.

**Comment by rusty1s** [comment]
According to our [tests](https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/conv/test_gen_conv.py), this should work just fine. Note that calling `jittable` is not an option but is instead required for TorchScript support.

**Comment by lianxh** [comment]
> According to our [tests](https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/conv/test_gen_conv.py), this should work just fine. Note that calling `jittable` is not an option but is instead required for TorchScript support.

Thanks! It`s my mistake..
