### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement scipy (from torch-sparse)

### ISSUE THREAD

**Issue by hnisonoff** [rusty1s/pytorch_geometric#2011]
## 📚 Installation

I received an error when installing `torch-sparse` in a new environment. 

## Environment

* OS: Ubuntu 18.04.4
* Python version: 3.8.5
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 10.2
* GCC version: 7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information:
Here are the exact commands I used to install everything

`mamba create -n "my_env" pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
`mamba activate my_env`
`mamba install pip`
```
> python -c "import torch; print(torch.__version__)"
1.7.1
> python -c "import torch; print(torch.version.cuda)"
10.2
```

```
> pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Collecting torch-scatter
  Downloading https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 973 kB/s
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.5
```

```
> pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Collecting torch-scatter
  Downloading https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 973 kB/s
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.5
(atom) hunter_nisonoff@beef  10:46:19  ~/projects/atom/FAST
> pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
Collecting torch-sparse
  Downloading https://pytorch-geometric.com/whl/torch-1.7.0%2Bcu102/torch_sparse-0.6.8-cp38-cp38-linux_x86_64.whl (24.3 MB)
     |████████████████████████████████| 24.3 MB 65.1 MB/s
ERROR:
ERROR: No matching distribution found for scipy
```

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Seems like you have a problem downloading `scipy`. Can you try to install it manually before installing `torch-sparse`?

**Comment by hnisonoff** [comment]
Manually installing it before works for me. Thanks

**Comment by Muhannadimad** [comment]
> Seems like you have a problem downloading `scipy`. Can you try to install it manually before installing `torch-sparse`?

thanks, I install scipy and it's work
