### ISSUE TITLE
Some datasets from TUDataset broken

### ISSUE THREAD

**Issue by anneouyang** [rusty1s/pytorch_geometric#2019]
## 🐛 Bug

Some datasets have 0 as the attribute `num_features`

## To Reproduce

```
path = osp.join(osp.dirname(osp.realpath(sys.argv[0])), '..', 'data', 'TU')
dataset = TUDataset(path, name='IMDB-binary').shuffle()
print(dataset.num_features)
```

## Expected behavior

A non-zero value for num_features

## Environment

* Python version: 3.7.7
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.2

**Comment by anneouyang** [comment]
https://github.com/rusty1s/pytorch_geometric/blob/master/examples/jit/gin.py

The example here doesn't work either

**Comment by rusty1s** [comment]
The `transform` should add node features into the dataset. Did you resolve it?

**Comment by anneouyang** [comment]
Yes I realized that was intended, thank you!
