### ISSUE TITLE
Using convolution neural network's output feature map of shape (NumNodes x X x Y x Z) as node embedding instead of flattening each activation map to single dimension (NumNodes x XYZ).

### ISSUE THREAD

**Issue by surajsrivathsa** [rusty1s/pytorch_geometric#2021]
## ❓ Questions & Help

Hello,

I am trying to use 3-dimensional CNN activation maps (X x Y x Z) directly as node embeddings instead of flattening it (1 x XYZ) into single dimension.
I replaced the linear layer with convolution filters in custom GCN class and aiming to increase node dimensionality after each GCN block in the following sequence (2 x 2 x 2) --> (4 x 4 x 4) --> (8 x8 x 8) till (128 x 128 x 128).

`

    def __init__(self, in_channels, out_channels):
        super(GCNConv, self).__init__(aggr='add')  # "Add" aggregation (Step 5).
        # self.lin = torch.nn.Linear(in_channels, out_channels)

        # Transposed convolution to increase node embedding activation map dimensions by factor of 2
        self.conv =  nn.Sequential(nn.ConvTranspose3d(in_channels, out_channels, kernel_size=2, stride=2, padding=0, output_padding=0, bias=True),
                                   nn.BatchNorm3d(out_channels),
                                   nn.LeakyReLU())

    def forward(self, x, edge_index):
        # x has shape [NumOfNodes, X, Y, Z]
        # edge_index has shape [2, E]

        # Step 1: Transform node feature matrix holding can activation maps and increase its dimensionality.
        x = self.conv(x)
        print("x shape: {}".format(x.shape))

        # Step 2: Compute normalisation.
        row, col = edge_index
        deg = degree(col, x.size(1), dtype=x.dtype)
        deg_inv_sqrt = deg.pow(-0.5)
        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # Step 3: Start propagating messages.
        return self.propagate(edge_index, x=x, norm=norm)

    def message(self, x_j, norm):
        # x_j has shape [E, out_channels]

        # Step 4: Normalize node features.
        return norm.view(-1, 1) * x_j
`

I ran into below error while trying to run this network, Could you please let me know If its possible to work on such node embeddings in current settings and any pointers on how to fix this. Thanks in advance.

Error message : IndexError: index out of range
File : message_passing.py
Function : __collect__(self, args, edge_index, size, kwargs)
Line: data = self.__lift__(data, edge_index, j if arg[-2:] == '_j' else i)

**Comment by rusty1s** [comment]
This is fixable via the `node_dim` attribute in `MessagePassing`, which defines in which dimension to aggregate. By default, it is set to `-2`, however, in your case, it needs to be set to either `0` or `-4`:
```python
import torch
from torch_geometric.nn import MessagePassing
from torch_geometric.datasets import Planetoid


class MyConv(MessagePassing):
    def __init__(self):
        super(MyConv, self).__init__(aggr='mean', node_dim=0)

    def forward(self, x, edge_index):
        return self.propagate(edge_index, x=x)

    def message(self, x_j):
        return x_j


dataset = Planetoid('/tmp/Planetoid', name='Cora')
data = dataset[0]
x = torch.randn(data.num_nodes, 8, 8, 8)

model = MyConv()
out = model(x, data.edge_index)
```

**Comment by surajsrivathsa** [comment]
Thank you, node_dim = -4 fixed it.
