### ISSUE TITLE
knn_graph runtime

### ISSUE THREAD

**Issue by abahnasy** [rusty1s/pytorch_geometric#2026]
## ❓ Questions & Help

I'm training a model for point cloud segmentation, and I'm creating graphs on the fly while training using knn_graph function. I've noticed that while data is on GPU, it takes so much time to create the graph than if the data is on cpu.

```
import time
for data in loader:
    tick = time.time()
    knn_graph(data.pos.to(device), k=4, batch=data.batch.to(device), loop=False, num_workers=1)
    tock = time.time()
print(tock - tick)
```
output: 60.35853147506714

while the data is on cpu

```
for data in loader:
    tick = time.time()
    knn_graph(data.pos, k=4, batch=data.batch, loop=False, num_workers=1)
    tock = time.time()
print(tock - tick)
```
output: 0.4549586772918701

am I missing anything here while calling the function? I belive it shoud be way faster if the data is on gpu?

Thank you

**Comment by rusty1s** [comment]
It seems like you are also benchmarking GPU memory transfer times. For example, the following code yields significant speed-up using GPUs:
```python
import time

import torch
from torch_cluster import knn_graph

pos = torch.randn(10 * 1024, 3)
batch = torch.arange(10).view(-1, 1).repeat(1, 1024).view(-1)

t = time.perf_counter()
knn_graph(pos, k=4, batch=batch)
print(time.perf_counter() - t)

device = 'cuda'
pos = pos.to(device)
batch = batch.to(device)
knn_graph(pos, k=4, batch=batch)  # Warm-up GPU

torch.cuda.synchronize()
t = time.perf_counter()
knn_graph(pos, k=4, batch=batch)
torch.cuda.synchronize()
print(time.perf_counter() - t)
```
```
0.02301020920276642
0.004213056061416864
```

**Comment by abahnasy** [comment]
Oh, I didn't take into consideration the data transfer time. Thanks for clarifying

**Comment by davodogster** [comment]
@abahnasy that's cool that graphs can be created on the fly! Just curious how many points per sample you have? and is it a fixed number or not? Cheers
