### ISSUE TITLE
Exclude keys from `Batch.from_data_list`

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [rusty1s/pytorch_geometric#2028]
## 🚀 Feature

A parameter that allows some keys to be excluded when constructing a `Batch` using `Batch.from_data_list`. Something like:

```
b = Batch.from_data_list(list_of_datas, exclude_keys = ['key1', 'key2'])
```

Glancing at the code suggests an implementation like:
```
keys = [set(data.keys) for data in data_list]
keys = list(set.union(*keys) - set(exclude_keys))
assert 'batch' not in keys and 'ptr' not in keys
```
at [L43-45 of `batch.py`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py#L43-L45).

## Motivation

In some cases, `Data` objects may contain per-graph fields that are known to be the same across the entire batch/dataset. In cases where the model code is aware of this and knows how to deal with a missing batch dimension for those fields, it would be nice to avoid constructing an unneeded full [n_batch, ...] set of copies.

**Comment by rusty1s** [comment]
Great idea. Added to master.

**Comment by Linux-cpp-lisp** [comment]
@rusty1s thanks for the quick response!
