### ISSUE TITLE
TypeError: index_select() received an invalid combination of arguments - got (Tensor, int, NoneType), but expected one of: * (Tensor input, name dim, Tensor index, *, Tensor out)

### ISSUE THREAD

**Issue by danielmanu93** [rusty1s/pytorch_geometric#2035]
Hi everyone, I am trying to train a graph neural network on a PPI dataset. The code below shows a part of a code that passes messages from neighboring nodes through connecting edges. I get Type error as shown in the image below when I run this code through an import from the main program. From the error message, the error is from line 83, specifically "edge_index[idx] which returns a “none” instead of an element corresponding to an idx value in the array. But when I print the “idx”, it returns “1” so it should probably return index 1 element from the edge_index array but returns a “none” instead which throws an error. See attached the images. when I printed out edge_index returned a tuple with "2D tensor, none", edge_index[idx] returned a "none" and idx returned "1" as shown in the last image. Any help to get this fixed will be appreciated. Thanks

*OS: macOS sierra 10.12.6
* Python version: 3.7.3
* PyTorch version: 1.7.1

![1](https://user-images.githubusercontent.com/67971334/105403774-6cbf1580-5be6-11eb-92ce-52b391fddd94.jpeg)
![2](https://user-images.githubusercontent.com/67971334/105404018-b7409200-5be6-11eb-91c7-f68a90162b69.jpeg)
![3](https://user-images.githubusercontent.com/67971334/105406722-0c31d780-5bea-11eb-9624-cbbd3afcf876.jpeg)

**Comment by rusty1s** [comment]
Not sure what's your input looks like, but it seems that in your case `edge_index` is given as a tuple via
```
edge_index = (tensor of shape [2, num_edges], None)
```
Setting `edge_index` to a tensor of shape `[2, num_edges]` should fix that.

**Comment by danielmanu93** [comment]
Thanks @rusty1s. Looks like there there was a bug in one of my import files, so I fixed that and it's working now.
