### ISSUE TITLE
Variable number of graphs in a single Data object

### ISSUE THREAD

**Issue by Alexey-Kamenev** [rusty1s/pytorch_geometric#2037]
## ❓ Questions & Help

What is the recommended way of storing multiple graphs in a single `Data` object?
Something like described [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html#pairs-of-graphs) but for variable number of graphs?
I've tried using `Batch` class but then `DataLoader` fails on [this assert](../blob/master/torch_geometric/data/batch.py#L45) - I guess Batch of Batches is not allowed (why?).

**Comment by rusty1s** [comment]
Yeah, batching multiple `Batch` objects is currently not allowed. You have two options to achieve your goal:
1. Put separate graphs into separate attributes:
```python
data = Data(x1=x1, edge_index1=edge_index1, x2=x2, edge_index2=edge_index2)
```
2. Replicate the batching behavior of `Batch` for `Data`:
```python
x = torch.cat([x1, x2], dim=0)
edge_index = torch.cat([edge_index1, edge_index2 + x1.size(0)], dim=1)
internal_batch = torch.cat(torch.zeros(x1.size(0), dtype=torch.long), torch.ones(x2.size(0), dtype=torch.long)
data = Data(x=x, edge_index=edge_index, internal_batch=internal_batch)
```
Both methods should work with `DataLoader`. The design decision depends on whether you want to allow a variable number of graphs inside each `Data` object.

**Comment by Alexey-Kamenev** [comment]
Thank you, Matthias! Option 2 is what I initially started with but then I found that `Batch` already has everything I need (except that assert) so I decided to check just in case.
