### ISSUE TITLE
num_graphs

### ISSUE THREAD

**Issue by richardrl** [rusty1s/pytorch_geometric#2041]
Hi,
Batch.num_graphs seems to be defined based on the batch index of Batch.pos

So, if you don't define Batch.pos, Batch.num_graphs is undefined

I think Batch.num_graphs should be equal to the number of samples, regardless of what Batch.pos is

**Comment by rusty1s** [comment]
In previous versions, `num_graphs` was indeed only defined in case the `batch` attribute exists. This is fixed in master by now :)
