### ISSUE TITLE
Fastest way to have hierarchical data objects

### ISSUE THREAD

**Issue by richardrl** [rusty1s/pytorch_geometric#2046]
Hello,
Let's say I have N pointclouds with M points each. 

How should I store this most efficiently in the Batch object?

One naive way is to store each pointcloud as a property of the Batch object, e.g. batch.pc1, batch.pc2, etc.

**Comment by rusty1s** [comment]
In case you have multiple point clouds, I suggest to store them each in their own `Data(pos=pc1)` object, and use `DataLoader` to form batches from it.

**Comment by richardrl** [comment]
But each individual sample has multiple pointclouds. So I'm not sure that works?

**Comment by richardrl** [comment]
@rusty1s I also noticed, if I have a datalist of 8 elements where each element is dimension (2, 100, 3), the Dataloader will batch it to (16, 100, 30). I don't think this is correct. I'd prefer if it did not batch the first two dimensions automatically, is this possible?

**Comment by richardrl** [comment]
The line that is affecting this is torch_geometric/data/batch.py, the following:

`                batch[key] = torch.cat(items, ref_data.__cat_dim__(key, item))
`

Maybe this is working as ... intended? Seems weird. OHHH I just remembered. I think for some reason the way you wrote batch, you concatenate together the batch and 0'th index, but you have a .batch operator so you can separate it later.

**Comment by richardrl** [comment]
Yes, using "to_dense_batch" gives me back the behavior I want.

**Comment by richardrl** [comment]
Except it doesn't work in this case:

**Comment by rusty1s** [comment]
Your desired behavior will be supported soon, see https://github.com/rusty1s/pytorch_geometric/pull/2036.
