### ISSUE TITLE
How to copy a `torch_geometric.data.Data` object?

### ISSUE THREAD

**Issue by demmerichs** [rusty1s/pytorch_geometric#2050]
## ❓ Questions & Help

I like the `torch_geometric.data.Data` object a lot, especially in combination with all the other neat stuff and the general `apply` function. One thing I am missing and currently have a stupid work-around for is the copying of such a data object.

E.g. the apply function does generate new `torch.Tensor` objects but overwrites the attributes of the existing `Data` object. So when I pass a `Data` object into a function and want to process the data without affecting the input object, I need to make a copy of the `Data` object.

Currently I am doing this via `data = torch_geometric.data.Data.from_dict(data.to_dict())`.
My question is, is there a better way of doing this or a reason why there does not exist a copy method?
Thanks for your input on this :)

**Comment by rusty1s** [comment]
There is a `Data.clone()` to deep-copy a `data` object. Alternatively, `copy.copy(data)` and `copy.deepcopy(data)` should work just fine.

**Comment by rusty1s** [comment]
Should be documented by now :)

**Comment by de-gozaru** [comment]
Hi @rusty1s 

I'm trying to use the `.clone()` inside a network during training, and I'm getting the following error:
```bash
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

My code was working just fine in version 1.6, but now, when I upgraded to version 2.0, I'm getting this error.

Is this behavior expected or it's a bug?  

Thank you for your help!

Full traceback:
```bash
Traceback (most recent call last):
  File "xxx.py", line 140, in <module>
output = data.clone()
  File "/path_pyth/lib/python3.8/site-packages/torch_geometric/data/data.py", line 190, in clone
    return copy.deepcopy(self)
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/path_pyth/lib/python3.8/site-packages/torch_geometric/data/data.py", line 375, in __deepcopy__
    out.__dict__[key] = copy.deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/path_pyth/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 94, in __deepcopy__
    out._mapping = copy.deepcopy(out._mapping, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/path_pyth/lib/python3.8/site-packages/torch/_tensor.py", line 85, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

**Comment by rusty1s** [comment]
Thanks for reporting. Do you have a minimal example to reproduce this?

**Comment by de-gozaru** [comment]
Hi @rusty1s 

Thanks for the quick reply!

Here is an example:
```python
import torch
from torch_geometric.data import Data

class MyNet(torch.nn.Module):
    def __init__(self, ):
        super().__init__()
        self.layer1 = nn.Linear(3, 17)
        self.layer2 = nn.Linear(17, 49)
        
    def forward(self, batch):
        batch.x = self.layer1(batch.x)
        batch = batch.clone()
        batch.x = self.layer2(batch.x)
        batch = batch.clone()
        return batch
    
batch = Data(x=torch.rand(100, 3))
model = MyNet()
model(batch)
```

**Comment by rusty1s** [comment]
Interesting. This should be now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/712e9bac83e66893e943b58b83ebf824359b0a67.

**Comment by de-gozaru** [comment]
Hi @rusty1s 

Thanks for your answer, so If I install now PyG using 
```bash
pip3 install https://github.com/pyg-team/pytorch_geometric.git@master
```
It should be ok, right?

**Comment by rusty1s** [comment]
Yes, indeed.
