### ISSUE TITLE
Problem with dataloader

### ISSUE THREAD

**Issue by trinayan** [rusty1s/pytorch_geometric#2058]
## 🐛 Bug

Getting an error when using dataloader. Error is trigerred in  PyG  (torch_geometric/data/dataset.py) line 214 and says "TypeError: __copy__() takes 1 positional argument but 2 were given". This problem was not there in previous PyG 1.6.1.

## To Reproduce

1. I encountered it while trying to run the 1-2-3-proteins.py  KGNN application here(https://github.com/chrsmrrs/k-gnn). I have also encountered it while trying some other applications based on PyG.

Traceback (most recent call last):
  File "1-2-3-proteins.py", line 37, in <module>
    dataset = dataset[perm]
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 191, in __getitem__
    return self.index_select(idx)
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 202, in index_select
    return self.index_select(idx.tolist())
  File "/usr/local/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 214, in index_select
    dataset = copy.copy(self)
  File "/usr/local/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
TypeError: __copy__() takes 1 positional argument but 2 were given

This used to work before with older versions of PyG. I am not sure where the problem is as the source is just invoking the internal dataloader. The error seems to stem from the library by looking at the above trace. Not sure if the source has to be updated.

## Environment

* OS: Ubuntu 16.04
* Python version: 3.6
* PyTorch version: 1.7
* CUDA/cuDNN version: 10.2
* GCC version: 5.4.0
* PyG version : 1.6.3 (Latest release version)

**Comment by rusty1s** [comment]
Can you show me a minimal example to reproduce? Would really appreciate it!

**Comment by trinayan** [comment]
So an update. I reverted back both my pytorch from 1.7.0 to 1.6.0 and PyG from 1.6.3 to 1.6.0 respectively and the problem went away. If u use the configuration mentioned  in my original issue above the steps to reproduce it would be:

1. git clone https://github.com/chrsmrrs/k-gnn
2. cd k-gnn/examples/
3. python3 1-2-3-proteins.py
Hope this helps. Would be interested to know what the issue was. I would prefer to use the new pytorch version instead of 1.6.0

**Comment by rusty1s** [comment]
Ok, got it. Can you check if the error still exists in PyG master?
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by rusty1s** [comment]
This should be fixed in master. Please reopen in case installing from master does not work for you.
