### ISSUE TITLE
Confused about forward arguments of Set2Set

### ISSUE THREAD

**Issue by marcopodda** [rusty1s/pytorch_geometric#206]
## ❓ Questions & Help

Hi there,
first of all, thanks for the awesome library.
I'm trying to build a model which consists of a GatedGraphConv followed by a Set2Set pooling layer. However, I'm confused about what the actual inputs you should pass to the Set2Set layer.

The forward method of my model class looks like this:

```
def forward(self, batch):
        output = self.conv(batch.x, batch.edge_index)
        output = self.pool(?, ?)
        return output
```
where `conv` is the GatedGraphConv instance and `pool` is the Set2Set instance. The signature of the `Set2Set.forward` method is:
```
def forward(self, x, batch)
```
however, I'm not sure what to pass to the method, and the signature looks a bit confusing to me (is the `x` argument referring to `batch.x` or to the output of the previous layer?). I tried several combinations, but none seems to work.

Can you clarify what arguments Set2Set expects? 
Thank you in advance!

**Comment by rusty1s** [comment]
Hi, we generally refer to `x` for holding any node features (of any layer) with shape `[num_nodes, channels]`. `batch` is the assignment vector of `batch.batch` which maps each node to its respective graph.

**Comment by rusty1s** [comment]
So in your case, this should be
def forward(self, batch):
        output = self.conv(batch.x, batch.edge_index)
        output = self.pool(output, batch.batch)
        return output

**Comment by marcopodda** [comment]
That was a super-fast reply :)
Yes, I already had it sorted out once you wrote the first post, just couldn't get around `batch.batch`. 

Thanks again and keep up the good work!
