### ISSUE TITLE
operation does not have an identity

### ISSUE THREAD

**Issue by ldv1** [rusty1s/pytorch_geometric#2064]
Hi,

In the `TransformerConv`, we compute the dot product of a query with a key. I would like to add another piece of information to the key, namely the "local" (i.e. one-hop) mean pooling of the features of the target node.

How to get this information? It is provided by `avg_pool_neighbor_x` that takes in `data`. So I created a simple variant thereof in `avg_pool.py`:

```
import torch

from torch_geometric.utils import maybe_num_nodes

def avg_pool_neighbor_xx(x: torch.Tensor, edge_index: torch.Tensor, num_nodes: Optional[int] = None):
  
    num_nodes = maybe_num_nodes(edge_index, num_nodes)
   
    edge_index, _ = add_self_loops(edge_index, num_nodes=num_nodes)

    row, col = edge_index
    avg_pool_x = scatter(x[row], col, dim=0, dim_size=num_nodes,
                     reduce='mean')
    return avg_pool_x
```
Strangely, it reports `cannot import name 'maybe_num_nodes'`. So I had to change the second line into

```
from torch_geometric.utils.num_nodes import maybe_num_nodes
```

In `TransformerConv`, I added

```
from torch_geometric.nn.pool.avg_pool import avg_pool_neighbor_xx

[...]

def forward(self, x: Union[Tensor, PairTensor], edge_index: Adj,
                edge_attr: OptTensor = None):
        """"""

        [...]

        if isinstance(x, Tensor):
            x: PairTensor = (x, x)
        
        patch_i = avg_pool_neighbor_xx(x[1], edge_index)


```
which ended up in

```
  File "/usr/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.6/site-packages/torch_geometric/nn/conv/transformer_conv.py", line 159, in forward
    patch_i = avg_pool_neighbor_xx(xx[1], edge_index)
  File "/usr/lib/python3.6/site-packages/torch_geometric/nn/pool/avg_pool.py", line 101, in avg_pool_neighbor_xx
    num_nodes = maybe_num_nodes(edge_index, num_nodes)
  File "/usr/lib/python3.6/site-packages/torch_geometric/utils/num_nodes.py", line 9, in maybe_num_nodes
    return int(index.max()) + 1 if num_nodes is None else num_nodes
RuntimeError: operation does not have an identity.

```

Thanks for any hint!

**Comment by rusty1s** [comment]
It looks like your `edge_index` may not contain any values. Is that correct?

**Comment by rusty1s** [comment]
You can not input attributes with name `*_i` to `propagate`, as those suffixes are reserved for mapping tensors to destination nodes in `message`. I suggest to call `propagate` via `propagate(..., patch=patch)`.

**Comment by ldv1** [comment]
Following your advice, I wrote

`out = self.propagate(edge_index, x=x, edge_attr=edge_attr, patch=patch, size=None)
`

and I changed the signature of `message(.)` into

```
def message(self, x_i: Tensor, x_j: Tensor, index: Tensor,
        edge_attr: OptTensor,
        ptr: OptTensor,
        patch_i: OptTensor,
        size_i: Optional[int]) -> Tensor:

```
It seems to work. Thanks for your help.
Out of curiosity: How does PyG know the tensor `patch` (in this case) is related to nodes and not to edges? Suppose I want to pass additional properties of edges to `message(.)`; how could I do that?

**Comment by rusty1s** [comment]
It does not know anything about whether tensors relate to nodes or edges. However, it expects tensors indexed with `_i` or `_j` to be node features. In case you have edge features, you can simply pass them to `propagate` and call access them in `message`:
```python
    self.propagate(edge_index, edge_feature=edge_features)

def message(self, edge_feature):
    ...
```

**Comment by ldv1** [comment]
thanks
