### ISSUE TITLE
Passing specific edge_attr to message()?

### ISSUE THREAD

**Issue by lvkd84** [rusty1s/pytorch_geometric#2070]
## ❓ Questions & Help

I need to define a MessagePassing layer that requires both the node attributes and the edge attributes to update. Specifically, I want to define something like:

def message(self, x_i, x_j, edge_attr_ij)

I'm not sure what is the best way to implement this since data.edge_attr has shape [num_edges, num_edge_features] and thus cannot be subscript with _i or _j? I'm new to both Torch and Torch Geometric so I'd like to hear your recommendation before attempting any hack around the problem.

Thank you in advance!

**Comment by rusty1s** [comment]
You simply can access edge features via
```python
def message(self, x_i, x_j, edge_attr)
```
There is no need to subscript them with `_i` or `_j` since they already contain edge information (in contrast to node features).

**Comment by lvkd84** [comment]
Thank you for the quick reply.

I might misunderstand how it works but the edge_attr passed to message() has shape [num_edges, num_edge_features]. How do we know which edge in edge_attr corresponds to x_i and x_j?

**Comment by lvkd84** [comment]
Nevermind. I misunderstood the subscripts.
