### ISSUE TITLE
Issue with multi-head GATConv.

### ISSUE THREAD

**Issue by ankith-jain** [rusty1s/pytorch_geometric#2084]
When I use multi-head GATConv network, I get the following error

I'm using heads = 2
**RuntimeError: mat1 dim 1 must match mat2 dim 0 **.

My network:

GCN(
(conv1): GATConv(2, 32, heads=2)
(conv2): GATConv(32, 32, heads=2)
(conv3): GATConv(32, 32, heads=2)
(lin): Linear(in_features=32, out_features=3, bias=True)
)

Torch.size for the conv1 is torch.Size([149226, 64])

Any idea how can I solve this issue?

**One solution I used is concat = False** 

Any other solutions? or the solution which was used is correct?

**Comment by ankith-jain** [comment]
If I don't want to average out the multi-heads? What can be the solution?

**Comment by rusty1s** [comment]
You need to increase the number of `in_channels` in the upcoming layer:
```
GCN(
(conv1): GATConv(2, 32, heads=2)
(conv2): GATConv(64, 32, heads=2)
(conv3): GATConv(64, 32, heads=2)
(lin): Linear(in_features=64, out_features=3, bias=True)
)
```

**Comment by ankith-jain** [comment]
Thank you for your reply and the solution. Sorry, I forgot to close the issue. I had increased the in_channels.
