### ISSUE TITLE
pip 20.3 breaks Docker build

### ISSUE THREAD

**Issue by ameya98** [rusty1s/pytorch_geometric#2087]
## 🐛 Bug

With pip 20.3 (released a few months ago) and later versions, the Docker build from the provided Dockerfile fails with:
```
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'latest+cu101'
```
when running
```
/bin/sh -c pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
```

## To Reproduce

1. Follow the Docker build steps at https://github.com/rusty1s/pytorch_geometric/tree/master/docker

## Expected behavior

The Docker build should succeed after these dependencies are installed correctly.

## Additional context

This has to do with changes with how versions are parsed, introduced by pip 20.3: https://github.com/pypa/pip/issues/9188

**Comment by rusty1s** [comment]
Should be fixed now! Thanks. Please let me know if you encounter any issues.
