### ISSUE TITLE
Possible GCN inefficiency

### ISSUE THREAD

**Issue by datavistics** [rusty1s/pytorch_geometric#209]
## 🐛 Bug
In [line 94](https://github.com/rusty1s/pytorch_geometric/blob/e3757cfe3b4823f05680386b6c3accd6bed98121/torch_geometric/nn/conv/gcn_conv.py#L94)
`edge_index, norm = GCNConv.norm(edge_index, x.size(0), edge_weight,`
should be changed to
`edge_index, norm = self.norm(edge_index, x.size(0), edge_weight,`
note the `GCNConv` change to `self`

If you agree, Id like to make a pull request.

**Comment by rusty1s** [comment]
Can you explain to me why this should be more efficient?

**Comment by datavistics** [comment]
I did an experiment here:

```python
import timeit


class TimeTest:
    @staticmethod
    def sum():
        i = 1 + 1

    def call_class(self):
        TimeTest.sum()

    def call_self(self):
        self.sum()


runs = 10000000
t_class = timeit.Timer("tt.call_class()", setup="from __main__ import TimeTest; tt = TimeTest()")
print(f"Class time: {t_class.timeit(runs)}")
t_self = timeit.Timer("tt.call_self()", setup="from __main__ import TimeTest; tt = TimeTest()")
print(f"Self time: {t_self.timeit(runs)}")
```

Which returns:
```
Class time: 1.509215982903684
Self time: 1.3448661428570106
```

It is faster to use `self`. Granted the times are quite close for 10^7 runs.

I also think its more readable, extensible (if the name of GCNConv changes for some reason in the future), and consistent (since self is used many other places in the method.

Not a huge deal, but I thought it might be helpful!

**Comment by rusty1s** [comment]
Ah cool, didn‘t know this. You can send a PR, otherwise I would change it tomorrow by myself. Thank you!
