### ISSUE TITLE
Overall build configuration

### ISSUE THREAD

**Issue by Twittadrock** [rusty1s/pytorch_geometric#21]
Hey, 

I struggle a bit with building this project and the dependencies. I have a working example, but this requires some conda-hacks (sideloading a pytorch build against cuda-9.2) and gpu for graclus is not working there.

I tried several combinations of pytorch / cuda / gcc / python versions but cannot really see the pattern.
Some are working for pytorch_scatter others for pytorch_spline_conv or pytorch_cluster.

Is there any working configuration that is consistent across the full project and its siblings? 
As an example: pytorch 0.4.0 (compiled against nvcc/cuda-8) with python 3.6 and a nvcc-8 and gcc-8 compiler.

It would be great if you could add this additional information (cuda, gcc versions) to the README.md.

Thanks a lot 
Matthias

Note: The important thing is that gcc and cuda versions match pytorch (and python) in order to be binary compatible (ABI) with the C-extensions.

**Comment by Twittadrock** [comment]
Sorry for spamming, but after being pretty desperate this morning, I did a full reset of my system and tried again from scratch.

Thanks to your code changes for 0.4.1 (+1!!) and several personal experiences on the way, I finally managed to find a configuration that is working for now.

System configuration:
==============
*Python 3.6.5 (compiled with GCC 7.2)
*PyTorch 0.4.1 (py36_cuda9.2.148_cudnn7.1.4_1 >> sideloaded into anaconda as `conda install ..` installs a different version) 
*gcc 6.4.1
*CUDA Toolkit 9.2.148 (with a CUDA_HOME/bin/gcc symlink to /usr/bin/gcc-6 otherwise nvcc uses the system gcc which may differ)

Environment variables:
===============
export CUDA_HOME=/path/to/cuda-9.2
export PATH=CUDA_HOME/bin:$PATH
export CPATH=CUDA_HOME/include:$CPATH
export CC=gcc-6

Executing
========
`CC=gcc-6 python setup.py install` and `CC=gcc-6 python setup.py test`

Maybe for anyone's interest, but for the rest, we can close the issue.

I apologize for any inconveniences.

Greets
Matthias

**Comment by rusty1s** [comment]
Really happy that it's now working for you. I like your suggestion adding some more information to the README. Sadly, I can't do much to make this installation process more fluid, as this singlehandly depends on the [PyTorch Extension API](https://github.com/pytorch/extension-cpp).
So in practice, CUDA and Python version should be irrelevant, and you need a gcc >= 4.9.
