### ISSUE TITLE
pyg with arm(raspberry, TX2...)

### ISSUE THREAD

**Issue by SYSUHPK** [rusty1s/pytorch_geometric#2116]
Excuse me, I wonder whether pyg can be installed on arm arch?

**Comment by rusty1s** [comment]
The provided wheels do not work on arm, but you may find success by installing from source. Never tested that though.

**Comment by SYSUHPK** [comment]
Thanks a lot! BTW, can you provide some related links?

**Comment by rusty1s** [comment]
You mean for installing from source? You can clone the repository (e.g., `torch-scatter`) and run `python setup.py install`.

**Comment by SYSUHPK** [comment]
Got it, thank you very much, I will try it.
