### ISSUE TITLE
Giant graph performance problem

### ISSUE THREAD

**Issue by tengwei12315** [rusty1s/pytorch_geometric#212]
## ❓ Questions & Help

Does the framework support hundreds of millions of giant graph?How is performance?

**Comment by rusty1s** [comment]
Hi, do you mean a large number of graphs or a large number of nodes in a single graph? Support for large graphs is trivial via mini-batching, but we currently do not have a way for handling one giant single graph. We have an open issue regarding this request [here](https://github.com/rusty1s/pytorch_geometric/issues/64). This will be definitely integrated for the next major release.

**Comment by rusty1s** [comment]
I am closing this in favour of https://github.com/rusty1s/pytorch_geometric/issues/64.
