### ISSUE TITLE
Incorrect GraphSAINT Node Norm Calculation

### ISSUE THREAD

**Issue by austintwang** [rusty1s/pytorch_geometric#2130]
I believe the `num_samples` incrementor in line 143 should be the total number of samples in the dataset (`self.num_steps`), not the batch size of `loader` (200):

https://github.com/rusty1s/pytorch_geometric/blob/f7dfd6cbd08f661c25cb0d22ecaca60b144c8922/torch_geometric/data/graph_saint.py#L120-L156

The current implementation undercounts `num_samples` when `self.num_steps > 200` and overcounts when `self.num_steps < 200`, resulting in an incorrect `node_norm`.

**Comment by austintwang** [comment]
Ran a test on a 129528-node graph, with `sample_coverage = 5`. 

I added some debug statements in `__compute_norm__`, with lines ending in `####` being lines I added. The following code starts on line 132:

```python
        num_samples = total_sampled_nodes = 0
        true_num_samples = 0 ####
        while total_sampled_nodes < self.N * self.sample_coverage:
            for data in loader:
                for node_idx, adj in data:
                    edge_idx = adj.storage.value()
                    node_count[node_idx] += 1
                    edge_count[edge_idx] += 1
                    total_sampled_nodes += node_idx.size(0)

                    true_num_samples += 1 ####

                    if self.log:  # pragma: no cover
                        pbar.update(node_idx.size(0))
            num_samples += 200

        if self.log:  # pragma: no cover
            pbar.close()

        print(f"Implemented Sample Count: {num_samples}") ####
        print(f"Manual Sample Count: {true_num_samples}") ####
```

Results: 

`self.num_steps = 500`
```
Compute GraphSAINT normalization: : 1178463it [00:50, 23293.25it/s]
Implemented Sample Count: 400
Manual Sample Count: 1000
```

`self.num_steps = 50`
```
Compute GraphSAINT normalization: : 648146it [01:44, 6210.57it/s]
Implemented Sample Count: 22000
Manual Sample Count: 550
```

**Comment by rusty1s** [comment]
Yes, I think you are right. `num_samples` is dependent on `self.num_steps`. Thanks for reporting! Should be fixed in master.
