### ISSUE TITLE
Residual Gated Graph ConvNets

### ISSUE THREAD

**Issue by pvnieo** [rusty1s/pytorch_geometric#2133]
Hi,

Thanks for the great library.

I searched in the implemented model, and I couldn't find [Residual Gated Graph ConvNets](https://arxiv.org/pdf/1711.07553v2.pdf), and I wanted to be sure that it's not implemented! It is the case?

Thank you in advance!

**Comment by ldv1** [comment]
I don't think so.
Closest match is  [FiLMConv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.FiLMConv) but in Residual Gated Graph ConvNets the function g takes in not only x_i (as in FiLMConv) but x_j as well.

**Comment by pvnieo** [comment]
Ok, thank you. Closing the issue!
