### ISSUE TITLE
version 1.4.3

### ISSUE THREAD

**Issue by MohsenFazaeli** [rusty1s/pytorch_geometric#2135]
## 📚 Installation

Hi, I cannot find version  1.4.3.

**Comment by rusty1s** [comment]
What do you mean? It should exist, see https://github.com/rusty1s/pytorch_geometric/releases/tag/1.4.3. Installable via
```
pip install torch-geometric==1.4.3
```

**Comment by MohsenFazaeli** [comment]
sorry, if it's not a real issue. 
I was trying 
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.4.3+${CUDA}.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.4.3+${CUDA}.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.4.3+${CUDA}.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.4.3+${CUDA}.html
I didn't know how to get compatible packages.

**Comment by rusty1s** [comment]
As far as I know, there is no PyTorch 1.4.3 version. You should just try the wheels for `torch-1.4.0`.
