### ISSUE TITLE
Cannot install with PyTorch Nightly

### ISSUE THREAD

**Issue by sunshineatnoon** [rusty1s/pytorch_geometric#2146]
## Environment

* OS: Ubuntu 16.04
* Python version: 3.7.9
* PyTorch version: 1.9.0.dev20210220
* CUDA/cuDNN version: 10.2.89
* GCC version: 5.4.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
  ```
  conda install pytorch torchvision torchaudio -c pytorch-nightly
  pip install torch-scatter
  pip install torch-sparse
  pip install torch-cluster
  pip install torch-spline-conv
  pip install torch-geometric
  ```
* Any other relevant information:
  The pip installation is successful, but when I try `import torch_sparse`, I got the following error:
  ```
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda2/envs/svg/lib/python3.7/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/anaconda2/envs/svg/lib/python3.7/site-packages/torch_sparse/storage.py", line 21, in <module>
    class SparseStorage(object):
  File "/home/xtli/anaconda2/envs/svg/lib/python3.7/site-packages/torch/jit/_script.py", line 979, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/anaconda2/envs/svg/lib/python3.7/site-packages/torch/jit/_script.py", line 72, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
  RuntimeError:
  attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
    File "/home/anaconda2/envs/svg/lib/python3.7/site-packages/torch_sparse/storage.py", line 145
    def empty(self):
        self = SparseStorage.__new__(SparseStorage)
        self._row = None
        ~~~~~~~~~~~~~~~~ <--- HERE
        self._rowptr = None
        self._value = None
  ```
## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
This looks like some TorchScript internals changed in PyTorch master. We will fix that once a new official PyTorch release lands. We cannot fix that for now to guarantee correct behavior with the current PyTorch release.

**Comment by sunshineatnoon** [comment]
Got it. Thanks for the quick response and looking forward to the new release.
