### ISSUE TITLE
Question about dataset COLLAB, IMDB and so on

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#2148]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I want to use dataset like ```COLLAB``` and ```IMDB``` to test my graph classification model(GCN based).
But When I run the code, the error was raised as fellow:
```
root@219230838ea7:/home/RCGNN# python cross.py --dataset COLLAB
-----
COLLAB - Net
-----
COLLAB - Net - 0.3 - 16
None
Traceback (most recent call last):
  File "cross.py", line 226, in <module>
    logger=None,
  File "cross.py", line 83, in cross_validation_with_val_set
    train_loss = train(model, optimizer, train_loader)
  File "cross.py", line 160, in train
    out = model(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/RCGNN/c923_models.py", line 66, in forward
    x11 = F.relu(self.conv1(x=x, edge_index=edge_index))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 160, in forward
    edge_index, edge_weight, x.size(self.node_dim),
AttributeError: 'NoneType' object has no attribute 'size'
```
The error is that dataset ```CALLAB``` 's graph feed to GCN layer.
when I print the ```data.x```, it is ```None```.
How to use the feature matrix of those dataset ```COLLAB``` and ```IBDM``` or instaed it to feed it to GCN layer?
So how can I use dataset ```COLLAB``` and use it to GCN message passing?
Thank you!

**Comment by rusty1s** [comment]
This is correct. `COLLAB` and `IMDB` do not come with an initial node feature set. Therefore, you need to create them yourself, and the general procedure for this is to use a one-hot encoding of node degrees as input features. You can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/datasets.py#L26).

**Comment by jiaruHithub** [comment]
Thankyou!
