### ISSUE TITLE
Is it possible to apply a transfer matrix to unify different matrix?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#216]
## ❓ Questions & Help

I want to implement a Heterogeneous graph network, that different kind of node has a different attribute, then how can I unify them.(e.g., use a matrix to transfer)

**Comment by rusty1s** [comment]
Hi, it would be easier to help you if you give more concrete ideas. I guess you want to send messages from one node type to a different node type. You can easily do this within PyG via the non-symmetric `MessagePassing` interface and assignment indices in COO format. The `PointConv` and `pointnet++` example show how to use this interface for bipartite graphs.

**Comment by mrbeann** [comment]
Thanks, I will read it.
