### ISSUE TITLE
Setting add_self_loops to False for GCNConv

### ISSUE THREAD

**Issue by mdanb** [rusty1s/pytorch_geometric#2167]
## 🐛 Bug

I believe that the parameter ```add_self_loops``` for the ```GCNConv``` layer isn't working properly. In particular, the ```init``` method for the class ```GCNConv``` doesn't seem to include a parameter to take in the ```add_self_loops``` option.
## To Reproduce

1. Just call ```GCNConv(in_channels=1, out_channels=1, add_self_loops=False```)

Here's the relevant error:
 ``` 
File "/home/mdanb/.local/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 45, in __init__
    super(GCNConv, self).__init__(aggr='add', **kwargs)
TypeError: __init__() got an unexpected keyword argument 'add_self_loops'
 ```

## Expected behavior

Not to get any error message when initializing an instance of GCNConv with the parameter ```add_self_loops```
## Environment

* OS: Linux
* Python version: 3.8.5
* PyTorch version: 1.5.0+cu101
* CUDA/cuDNN version: 10.1
* GCC version: 9.3.0
* Any other relevant information:

**Comment by wsad1** [comment]
The [GCNConv](https://pytorch-geometric.readthedocs.io/en/1.5.0/_modules/torch_geometric/nn/conv/gcn_conv.html) in PyTorch version: 1.5.0 doesn't have the add_self_loops argument. But it's present in version [1.6](https://pytorch-geometric.readthedocs.io/en/1.6.0/_modules/torch_geometric/nn/conv/gcn_conv.html) and above.
