### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#219]
Documentation ([https://rusty1s.github.io/pytorch_geometric/build/html/notes/create_gnn.html](url)):

> In the message() function, we need to normalize the **target node features** x_j. Here, x_j denotes a lifted tensor, which contains the **target node features** of each edge. Node features can be automatically lifted by appending _i or _j to the variable name. In fact, any tensor can be lifted this way, as long as they have 𝑁 entries in its first dimension.
> 
> The **target node features** are normalized by computing node degrees deg(𝑖) for each node 𝑖 ....

Here `x_j` should be **source** node features instead of **target** node features. Please see the below source code from the class `MessagePassing`:

```
        i, j = (0, 1) if self.flow == 'target_to_source' else (1, 0)
        ij = {"_i": i, "_j": j}

        message_args = []
        for arg in self.message_args:
            if arg[-2:] in ij.keys():
                tmp = kwargs[arg[:-2]]
                if tmp is None:  # pragma: no cover
                    message_args.append(tmp)
                else:
                    idx = ij[arg[-2:]]
                    if isinstance(tmp, tuple) or isinstance(tmp, list):
                        assert len(tmp) == 2
                        if size[1 - idx] is None:
                            size[1 - idx] = tmp[1 - idx].size(0)
                        if size[1 - idx] != tmp[1 - idx].size(0):
                            raise ValueError(_size_error_msg)
                        tmp = tmp[idx]

                    if size[idx] is None:
                        size[idx] = tmp.size(0)
                    if size[idx] != tmp.size(0):
                        raise ValueError(_size_error_msg)

                    tmp = torch.index_select(tmp, 0, edge_index[idx])
                    message_args.append(tmp)
            else:
                message_args.append(kwargs[arg])
```

In the case of the default parameter`self.flow = source_to_target`, `x_j` is the featuer matrix of the source node cause `torch.index_select` selects `tmp` from the indices in the first row of `edge_index` which represent the source nodes of all the edges.

Although it makes no difference when working with undirected graphs, it may confuse people who study directed graphs.

**Comment by rusty1s** [comment]
Ok, this is indeed misleading. I will change it. Thank you!
