### ISSUE TITLE
LocalCartesian, row or col?

### ISSUE THREAD

**Issue by ldv1** [rusty1s/pytorch_geometric#2194]
In [LocalCartesian](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/local_cartesian.html#LocalCartesian) the "neighborhood" normalization is as follows:

```
(row, col), pos, pseudo = data.edge_index, data.pos, data.edge_attr

cart = pos[col] - pos[row]
cart = cart.view(-1, 1) if cart.dim() == 1 else cart

max_value, _ = scatter_max(cart.abs(), row, 0, dim_size=pos.size(0))
max_value = max_value.max(dim=-1, keepdim=True)[0]
cart = cart / (2 * max_value[row]) + 0.5 
```

I think we should define the neighborhood of a node x_j as the nodes that points to x_j and so use `col` instead of `row`, as in

```
[...]
max_value, _ = scatter_max(cart.abs(), col, 0, dim_size=pos.size(0))
max_value = max_value.max(dim=-1, keepdim=True)[0]
cart = cart / (2 * max_value[col]) + 0.5
```

**Comment by rusty1s** [comment]
Yes, indeed. Good spot! Fixed in master.

**Comment by ldv1** [comment]
When we are at it: would it be possible to change
`cart = pos[col] - pos[row]`
into
`cart = pos[row] - pos[col]`
because it is usually x_j - x_i (position of neighbor - position of central point) ?
And add the normalization as an option ? (in my case, I do not want it)
Those are very small changes, but if you want I can submit a PR. Thanks in advance.

**Comment by rusty1s** [comment]
Thanks for your PR. I will have a closer look later.
