### ISSUE TITLE
import spspmm_cuda, ImportError: undefined symbol: cusparseDcsrgemm

### ISSUE THREAD

**Issue by hongsong-wang** [rusty1s/pytorch_geometric#22]
I follow the instructions to install. The process went well. But when import torch_geometric.transforms as T, I got the error as show below.

import spspmm_cuda
ImportError: /home/name/.local/lib/python2.7/site-packages/spspmm_cuda.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface20unchecked_set_deviceE

I use python2.7, cuda8.0, pytorch 0.4.1, Ubuntu 16.04.4. Both pip and Miniconda environment  gets the same error.

**Comment by rusty1s** [comment]
Can you test the workaround described in https://github.com/rusty1s/pytorch_sparse/issues/1?

**Comment by hongsong-wang** [comment]
Thanks! It is the same problem as [https://github.com/rusty1s/pytorch_sparse/issues/1](url). The solution [https://github.com/rusty1s/pytorch_sparse/issues/1#issuecomment-414550293](url) works for me.

**Comment by hongsong-wang** [comment]
Thanks! It works.
