### ISSUE TITLE
OSError: dlopen(/usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 6): Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationESs   Referenced from: /usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so   Expected in: flat namespace  in /usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so

### ISSUE THREAD

**Issue by codenoob1997** [rusty1s/pytorch_geometric#2200]
## 📚 Installation

i installed torch-geometric-1.6.3 successfully, but when I tried to import torch_geometric in terminal .
An Error Occurred:
import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/usr/local/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/usr/local/lib/python3.9/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/usr/local/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.9/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib/python3.9/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/usr/local/lib/python3.9/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/usr/local/lib/python3.9/site-packages/torch_scatter/__init__.py", line 13, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/usr/local/lib/python3.9/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 6): Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationESs
  Referenced from: /usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/torch_scatter/_version_cpu.so

## Environment

* OS:macOS Catalina version 10.15.7
* Python version:Python 3.9.0
* PyTorch version:1.7.1
* CUDA/cuDNN version:no CUDA
* GCC version:gcc-10
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
pip3 install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1.html
pip3 install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.1.html
pip3 install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.1.html
pip3 install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.1.html
pip3 install torch-geometric
* Any other relevant information:
I tried to reinstall it, but the same error still popped up.

## Checklist

- [y] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [y] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [n] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [n] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Please uninstall all extension packages (`torch-scatter`, ...), and install via
```
pip3 install --node-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
```
The `torch-1.7.1.html` page does not exist.

**Comment by codenoob1997** [comment]
> Please uninstall all extension packages (`torch-scatter`, ...), and install via
> 
> ```
> pip3 install --node-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
> ```
> 
> The `torch-1.7.1.html` page does not exist.


$ pip3 install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
ERROR: Could not find a version that satisfies the requirement torch-scatter (from versions: none)
ERROR: No matching distribution found for torch-scatter


Does this mean that it doesn't support my cpu?
CPU:Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz

**Comment by rusty1s** [comment]
I see. We currently do not yet provide any Python 3.9 wheels.

**Comment by codenoob1997** [comment]
> I see. We currently do not yet provide any Python 3.9 wheels.

Thank you!
I tried to install it in a environment where python version==3.8.5 and got my problem solved eventually.
Now the pytorch-geometric is successfully installed and can import with no error occur.
Once again , thank you for your help!

**Comment by rusty1s** [comment]
Great!
