### ISSUE TITLE
PyTorch 1.8 Support

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [rusty1s/pytorch_geometric#2206]
PyTorch 1.8 was recently released (https://pytorch.org/blog/pytorch-1.8-released/). Is there any estimate for when torch_geometric might support it?

(This is not a demand, just a question, since PyTorch 1.8 has some features we'd really like to use 🙂)

**Comment by rusty1s** [comment]
Should be already supported by installing from master. The wheels are currently building. Should be done on Monday at the latest.

**Comment by rusty1s** [comment]
PyTorch 1.8.0 supprt landed. All wheels have been built. Please re-install them in order to use PyG with PyTorch 1.8.0.

**Comment by Linux-cpp-lisp** [comment]
Awesome! Thanks @rusty1s , that was so quick!
