### ISSUE TITLE
When graph only has one node: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by xinliweiyuan** [rusty1s/pytorch_geometric#221]
## To Reproduce

edge_index = torch.LongTensor([[0, 0]])
x = torch.FloatTensor([0.2, 0.2])
data_test = Data(x, edge_index)
data_test
>>>Data(edge_index=[1, 2], x=[2])

from torch_geometric.nn import GCNConv
gcv_conv = GCNConv(2, 10)
gcv_conv(data_test.x, data_test.edge_index)
ValueError: not enough values to unpack (expected 2, got 1)

The reason is related to the following code:

row, col = data_test.edge_index

ValueError: not enough values to unpack (expected 2, got 1)

can you fix it? Thanks.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Hi, you need to save edge indices in `[2, num_edges]` format. A simple transpose should be enough to fix your problem.

**Comment by xinliweiyuan** [comment]
Thanks, it really works 👍
