### ISSUE TITLE
Pytorch sparse installation problem

### ISSUE THREAD

**Issue by Shubhendu-Jena** [rusty1s/pytorch_geometric#2218]
## Environment

* OS: Ubuntu 20.04.2 LTS
* Python version: Python 3.7.9
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 11.0
* GCC version: 9.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html
* Any other relevant information:

## Checklist

- [ Yes] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ Yes] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ Yes] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ No] I do have multiple CUDA versions on my machine.

## Additional context

Even though I install the correct version for torch sparse, it later throws the following error when I try to import pytorch geometric:

RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 11.0 and torch_sparse has CUDA version 10.1. Please reinstall the torch_sparse that matches your PyTorch install.

**Comment by Shubhendu-Jena** [comment]
After a second look, I see that my Pytorch cuda version (11.0) and system cuda version (10.1) do not match. Maybe this is the problem and I should change my Pytorch version?

**Comment by rusty1s** [comment]
Note that the correct link is: `https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`.

In case you want to use CUDA 11, you need to set `LD_LIBRARY_PATH` to the CUDA toolkit installed by PyTorch. This is usually placed in `{miniconda_path}/lib`. Alternatively, you can change the PyTorch CUDA version to 10.1.

**Comment by Shubhendu-Jena** [comment]
Hi, thank you for the quick response. For installing using torch 1.7.1 and cuda 10.1, does the following command work?
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
 
or should it be pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html?

Thanks again

**Comment by rusty1s** [comment]
It should be
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

**Comment by Shubhendu-Jena** [comment]
Thank you again. I managed to solve the issue with your suggestion. Closing the issue now.
