### ISSUE TITLE
about undirected graph for GCNConv

### ISSUE THREAD

**Issue by zhuo931077127** [rusty1s/pytorch_geometric#2219]
When deal with undirected graph with ```GCNConv```, and the input ```edge index``` only with single directed edges. Do I have to  use ```to_undirected(edge_index)``` to convert directed edge index to bidirectional edge index?  Or ```GCNConv``` can treat single directed edge index as bidirection.

**Comment by rusty1s** [comment]
You need to use `to_undirected` first to operate on undirected graphs.

**Comment by zhuo931077127** [comment]
When input an edge index ```[[0,0,1,2,3],  [1,3,2,0,1]]``` to ```GCNConv```, nodes in the first row (source) aggregate messages from second row (target), right?

**Comment by ldv1** [comment]
The other way round: Targets aggregate messages from sources.
