### ISSUE TITLE
Can't install torch-geometric in colab.

### ISSUE THREAD

**Issue by sasan73** [rusty1s/pytorch_geometric#2230]
As of today, I am getting an error when trying to import PyTorch geometric in Google Colaboratory. This error occurs when I try to run the sample codes [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html) as well.

> OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv

**Comment by rusty1s** [comment]
Indeed. Fixed it in the Colabs.

**Comment by sasan73** [comment]
Thank you it worked.
