### ISSUE TITLE
Memory increase while iterate thru dataloader

### ISSUE THREAD

**Issue by johnny12150** [rusty1s/pytorch_geometric#2253]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I am using [this code](https://github.com/kunwuz/DGTN) to reproduce some experiments.
I found the memory quickly increase, so I did a little test and found just iterate thru the dataloader would cause this issue.
`multi_sess_graph.py` in `data` folder is  how they manage the dataset and each batch would look like this:
![image](https://user-images.githubusercontent.com/22369387/111057517-1f16a900-84c3-11eb-9dfc-622cc950543e.png)

```
Batch(batch=[1920], edge_count=[2088], edge_index=[2, 2088], in_degree_inv=[2088], mt_edge_index=[2, 5189], mt_node_num=[128], mt_sess_item_idx=[2240], mt_x=[3709, 1], num_count=[1920], out_degree_inv=[2088], sequence_len=[128], sess_item_idx=[2240], sess_masks=[3709], x=[1920, 1], y=[128])
```
I thought the memory a batch used will be released when the batch is moved to GPUs. 
Later, I found [the source](https://github.com/RuihongQiu/FGNN) of this modified code.
I did the same test of iterate thru the dataset and yet the memory usage also didn't increase.
Their batch looks like:
![image](https://user-images.githubusercontent.com/22369387/111057565-892f4e00-84c3-11eb-96ed-6629ec027676.png)

```
Batch(batch=[512], edge_index=[2, 6896], x=[512, 1], y=[100])
```
Is it normal to find the memory usage increase while iterating thru dataloader?
Or maybe it is a [bug from pytorch](https://github.com/pytorch/pytorch/issues/20433)?

**Comment by rusty1s** [comment]
Are you referring to CPU memory increases? My guess is that memory consumption will slightly increase by iterating over the dataset the first time, but should stay constant afterwards.

**Comment by johnny12150** [comment]
Yes, it's CPU memory usage.
I added the `gc.collect()` in the loop of iterating dataloader and the increment has been more acceptable.
