### ISSUE TITLE
Question about number of edge types in AIFB and MUTAG datasets

### ISSUE THREAD

**Issue by zhikaili** [rusty1s/pytorch_geometric#2256]
Hi,

As presented in [the RGCN paper](https://arxiv.org/pdf/1703.06103.pdf), AFIB and MUTAG datasets have 
45 and 23 types of edges repsectively:

![image](https://user-images.githubusercontent.com/76140761/111125649-ce7b7a80-85ac-11eb-8b9d-e4f1d1112591.png)

But in PYG implementation, i.e. the Entities class, they have 90 and 46 types of edges.  May I know why the number of edge types is doubled?

Thank you!

**Comment by rusty1s** [comment]
Indeed, following the paper, we add reverse relations to the graph, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/entities.py#L106).

**Comment by zhikaili** [comment]
@rusty1s Thank you for your reply!
