### ISSUE TITLE
DataLoader doesn't support batches composed of graph with different edge_index 

### ISSUE THREAD

**Issue by pinkfloyd06** [rusty1s/pytorch_geometric#2297]
Hello,

l would like to build a DataLoader from my custom dataset. Each sample has its own adjacency matrix. The latter varies in terms of the number of nodes and connectivity from one sample to another. As a consequence, each sample has its own edge_index and edge_weight.

When l use `dataLoader`  with  `batch_size=1` it works.  However when  `batch_size  > 1` l get the following error : 

```
from torch_geometric.data import DataLoader
loader = DataLoader(train_folder, batch_size=2, shuffle=True)
batch=next(iter(loader))
```
***** RuntimeError: stack expects each tensor to be equal size, but got [2, 107050] at entry 0 and [2, 106190] at entry 1**

Is  DataLoader not supporting varying **edge_index** ?

**Comment by rusty1s** [comment]
How is `train_folder` defined? It needs to be a list of PyTorch Geometric `Data` objects.

**Comment by pinkfloyd06** [comment]
Thank you for you answer @rusty1s .
Indeed, now l did the  following for each sample to build my dataset w.r.t Pytorch Geometric Data Object :

`torch_geometric.data.Data(x=features,pos=coordinates, edge_index=edge_index, edge_attr=edge_weight,y=targets, )`

then the dataloader as follow :  

`train_loader = torch_geometric.data.DataLoader(train_folder, batch_size=batch_size_train, shuffle=True)`

However, l am not sure to understand how  Geometric Pytorch distinguishes the different indexes across the samples.
For instance, in the following batch, l have two samples  

`Batch(batch=[32768], edge_attr=[211906], edge_index=[2, 211906], pos=[32768, 3],  x=[32768, 20], y=[32768, 20])`
 1- Since the edge indexes of the two samples are concatenated (and also `x` and  `y`), how to be sure that matrix multiplication between  `x` and `edge_index` is done with respect to the nodes of each sample only ? let's say the first sample has 14000 nodes and the second 18000.

2- Or Given this batch representation of `edge_index` Geometric Pytorch  will create a. big adjacency matrix of 14000+18000 nodes than do matrix multiplication between `x` and `edge_indices`  ? (we do not want to do that).

Thank you

**Comment by rusty1s** [comment]
1. This information is encoded in the `batch` vector, and matrix multiplication with `x` and `edge_index` is ensured to be correct by increasing the indices of `edge_index` per example.
2. Not sure what's your issue with that. Since `edge_index` is a sparse connectivity format, it will result in no runtime overhead.

**Comment by pinkfloyd06** [comment]
1. From one batch to another it is clear for me. It is done for instance  as follow :  `batch=next(iter(train_loader))` .  However, for the samples within the same batch it's not clear how `edge_index`  index is correctly increased per example  since `GCNCONV()` for instance in Geometric Pytorch is fed with batches `GCNCONV(x,edge_index) `. In my case 2 samples per batch.  So, l am not sure to understand how `GCNCONV() ` increases correctly the indices of `edge_index` per example since it's  fed with more than one example (batch operation).


Let's clarify that relying on dense multiplication :  

```
A1=A1.to_dense()
A2=A2.to_dense()
A=torch.cat((A1,A2))
X=torch.cat((X1,X2))
X=torch.bmm(X,A)
```
this writing allows to do matrix multiplication per sample  `X1 x A1` and `X2 x A2`
My question is this  dense multiplication equivalent to the sparse one  with `edge_index` in Geometric Pytorch ? 

Thank you

**Comment by rusty1s** [comment]
Instead of `torch.cat`, I guess you want to make use of `torch.stack` in the dense setting (to get a designated batch dimension).

This will indeed compute the same result as in our sparse scenario (after reshaping to `X.view(batch_size * num_nodes, num_features)`). It is explained in more depth [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches) and [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html).

Indices of `edge_index` are increased by the cumulated sum of all previously encountered numbers of nodes, e.g.:
```python
edge_indices = []
cumsum = 0
for data in data_list:
     edge_indices.append(edge_index + cumsum)
     cumsum += data.num_nodes
edge_index = torch.cat(edge_indices, dim=-1)
```

**Comment by pinkfloyd06** [comment]
Thank you for the links and details.

1/
```
train_folder=[ ]

for data_sample in data_list:

                           features,coordinates,edge_index,edge_weight,targets=data_sample

                           train_folder.append(
                            torch_geometric.data.Data(
                            x=features,
                            pos=coordinates, 
                            edge_index=edge_index, 
                            edge_attr=edge_weight,
                            y=targets, 
                            )
                            )

train_loader = torch_geometric.data.DataLoader(train_folder, batch_size=batch_size_train, shuffle=True)
```

Do you think that my edge_index are accumulated correctly in 1/  or l need to consider  `cumsum` as follow   in 2/ ? 

2/

```
train_folder=[ ]

cumsum = 0

for data_sample in data_list:

                           features,coordinates,edge_index,edge_weight,targets=data_sample

                           num_nodes=coordinates.shape[0]

                           cumsum += num_nodes

                           edge_index = edge_index + cumsum 

                           train_folder.append(
                            torch_geometric.data.Data(
                            x=features,
                            pos=coordinates, 
                            edge_index=edge_index, 
                            edge_attr=edge_weight,
                            y=targets, 
                            )
                            )

train_loader = torch_geometric.data.DataLoader(train_folder, batch_size=batch_size_train, shuffle=True)
```


3/ It seems to me that cumsum plays a role of mask. It control the number of nodes per samples involved in matrix multiplications, in order not to confuse/mix the nodes between the different samples.

Than you

**Comment by rusty1s** [comment]
1. No, it should only be applied to indices.
2. Yes, that's what `DataLoader` is doing out of the box (your third point results in *wrong* behaviour)
