### ISSUE TITLE
Segmentation fault in SplineConv

### ISSUE THREAD

**Issue by fguney** [rusty1s/pytorch_geometric#23]
`self.conv1 = SplineConv(n_in, n_hidden, dim=3, kernel_size=3, norm=False)`
`x = F.elu(self.norm(self.conv1(x, edge_index, pseudo), edge_index))`

It runs perfectly well on my laptop (mac, CPU), but there is a segmentation fault on the line above when I switch to the server (linux-x86_64, gcc 4.9.0, python 2.7, cuda 8.0).

here is the test output:

> ================================================= test session starts =================================================
platform linux2 -- Python 2.7.5, pytest-3.8.2, py-1.6.0, pluggy-0.7.1
rootdir: /users/../libs/pytorch_spline_conv, inifile: setup.cfg
plugins: cov-2.6.0
collected 28 items                                                                                                    
test/test_basis.py Segmentation fault (core dumped)

**Comment by rusty1s** [comment]
A segmentation fault may be a sign of an installation error  in `pytorch_spline_conv`. What PyTorch version are you using?

Please confirm that
```
python setup.py install
python setup.py test
```
in `pytorch_spline_conv` works and report again.

**Comment by fguney** [comment]
0.4.1

Install runs fine but it's the same problem in test.

**Comment by rusty1s** [comment]
Are you sure the kernel did rebuild? You can force this with
```
rm -rf build/ && python setup.py install
```

**Comment by fguney** [comment]
still, the test fails with this: 

`test/test_backward.py ....Segmentation fault (core dumped)`

**Comment by derek-saal** [comment]
I had the same issue with all the mnist examples.

**Comment by sethglazier** [comment]
I've got the same issue w/ the qm9 example.

**Comment by rusty1s** [comment]
Could this be resolved by anyone?

**Comment by Yannick-S** [comment]
I have that all tests run successfully, but get problems when running my own model: It always runs for some epochs, but then i get problems:

Segmentation fault (core dumped)
or

free(): invalid size
Aborted (core dumped)
or

free(): invalid next size (normal)
Aborted (core dumped)
or

double free or corruption (out)
Aborted (core dumped)
or

Traceback (most recent call last):
  File "first_test.py", line 101, in <module>
    loss = train(epoch)
  File "first_test.py", line 83, in train
    loss.backward()
  File "/home/*/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/*/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: could not compute gradients for some functions

or
corrupted size vs. prev_size
Aborted (core dumped)

or
munmap_chunk(): invalid pointer
Aborted (core dumped)

I think those are all the different error messages I get without changing any of my code.

I was not able to track down the error further than knowing it is somewhere in the backward step if I use SplineConv. When doing with torch.no_grad for the SplineConv layer I don't have issues.

**Comment by Yannick-S** [comment]
I think I know the issue. When feeding pseudo values which are not in [0,1], there is a disaster. Maybe there should be a test somewhere warning the user?

**Comment by rusty1s** [comment]
Yes, this is not allowed! I could add an assertion, but this would result in unnecessary computations. Any idea?

**Comment by Yannick-S** [comment]
Mhh true. I think in the documentation there should be a warning.
And maybe when initializing the spline conv you could add a safe=True/False option. Depending on this it will do either
if safe:
   def forward(...) safely
else:
   def forward(...) as is...

this is ofc ugly and a dupication of code. 
Then again i am bad at programming.

**Comment by rusty1s** [comment]
I will definitively add a note in the documentation. I think i will add an assertion in the forward pass which gets only called once.

**Comment by rusty1s** [comment]
Done!
