### ISSUE TITLE
edge_attr - construction

### ISSUE THREAD

**Issue by orialz** [rusty1s/pytorch_geometric#230]
## ❓ Questions & Help

How should edge_attr be constructed?
I did not find any kind of (explicit) matching between the nodes and the edges. I'm assuming the construction implicitly uses the adjacency matrix to match the edge_attributes to the actual edges.

Is the matching done by order of rows? columns? how can I make sure the relevant attributes are assigned to the correct edges?

beautiful work!
Much appreciated!

**Comment by orialz** [comment]
Brain fart. there's that, so should be by the same order:
data.edge_index: Graph connectivity in COO format with shape [2, num_edges] and type torch.long
data.edge_attr: Edge feature matrix with shape [num_edges, num_edge_features]

**Comment by rusty1s** [comment]
Exactly :) Order is defined by `edge_index`.
