### ISSUE TITLE
A faster way to use “einsum” and SparseTensor for calculating the dot-product attention ?   

### ISSUE THREAD

**Issue by GabbySuwichaya** [rusty1s/pytorch_geometric#2301]
## ❓ Questions & Help

 Hi! Just recently I have tried to use `einsum` ...  I have come to notice that one of the following forms of sum-product is actually being processed faster?   

My matrix multiplication is done in order to achieve the following   
1. I want to calculate the matrix multiplication: A = x^T * x where x^T is NxHxD...  and x = DxHxN... I hope to get the result A in the form of A = NxNxH.  
2. Then, I will select the feature element of size 1xH from the upper triangular elements on the NxN coordinates of A.  
 

- The 1st approach, which is quite straight forward and is the faster approach, is as follows:    
```
x_      = [DxHxN]  
A1 =  torch.einsum('dhn,dhm->hnm', x_, x_)     # A1  = [HxNxN]  

edge_index_j, edge_index_i = edge_index       #  edge_index = [2x #Edges]]  # where #Edges=N^2/2 

A1 = A1[:,edge_index_j,edge_index_i]            # A1  = [Hx#Edges] 
A1 = A1.permute(1, 0)                                    # A1  = [#EdgesxH]   
```  

The 2nd slower approach is  
``` 
x   = x.permute(2,1,0)                         # x  = [NxHxD] 
x_i = torch.index_select(x, 0, edge_index_i)   # x_i = [#EdgexHxD] 
x_j = torch.index_select(x, 0, edge_index_j)   # x_j = [#EdgexHxD]  
A2 = torch.einsum("ehd,ehd->eh", x_i, x_j)     # A2 = [#EdgexH] 
```  
As N = 2000, the runtime of the 1st approach is so much smaller than the 2nd approach: 

 ```
Runtime (1st): 1.312180 ms 
Runtime (2nd): 32.030568 ms  
``` 
Here, I measured the runtime with torch.cuda.Event on RTX 2080 Ti  

My questions are as follows: 
- Why the 1st approach is faster when N becomes larger (e.g., > 500) when actually the 2nd approach has less number of flops?  

- Did I misunderstand anything?  From my understanding, in the 1st approach, the calculation of A1 is  NxHxDxN = N^2 X H X D, which is twice more than the 2nd approach, e.i., the calculation of A2 is #EdgexHxD.  where #Edge = N^2/2... 

-  Also, if I can use the SparseTensor for my graph, would it be faster to use SparseTensor with the 2nd approach?

-  Since I don't have much experience with SparseTensor, could you give an example of how to use the SparseTensor for this case?

**Comment by rusty1s** [comment]
I think the first approach is faster since it is more memory-efficient as it avoids the creation of really big `x_i` and `x_j` tensors.

I don't think there is a way to implement this via `SparseTensor`, as it does not support `sparse_einsum` capabilities yet.

**Comment by GabbySuwichaya** [comment]
I see. Thank you so much.
