### ISSUE TITLE
Add randomly edges to edge_index

### ISSUE THREAD

**Issue by pinkfloyd06** [rusty1s/pytorch_geometric#2302]
Hello,
Similar to [https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.dropout_adj](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.dropout_adj)
where the function `dropout_adj()` allows to randomly remove edges with probability `p`.
I am looking to build a function that allows to **add randomly edges**. Given an adjacency matrix `A` with **n nodes**.  How could one add  ` K%` **random edges** such that A is an undirected adjacency matrix.

Thank you

**Comment by rusty1s** [comment]
You can simply sample random edges, and add them to your `edge_index`, e.g.:
```python
edge_index_to_add = torch.randint(0, N, (2, num_edges_to_add), dtype=torch.long)
edge_index_to_add = to_undirected(edge_index_to_add)
edge_index = torch.cat([edge_index, edge_index_to_add], dim=1)
```

**Comment by pinkfloyd06** [comment]
Nice ! 
Thank you
