### ISSUE TITLE
Incomplete `download` method in `create_dataset`?

### ISSUE THREAD

**Issue by Yash-10** [rusty1s/pytorch_geometric#2303]
Hello,

First of all, thank you for this project!

I was going through the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html#creating-in-memory-datasets) to create a custom dataset. While going through it, I came across a part where a piece of code to create user-defined datasets is provided. 

I was wondering whether the missing implementation for the `download` method is kept incomplete (or syntactically incorrect) for a purpose, since it just provides a sample. 

```py
def download(self):
    # Download to `self.raw_dir`.
.
.
.
```

It might be a trivial point here, but is there a need to use a `pass` statement or equivalent to fill it's implementation?

Thanks!!

**Comment by zcajiayin** [comment]
This is not a necessary method to be implemented if you would like to create your own dataset. If your dataset is from nowhere but generated yourself, you can just ignore this method (just as the example code you paste here). However, in this case, in `process()` method, you need to load a list of `Data()` objects and processed it, and finally save to file. 


If you do not want to save to file, just use dataloader:
```
from torch_geometric.data import Data, DataLoader
data_list = [Data(...), ..., Data(...)]
loader = DataLoader(data_list, batch_size=32)
```

**Comment by Yash-10** [comment]
Thank you so much for your guidance, I will keep that in mind.

Additionally, I just wanted to ask whether a `pass` statement or something equivalent could be included in the documentation instead of just leaving the `download` method blank.

Could you let me know what do you think about this?

Thanks!!

**Comment by rusty1s** [comment]
I added this to the documentation :)
