### ISSUE TITLE
Potential typo in "Scaling Graph Neural Networks" notebook

### ISSUE THREAD

**Issue by IaroslavElistratov** [rusty1s/pytorch_geometric#2310]
## ❓ Questions & Help

Hi, in the [Scaling Graph Neural Networks](https://colab.research.google.com/drive/1XAjcjRHrSR_ypCk_feIWFbcBKyT4Lirs?usp=sharing) when we're iterating over each mini-batch of the data, shouldn't we pass the current batch to the model inside the loop? I.e., "model(sub_data.x, sub_data.edge_index)" instead of "model(data.x, data.edge_index)", because now it seems even though we're iterating over the mini-batches we're still passing the whole dataset to the model each time.

<img width="1122" alt="Screen Shot 2021-03-27 at 7 22 45 AM" src="https://user-images.githubusercontent.com/57019863/112709951-95a5a480-8ece-11eb-825f-8371296bb113.png">

Please let me know if I'm missing something. Thanks!

**Comment by rusty1s** [comment]
Indeed. Thanks for reporting :) This is now fixed.
