### ISSUE TITLE
The `adj` in dense data is following which convention?

### ISSUE THREAD

**Issue by zcajiayin** [rusty1s/pytorch_geometric#2319]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

If the data is dense, then in the adjacent matrix `adj` of this data, the source node is row or colunm?

For example, in the following `adj`:

```
connection for node 0 -> [[0, 1],
connection for node 1 ->  [0, 0]]
```

Is `node 0` pointing to `node 1`, or `node 1` pointing to `node 0`?

**Comment by rusty1s** [comment]
The source node is `row`, i.e.:
```
row, col = adj.nonzero().t()
```
If you want the same message passing flow as in our sparse variants, I suggest to input the transposed adjacency matrix, e.g.:
```python
dense_conv(x, adj.t(-2, -1))
```
I will make this more clear in the documentation.

**Comment by zcajiayin** [comment]
Clear. Thanks!
