### ISSUE TITLE
AddTrainValTestMask

### ISSUE THREAD

**Issue by Marc79745** [rusty1s/pytorch_geometric#2325]
## To Reproduce

1. Run "cora.py" in examples folder

AttributeError: module 'torch_geometric.transforms' has no attribute 'AddTrainValTestMask'

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

## Additional context

in torch_geometric/transforms/__init__.py : line 42: **from.add_train_val_test_mask import AddTrainValTestMask** 
i suppose it should be **from .add_train_val_test_mask import AddTrainValTestMask** 

as i am new to reporting bugs on here i hope that is the right place to report a typo

**Comment by rusty1s** [comment]
Thanks for reporting. This should be fixed now.
