### ISSUE TITLE
GCNconv uses pow_ instead of pow

### ISSUE THREAD

**Issue by Baekhyun-G** [rusty1s/pytorch_geometric#2334]
## 🐛 Bug

in line 42 or 63 of   https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py
`      deg_inv_sqrt = deg.pow_(-0.5)`
is used which is wrong because of- deg is a long tensor because it is derived from edge_indices which in itself is a long matrix.
I am facing this following error because of the same reason
RuntimeError: result type Floatcan't be cast to the desired output type Long

## To Reproduce

Following is the tail of the stack trace
>   File "/mnt/infonas/data/baekgupta/expt_venvs/tg171/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 159, in forward
>     edge_index, edge_weight = gcn_norm(  # yapf: disable
>   File "/mnt/infonas/data/baekgupta/expt_venvs/tg171/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 63, in gcn_norm
>     deg_inv_sqrt = deg.pow_(-0.5)
> RuntimeError: result type Floatcan't be cast to the desired output type Long
> 

## Environment

* OS: ubuntu
* Python version: 3.8
* PyTorch version: 1.7.1/1.8.0
* CUDA/cuDNN version: 11.0
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Are you passing any edge weights to the operator? Of which type are they?

**Comment by Baekhyun-G** [comment]
Actually my Dataloader is created the following way
[Data() Data() .....]
and initialisiation of Data() is this Data(x=x,y=y,edge_index=edge_index,pos=pos) where pos is just [num_nodes x 1] tensor (long).
and I pass batch.x and batch.edge_index to the conv network.
So as you can see there is no explicit edge weight that I defined.

**Comment by Baekhyun-G** [comment]
okay actually x.dtype was int. Thanks
