### ISSUE TITLE
Too big to fit "in_memory_dataset"

### ISSUE THREAD

**Issue by neon5d** [rusty1s/pytorch_geometric#234]
## ❓ Questions & Help

My data set is too big to fit "in_memory_dataset".
"collate" in in_memory_dataset failed.
How can I create a data set without in_memory_dataset?
Is there any example?

**Comment by sw-gong** [comment]
See https://rusty1s.github.io/pytorch_geometric/build/html/notes/create_dataset.html#creating-larger-datasets

**Comment by neon5d** [comment]
Thank you for the information.
