### ISSUE TITLE
Regarding the output and usage of dense_mincut_pool

### ISSUE THREAD

**Issue by xiaoyuxin1002** [rusty1s/pytorch_geometric#2343]
Hi, I am trying to use the dense pooling function dense_mincut_pool according to the given [example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/proteins_mincut_pool.py),:
`x, adj, mc1, o1 = dense_mincut_pool(x, adj, s, mask)`

but I have a question regarding the input adj:
1. The document says that the input adj is a symmetrically normalized adjacency tensor. If my adj is of the required input shape B x N x N but not symmetrically normalized, is there a good way to do that while retaining the gradient information of the input adj tensor? Does the input of DenseGINConv also require a symmetrically normalized adj tensor?

Thank you very much!

**Comment by rusty1s** [comment]
1. You can convert `adj` to a symmetrically normalized one via:
```python
D = adj.sum(dim=-1).pow(-0.5)
adj = D.view(B, N, 1) * adj * D.view(B, 1, N)
```
`GINConv`, on the other hand, does not need to operate on symmetrically normalized adjacencies.
