### ISSUE TITLE
using edge_weight into shape classification

### ISSUE THREAD

**Issue by Rishabh201911010** [rusty1s/pytorch_geometric#2346]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Dear rusty1s,
I am trying to classify shape which are 3D using GCN . For Edge_weight I am using Laplace Beltrami operator. Now I have to incorporate this edge weight into ModelNet10 dataset.  How can  I do this?

**Comment by rusty1s** [comment]
You can add edge weights to your dataset via the `transform` and `pre_transform` arguments of a dataset. Furthermore, there exists many GNNs that can take  `edge_weight` into account, such as `GraphConv` and `GCNConv`.

**Comment by Rishabh201911010** [comment]
Thank You Sir.
