### ISSUE TITLE
Possible error of DenseSAGEConv

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#235]
Below is the part of the current implementation of DenseSAGEConv  
```
        if add_loop:
            eye = torch.eye(N, dtype=adj.dtype, device=adj.device)
            adj = adj + eye.unsqueeze(0).expand_as(adj)
```
I suppose it needs to remove loop first before adding loop in such way. 

Thanks.

**Comment by rusty1s** [comment]
Yes, at least to be consistent with all sparse ops. I fixed it in master. Thank you!
