### ISSUE TITLE
GCNConv()  __init__() got an unexpected keyword argument 'normalize'

### ISSUE THREAD

**Issue by pinkfloyd06** [rusty1s/pytorch_geometric#2359]
Hello,

I would like to experiment `GCNConv` operation with/without normalizing adjacency matrices and also the improved version following [https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GCNConv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GCNConv
)

However, it seems that the parameters `normalize `and `improved ` are not recognized !  l get the following error : 

`*** TypeError: __init__() got an unexpected keyword argument 'normalize`

Here is my code

```
from torch_geometric.nn import GCNConv        
self.conv1 = GCNConv(
            in_channels=32,
            out_channels=64,
            normalize=self.normalize_adjacency,
            improved=self.improved_adjacency,
            )

```

**Comment by rusty1s** [comment]
Which version of PyG are you using? This argument should be available in later releases.

**Comment by pinkfloyd06** [comment]
I have the following versions  : 

```
torch_geometric.__version__
'1.6.3'
```
```

torch.__version__
'1.6.0+cu101'
```

**Comment by rusty1s** [comment]
I'm actually not sure what's causing this. To me, this looks like a conflict with different PyG versions on your system.

**Comment by pinkfloyd06** [comment]
Yes, definitely !
Thank you
