### ISSUE TITLE
In AMiner dataset, what is the meaning of y_index_dict and y_dict?

### ISSUE THREAD

**Issue by Yonggie** [rusty1s/pytorch_geometric#2365]
I'm making my own dataset for metapath2vec model, the example code used Aminer dataset for illustration. But every thing inside AMiner dataset has been processed inside.
After checking the source code of AMiner dataset class, I found there are many attributes inside. I figure every attributes out but y_index_dict and y_dict. They must be related to label, but I can't know what exactly they are.
 
Could any nice one help me out?

**Comment by rusty1s** [comment]
Yes, the `y_dict` refers to `author` and `venue` labels of the nodes in `y_index_dict`. Not that there do not exist labels for every node in the graph, just for the ones denoted in `y_index_dict`.

**Comment by Yonggie** [comment]
Thank you so much for explaination.
After double triple check on the AMiner class code, I finally make it.
There's was huge misunderstanding that I thought all nodes' id are globally assigned, which made me unsuccessful whatever I tried.😂
All ids are assigned separatedly inside separate class.
