### ISSUE TITLE
modified module is not actually affected. 

### ISSUE THREAD

**Issue by pixar0407** [rusty1s/pytorch_geometric#2366]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hello @rusty1s 

I am trying to run point_cnn.py (https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/points/point_cnn.py)
By doing so, i wanted to change some little modification to x_conv.py(https://github.com/rusty1s/pytorch_geometric/blob/d1440988fb9db2c28e6a42bdfd4f08e5e73aec61/torch_geometric/nn/conv/x_conv.py#L19).

Actually i add some print() code in the def forward on x_conv.py.

i modified the x_conv.py file and run the point_cnn.py. But the change does not affected.
And i googled it. I found this kind of source (https://stackoverflow.com/questions/961162/reloading-module-giving-nameerror-name-reload-is-not-defined/33409066#33409066).

> from torch_geometric.nn import XConv, fps, global_mean_pool
> 
> import importlib
> import sys
> importlib.reload(sys.modules['torch_geometric.nn'])

But this does not solve the problem.

I also tried "python -B point_cnn.py" to ignore the __pycache__.
How can i import the modified XConv. 

Any suggestion would be appreciated. 
Thank you.

**Comment by rusty1s** [comment]
Where did you modify `x_conv.py`? When installing Python packages, the package will be moved to the Python environment lib directory. For example, mine is located in `{miniconda_path}/lib/python3.7/site-packages/torch_geometric`. You need to modify the source code there, or, alternatively, install the package in developer mode via `python setup.py develop`.

**Comment by pixar0407** [comment]
hello, @rusty1s 

You are right! thank you.  I was little confused. Long time ago, I had installed the packages.
And recently I downloaded the github files and did try things there.
But, as you said, obviously i have to touch the lib directory. 

Anyway, thank you for the help. 
Hope you being well :)
