### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by Rishabh201911010** [rusty1s/pytorch_geometric#2373]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I am unable to fix this error.data_list_1 is list in which I have Data type object with edge_attr , edge_index, pos and y. List having only 2 Data object. After calling my Net module , I got output for 1st data in list but for 2nd got index error.
[Simple.ipynb - Colaboratory.pdf](https://github.com/rusty1s/pytorch_geometric/files/6283612/Simple.ipynb.-.Colaboratory.pdf)

**Comment by rusty1s** [comment]
Please remove the `cached=True` option from the `GCNConv`.

**Comment by Rishabh201911010** [comment]
Thank you very much sir. Its solved.
