### ISSUE TITLE
Error while installing PyTorch Scatter

### ISSUE THREAD

**Issue by Arun0013** [rusty1s/pytorch_geometric#2381]
## 📚 Installation

I am getting the error "**cl : Command line error D8003 : missing source filename**" while installing PyTorch Scatter.
I am using the command "pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html".
Visual Basic along with Windows 10 SDK is already installed.

## Environment

* OS: Windows 10
* Python version: 3.6.5
* PyTorch version: 1.8.1
* CUDA/cuDNN version: None
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

Log details:
Looking in links: https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
Collecting torch-scatter
  Using cached torch_scatter-2.0.6.tar.gz (21 kB)
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"'; __file__='"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\1583548\AppData\Local\Temp\pip-wheel-gv7edt2r'
       cwd: C:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\placeholder.py -> build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\scatter.py -> build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\utils.py -> build\lib.win-amd64-3.6\torch_scatter
  copying torch_scatter\__init__.py -> build\lib.win-amd64-3.6\torch_scatter
  creating build\lib.win-amd64-3.6\torch_scatter\composite
  copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.6\torch_scatter\composite
  copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.6\torch_scatter\composite
  copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.6\torch_scatter\composite
  copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.6\torch_scatter\composite
  running build_ext
  C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'torch_scatter._scatter_cpu' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\Users
  creating build\temp.win-amd64-3.6\Release\Users\1583548
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc
  creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\cpu
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\THC -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\" /EHsc /TpC:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\scatter.cpp /Fobuild\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\scatter.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O2 -DAT_PARALLEL_OPENMP /openmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0
  cl : Command line error D8003 : missing source filename
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\initialise.py", line 20, in reset_all
      AnsiToWin32(orig_stdout).reset_all()
    File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 71, in __init__
      strip = conversion_supported or (not is_stream_closed(wrapped) and not is_a_tty(wrapped))
    File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 17, in is_stream_closed
      return not hasattr(stream, 'closed') or stream.closed
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
    Running setup.py install for torch-scatter ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"'; __file__='"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\1583548\AppData\Local\Temp\pip-record-7d0cj2dr\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\1583548\AppData\Roaming\Python\Python36\Include\torch-scatter'
         cwd: C:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\placeholder.py -> build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\scatter.py -> build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\utils.py -> build\lib.win-amd64-3.6\torch_scatter
    copying torch_scatter\__init__.py -> build\lib.win-amd64-3.6\torch_scatter
    creating build\lib.win-amd64-3.6\torch_scatter\composite
    copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.6\torch_scatter\composite
    copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.6\torch_scatter\composite
    copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.6\torch_scatter\composite
    copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.6\torch_scatter\composite
    running build_ext
    C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'torch_scatter._scatter_cpu' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\Users
    creating build\temp.win-amd64-3.6\Release\Users\1583548
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc
    creating build\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\cpu
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\THC -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\" /EHsc /TpC:\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\scatter.cpp /Fobuild\temp.win-amd64-3.6\Release\Users\1583548\AppData\Local\Temp\pip-install-b92l6kvp\torch-scatter_5b2264bb35584445b5cb65709b56d255\csrc\scatter.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -O2 -DAT_PARALLEL_OPENMP /openmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0
    cl : Command line error D8003 : missing source filename
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\initialise.py", line 20, in reset_all
        AnsiToWin32(orig_stdout).reset_all()
      File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 71, in __init__
        strip = conversion_supported or (not is_stream_closed(wrapped) and not is_a_tty(wrapped))
      File "C:\ProgramData\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 17, in is_stream_closed
        return not hasattr(stream, 'closed') or stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"'; __file__='"'"'C:\\Users\\1583548\\AppData\\Local\\Temp\\pip-install-b92l6kvp\\torch-scatter_5b2264bb35584445b5cb65709b56d255\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\1583548\AppData\Local\Temp\pip-record-7d0cj2dr\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\1583548\AppData\Roaming\Python\Python36\Include\torch-scatter' Check the logs for full command output.

**Comment by rusty1s** [comment]
Can you try to install via:
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
```

**Comment by Arun0013** [comment]
I am getting the following error when installing via 
`pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html`


ERROR: Could not find a version that satisfies the requirement torch-scatter
ERROR: No matching distribution found for torch-scatter

**Comment by rusty1s** [comment]
That is weird. Where are you located? You can also try to directly install from the wheel link, e.g.:
```
pip install https://pytorch-geometric.com/whl/torch-1.8.0+cpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl
```

**Comment by Arun0013** [comment]
Unfortunately, this also did not work. I am getting the following error:

ERROR: HTTP error 403 while getting https://pytorch-geometric.com/whl/torch-1.8.0+cpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl
ERROR: Could not install requirement torch-scatter==2.0.6 from https://pytorch-geometric.com/whl/torch-1.8.0+cpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl because of HTTP error 403 Client Error: Forbidden for url: https://pytorch-geometric.com/whl/torch-1.8.0+cpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl for URL https://pytorch-geometric.com/whl/torch-1.8.0+cpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl

I am located in India.

**Comment by rusty1s** [comment]
Sorry to hear. Does this link work for you?
https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.8.0%2Bcpu/torch_scatter-2.0.6-cp36-cp36m-win_amd64.whl

**Comment by Arun0013** [comment]
Thanks a ton! This link worked, and I installed the package as well. 

Could you please provide the links for the following packages as well:
torch-sparse
torch-cluster
torch-spline-conv

**Comment by rusty1s** [comment]
The beginning of the URL is the same for all of them. Just replace the `torch_scatter-2.0.6` naming with the corresponding names of the other packages, see [here](https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html).

**Comment by Arun0013** [comment]
I am now able to use PyTorch Geometric. Thanks for your support. And, thanks for creating such a useful package! 👍

**Comment by khlaifiabilel** [comment]
> `pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html`

Thank you , this cmd solved my problem

**Comment by RoshiniDantuluri** [comment]
Hi 
I tried everything listed above. None of them seem to work for me. Could someone help me out with this

**Comment by akihironitta** [comment]
@RoshiniDantuluri I'd recommend opening a new issue and sharing the commands you ran, your env detail and full error message there.
