### ISSUE TITLE
additional outputs (embeddings etc) in forward function

### ISSUE THREAD

**Issue by iceland20** [rusty1s/pytorch_geometric#2385]
Hi,
I am trying to look into intermediate output of my GNN class. To achieve that, I am adding extra output elements, as in:
```
def forward(self, data):
    edge_attr, edge_index, x = data.edge_attr, data.edge_index, data.x
    n = self.CONV(x, edge_index)
    e = self.MLPe(edge_attr)

    src, dst = edge_index
    s = self.MLP(torch.cat([n[src], n[dst], e], dim=-1))
    r = torch.nn.functional.linear(s, self.W, self.B)
    return r, n[src], n[dst], e
```
However, masking this while training (or testing) with the same mask that works for a single output
```
    out, n_s, n_d, e_ = model(data)[data.train_mask]
```
gives an error
TypeError: only integer tensors of a single element can be converted to an index

(Above, my `model` comes from
```
    model = Net().to(device)
    model.train()
```
)

The output is a tuple, but supplying a tuple of training masks does not help.

I am confused about how do to it properly? I know that people use more than one output in their codes, but somehow it does not harm them at the training stage...

**Comment by rusty1s** [comment]
You might only want to mask your actual output, i.e.:
```python
out, n_s, n_d, e_ = model(data)
out = out[data.train_mask]
```

**Comment by iceland20** [comment]
Sure, one can do that. But when I have some complicated mask patterns, I would still need to mask those extra outputs too. So, the only practical way is to do that later one by one, such as  
```
n_s = n_s[data.train_mask]
n_d = n_d[data.train_mask]
e_ = e_[data.train_mask]
```

Okay, given that people often use many outputs, I just thought your community has some more elegant ways. No problem, thank you very much, @rusty1s !

**Comment by rusty1s** [comment]
Alternatively, you can pass the `mask` directly to the model and do the underlying masking directly in the `model.forward` code.
