### ISSUE TITLE
From_NetworkX

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#239]
Adding a from_networkx module could be useful for someone looking to train quickly. I know they could write a few functions to make this happen, as that's what I'm doing, but this could be targeted for someone who finds this to be less intuitive.

**Comment by rusty1s** [comment]
This is a good idea and should be integrated. Will try to implement it ASAP.

**Comment by rusty1s** [comment]
Added to master and v1.2.0.
