### ISSUE TITLE
adding optional seed for shuffle datasets 

### ISSUE THREAD

**Issue by thegodone** [rusty1s/pytorch_geometric#2399]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for proposing new features.

## 🚀 Feature

can we add an option to set the seed for the shuffle of dataset ?

## Motivation

it's allow an easy way to benchmark results with predefined seeds

## Additional context

validation of models using default splits based on seed

**Comment by rusty1s** [comment]
You can achieve that by setting `torch.manual_seed(42)` before calling `shuffle`.

**Comment by thegodone** [comment]
thanks for the fast solution
