### ISSUE TITLE
Unnormalized ChebConv

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#242]
Hi,

This line `deg = degree(row, num_nodes, dtype=x.dtype)` in the `forward` of `ChebConv` should be changed to `deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)`.

Additionally, the Laplacian used in the paper is the scaled Laplacian, i.e., 2 * Lap / lamda_max - I_N. It doesn't restrict the Laplacian to be a normalized Laplaician, and it doesn't approximate lamda_max to be 2. Will you consider adding the choices over Laplacian and lamda?

**Comment by rusty1s** [comment]
Good catch. Fixed in master.

**Comment by sw-gong** [comment]
Btw, may I ask why you initiate the parameters of some conv operations with uniform and some with glorot? Or it's just because you wrote the code in different time? Which type of initialization do you prefer?

Thanks.

**Comment by rusty1s** [comment]
Actually no preference, both perform equally. I initially initialized all parameters uniform, but we had a few PRs who fixed initializations for operators which explicitly state their used initialization.

**Comment by sw-gong** [comment]
I see. Will you release an updated version of the library recently? It seems that there are some changes made and new modules introduced after the current latest released version.

**Comment by rusty1s** [comment]
Yes, will do this on monday.

**Comment by sw-gong** [comment]
Thanks.

**Comment by rusty1s** [comment]
v1.2.0 just released.

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/rusty1s/pytorch_geometric/issues/530.
