### ISSUE TITLE
Install issues on POWER, aka, make mostly-unsued dependencies optional

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [rusty1s/pytorch_geometric#2426]
## 🐛 Bug

Many of `pytorch_geometric`'s dependencies are entirely optional for the core library. Searching the codebase seems to indicate that the only "core" dependencies (those that are used anywhere except in a specific dataset or single transform) are
```
install_requires = [
    'numpy',
    'tqdm',
    'scipy',
    'networkx',
    'jinja2',
]
```

It would be nice if the other dependencies are specified as one or more `extras_require` sections, such as a `datasets` and `transforms` extras, for example. (Unfortunately, there does not appear to be a way to specify a default set of extras — see [here](https://discuss.python.org/t/adding-a-default-extra-require-environment/4898) — so the installation instructions would have to be updated correspondingly.) Alternatively, dependencies that are only used for specific datasets can just be wrapped in
```
try:
   
except ImportError:
    raise "useful message"
```
guards so that only users who need those dependencies will install them.

This is related to a specific bug: while trying to install `pytorch_geometric` on a ppc64 architecture cluster, we ran into issues related to the `llvmlite` dependency of `numba`, which is a `pytorch_geometric` dependency. `numba` is [only used](https://github.com/rusty1s/pytorch_geometric/search?q=numba) in the GDC transform. By commenting out `numba` in `setup.py` and its import in `gdc.py`, we were able to install and import `pytorch_geometric`.

**Comment by rusty1s** [comment]
Thanks! You are right. There are some packages that are not mandatory for installation or even using PyTorch Geometric. I will look into it.

**Comment by rusty1s** [comment]
`numba` should now be an optional dependency.

**Comment by simonbatzner** [comment]
Thanks! Another one was h5py which is only needed for certain datasets.

**Comment by rusty1s** [comment]
Should be fixed as well.

**Comment by simonbatzner** [comment]
Vielen Dank Matthias! :)
