### ISSUE TITLE
some questions about DenseDataLoader

### ISSUE THREAD

**Issue by MNLei** [rusty1s/pytorch_geometric#2428]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

when I load data by DenseDataLoader, the adj dimensionality will be one more dimension，is this correct or wrong？
```
dataset = TUDataset('data', 'MUTAG', transform=T.ToDense(30))
data_loader = DenseDataLoader(dataset, batch_size=16, shuffle=True)
for data in data_loader:
    print(data.adj.shape)
```
<img width="515" alt="截屏2021-04-20 下午4 54 41" src="https://user-images.githubusercontent.com/58616480/115367867-2420f380-a1f9-11eb-94a4-ec9624c283a6.png">

**Comment by rusty1s** [comment]
`MUTAG` comes with multi-dimensional edge features. You may want to remove them first before using `DenseDataLoader`:
```python
def my_transform(data):
    data.edge_attr = None
    return data

TUDataset(..., transform = my_transform)
```

**Comment by MNLei** [comment]
Thanks！！
