### ISSUE TITLE
about consecutive_cluster

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#243]
Hi,

```
def consecutive_cluster(src):
    unique, inv = torch.unique(src, sorted=True, return_inverse=True)
    perm = torch.arange(inv.size(0), dtype=inv.dtype, device=inv.device)
    perm = inv.new_empty(unique.size(0)).scatter_(0, inv, perm)
    return inv, perm
```

Is that really necessary to get the consecutive cluster, i.e., `inv` (IMO, original clusters are enough, or can you explain it)? So I think we only need to obtain the `perm` in order to calculate new `batch` right? `perm = scatter_('max', torch.arange(cluster.size(0), dtype=cluster.dtype, device=cluster.device), cluster)`.

Thanks.

**Comment by rusty1s** [comment]
Hi,
`perm` is just to calculate new `batch`. This is done via the much faster `scatter_` instead of using atomic operations like in `scatter_max`. The `inv` tensor is crucial, because it moves the cluster values to "consecutive" values (if you have a better name for this, please feel free to suggest), *e.g.*,
```python
cluster = [0, 0, 4, 3, 3, 4]
>>> inv = [0, 0, 2, 1, 1, 2]
```
This is both needed for graclus and voxel  grid pooling and enables clustering of nodes via scatter ops.

**Comment by sw-gong** [comment]
Hi,

You may not understand my point. My point is why we need the 'consecutive' value clusters (`inv` in your case) instead of using the original clusters (`cluster` in your case) which I think it should be enough (to obtain `perm` to calculate new batch and for graclus and voxel grid pooling, etc). Could you please give me a counter-example to show it's necessary to consecutive cluster values? Thanks.

Additionally, if we keep using the original clusters, we can obtain `perm` with one line `perm = scatter_('max', torch.arange(cluster.size(0), dtype=cluster.dtype, device=cluster.device), cluster)`.

**Comment by rusty1s** [comment]
Sure:
```python
cluster = [0, 0, 4, 3, 3, 4]
x = torch.randn(6, 32)
x_pooled = scatter_max(cluster, x, dim=0)  # -> wrong shape [5, 32] (we only have 3 supernodes)
inv = [0, 0, 2, 1, 1, 2]
x_pooled = scatter_max(inv, x, dim=0)  # -> correct shape [3, 32]
```

**Comment by sw-gong** [comment]
Hi @rusty1s 

I see where is the problem. Scatter_max woud fill the positions where without the corresponding cluster with `fill_value` which lead to shape [5, 32] instead of [3, 32]. Btw, do you need to update `def scatter_`? I just noticed that it may overflow with your current `fill_value=-1e38` if the `src` is int32 or int64.

**Comment by rusty1s** [comment]
`torch.scatter_` is the PyTorch scatter function and `torch_geometric.utils.scatter_` is the wrapper around the `scatter_add/mean/max` functions. We can lower the `fill_value` for int32 or int64, although we never `scatter_add/mean_max` any integer values. I will set it to `-1e9`.
