### ISSUE TITLE
GNN Explainer example not running 

### ISSUE THREAD

**Issue by Mandeep-Rathee** [rusty1s/pytorch_geometric#2431]
hello dear,

 I tried to run gnn_explainer example. I am getting the following error.

Traceback (most recent call last):
  File "gnn_explainer.py", line 43, in <module>
    explainer = GNNExplainer(model, epochs=200, return_type='log_prob')
TypeError: __init__() got an unexpected keyword argument 'return_type'

**Comment by rusty1s** [comment]
Are you using `torch-geometric==1.7.0`.

**Comment by Mandeep-Rathee** [comment]
No, I am using torch-geometric==1.6.1 Should I update the version? 

thanks

**Comment by rusty1s** [comment]
Yes, the `return_type` argument is only supported in `torch-geometric==1.7.0`. You can simply drop it in case you do not want to upgrade.

**Comment by Mandeep-Rathee** [comment]
thanks a lot
