### ISSUE TITLE
how could I stack the graph with different number of node and edge_index in to a mini-batch?

### ISSUE THREAD

**Issue by luciaL** [rusty1s/pytorch_geometric#2436]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for proposing new features.

**Comment by luciaL** [comment]
It will take a long to stack along one dimension with Dataloader. So I'd like to try the mini-batch method. But the DenseDataLoader and __cat_dim__ need the number of nodes is all the same.
class MyData(Data):
     def __cat_dim__(self, key, item):
         if key == 'foo':
             return None
         else:
             return super().__cat_dim__(key, item)

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/rusty1s/pytorch_geometric/discussions/2439.
