### ISSUE TITLE
Application/Benchmark Global Diff Pool to GraphSAGE

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#244]
It would be quite nice to see an implementation of a global_diff_pool, applied after some GraphSAGE convolution layers.

Can you recommend the quickest approach to handle this? I'll implement ASAP.

**Comment by rusty1s** [comment]
I am not sure what you mean by `global_diff_pool`? Can you elaborate?

**Comment by jlevy44** [comment]
Wasn't a well posed question. I think you have graphsage layers built into your diffpool module. Why DenseGraphSage vs regular? How large graphs could I run this on, and can it be variable sized inputs?

Seeking to train on sequences of ~20-30k node graphs and find graph level representations to the make graph level predictions, but number nodes and node labels can be variable.

**Comment by jlevy44** [comment]
Nodes don't correspond between graphs

**Comment by jlevy44** [comment]
I can close this and open it up in a new issue, but pretty much I'd like to use GraphSAGE + DiffPool to make node level and graph level predictions on multiple graphs with no node correspondence.

**Comment by rusty1s** [comment]
Hi, you can do this like it in done in the examples (we do graph-level predictions there). Actually, GraphSAGE is not built into DiffPool. The DiffPool module just coarsens and downsamples *dense* adjacency and node feature matrices respectively. As long as your 20-30k dense node graphs fit into memory, DiffPool should work really well. Please note to use the `DenseDataLoader` which outputs adjacency matrices of shape `[batch_size, max_num_nodes, max_num_nodes]` with masks `[batch_size, max_num_nodes]` to indicate valid nodes.

**Comment by jlevy44** [comment]
Do you think 12 Gb GPU memory is sufficient?

**Comment by rusty1s** [comment]
This depends on how much clusters you wish to obtain in each DiffPool module. This is hard to say and should be verified experimentally.

**Comment by jlevy44** [comment]
Trying to convert to dense but am having issues.
```
    A = Variable(sparse_to_dense(batch.edge_index,num_nodes=y_true.size()[0]), requires_grad=True)#Variable(batch.edge_index, requires_grad=True) 
  File "", line 39, in sparse_to_dense
    adj = torch.sparse_coo_tensor(edge_index, edge_attr, torch.Size([N, N]))
RuntimeError: number of dimensions must be sparse_dim (446552) + dense_dim (0), but got 2
```

**Comment by rusty1s** [comment]
It seems that your `edge_index` does not have the correct shape. However, the entire call is so incorrect (you should never convert a batched sparse matrix to a dense one, because your memory will explode). You should use the transforms and Dataloaders of the DiffPool examples.

**Comment by jlevy44** [comment]
Got it thanks. I think I'm going to end up using graphsage instead of diffpool for now.
