### ISSUE TITLE
Why does tg.transforms.to_sparse_tensor switch row and col?

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [rusty1s/pytorch_geometric#2446]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hey,

While reading the source code of tg.transforms.to_sparse_tensor, I found it switches the place of row and col when creating the final adj. It is confusing and could anyone explain to me why we need such an operation. 
Link to the code: https://github.com/rusty1s/pytorch_geometric/blob/a719b0419f89c9d19535dee01ef9e6d42dbb5a35/torch_geometric/transforms/to_sparse_tensor.py#L51

Thanks.

**Comment by rusty1s** [comment]
Yes, this is intended. We use the `SparseTensor` class to make use of sparse matrix multiplication, for which one needs to use the transposed adjacency matrix to perform message passing from source to target nodes For example,
```
Z = A^T @ X
```
will pass neighboring features along their edges, while
```
Z = A @ X
```
will use "reverse" edges for message passing. Note that this is solely required for directed graphs.

**Comment by zhiqiangzhongddu** [comment]
I see. Thanks for your reply.
