### ISSUE TITLE
Training DiffPool with No Features

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#245]
Is it possible to train the benchmarked DiffPool with no features? I just wanted to train on graph structure alone, and only have the edge_index and node and graph level outcome classes.

Right now I'm having trouble because self.x is set to None. On another note, if self.x is none, I think there should be an automatic mechanism to set self.x in Data class to the sparse identity.

**Comment by jlevy44** [comment]
Is it better to just create torch.ones() for self.x versus an identity matrix?

**Comment by rusty1s** [comment]
Hi,
Actually, I'm not a big fan of *automatically* setting node features in case they are not given. It is important that users know what they are inputing into the network. For example, sparse identity should only be used in transductive learning scenarios, and heavily fails in inductive ones. Here, it is much more common to use a `one` vector or use something as one-hot encoded node degrees.

**Comment by jlevy44** [comment]
Sounds good to me. Thanks.
