### ISSUE TITLE
Is changing shape as part of the model differentiable?

### ISSUE THREAD

**Issue by talbenha** [rusty1s/pytorch_geometric#2454]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hi,
I have noticed something strange using PyG. 

I am trying to implement an edge classification task, and when I am changing the shape of the output that forwarded using the model, I get that the loss and the metric scores get stuck and do not improve (which indicates that the model is not learning) - I suspect that this operation doesn't differentiable, however, I used it before (in PyTorch for example) and everything works fine.

The method that I used for reshaping is 
with: `return x.reshape(curr_num_nodes, next_num_nodes)` - also tried to use `torch.view()`
without: `return x`

I have also tried to change the shape of the features to forward it to MLP- and I got the same results (NN didn't converge)

It really affects the algorithm I build so that with the reshaping I run Multi-label classification and in the second method binary classification (each with corresponding loss), is there a way to overcome the issue and use reshape?

Thanks in advance,
Tal

**Comment by rusty1s** [comment]
I doubt that utilizing `reshape` in PyG destroys the computation flow, there might be something else going wrong somewhere. Do you have a minimal example to reproduce? Otherwise, it might be a good idea to check if earlier parameters indeed receive no gradients.

**Comment by talbenha** [comment]
I overcame the issue, I had a problem in the implementation. Thanks a lot for the answer, you can close it
