### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by youjinChung** [rusty1s/pytorch_geometric#246]
I was using pytorch-geometric that I installed from github repo.
and got this error while running autoencoder example code with my custom dataset.

```
Traceback (most recent call last):
  File "json2edgelist.py", line 72, in <module>
    data = model.split_edges(data)
  File "/home/paperspace/miniconda2/envs/thesis/lib/python3.6/site-packages/torch_geometric-1.1.3-py3.6.egg/torch_geometric/nn/models/autoencoder.py", line 114, in split_edges
    row, col = data.edge_index
ValueError: too many values to unpack (expected 2)
```
I read that this is due to the confliction between pypi packages from former issues, I guess I got this issue using the master branch version.

**Comment by youjinChung** [comment]
Actually, I just checked again.
It worked well as example code without editing. but I just got this error when I run with my custom data.

**Comment by rusty1s** [comment]
Related https://github.com/rusty1s/pytorch_geometric/issues/221

**Comment by youjinChung** [comment]
Thank you so much!
