### ISSUE TITLE
Does negative_sampling properly work after train_test_split_edges?

### ISSUE THREAD

**Issue by Curt-Park** [rusty1s/pytorch_geometric#2475]
I would like to check that `negative_sampling` method always works properly after splitting edges by `train_test_split_edges`.

Let's say, we have positive edges: row=[0, 1, 2, 3, 4, 5] and col=[1, 2, 3, 4, 5, 6].
[`train_test_split_edges`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/train_test_split_edges.py#L6) possibly splits the positive edges into 3 pieces:
- train_pos_edge_index: [[2, 3, 4, 5], [3, 4, 5, 6]]
- val_pos_edge_index: [[0], [1]]
- test_pos_edge_index: [[1], [2]]

Next, we call [`negative_sampling(train_pos_edge_index)`](https://github.com/rusty1s/pytorch_geometric/blob/543128e2088909fca7a6a772fbb0ec183dd8e13a/torch_geometric/utils/negative_sampling.py#L15) and the following lines samples negative edges.
```python
# line 76 in negative_sampling.py
perm = sample(size, int(alpha * num_neg_samples)) 
mask = torch.from_numpy(np.isin(perm, idx.to('cpu'))).to(torch.bool)
perm = perm[~mask][:num_neg_samples].to(edge_index.device) 
```

It samples arbitrary edges from all edges not included in `train_pos_edge_index`. I think sometimes it can sample the positive edges belong to `val_pos_edge_index` or `test_pos_edge_index` _as negative samples_, and it will cause incorrect estimation of a model while training.

Am I missing something at this point?

**Comment by rusty1s** [comment]
Yes, this is intended. Given the standard machine learning scenario of hold-out validation and test sets, it might well happen that positive validation edges and test edges appear as negative samples during training. We are not allowed to acknowledge their existence during training to prevent any data leakage. Although this seems to be counter-intuitive at first glance, it is to be expected that such a noise in the learning signal is averaged out during optimization.

**Comment by Curt-Park** [comment]
@rusty1s Thanks for your answer. I will close this issue.
