### ISSUE TITLE
About install pytorch-geometric

### ISSUE THREAD

**Issue by cainiaoshidai** [rusty1s/pytorch_geometric#2476]
## ❓ Questions & Help

Hi,

I installed pytorch1.8 via source code, and when I install `pytorch-geometric` according to the instructions in the `readme`, everything works fine. But when I run i`mport torch_geometric`, the following error occurs.

```
(py3) gzm@gzm:~$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/gzm/anaconda3/envs/py3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/gzm/anaconda3/envs/py3/lib/python3.7/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationESs
>>> 

```

Can you give me some advice? Thank you.

**Comment by rusty1s** [comment]
Yes, this is a standard error, see [here](https://github.com/rusty1s/pytorch_geometric/search?q=undefined+symbol%3A&type=issues). In general, this error is produced by a mismatch between your actual PyTorch version and the expected PyTorch version of the corresponding extension packages.

You should make sure that there do not exist multiple PyTorch versions in your local environment, and that the extension package you install corresponds to PyTorch 1.8.0/PyTorch 1.8.1.

**Comment by cainiaoshidai** [comment]
> Yes, this is a standard error, see [here](https://github.com/rusty1s/pytorch_geometric/search?q=undefined+symbol%3A&type=issues). In general, this error is produced by a mismatch between your actual PyTorch version and the expected PyTorch version of the corresponding extension packages.
> 
> You should make sure that there do not exist multiple PyTorch versions in your local environment, and that the extension package you install corresponds to PyTorch 1.8.0/PyTorch 1.8.1.

Thank you for your reply. But because of the equipment, I have to install `pytorch` with source code, so I don't know how I can solve this problem. I know a general direction is to install the `pytorch` version that only supports GPU, but I don't know what to do next. Can you give me some suggestions?

**Comment by rusty1s** [comment]
Did you install PyTorch 1.8 from source or the current master? You may need to install the extension packages from source too in case of the latter.

**Comment by cainiaoshidai** [comment]
> Did you install PyTorch 1.8 from source or the current master? You may need to install the extension packages from source too in case of the latter.

I installed `pytorch` from the current master. So I need to install `torch-scatter`  `torch-sparse`  `torch-cluster`  `torch-spline-conv` `torch-geometric`  with source code, right?  
There is another problem, I can't find the source code other than `torch-geometric`.

**Comment by rusty1s** [comment]
You only need to install `torch-scatter` and `torch-sparse`. The other two are optional. Those are located here:
* https://github.com/rusty1s/pytorch_scatter
* https://github.com/rusty1s/pytorch_sparse

**Comment by cainiaoshidai** [comment]
Thank you very much.
