### ISSUE TITLE
Update from PyG 1.6.0 to 1.7.0

### ISSUE THREAD

**Issue by adhikarirsr** [rusty1s/pytorch_geometric#2479]
Hi, 
I have cuda 10.2
I just updated to these:
```
torch==1.8.0
torch-cluster==1.5.9
torch-geometric==1.7.0
torch-scatter==2.0.6
torch-sparse==0.6.9
torch-spline-conv==1.2.1
torchvision==0.9.0
```
When I do this:
```
Python 3.7.4 (default, Sep 11 2019, 11:24:51)
[GCC 6.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_geometric
>>> from torch_geometric.nn import GCNConv
**Illegal instruction**
```
I get illegal instruction 

If I try to run PyG from jupyter notebook, the kernel dies.

All these:
```
from torch_geometric.data import InMemoryDataset, Data, DataLoader
from torch_geometric.utils import grid
from torch_geometric.transforms import Cartesian
```
load fine 

I pip uninstalled
```
torch-cluster==1.5.9
torch-geometric==1.7.0
torch-scatter==2.0.6
torch-sparse==0.6.9
torch-spline-conv==1.2.1
```
and reinstalled them but it didn't resolve my problem.

I would really appreciate any help to resolve it.

**Comment by rusty1s** [comment]
Never heard of `Illegal instruction` before. What happens if you do:
```
import torch_scatter
```
Does that work?

**Comment by adhikarirsr** [comment]
I disconnect from the high-performance cluster and restarted everything a couple of times and now everything seems to load fine.

I had done the same thing before and it didn't work.  For now, I will close this post and open it again if needed.
Thanks!
