### ISSUE TITLE
Help with using S3DIS

### ISSUE THREAD

**Issue by edshkim98** [rusty1s/pytorch_geometric#2483]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hi, I am trying to use S3DIS dataset from torch geometric.
So far, I downloaded the data by `dataset = S3DIS(root = '../tmp/s3dis')` and I checked that dataset[0] gives me 4096 sampled points. However, I don't quite understand all the files. 
1. Why did you separate into 'raw' and 'processed' file?
2. How and where can I access to test area file?

Thank you and sorry if this was a stupid question

**Comment by rusty1s** [comment]
1. We follow `torchvision` here and separate the raw data and the processed data for faster loading. The processed files contain the raw files converted into the `torch_geometric.data.Data` format.
2. You can set `S3DIS(..., train=False)` for accessing the test data.

**Comment by edshkim98** [comment]
@rusty1s  Hi, thank you for the reply.
So just to confirm once more, if let's say I've ran S3DIS( test_area=6,.... train=True), then will I only get files only with the area from 1-5 (no area 6)? Also, to get the area 6 for test data, then I shud write S3DIS( test_area=6,.... train=False). Is this correct?

**Comment by edshkim98** [comment]
I am asking this because when I ran S3DIS( test_area=6,.... train=True), I get bunch of files in raw folder from ply_data_all_1.h5 to ply_data_all_23.h5, but it doesn't state anything about the name of area...

**Comment by rusty1s** [comment]
Yes, this is correct:
* `S3DIS( test_area=6,.... train=True)` will return areas 1-5 for training
* `S3DIS( test_area=6,.... train=False)` will return area 6 for testing

There should be additional files in the `raw/` folder (`all_files.txt` and `room_filelist.txt`) which denote the correspondence of files to their respective areas.

**Comment by edshkim98** [comment]
@rusty1s  Thank you for the quick reply!
Just a one last question, I've noticed each data sample is sampled into 4096 points. 
Does this follow the same pre-processing as PointNet? (e.g. 1*1m block randomly sampled 4096 points)

**Comment by rusty1s** [comment]
Yes, I think so, but I'm not 100% certain anymore. Might be good to double check.
