### ISSUE TITLE
return src.index_select(self.node_dim, index) IndexError: index out of range in self (EdgeConv)

### ISSUE THREAD

**Issue by eitan159** [rusty1s/pytorch_geometric#2486]
Hello everyone,

I used ModelNet10 dataset with pre_transform=EgdeToFace() and transform=SamplePoints(1024).
like this:

dataset_train = ModelNet(path, name="10", train=True, transform=torch_geometric.transforms.SamplePoints(1024),
                        pre_transform=torch_geometric.transforms.FaceToEdge(), pre_filter=None)

**this is my model:**
class Net(torch.nn.Module):
    def __init__(self, num_features, num_classes, dim_size, dropout):
        super(Net, self).__init__()

        dim = dim_size
        self.dropout = dropout

        nn1 = Sequential(Linear(2 * num_features, dim), ReLU(), Linear(dim, dim))
        self.conv1 = EdgeConv(nn1)
        self.bn1 = torch.nn.BatchNorm1d(dim)

        nn2 = Sequential(Linear(2 * dim, dim, bias=False), ReLU(), Linear(dim, dim, bias=False))
        self.conv2 = EdgeConv(nn2)
        self.bn2 = torch.nn.BatchNorm1d(dim)

        nn3 = Sequential(Linear(2*dim, dim, bias=False), ReLU(), Linear(dim, dim, bias=False))
        self.conv3 = EdgeConv(nn3)
        self.bn3 = torch.nn.BatchNorm1d(dim)

        nn4 = Sequential(Linear(2*dim, dim, bias=False), ReLU(), Linear(dim, dim, bias=False))
        self.conv4 = EdgeConv(nn4)
        self.bn4 = torch.nn.BatchNorm1d(dim)

        nn5 = Sequential(Linear(2*dim, dim, bias=False), ReLU(), Linear(dim, dim, bias=False))
        self.conv5 = EdgeConv(nn5)
        self.bn5 = torch.nn.BatchNorm1d(dim)

        self.fc1 = Linear(dim, dim)
        self.fc2 = Linear(dim, num_classes)

def forward(self, x, x_2, y, y_2, edge_index, edge_index_2, batch, batch_2):
            x = F.relu(self.conv1(x, edge_index))
            x = self.bn1(x)
            x = F.relu(self.conv2(x, edge_index))
            x = self.bn2(x)
            x = F.relu(self.conv3(x, edge_index))
            x = self.bn3(x)
            x = F.relu(self.conv4(x, edge_index))
            x = self.bn4(x)
            x = F.relu(self.conv5(x, edge_index))
            x = self.bn5(x)
            x = global_add_pool(x, batch)
            x = F.relu(self.fc1(x))
            x = F.dropout(x, p=self.dropout, training=self.training)
            x = self.fc2(x)
            return F.log_softmax(x, dim=-1)

When i start training my model i get this error:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Eitan/Desktop/GIN/PCMModel.py", line 250, in <module>
    train()
  File "C:/Users/Eitan/Desktop/GIN/PCMModel.py", line 200, in train
    train_loss, model = train_epoch(model, epoch, epochs, train_loader, mixup_loader, optimizer)
  File "C:/Users/Eitan/Desktop/GIN/PCMModel.py", line 227, in train_epoch
    output = model(x=data.pos, x_2=None, y=data.y, y_2=None, edge_index=torch.LongTensor(data.edge_index), edge_index_2=None,
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:/Users/Eitan/Desktop/GIN/PCMModel.py", line 137, in forward
    x = F.relu(self.conv1(x, edge_index))
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch_geometric\nn\conv\edge_conv.py", line 51, in forward
    return self.propagate(edge_index, x=x, size=None)
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 233, in propagate
    coll_dict = self.__collect__(self.__user_args__, edge_index, size,
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 157, in __collect__
    data = self.__lift__(data, edge_index,
  File "C:\Users\Eitan\Desktop\GIN\venv\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 127, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self

**Comment by rusty1s** [comment]
You cannot use `FaceToEdge` in conjunction with `SamplePoints`. `SamplePoints` will sample points from mesh surface, and therefore the number of points and the given `edge_index` do not align anymore.

Alternatively, you can do:
```python
import torch_geometric.transforms as T

dataset_train = ModelNet(path, name="10", train=True,
                         transform=T.Compose([T.SamplePoints(), T.KNNGraph(k=6)]))
```

**Comment by eitan159** [comment]
Thanks you it's working.
But how I can make it run faster?  (It's very slowly and I'm using 2080ti gpu's)

**Comment by rusty1s** [comment]
I suggest to either drop the `BatchNorm` call or re-implement it, as there is currently a bug in PyTorch that slows down the network significantly, see https://github.com/rusty1s/pytorch_geometric/issues/2394.

**Comment by rusty1s** [comment]
You can also consider moving the `knn_graph` call directly to the GPU.

**Comment by eitan159** [comment]
How I can move the knn_graph call to the gpu? (I'm just a beginner)
