### ISSUE TITLE
ValueError: too many values to unpack (expected 2) 

### ISSUE THREAD

**Issue by ahtsham58** [rusty1s/pytorch_geometric#2489]
Hi,

I am trying to train a model and getting this error. I tried to find out workarounds but in vain.

Environment:
Pytorch=1.3.0
CUDA=10.1
torch_geometric==1.3.2

Here is the exact error message.

![image](https://user-images.githubusercontent.com/23135687/116401438-8a29fe00-a82b-11eb-9ba0-921dffe1406b.png)

Please suggest a possible solution. thanks!

**Comment by rusty1s** [comment]
What's the output of `torch.version.cuda` for you?

**Comment by ahtsham58** [comment]
**commands and their output**
python -c "import torch; print(torch.__version__)"
python -c "import torch; print(torch.version.cuda)"
python -c "import torch; print(torch.cuda.is_available())"
python -c "import torch; print(torch.cuda.current_device())"

**OutPut**

1.3.0
10.1.243
True
0


Everything is fine in terms of hardware activation.

**Comment by rusty1s** [comment]
Are you sure you are using a version of `torch-cluster` that satisfies the PyTorch 1.3.0 dependeny, e.g., this one: https://github.com/rusty1s/pytorch_cluster/releases/tag/1.4.5?

**Comment by ahtsham58** [comment]
I didn't get point exactly. Please explain it a little bit more. 
or how can I check torch-cluster compatibility with PyTorch 1.3.0?

**Comment by rusty1s** [comment]
Are you able to run "normal" PyTorch in GPU mode? https://github.com/pytorch/pytorch/issues/5046 might also be related.

**Comment by ahtsham58** [comment]
@rusty1s thanks man. this helps me to investigate the code developed by someone else. And the problem was the same. i.e os.environ["CUDA_VISIBLE_DEVICES"] = '3' was mentioned in the code and I converted it to os.environ["CUDA_VISIBLE_DEVICES"] = '0'

Problem solved
