### ISSUE TITLE
ERROR: Failed building wheel for torch-scatter

### ISSUE THREAD

**Issue by Gerrit28282** [rusty1s/pytorch_geometric#2494]
## 📚 Installation

Following the docs, installing torch-geometric worked fine. The rest of the packages not so much. I can't get to much out of the error log. Microsoft Visual Studio is up to date. Something seems to be wrong with the cl.exe compiler. 

[Error_log.txt](https://github.com/rusty1s/pytorch_geometric/files/6397143/Error_log.txt)

## Environment

* OS: Windows 10
* Python version: 3.8.3
* PyTorch version: 1.8.1+cpu
* CUDA/cuDNN version: none
* GCC version: 6.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):

From the docs: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cpu.html

* Any other relevant information:

## Checklist

- [x ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [~ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

I am using Anaconda and tried both the conda installation and using the pip commands. None of them worked. My graphics card sadly doesnt support CUDA so I have to run it on my CPU. This seems to cause the problems. I am out of ideas. Any help would be really appreciated. 

Greetings
Gerrit

**Comment by rusty1s** [comment]
Sorry for the misconfusion. The correct link is
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
```
(even for PyTorch 1.8.0).

**Comment by Gerrit28282** [comment]
Thanks a lot, totally worked that way. Should have properly read the docs where you mention that the pip command with 1.8.0 is for both pytorch 1.8.0 and 1.8.1.

**Comment by rusty1s** [comment]
Great :)
