### ISSUE TITLE
GATConv vs EdgeConv in edge_cnn.py

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#250]
In pytorch_geometric/benchmark/points/edge_cnn.py, is it just as legitimate to use GATConv operator instead of edge convolutions, EdgeConv? I wanted to incorporate an attention mechanism that would take a point cloud that was generated from another neural network, knn it, and then using attention weight the most important points in the point cloud for downstream graph-level predictions? 

I suppose is that what this script is getting at? If so, this would be immensely useful.

**Comment by rusty1s** [comment]
You lose out on all spatial information if you simply replace the EdgeConv with GATConv. Therefore, I can not recommend it.They way it sounds, you want to obtain graph-level representations using attention. You should therefore replace the global pooling call with [GlobalAttention](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.glob.GlobalAttention). [Here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/global_attention.py) is an example on how to use it.

**Comment by jlevy44** [comment]
Awesome. Do you think I could generate knn_graph and use the edge index with my input features x for global attention? Trying to make end-to-end neural network with CNN generating the point cloud.

**Comment by rusty1s** [comment]
Sure. Use KNN to generate the graphs, perform some convolution and use global attention afterwards.

**Comment by jlevy44** [comment]
Do you have any recommendations for debugging/optimizing this? My model isn't quite learning.

The flow is sample X (did not use fps because there are memory errors when passing all the data through the CNN) -> CNN -> knn -> EdgeConv -> Global Attention

**Comment by jlevy44** [comment]
@rusty1s

**Comment by tformal** [comment]
Hi @rusty1s , 
I have been struggling with related issues: could you develop a bit more when you say "You lose out on all spatial information if you simply replace the EdgeConv with GATConv" ? I am not sure I completely get the idea 
Thanks in advance

**Comment by rusty1s** [comment]
Well, the `EdgeConv` performs aggregation based on relative Cartesian coordinates `pos_j - pos_i` while the `GATConv` does not. You can, of course, input the absolute Cartesian coordinates as node features, but this kinda contradicts weight sharing (similar to when you input the pixel positions as features in `conv2d`). In addition, I'm not really sure if neighborhood attention provides any benefits for `EdgeConv` because the kernel might already learn similar behaviors.
