### ISSUE TITLE
Disable DataLoader UserWarning when using cuda

### ISSUE THREAD

**Issue by fonnesbeck** [rusty1s/pytorch_geometric#2504]
## 🐛 Bug

When `num_workers` is specified as zero on a multicore machine, you get the following warning:

    UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.

This is fine when the model is being fit using CPUs, but is not sound advice when using GPUs and data are being loaded to the GPU with `.to(device)`. Can this message be turned off when cuda is specified as the device?

## Environment

* OS: Ubuntu
* Python version: 3.7.10
* PyTorch version: 1.8
* CUDA/cuDNN version: 11

**Comment by fonnesbeck** [comment]
Sorry, this is a Lightning issue. Closing.

**Comment by rusty1s** [comment]
Yes, I don't link this warning either :D
