### ISSUE TITLE
Segmentation Fault in Forward Loop of Edge Conv

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#251]
Hey there!

I'm testing out edge conv and am running into some issues. I'm getting a segmentation fault during the knn_graph generation:

```
line 13: 14361 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES="$gpuNum" python ...
```

Here's output using pysnooper, I traced the error to this location:
```
Starting var:.. batch = None
Starting var:.. pos = tensor([[-3.1472e-01, -7.1309e-01, -1.5181e-01,  1.3493e+00,  1.0879e+00,          4.9691e-01, -1.54...
Starting var:.. self = Net(  (conv1): EdgeConv(nn=Sequential(    (0): Linear(in_features=50, out_features=64, bias=True)   ...
17:39:03.629809 call        41  def forward(self, pos, batch):
17:39:03.680347 line        42          edge_index = knn_graph(pos, k=20, batch=batch)
~
```

Last line is where error is happening.

As more context, I'm generating my point cloud using a CNN, batch and positions are shown above, cannot seem to make it through the generation of the edge index.

Can you please help me out here?

**Comment by rusty1s** [comment]
Hard to say, you should verify that the tests of pytorch-cluster work. If this is the case, the error is likely to be in your side. You can test smaller point clouds and batches of size one to identify your error.

**Comment by jlevy44** [comment]
I’ll try it out. Segmentation faults were still happening even with small batch size (20 nodes, one graph at a time)

**Comment by jlevy44** [comment]
I have the right input, correct?

**Comment by jlevy44** [comment]
Could it be a pynndescent problem?

**Comment by jlevy44** [comment]
```
>>> import torch; print(torch.__version__)
1.0.1.post2
>>> if torch.cuda.is_available():
...     import torch_cluster.knn_cuda
... 
>>> dir(torch_cluster.knn_cuda)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'knn']
>>> x = torch.Tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
>>> batch_x = torch.tensor([0, 0, 0, 0])
>>> y = torch.Tensor([[-1, 0], [1, 0]])
>>> batch_y = torch.tensor([0, 0])
>>> assign_index = torch_cluster.knn_cuda.knn(x, y, 2, batch_x, batch_y)
Segmentation fault (core dumped)
```
I think I may just need to reinstall.

By the way, your doc string for knn in torch_cluster uses "batch_x" twice instead of using batch_y for its test module.

**Comment by jlevy44** [comment]
I reinstalled and am still getting the segmentation fault.

**Comment by jlevy44** [comment]
Works perfectly fine without GPU.

**Comment by jlevy44** [comment]
```
>>> import torch; print(torch.__version__)
x = torch.Tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
1.0.1.post2
>>> x = torch.Tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
>>> batch_x = torch.tensor([0, 0, 0, 0])
>>> y = torch.Tensor([[-1, 0], [1, 0]])
>>> batch_y = torch.tensor([0, 0])
>>> import torch_cluster
>>> assign_index = torch_cluster.knn(x, y, 2, batch_x, batch_y)
>>> assign_index
tensor([[0, 0, 1, 1],
        [1, 0, 3, 2]])
```

**Comment by jlevy44** [comment]
Could this have something to do with it:
```

                                   !! WARNING !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (/bin/x86_64-conda_cos6-linux-gnu-c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using /bin/x86_64-conda_cos6-linux-gnu-c++, and then you can also use
    /bin/x86_64-conda_cos6-linux-gnu-c++ to compile your extension.

    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                  !! WARNING !!

```

**Comment by rusty1s** [comment]
So first of all, are pytorch-cluster tests working? It could be due ti the compiler warning, but this is quite unreasonable because other subpackages seem to run fine for you. Does the error occur when running the benchmark scripts?

**Comment by jlevy44** [comment]
Some of the scatter tests failed as well. I’m not sure, haven’t tested but seems the CPU runs are fine, just struggling with GPU.

I ran the above test, which is the knn test line by line which reproduced the fault

**Comment by jlevy44** [comment]
I’ll try benchmark

**Comment by jlevy44** [comment]
Also, I’m on a cluster environment, so had to load a particular version of CUDA that the cluster offered

**Comment by jlevy44** [comment]
Before I installed the packages

**Comment by jlevy44** [comment]
I'm trying CUDA_HOST_COMPILER=gcc when I'm reinstalling pytorch from source and the other packages.

**Comment by jlevy44** [comment]
Seems to be working now.. I'll have to confirm with my pipeline.

**Comment by rusty1s** [comment]
Cool :)

**Comment by jlevy44** [comment]
Now torch sparse is failing.

**Comment by jlevy44** [comment]
:/

**Comment by jlevy44** [comment]
```
 cuda/spspmm_kernel.cu(78): error: no suitable user-defined conversion from "at::DeprecatedTypeProperties" to "const at::Type" exists
    
    1 error detected in the compilation of "/tmp/tmpxft_0000728f_00000000-6_spspmm_kernel.cpp1.ii".
    error: command '/opt/cuda/9.0-cuDNNv7/bin/nvcc' failed with exit status 1

```

**Comment by jlevy44** [comment]
Could it be related to: https://github.com/rusty1s/pytorch_sparse/issues/9

**Comment by rusty1s** [comment]
You can follow https://github.com/rusty1s/pytorch_geometric/issues/225 to fix.

**Comment by jlevy44** [comment]
Will removing spsmm cause my pipeline to fail? What are the implications of removing this?

**Comment by rusty1s** [comment]
There are none.

**Comment by jlevy44** [comment]
Cool.

**Comment by jlevy44** [comment]
Should I be building with nvcc instead of gcc?

Turn this: CUDA_HOST_COMPILER=gcc

Into this: CUDA_HOST_COMPILER=nvcc ?

**Comment by jlevy44** [comment]
```
import torch_sparse
...
import torch_sparse.unique_cuda
ModuleNotFoundError: No module named 'torch_sparse.unique_cuda'
```

**Comment by jlevy44** [comment]
Didn't make a difference, for some reason, after following your instructions, this extension will not load.

**Comment by jlevy44** [comment]
Ah, torch_scatter works now. Let's see if all of this did the trick.

**Comment by jlevy44** [comment]
Just need to run a few more tests. Seems like remaining issues are not related to the install (just on my side). Hopefully works now, but will confirm.

**Comment by jlevy44** [comment]
All is good on my end!
