### ISSUE TITLE
How to pass message inversely through an edge?

### ISSUE THREAD

**Issue by flowerbeach** [rusty1s/pytorch_geometric#253]
Hi! Thanks for build this powerful tool!

But I’d like to reproduce Gated Graph Neural Networks using PyG. I’m wondering how to pass message inversely through an edge, as the model mentioned in the paper uses features of nodes connected by both incoming and outgoing edges separately.

Thanks

**Comment by rusty1s** [comment]
Hi, you can change the `flow` direction in the `MessagePassing` interface to achieve this, *.e.g.*:
```python
def forward(self, x, edge_index):
    self.flow = 'source_to_target'
    incoming = self.propagate(edge_index, x=x)
    self.flow = 'target_to_source'
    outcoming = self.propagate(edge_index, x=x)
    return incoming + outcoming

def message(self, x_i, x_j):
    # Create messages: Branch dependent on `self.flow` (if needed)

**Comment by flowerbeach** [comment]
Thanks for your quick reply! I'll have a try.
