### ISSUE TITLE
torch_geometric.nn.radius gets different output/performance on GPU and CPU

### ISSUE THREAD

**Issue by zhan-xu** [rusty1s/pytorch_geometric#2531]
Hello!

I found my pointnet++ implementation performs differently on GPU and CPU, although all the randomness has been removed. I narrowed down and locate the difference at the function "torch_geometric.nn.radius". It gives different results on GPU and CPU. By fixing the rows and cols returned by this function, CPU and GPU performances get much closer. Do you have a sense about what the potential cause is?

Thanks!

**Comment by rusty1s** [comment]
Yeah, the `radius` GPU kernel is non-deterministic. It will return a random permutation of nodes that lay within the given radius in case the number of neighbors in larger than `max_num_neighbors`. The CPU version will return the closest ones. You can "fix" that by increasing the number of `max_num_neighbors` or reducing the `radius`.

**Comment by zhan-xu** [comment]
Thanks for clarifying this!
