### ISSUE TITLE
Download problems Reddit 5k and Reddit 12k

### ISSUE THREAD

**Issue by c-hofer** [rusty1s/pytorch_geometric#254]
## 🐛 Bug

The data set name specified in [https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets](url) for the 5K and 12K  Reddit datasets do not coincide with the dataset names used by the `torch_geometric.datasets.TUDataset` class. 

It is 
"REDDIT-MULTI-5k" vs "REDDIT-MULTI-5K"
and
"REDDIT-MULTI-12k" vs "REDDIT-MULTI-12K"

I don't know if this is a "real" bug, but as I needed some time to figure out what is going on, I decided to document it somewhere. :)

regards chris

## To Reproduce

```
dataset_name = "REDDIT-MULTI-5k"
# dataset_name = "REDDIT-MULTI-5K" # <-- this works, 'K' instead of 'k'
path = '/tmp/' + dataset_name
dataset = TUDataset(path, name=dataset_name)
```

**Comment by rusty1s** [comment]
Ah I see, the names do not match the urls. Can you fix this @chrsmrrs?

**Comment by chrsmrrs** [comment]
I changed the names in the table https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets#benchmark_data_sets_for_graph_kernels .
