### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin' when importing InMemoryDataset

### ISSUE THREAD

**Issue by hminle** [rusty1s/pytorch_geometric#2541]
Hi guys,

I got this but when trying to import `InMemoryDataset`
![image](https://user-images.githubusercontent.com/16201681/117232997-4bc6ad00-adf0-11eb-80be-1a33fc0cdfb3.png)

Could you guys help me to check it out?
Thanks.

## Environment

* OS: Linux
* Python version: 3.8
* pytorch_geometric: 1.7.0
* PyTorch version: 1.8.1
* CUDA/cuDNN version: 11.2

**Comment by rusty1s** [comment]
Please see: https://github.com/rusty1s/pytorch_geometric/issues/2429

**Comment by hminle** [comment]
Thank @rusty1s
