### ISSUE TITLE
How to obtain the graph index for TUDataset?

### ISSUE THREAD

**Issue by ha-lins** [rusty1s/pytorch_geometric#2542]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help
Hi,

I wonder how to obtain/construct the `index` for each graph in TUDataset, such as `1-188` in `MUTAG` dataset, since I wish to process graphs across batches. Can I get the graph id in `torch_geometric.data.Data`? 
![image](https://user-images.githubusercontent.com/22448743/117261183-72352880-ae82-11eb-8343-b01007007e0c.png)

Thanks a lot!

**Comment by rusty1s** [comment]
It's best to do this via `pre_transform`:
```python
class AddGraphIndices(object):
    def __init__(self):
        self.i = 0

    def __call__(self, data):
        data.graph_idx = i
        i += 1
        return data

TUDataset(..., pre_transform=AddGraphIndices())
```

**Comment by ha-lins** [comment]
Thanks for the solution! It's really helpful.
