### ISSUE TITLE
Enquiries about examples/ppi

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#255]
Hi,

I have a few questions regarding examples/ppi.
- Is the implemented architecture from any paper, can you post it here? 
- `preds.append((out > 0).float().cpu())` It can be considered as you use 0 as threshold to convert network output to positive and negative predictions. Is there any explanation about why it is 0 here? 

Thanks.

**Comment by rusty1s** [comment]
We try to follow the proposed GAT architecture for PPI. We use `0` as threshold because the network output does not integrate a sigmoid function (because we use the more stable `BCEWithLogitsLoss` as loss op).

**Comment by sw-gong** [comment]
I konw there is no a sigmoid function in the output of the model so the out \in R, but in this case, how to define or any hint to set this threshold? Additionally, how to interpret the model output in this case without a sigmoid since its value belongs to R?

**Comment by rusty1s** [comment]
The way we train it: `- infinity` for false labels, and `infinity` for true ones, so `0` is a reasonable threshold. We could actually search for more better thresholds using ROC curves, but I do not see the necessity here.

**Comment by sw-gong** [comment]
Thanks.
