### ISSUE TITLE
Can't extracte the .gz file such as Tox21 dataset in Moleculenet

### ISSUE THREAD

**Issue by Oceanusity** [rusty1s/pytorch_geometric#2550]
## 🐛 Bug
It seems like the extract_gz and extract_gz2 function can't find the downloaded compressed files.

## To Reproduce

dataset = MoleculeNet(root='.', name='Tox21')

File "/home/my_user/anaconda 3/envs/torch v1. 5/1ib/python3.8/site-packages/torch geometric/data/extract.py", 1ine 54, in extract_gz
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/tox21/raw/datasets/tox21//raw/tox 21. csv'

## Environment

* Python version: 3.8
* PyTorch version: 1.6.3

**Comment by Oceanusity** [comment]
By the way, for the bbbp dataset, the num_classes is 1. However, it should be 2 for bbbp dataset. Additional, the expression of dataset bbbp is BBPB which is a typo.  I am not sure whether these things have been fixxed in the latest version. Thank you for your patience, and this package is a quite convient and powerful work.

>>> dataset = MoleculeNet(root='.', name='bbbp')
>>> print(dataset.num_classes)
>>> 1
>>> dataset
>>> BBPB(2039)

**Comment by rusty1s** [comment]
The issue with relative paths should already be fixed in master. I also fixed the `num_classes` issue.
