### ISSUE TITLE
ModelNet40 Sample points crashes. 

### ISSUE THREAD

**Issue by Yannick-S** [rusty1s/pytorch_geometric#256]
## 🐛 Bug

There are some models in ModelNet40 which give problems when sampling a point cloud from their surface. The function SamplePoints (sample_points.py)  has the line
`
 area = (pos[face[1]] - pos[face[0]]).cross(pos[face[2]] - pos[face[0]])
`

I have done some digging, and some files have really really large dimensions. Meaning the pos[] has things of the order of 
tensor([[ 3.5578e+09, -6.4410e+10, -5.4855e+11],
        [-7.3821e+08, -6.7892e+10, -5.5279e+11],
        [ 7.1078e+08, -6.6997e+10, -5.6201e+11],
        ...,
        [-8.2806e+09,  6.2464e+11,  2.9970e+10],
        [-8.2806e+09,  6.2318e+11,  2.9970e+10],
        [-7.6240e+09,  6.2464e+11,  3.3878e+10]])

... which is big. Especially since taking the cross product in the next line, and then squariong in the line after gives even bigger results. 
This leads to areas of
tensor([       inf,        inf,        inf,  ..., 3.3477e+18, 2.8870e+18,
        2.8870e+18])
, which then leads to invalid probabilities when sampling from torch.multinomial.

A quick fix is simply adding

pos = pos / pos.max()

the line after the second assert.

       
## To Reproduce

1.
1.
1.

## Expected behavior

I expect this not to crash. But it does

## Environment

* OS: Ubuntu 16.04
* Python version: 3.5
* PyTorch version: 1.0
* CUDA/cuDNN version: 10.1
* GCC version:
* Any other relevant information:

**Comment by Yannick-S** [comment]
I think  my fix works, it doesn't crash anymore. If you also believe that it is still correct, then i will add a pull request.

**Comment by rusty1s** [comment]
Thank you. I didn't know that. The only concern I'm having is that we are changing the models position this way (which is not what the user might expect).

**Comment by Yannick-S** [comment]
what about scaling all the sampled poitns back up by saving pos.max() 

pos_max = pos.max()
pos = pos / pos_max
...#get samples
point_cloud *= pos_max

**Comment by rusty1s** [comment]
Yes, we should definitely do this. Thank you. Waiting for your PR.

**Comment by NT795** [comment]
Hi, I have used the Sample_points.py code in master, however, there still an error exists when sampling 2048 points from the Training dataset in ModelNet40(Test dataset is ok). As you have met, the error is 'RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry < 0)'. I'm wondering if some negative Numbers caused this error when calculate `area = (pos[face[1]] - pos[face[0]]).cross(pos[face[2]] - pos[face[0]])`?

**Comment by rusty1s** [comment]
Interesting. In theory, `area` can not be negative due to the `norm` in line 29. I added an `abs` call to the `area` computation. Can you verify that this fixes your problem?

**Comment by NT795** [comment]
Unfortunately, this was not resolved, but I found this error occurred when sampling the 3559th training dataset in ModelNet40. I'm going to take a closer look at what's so special about this graph. 
BTW, the transformation operation does not seem to work in ModelNet. For example, when I use the following code, there is no sampling and the data obtained is not transformed.
`modelnet40_trainset=ModelNet(root='XXX',name='40',transform=SamplePoints(2048))
modelnet40_testset=ModelNet(root='XXX',name='40',train=False,transform=SamplePoints(2048))`
Am I making a mistake?
So now for sampling purposes, my code is written like this.
`modelnet40_trainset=ModelNet(root='XXXX',name='40')
modelnet40_testset=ModelNet(root='XXXX',name='40',train=False)
samler=SamplePoints(2048)
modelnet40_testset=[samler(d) for d in modelnet40_testset]
modelnet40_trainset=[samler(d) for d in modelnet40_trainset[0:3559]]
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
`

**Comment by rusty1s** [comment]
Are you sure? There is no reason `ModelNet40` would not call `transform` upon access.

**Comment by NT795** [comment]
> Are you sure? There is no reason `ModelNet40` would not call `transform` upon access.

Yeah, if I use the code `modelnet40_trainset=ModelNet(root='XXX',name='40')`, then I will get `modelnet40_trainset=ModelNet40(9843), modelnet40_trainset.data=Data(face=[3,177419739],pos=[178128692,3],y=[9843]), moedelnet40_trainset.transform=None`.

However, if I use the code `modelnet40_trainset=ModelNet(root='XXX',name='40',transform=SamplePoints(2048))`, then I will get `modelnet40_trainset=ModelNet40(9843), modelnet40_trainset.data=Data(face=[3,177419739],pos=[178128692,3],y=[9843]), moedelnet40_trainset.transform=SamplePoints(2048)`.

The PyG I'm using is 1.2.0

**Comment by rusty1s** [comment]
Hi, I understand. `transform` gets called when accessing *specific* dataset examples (equivalent to `torchvision` datasets), *e.g.*:
```python
modelnet40_trainset[0]
```
It does not get called when accessing the internal data storage `dataset.data` (which you should access neither).

**Comment by NT795** [comment]
> Hi, I understand. `transform` gets called when accessing _specific_ dataset examples (equivalent to `torchvision` datasets), _e.g._:
> 
> ```python
> modelnet40_trainset[0]
> ```
> 
> It does not get called when accessing the internal data storage `dataset.data` (which you should access neither).

Oh, I see. THX!
