### ISSUE TITLE
Global Attention with None Batch

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#258]
Hey there! Started running Global attention, but I want to run it with None batch size, which works on some other modules. For some reason, it is not working here. Can you modify global attention to allow None data.batch?

```
torch_geometric/nn/glob/attention.py", line 41, in forward
    size = batch[-1].item() + 1 if size is None else size
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jlevy44** [comment]
Perhaps you mean to replace size with batch for size is None?

**Comment by rusty1s** [comment]
Mh, actually not a big fan of this idea, because it facilitates the misuse of these operators in mini-batch scenarios (e.g., when simply forgetting to pass the batch assignment vector). You should input a zero-filled batch vector instead.

**Comment by jlevy44** [comment]
Ah okay. I'm working on getting this incorporated into my pipeline. I'll let you know if this works.

**Comment by jlevy44** [comment]
I got it to work, but the embeddings of my graphs are pretty bad. I just extracted the output of the embedding and ran PCA for quick visualization.

Would it be better to run global attention or top k-pooling? 

Are dynamic knn and EdgeConv useful even if the dimensionality of the data is 100-D+?
