### ISSUE TITLE
MessagePassing and GMMConv

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#259]
Hi,

- `MessagePassing`:
```
        message_args = []
        for arg in self.__message_args__:
            if arg[-2:] in ij.keys():
                tmp = kwargs[arg[:-2]]
                if tmp is None:  # pragma: no cover
                    message_args.append(tmp)
                else:
                    idx = ij[arg[-2:]]
                    if isinstance(tmp, tuple) or isinstance(tmp, list):
                        assert len(tmp) == 2
                        if size[1 - idx] is None:
                            size[1 - idx] = tmp[1 - idx].size(0)
                        if size[1 - idx] != tmp[1 - idx].size(0):
                            raise ValueError(__size_error_msg__)
                        tmp = tmp[idx]

                    if size[idx] is None:
                        size[idx] = tmp.size(0)
                    if size[idx] != tmp.size(0):
                        raise ValueError(__size_error_msg__)

                    tmp = torch.index_select(tmp, 0, edge_index[idx])
                    message_args.append(tmp)
            else:
                message_args.append(kwargs[arg])

        size[0] = size[1] if size[0] is None else size[0]
        size[1] = size[0] if size[1] is None else size[1]

        kwargs['edge_index'] = edge_index
        kwargs['size'] = size
```
If someone pass `x_i` and `edge_attr_i` to `message` when create new operators, the inferred size which would come from the size of parameter from the later position is then unpredictable.

- `GMMConv`
I noticed that you updated GMMConv yesterday, but I'm not quite sure about the reasons of the following changes
```
        if self.root is not None:
            out = out + torch.matmul(x, self.root)
```
If considering root node, I think the root feature should be weighted by the weight function before linear transformation. Therefore, why not just add self-loop to each node and perform all the operations as before.

```
        # Normalize gaussians across edge dimension.
        gaussian_sum = scatter_add(
            gaussian, edge_index_i, dim=0, dim_size=size_i)[edge_index_i]
        gaussian = gaussian / (gaussian_sum + EPS)
```
There is no such normalization step in the GMM definition. Where is this from?

Thanks.

**Comment by rusty1s** [comment]
Hi,
I do not understand your point concerning `x_i` and `edge_attr_i`. The usage of `edge_attr_i` is just wrong, only node features should be mapped via `_i` and `_j`.
Concerning `GMMConv`, I added the root node to be in line with other operators such as `SplineConv` oder `NNConv`. You can of course manually add self-loops to the graph and pass `root_weight=False`. The normalization of gaussians is borrowed from [here](https://github.com/shchur/gnn-benchmark/blob/master/gnnbench/models/monet.py#L48).

**Comment by sw-gong** [comment]
Hi,
In some cases, `edge_attr_i` may not wrong. What if someone works on directed graphs, `edge_attr_i` and `edge_attr_j` are then different and they might use it as parameter of `message`. For example, if they define it as `message(self, x_i, x_j, edge_attr_j, edge_index)`, the inferred size would be `edge_attr.size(0)` != `x.size(0)`. If they change the position of `x` and `edge_attr`, they would then get a different `size` consequently.  

Indeed, you can ignore it if we agree with only mapping node featuers via `_i` and `_j` (then the inferred size would be aways `num_nodes`). 

Btw, may I ask why GMMConv (and most of other graph_conv operators) does linear transformation in the end, whileas the original definition of the paper does not make it clear about how to map input features to differnet channels of output features (they only define how to map to a single channel of output feature)? Can I understand it as it is just the general choice to map input features to output features with different dimension by **linear transformation**? I'm not sure if I make it clear.

Thanks.

**Comment by rusty1s** [comment]
In PyG, working with directed or undirected graphs is the same (we encode double edges for undirectes graphs). Hence, for each edge, there is only one `edge_attr`, *e.g.*:
```python
def message(self, x_i, x_j, edge_attr):
    # x_i has shape [E, F]
    # x_j has shape [E, F]
    # edge_attr has shape [E, D]
```
The "linear" transformation is a classic in deep learning. Often operators are only defined for a single input/output channel. Its generalization is mapping all input channels to a single output channel.

**Comment by sw-gong** [comment]
Thanks for your clarification.

_Its generalization is mapping all input channels to a single output channel and repeat this out_channels times._

If following this, there is no need to do linear transformation for `GMMConv`, isn't it? Why not repeat the operations prior to linear transformation over `out_channels` times to generate output features?

**Comment by rusty1s** [comment]
Because there would be no transformation, only a data-dependent aggregation. They way I formulated it above might be a bit misleading concerning `GMMConv`, because the mixture gaussians only act as an attention mechanism on neighboring nodes., which can not transform any features.
