### ISSUE TITLE
Hypergraph Convolution and Hypergraph Attention

### ISSUE THREAD

**Issue by MendelXu** [rusty1s/pytorch_geometric#260]
## 🚀 Feature

Hypergraph Convolution and Hypergraph Attention https://arxiv.org/pdf/1901.08150.pdf,
## Motivation

I am trying to implement this paper https://arxiv.org/pdf/1901.08150.pdf, which I find interesting variants of GNNs. 

It proposes hypergraph convolution and hypergraph attention, high-order extensions of GCN and GAT.

Do you have any plan to include it in Py-Geometric?
## Additional context

 I am happy to help because I have tried a bit.

**Comment by rusty1s** [comment]
Hi, this is a good request. I do not know when I will have time to implement it, so I would be happy if you could present a first draft.

**Comment by MendelXu** [comment]
Thank you for your reply. I have implemented a daft and after some testing, I'll give the pr.

**Comment by rusty1s** [comment]
Really cool. Thank you!

**Comment by rusty1s** [comment]
Thanks again for your great contribution. I slightly updated the operator. I think we can close this issue.

**Comment by thupchnsky** [comment]
Hi,

I have some questions about the specific usage of this method. What exactly does `hyperedge_index` means in `forward` and how should we get it from the incidence matrix? It would be great if you can just show me a small example!

Thanks in advance for your help! I am using it as a baseline method so your help on this is greatly appreciated.

**Comment by rusty1s** [comment]
`hyperedge_index` refers to the indices of a sparse incidence matrix. Sorry if that wasn't clear enough.

**Comment by thupchnsky** [comment]
Thanks for the reply. Just want to check if I understand this correctly. This is the forward function for HCHA:
```python
def forward(self, x, hyperedge_index, hyperedge_weight=None):
        r"""
        Args:
            x (Tensor): Node feature matrix :math:`\mathbf{X}`
            hyper_edge_index (LongTensor): Hyperedge indices from
                :math:`\mathbf{H}`.
            hyperedge_weight (Tensor, optional): Sparse hyperedge weights from
                :math:`\mathbf{W}`. (default: :obj:`None`)
        """
        x = torch.matmul(x, self.weight)
        alpha = None

        if self.use_attention:
            x = x.view(-1, self.heads, self.out_channels)
            x_i, x_j = x[hyperedge_index[0]], x[hyperedge_index[1]]
            alpha = (torch.cat([x_i, x_j], dim=-1) * self.att).sum(dim=-1)
            alpha = F.leaky_relu(alpha, self.negative_slope)
            alpha = softmax(alpha, hyperedge_index[0], num_nodes=x.size(0))
            alpha = F.dropout(alpha, p=self.dropout, training=self.training)
        ...
```
Both `hyperedge_index[0]` and `hyperedge_index[1]` are used. So I assume `hyperedge_index` should be a matrix with 2 rows. So if we have a hypergraph with 3 nodes and 2 hyperedges with incidence matrix H=[1, 0; 1, 1; 1, 1] of size 3x2 (I am assuming N means number of points and M means number of hyperedges), then the hyperedge_index would be [0, 1, 1, 2, 2; 0, 0, 1, 0, 1]. The first row means the index of nodes and second rows means the index of the edge. Then `hyperedge_weight` would just be a vector of size 2. Is this correct?

**Comment by rusty1s** [comment]
Yes, I also updated the documentation to explain the input format :)

**Comment by thupchnsky** [comment]
Thanks so much for the reply! But it seems that there is a bug when we try to use attention in this method. For the input x in `forward`, it should only contain node features. Then this line
```python
x_i, x_j = x[hyperedge_index[0]], x[hyperedge_index[1]]
```
does not make that much sense because `hyperedge_index[0]` corresponds to node indices and `hyperedge_index[1]` corresponds to edge indices. The value for `x_j` should be the "edge feature" according to paper; however, it is some other node feature in this case. Moreover, when the number of hyperedges is larger than the number of nodes, this line would cause out of bounds error. So I am wondering what could be a fix here? 

Thanks in advance for your help!

**Comment by rusty1s** [comment]
Yes, sorry. You are absolutely right. I fixed it by requiring an additional `hyperedge_attr` attribute (the features of each hyperedge) in `forward` in case `attention=True`.

**Comment by 1075793472** [comment]
Hello, I would like to ask how hyperedge_attr is obtained？

**Comment by rusty1s** [comment]
This depends on the dataset and its task. In general, `hyperedge_attr` denotes the features between a node and a given cluster.

**Comment by 1075793472** [comment]
Thanks so much for the reply!How do Cora datasets calculate hyperedge_attr？

**Comment by rusty1s** [comment]
`Cora` is just a regular graph, not a hypergraph, and it does not contain any edge features. In this case, `hyperedge_attr` is simply `None`.

**Comment by lorenz0890** [comment]
I am thinking of adapting this to accepting heterogeneous graphs. 

Is my understanding correct that for nodes 1 2 and 3 connected via edges 0 and 1 in the below `hyperedge_index`, `propagate` treats this case as if the edge indices were virtual nodes? 

```
 hyperedge_index = torch.tensor([
            [0, 1, 2, 1, 2, 3],
            [0, 0, 0, 1, 1, 1],
        ])
```

The `propagate` method doesn't seem to differentiate between edge indices in the form of `[[src_nodes], [target_nodes]] `and the type of `hyperedge_index` in the form of `[[nodes], [edges]] `.

**Comment by rusty1s** [comment]
Yes, you can consider a hyperedge as some form of virtual node that is only connected to a subset of nodes.
