### ISSUE TITLE
Python 3.9 Wheels

### ISSUE THREAD

**Issue by joelmac** [rusty1s/pytorch_geometric#2604]
Hello,

Can python 3.9 wheels be provided on the wheel distribution? I believe it is the latest stable version as of now. The current wheels have 3.6, 3.7, and 3.8 but not 3.9.

Thank you very much.

**Comment by rusty1s** [comment]
Yes, I will probably take care of that in the next release cycle.

**Comment by rusty1s** [comment]
Python 3.9 wheels are now included :)
