### ISSUE TITLE
Question about transmit Cora to mutiple GPU

### ISSUE THREAD

**Issue by jiaruHithub** [rusty1s/pytorch_geometric#2607]
I use several GCN layers with large amount of parameters training on the dataset ```Cora```.
I try to use mutiple GPU to train.
Is there any method that can transmit ```Cora``` to several GPUs ?
I understand the theory of transmiting a number of graphs to mutiple GPUs, but I don't understand how to send one graph to mutiple GPUs and train them.
Thank you for your answer!

**Comment by rusty1s** [comment]
You can use all regular PyTorch tools to achieve that, e.g.:
```python
model_cuda1 = copy.deepcopy(model).to('cuda:1')
model_cuda2 = copy.deepcopy(model).to('cuda:2')

data_cuda1 = copy.deepcopy(data).to('cuda:1')
data_cuda2 = copy.deepcopy(data).to('cuda:2')

model_cuda1(data_cuda1.x, data_cuda1.edge_index)
model_cuda2(data_cuda2.x, data_cuda2.edge_index)
```

**Comment by jiaruHithub** [comment]
This seems to be copied to other GPUs and I want to split ```Cora``` to train on multiple GPUs. To overcome my single GPU memory shortage. Splitting a single image into multiple GPUs for training seems impossible. Is that right?

**Comment by rusty1s** [comment]
Can you be more precise on what you want to do? Do you want to implement model or data parallelism on multiple GPUs? For data parallelism, we have some examples in `examples/multi_gpu` and `examples/pytorch_lightning`.

**Comment by jiaruHithub** [comment]
> Can you be more precise on what you want to do? Do you want to implement model or data parallelism on multiple GPUs? For data parallelism, we have some examples in `examples/multi_gpu` and `examples/pytorch_lightning`.

When I training my GCN model on ```Cora``` dataset, ```CUDA out of memory``` was reported. I want to use multi-GPU to tackle this problem.

**Comment by rusty1s** [comment]
I see. As said earlier, you have two options here:
* Data Parallelism: You only compute node embeddings in mini-batches, in which you can make use of sampling techniques such as `NeighborSampler`, `ClusterGCN` or `GraphSAINT`. The links above provide a good starting point to lift them to multiple GPUs
* Model Parallelism: You separate which computation is done on which GPU, as described [here](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html).

**Comment by jiaruHithub** [comment]
Thanks a lot! Best wishes!
