### ISSUE TITLE
Examples of Generative Model

### ISSUE THREAD

**Issue by nashid** [rusty1s/pytorch_geometric#2612]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for proposing new features.

## 🚀 Feature

Generative Model

## Motivation

**Pytorch Geometric** is easy to use and there are some great examples. However, Pytorch Geometric lacks examples of **generative models**. 

I am wondering whether there are any plans to include any of the following models:

- GraphRNN: https://github.com/JiaxuanYou/graph-generation

Also, Pytorch Geometric lacks examples of **Graph2Seq** based models. It would be awesome to consider any of the following Graph2Seq based **generative models**.

- Graph-to-Sequence Learning using Gated Graph Neural Networks, ACL’18, https://github.com/beckdaniel/acl2018_graph2seq
Using MXNet

- Densely Connected Graph Convolutional Networks for Graph-to-Sequence Learning, ACL’19
https://github.com/Cartus/DCGCN
Using MXNet 1.3.0

- Heterogeneous Graph Transformer for Graph-to-Sequence Learning, ACL’18 
https://github.com/QAQ-v/HetGT 
Using OpenNMT

## Additional context
I'm happy to contribute as well.

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_geometric/discussions/2614
