### ISSUE TITLE
GCN2Conv fails

### ISSUE THREAD

**Issue by zhaoyy0000** [rusty1s/pytorch_geometric#2617]
## ❓ Questions & Help
I met a problem:
There is no problem running ./example/gcn2_cora.py. But when i replace cora dataset with other, i get the return:

    `AttributeError: 'NoneType' object has no attribute 'view'`

   in file gcn2_conv.py, line 150, in message
    `return edge_weight.view(-1, 1) * x_j`

I have tried this method as suggested in #1833 , but I got loss = Nan

**Comment by rusty1s** [comment]
Can you show me the steps to reproduce? Which dataset are you using?

**Comment by zhaoyy0000** [comment]
Sorry, there is a problem with the dataset, I have revised it again, and there is no problem now . 
Thank you very much.
