### ISSUE TITLE
Question about edge weight in non-squared A matrix of GatedGraphConv

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#262]
## ❓ Questions & Help

May I ask how to implement a almost the same propagation as `GatedGraphConv` with weighted directed edges? The origin `GatedGraphConv` seems like doesn't support this setting. And for the non-squared shape `A` matrix. I have constructed the edge weight with `edge_attr` already.

![image](https://user-images.githubusercontent.com/17882988/57052941-fa015e80-6ccd-11e9-951e-49a76f3b369c.png)

with the `A` matrix as following:
![image](https://user-images.githubusercontent.com/17882988/57052946-0b4a6b00-6cce-11e9-8e80-d8f05178cc89.png)

Borrowing the code from `GatedGraphConv`, if I don't make it wrong, utilizing the edge weight is straight forward:

```python
def forward(self, x, edge_index, edge_attr):
    """"""
    h = x
    row, col = edge_index
    for i in range(self.num_layers):
        m = torch.matmul(h, self.weight[i])[col] * edge_attr
        m = self.propagate(edge_index, size=(x.size(0), x.size(0)), x=m)
        h = self.rnn(m, h)
    return h
```

It is still confusing for me to use the non-squared `A` matrix.
@rusty1s

**Comment by rusty1s** [comment]
Hi,
`edge_attr` should be integrated in the `message` function, *e.g.*:
```python
def message(self, x_j, edge_attr):
    return x_j * edge_attr
```
I am not exactly sure if I do understand your double adjacency matrix for outgoing and incoming edges (why not encode it in a single adjacency matrix?). However, I think in this case its best to pass two `edge_indices` to the `forward` pass and perform propagation two times, for each adjacency matrix individually.

**Comment by RuihongQiu** [comment]
Thanks! Oh right. `edge_attr` should be used in `message` function.

The double `A` matrix is just similar to Gated Graph.
![image](https://user-images.githubusercontent.com/17882988/57059199-70ff1d00-6cf7-11e9-80d1-5ccf5b3c0705.png)

 Seems like PyG doesn't consider this `A` settings? Different types of edges for outgoing and incoming?

**Comment by rusty1s** [comment]
Hi, I integrated `edge_weight` into the `GatedGraphConv`.

You are right. PyG does not consider this `A` setting explicitly. I'm not sure, it doesn't seem like outgoing and incoming edges are weighted differently? In this case, I do not see a reason why one can not encode these edges into a single adjacency matrix.

**Comment by RuihongQiu** [comment]
Wow! I saw the commit.

I think in the Gated Graph paper and the paper above mentioned, an edge has different meanings for the source node and target node. So it cannot encode two representations within the same grid in `A`.

**Comment by rusty1s** [comment]
If they have different meaning, they should be weighted independently. I do not see this in the above formula.

**Comment by RuihongQiu** [comment]
From the matrix, it shows that for the same edge, the weight for source node and target node is different, e.g. `B` for `1` and `B'` for `2` in edge `(1,2)` in Figure 1, Gated Graph paper above.

**Comment by rusty1s** [comment]
IMO, you can just encode this in a symmetric adjacency matrix with potentially different edge weights for incoming and outgoing edges. But I must confess that I don't quite understand this partitioning yet.

**Comment by RuihongQiu** [comment]
Uh, yeah. I get your idea. Just encode the two weights of an edge as a tuple in the `A` and that's enough. Do I make sense?

**Comment by rusty1s** [comment]
That's what I mean.

**Comment by RuihongQiu** [comment]
Cool! I get the idea and thank you very much!
