### ISSUE TITLE
MoleculeNet Transform Error

### ISSUE THREAD

**Issue by LanceKnight** [rusty1s/pytorch_geometric#2626]
Hello, I think there might be a bug for the transform function in MoleculeNet dataset. See below:

```from torch_geometric.datasets import MoleculeNet, Planetoid
from torch_geometric.transforms import AddSelfLoops
dataset2 = Planetoid(root='data/Planetoid', name='Cora',  transform = AddSelfLoops())
print(dataset2[0])
dataset1 = MoleculeNet(root='/tmp/ENZYMES', name='sider', transform = AddSelfLoops())
print(dataset1[0])
```

output:

> Data(edge_index=[2, 13264], test_mask=[2708], train_mask=[2708], val_mask=[2708], x=[2708, 1433], y=[2708])
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-3-d81c0273f5d6> in <module>
>       4 print(dataset2[0])
>       5 dataset1 = MoleculeNet(root='/tmp/ENZYMES', name='sider', transform = AddSelfLoops())
> ----> 6 print(dataset1[0])
>       7 
>       8 
> 
> D:\Anaconda3\envs\conv_qsar\lib\site-packages\torch_geometric\data\dataset.py in __getitem__(self, idx)
>     186         if isinstance(idx, int):
>     187             data = self.get(self.indices()[idx])
> --> 188             data = data if self.transform is None else self.transform(data)
>     189             return data
>     190         else:
> 
> D:\Anaconda3\envs\conv_qsar\lib\site-packages\torch_geometric\transforms\add_self_loops.py in __call__(self, data)
>       9         N = data.num_nodes
>      10         edge_index = data.edge_index
> ---> 11         assert data.edge_attr is None
>      12 
>      13         edge_index, _ = add_self_loops(edge_index, num_nodes=N)
> 
> AssertionError: 
>

**Comment by rusty1s** [comment]
Yes, `torch_geometric.transforms.AddSelfLoops` does not work in graphs that come with edge features since there is no way for us to infer meaningful self-loop features). A workaround is to treat central node information and neighboring node information differently during message passing, e.g., by utilizing skip-connections.

**Comment by LanceKnight** [comment]
I see. Thank you @rusty1s !
