### ISSUE TITLE
max_num_nodes in the benchmark dense dataset

### ISSUE THREAD

**Issue by kwonoh** [rusty1s/pytorch_geometric#266]
## ❓ Questions & Help

Hi Matthias,

I have a question about [the lines from 40 to 54 in `benchmark/kernel/datasets.py`](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/datasets.py#L45-L48):
```python
if not sparse:
    num_nodes = max_num_nodes = 0
    for data in dataset:
        num_nodes += data.num_nodes
        max_num_nodes = max(data.num_nodes, max_num_nodes)
    if name == 'REDDIT-BINARY':
        num_nodes = min(int(num_nodes / len(dataset) * 1.5), max_num_nodes)
    else:
        num_nodes = min(int(num_nodes / len(dataset) * 5), max_num_nodes)

    indices = []
    for i, data in enumerate(dataset):
        if data.num_nodes <= num_nodes:
            indices.append(i)
    dataset = dataset[torch.tensor(indices)]
```
It seems the purpose of the code is to filter out large graphs. 
Is this a workaround for GPUs with limited memory capacity? Is there any other reason for this filtering?

Thank you for this great library! 
Oh-Hyun

**Comment by rusty1s** [comment]
Hi, yes this is a reason. There are a really few really large graphs in both datasets and we need to filter them out for applying DiffPool :(

**Comment by kwonoh** [comment]
Thank you for the prompt reply!
