### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by mamengyiyi** [rusty1s/pytorch_geometric#267]
## ❓ Questions & Help

Hi, does PyG have a visualization tool to help us see the states of node classification during the training process?

**Comment by rusty1s** [comment]
Hi, I'm sorry. We do not provide any visualization tools. You need to consult other libraries for that, *e.g.* networkx. We provide convert methods to the networkx format in the `torch_geometric.utils` subpackage.

**Comment by sw-gong** [comment]
Btw @rusty1s , which tools (e.g., meshlab) or library (e.g., menpo3d, MPI-IS/mesh) are generally used to visualize meshes or 3d shape?

**Comment by rusty1s** [comment]
Never used any library for this, so I do not have any recommendations. For visualizing, I usually export models in .off format and render them.

**Comment by sw-gong** [comment]
@rusty1s  Can you elaborate it a bit? Which software do you use to render them? Thanks.

**Comment by rusty1s** [comment]
`.off` is a really simple format which I write manually. Alternatively, you can use `.ply` (with `plyfile` package). I render them with Blender.

**Comment by sw-gong** [comment]
Thank you @rusty1s

**Comment by jlevy44** [comment]
I've been extracting the embeddings from the forward pass and using plotly to plot at each epoch. May not be useful for large n
