### ISSUE TITLE
Restoring node feature concatenation in SAGEConv 

### ISSUE THREAD

**Issue by airknits** [rusty1s/pytorch_geometric#2676]
I noticed that the `concat` functionality was removed from `SAGEConv` in this refactor here: https://github.com/rusty1s/pytorch_geometric/commit/16c6e0a18c6684b8faface5bc24344f0aafdcdea

Any plans to restore it? It's likely not a priority, but I can put up a PR when I have the time.

**Comment by rusty1s** [comment]
`concat=True` is now always enabled for `SAGEConv`. Do you need to use `SAGEConv` with `concat=False`?

**Comment by airknits** [comment]
I traced through the code manually, and it does look like the concatenation is there indeed. Sorry for the confusion and thanks for the cool library!
