### ISSUE TITLE
Is there a way to modify Data object key value on the fly ?

### ISSUE THREAD

**Issue by thegodone** [rusty1s/pytorch_geometric#2682]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for proposing new features.

## 🚀 Feature

Modify "Data" object key value on the fly

## Motivation

Testing features in graph need to be able to modify on the fly the features values for a given "Data" object

## Additional context

using loop did not work.

initial value: torch.Size([18, 26])
modify value: torch.Size([18, 42])
store value: torch.Size([18, 26])

like this in the loop : dataset[i].__setitem__('x',d.x)

**Comment by rusty1s** [comment]
The `dataset` will create new `Data` objects, and does not maintain any state. If you want to do that, you can create a `data_list` of modifiable `Data` objects, which can be passed to a `DataLoader` as well:
```python
data_list = [data for data in dataset]

for data in data_list:
    # Modify

loader = DataLoader(data_list)
```

**Comment by thegodone** [comment]
thanks it works
