### ISSUE TITLE
PointCNN dilated KNN might select less than `K` neighbours 

### ISSUE THREAD

**Issue by mayur-ag** [rusty1s/pytorch_geometric#2684]
## 🐛 Bug

In the current X-Conv implementation, I can see the following:

https://github.com/rusty1s/pytorch_geometric/blob/e8e004439e3204a7b888a21e508c45d166c5817c/torch_geometric/nn/conv/x_conv.py#L130-L137

As, `torch.randint` would sample with replacement, there's a chance that the number of actual neighbours can be less than `K`. I am thinking we can fix this using something like:

```
indices = torch.randperm(K * dil)[:K]
```

**Comment by rusty1s** [comment]
Yes, I think it makes sense to fix this, e.g., the official implementation just takes each `D`-th entry. Are you interested in fixing this?

**Comment by mayur-ag** [comment]
Yup. PR on the way.
