### ISSUE TITLE
KNN selects fewer number of neighbours than expected

### ISSUE THREAD

**Issue by mayur-ag** [rusty1s/pytorch_geometric#2685]
## 🐛 Bug

I recently ran into this issue while working with PointCNN where I'm trying to sample `K * dilation` number of points from a point cloud but end up with fewer points. Following is a way to reproduce

- Download the arrays ZIP: [arrays.zip](https://github.com/rusty1s/pytorch_geometric/files/6591615/arrays.zip)
- Run the following script:

```
import numpy as np
import torch
from torch_geometric.nn import knn


def read(file: str):
    with open(file, "rb") as f:
        return torch.from_numpy(np.load(f)).cuda()

X = read("X.npy")
y = read("y.npy")
bx = read("batch_x.npy")
by = read("batch_y.npy")
k = 32
edge = knn(X, y, k, bx, by)
print("Selecting", k, "nearest neighbors in", X.shape[0], "for every point in", y.shape[0])
print("Edge matrix:", edge.shape, "Expected size:[2,", y.shape[0] * k, "]")
```

Output is: 

```
Selecting 32 nearest neighbors in 768 for every point in 384
Edge matrix: torch.Size([2, 12272]) Expected size:[2, 12288 ]
```

I'm expecting the matrix to be size `[2, len(y) * k]` = `[2, 12288]` but it has fewer number of points. Am I missing something?

**Comment by rusty1s** [comment]
There is one example with only `31` points, so the `knn` graph constructed in this example can have at most 30 neighbors per node:
```python
bx.bincount()
>>> [50, 31, 510, 177]
```
