### ISSUE TITLE
Any other sampling strategies like GraphSAGE, FastGCN, AdaptiveSampling?

### ISSUE THREAD

**Issue by RyanHuangNLP** [rusty1s/pytorch_geometric#270]
## 🚀 Feature

Node wise and layer wise sampling strategies.

## Motivation

Only efficient sampling strategies can train gcn on large-scale data. Is there any example like [fastgcn](https://github.com/matenure/FastGCN), [Graphsage](https://github.com/williamleif/GraphSAGE), [AS-GCN](https://github.com/huangwb/AS-GCN) in 
pytorch_geometric

**Comment by rusty1s** [comment]
Sadly no. We have an open issue regarding this [here](https://github.com/rusty1s/pytorch_geometric/issues/64). I will try to implement it after ICLR.
