### ISSUE TITLE
GAT different edge size and attention size in each batch

### ISSUE THREAD

**Issue by mertkiray** [rusty1s/pytorch_geometric#2701]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hello, I am fairly new to graph neural networks and  I am training a model using GAT and I have a few questions.

My model input is such that each node correspond to an object coming from the data. 

I am calling the function by         
`result, (edge_index, att_weights) = self.att_matrix(input, edge_index, return_attention_weights=True)
`

The question is my node count and edge_index size differs in each batch such that in the first batch I have:
```
input shape: torch.Size([74, 512])   ----> 74 node
edge_index shape: torch.Size([2, 5476]) ---> 74 x 74 edge such that each node is connected
att_weights shape: torch.Size([5476, 1])  ---> as expected a weight matrix for each edge
```

In the second batch I have:
```
input shape: torch.Size([50, 512])  ----> 50 node
edge_index shape: torch.Size([2, 2500]) ---> 50 x 50 edge such that each node is connected
att_weights shape: torch.Size([2500, 1]) ---> as expected a weight matrix for each edge
```

My question is can pytorch_geometric GAT implementation can handle this and having different edge_index and node size for each batch cause a problem for the model?

Should I try to pad the graph in order to have same amount of attention_weights? 

If this is expected and not problematic how should pytorch_geometric handle different size of nodes and edge_index? Please guide me any help is greatly appreciated :)

Edit: I also asked in discussion but I do not know if it is used frequently so I wanted to ask here too.

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/rusty1s/pytorch_geometric/discussions/2700.
