### ISSUE TITLE
SparseTensor error occurs when adding value argument to data

### ISSUE THREAD

**Issue by MaxH1996** [rusty1s/pytorch_geometric#2706]
I am having slight difficulties with the `SparseTensor` functionality. When I go through the example given in the documentation on how to create  a` SparseTensor`, and I add  `value` to the tensor as shown below:
```
adj = SparseTensor(row=edge_index[0], col=edge_index[1], value=...,
                   sparse_sizes=(num_nodes, num_nodes))
```
then `sparse_sizes` changes to shape `(num_nodes, num_nodes , *)`, where `*` depends on the dimension of `value`. I am not entirely sure why that happens. Moreover, when I now try to run some code, such as the example given in the documentation which I added below, with a custom `adj` containing some `value` I cannot run the following example:

```
from torch_sparse import matmul

class GINConv(MessagePassing):
    def __init__(self):
        super(GINConv, self).__init__(aggr="add")

    def forward(self, x, edge_index):
        out = self.propagate(edge_index, x=x)
        return MLP((1 + eps) x + out)

    def message(self, x_j):
        return x_j

    def message_and_aggregate(self, adj_t, x):
        return matmul(adj_t, x, reduce=self.aggr)
```
It returns an error at `return matmul(adj_t, x, reduce=self.aggr)`:

`
RuntimeError:optional_valueA.value().dim() == 1 INTERNAL ASSERT FAILED at "/home/travis/build/rusty1s/pytorch_sparse/csrc/cpu/spspmm_cpu.cpp":24, please report a bug to PyTorch. Input mismatch`

Maybe to make things a little more concrete my `adj` looks something like this:
```
SparseTensor(row=tensor([  0,   0,   0,  ..., 999, 999, 999]),
             col=tensor([  1,   2,   3,  ..., 996, 997, 998]),
             val=tensor([[ 2.1610, -0.2971, -2.1614],
                           [ 2.1926,  0.4863, -0.0328],
                           [ 1.0593, -1.7626, -0.9240],
                           ...,
                           [ 1.7105,  1.3595, -1.1967],
                           [-0.3877,  2.0816, -2.6105],
                           [ 1.3563,  1.0542, -3.2807]]),
             size=(1000, 1000, 3), nnz=8912, density=0.89%)
```
I am sure there is an easy workaround, but I am just not familiar enough with the workings of PyTorch Geometric. Any hints or comments would be appreciated.

**Comment by rusty1s** [comment]
Thanks for your interest. I agree that the error message is not very intuitive, will try to fix this :)

In cases you pass multi-dimensional edge features to a `SparseTensor`, the resulting tensor will have two sparse dimensions and one dense dimension, resulting in an overall shape of `[1000, 1000, 3]` in your case (just like you would get a 3-dimensional tensor in regular PyTorch). However, `matmul` is only supported for one-dimensional edge features/vectors. As such, if you want to perform sparse-matrix multiplication, you can perform the `matmul` for each individual feature. For example:
```python
 def message_and_aggregate(self, adj_t, x):
    out = 0
    _, _, edge_attr = adj_t.coo()
    for i in range(
        adj_t = adj_t.set_value(edge_attr[:, i], layout='coo')
        out += matmul(adj_t.set_value(adj_t, x, reduce=self.aggr)
    return out
```

**Comment by MaxH1996** [comment]
Thank you very much for you quick response, this helps a lot. Just a quick follow-up, would the `matmul` correspond to the aggregation step? So to clarify my question: if I would use my `SparseTensor` (for simplicity without the `values` argument) and I pass `adj` and  `x` (of shape `[num_nodes, feature_dim]`) to `propagate`, i.e. `message_and_aggregate` , the vector that returns for me, if I use the `x_j` functionality, is not a vector of `[num_nodes, feature_dim]`  but `[num_edges, feature_dim]`. This is different than in the normal non-sparse scheme, where I get `[num_nodes, feature_dim]` after the update step. 

So again in code:

```
from torch_sparse import matmul

class GINConv(MessagePassing):
    def __init__(self):
        super(GINConv, self).__init__(aggr="add")

    def forward(self, x, edge_index):
        out = self.propagate(edge_index, x=x)
        return MLP((1 + eps) x + out)

    def message(self, x_j):
        return x_j

    def message_and_aggregate(self, adj_t, x_j):
        return x_j

```
and I would expect the output to have dimension `[num_nodes, feature_dim]` for both sparse and non-sparse, but as mentioned I get `[num_edges, feature_dim]` in the sparse case. However, if I add the `matmul` term then I get the expected dimensions. I hope it is clear what I am asking. Let me know if a I can clarify anything.

**Comment by rusty1s** [comment]
`message_and_aggregate` needs to both define the message and aggregation step, returning a tensor of shape `[num_nodes, ...]`. This is useful, as in some cases we can directly aggregate information without materializing edge representations. For `message`, the aggregation step is actually done internally (by passing `aggr='add'` to the `__init__`. For `message_and_aggregate`, you need to take care of implementing aggregation as well. As such, the correct way to implement it
```python
class GINConv(MessagePassing):
    def __init__(self):
        super(GINConv, self).__init__(aggr="add")

    def forward(self, x, edge_index):
        out = self.propagate(edge_index, x=x)
        return MLP((1 + eps) x + out)

    def message(self, x_j):
        return x_j

    def message_and_aggregate(self, adj_t, x):
        return adj_t @ x
```

**Comment by MaxH1996** [comment]
Awesome, thank you very much!
