### ISSUE TITLE
Decouple SchNet imports

### ISSUE THREAD

**Issue by mshuaibii** [rusty1s/pytorch_geometric#2708]
## 🐛 Bug

To use SchNet, ASE is required while SchnetPack (`spk`) is optional. `spk` is only required when loading a pretrained model. 
https://github.com/rusty1s/pytorch_geometric/blob/718b59708bae84561345e85766289e091f1768c9/torch_geometric/nn/models/schnet.py#L16-L21

However, the way the imports are set up is that if you have ASE but not `spk` both are set to None and you hit the following error:
https://github.com/rusty1s/pytorch_geometric/blob/718b59708bae84561345e85766289e091f1768c9/torch_geometric/nn/models/schnet.py#L93-L94

## To Reproduce

Run any SchNet model with ASE available and not SchnetPack in your conda environment.

## Expected behavior

Not hitting the import error when ASE is installed but not SchnetPack.

## Environment

* OS: Linux
* Python version: 3.8
* PyTorch version: 1.8
* Any other relevant information: Conda environment must contain ASE but not SchnetPack to reproduce.

## Additional context
This was fine in an earlier version of torch_geometric before ASE was made optional (spk was optional at that time).

Proposed fix: separate try/except blocks for the 2 dependencies.

**Comment by rusty1s** [comment]
Good catch! I fixed it in master.
