### ISSUE TITLE
Pytorch Geometric build error in Github Actions

### ISSUE THREAD

**Issue by VIGNESHinZONE** [rusty1s/pytorch_geometric#2711]
Im writing this part of Library [Deepchem](https://github.com/deepchem/deepchem) which has dependencies on PyG for number of graph-based models on molecules.
Here is `requirement.yml` file initializing Pytorch Geometric - https://github.com/deepchem/deepchem/blob/master/env.cpu.yml
Our CI/CD pipeline is failing because of PyG Torch dependency and it would really help if you could help us. There were two instances - 

1) We tried upgrading to Pytorch 1.8.1 as part of [PR](https://github.com/deepchem/deepchem/pull/2518)

Here is the CI failure log - https://github.com/deepchem/deepchem/pull/2518/checks?check_run_id=2633008423
```
  Collecting torch-cluster
    Downloading torch_cluster-1.5.9.tar.gz (38 kB)
  
  failed
  Warning: Pip subprocess error:
      ERROR: Command errored out with exit status 1:
       command: /usr/share/miniconda3/envs/deepchem/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_6bw23xo/torch-cluster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_6bw23xo/torch-cluster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hobm9ljh
           cwd: /tmp/pip-install-_6bw23xo/torch-cluster/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-_6bw23xo/torch-cluster/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

2) We tried installing JAX as part of [PR](https://github.com/deepchem/deepchem/pull/2541)
Here is the CI failure log - https://github.com/deepchem/deepchem/pull/2541/checks?check_run_id=2770978151#step:11:907
```
      ERROR: Command errored out with exit status 1:
       command: /usr/share/miniconda3/envs/deepchem/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a1ap_hr0/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a1ap_hr0/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tun2odv5
           cwd: /tmp/pip-install-a1ap_hr0/torch-scatter/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-a1ap_hr0/torch-scatter/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Thanks in advance,

**Comment by VIGNESHinZONE** [comment]
Even in the `env.cpu.yml` file https://github.com/deepchem/deepchem/blob/master/env.cpu.yml, `torch==1.6.0+cpu` is being installed

**Comment by rusty1s** [comment]
Thanks for reaching out. The errors can be explained by the fact that the PyG dependencies are not installed from wheels, but are instead compiled from source. Compiling from source requires that PyTorch is already installed on the system (and therefore `torch` and `torch-scatter` can not co-exist in the same `requirements.txt` file).

However, this is not a problem when installing from wheels. The correct link to install from wheels is
```
https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
```
even for PyTorch 1.8.1 (not `https://pytorch-geometric.com/whl/torch-1.8.1+cpu.html`) since wheels for PyTorch 1.8.0 work as well for PyTorch 1.8.1.

For installing the dependencies for older PyTorch versions such as 1.6.0, it's always best to define the correct version number. Otherwise, the dependencies will be installed from source as well (as a never version exists for which we do not provide wheels anymore). You can find a list of supported versions for PyTorch 1.6.0 [here](https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html).

**Comment by VIGNESHinZONE** [comment]
@rusty1s 
Thank you very much for the quick reply, it was very helpful

I have implemented the changes, we initiated the PR for upgrading to pytorch - 1.8.1 
The install dependencies checks have been successfully passed, and if you get time could you also verify the changes in this PR
https://github.com/deepchem/deepchem/pull/2541/files to see if I have followed the best practice.

**Comment by rusty1s** [comment]
Awesome, I added some comments to the PR :)

**Comment by VIGNESHinZONE** [comment]
Thanks, @rusty1s 

We are facing few other build errors in CI due to pytorch geometric - https://github.com/deepchem/deepchem/pull/2538/checks?check_run_id=2780500329#step:11:869
```
    ERROR: Command errored out with exit status 1:
     command: /usr/share/miniconda3/envs/deepchem/bin/python /usr/share/miniconda3/envs/deepchem/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-1khr12rd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://download.pytorch.org/whl/torch_stable.html --find-links https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html -- 'numpy>=1.20.1' 'setuptools>=43.0.0'
         cwd: None
    Complete output (3 lines):
    Looking in links: https://download.pytorch.org/whl/torch_stable.html, https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
    ERROR: Could not find a version that satisfies the requirement numpy>=1.20.1 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
    ERROR: No matching distribution found for numpy>=1.20.1
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/share/miniconda3/envs/deepchem/bin/python /usr/share/miniconda3/envs/deepchem/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-1khr12rd/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://download.pytorch.org/whl/torch_stable.html --find-links https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html -- 'numpy>=1.20.1' 'setuptools>=43.0.0' Check the logs for full command output.

```

**Comment by rusty1s** [comment]
This does not look related to PyG, why do you think so?
