### ISSUE TITLE
Installation error in colab examples

### ISSUE THREAD

**Issue by IaroslavElistratov** [rusty1s/pytorch_geometric#2712]
## 📚 Installation

Hi, installation appears to be failing in the provided [colab notebooks](https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html).

```
ERROR: Could not find a version that satisfies the requirement torch-geometric (from versions: none)
ERROR: No matching distribution found for torch-geometric
```

**Comment by QuanticDisaster** [comment]
There are multiple problems on various sites currently, probably due to a problem with servers host such as AWS. Your issue is probably unrelated to torch geometric and comes from pip servers being down
