### ISSUE TITLE
libprotobuf error

### ISSUE THREAD

**Issue by vthost** [rusty1s/pytorch_geometric#2716]
## 📚 Installation

Hi,
Running code that worked before on a new cluster, I come across the below error. Do you maybe have any idea what to do about that?

```
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.0).  Co$
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.0).  Contact the program author for an update. 
```

## Environment

* OS: CentOS Linux 8 (Core)
* Python version: 3.9.4
* PyTorch version: 1.7.1  
* CUDA/cuDNN version: CUDA Version 11.0.228
* GCC version: gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information: -

## Checklist 

- [x ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Can you give some more information on what exactly produces this error?

**Comment by vthost** [comment]
I did not really get anymore information.
For now, I removed protobuf from my environment, which is not ideal, but solved the error.
