### ISSUE TITLE
Implementation that does well on growing graph?

### ISSUE THREAD

**Issue by richardrl** [rusty1s/pytorch_geometric#272]
Are there any implementations that perform well in the dynamic setting where the number of nodes is increasing during training?

For example, the standard Transformer style graph seems to suffer if you train incrementally with increasing nodes. This makes sense since going from 1 node to 2 nodes means node embeddings lose semantic meaning (pooling .5*node1 and .5*node2 to create the embedding for node 2 means the weights become useless).

**Comment by rusty1s** [comment]
We provide an implementation of RENet on the dynamic datasets ICEWS and GDELT. We plan to integrate more dynamic methods in the future.

**Comment by richardrl** [comment]
After looking at the RENet paper, it's not clear to me that they developed a module specifically designed to support unseen number of nodes better than average/max pooling. Can you point me to the operator that may help there?

Incorporating temporal information is a bit different than having something that supports additional unseen nodes inductively.

Are there any other dynamic methods/modules you'd recommend?

**Comment by rusty1s** [comment]
I see what you mean. You are right. RENet is not capable of this. You should check out [Know-Evolve](https://arxiv.org/abs/1705.05742) and [DyRep](https://openreview.net/forum?id=HyePrhR5KX).

**Comment by rusty1s** [comment]
Related https://github.com/rusty1s/pytorch_geometric/issues/153
