### ISSUE TITLE
build wheels for patched Torch releases

### ISSUE THREAD

**Issue by Borda** [rusty1s/pytorch_geometric#2735]
## 🚀 Feature

Please consider publishing builds also for patched PyTorch releases on https://pytorch-geometric.com/whl/
- 1.7.1
- 1.8.1

see PT releases: https://pypi.org/project/torch/#history 

## Motivation

it is great to be able to use build wheels to speed up installation, but these limitations to initial feature releases limit uses fixed Torch versions

**Comment by rusty1s** [comment]
You can use the PyTorch 1.*.0 wheels for the patch releases as well, see [here](https://github.com/rusty1s/pytorch_geometric#pytorch-180181).
