### ISSUE TITLE
A method of finding all connected components in a graph？

### ISSUE THREAD

**Issue by A-student-without-emotion** [rusty1s/pytorch_geometric#2750]
hi,Thank you for your work！
Now I have a problem that I need to find all the connected components in an undirected graph.
if the shape of a graph.x is [160,4], and the edge_index is[ [0,1,2......],[2,3,0......] ]
I want to find all connected components in this graph
like this graph1.x = [60,4] , graph1.edge_index = [ [0,1,3...], [3,4,2.....]]; graph2.x = [100,4] , graph2.edge_index = [ [2,1,3...], [3,4,5.....]]
Could you tell me a way to achieve it?

**Comment by rusty1s** [comment]
I suggest you convert your data to `network` and perform the connected component search there. Then, you can simple split your `data` into connected components afterwards:
```python
G = to_networkx(...)
# Find connected components and save them in a PyTorch vector of shape [num_nodes], e.g.:
# cluster = [0, 0, 0, 0, 1, 1, 1, 1]

# Perform filtering:
data_list = []
for i in range(connected_components):
    subset = torch.arange(data.num_nodes)[cluster == i]
    sub_data = Data()
    sub_data.x = data.x[subset]
    sub_data.edge_index = torch_geometric.utils.subgraph(subset, data.edge_index, relabel_nodes=True)[0]
```

**Comment by A-student-without-emotion** [comment]
> I suggest you convert your data to `network` and perform the connected component search there. Then, you can simple split your `data` into connected components afterwards:
> 
> ```python
> G = to_networkx(...)
> # Find connected components and save them in a PyTorch vector of shape [num_nodes], e.g.:
> # cluster = [0, 0, 0, 0, 1, 1, 1, 1]
> 
> # Perform filtering:
> data_list = []
> for i in range(connected_components):
>     subset = torch.arange(data.num_nodes)[cluster == i]
>     sub_data = Data()
>     sub_data.x = data.x[subset]
>     sub_data.edge_index = torch_geometric.utils.subgraph(subset, data.edge_index, relabel_nodes=True)[0]
>     data_list.append(sub_data)
> ```

Thank you very much!!!!!

**Comment by A-student-without-emotion** [comment]
> I suggest you convert your data to `network` and perform the connected component search there. Then, you can simple split your `data` into connected components afterwards:
> 
> ```python
> G = to_networkx(...)
> # Find connected components and save them in a PyTorch vector of shape [num_nodes], e.g.:
> # cluster = [0, 0, 0, 0, 1, 1, 1, 1]
> 
> # Perform filtering:
> data_list = []
> for i in range(connected_components):
>     subset = torch.arange(data.num_nodes)[cluster == i]
>     sub_data = Data()
>     sub_data.x = data.x[subset]
>     sub_data.edge_index = torch_geometric.utils.subgraph(subset, data.edge_index, relabel_nodes=True)[0]
>     data_list.append(sub_data)
> ```

I'm sorry to disturb you again
I want to train a graph classification model, datasets are different from traditional graph classification datasets, because in this datasets, each graph contains some connected components, and i want to
1, Identify all connected components in a graph(Completed)
2, each connected component is pooled hierarchically
3,  aggregate results of all  pooling connected components
I try to use a method to implement this model, but after identifying the connected components of each graph, there is no way to batch training (multiple connected components represent a graph), resulting in low efficiency.
I would appreciate it if you could give me some advice

**Comment by rusty1s** [comment]
Hi,

I see, I thought you have a single giant graph which you want to split into its connected components. If you have a set of graphs, its best to not split `data` into separate `data` objects, but just add the `cluster` index to it (`data.cluster = cluster`). In order to let `cluster` be correctly incremented in a mini-batch, you want to override the `__inc__` method of `data` as well:
```python
class MyData(Data):
    def __inc__(self, key, value):
        if key == 'cluster':
            return int(cluster.max()) + 1
         return super().__inc__(key, value)
```
Then you can simply pool your connected components together via `scatter` calls:
```python
x_pooled = torch_scatter.scatter(data.x, data.cluster, dim=0, reduce='add')
```
and aggregate all results of all pooled connected components afterwards:
```python
batch_pooled = batch.new_empty(x_pooled.size(0).scatter_(0, cluster, batch)
x_global = torch_scatter.scatter(x_pooled, batch, dim=0, reduce='add')
```

**Comment by A-student-without-emotion** [comment]
> Hi,
> 
> I see, I thought you have a single giant graph which you want to split into its connected components. If you have a set of graphs, its best to not split `data` into separate `data` objects, but just add the `cluster` index to it (`data.cluster = cluster`). In order to let `cluster` be correctly incremented in a mini-batch, you want to override the `__inc__` method of `data` as well:
> 
> ```python
> class MyData(Data):
>     def __inc__(self, key, value):
>         if key == 'cluster':
>             return int(cluster.max()) + 1
>          return super().__inc__(key, value)
> ```
> 
> Then you can simply pool your connected components together via `scatter` calls:
> 
> ```python
> x_pooled = torch_scatter.scatter(data.x, data.cluster, dim=0, reduce='add')
> ```
> 
> and aggregate all results of all pooled connected components afterwards:
> 
> ```python
> batch_pooled = batch.new_empty(x_pooled.size(0).scatter_(0, cluster, batch)
> x_global = torch_scatter.scatter(x_pooled, batch, dim=0, reduce='add')
> ```

thank you very much!!!    I will try it right now, have a nice day!

**Comment by February24-Lee** [comment]
@rusty1s 
Hi, I have a simple and straightforward question.
Is there any special reason why this feature is not implemented in the Pyg library?

In more detail,
I am preparing the PR about some explanation method, and requested to minimize the use of nx as much as possible. So, I'm changing all nx functions to pyg. In the process, I expected that this function would be very common, but it seems not to exist. (If there's something I'm missing, please let me know) 

Anyway, is there a reason to recommend nx conversion without creating this function? If not, I will do the related work and PR.

**Comment by rusty1s** [comment]
We can include it but I would like to avoid adding too many graph algorithms to PyG to not broaden its scope too much. Please feel free to submit the PR if you feel you have an elegant implementation of it in PyTorch.

**Comment by February24-Lee** [comment]
> We can include it but I would like to avoid adding too many graph algorithms to PyG to not broaden its scope too much. Please feel free to submit the PR if you feel you have an elegant implementation of it in PyTorch.

got it. thank you 🙏
