### ISSUE TITLE
Issue with Node Classification Colab Example

### ISSUE THREAD

**Issue by kingabzpro** [rusty1s/pytorch_geometric#2756]
## 🐛 Bug

I am running colab notebook of one of your examples `Node Classification.ipynb`

## To Reproduce

1. `!pip install -q torch-geometric==1.7.1`
2. `from torch_geometric.datasets import Planetoid`

Code 
```python
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
```

Output
```python
OSError                                   Traceback (most recent call last)
<ipython-input-4-041880f67b42> in <module>()
----> 1 from torch_geometric.datasets import Planetoid
      2 from torch_geometric.transforms import NormalizeFeatures
      3 
      4 dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
      5 

5 frames
/usr/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

## Environment

* OS:
* Python version: 3.7
* PyTorch version: colab defaults
* CUDA/cuDNN version: google olabs
* GCC version: google colab
* Any other relevant information:

## Additional context
It was working before but it stopped working today.

**Comment by ainnoot** [comment]
Some Github issues link the `... undefined symbol ...` stuff to multiple installation of PyTorch-related libraries, version conflicts or something like it.

As of today Colab ships (at least on GPU runtimes, I didn't check other runtimes) `torch-1.9.0`, you can check with `print(torch.__version__)`, but the topmost cell in the notebook installs `torch-scatter`, `torch-sparse` for `torch-1.8.0`.

Uninstalling `torch` completely and re-installing the 1.8.0 version fixes it for me, and I hope it fixes it for you too:

```
####
!pip uninstall torch
!pip install -q torch==1.8.0
####

!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install -q torch-geometric
```

You might need to perform a factory reset before doing all of this and/or to restart the runtime before importing `torch_geometric` if you previously imported `torch` before uninstalling and reinstalling it.

Have a nice day!

**Comment by rusty1s** [comment]
I updated the installation commands for the Google Colab, see *e.g.* [here](https://colab.research.google.com/drive/14OvFnAXggxB8vM4e8vSURUp1TaKnovzX?usp=sharing). Instead of installing Pytorch 1.8.0, you can also directly make use of the new wheels for PyTorch 1.9.0:
```python
!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
!pip install -q torch-geometric
```

**Comment by kingabzpro** [comment]
> I updated the installation commands for the Google Colab, see _e.g._ [here](https://colab.research.google.com/drive/14OvFnAXggxB8vM4e8vSURUp1TaKnovzX?usp=sharing). Instead of installing Pytorch 1.8.0, you can also directly make use of the new wheels for PyTorch 1.9.0:
> 
> ```python
> !pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
> !pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
> !pip install -q torch-geometric
> ```

yes this works perfectly. Thank you
