### ISSUE TITLE
DeepGCNLayer Bug with no norm defined

### ISSUE THREAD

**Issue by lukasfolle** [rusty1s/pytorch_geometric#2761]
## 🐛 Bug

The `DeepGCNLayer` throws an error if no norm function is defined due to https://github.com/rusty1s/pytorch_geometric/blob/8f9de2ebc936dd97bae806c6b1d57bc7da5153bb/torch_geometric/nn/models/deepgcn.py#L74
and
https://github.com/rusty1s/pytorch_geometric/blob/8f9de2ebc936dd97bae806c6b1d57bc7da5153bb/torch_geometric/nn/models/deepgcn.py#L76
where h is referenced when it might not be defined yet due to a missing norm call.
## To Reproduce

1. Use plain `DeepGCNLayer` without setting any `__init__` parameters.

## Fix
Either replace `norm=None` in `__init__` with `norm=torch.nn.Identity` or create else statement if `norm is None` to define `h=x`.

I would like to fix this in form of a pull request if this makes sense.

**Comment by rusty1s** [comment]
Great catch. Fixed it already :)

**Comment by lukasfolle** [comment]
Appreciated 👍
