### ISSUE TITLE
Possible memory leak in CPU version of farthest point sampling

### ISSUE THREAD

**Issue by sukjulian** [rusty1s/pytorch_geometric#2769]
## 🐛 Bug

Calling ```torch.geometric.nn.fps(pos.to(torch.device('cpu')), batch, ratio)``` repeatedly in a data loader occupies large amounts of RAM until Ubuntu kills the job. This issue only exists for a certain dataset and when using farthest point sampling (the same code with random sampling had no issue). Everything works fine when using the CUDA version of farthest point sampling: ```torch.geometric.nn.fps(pos.to(torch.device('cuda:0')), batch, ratio)```.

## To Reproduce

1. Wrap ```torch.geometric.nn.fps(pos.to(torch.device('cpu')), batch, ratio)``` in a data transform.
2. Create a ```torch_geometric.nn.data.InMemoryDataset``` or ```torch_geometric.nn.data.Dataset```.
3. Call the dataset with the data transform.

## Expected behavior

The function ```torch.geometric.nn.fps(pos.to(torch.device('cpu')), batch, ratio)``` should free up the used RAM.

## Environment

* OS: Ubuntu 20.04.2
* Python version: 3.8.5
* PyTorch version: 1.8.1
* CUDA/cuDNN version: 11.2
* GCC version: 9.3.0
* Any other relevant information: issue only exists on CPU

## Additional context

The dataset consists of VTP files that are read using ```vtk.vtkXMLPolyDataReader```.

**Comment by rusty1s** [comment]
Do you have some guidance to reproduce? For example,
```
import torch
from torch_cluster import fps

pos = torch.randn(10000, 3)
batch = torch.arange(10).view(-1, 1).repeat(1, 1000).view(-1)
print(batch)
for i in range(100000):
    fps(pos, batch, ratio=0.5)
    print(i)
```
does not increase memory for me.

**Comment by sukjulian** [comment]
Thanks for the quick reply. I will write a minimal reproducing example and send it to you.

**Comment by sukjulian** [comment]
I have a dataset of 3D geometries like this:
<img src="https://user-images.githubusercontent.com/86407254/123316896-af867000-d52d-11eb-868b-cfd2b5915369.png" alt="drawing" width="300"/>
This [.pt file](https://github.com/rusty1s/pytorch_geometric/files/6711537/vertices.pt.zip) (zipped due to GitHub) contains the node coordinates of the geometry.
To reproduce the memory accumulation issue on my machine it is enough to
```python
import torch
import tqdm  # progress bar
from torch_geometric.nn import fps

vertices = torch.load("vertices.pt")
dataset = [vertices]*1000
device = torch.device('cpu')  # switch for the CUDA implementation of fps

# Emulate a Pytorch Geometric dataset
for vertices in tqdm.tqdm(dataset):
    fps(vertices.to(device), None, 0.3)
```
On the other hand the CUDA implementation works like a charm.

**Comment by rusty1s** [comment]
Thanks for the example code. Memory does not increase for me (287MB used for the whole process), so I guess Python has some weird problems releasing memory on your side. Have you tried adding
```
import gc
gc.collect()
```
after each `fps` call?

**Comment by sukjulian** [comment]
You are right. I have tried reproducing it on another Linux system (running the same Ubuntu version) and on a Mac and there was no problem on either of them.

Using ```gc.collect()``` did not help on my main computer but upgrading PyTorch from 1.8.1 to 1.9.0 and reinstalling the corresponding PyTorch Geometric packages solved the issue.

Anyway thanks for the help! Big fan of PyTorch Geometric in general :)

**Comment by rusty1s** [comment]
Cool, awesome :)
