### ISSUE TITLE
Best Method for Training on Point Clouds

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#277]
Is there a standard method for training on high dimensional point clouds with sampled inputs?

So far I'm just doing PointCloud (sampled points due to memory limitations) -> KNN -> EdgeConv -> Global Attention

But am not getting good results.

What can I do to improve my results?

**Comment by rusty1s** [comment]
You could try out other architectures provided in the `benchmark.points` directory, e.g., PointCNN.
