### ISSUE TITLE
Creation of environment from scratch from single `requirements.txt` file not possible if Py_G included

### ISSUE THREAD

**Issue by benjamin9555** [rusty1s/pytorch_geometric#278]
## 📚 Installation

I piped my current running environment into a [requirements.txt](https://github.com/rusty1s/pytorch_geometric/files/3144965/requirements.txt) file and then try to set up a new virtualenv with `pip install -r requirements.txt --no-cache-dir`.
The installation fails with the following error
```
Collecting torch==1.1.0 (from -r requirements.txt (line 77))
  Downloading https://files.pythonhosted.org/packages/c9/e2/40f7f017437139e5dc076ea5ad4207da61250cc078bceef7d6f333c1d05c/torch-1.1.0-cp37-none-macosx_10_7_x86_64.whl (88.9MB)
     |████████████████████████████████| 88.9MB 11.4MB/s
Collecting torch-cluster==1.2.4 (from -r requirements.txt (line 78))
  Downloading https://files.pythonhosted.org/packages/32/c8/9b3af10be647326dd807bb2fe7ced8ae4c3fd74178dba884621749afc4d7/torch_cluster-1.2.4.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/76/0yn0ft0n6f31w321p7j7xf840000gn/T/pip-install-3ibm08fr/torch-cluster/setup.py", line 2, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/76/0yn0ft0n6f31w321p7j7xf840000gn/T/pip-install-3ibm08fr/torch-cluster/
```
I saw that you require to manually install some of your other packages before installing pytorch-geometric, however, it would be nice if you could spell out the dependencies such that it is possible to install the entire environment from a single requirements file.

## Environment

* OS: macOS 10.13.6
* Python version: 3.7.3
* PyTorch version: 1.1.0
* CUDA/cuDNN version: None, cpu-only
* GCC version: using Clang, Apple LLVM version 10.0.0 (clang-1000.11.45.5)
* How you tried to install PyTorch Geometric and its extensions (pip, source): pip

**Comment by rusty1s** [comment]
Yes, we require `torch` to be installed before installing the needed packages. Due to whatever, `torch` isn‘t yet installed when installing all packages from a single requirements.txt file. Install torch first and then run the command again.

**Comment by benjamin9555** [comment]
Ok got it. Out of curiosity, may I ask why it's necessary to install  `torch`  before installing py_g?

**Comment by rusty1s** [comment]
Because we need to import `torch` in our installation to build the kernels.

**Comment by sumitsk** [comment]
Is there any way we can install torch_geometric along with torch using a single `requirements.txt` file?

**Comment by rusty1s** [comment]
Sadly no :( torch is required to allow installation. What is your use-case?

**Comment by Whadup** [comment]
Usecase: Run in AWS / Azure Serverless Setups. The Environments seem to be built solely based on a single requirements.txt

**Comment by tchaton** [comment]
Hey @rusty1s, you should move the installation to poetry: https://github.com/sdispater/poetry

**Comment by Whadup** [comment]
https://stackoverflow.com/questions/54117786/add-numpy-get-include-argument-to-setuptools-without-preinstalled-numpy maybe there's a solution in here?

**Comment by rusty1s** [comment]
Looks promising, thank you :)
