### ISSUE TITLE
gat_conv multiplication order

### ISSUE THREAD

**Issue by derek-saal** [rusty1s/pytorch_geometric#28]
https://github.com/rusty1s/pytorch_geometric/blob/41c85e58970c81e40fb1c68e4c8d9eb613238507/torch_geometric/nn/conv/gat_conv.py#L68

[Equation 1](https://arxiv.org/pdf/1710.10903.pdf#page=3) shows *e_ij = a(W\*h_i,W\*h_j)*

In code you have the inputs being multiplied as *X\*W*.

**Comment by rusty1s** [comment]
Hi,

I do not see any problems with this. Here,`X` is a [N, F_in] matrix and`W` a [F_in, F_out] matrix (in the GAT paper they are transposed). Note that (X * W)^T = W^T * X^T.

**Comment by derek-saal** [comment]
Yes, you are 100% correct. Thanks for your patience.
