### ISSUE TITLE
How to use node features which is 2 dimension?

### ISSUE THREAD

**Issue by zzzzzzzzzzzx** [rusty1s/pytorch_geometric#2814]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

In the pyg data format, x=[num_nodes, num_node_features], in all the explanation and the code I saw, this 'num_node_features' is a one-dimensional vector, that is, the node feature is one-dimensional data, but my node features is a two-dimensional matrix, how can i implement the node features in the pyg data format?

here is an example:
`x = torch.tensor([[[2,1,1,3,5,6],[2,1,1,3,5,6]],[[5,6,1,3,5,6],[2,1,1,3,5,6]],[[3,7,1,3,5,6],[2,1,1,3,5,6]],[[12,0,1,3,5,6],[2,1,1,3,5,6]]],dtype=torch.float)
y = torch.tensor([0,1,0,1], dtype=torch.float)
edge_index = torch.tensor([[0,1,2,1,0,3,3,2],
                          [1,0,1,2,3,0,2,3]],dtype=torch.long)
mydata = Data(x=x,y=y,edge_index=edge_index)`

The output is `Data(edge_index=[2, 5], x=[4, 2, 6], y=[4])`;

then i use a simple model to train this data:
`class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(mydata.num_node_features, 2)
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        return F.log_softmax(x, dim=1)`

This code report an error, which is "RuntimeError: size mismatch, m1: [8 x 6], m2: [2 x 2] at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMathBlas.cu:290", **Obviously this is because of my node feature. SO how can i use the node features which is 2 dimension? THANKS !**

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/rusty1s/pytorch_geometric/discussions/2813.
