### ISSUE TITLE
GraphsTuple to TORCH_GEOMETRIC.DATASETS

### ISSUE THREAD

**Issue by Mandeep-Rathee** [rusty1s/pytorch_geometric#2815]
hello dear,

I want to use the dataset of type GraphsTuple (https://github.com/deepmind/graph_nets ) in PyTorch-geometric. 
Is there any package in PyTorch-geometric to convert GraphsTuple to TORCH_GEOMETRIC.DATASETS?

thanks in advance!!

**Comment by rusty1s** [comment]
There exists no such function yet. As far as I know, the `GraphsTuple` store follows a similar representation, and you should be able to simply copy all attributes from `GraphsTuple` to a PyTorch Geometric `Data` object.

**Comment by Mandeep-Rathee** [comment]
hey @rusty1s 
I successfully transformed GraphTuple to PyG format. 
Thanks a lot.

**Comment by guolalala** [comment]
@Mandeep-Rathee hi, can you share the transformer code of "GraphTuple to PyG format"? thanks very much!
