### ISSUE TITLE
New version introduced: DataLoader found invalid type: <class 'str'>

### ISSUE THREAD

**Issue by demmerichs** [rusty1s/pytorch_geometric#2817]
## 🐛 Bug

When using the torch_geometric DataLoader it can no longer handle strings in the data, because of the following code change: https://github.com/rusty1s/pytorch_geometric/commit/fc2c9d028e02f1621750e1574532c03d34d7c355#r53073008

## To Reproduce

1. Create a dataset returning strings as elements.
1. Wrap it with the dataloader class.
1. Raises TypeError:
```python
  File "~/.venv/lib/python3.6/site-packages/torch_geometric/data/dataloader.py", line 32, in collate
    raise TypeError('DataLoader found invalid type: {}'.format(type(elem)))
TypeError: DataLoader found invalid type: <class 'str'>
```

## Expected behavior

I don't see any reason why this data type support was dropped, it worked in the past as expected.

**Comment by rusty1s** [comment]
That was indeed a mistake. Thanks for letting me know. I added it back in, see https://github.com/rusty1s/pytorch_geometric/commit/6442a6e287563b39dae9f5fcffc52cd780925f89.
