### ISSUE TITLE
torch_geometric calls torch_cluster knn_graph() using wrong number arguments 

### ISSUE THREAD

**Issue by gabywang5** [rusty1s/pytorch_geometric#2821]
## ❓ Questions & Help

Hi, friends,
I came across the following error when I initialize my customed dataset.

> RuntimeError: knn_graph() Expected a value of type 'Tensor' for argument 'x' but instead found type 'NoneType'.
Position: 0
Value: None
Declaration: knn_graph(Tensor x, int k, Tensor? batch=None, bool loop=False, str flow="source_to_target", bool cosine=False, int num_workers=1) -> (Tensor)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

This is part of my code:
```python
class MyOwnDataset(Dataset):
    def __init__(self, root="./data_1/", transform=None, pre_transform=T.KNNGraph(k=4)):
        super(MyOwnDataset, self).__init__(root, transform, pre_transform)
```

This is the Traceback:
![image](https://user-images.githubusercontent.com/26650907/124566119-5693d180-de75-11eb-9b05-643164e8e4e9.png)

It seems the `torch-geometric` process the `Data` object by calling `torch-cluster`'s `knn_graph` function, however, the `torch_cluster.knn_graph` took 7 arguments but `torch_geometric.nn.knn_graph` only give 6.

I manage the package environment using conda. Here is my package version:

> torch                     1.9.0 
torch-cluster             1.5.9
torch-geometric           1.7.2
torch-scatter             2.0.7
torch-sparse              0.6.10

I installed the packages using Pip and followed the instructions of this guidance: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

I am pretty sure that my` torch-cluster` matches my `torch` version. They are both cpu version.

This problem is going to drive me crazy. So I am very grateful if you guys could give me some idea of where the problem might be. 

Thank you so much.

**Comment by rusty1s** [comment]
The `KNNGraph` will create the graph connectivity based on the `data.pos` argument, which seems to be missing in your case.

**Comment by gabywang5** [comment]
@rusty1s thank you! That is exactly where the problem is.
