### ISSUE TITLE
Incorrect wheel links for torch-1.8.1+cu111

### ISSUE THREAD

**Issue by Sayam753** [rusty1s/pytorch_geometric#2825]
If I go to https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html, all the wheels links are linked to `torch-1.8.0+cu111`.

As an example - 
`torch_cluster-1.5.9-cp37-cp37m-linux_x86_64.whl` is pointing to `https://pytorch-geometric.com/whl/torch-1.8.0+cu111/torch_cluster-1.5.9-cp37-cp37m-linux_x86_64.whl` at `torch-1.8.1+cu111`

Is this expected behaviour of wheel links or am I missing something?
Thanks

**Comment by Sayam753** [comment]
Even all the wheel links at

- [torch-1.7.1](https://pytorch-geometric.com/whl/torch-1.7.1.html)
- [torch-1.7.1+cpu](https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html)
- [torch-1.7.1+cu101](https://pytorch-geometric.com/whl/torch-1.7.1+cu101.html)
- [torch-1.7.1+cu102](https://pytorch-geometric.com/whl/torch-1.7.1+cu102.html)
- [torch-1.7.1+cu110](https://pytorch-geometric.com/whl/torch-1.7.1+cu110.html)
- [torch-1.7.1+cu92](https://pytorch-geometric.com/whl/torch-1.7.1+cu92.html)

are all pointed to corresponding `torch-1.7.0`.

**Comment by rusty1s** [comment]
Yes, this is intended. The wheels for PyTorch 1.7.0 work for 1.7.1 as well, and the same holds true for PyTorch 1.8.0.

**Comment by Sayam753** [comment]
Great. Since this is the expected behaviour, I am closing the issue.
Many thanks for the quick reply @rusty1s .
