### ISSUE TITLE
propagate function will output 0 when there is no connection among nodes.

### ISSUE THREAD

**Issue by zcaicaros** [rusty1s/pytorch_geometric#2839]
## To Reproduce

1. Install torch-sparse 0.6.10
1. Install torch-scatter 2.0.7
1. Install torch-geometric 1.7.2

Reproduce Code Sample:

```
from typing import Union
from torch_geometric.typing import OptPairTensor, Adj, Size
import torch
from torch import Tensor
from torch_geometric.nn.conv import MessagePassing


class ForwardPass(MessagePassing):
    def __init__(self, **kwargs):
        kwargs.setdefault('aggr', 'max')
        super(ForwardPass, self).__init__(**kwargs)

    def forward(self,
                x: Union[Tensor, OptPairTensor],
                edge_index: Adj,
                size: Size = None) -> Tensor:
        """"""
        if isinstance(x, Tensor):
            x: OptPairTensor = (x, x)
        # propagate_type: (x: OptPairTensor)
        out = self.propagate(edge_index, x=x, size=size)
        return out

fp = ForwardPass(aggr='max', flow="target_to_source")
out = fp(x=torch.tensor([[1.], [2.], [3.]]), edge_index=torch.tensor([[],[]], dtype=torch.long))
print(out)
```
This will give output:
```
tensor([[0.], [0.], [0.]])
```

## Expected behavior
In the above example, we have a 3-node graph with no `edge_index` indicating there is no connections (edges) among any nodes. The nodes' initial featuer is `torch.tensor([[1.], [2.], [3.]])`. That is, the first node holds feature `1.`, the second node holds feature `2.`, and the third node holds feature `3.`. What I can expect from the `propagate` function is that, since there is no connection amogn all nodes, the output of the `propagate` function should not make any effects on node features. So, the output should stay the same as `torch.tensor([[1.], [2.], [3.]])`, but it gives `tensor([[0.], [0.], [0.]])` instead, i.e., after one round of propagation, all the node features become `0.`

Is this a bug?

## Environment

* OS: WIn10
* Python version: 3.8
* PyTorch version: 1.9.0
* CUDA/cuDNN version: 11.3
* GCC version: N/A
* Any other relevant information:

![image](https://user-images.githubusercontent.com/29399076/125183472-66326200-e249-11eb-8f79-cda3f01a6e94.png)

## Additional context

N/A

**Comment by rusty1s** [comment]
This is expected behavior. `propagate` will return the aggregated result of incoming messages. As there exists no messages, the output will be a zero-filled matrix. If you want to preserve central node features, you either need to
1. Add self-loops to your graph or
2. Apply a simple skip-connection
```python
return self.propagate(edge_index, x=x, size=size) + x
```

**Comment by zcaicaros** [comment]
Well understood. Good job as always!
