### ISSUE TITLE
question on Xconv implementation

### ISSUE THREAD

**Issue by amiltonwong** [rusty1s/pytorch_geometric#286]
Hi, @rusty1s,

According to line[132](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L132) and line [140](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L140), both the input is pos (node position matrix). Why the second [one](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L140) is reshaped as [N, K * D], which is different to the [first one](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L132)?

**Comment by rusty1s** [comment]
This is intended behaviour. The one applies a transformation on each point separately, the other on each neighborhood.

**Comment by amiltonwong** [comment]
Thanks @rusty1s  for your clarification.
