### ISSUE TITLE
Integration with DeepSpeed: `expected scalar type Float but found Half`

### ISSUE THREAD

**Issue by griff4692** [rusty1s/pytorch_geometric#2866]
Hi - I'm trying to integrate geometric with pytorch lightning and the deepspeed plugin.  Yet, when I do my GATConv code which previously worked with half precision is now failing.  Any ideas ?

Here is the full stack trace.

>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/kabupra/graph/models/model_utils.py", line 132, in forward
>     x = self.elu(self.conv1(x, edge_index))
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 124, in forward
>     x_l = x_r = self.lin_l(x).view(-1, H, C)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/linear.py", line 96, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/usr/lib/python3/dist-packages/torch/cuda/amp/autocast_mode.py", line 211, in decorate_fwd
>     return fwd(*args, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/deepspeed/runtime/zero/linear.py", line 60, in forward
>     output = input.matmul(weight.t())
> RuntimeError: expected scalar type Float but found Half

I tried calling "half" on the input tensors to the GATConv but then I get another error:

>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/kabupra/graph/models/model_utils.py", line 133, in forward
>     x = self.elu(self.conv1(x, edge_index))
>   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
>     result = forward_call(*input, **kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 152, in forward
>     out = self.propagate(edge_index, x=(x_l, x_r),
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 237, in propagate
>     out = self.message(**msg_kwargs)
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py", line 180, in message
>     alpha = softmax(alpha, index, ptr, size_i)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_geometric/utils/softmax.py", line 41, in softmax
>     elif index is not None:
>         N = maybe_num_nodes(index, num_nodes)
>         src_max = scatter(src, index, dim, dim_size=N, reduce='max')
>                   ~~~~~~~ <--- HERE
>         src_max = src_max.index_select(dim, index)
>         out = (src - src_max).exp()
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_scatter/scatter.py", line 161, in scatter
>         return scatter_min(src, index, dim, out, dim_size)[0]
>     elif reduce == 'max':
>         return scatter_max(src, index, dim, out, dim_size)[0]
>                ~~~~~~~~~~~ <--- HERE
>     else:
>         raise ValueError
>   File "/home/griffin/sauce/lib/python3.8/site-packages/torch_scatter/scatter.py", line 73, in scatter_max
>         out: Optional[torch.Tensor] = None,
>         dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
>     return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> RuntimeError: "scatter" not implemented for 'Half'

**Comment by rusty1s** [comment]
There exists no `torch.half` support yet in `torch_scatter`, but its on the roadmap. The reason why it may have worked earlier is that the `scatter_max` call got recently re-introduced in the `GATConv` `softmax` call in order to guarantee numerical stability.

**Comment by griff4692** [comment]
Thanks Matthias!  Is there any way then to use deepspeed with pytorch_geometric?

**Comment by rusty1s** [comment]
I think that you can use all the models that do not make use of `scatter_max`. For other models, you need to cast features to float32 before calling `scatter_max`. Nonetheless, I will work on half-precision support soon which should be available in the next month.

**Comment by rusty1s** [comment]
I just pushed `torch.half` support in `torch-scatter` to master. Can you please try and see if that fixes your issues? If everything works as expected, I will create a new release.

**Comment by rusty1s** [comment]
Just released a new `torch-scatter` version with half-precision support.
