### ISSUE TITLE
Graph classification problem

### ISSUE THREAD

**Issue by Archer666** [rusty1s/pytorch_geometric#289]
Excuse me，Do you have some examples of Graphs classification problem,because I want to do a 3D mesh classification task using GCN.

**Comment by xinliweiyuan** [comment]
You can see the attached documents. https://rusty1s.github.io/pytorch_geometric/build/html/index.html

**Comment by rusty1s** [comment]
And all `mnist_*` examples and the `pointnet++` example :)
