### ISSUE TITLE
[Feature Request] Can torch_sparse::matmul support FP16 data type in the future?

### ISSUE THREAD

**Issue by warai-0toko** [rusty1s/pytorch_geometric#2893]
## 🚀 Feature

Currently most of the GraphConv layers in PyG rely on the torch_sparse::matmul to realize message and propagation. However, I found that it does not support FP16 data type.

I re-implement the CUDA kernel of spmm_mean, spmm_sum, spmm_min, and spmm_max in the torch_sparse to support FP16 data type 

Specifically, I changed the code mainly in the following way.

1. I changed https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cuda/spmm_cuda.cu line 135 AT_DISPATCH_ALL_TYPES -> AT_DISPATCH_ALL_TYPES_AND_HALF. 

2. I overwrite the __shfl_sync function by:

```
__device__ __inline__ c10::Half __shfl_sync(const unsigned mask, const c10::Half var,
                                            const unsigned int delta) {
  __half var_ = var;
  return __shfl_sync(mask, var_, delta);
}
```

I tested the GCNConv and SAGEConv, under the mixed precision setting (torch.cuda.amp), it works well in terms of numerical precision. Also, I train a 3-layer 256-wide GraphSaint (sage aggr) model on OGB-Arxiv and OGB-Products. The results are identical to the one reported on the OGB leaderboard.

Mixed precision training can reduce the memory requirement of training GNNs significantly.  I am wondering why torch_sparse::matmul does not support FP16 data type officially? Sorry I am newbee to the GPU programming. Is there any other concerns? 

## Motivation

Reduce the memory requirement of training GNNs

**Comment by rusty1s** [comment]
Yes, of course we can add this in. Half-precision support is indeed only yet implemented for the CPU version of `spmm`. Do you want to create a PR or do you want me to apply the necessary changes?

**Comment by warai-0toko** [comment]
I prefer the second one instead of creating a PR.

It helps a lot.

Zirui

**Comment by rusty1s** [comment]
Ok, great. Will work on it in the upcoming week.

**Comment by rusty1s** [comment]
Added the necessary features to master, see [here](https://github.com/rusty1s/pytorch_sparse/commit/3e87af1cc2218954fd6fd457f96ab4ef6e0f3b15). Thank you!
