### ISSUE TITLE
RuntimeError: full(...) is not implemented for sparse layout in ChebConv

### ISSUE THREAD

**Issue by xinliweiyuan** [rusty1s/pytorch_geometric#290]
## To Reproduce
from torch_geometric.nn import ChebConv, GCNConv
import torch

x = torch.sparse.FloatTensor(indices=torch.LongTensor([[1, 2, 0],
                       [1, 1, 2]]),  values=torch.Tensor([1, 1, 1]), size=(32, 100))

##x is a sparse matrix 32*100, only have 3 nodes.
##edge_index is a sparse matrix only has four edges. 

edge_index = torch.LongTensor([[ 0, 1, 2, 1], [ 1, 0, 1, 2]])

gcn_conv = GCNConv(100, 32)
gcn_conv(x, edge_index).shape
##works fine in gcn_conv

cheb_conv = ChebConv(100, 32, K=1)

##edge_weight = torch.full((num_edges, ), 1, dtype=edge_index.dtype, device=edge_index.device)
cheb_conv(x, edge_index)

we can add 

edge_weight = torch.full((num_edges, ), 1, dtype=edge_index.dtype, device=edge_index.device) in the cheb_conv.py

But it still has some other issues. RuntimeError: value cannot be converted to type int64_t without overflow: inf.

When x and edge_index are sparse.  It is not easy for me to debug it. Can you fix it? Thanks for the help.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Hi, sparse node feature matrix support in the `ChebConv` is something which can not be easily achieved because of the need of sparse sparse matrix multiplications. I suggest converting your sparse node feature matrix to a dense one first (if that fits into memory). It's faster anyway.

**Comment by xinliweiyuan** [comment]
Thanks for the response. It is true.  I found it is hard to have both X and edge_index with sparse features. But it is possible to have node features is dense and edge_index is sparse. I will see if it can be done in TensorFlow, might easier.

**Comment by rusty1s** [comment]
Hi, as far as I know, TensorFlow does not have a sparse sparse matrix multiplication either. You can, however, try out my [sparse package](https://github.com/pytorch-sparse). Please note that `edge_index` is always sparse.
