### ISSUE TITLE
Troubles loading the Zachery dataset from torch_geometric.datasets 

### ISSUE THREAD

**Issue by mv96** [rusty1s/pytorch_geometric#2907]
Sorry, a bit new to Pytorch, for hours have been trying to fix an installation issue for a Graph Neural Network Course

`from torch_geometric.datasets import KarateClub`

**Running the above script causes system to crash leading to the following error**

AttributeError: module 'community' has no attribute 'best_partition'

**Pytorch Installation command used**

pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html

*Also getting the same error while trying to run the official Colab notebooks provided in the installation section*

For more details please see the Colab notebook or follow the tutorial notebook provided under Examples/Colab/Introduction: Hands-on Graph Neural Networks Notebooks/ 

Colab link - https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing

**Comment by rusty1s** [comment]
This seems to be a bug in Colab, which already comes with a `community` dependency. Not sure why it worked before. Nonetheless, I fixed the issue in PyG master, and the [Google Colab code](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing#scrollTo=zF5bw3m9UrMy) should work again just fine.
