### ISSUE TITLE
issues on dense_diff_pool function

### ISSUE THREAD

**Issue by PandaGuang** [rusty1s/pytorch_geometric#291]
I was trying to run  pytorch_geometric/examples/enzymes_diff_pool.py , but I came across an issue, which is below,

x, adj, l1, e1 = dense_diff_pool(x, adj, s, mask)
ValueError: not enough values to unpack (expected 4, got 3)

I read the description of this function on Pytorch Geometric Documentation and it states that the function dense_diff_pool is supposed to return 4 output, but running the code, it only gives 3.

**Comment by rusty1s** [comment]
Ah I see, it looks like you are running an older version of PyG. The current master version should fix this problem.

**Comment by PandaGuang** [comment]
Get it! It works! Thank you very much!

**Comment by PandaGuang** [comment]
When I change the number of epochs from 151 to a larger number, the training loss becomes NAN after 150 epoch, what is the problem?

**Comment by rusty1s** [comment]
I will look into it.

**Comment by rusty1s** [comment]
The issue is fixed in current master. There was a bug in `DenseSAGEConv` where neighborhood normalization was performed even if in case there were no neighbors (which could happen for DiffPool). Thank you.
