### ISSUE TITLE
PointCNN is not working

### ISSUE THREAD

**Issue by tashfin-msu** [rusty1s/pytorch_geometric#2914]
Hi,
Although I added the new lines in the x_conv.py file like you mentioned in "PointCNN example is broken after #2691 #2881".
 I am still getting error.

`File "/......../torch_geometric/nn/conv/x_conv.py", line 139, in forward x = x[col].view(N, K, self.in_channels) RuntimeError: shape '[6144, 12, 48]' is invalid for input of size 589824`

Do you know what might be the issue?
Thanks

**Comment by rusty1s** [comment]
I think this might be the same problem as [here](https://github.com/rusty1s/pytorch_geometric/issues/2904).

**Comment by tashfin-msu** [comment]
Thanks.

**Comment by DeadlyAbyss** [comment]
Hi, I run the code and get the same error report. Have someone already fixed the bug or run succeessfully?

**Comment by DeadlyAbyss** [comment]
Sir, my environment are:
windows10（I‘m not sure whether it's relevant or not)
python=3.8, torch=2.2.0, torch-geometric=2.5.0, cuda11.8
torch-cluster&nbsp; =1.6.3+pt22cu118
torch-scatter&nbsp; =&nbsp;2.1.2+pt22cu118
torch-sparse&nbsp; = 0.6.18+pt22cu118
torch-spline-conv&nbsp;=1.2.2+pt22cu118


I notice that&nbsp;pyg_lib&nbsp;only have linux version, so I thought might OS have influence?
I'm now trying running the project on Ubuntu20.04, I'm not sure wheather it will have some effect.


Acctually, at first I move the PointCNN and xCov code to my own experiment project, and show shape invalid error like that in "https://github.com/pyg-team/pytorch_geometric/issues/2904". But I cant fix it. Than I run it directly in the original project and show the error which occurs now:"couldn't find module _grid_cuda.pyd"


If it is OK, may I have your environment information? Or if there are any other possible reasons and solutions?&nbsp;




Thanks a lot for relying to my confusion. Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月14日(星期四) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyg-team/pytorch_geometric] PointCNN is not working (#2914)





 
I can run the script succesfully:
 Epoch: 001, Test: 0.6828, Duration: 34.98 Epoch: 002, Test: 0.7577, Duration: 33.73 Epoch: 003, Test: 0.8249, Duration: 33.85 Epoch: 004, Test: 0.8106, Duration: 33.88  
Which PyG/PyTorch version are you using?

**Comment by rusty1s** [comment]
Did you have success on Ubuntu? This does not seem to be related to `pyg-lib`.

**Comment by DeadlyAbyss** [comment]
yes，i do. it's now working well. it must be related to pyg-lib.
thanks a lot！



发自我的iPhone


------------------ Original ------------------
From: Matthias Fey ***@***.***&gt;
Date: Mon,Mar 18,2024 10:38 PM
To: pyg-team/pytorch_geometric ***@***.***&gt;
Cc: DeadlyAbyss ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [pyg-team/pytorch_geometric] PointCNN is not working (#2914)





 
Did you have success on Ubuntu? This does not seem to be related to pyg-lib.
