### ISSUE TITLE
Missing non-linearity in HypergraphConv

### ISSUE THREAD

**Issue by yinyee** [rusty1s/pytorch_geometric#2921]
I think there is a non-linear operation missing in HypergraphConv.

https://github.com/rusty1s/pytorch_geometric/blob/85c8b78ecd698b21c26f81a91827747bc5f6411e/torch_geometric/nn/conv/hypergraph_conv.py#L136 contains the only non-linear operation ```F.leaky_relu``` but it is inside a conditional block ```if self.use_attention:``` for which the default is ```False```.

Excerpt from the paper:

![Screenshot 2021-07-29 at 21 16 44](https://user-images.githubusercontent.com/11690366/127559989-6342c67f-3868-472d-8ea8-4505f2cabb2c.png)

I'm not sure if the intention is to adhere strictly to the paper's choice of non-linearity but there should be a default non-linear operation and/or the ability to specify a non-linear operation.

**Comment by rusty1s** [comment]
In PyG, we usually omit the non-linearity from GNN operators (in the same spirit as `Conv2d` or `Linear` in PyTorch). It's the users responsibility to call the appropriate non-linearity after GNN op execution.

**Comment by yinyee** [comment]
Makes sense! Thanks for the quick response
