### ISSUE TITLE
GNNExplainer with ChebConv: assertion failed after adding self loops

### ISSUE THREAD

**Issue by NithyaBhasker** [rusty1s/pytorch_geometric#2922]
Hello, 

I am using GNNExplainer for a model containing ChebConv layers. The following assertion fails after my ChebConv normalization adds self loops -
"assert out.size(self.node_dim) == edge_mask.size(0)"

Is there a workaround for this? 

Thanks in advance.

**Comment by tw200464tw** [comment]
HI,I have got the same problem ,but I find the reason.[https://github.com/rusty1s/pytorch_geometric/issues/2934](url)

**Comment by tw200464tw** [comment]
HI,I have got the same problem ,but I find the reason. Like this [https://github.com/rusty1s/pytorch_geometric/issues/2934#issue-958854516](url)

**Comment by tw200464tw** [comment]
Hi,I have got the same problem ,but I find the reason. You can search 'A bug or a special case about Graph Explainer' in the issues

**Comment by rusty1s** [comment]
This is now fixed in master, see https://github.com/rusty1s/pytorch_geometric/issues/2934.
