### ISSUE TITLE
About the GAT citation benchmark

### ISSUE THREAD

**Issue by h12345jack** [rusty1s/pytorch_geometric#293]
## 🐛 Bug

Hello, in citations/run.sh, When handling PubMed dataset, the code is 

```
python gat.py --dataset=PubMed --lr=0.01 --weight_decay=0.001 --output_head=8
```
However, in [gat.py](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/gat.py), the ```output_head``` are not used. 

So I think you should add it to the ```GATConv``` like
```
class Net(torch.nn.Module):
    def __init__(self, dataset):
        super(Net, self).__init__()
        self.conv1 = GATConv(
            dataset.num_features,
            args.hidden,
            heads=args.heads,
            dropout=args.dropout)
        self.conv2 = GATConv(
            args.hidden * args.heads,
            dataset.num_classes,
            heads=args.output_head,
            concat=False,
            dropout=args.dropout)
```
After doing that, the results is 79% .
By the way, the GAT's Citeseer results can be 72.5 in the paper
But I can only get 70.8. 

Even I changed the [early stop](https://github.com/PetarV-/GAT/issues/14),  I can only get 71.6
Is there something important I missed? Thank you

## Environment

* OS: Linux
* Python version: 3.6.5
* PyTorch version: 1.0.0
* CUDA/cuDNN version: 9.0
* GCC version:  5.5
* Any other relevant information:

**Comment by rusty1s** [comment]
Hi, Thank you. You are indeed right. This is a bug and it is fixed in master. I will adjust the results accordingly. The Citeseer results are indeed lower than reported in the paper, but the architecture should match the one described in the paper and Cora results match the ones reported, so I do not know what causes this.
