### ISSUE TITLE
SchNet maximum neighbor limit 

### ISSUE THREAD

**Issue by nec4** [rusty1s/pytorch_geometric#2933]
## 🐛 Bug

Hello everyone! The tools are great so far. I noticed that there is a small but important corner case for the usage of `radius_graph` from `torch_cluster` for users of `SchNet`. When searching for neighbors, the behavior is governed by both the cutoff distance `r` and `max_num_neighbors` (see docs here: https://github.com/rusty1s/pytorch_cluster#radius-graph). The latter is set to a default maximum of 32 neighbors for each atom/node. If, for example, the user inputs a large cutoff distance intending to return all neighbors, they will still be truncated at a maximum of 32 even if the user expects more. Furthermore, I'm not sure how radius_graph decides to reject extra neighbors. For my usage case, setting `max_num_neighbors` higher seems to make a big difference in the training and inference. Because the SchNet philosophy is to operate on the notion of cutoff distances, not maximum neighbors, would it make sense to add a kwarg somewhere to raise the limit of the max neighbors for this operation should the user need it?

Of course, most users probably will not run into this problem if they stick to small cutoffs because they will never hit the upper neighbor ceiling. However, the effects are pretty severe for those that stray outside of the typical usage. Even if it is undesirable to mess with `max_num_neighbors` in `radius_graph`, the limitation above should at least be made clear in the class docs for `SchNet` because I think most users expect raising the cutoff distance alone will give them more neighbors per bead without arbitrary truncation.

## To Reproduce

I have written a simple script that demonstrates the expected and default behavior. For simplicity, I have only focused on the first step of the `forward` method in `SchNet` where the molecular interaction graph is constructed:

(https://github.com/rusty1s/pytorch_geometric/blob/85c8b78ecd698b21c26f81a91827747bc5f6411e/torch_geometric/nn/models/schnet.py#L226)

```
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch_geometric
from torch_geometric.data import InMemoryDataset, DataLoader, Data

# 1 example, random coordinates/types with molecules of 200 atoms
num_atoms = 200
test_coords = torch.randn(num_atoms,3)
test_types = torch.randint(low=1,high=10,size=(num_atoms,), dtype=torch.long)
test_batch = torch.zeros(size=(num_atoms,), dtype=torch.long)

from torch_cluster import radius_graph

default_edges = []
expected_edges = []
cutoffs = np.linspace(0.1,10,100)
for cutoff in cutoffs:
    pos = test_coords
    # Default SchNet behavior as implemented in PTGeom
    edge_index = radius_graph(pos, r=cutoff, batch=test_batch)
    row, col = edge_index
    edge_weight = (pos[row] - pos[col]).norm(dim=-1)
    default_edges.append(len(edge_weight))
    
    # Expected behavior
    edge_index = radius_graph(pos, r=cutoff, max_num_neighbors=num_atoms, batch=test_batch)
    row, col = edge_index
    edge_weight = (pos[row] - pos[col]).norm(dim=-1)
    expected_edges.append(len(edge_weight))

print(expected_edges[-1])
print(default_edges[-1])
    
plt.plot(cutoffs, default_edges, label="Default Behavior")
plt.plot(cutoffs, expected_edges, label="Expected Behavior")
plt.yscale('log')
plt.xlabel('Cutoff Value')
plt.ylabel('Edges Found')
plt.legend(loc='best')
plt.show()

```

## Expected behavior

As the physical cutoff distance is raised in SchNet, the number of nearby neighbors for each bead should approach N x (N-1), not N x 32. In this case, for 200 atoms, the default behavior approaches 6400 edges while the expected behavior approaches 39800

<img width="417" alt="cutoffs" src="https://user-images.githubusercontent.com/42926839/127906808-a09f6831-5cee-4810-b51f-1c2083c6900f.png">

## Environment

* OS: macOS Mojave 10.14.6 18G87 x86_64
* Python version: Python 3.9.6
* PyTorch version: 1.8.0
* CUDA/cuDNN version: CPU 
* GCC version:  [Clang 11.0.0 (clang-1100.0.33.17)] on darwin
* Any other relevant information: torch_geometric version 1.7.2

## Additional context

I am happy to contribute or continue to experiment with this issue if it is needed.

**Comment by rusty1s** [comment]
Thanks for this detailed issue. Highly appreciated. For now, I added the `max_num_neighbors` attribute as an additional argument to both `SchNet` and `DimeNet` models, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.models.SchNet). Sadly, the `max_num_neighbors` attribute is crucial for now to allow for a fast graph generation on GPU. Closing this issue for now. Feel free to reopen if there exists still some concerns from your point of view.

**Comment by nec4** [comment]
Thanks for taking a look!
