### ISSUE TITLE
Google Colab crashes with graph classification tutorial

### ISSUE THREAD

**Issue by paulamartingonzalez** [rusty1s/pytorch_geometric#2937]
## 🐛 Bug

I am trying to run the[ graph classification tutorial ](https://colab.research.google.com/drive/1I8a0DfQ3fI7Njc62__mVXUlcAleUclnb) with a custom dataset and google Colab crashes when training.

It does work well when I run the tutorial but my dataset is not huge as is not in memory either so I wasn't expecting this to be a problem.

The log I get is "src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7ffdafbc10d8" before I get "KernelRestarter: restarting kernel (1/5), keep random ports" and "WARNING:root:kernel 7180f956-fbf9-4e1b-adb7-617812dd4ee1 restarted".

Do you have any hint of what might be happening? Any suggestion is welcomed!

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/rusty1s/pytorch_geometric/discussions/2936.
