### ISSUE TITLE
Python 2 Support?

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_geometric#295]
## ❓ Questions & Help

Looks like the [example code](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ppi.py) doesn't support `python 2`. 

Any plan to support `python 2` in the future?

**Comment by rusty1s** [comment]
Python 2 support should be fine. For the examples, you need to fix the accuracy computations by using
```python
from __future__ import division
```

**Comment by mingloo** [comment]
Hi @rusty1s 

Still have some incompatible issue between `python 2` and `3` as below...

> Traceback (most recent call last):
  File "ppi.py", line 7, in <module>
    from torch_geometric.nn import GATConv
  File "/home/minglu/anaconda2/lib/python2.7/site-packages/torch_geometric/nn/__init__.py", line 4, in <module>
    from .conv import *  # noqa
  File "/home/minglu/anaconda2/lib/python2.7/site-packages/torch_geometric/nn/conv/__init__.py", line 15, in <module>
    from .dna_conv import DNAConv
  File "/home/minglu/anaconda2/lib/python2.7/site-packages/torch_geometric/nn/conv/dna_conv.py", line 47
    out = out.view(*size, self.out_channels)
SyntaxError: only named arguments may follow *expression

**Comment by rusty1s** [comment]
Ah I see, seems like Python2 is currently not supported. I should add the Python2 travis builds back in and see if I can fix the incompatibilities (I didn't know there are still people using Python2 :P).

**Comment by rusty1s** [comment]
I added Python2.7 support back into master (see [here](https://travis-ci.org/rusty1s/pytorch_geometric))

**Comment by mingloo** [comment]
Thanks for your help! @rusty1s

**Comment by mingloo** [comment]
Hi @rusty1s 

One more question, is there any release plan like `1.2.1` to incorporate `python 2` fix so that users can install `torch_geometric` via `pip install`?

**Comment by rusty1s** [comment]
Yes, as soon as I have fixed the DiffPool `NaN` error.

**Comment by mingloo** [comment]
Thanks a lot.
