### ISSUE TITLE
How to get batch sizes greater than 1 with graphs of arbitrary (and different) numbers of nodes?

### ISSUE THREAD

**Issue by errhernandez** [rusty1s/pytorch_geometric#2961]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

I am trying to create a torch_geometrid.data.Dataloader to work with a collection of graphs having arbitrary but generally different numbers of nodes. The objective is to train a CGNN to predict a graph feature based on node embeddings.  I follow the steps indicated in the documentation (https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html#batching-along-new-dimensions) which appear to apply to my case. Everything appears to work fine if I set batch_size = 1, but if I try anything bigger, I get the following error message:

RuntimeError: Sizes of tensors must match except in dimension 0. Got 72 and 54 in dimension 1 (The offending index is 1)

I have also tried increasing num_workers in the DataLoader, but it doesn't solve the problem either. 

I'd appreciate any help on this.

**Comment by rusty1s** [comment]
I think the "Batching along new dimensions" does not really fit your use-case, as this only works for node-level attributes in case all your graphs are of the same size. However, the standard `torch_geometric.data.DataLoader` should cover this use-case already pretty well (and in general does not require any modifications for mini-batching). Does that not work for you?

**Comment by errhernandez** [comment]
Hi; thank you for your reply. Unfortunately, I can't get torch_geometric.data.DataLoader to work for my case with batch_size > 1. Here is what happens:

This works fine:

nBatch = 1
trainLoader = DataLoader( trainDataset, batch_size = nBatch, num_workers = 0 )
valLoader = DataLoader( valDataset, batch_size = nBatch, num_workers = 0 )
testLoader = DataLoader( testDataset, batch_size = nBatch, num_workers = 0 )

and produces the following output (irrelevant really, but shown for completeness)

epoch      train-loss      validation-loss
------------------------------------------
0,  1578479.1875,  1728759.234375
1,  1481032.5859375,  1666272.3984375
...
9,  1077099.15234375,  1285475.078125

Now, this doesn't work:

nBatch = 2 (everything else the same)

produces the following output:

epoch      train-loss      validation-loss
------------------------------------------
Traceback (most recent call last):
  File "FitGraph.py", line 62, in <module>
    for sample in trainLoader:
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 36, in __call__
    return self.collate(batch)
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch_geometric/data/dataloader.py", line 16, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/Users/ehe/opt/anaconda3/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 151, in from_data_list
    batch[key] = torch.cat(items, cat_dim)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 72 and 54 in dimension 1 (The offending index is 1)

Perhaps I'm doing something wrong out of ignorance (I am obviously a newbie). The fit loop looks like this:

model.train()

for epoch in range( nEpochs ):

    train_running_loss = 0.0

    for sample in trainLoader:

        optimizer.zero_grad()

        with debug():

           energy = model( sample, sample.batch )

           # train_loss = lossFunction( torch.squeeze( energy, dim = 1 ), sample.y[12] )  # this is the energy
           train_loss = lossFunction( torch.squeeze( energy, dim = 1 ), sample.y[:,12] )

           train_running_loss += train_loss.item()

        # perform backward pass and update parameters

           train_loss.backward()

           optimizer.step()

Thanks for your time.

**Comment by rusty1s** [comment]
Can you show me how your `Data` objects look like?

**Comment by errhernandez** [comment]
Sure! I create them like this:

Graph = Data( x = nodeFeatures, y = y, edge_index = edge_index, edge_attr = edge_attr )

where 
- nodeFeatures is a torch.float32 tensor of size [ nNodes, nFeatures ] 
- y is a 1D torch tensor.float32 of graph properties, but in practice I only fit against one of its entries. 
- edge_index is the usual  torch.long [2,nEdges]
- edge_attr a torch.float32 [nEdges,1] (only one attribute per edge).

Does this answer your question?

**Comment by rusty1s** [comment]
This looks correct and should work out-of-the-box. Can you give me a small example to reproduce?

**Comment by errhernandez** [comment]
Can I send you a tar file?

**Comment by rusty1s** [comment]
Sure, either upload it or send it to my email :)

**Comment by errhernandez** [comment]
[bugGraph.tar.gz](https://github.com/rusty1s/pytorch_geometric/files/6974785/bugGraph.tar.gz)
Hello again!
If you untar the above file and simply type "python FitGraph.py" you'll get an example that works (nBatch = 1). If, after that you edit FItGraph.py and look for the line setting nBatch and change it to e.g. nBatch = 2, things fail. 

Again, thank you so much for your help.

Eduardo

**Comment by errhernandez** [comment]
I see! The number of graph features that are contained in y depends on the number of nodes in the graph, hence y has varying dimensions, but this is easily overcome in my particular case, since I only use one value of y for fitting, so one only needs a tensor of size 1 containing that particular value. I can try that!

Again, thank you so much for taking the time to help me over this. I was quite at a loss. 

Best wishes,

Eduardo

**Comment by errhernandez** [comment]
Solved. Thank you!

**Comment by ducviet00** [comment]
Hi @rusty1s 
I'm working on a dataset containing many graphs with variety number of nodes in each graph. 
It works fine with `torch_geometric.data.DataLoader`.
But now, I want to learn adjacency matrices, so combining many graphs in one (there is no connection between 2 graphs) does not work. 
I am trying with padding nodes and masking them to batching in a new dimension. But it adds noise to the graph. Could you recommend a better way?

**Comment by rusty1s** [comment]
I assume that you want to learn adjacency matrices in a fully-connected graph? Then you will indeed have to handle padding of nodes and masking by yourself :(

If you want to re-fine a graph based on sparse connections already given, you can still use `torch_geometric.data.DataLoader`, and learn dedicated `edge_weight` vectors.

**Comment by AliyaDav** [comment]
Hi @rusty1s! 

I came across the same issue.. I created custom dataset where graphs are of different sizes, tried to use `torch_geometric.data.DataLoader` but run into error:

```
Traceback (most recent call last):
  File "/Users/aliyadavletshina/Desktop/thesis/VRPNet/run.py", line 195, in <module>
    _run_sl(opts)
  File "/Users/aliyadavletshina/Desktop/thesis/VRPNet/run.py", line 170, in _run_sl
    train_epoch_sl(
  File "/Users/aliyadavletshina/Desktop/thesis/VRPNet/train.py", line 126, in train_epoch_sl
    for batch_id, batch in enumerate(tqdm(train_dataloader, disable=opts.no_progress_bar)):
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/loader/dataloader.py", line 34, in __call__
    return [self(s) for s in zip(*batch)]
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/loader/dataloader.py", line 34, in <listcomp>
    return [self(s) for s in zip(*batch)]
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/loader/dataloader.py", line 19, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/data/collate.py", line 84, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/Users/aliyadavletshina/Library/Python/3.10/lib/python/site-packages/torch_geometric/data/collate.py", line 155, in _collate
    value = torch.cat(values, dim=cat_dim or 0, out=out)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 34 but got size 44 for tensor number 1 in the list.
```

Here is the minimal code to reproduce.
[debug_GNN.tgz](https://github.com/pyg-team/pytorch_geometric/files/9837578/debug_GNN.tgz)

**Comment by AliyaDav** [comment]
@EdisonLeeeee thank you so much! Issue solved.
