### ISSUE TITLE
About the InMemoryDataset

### ISSUE THREAD

**Issue by Archer666** [rusty1s/pytorch_geometric#297]
Excuse me, I want to use the CoMA dataset, contains about 20000 mesh, each has 5023 vertices.Should I use InMemoryDataset Class to read the data or just use the torch_geometric.data.Dataset.

**Comment by rusty1s** [comment]
Hi, we actually implemented the CoMA dataset as an [`InMemoryDataset`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/coma.py), but dependent on your memory this may be better implemented as a normal `Dataset`. I recommend checking the provided dataset and see if it fits your need.
