### ISSUE TITLE
Incorrect to_network from subgraph

### ISSUE THREAD

**Issue by cshjin** [rusty1s/pytorch_geometric#2972]
## To Reproduce

1. graph from `KarateClub` dataset
2. extract an induced 1-hop subgraph from a single node, i.e, 9
3. build the networkx graph from it.

```python
from torch_geometric.datasets import KarateClub
import torch_geometric.utils as pygutil
import networkx as nx
dataset = KarateClub()
node_idx, edge_index, node_mapping_idx, edge_mask = ptgutil.k_hop_subgraph(9, 1, dataset.data.edge_index)
print(node_idx)  ## output [2, 9, 33]
data = Data(dataset.data.x[node_idx], edge_index=edge_index, edge_attr=None, y=dataset.data.y[node_idx])
subG = ptgutil.to_networkx(data, to_undirected=True)
print(subG.nodes()) ## output [0, 1, 2, 9, 33]
nx.draw_networkx(subG)
```

Then it will produce a graph with additional nodes [0, 1]
![image](https://user-images.githubusercontent.com/4164048/129464891-140d24a7-f9a7-45a8-bbff-ef304f6489cc.png)

## Environment

* OS: Linux
* Python version: 3.7.12
* PyTorch version:  1.5
* CUDA/cuDNN version: 11.1
* GCC version: 7
* Any other relevant information: N/A

## Additional context

It is mainly because 
https://github.com/rusty1s/pytorch_geometric/blob/38f2a7447bb9975d7ef649039f2f4d5cea451cdb/torch_geometric/utils/convert.py#L78
in `to_networkx` function is incorrect.

Should be fixed with (or simply remove it) 
```python
G.add_nodes_from(torch.unique(data.edge_index).numpy())
# extract the nodes with ids rather than numbers.
```

Or a better way I am thinking is to change the API from 
`def to_networkx(data, node_attrs=None, edge_attrs=None, to_undirected=False,
                remove_self_loops=False):`
to 
`def to_networkx(edge_index, node_attrs=None, edge_attrs=None, to_undirected=False,
                remove_self_loops=False):`
same some mem from creating a new Data object.

**Comment by rusty1s** [comment]
Your `data` object is not valid, which will introduce this "bug" during `networkx` conversion. In particular, `edge_index` contains values greater than the actual number of nodes in your graph. Using
```python
node_idx, edge_index, node_mapping_idx, edge_mask = ptgutil.k_hop_subgraph(9, 1, dataset.data.edge_index, relabel_nodes=True)
```
fixes this issue.
