### ISSUE TITLE
What scatter_() needs as input??

### ISSUE THREAD

**Issue by okayu1015** [rusty1s/pytorch_geometric#2978]
## ❓ Questions & Help

Hello, @rusty1s .
Your `pytorch_geometric.utils.scatter_()` has (name, src, index, dim=0, dim_size=None) as parameters. ([source](https://pytorch-geometric.readthedocs.io/en/1.3.2/modules/utils.html?highlight=scatter#torch_geometric.utils.scatter_))
However, `torch.scatter_()` needs **input**. ([source](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_))
So, what is the input?

I know #1526 issue, and I will replace `pytorch_geometric.utils.scatter_()` with `torch.scatter()`.

 Thanks in advance!

**Comment by rusty1s** [comment]
The `torch.scatter_` performs an in-place operation (it aggregates all values into `input`, while `torch_geometric.utils.scatter_` is an out-of-place operation and will return a new tensor.

**Comment by okayu1015** [comment]
Thanks to your advice, the problem has been solved!

**Comment by Gouvernathor** [comment]
Is there a canonic way to create that `input` tensor ? I'm trying to create it using the src and index tensors as models, but it's not working.
Could you publish an official workaround ? Like `p_g.utils.scatter_(name, src, index, dim_size=dim)` -> `torch._new_tensor().scatter_(dim, index, src, reduce=name)` ? For example in the torch_geometric.utils doc page, for people wanting to adapt code from previous versions.

**Comment by rusty1s** [comment]
The recommended workaround of
```python
torch_geometric.utils.scatter_(name, src, index, dim_size=dim)
```
is
```python
from torch_scatter import scatter
scatter(src, index, dim=dim, dim_size=dim_size, reduce=name)
```

**Comment by ScottHoang** [comment]
> The recommended workaround of
> 
> ```python
> torch_geometric.utils.scatter_(name, src, index, dim_size=dim)
> ```
> 
> is
> 
> ```python
> from torch_scatter import scatter
> scatter(src, index, dim=dim, dim_size=dim_size, reduce=name)
> ```

what is "dim_size" in this case for for dim_size argument in torch scatter() ?

**Comment by rusty1s** [comment]
Can you clarify what you mean? The `dim_size` argument is determines the new size of the dimension along we reduce.
