### ISSUE TITLE
How to use KNNGraph with Data or batch

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [rusty1s/pytorch_geometric#298]
## ❓ Questions & Help

Hello,

is it possible to use `KNNGraph` with a instance of `Data` or just `Batch`? 

```python
edge_index, x = ....


x = torch.tensor(x, dtype=torch.float).unsqueeze(-1)

edge_index = torch.tensor(edge_index, dtype=torch.long)

data = Data(x=x, edge_index=edge_index)

print(data)

>>>>Data(edge_index=[2, 5776], x=[5776, 1])

knn = KNNGraph(k=6)
knn(data)
```
Error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-61-52b703663264> in <module>()
     14 # ds = MyDataset(root='/')
     15 
---> 16 knn(data)

2 frames
/usr/local/lib/python3.6/dist-packages/torch_cluster/knn.py in knn(x, y, k, batch_x, batch_y)
     40 
     41     if batch_x is None:
---> 42         batch_x = x.new_zeros(x.size(0), dtype=torch.long)
     43 
     44     if batch_y is None:

AttributeError: 'NoneType' object has no attribute 'new_zeros'
```
Thank you in advance

Francesco

**Comment by rusty1s** [comment]
Ah, the `KNNGraph` build the graph based on the `pos` attribute. So if you set `data` to
```python
data = Data(pos=pos, edge_index=edge_index)
```
this should work just fine.

**Comment by FrancescoSaverioZuppichini** [comment]
it is not clear to me what `.pos` should be. 

I have a gray image, e.g. 100x100, and I want to convert it to a graph. So I first create a Data with all the pixels connected and then my plan is to use KNN to make each node connected only to `k` neighbors.

**Comment by rusty1s** [comment]
You want to use `knn` based on pixel colors or positions?

**Comment by FrancescoSaverioZuppichini** [comment]
position

**Comment by rusty1s** [comment]
Then save the position in `.pos`. Alternatively, use the [`grid`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/grid.py#L5) function.

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect! 

![image](https://user-images.githubusercontent.com/15908060/57713231-58392480-7672-11e9-9e01-7f8877eb49d9.png)

Do you think this strategy is feasible for around 150k of 76x76 images? In colab seems very slow but probably it is running on CPU, nevertheless, any advice is more than appreciated

**Comment by rusty1s** [comment]
It takes 29s to build one `knn` graph? This seems really slow to me. I verified it and its true, but its much faster if you convert `pos` to `torch.float` first:
```python
data = Data(pos=pos.to(torch.float))
```
This seems to be a bug in `grid`. Will fix it.

**Comment by rusty1s** [comment]
Fixed in master.

**Comment by FrancescoSaverioZuppichini** [comment]
is `edge_index` too big? `51076` seems huge to me since I have 10k nodes in the `100x100` image. 

By the way, is there a way to offer you a beer?  So at least I don't feel bad bothering you

**Comment by rusty1s** [comment]
`76*76*6=34656` should be the number of edges. This is true for floating point `pos` tensor. The `KNNGraph` transform just does not work for integer types.

**Comment by FrancescoSaverioZuppichini** [comment]
yes, it makes sense. Thank you

**Comment by FrancescoSaverioZuppichini** [comment]
well, I say we can close the issue. Thank you again

**Comment by rusty1s** [comment]
No problem :)

**Comment by JPBatisteli** [comment]
What are the changes needed if i want to to use knn based on pixel colors?

**Comment by rusty1s** [comment]
I don't think any changes are required. Can you clarify?
