### ISSUE TITLE
Process large dataset

### ISSUE THREAD

**Issue by 595693085** [rusty1s/pytorch_geometric#3000]
Hi,
I'm struggling with a problem. Here, I'm trying to create a large dataset with N samples. Each sample is like (graph_i1, graph_i2, ... , graph _in, Y) , where y is the label. I solved it by using the collate_n to return a tuple like this, but there's problem. Because N is a very large number (such as 1000000000) which memory can not hold the dataset. So i intend to use torch.load to load each saved sample, but too slow and there around N files in disk (too messy).  And now i want to save it on 3 files which each file saves L/3 samples, this may be fast, but i don't know how to implement it. Is there any suggestion to it or other solutions to the probles, thank you.

**Comment by rusty1s** [comment]
This is indeed tricky to implement. One thing that could work is implementing your own `Dataset` class which implements a custom `__iter__` method. Once you reach a certain step, you will load the next chunk of data from memory and throw the old one away. Does something like that work for you?

**Comment by 595693085** [comment]
Thanks for your reply. So there is no directly available way in PyG to implement larger dataset in several saved chunks, right? And is there any available method in PyG to implement a sample, which n graphs correspond to one label, i konw we can use Data object to package one sample with a graph and a label, but if there are two or more graph in one sample, how to implement it. I just want to improve the efficiency of my code. Thank you.

**Comment by rusty1s** [comment]
Yes, this needs to be implemented from scratch at the moment. Sorry :( If you have a working solution, it would be great to support that directly in PyG.

The data object currently does not support batching a list of graphs, so you will need to store each `edge_index` individually, e.g.:
```python
data = Data()
for i, edge_index in enumerate(edge_indices):
    data[f'edge_index_{i}'] = edge_index
```

**Comment by 595693085** [comment]
Thank you very much. I'll try it.
