### ISSUE TITLE
utilise multiple CPUs for cora.py

### ISSUE THREAD

**Issue by jazzmuesli** [rusty1s/pytorch_geometric#302]
## 🚀 Feature

I have created an environment from https://github.com/jazzmuesli/pytorch_geometric/blob/288_pytorch110-docker/docker/Dockerfile and running python cora.py I can see it utilises only one CPU.

## Motivation

It would be useful to utilise multiple CPUs.

## Additional context

Also add tqdm progressbar.

**Comment by rusty1s** [comment]
Hi, and thank you. This is just a problem with the CPU version of `SplineConv` which is not really well implemented and should therefore be avoided. I can fix that but IMO this is not that important. I believe sr should add a warning when using SplineCNN on CPU.

In addition, I do not think we should add the `tqdm` package as a dependency to PyG just fir the examples. IMO, this is fine as it is right now. Is this okay for you?
