### ISSUE TITLE
the order of the neighboring nodes

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#304]
Hi,

Assume edge_index is generated by FaceToEdge, do the neighboring nodes (assume neighboring nodes are consecutively yielded from edge_index[1]) of a node i in edge_index[0] follow any order like clockwise or counter-clockwise?

**Comment by rusty1s** [comment]
Generally speaking, all operators that change/create graph structure order edge indices row-wise. However, for PyG message operators, there are no requirements on the order of edge indices.

**Comment by sw-gong** [comment]
I suppose I should make it clear. What my concern is that I want to generate concatenated features with 1, 2, .., k-hop neighboring nodes and nodes are following clockwise or counter clockwise order in each hop.

**Comment by rusty1s** [comment]
I understand. Actually, PyG can not guarantee that. It might be best to sort the edge indices on your own, given your specific condition.

**Comment by sw-gong** [comment]
Do you know any convenient way to perform that? Assume input data are triangulated meshes, any nodes should be surrounded by a couple of faces, so we can generate sorted neighboring nodes right? But how to do it with the data structures provided in pyg?

**Comment by rusty1s** [comment]
In theory, this is possible (although there is no dedicated start node). It is maybe best to implement this in pure Python (due to the sequential processing of the neighboring nodes), and to convert the resulting edge list into a PyTorch tensor.

**Comment by sw-gong** [comment]
Every start point in the (k+1) hop can be assigned to the point with the minimal Euclidean distance to the last point in the (k) hop. In this case, do you know if there is a easy way to implement that in pure Python?

**Comment by rusty1s** [comment]
I‘m sorry. I do not know of any specific algorithms.
