### ISSUE TITLE
When putting an object of torch_geometric.data.Data to GPU, attributes of namedtuple will be converted to List.

### ISSUE THREAD

**Issue by WuliangHuang** [rusty1s/pytorch_geometric#3056]
## 🐛 Bug
When putting an object `data` of `torch_geometric.data.Data` to GPU, if the types of some attributes are `collections.namedtuple,` it will cause unexpected results.

## To Reproduce
Running this demo, the type of `x1` is `PackedSequence.` while the type of `x2` is `List`.
```python
import torch
from torch.nn.utils.rnn import pack_padded_sequence, pad_sequence
from torch_geometric.data import Data

x = pad_sequence(
    [torch.FloatTensor([[1, 2], [1, 2]]), torch.FloatTensor([[1, 2]])]
)
x = pack_padded_sequence(x, [2, 1], batch_first = True)
x1 = x.cuda()
data = Data(
    x = x
)
data = data.cuda()
x2 = data.x
```

## Suggestions
In `torch_geometric/data/data.py`, function , `__apply__`, [line 317](https://github.com/rusty1s/pytorch_geometric/blame/e425622d6efc6832b15e9fe577710a7119d76cef/torch_geometric/data/data.py#L307-L322) 

```python
def __apply__(self, item, func):
    if torch.is_tensor(item):
    # If replacing the above line, the question above will be solved. It should be 
    # if torch.is_tensor(item) or isinstance(item, PackedSequence):
        return func(item)
    ...
    elif isinstance(item, (tuple, list)): # Here, a PackedSequence Object will be converted to list.
        return [self.__apply__(v, func) for v in item]
    elif isinstance(item, dict):
        return {k: self.__apply__(v, func) for k, v in item.items()}
    else:
        return item
```
I think if we replace `if torch.is_tensor(item):` to ` if torch.is_tensor(item) or isinstance(item, PackedSequence):`, this problem will be solved.

However, I have two concerns.
- The first is if this is really a bug. I do not know if this will break some other rules.
- The second is if there are other types like `collections.namedtuple` which will cause this situation.

**Comment by rusty1s** [comment]
Yes, you are right. I'm happy to take a PR on this one if you like. An alternative is to pass individual elements of `PackedSequence` to `Data`, e.g.:
```python
data = Data(**x._asdict())
```

**Comment by rusty1s** [comment]
Fixed via https://github.com/rusty1s/pytorch_geometric/pull/3066
