### ISSUE TITLE
About a lot of edges

### ISSUE THREAD

**Issue by TCcoder** [rusty1s/pytorch_geometric#306]
## ❓ Questions & Help

hi, PyG is a cool thing,and I am interested in this job.Thank you for your hard working.

OK,for my project, i am trying to train a Graph with a GAT, but the edge index is too large that my memory is not enough to run,so i try to solve it with this  method

https://rusty1s.github.io/pytorch_geometric/build/html/notes/create_dataset.html#creating-larger-datasets

I split the edge index several parts that it can work, but I don't know whether it's true or not, and the result looks not so good,so i think divide edge index is not true,but i haven't a good idea for this problem.How do you deal with such large edge index Graph?

thank you very much and look forward to your reply.

**Comment by rusty1s** [comment]
You need some kind of neighborhood sampling for this, something which is currently not supported by PyG (see [here](https://github.com/rusty1s/pytorch_geometric/issues/64)).
