### ISSUE TITLE
LEConv is not jittable

### ISSUE THREAD

**Issue by lucagrementieri** [rusty1s/pytorch_geometric#3064]
## 🐛 Bug

The layer `LEConv` is not jittable since its source code contains no type hints and no `propagate_type` comment.

## To Reproduce

1. Run the following code 
```
import torch_geometric.nn.conv as conv
conv.LEConv(10, 10).jittable()
```

The error displayed is
```
TypeError: TorchScript support requires the definition of the types passed to `propagate()`. Please specificy them via 

propagate_type = {"arg1": type1, "arg2": type2, ... }

or via

# propagate_type: (arg1: type1, arg2: type2, ...)

inside the `MessagePassing` module.
```

## Expected behavior

The layer should be jittable as other convolution layers.

## Environment

* OS: ArchLinux
* Python version: 3.9.6
* PyTorch version: 1.9.0
* CUDA/cuDNN version: 11.4.1
* GCC version: 11.1.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Thanks for reporting. That was indeed a bit sloppy. I fixed it in master, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/le_conv.py).

**Comment by vincrichard** [comment]
Hello @rusty1s , I just updated my Pytorch Geometric from a older version (< 2.0) to  to the current version. 
I am now facing an issue where previous trained model are not consistent in inference, I pin pointed the issue to the LEConv layer update in this [commit](https://github.com/pyg-team/pytorch_geometric/commit/3183fe181c2bec68cadc32de318e99fdd981a2a8#diff-e2f663118dc641af24c378ed8b27ffe5dc2dd97bc1edaf795904b95009c22698R70): 

Specifically, you inverted the i and j subscript. What was the reason behind this choice ? This, as far as I can tell, leads to the previous trained model using the LEConv layer to be unusable. I don't know the framework well so there might be other point which motivates this change.

From previous version:
```    
def message(self, a_i, b_j, edge_weight):
        out = a_i - b_j
```
to current version (> 2.0)
```
    def message(self, a_j: Tensor, b_i: Tensor,
                edge_weight: OptTensor) -> Tensor:
        out = a_j - b_i
```

**Comment by rusty1s** [comment]
Yes, this is a bugfix for handling bipartite graphs currently in `LEConv`. `a` refers to transformed source node features (`_j`), while `b` refers to transformed destination node features (`_i`). Sorry for the inconvenience. As a short term fix, you can just swap out the layers on your own:
```python
conv = LEConv(...)
conv.lin1, conv.lin2 = conv.lin2, conv.lin1
