### ISSUE TITLE
ModelNet dataset error on Window

### ISSUE THREAD

**Issue by hagianga21** [rusty1s/pytorch_geometric#308]
## 🐛 Bug

When I load PointNet2 example. There 's an error occur with ModelNet.
## To Reproduce

The log file:

IndexError                                Traceback (most recent call last)
<ipython-input-7-beccdbcb74fd> in <module>
      3 print(DataPath)
      4 pre_transform, transform = T.NormalizeScale(), T.SamplePoints(1024)
----> 5 train_dataset = ModelNet(DataPath, '10', True, transform, pre_transform)
      6 test_dataset = ModelNet(DataPath, '10', False, transform, pre_transform)

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\datasets\modelnet.py in __init__(self, root, name, train, transform, pre_transform, pre_filter)
     61         self.name = name
     62         super(ModelNet, self).__init__(root, transform, pre_transform,
---> 63                                        pre_filter)
     64         path = self.processed_paths[0] if train else self.processed_paths[1]
     65         self.data, self.slices = torch.load(path)

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\data\in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     54                  pre_filter=None):
     55         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 56                                               pre_filter)
     57         self.data, self.slices = None, None
     58 

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\data\dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     81 
     82         self._download()
---> 83         self._process()
     84 
     85     @property

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\data\dataset.py in _process(self)
    115 
    116         makedirs(self.processed_dir)
--> 117         self.process()
    118 
    119         print('Done!')

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\datasets\modelnet.py in process(self)
     84 
     85     def process(self):
---> 86         torch.save(self.process_set('train'), self.processed_paths[0])
     87         torch.save(self.process_set('test'), self.processed_paths[1])
     88 

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\datasets\modelnet.py in process_set(self, dataset)
     89     def process_set(self, dataset):
     90         categories = glob.glob(osp.join(self.raw_dir, '*', ''))
---> 91         categories = sorted([x.split('/')[-2] for x in categories])
     92 
     93         data_list = []

~\Anaconda3\envs\basic\lib\site-packages\torch_geometric\datasets\modelnet.py in <listcomp>(.0)
     89     def process_set(self, dataset):
     90         categories = glob.glob(osp.join(self.raw_dir, '*', ''))
---> 91         categories = sorted([x.split('/')[-2] for x in categories])
     92 
     93         data_list = []

IndexError: list index out of range

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Should be fixed in master.

**Comment by hagianga21** [comment]
Thank you so much. It is fixed
