### ISSUE TITLE
EdgeIndex increase when batching

### ISSUE THREAD

**Issue by Blitzman** [rusty1s/pytorch_geometric#31]
Hi!

Thanks for this awesome tool! I am having a great time writing my custom datataset and loader for a problem at hand but just stumbled upon something that was messing my visualizations up!

Say I have graphs with x=[3,24], y=[1], pos=[2,24] and edge_index=[2,66] (in both directions so undirected). When I try to batch them in say, batches of 3 or 4 my edge indices get increased by 3 for each graph in the batch!

E.g.: if the original edges are [ [0, 1, 1, 2], [1, 0, 2, 1] ] then for the first graph in the batch they are OK but for the next batch they get increased by 3 as follows [ [3, 4, 4, 5], [4, 3, 5, 4] ]. And that messes up my visualizations since I take edge indices to find node positions.

Question is... is that intended and needed for any kind of operation I am missing when using batches? Is it a bug? Maybe I am missing something in my code but can't find it.

So far the solution is as easy as doing edge_indices - 3*i being i the graph in the batch index but...

Thank you!

**Comment by rusty1s** [comment]
Hi,
the edge indices should indeed increase when using batches (same as node features are concatenated in the node dimension). So what you actually get when using batches is one big graph which contains disconnected subgraphs (your examples). 
I think your example is wrong, as both `x` and `pos` should have shape [N, ...] (N being the number of nodes) instead of [..., N]. Then your edge indices get increased by N instead of 3.

**Comment by Blitzman** [comment]
Hi!

Thanks a lot for your reply. I got confused about 'x' and 'pos' shapes and completely messed it up. Sorry for missing that and making you waste your time.

Regarding the fact that batches are treated as one big graph with disconnected subgraphs... What implications does that have? I don't quite get how those disconnected graphs are handled by let's say a max pooling layer.

Thanks for your answer!

**Comment by rusty1s** [comment]
Regarding implications: Pooling operators do in fact need to be designed to work in a batch-wise fashion, do that only the disconnected supgraphs are pooled. For, e.g., global pooling, this can be achieved via operations like scatter-max or scatter-mean.

Further disadvantages arise when you want to model autoencoders based on probability adjacency matrices. In this case it might be more beneficial to just use dense adjacency matrices stacked together with zero paddings.

However, in general the advantages you get (sparse representation + dynamic number of nodes for each graph) heavily outweight those disadvantages. It is nonetheless important to be aware of them.

**Comment by Blitzman** [comment]
Thanks a lot Matthias, that was quite helpful!
