### ISSUE TITLE
HeteroConv edge attributes not correctly used

### ISSUE THREAD

**Issue by JakeForsey** [rusty1s/pytorch_geometric#3111]
## 🐛 Bug

edge_attr_dict is not used unless edge_weight_dict is also used

I believe this line is incorrect: https://github.com/rusty1s/pytorch_geometric/blob/5d93de54aaeb38747aea8c08e0b98ba36aaab9b7/torch_geometric/nn/conv/hetero_conv.py#L85

**Comment by rusty1s** [comment]
Thanks! This is now fixed in master.
