### ISSUE TITLE
Is there a nightly Build for pytorch_geometric

### ISSUE THREAD

**Issue by deepakagrawal** [rusty1s/pytorch_geometric#3116]
I see that there is already a documentation for PyG 2.0 [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html). It has many new implementations such as `HeteroData`, `HeteroConv`. Is there a way I can install it using pip or conda?

**Comment by rusty1s** [comment]
You can install the latest features via
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
