### ISSUE TITLE
Create own torch_geometric.data.Data class with extra features

### ISSUE THREAD

**Issue by ludwigwinkler** [rusty1s/pytorch_geometric#313]
Hi,

first of all thank you very much for your awesome library.
We all appreciate it your work a lot.

My question concerns the torch_geometric.data.Data class:

Let's say I have a graph and I have some extra features which cannot be described with the attributes of the torch_geometric.data.Data class.

How would I add these extra features of edges, nodes or the entire graph to the Data class?

Below is a conceptual example of what I would like to achieve.
It basically boils down to the Dataloader spitting out more information than "just" x, y, edge_index, edge_attribute etc.

Specifically, I would like to receive the extra_data1 and extra_data2 during the training loop, as highlighted in the AugmentedData class.

In fact, during my testing the Dataloader produces seemingly right batches with all the relevant information including extra_data1 and extra_data2.
The Dataloader seemingly grabs all the class attributes correctly and apparently there is no need to implement an extra __getitem__ method?
I just wanted to make sure what the proper way is to implement such extra data.

Thanks in advance for your time and thanks a lot for your effort!

```
import torch
import torch.nn.functional as F

import torch_geometric
from torch_geometric import transforms
from torch_geometric.data import InMemoryDataset, Data

import os

class AugmentedData(torch_geometric.data.Data):

	def __init__(self,
	             _x                 = None,
	             _edge_index        = None,
	             _edge_attribute    = None,
	             _y                 = None,
	             _pos               = None,
	             _norm              = None,
	             _face              = None,
	             _extra_data1       = None,
	             _extra_data2       = None)

		super().__init__()
		
		self.x                 = _x,
		self.edge_index        = _edge_index,
		self.edge_attribute    = _edge_attribute,
		self.y                 = _y,
		self.pos               = _pos,
		self.norm              = _norm,
		self.face              = _face,
		
		# !!!!!!! 
		self.extra_data1       = _extra_data1,
		self.extra_data2       = _extra_data2
		# !!!!!!! 

class AugmentedDataSet(InMemoryDataset):
	def __init__(self,
	             root=None,
	             name=None,
	             transform=None,
	             pre_transform=None):

		super().__init__(root, name, transform, pre_transform)

		
		self.data, self.slices = torch.load(self.processed_paths[0])
		os.remove(self.processed_paths[0])

	@property
	def raw_file_names(self):

		return ['xzy_raw']

	@property
	def processed_file_names(self):

		return ['xzy_processed']

	def download(self):
		pass

	def process(self):

		
		data = [AugmentedData(...), AugmentedData(...), AugmentedData(...)] # Code obviously not working
		
		data, slices = self.collate(data)

		torch.save((data, slices), self.processed_paths[0])


data = AugmentedDataSet()

dataloader = torch_geometric.data.DataLoader(data)
```

**Comment by rusty1s** [comment]
Hi, you do not need to inherit from `Data`. `Data` can hold any attribute:
```python
data = Data(x=x, extra_data1=extra_data1)
data.extra_data2 = data.extra_data2
```

**Comment by rusty1s** [comment]
In addition, no modifications are needed for the `Dataset`.

**Comment by ludwigwinkler** [comment]
Nice! Thanks a lot!
