### ISSUE TITLE
Questions about ChebConv

### ISSUE THREAD

**Issue by leondelee** [rusty1s/pytorch_geometric#317]
## ❓ Questions & Help

Hi, I am currently working with ChevConv but I don't understand the parameter "edge_index" in the function "forward" of the class ChevConv. Can anyone help me? Thanks!
` forward(x, edge_index, edge_weight=None)`

**Comment by rusty1s** [comment]
The `edge_index` denotes the connectivity as a sparse node tuple pair. Please have a look at the [tutorial](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html) for a better understanding.

**Comment by leondelee** [comment]
Thanks! That helps a lot!
