### ISSUE TITLE
Problem about ChebConv

### ISSUE THREAD

**Issue by lu-m13** [rusty1s/pytorch_geometric#32]
Hi, in the code of ChebConv, you use the following implementation:

![image](https://user-images.githubusercontent.com/18493978/48056074-fc39a300-e1eb-11e8-8e68-4e8c35751e29.png)

According to the wiki, The elements of Symmetric normalized Laplacian should be defined as:

![image](https://user-images.githubusercontent.com/18493978/48056176-2ee39b80-e1ec-11e8-83d4-e9021b023453.png)

I wonder if the two formulations are the same in your library, please reply me if you have time. Thanks.

**Comment by rusty1s** [comment]
Hi,
the line `deg[row] * edge_attr * deg[col]` indeed computes `D^-0.5 * A * D^-0.5`.
However, the term `lap` may be misleading, as it acutally computes the scaled Laplacian: `2L/lambda_max - I`. With `lambda_max = 2` this boils down to `I - D^-0.5 * A * D^-0.5 - I = - D^-0.5 * A * D^-0.5`, which is in fact, what we compute here.

**Comment by lu-m13** [comment]
Ok, I see. Thanks!
