### ISSUE TITLE
batched sequence data

### ISSUE THREAD

**Issue by szymonzmyslony** [rusty1s/pytorch_geometric#321]
## ❓ Questions & Help
I am trying to create a graphConvLstm which requires an input and output sequence of graphs from the data-loader. For each data-sample I need 20 different graphs (5 for input), 15 for output and I would model it as tensor or array of graphs but this doesn't work with the concept of batch which doesn't accept array of graphs from _get_item.
What would be the best way to go about it?

**Comment by rusty1s** [comment]
You can encode multiple graphs in one `Data` object via the concept of disconnected graphs. In addition, you need a `seq` assignment vector that maps each node to its respective subgraph. You can then obtain subgraph-level embeddings via `batch` and `seq` assignments, and apply your LSTM afterwards on shapes `[batch_size, seq_len, *]`.

**Comment by szymonzmyslony** [comment]
Thanks for your quick reply, but unfortunately not quite sure how to proceeded, is there any example code that I could follow? I tried using nested batches but it also seems wrong.

**Comment by rusty1s** [comment]
There is no example code, sorry. Why do nested batches not work for you? You should post a minimal example for further discussion.

**Comment by szymonzmyslony** [comment]
Thanks, I managed to get it working by creating a single graph with multiple features nodes representing different src, trg for LSTM.  Thanks for you help!
