### ISSUE TITLE
GatedGraphConv input arguments bug

### ISSUE THREAD

**Issue by tomcat123a** [rusty1s/pytorch_geometric#325]
## To Reproduce

1.
from torch_geometric.nn import  GatedGraphConv
g = GatedGraphConv(2,7)
x = torch.tensor([[-1], [0], [1],[4]], dtype=torch.float)
egde_weight=torch.tensor([0.5,1,0.5])
edge_index = torch.tensor([[0, 1, 1],
                           [1, 0, 2]], dtype=torch.long)
    
g(x1,edge_index1,egde_weight)
1.
1.#the error message is

g(x1,edge_index1,egde_weight)
Traceback (most recent call last):

  File "<ipython-input-67-1c3f07ad6e91>", line 1, in <module>
    g(x1,edge_index1,egde_weight)

  File "C:\ProgramData\Anaconda3\envs\py001\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)

TypeError: forward() takes 3 positional arguments but 4 were given
## Expected behavior
The ducoment says the input argument list of GatedGraphConv is 
"forward(x, edge_index, edge_weight=None)"
as in https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html
.

## Environment

* OS: Windows 10
* Python version: 3.6.8
* PyTorch version:1.0.1
* CUDA/cuDNN version:
* GCC version:8.1.0
* Any other relevant information:

## Additional context

In your test code,the file
pytorch_geometric/test/nn/conv/test_gated_graph_conv.py
only tests the case where GatedGraphConv has arguments,not including an edge_weight argument.
Thanks.

**Comment by rusty1s** [comment]
The `edge_weight` attribute of the `GatedGraphConv` was recently integrated into PyTorch Geometric master. You need to either install from source to be able to pass `edge_weight` to the operator, or do not pass `edge_weight` at all. I will craft a new PyPi version soon.
