### ISSUE TITLE
Missing method in Data class

### ISSUE THREAD

**Issue by Flock1** [rusty1s/pytorch_geometric#326]
## ❓ Questions & Help

I was running the `cora.py` code and I came across an error:

> AttributeError: 'Data' object has no attribute 'num_classes'

This is in line `25`. This method is also missing in the `Data` class definition. Can you help me with this?

**Comment by rusty1s** [comment]
The `cora.py` script does not access `data.num_classes`, but `dataset.num_classes`. Are you sure you are running the latest scripts and versions?

**Comment by Flock1** [comment]
I cloned this:
https://github.com/llSourcell/pytorch_geometric

I guess this is the older one.

**Comment by rusty1s** [comment]
This is a fork. Please clone the official one.
