### ISSUE TITLE
Scatter_max overflows with int

### ISSUE THREAD

**Issue by Caykroyd** [rusty1s/pytorch_geometric#327]
## 🐛 Bug

I have a torch_geometric.data.Data object with the x attribute in torch.int format. (the attribute represents vertex colours, hence the type).

If I attempt to use torch.nn.max_pool, it will yield an error in scatter_max. Note that using torch.nn.avg_pool gives the desired result, as does converting the x attribute to float before trying scatter_max (which is what I resorted to doing)

````
>>> avg_pool(clusters,data)
Batch(edge_index=[2, 64384], pos=[10758, 3], x=[10758, 3])
>>> max_pool(clusters,data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wp01/trainees/aykroydc/tools/miniconda3/lib/python3.7/site-packages/torch_geometric/nn/pool/max_pool.py", line 64, in max_pool
    x = _max_pool_x(cluster, data.x)
  File "/home/wp01/trainees/aykroydc/tools/miniconda3/lib/python3.7/site-packages/torch_geometric/nn/pool/max_pool.py", line 9, in _max_pool_x
    return scatter_('max', x, cluster, dim_size=size)
  File "/home/wp01/trainees/aykroydc/tools/miniconda3/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 28, in scatter_
    out = op(src, index, 0, None, dim_size, fill_value)
  File "/home/wp01/trainees/aykroydc/tools/miniconda3/lib/python3.7/site-packages/torch_scatter/max.py", line 98, in scatter_max
    src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
  File "/home/wp01/trainees/aykroydc/tools/miniconda3/lib/python3.7/site-packages/torch_scatter/utils/gen.py", line 18, in gen
    out = src.new_full(out_size, fill_value)
RuntimeError: value cannot be converted to type int without overflow: -1e+38
````

Nothing particular about the data I'm using:
`>>> data.x.dtype`
`torch.int32`
`>>> data.x.shape`
`torch.Size([53490, 3])`
`>>> data.x.max()`
`tensor(239, dtype=torch.int32)`
`>>> data.x.min()`
`tensor(14, dtype=torch.int32)`
`>>> clusters.shape`
`torch.Size([53490])`

**Comment by rusty1s** [comment]
Hi, are you sure you are running the latest PyG version? This error was fixed a while ago. The default fill value is now `-1e9` (see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/scatter.py#L26)).

**Comment by Caykroyd** [comment]
Thanks. Indeed you're right, I had a version from mid-april.

Just a quick question while I'm at it. How would I proceed to use max_pooling on a batch, given that I have a cluster tensor for a **single** mesh but which I want to apply to all the (perfect-corresponding) meshes in the batch?
I tried
```
max_pool(cluster, batch)
max_pool_x(cluster, mesh, batch)
max_pool_x(cluster.repeat(1,max(mesh.batch)+1), mesh, batch)
```

**Comment by rusty1s** [comment]
Yes, that is the way to do it. Note that you need to add the bias for `batch` too.

**Comment by rusty1s** [comment]
Ok, so like that:
```python
cluster = cluster.view(1, -1).expand(batch_size, 1) * torch.arange(batch_size) * (cluster.max().item() + 1)
```

**Comment by Caykroyd** [comment]
I did it slightly different (I think you missed a repeat?)
```
cluster_new = cluster.repeat(1, data.batch.max() + 1)
cluster_new = cluster_new + torch.arange(data.batch.max() + 1).view(-1, 1).repeat(1,cluster.size(0)).view(-1) * (cluster.max().item() + 1)
cluster_new = cluster_new.view(-1)
```

**Comment by rusty1s** [comment]
Yes, this is possible too. I was making use of broadcasting though.
