### ISSUE TITLE
Enable inheriting from torch_geometric.data.Data

### ISSUE THREAD

**Issue by benjamin9555** [rusty1s/pytorch_geometric#328]
## 🚀 Feature

Change the Dataset Loading and Batching in a way such that it is able to handle custom classes that inherit from `torch_geometric.data.Data`.

## Motivation

I have seen #313 and agree that this is a nice workaround, but I don't think this is very clean. It gets a little bit fiddly once you want to build a lot of custom datasets with graphs that fulfill certain requirements.

As an example, I would like to have a custom plotting function for different kinds of data and it would be nice to include that as a method in the class inheriting from `torch_geometric.data.Data`.

**Comment by rusty1s** [comment]
You can now use custom data objects in `InMemoryDataset`.

**Comment by benjamin9555** [comment]
Awesome, thank you :) Note that custom data objects still don't work if a `DataLoader` is used to produce batches.

**Comment by rusty1s** [comment]
Yes, but there is no easy way to fix this.
