### ISSUE TITLE
Question about cora dataset

### ISSUE THREAD

**Issue by zdaiot** [rusty1s/pytorch_geometric#343]
## ❓ Questions & Help

Hello, in the website https://linqs.soe.ucsc.edu/data, it says that cora dataset has 5429 links, but why  the file `data/Cora/raw/ind.cora.graph` has 10556 links.

And another Question, README in above website about the cora dataset says that the direction of the link in the .cites file is from right to left. File `data/Cora/raw/ind.cora.graph`  is a `dict` in the format `{index: [index_of_neighbor_nodes]}.`, what the direction about it?

Waiting for your reply. Thanks~

**Comment by rusty1s** [comment]
We save each link as an undirected edge in both directions, which approximately doubles the number of edges.

**Comment by zdaiot** [comment]
Sorry to bother you again. The number of edges is reduced from 10858 to 10556 after function `coalesce` execution. But I can't imagine why duplicate edges appear in the Cora dataset. Can you give me a detailed example?

Thanks again~

**Comment by rusty1s** [comment]
Actually, I do not know why those datasets come with duplicated edges, but obviously, there are some, *e.g.* node `4` has duplicate edges to node `2176`.
