### ISSUE TITLE
How to learn edge_index?

### ISSUE THREAD

**Issue by zhongpeixiang** [rusty1s/pytorch_geometric#345]
## ❓ Questions & Help

For graphs in my research problem, the adjacency matrix is unknown, i.e., nodes are connected with different unknown strengths. How do I learn edge_index from data? Currently edge_index does not support FloatTensor. 

One possible solution I can think of is: make edge_index fully connected (all ones) and fixed, and then learn edge_weight instead. Is it the right way to go?

Thanks,
Peixiang

**Comment by rusty1s** [comment]
Hi, `edge_index` does only support gradients via their edge weights. So what you are saying is right. You can sparsify the resulting adjacency matrix using something like `topk`.

**Comment by zhongpeixiang** [comment]
@rusty1s Dynamically calculating `edge_index` is a really interesting idea. I'm wondering if there is a difference between keeping `edge_index` fixed with all ones and calculating `edge_index` using `edge_weight` and `topk` dynamically after every batch.

Essentially I'm curious that if one edge having 0 in `edge_weight` effectively indicates that whether this edge exist in the `edge_index` does not matter.

For example, Is
```
edge_index = [[0, 1, 2], [1, 2, 0]]
edge_weight = [0, 0.5, 1]
```
equivalent to
```
edge_index = [[1, 2], [2, 0]]
edge_weight = [0.5, 1]
```
?


Thanks,
Peixiang

**Comment by rusty1s** [comment]
This depends on the operator you use (and whether this operator does take edge weights into account). For `GCNConv` this should be true, given that we multiply each incoming message by `edge_weight`.

**Comment by zhongpeixiang** [comment]
@rusty1s I see, thank you!
