### ISSUE TITLE
Doubt in perm parameter of TopK pooling layer

### ISSUE THREAD

**Issue by yorard123** [rusty1s/pytorch_geometric#346]
My question is related to TopK pooling layer. I would like to know if I understood properly the return parameters, in specific the perm parameter. This parameter contains a list of the old positions of the nodes used in the new graph, isn't it?

**Comment by rusty1s** [comment]
The `perm` variable denotes the indices of the top-k scores in each example. The wording `perm` might not be the best choice here, I will change that.

**Comment by yorard123** [comment]
If I want to recover the pos of these nodes, I can do it using the `perm` variable, Am I right?

**Comment by rusty1s** [comment]
Yes.
