### ISSUE TITLE
Jumpingknowledge

### ISSUE THREAD

**Issue by tomcat123a** [rusty1s/pytorch_geometric#348]
## To Reproduce

1.
1.
1.

def __init__(self, mode, channels=None, num_layers=None):
        super(JumpingKnowledge, self).__init__()
        self.mode = mode.lower()
        assert self.mode in ['cat', 'max', 'lstm']

        if mode == 'lstm':
            assert channels is not None
            assert num_layers is not None
            self.lstm = LSTM(
                channels,
                channels * num_layers // 2,
                bidirectional=True,
                batch_first=True)
            self.att = Linear(2 * channels * num_layers // 2, 1)

        self.reset_parameters()

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

## Additional context
In the JumpingKnowledge, there is an 'channels * num_layers // 2',which will bring in bugs when both channels and num_layers are odd numbers.

**Comment by rusty1s** [comment]
Fixed in master. Thank you.
