### ISSUE TITLE
add_remaining_self_loops with no loop weights provided

### ISSUE THREAD

**Issue by mrmotallebi** [rusty1s/pytorch_geometric#349]
## 🐛 Bug

L110 of loop.py
```
        loop_weight[row[inv_mask]] = edge_weight[inv_mask].view(-1)
```

When edge_weights and no loops are not provided, row[inv_mask] and edge_weight[inv_mask] become tensor([], device='cuda:0', dtype=torch.uint8) causing it to throw error:

> IndexError: The shape of the mask [0] at index 0 does not match the shape of the indexed tensor [XXX] at index 0

## To Reproduce

1. Create a Dataset with x, y and edge_index initialized (without any loops and edge weights)
2. Pass Data object to GCNConv
3. Get error 

> ~/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
>      87         if not self.cached or self.cached_result is None:
>      88             edge_index, norm = self.norm(edge_index, x.size(0), edge_weight,
> ---> 89                                          self.improved, x.dtype)
>      90             self.cached_result = edge_index, norm
>      91         edge_index, norm = self.cached_result
> 
> ~/torch_geometric/nn/conv/gcn_conv.py in norm(edge_index, num_nodes, edge_weight, improved, dtype)
>      72         fill_value = 1 if not improved else 2
>      73         edge_index, edge_weight = add_remaining_self_loops(
> ---> 74             edge_index, edge_weight, fill_value, num_nodes)
>      75 
>      76         row, col = edge_index
> 
> ~/torch_geometric/utils/loop.py in add_remaining_self_loops(edge_index, edge_weight, fill_value, num_nodes)
>     113         print('loop weight size is ', loop_weight.size())
>     114         print('edge_weight[inv_mask]', edge_weight[inv_mask].view(-1))
> --> 115         loop_weight[row[inv_mask]] = edge_weight[inv_mask].view(-1)
>     116         edge_weight = torch.cat([edge_weight[mask], loop_weight], dim=0)
>     117 
> 
> IndexError: The shape of the mask [0] at index 0 does not match the shape of the indexed tensor [390] at index 0
> 

## Expected behavior

If edge_weight[inv_mask] is empty it should skip.

## Environment

* OS: Ubuntu 18.04
* Python version: 3.6
* PyTorch version: 1.1
* CUDA/cuDNN version: CUDA 9
* GCC version: unknown
* Any other relevant information: version 1.2.1

**Comment by mrmotallebi** [comment]
Also, L115 of loop.py
```
                              dtype=torch.long,
```
wouldn't it better to be `dtype=edge_index.dtype` ?
Seems like you have uint8 as index type in other places?

**Comment by rusty1s** [comment]
Hi, yes I can fix this. I find it however weird that my PyTorch can handle those cases successfully by returning an empty tensor.

**Comment by rusty1s** [comment]
Does this code snippet work for you?
```python
import torch
x = torch.randn(100)
mask = torch.zeros(100, dtype=torch.uint8)
x[mask]
```

**Comment by rusty1s** [comment]
Nevermind, you are absolutely right. Fixed in master and included an additional test. Thank you!

**Comment by mrmotallebi** [comment]
Thank you~
