### ISSUE TITLE
Typo in Data.is_directed?

### ISSUE THREAD

**Issue by AntoinePrv** [rusty1s/pytorch_geometric#35]
Hello,

Shouldn't the code for `Data.is_directed` [line](https://github.com/rusty1s/pytorch_geometric/blob/8d458908ccfd2429dd13df6c236aa75d8e25282c/torch_geometric/data/data.py#L93) be:
```python
 return not self.is_undirected()
```
Given that `is_undirected` is not a property:
```python
def is_undirected(self):
    return is_undirected(self.edge_index, self.num_nodes)

def is_directed(self):
    return not self.is_undirected
```

**Comment by rusty1s** [comment]
Thanks a lot. Fixed in master.
