### ISSUE TITLE
A little confusion about torch_geometric.transforms example on ShapeNet

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#358]
## ❓ Questions 

Hello, I tried your example code on data transforms on ShapeNet dataset. 

In your example, the code is:
```python
import torch_geometric.transforms as T
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', category='Airplane',
                    pre_transform=T.KNNGraph(k=6))

data[0]
>>> Data(edge_index=[2, 17768], pos=[2518, 3], y=[2518])
```

First, data[0] should be dataset[0]?
Second, there is a little difference with your code result. Here is my code.

```python
import torch_geometric.datasets as gdatasets
import torch_geometric.transforms as gtransforms
# my transform
my_transform = gtransforms.KNNGraph(k=6)
# import ShapeNet dataset. I have processed all 16 categories before. with no transforms. 
dataset = gdataset.ShapeNet(root='./ShapeNet/', category='Airplane', transform=my_transform)

dataset[0]
>>> Data(edge_index=[2, 15108], pos=[2518, 3], y=[2518])
```

The only difference between [the example code's result](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#data-transforms) and my code's result is edge_index. Example is 17768, while mine is 15108.

I do not know why this happen. And i don't know if this difference affect something. 

My environments are listed as below:

Operating System: Ubuntu 16.04.4 LTS
Python: 3.7.3
pytorch: 1.1.0
pytorch_geometric: 1.2.1
numpy: 1.16.3

Yours,
MingFei.

**Comment by rusty1s** [comment]
Your results are correct. I will update the doc. Sorry for the inconveniences.

**Comment by WMF1997** [comment]
thank you very much~
