### ISSUE TITLE
can not install torch-scatter on win10 cuda10.0 pytorch1.1.0

### ISSUE THREAD

**Issue by Mario-Liu** [rusty1s/pytorch_geometric#362]
## Environment

* OS:win10
* Python version:3.7
* PyTorch version:pytorch1.1.0
* CUDA/cuDNN version:cuda 10.0
* GCC version:
* How you tried to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

`(torchgeometric) C:\Users\lzt>python -c "import torch; print(torch.__version__)"
1.1.0

(torchgeometric) C:\Users\lzt>python -c "import torch; print(torch.cuda.is_available())"
True

(torchgeometric) C:\Users\lzt>python -c "import torch; print(torch.version.cuda)"
10.0

(torchgeometric) C:\Users\lzt>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

`

## Checklist

- [yes]  I followed the installation guide.
- [ no] I cannot find my error message in the FAQ.
- [no ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [no ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context
There is a similar question in FAQ:
4 error: command '/usr/bin/nvcc' failed with exit status 2: Ensure that at least CUDA >= 8 is installed (see Issue#25a and Issue#106).
AND I check Issue#25a and Issue#106 and make sure CUDA >8,but it still cant help

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe -c cuda/scatter_kernel.cu -o build\temp.win-amd64-3.6\Release\cuda/scatter_kernel.obj -Xcompiler /wd4819 -Xcompiler /MD -Id:\anaconda\lib\site-packages\torch\include -Id:\anaconda\lib\site-packages\torch\include\torch\csrc\api\include -Id:\anaconda\lib\site-packages\torch\include\TH -Id:\anaconda\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -Id:\anaconda\include -Id:\anaconda\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0

**error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2**
----------------------------------------

ERROR: Command "'d:\anaconda\python.exe' -u -c 'import setuptools, tokenize;file='"'"'C:\Users\lzt\AppData\Local\Temp\pip-install-zmhx_cj7\torch-scatter\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\lzt\AppData\Local\Temp\pip-record-wou7zo1z\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\lzt\AppData\Local\Temp\pip-install-zmhx_cj7\torch-scatter`

**Comment by rusty1s** [comment]
Hi, does `nvcc` output any kind of error message/log to help identify the error?

**Comment by Mario-Liu** [comment]
> 
> 
> Hi, does `nvcc` output any kind of error message/log to help identify the error?

Maybe I solved this problem by deleting and reinstall but right now I got another problem:

`(torchgeometric) E:\competition\torchgcnopv\pytorch_scatter>python setup.py install
running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info\PKG-INFO
writing dependency_links to torch_scatter.egg-info\dependency_links.txt
writing top-level names to torch_scatter.egg-info\top_level.txt
reading manifest file 'torch_scatter.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\Anaconda\envs\torchgeometric\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'torch_scatter.scatter_cuda' extension
D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\THC -ID:\cuda\include -ID:\Anaconda\envs\torchgeometric\include -ID:\Anaconda\envs\torchgeometric\include /EHsc /Tpcuda/scatter.cpp /Fobuild\temp.win-amd64-3.7\Release\cuda/scatter.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /MD
scatter.cpp
D:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打开包括文件: “cstddef”: No such file or directory
error: command 'D:\\MicrosoftVisualStudio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2`

There are many similar problems online and in the pytorch_geometric Issue,but none of them really solved  my new problem.

Here are the cl.exe pathes of VS 2017 because there are actually 4 cl.exe in the symstem
D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64
D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86
D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x64
D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86

Could you please help me get through this...
Much thanks!

**Comment by rusty1s** [comment]
Mh, this seems to be the problem: `“cstddef”: No such file or directory error`. Maybe it helps to add something like `extra_compile_args=["-g", "-stdlib=libc++", "-std=c++11"]` to the compile args (see [here](https://github.com/Roger-luo/pytorch-complex/issues/5)).

**Comment by Mario-Liu** [comment]
> 
> 
> Mh, this seems to be the problem: `“cstddef”: No such file or directory error`. Maybe it helps to add something like `extra_compile_args=["-g", "-stdlib=libc++", "-std=c++11"]` to the compile args (see [here](https://github.com/Roger-luo/pytorch-complex/issues/5)).

I tried extra_compile_args=["-g", "-stdlib=libc++", "-std=c++11"] , extra_compile_args=["-g"] as the post said,but nothing worked;

can **cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error)) building 'torch_scatter.scatter_cuda' extension** be the problem? 

please help me to fix this. Much thanks.

`(torchgeometric) E:\competition\torchgcnopv\pytorch_scatter>python setup.py install running install running bdist_egg running egg_info writing torch_scatter.egg-info\PKG-INFO writing dependency_links to torch_scatter.egg-info\dependency_links.txt writing top-level names to torch_scatter.egg-info\top_level.txt reading manifest file 'torch_scatter.egg-info\SOURCES.txt' reading manifest template 'MANIFEST.in' writing manifest file 'torch_scatter.egg-info\SOURCES.txt' installing library code to build\bdist.win-amd64\egg running install_lib running build_py running build_ext D:\Anaconda\envs\torchgeometric\lib\site-packages\torch\utils\**cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error)) building 'torch_scatter.scatter_cuda' extension** D:\MicrosoftVisualStudio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\TH -ID:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\THC -ID:\cuda\include -ID:\Anaconda\envs\torchgeometric\include -ID:\Anaconda\envs\torchgeometric\include /EHsc /Tpcuda/scatter.cpp /Fobuild\temp.win-amd64-3.7\Release\cuda/scatter.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /MD scatter.cpp D:\Anaconda\envs\torchgeometric\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打开包括文件: “cstddef”: No such file or directory error: command 'D:\\MicrosoftVisualStudio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2`

**Comment by rusty1s** [comment]
What did you change and where?

**Comment by Mario-Liu** [comment]
> 
> 
> What did you change and where, because there is no flag `-stdlib=libc++` in your log.

Haha，Thats the problem. I reinstalled the VS 2017 in higher version and checked more workload that may  related to the installation. Now evertything works fine on my computer.

**Comment by rusty1s** [comment]
Cool :)
