### ISSUE TITLE
Requesting an implementation of Line Graph Neural Networks

### ISSUE THREAD

**Issue by zhengdao-chen** [rusty1s/pytorch_geometric#365]
## 🚀 Feature

In the paper "Supervised community detection with line graph neural networks" (https://openreview.net/forum?id=H1g0Z3A9Fm), published at ICLR 2019, GNNs are adapted to solve community detection in a supervised learning setting. In particular, the Line Graph Neural Network (LGNN) is proposed, which operates simultaneously on both the original graph and its line graph defined via the non-backtracking matrix. It achieves success in synthetic and real-world datasets. It has been implemented in PyTorch, and the code can be found here: https://github.com/zhengdao-chen/GNN4CD. There is also a version implemented by the Deep Graph Library team, which can be found at https://docs.dgl.ai/en/latest/tutorials/models/1_gnn/6_line_graph.html.

## Motivation

For solving community detection in a supervised learning setting

**Comment by rusty1s** [comment]
Thank you for the reminder :)

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_geometric/issues/431
