### ISSUE TITLE
torch.multiprocessing cannot pickle local object DataLoader (pointnet segmentation example)

### ISSUE THREAD

**Issue by chriss2401** [rusty1s/pytorch_geometric#366]
## 🐛 Bug

Hi, when trying to run the pointnet++ example on segmentation, I get the following error in utils/data/dataloader.py:

> File "pointnet2_segmentation.py", line 127, in <module>
    train()
  File "pointnet2_segmentation.py", line 91, in train
    for i, data in enumerate(train_loader):
  File "C:\Users\Apostolopoulos\Envs\pointnetplusplus\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Apostolopoulos\Envs\pointnetplusplus\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "c:\users\apostolopoulos\appdata\local\continuum\anaconda3\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\users\apostolopoulos\appdata\local\continuum\anaconda3\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\apostolopoulos\appdata\local\continuum\anaconda3\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\apostolopoulos\appdata\local\continuum\anaconda3\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\apostolopoulos\appdata\local\continuum\anaconda3\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DataLoader.__init__.<locals>.<lambda>'

Anyone had similar issues ? read pickle cant pickle lambda functions but I wonder why the default implementation of pytorch is made this way ?

## Environment

* OS: Windows
* Python version: 3.6
* PyTorch version: 1.1
* CUDA/cuDNN version: 10

**Comment by rusty1s** [comment]
It seems like you do need to set `num_workers=0` on Windows due to missing multiprocessing support. Can you please try this?

**Comment by chriss2401** [comment]
It was that, thank you @rusty1s for the quick reply !

**Comment by blueloveTH** [comment]
I have the same issue. In my case, without multiprocessing the training speed would be much lower. Hope you can fix it.

**Comment by rusty1s** [comment]
There's sadly nothing for me to fix since this is a PyTorch issue.

**Comment by pythlang** [comment]
Simply setting `num_workers=0` solved for me on Mac Big Sur using PyTorch as well. Not sure why since a check occurs for GPU, which I'm not using, and just thought I would mention it before continuing to train my model @rusty1s

**Comment by MichaelSchroter** [comment]
> It seems like you do need to set `num_workers=0` on Windows due to missing multiprocessing support. Can you please try this?
Hi,

What about for MacOS please?
Thanks & Best Regards
Schroter Michael

**Comment by rusty1s** [comment]
I think `num_workers>0` on macOS should work just fine. Let me know.

**Comment by chengengliu** [comment]
Hi, I'm wondering if there is a fix on the multiprocessing issue? I'm using Pytorch1.12, Windows.

**Comment by rusty1s** [comment]
Is this PyG related? Does `num_workers>0` work for other data loaders on Windows?

**Comment by chengengliu** [comment]
> 

Thank you for the reply! I'm sorry that I didn't notice this is a PyG repo. I have fixed it(it's something on my dataset issue).

**Comment by chengengliu** [comment]
> Is this PyG related? Does `num_workers>0` work for other data loaders on Windows?

Thank you for the reply @rusty1s ! I'm sorry that I didn't notice this is a PyG repo. I have fixed it(it's something on my dataset issue).
