### ISSUE TITLE
a little bug in ./torch_geometric/utils/num_nodes.py

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#369]
Hello:
I continue my journey on torch-geometric.
I manage to add self loop to KarateClub Dataset. 
Here is my code:
```python
# if pytorch is imported... i add g to distinguish them. 
import torch_geometric.datasets as gdatasets
import torch_geometric.transforms as gtransforms

zkc = gdatasets.KarateClub()
add_self_loop = gtransforms.AddSelfLoops() # a transform here.
# return z_data_ may be meaningless... 
z_data_ = add_self_loop(zkc.data)

```
it raises error as below:
```
TypeError: arange() received an invalid combination of arguments - got (int, Tensor), but expected one of:
 * (Number end, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
I find out the reason.

In ./torch_geometric/utils/num_nodes.py

previous code:
```python
def maybe_num_nodes(index, num_nodes=None):
    return index.max().item() + 1 if num_nodes is None else num_nodes
```

my code: 
```python
def maybe_num_nodes(index, num_nodes=None):
    # NOTE(WMF): I find out a problem here, 
    # index.max().item() -> int
    # num_nodes -> tensor
    # need type conversion.
    # return index.max().item() + 1 if num_nodes is None else num_nodes
    return index.max().item() + 1 if num_nodes is None else int(num_nodes)
```
since num_nodes only contains 1 number, i just write a type conversion here. 

P.S.
1. there is still a little ??problem?? [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/introduction.html#data-transforms).
```python
from torch_geometric.datasets import ShapeNet

dataset = ShapeNet(root='/tmp/ShapeNet', category='Airplane')

data[0]
>>> Data(pos=[2518, 3], y=[2518])
```
you still leave ```data[0]```, in fact, i think it is```dataset[0]```. i have thought you changed this...

2. I am really a greenhorn in gnn... I really like this python library, and I want to make contributions to this useful tool. I am a chinese, my english might be a little poor...

yours, 
wmf1997

**Comment by rusty1s** [comment]
1. You need to access the data by `zkc[0]`, `zkc.data` is just an internal storage format which cannot be transformed.
2. I only changed `dataset[0]` in one place and missed the others. Fixed in master.
3. Sure, any contributions are welcome. Don't worry about your english. In the end, we are just writing code :)

**Comment by WMF1997** [comment]
thank you very much~

**Comment by Whadup** [comment]
shouldn't this be

    def maybe_num_nodes(index, num_nodes=None):
        return (index.max().item() + 1) if num_nodes is None else num_nodes

otherwise if `index` is empty this crashes as `max()` on empty tensors is not defined
