### ISSUE TITLE
ps:Memory efficient version of DenseSageConv

### ISSUE THREAD

**Issue by tomcat123a** [rusty1s/pytorch_geometric#374]
## 🚀 Feature

DenseSage accepts adj,which is a B times N times N tensor contains B adjacency matrices. In most application cases, there are identical B adjacency matrices for a batch of sample.Will there be a mechanism to reuse the COMMONLY SHARED adjacency matrix for different samples?

**Comment by rusty1s** [comment]
As far as I know, you can achieve this by making use of broadcasting and inputing a [1,N,N] matrix into the forward pass.

**Comment by rusty1s** [comment]
I added tests both for [`DenseSAGEConv`](https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/dense/test_dense_sage_conv.py#L44-L57) and [`DenseGinConv`](https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/dense/test_dense_gin_conv.py#L48-L62). This already works :)

**Comment by tomcat123a** [comment]
The issue is a bug of PyTorch not Torch_geometric.
[https://github.com/pytorch/pytorch/issues/18862](url)

**Comment by rusty1s** [comment]
How is this issue related to the problem described above?
