### ISSUE TITLE
Need to define data.num_nodes field when creating new datasets, but its not a necessary field in Data

### ISSUE THREAD

**Issue by victor000000** [rusty1s/pytorch_geometric#378]
when creating my own dataset, a error occurs:

![Annotation 2019-06-05 201031](https://user-images.githubusercontent.com/1636580/58955248-08abcb80-87ce-11e9-94f3-62c2a44a3259.png)

the reason why this occurs is that I didn't define the num_nodes field for the torch_geometric.data.Data instance

but in the __init__ function of Data class, 
/torch_geometric/data/data.py line 57
there seems no need to define the num_nodes field, or any key words like num_nodes=None

I think we have to define num_nodes explicitly by using something like:
data = Data(
  x=colors, y=gt_labels, pos=points_raw,
  cubics_ids=raw_data.cubics_ids,   # user defined field
  shift=shift,  # user defined field
  num_nodes=None  # or num_nodes=points_raw.shape[0]
)
when we create our own dataset.

maybe its related to #190

**Comment by rusty1s** [comment]
You do not need to define `num_nodes` if the number of nodes can be automatically inferred by PyG, *e.g.*, when having a node feature matrix (basically whenever there is no warning). I am not sure however why there is an error. Therefore, you should remove the `num_nodes` attribute in the initializer of your `Data`. In addition, do you use anything other than `torch.tensor` as an attribute in your `data` object?

**Comment by victor000000** [comment]
Thx, that's the problem, 
I use numpy as an attribute in data object,
it raise a ValueError when I define the num_nodes,

I need to use torch.tensor as an attribute in my data object
