### ISSUE TITLE
find a bug in autoencoder.py

### ISSUE THREAD

**Issue by w21180239** [rusty1s/pytorch_geometric#381]
## To Reproduce

1.normally initialize the ARGA class then will crash like follow

```
Traceback (most recent call last):
  File "C:\Users\wardliu\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\torch_geometric\nn\models\autoencoder.py", line 268, in __init__
    self.discriminator = discriminator
  File "C:\Users\wardliu\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 565, in __setattr__
    "cannot assign module before Module.__init__() call")
AttributeError: cannot assign module before Module.__init__() call
```
2. simply change the order of two lines will meet a new crash like follow 
`File "C:\Users\wardliu\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\torch_geometric\nn\models\autoencoder.py", line 268, in __init__
    self.discriminator = discriminator
  File "C:\Users\wardliu\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 565, in __setattr__
    "cannot assign module before Module.__init__() call")
AttributeError: cannot assign module before Module.__init__() call`

## Expected behavior
The bug is cauesed by assign discriminator before super(ARGA, self).__init__(encoder, decoder) is called, and it could be fix bt changing the code of ARGA. __init__() into 
`    def __init__(self, encoder, discriminator, decoder=None):
        self.discriminator = discriminator
        super(ARGA, self).__init__(encoder, decoder)
reset(self.discriminator)`

also change the code of autoencoder.py -87 into `GAE.reset_parameters(self)`

## Environment

* OS: Win10
* Python version: 3.6
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 10.0
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Cool! Fixed in master.
