### ISSUE TITLE
Semantically correct for changing self.flow in one propagation calculation?

### ISSUE THREAD

**Issue by RuihongQiu** [rusty1s/pytorch_geometric#382]
## ❓ Questions & Help

Hello!

I am working on a directed graph. If I use the default settings of a `Message Passing` network, the aggregation of neighbors will be just `source_to_target` or `target_to_source`. If I want to calculate both flows, i.e., neighbors of a node `i` consists of not only nodes to `i` but also nodes from `i`, how should I implement it?

Take this graph as an example,
![image](https://user-images.githubusercontent.com/17882988/59011578-7b718100-8878-11e9-9764-477aa0e8511a.png)
For the default setting as `source_to_target`, the neighbors of node `v_2` will be just `v_1` and `v_3` (source neighbors). If I think the `target` from `v_2` is also useful, I want the neighbors of `v_2` to include `v_4` and `v_3` (target neighbors) as well. In addition, the feature space of these two kinds of neighbors are different, so that there are two sets of weights to map them into the same feature space.

I try to implement inside the `GatedGraphConv` as following and could you please help me to check if this makes sense?
```python
def forward(self, x, edge_index, edge_weight):
    ...
    self.flow = 'source_to_target'
    h1 = torch.matmul(h, self.weight[i, 0])
    m1 = self.propagate(edge_index, x=h1, edge_weight=edge_weight)
    self.flow = 'target_to_source'
    h2 = torch.matmul(h, self.weight[i, 1])
    m2 = self.propagate(edge_index, x=h2, edge_weight=edge_weight)
    h = self.rnn(torch.cat((m1, m2), dim=-1), h)
```

**Comment by rusty1s** [comment]
Yes, you can simply change the `flow` direction and propagate two times :)

**Comment by RuihongQiu** [comment]
Thanks! Because of the `scatter` function, will `m1` and `m2` already be aligned (the same index of the list points to the same center node) to concatenate or add or multiply together?

**Comment by rusty1s** [comment]
Yes, node ordering will stay the same.

**Comment by RuihongQiu** [comment]
Fantastic design for the `PyTorch_scatter`.
