### ISSUE TITLE
Why is the number of edge_index abnormal?

### ISSUE THREAD

**Issue by PerfectVeo** [rusty1s/pytorch_geometric#383]
## ❓ Questions & Help

Hi
I am using your framework, but I found that the value of edge_index in data is abnormal. For example, the edge_index in the Cora dataset should be 5429, but it is actually 10556, and they are not twice as large.
I don't know why?
Thank you very much

**Comment by rusty1s** [comment]
Hi, this is highly related to https://github.com/rusty1s/pytorch_geometric/issues/343.
