### ISSUE TITLE
Classifying nodes and edges of a graph simultaneously

### ISSUE THREAD

**Issue by nitinkgp23** [rusty1s/pytorch_geometric#387]
## ❓ Questions & Help

I have a graph, which has features on both nodes and edges. I need to classify these nodes into different classes (~6 classes) and the edges into 2 classes. I need to do the classification for both simultaneously.

Currently, I am able to classify the nodes using standard models, and edges - by transforming it into line graph, and consequently classifying the nodes (which were previously edges). But, these are currently independent, and I want to do this simultaneously. 

Is there any way to do this via PyG?

**Comment by rusty1s** [comment]
What do you mean by simultaneously? Processing both graphs in one forward pass or predicting both targets from one graph? The first one is trivial, and for the second one, I suggest simply using an edge-conditioned convolution operator like `NNConv`, update node features based on this convolution and update edge features via something like:
```python
x = self.conv(x, edge_index, edge_attr)
row, col = edge_index
edge_attr = self.mlp(torch.cat([x[row], x[col], edge_attr], dim=1))
```

**Comment by nitinkgp23** [comment]
Thanks for the quick response.
By simultaneously, I mean, predicting both nodes and edges from 1 graph.

**Comment by rusty1s** [comment]
Then you should go for the second one :)
