### ISSUE TITLE
Improve documentation of 'nn' argument in NNConv

### ISSUE THREAD

**Issue by MilkshakeForReal** [rusty1s/pytorch_geometric#389]
## ❓ Questions & Help

I know nn is MLP it seems that I need to define nn by myself. My question is what are the input and output channels of nn?

I have tried to set the input channels to edge_attr.shape[1] and the output channels to in_channels * out_channels, but Nan appeared in the return value

**Comment by MilkshakeForReal** [comment]
Oops, I found that my input has Nan in it. The input and output channels is correct but I studied the source code for a long time to get it right, so I think it'd better to add a note to the document?

**Comment by rusty1s** [comment]
Well, technically nn does not have to be an MLP, but can be anything what can map the number of edge attributes to input channels times output channels. But you are right, we should make this more clear in the doc.

**Comment by rusty1s** [comment]
Done in master.
