### ISSUE TITLE
Heterogenous Graph Formation

### ISSUE THREAD

**Issue by CheriseZhu** [rusty1s/pytorch_geometric#39]
It's a brilliant work! But I have a data formation problem of heterogenous graph.
I'm not sure if pytorch_geometric can support heterogenous graph data.

**Comment by rusty1s** [comment]
I do not know if I understand the question correctly, but yes, `data.edge_attr` contains the edge features for all edges in your graph. Can you explain your problem a little bit further?

**Comment by CheriseZhu** [comment]
I mean the heterogenous graph with different types of edges. So data.edge_attr can model these edges and then doing somes tasks such as edge classification. :)

**Comment by rusty1s** [comment]
Yes, this is possible. However, you need to implement your own operators since none of the already implemented methods can perform edge classification.
