### ISSUE TITLE
Question about citation datasets

### ISSUE THREAD

**Issue by Jianjin123** [rusty1s/pytorch_geometric#391]
## ❓ Questions & Help

Hello, could you please tell me where I can find the directed graphs for citation datasets (Cora, Citeseer and Pubmed)? I cannot find any directed (original) versions of them. 

Waiting for your reply. Thanks in advance.

**Comment by rusty1s** [comment]
I do not know, the official Planetoid dataset is undirected by default.

**Comment by Jianjin123** [comment]
Thans for your prompt reply.
