### ISSUE TITLE
Import error mean_iou

### ISSUE THREAD

**Issue by FraLotito** [rusty1s/pytorch_geometric#394]
Hi!

I'm trying to run the pointNet2 segmentation example but I'm facing the following error:

----> 1 from torch_geometric.utils import mean_iou
ImportError: cannot import name 'mean_iou'

How can I fix this?

Thank you!

**Comment by rusty1s** [comment]
Hi, this function is currently only available on master, so either install from source or copy paste [this function](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/metric.py#L149) to your script file.

**Comment by Shaun-Wong** [comment]
how can i solve from torch_geometric.utils import mean_iou error?

**Comment by rusty1s** [comment]
Let's discuss here: https://github.com/pyg-team/pytorch_geometric/discussions/7434
