### ISSUE TITLE
A little question about downloading datasets through TUDataset()

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#395]
## ❓ Questions & Help

hello @rusty1s :

I have downloaded some datasets via ```TUDataset(root=myroot, name=myname)``` about 2 weeks ago. 
But when I downloaded a dataset(for example, Enzymes dataset) through ```TUDataset(root=myroot, name=myname)```
to my new computers today, it cannot work. 
here is my code:
```python
from torch_geometric.datasets import TUDataset
enz = TUDatasets(root='./ENZYMES', name='ENZYMES')
```
but it raises an error: ```Certification Error```
```Certification Error: hostname 'ls11-www.cs.uni-dortmund.de' doesn't match 'ls11-www.cs.tu-dortmund.de'```
(P.S. When I am in Microsoft Windows 10, The way of installing it on Win 10 is just by chance(pip install, Visual Studio 2019 + Python 3.7))
or 
``` URLError: <urlopen error [SSL: CERTIFICATION_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ls11-www.cs.uni-dortmund.de'. (_ssl_c:1056)>```
(When I am in Ubuntu 16.04)

I don't know what is the reason for that. 

Yours, 
@wmf1997

**Comment by AnirudhDagar** [comment]
Was this fixed [here](https://github.com/rusty1s/pytorch_geometric/commit/90a06d02b79414fc48a3367c79cfb28f919d5769)?

**Comment by rusty1s** [comment]
Exactly, the easiest way for you to fix is probably to adjust the url manually.

**Comment by WMF1997** [comment]
thank you very much

**Comment by AnirudhDagar** [comment]
Btw how can I install PyG from source? Should I just run the pip install -e /path/to/myfork ??

**Comment by rusty1s** [comment]
```
python setup.py install
```
or
```
python setup.py develop
```
Inside your forked or cloned directory. You may need to install the latest version of `torch-cluster` via `pip`.

**Comment by ZdsAlpha** [comment]
Quick fix for people having this issue. Change path before downloading dataset:
`UDataset.path = 'https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets'`
Hope it works!

**Comment by rusty1s** [comment]
Thanks. I will push a new release soon. Sorry for the delay.

**Comment by materdd** [comment]
> Quick fix for people having this issue. Change path before downloading dataset:
> `UDataset.path = 'https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets'`
> Hope it works!

Thanks for your information, but a little bit mistake. Below is correct one.
Anyway, thanks.

TUDataset.url = 'https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets'
