### ISSUE TITLE
import  DynamicEdgeConv error

### ISSUE THREAD

**Issue by voidspiral** [rusty1s/pytorch_geometric#396]
I'm trying to run the dgcnn_segmentation example but I'm facing the following error:

----> 1 from torch_geometric.nn import DynamicEdgeConv
ImportError:cannot import name 'DynamicEdgeConv'

I have no  DynamicEdgeConv class in  torch_geometric/nn/conv/edge_conv.py
How can I update torch_geometric lib?

Thank you !

**Comment by rusty1s** [comment]
You can either install from source or wait until the next release (about a week).
