### ISSUE TITLE
Can GCNConv work on directed-graph？

### ISSUE THREAD

**Issue by jumormt** [rusty1s/pytorch_geometric#397]
## ❓ Questions & Help

Thanks！the paper claimed it works on undirected but possible work in directed one. Can GCNConv work on directed-graph？

**Comment by rusty1s** [comment]
Sure, you can use it for directed graphs.

**Comment by jumormt** [comment]
Many thanks.! But how do u use it for directed graphs? Limiting to directed graph is one of the limitation of this paper. https://arxiv.org/pdf/1609.02907.pdf   u can see it at the second in 7.2

**Comment by rusty1s** [comment]
I mean implementation-wise there is no limitation to not use it for directed graphs. Although there are theoretical implications, IMO `GCNConv` should just work fine for directed graphs. In the end, it just performs a normalized spatial aggregation. You could run the `SAGEConv` alternatively and compare the peformance of both operators for directed graphs.

**Comment by jumormt** [comment]
The implementation work is splendid and thanks for your contribution! Do you mean that `[SAGEConv](https://arxiv.org/pdf/1706.02216.pdf)` shows no limitation on directed-G?  In the conclusion part, it says " A number of extensions and potential improvements are possible, such as extending GraphSAGE to incorporate directed or multi-modal graphs. ". I guess it does not support directed-G. Take a look at [MOTIFNET](https://arxiv.org/pdf/1802.01572.pdf) at your convenience. It says " One of the key drawback of spectral CNNs is their explicit assumption of an undirected graph, leading to a symmetric Laplacian matrix with orthogonal eigendecomposition.". I guess there is a difference in handling undirected and directed graph. Thanks again for your attention!

**Comment by rusty1s** [comment]
> One of the key drawback of spectral CNNs is their explicit assumption of an undirected graph, leading to a symmetric Laplacian matrix with orthogonal eigendecomposition.

Yes, this is the case for spectral methods, but please note that there are no such limitations for spatial methods (like `SAGEConv`). There may be a difference in handling undirected and directed graph, *e.g.* you may take both in- and out- edges into account (and weight them separately), but spatial aggregation methods that follow the definition of message passing do not have any limitations per se being applied to directed graphs.

**Comment by jumormt** [comment]
Thanks! As you said, experiments show that `GCNConv` just works fine for directed graphs!

**Comment by Laknath1996** [comment]
Can GCNConv layer handle weighted directed graphs? When I pass my graph data through the GCNConv layer the output become "nan" after one or two iterations.

**Comment by rusty1s** [comment]
The `GCNConv` layer can handle weighted directed graphs, but edge weights need to be positive due to the `pow(-0.5)` call.

**Comment by Laknath1996** [comment]
Thank you very much @rusty1s for the quick reply. I guess my problem was having negative weights in the Adjacency matrices. Would I be giving up information in the Adj matrix if I rescale the values within [0, 1]? That would solve the negative weight problem, but I wonder whether it would affect the structure of the adj matrices..

**Comment by rusty1s** [comment]
In general, this should work just fine, but it depends on what you are trying to do. If you think of negative edge weights as a way to "subtract information" during message passing, then you are better of using something like `GrapConv`, which supports negative edge weights by default. If (negative) edge weights just denote the relative amount of information a node should receive, then scaling the weights should work best.

**Comment by Laknath1996** [comment]
Thanks a lot @rusty1s ! I'll check out ```GrapConv```  to see whether it fits the problem I'm working on.
