### ISSUE TITLE
Set global data attribute for the whole dataset

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#398]
If all the graphs in the dataset share some global attribute, assuming it as global_edge_index, how can we set it along with train_dataset/test_dataset only once, and put it into the DataLoader?

**Comment by rusty1s** [comment]
You can simply set/load your data as additional attribute of your dataset, *e.g.*:
```python
dataset.edge_index = torch.tensor([...])
```
You can then pass this attribute to your data by using, *e.g.*, custom transforms.

**Comment by sw-gong** [comment]
> You can simply set/load your data as additional attribute of your dataset, _e.g._:
> 
> ```python
> dataset.edge_index = torch.tensor([...])
> ```
> 
> You can then pass this attribute to your data by using, _e.g._, custom transforms.

Could you please write a mini example about how to do this without saving duplicated edge_index?

**Comment by rusty1s** [comment]
```python
MyTransform(object):
    def __init__(self, edge_index):
        self.edge_index = edge_index
    def __call__(self, data):
        data.edge_index = edge_index
        return edge_index

transform = MyTransform(dataset.edge_index)
dataset.transform = transform
```
should do the trick

**Comment by sw-gong** [comment]
Is this measure different than simply saving edge_index in each data? In both ways, data looks like the same way, `Data(edge_index=[2, 29990], x=[5023, 3], y=[1])`.

**Comment by rusty1s** [comment]
Well, by using transforms the data is not copied.

**Comment by sw-gong** [comment]
I see. Thanks.

**Comment by sw-gong** [comment]
> Well, by using transforms the data is not copied.

Do you know why it is still consumed the higher time?

`Batch(batch=[160736], edge_index=[2, 959680], x=[160736, 3], y=[32])` (edge_index is obtained by transform method)
`Batch(batch=[160736], x=[160736, 3], y=[32])` (no edge_index, but I used a variable global_edge_index, and send this to the device so don't need to send it to device at each iteration)

**Comment by rusty1s** [comment]
Sure. The `edge_index` still gets created for each batch individually. If you do not want this, set `drop_last=True` in the DataLoader and create a batched `edge_index` on your own, *e.g.*:
```python
edge_indices = []
cum_num_nodes = 0
for _ in range(batch_size):
    edge_indices.append(edge_index + cum_num_nodes)
    cum_num_nodes += num_nodes
edge_index = torch.cat(edge_indices, dim=1)
```

**Comment by sw-gong** [comment]
> Sure. The `edge_index` still gets created for each batch individually. If you do not want this, set `drop_last=True` in the DataLoader and create a batched `edge_index` on your own, _e.g._:
> 
> ```python
> edge_indices = []
> cum_num_nodes = 0
> for _ in range(batch_size):
>     edge_indices.append(edge_index + cum_num_nodes)
>     cum_num_nodes += num_nodes
> edge_index = torch.cat(edge_indices, dim=1)
> ```

I see. This is what I exactly have done on my work, i.e.., create a batched `edge_index` and drop the last incomplete batch. Thank you all the same.
