### ISSUE TITLE
Can't call torch_geometric.utils directly

### ISSUE THREAD

**Issue by yutaizhou** [rusty1s/pytorch_geometric#402]
## ❓ Questions & Help

Hello,

When I **import torch_geometric**, I can't do **torch_geometric.utils** directly. It raises _module 'torch_geometric' has no attribute 'utils'_ error.  However, if I do something like **from torch_geometric.utils import from_networkx**, **torch_geometric.utils** is perfectly valid. 

Is this an intended behavior? I feel like a user should be able to call **torch_geometric.utils** by just importing the base library.

**Comment by rusty1s** [comment]
No, it's not. Fixed in master. Thank you :)
