### ISSUE TITLE
SGConv fails on graphs with many features

### ISSUE THREAD

**Issue by dfdazac** [rusty1s/pytorch_geometric#404]
## 🐛 Bug

The SGConv layer works fine for datasets like Cora, but for datasets like Coauthor CS, it runs out of memory.

## To Reproduce

The following script runs out of memory on a NVIDIA Titan X, when doing the forward pass with the Coauthor CS dataset.

```python
from torch_geometric.datasets import Coauthor, Planetoid
from torch_geometric.nn import SGConv
import torch


def test_forward(data):
    data.to(device)
    layer = SGConv(data.num_features, out_channels=128, K=2).to(device)
    out = layer(data.x, data.edge_index)
    return out


device = torch.device('cuda')

# Works fine
print('Testing SGConv with Cora...')
data = Planetoid('datasets/cora', 'Cora')[0]
test_forward(data)

# Throws out of memory error
print('Testing SGConv with CoauthorCS...')
data = Coauthor('datasets/coauthorcs', 'CS')[0]
test_forward(data)
```

## Environment

* OS: Linux Mint 18.1 Serena
* Python version: 3.7
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 9.0.176
* GCC version: 5.4.0

## Additional context

I believe the problem stems from how the forward pass is done in the SGConv layer: we first do K-message passes with the feature matrix X and then pass the result through the linear layer. This works well if the feature matrix X is small, like in Cora, where nodes have ~1,400 features. However, Coauthor CS and Physics have more than 6,000 features, so the message passing is more intensive. This is not a problem in layers like GCNConv because there we multiply by the weight matrix first, which reduces the dimension, before doing the message passing.

In order to get it to work, I'm using a modified version that first passes X through the linear layer, thereby reducing the dimension of the features, which is equivalent in terms of the SGC formulation:

```python
class SGConv(MessagePassing):
    ...
    def forward(self, x, edge_index, edge_weight=None):
        """"""
        x = self.lin(x)
        edge_index, norm = GCNConv.norm(edge_index, x.size(0), edge_weight,
                                        dtype=x.dtype)

        for k in range(self.K):
            x = self.propagate(edge_index, x=x, norm=norm)

        return x
```

**Comment by rusty1s** [comment]
Hi, I'm not sure how to fix it, although it might be possible to outsource the propagation to the CPU. You lose out on the caching behavior of `SGConv` in your case.

**Comment by dfdazac** [comment]
I think doing the propagation on the CPU could be an option as a preprocessing step, maybe doing something like this?

```python
device = torch.device('cuda')

# Preprocessing
layer = SGConv(...)
x_prop = layer.propagate(data.edge_index, data.x)

# During training
x_prop.to(device)
layer.to(device)
layer.cached_result = x_prop
out = layer(data.edge_index, data.x)
```

Although it feels a bit cumbersome and we'd be using `propagate` in one part of the code and then later the forward function...

What do you think about using the `cached` flag so that when it is False, the pass through the linear layer is computed first? This way, for larger graphs all people would have to do is set `cached=False`:

```python
class SGConv(MessagePassing):
    ...
    def forward(self, x, edge_index, edge_weight=None):
        """"""
        if not self.cached:
            x = self.lin(x)
    
        if not self.cached or self.cached_result is None:
            edge_index, norm = GCNConv.norm(
                edge_index, x.size(0), edge_weight, dtype=x.dtype)
    
            for k in range(self.K):
                x = self.propagate(edge_index, x=x, norm=norm)
            self.cached_result = x
    
        return self.lin(self.cached_result) if self.cached else x
```

**Comment by rusty1s** [comment]
Fixed in master :)
