### ISSUE TITLE
failed to reduce memory cost by using Dataloader

### ISSUE THREAD

**Issue by w21180239** [rusty1s/pytorch_geometric#406]
## ❓ Questions & Help

I have a big graph whose x is (153364,67) and I create dataset like this
```
class MyOwnDataset(Dataset):
    def __init__(self, root='./', transform=None, pre_transform=None):
        super(MyOwnDataset, self).__init__(root, transform, pre_transform)

    @property
    def raw_file_names(self):
        return ['some_file_1', 'some_file_2']

    @property
    def processed_file_names(self):
        return ['data.npz']

    def __len__(self):
        return len(self.processed_file_names)


    def _download(self):
        pass

    def _process(self):
        pass

    def get(self, idx=None):
        data = torch.load('data.npz')
        return data
```
and use dataloader like this:
`loader = DataLoader([data],batch_size=16)`.

 But when I come to the code:
```
        for batch in loader:
            optimizer.zero_grad()
            batch = batch.to(dev)
            loss = loss_op(model(batch.x, batch.train_edge_index)[batch.train_mask], batch.y[batch.train_mask])
            loss.backward()
            optimizer.step()
```

`batch.x ` is still (153364,67) and caused the OOM error, I'm very confused with this bug and looking forward to your reply.

**Comment by rusty1s** [comment]
The `DataLoader` is used to load mini-batches of graphs. You are looking for the [NeighborSampler API](https://rusty1s.github.io/pytorch_geometric/build/html/modules/data.html?highlight=neighborsa#torch_geometric.data.NeighborSampler) ([here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py) is an example on how to use, a tutorial will follow). You need to install PyG from source though.

**Comment by w21180239** [comment]
> The `DataLoader` is used to load mini-batches of graphs. You are looking for the [NeighborSampler API](https://rusty1s.github.io/pytorch_geometric/build/html/modules/data.html?highlight=neighborsa#torch_geometric.data.NeighborSampler) ([here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py) is an example on how to use, a tutorial will follow). You need to install PyG from source though.

thanks to your reply, but I realized that the SAGEConv in reddit.py is different from SAGEConv from torch_geometric.nn and If I replace the SAGEConv with the SAGEConv from torch_geometric.nn or just don't provide` size` parameter will cause error

In fact, the SAGECons  from torch_geometric.nn don't have parameter `size` , also do not use the method `propogate`.

How can I fix this

**Comment by rusty1s** [comment]
Yes, you are right. We still need to convert some existing operators to be able to automatically support bipartite graph message passing (this is why we reimplement `SAGEConv` in the example). You can simply use the `SAGEConv` operator defined in the example.

**Comment by w21180239** [comment]
Awesome! You really are the most enthusiastic man I have ever seen in github.

**Comment by w21180239** [comment]
> Yes, you are right. We still need to convert some existing operators to be able to automatically support bipartite graph message passing (this is why we reimplement `SAGEConv` in the example). You can simply use the `SAGEConv` operator defined in the example.
> 
> **Edit:** The `SAGEConv` in `nn.conv` now also uses the `MessagePassing` interface.

Awesome, You really are the most enthusiastic man I have ever seem in github!

**Comment by w21180239** [comment]
> Yes, you are right. We still need to convert some existing operators to be able to automatically support bipartite graph message passing (this is why we reimplement `SAGEConv` in the example). You can simply use the `SAGEConv` operator defined in the example.
> 
> **Edit:** The `SAGEConv` in `nn.conv` now also uses the `MessagePassing` interface.

By the way, could you tell what conv model support  `NeighborSampler` except SAGEConv

**Comment by rusty1s** [comment]
Currently only `SAGEConv` and `PointConv`.
