### ISSUE TITLE
sample_points works only on CPU

### ISSUE THREAD

**Issue by mauriziokovacic** [rusty1s/pytorch_geometric#407]
## 🐛 Bug

Line 35 on  _pytorch_geometric/torch_geometric/transforms/sample_points.py_ :
` frac = torch.rand(self.num, 2)`

should be
` frac = torch.rand(self.num, 2,device=pos.device)`

otherwise fails on line 46 if pos is on cuda

**Comment by rusty1s** [comment]
Fixed in master. Thank you :)
