### ISSUE TITLE
S3DIS dataset support

### ISSUE THREAD

**Issue by 1zb** [rusty1s/pytorch_geometric#412]
## 🚀 Feature

Stanford Large-Scale 3D Indoor Spaces Dataset (S3DIS) is a popular point cloud dataset.
http://buildingparser.stanford.edu/dataset.html

**Comment by rusty1s** [comment]
Added it to my TODO :)

**Comment by rusty1s** [comment]
Added to [master](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/s3dis.py).
