### ISSUE TITLE
About the benchmark experiments and validation dataset

### ISSUE THREAD

**Issue by imankgoyal** [rusty1s/pytorch_geometric#413]
## ❓ Questions & Help

Hi, 
Thanks for the great framework. I had some questions regarding the benchmark experiments, especially the point classification on ModelNet10. In ReadMe (https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/README.md), it is mentioned that you used a validation dataset for hyperparameter optimization. However, I was unable to find the code regarding the creation and use of the validation dataset for ModelNet. Maybe I am missing something. 

Also, you benchmarked point classification on ModelNet10, however, most of the benchmarked models (PointCNN, PointNet++) are evaluated on ModelNet40 in the official paper. Do you have some evaluation on ModelNet40 or plan to evaluate on ModelNet40 in future (at least for the sota models)? The reason I am asking about them so as to get a fair idea out how the current implementations perform as opposed to the official ones.
Again thanks for the great tool!

Best,
Ankit

**Comment by rusty1s** [comment]
Yes indeed, we did not perform any hyperparameter optimization on ModelNet and mostly follow the architectures described in the respective papers. We report accuracies after 200 epochs of training. Evaluating on ModelNet40 should be as easy as switching the datasets, but IMO it is much harder to compare the approaches here. Most papers perform different data augmentation and align the dataset using individual spatial transformers.

**Comment by imankgoyal** [comment]
Thanks for the info.
