### ISSUE TITLE
Visualize graph in `Data`

### ISSUE THREAD

**Issue by zc-alexfan** [rusty1s/pytorch_geometric#415]
## ❓ Questions & Help

Suppose that I have constructed a`Data` object, does PyG has tools to visualize the graph within the object? I know that in DGL we can use `networkx` to plot the graph, but the visualization from `networkx` is often too clutter, and it doesn't plot edges like loops and some directed edges. 

If PyG doesn't have visualization library, what tool would you recommend to visualize graphs?

**Comment by rusty1s** [comment]
Hi, we do not provide such functionality and also refer the user to convert its data to `networkx` via `utils` functions. In the end, PyG is a deep learning library and hence not very specialised for drawing of graphs. Personally, I had good experience using [`networkx` for visualization](https://networkx.github.io/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html#networkx.drawing.nx_pylab.draw_networkx), but it needs some tuning to get a pleasant result, *e.g.* fine-tuning of [`spring_layout` hyperparameters](https://networkx.github.io/documentation/stable/reference/generated/networkx.drawing.layout.spring_layout.html?highlight=spring%20layout#networkx.drawing.layout.spring_layout).
