### ISSUE TITLE
a little question about GraphSAGE in torch_geometric.nn.SAGEConv

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#416]
## ❓ Questions & Help

hello @rusty1s :

Sorry to trouble you for many times...

I am reading the code about GraphSAGE (./nn/conv/sage_conv.py). 
In the [article](https://arxiv.org/abs/1706.02216), the authors mentioned in Section 3.1, **Neighborhood Defination**:
> we uniformly sample a fixed-size set of neighbors, instead of
using full neighborhood sets

however, I read the code in sage_conv.py, and I cannot find where neighbor sample is. Only the search depth K is defined. 

And in the last part of **Neighborhood Defination**, the article says that K and S are hyper-parameters. And I really cannot find where S is in sage_conv.py. 

I wonder that if you want to use GraphSAGE with sage_conv.py, you have to write a sample function (perhaps in torch_geometric.utils, or networkx?) before the GraphSAGE module. 

yours, 
@wmf1997

**Comment by rusty1s** [comment]
Have a look at the [`NeighborSampler`](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.data.NeighborSampler) and the [Reddit example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py). This setup currently only works in master though.

**Comment by WMF1997** [comment]
thank you very much. i will have a try~
