### ISSUE TITLE
Is there any bipartite example?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#418]
## ❓ Questions & Help

It seems the newest sageconv support bipartite graph, is there any examples?  Thanks

**Comment by rusty1s** [comment]
Yes, the reddit.py uses the bipartite version of SAGEConv. A tutorial will follow.

**Comment by rusty1s** [comment]
Yes, the reddit.py uses the bipartite version of SAGEConv. A tutorial will follow.

**Comment by rusty1s** [comment]
Yes, the reddit.py uses the bipartite version of SAGEConv. A tutorial will follow.

**Comment by mrbeann** [comment]
Thanks for your reply, I found an example in another issue,
```
class BipartiteGraphOperator(MessagePassing):
    def __init__(self):
        super(BipartiteGraphOperator, self).__init__('add')
        self.lin = torch.nn.Linear(2, 1)

    def forward(self, x, assign_index, N, M):
        return self.propagate(assign_index, size=(N, M), x=x)

    def message(self, x_i, x_j):
        return self.lin(torch.cat([x_i, x_j], dim=1))

conv = BipartiteGraphOperator()

x_left = torch.Tensor([[1], [2], [3]])
x_right = torch.Tensor([[1], [2]])
row = torch.tensor([0, 1, 2, 0, 1, 2])
col = torch.tensor([0, 0, 0, 1, 1, 1])
assign_index = torch.stack([row, col], dim=0)

out = conv((x_left, x_right), assign_index, N=3, M=2)
print(out.size())
print(out)
```

Based on this I want to implement the bipartite with different parameters in a different direction, how can I achieve this? E.g., for a message from A to B use W1, and a message from B to A use W2.

**Comment by rusty1s** [comment]
You can propagate twice with different flows (`source_to_target` and `target_to_source`) and pass in the respective weight parameters to use.

**Comment by mrbeann** [comment]
Yeah, this seems great! BTW, I'm a bit confused about `x_j`, I found this means "the features of node j which gets aggregated",  so I guess this means that contain the neighbor's feature of node j, however, the dimension of this is `[E, m]`(m is the feature dimension. this means that all the nodes are neighbor of j?), did I wrong about this?

**Comment by rusty1s** [comment]
Maybe this gets clearer when looking at our [paper](https://arxiv.org/abs/1903.02428). In the message function, you have access to `x_i` (the root node) and `x_j` (the neighboring node), for each edge in your whole graph (dimension E).

**Comment by mrbeann** [comment]
It seems this works now. BTW, Is it possible to use diffierent feature size for a different group of nodes?

**Comment by rusty1s** [comment]
Sure, that works:
```python
import torch
from torch_geometric.nn import MessagePassing

class BipartiteGraphOperator(MessagePassing):
    def __init__(self):
        super(BipartiteGraphOperator, self).__init__('add')
        self.lin = torch.nn.Linear(16 + 32, 1)

    def forward(self, x, assign_index, N, M):
        return self.propagate(assign_index, size=(N, M), x=x)

    def message(self, x_i, x_j):
        return self.lin(torch.cat([x_i, x_j], dim=1))

conv = BipartiteGraphOperator()

x_left = torch.randn(3, 16)
x_right = torch.randn(2, 32)
row = torch.tensor([0, 1, 2, 0, 1, 2])
col = torch.tensor([0, 0, 0, 1, 1, 1])
assign_index = torch.stack([row, col], dim=0)

out = conv((x_left, x_right), assign_index, N=3, M=2)
print(out.size())
print(out)
```

**Comment by mrbeann** [comment]
Thanks! Do the `Data` class support this kind of data? I tried `Data(x=(x_left, x_right), edge_index=assign_index)` but it doesn't work.

**Comment by rusty1s** [comment]
No, this does not work yet, but it is a good request. Will think about it. In the meantime, you need to keep track of your data manually.

**Comment by mrbeann** [comment]
Yeah, this can be done! And an API to support bipartite and hete graph will be great!

**Comment by mrbeann** [comment]
After trying some implementation of bipartite, I found the main difference is the message direction, any other things are special for the bipartite graph? Also, I found the only things related to bipartite graph in sage_conv is the following codes.
```
            x = (None if x[0] is None else torch.matmul(x[0], self.weight),
                 None if x[1] is None else torch.matmul(x[1], self.weight))
```

Am I right about this?

**Comment by rusty1s** [comment]
The only special thing is that you need to pass a `size` argument to the convolution operator (that denotes the size of the assignment matrix) and that you can technically pass in a tuple of node features (for the "left" and the "right" side of nodes). That is why we are doing the branching in the `SAGEConv` code.

**Comment by mrbeann** [comment]
Thanks！
