### ISSUE TITLE
Documentation for MetaLayer

### ISSUE THREAD

**Issue by baldassarreFe** [rusty1s/pytorch_geometric#42]
Where can I find a reference or an example for the [MetaLayer](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/meta.py)?

In particular, I need to understand the parameters of `forward` and the signature of the three methods `node_model, edge_model, global_model`. 
If someone posts a working example I can write some doc from it :wink:

**Comment by rusty1s** [comment]
I will write a short documentation.

**Comment by rusty1s** [comment]
https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.meta.MetaLayer
