### ISSUE TITLE
Is there any support or examples of operations on 3D mesh?

### ISSUE THREAD

**Issue by LYHTHU** [rusty1s/pytorch_geometric#421]
## ❓ Questions & Help

Is there any support or examples of operations on 3D meshes? It seems PyG has very few tutorials.

**Comment by rusty1s** [comment]
While we do not have many tutorials, we have examples of:

* [FAUST Shape Correspondence](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/faust.py)
* [PointNet++](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_classification.py) and [DGCNN](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/dgcnn_classification.py) ModelNet classification
* [PointNet++](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py) and [DGCNN](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/dgcnn_segmentation.py) ShapeNet Part Segmentation

**Comment by LYHTHU** [comment]
> While we do not have many tutorials, we have examples of:
> 
> * [FAUST Shape Correspondence](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/faust.py)
> * [PointNet++](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_classification.py) and [DGCNN](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/dgcnn_classification.py) ModelNet classification
> * [PointNet++](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py) and [DGCNN](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/dgcnn_segmentation.py) ShapeNet Part Segmentation

Thank you!
