### ISSUE TITLE
Add FeaStNet operation with Mahalanobis distance

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_geometric#422]
## 🚀 Feature

Would you consider adding [FeaStNet](https://arxiv.org/abs/1706.05206) in the library?
I think should be interesting to have it the feature proposed on this paper due to the fact that are included recently to the tensorflow 2.0 preview. In addition is achieving great results in shape correspondences, part segmentation and so on.

**Comment by sw-gong** [comment]
I have already implemented FeaStConv based on PyG. I'll upload this module shortly.

**Comment by rusty1s** [comment]
Integrated in Pyg (see https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/feast_conv.py) thanks to @sw-gong
