### ISSUE TITLE
Finished my thesis, just incase you are interested.

### ISSUE THREAD

**Issue by Yannick-S** [rusty1s/pytorch_geometric#433]
Hi,
I wasn't sure what the best way of contacting you was. This ofcourse idn't really an issue.

You seem to be on top of all research in the field, and I wanted to share my thesis with you. The results are not sota but still... And I wanted to say a huge thanks! Without this repo, your immediate help and bugfixes none of my thesis could have been possible.

http://kth.diva-portal.org/smash/get/diva2:1320133/FULLTEXT01.pdf

Thanks!

**Comment by rusty1s** [comment]
Congratz on your thesis, it looks really good! I will definitely read it. Cool that I could be of help to you and hope you will continue your journey on geometric deep learning.
