### ISSUE TITLE
Libtorch C++ Support?

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_geometric#434]
## ❓ Questions & Help

Is is possible to use `libtorch` C++ support for `pytorch-geometric`?

**Comment by rusty1s** [comment]
No, PyTorch Geometric is Python only :(

**Comment by mingloo** [comment]
Understand. I'm just wondering `pytorch-geometric` might be faster if it has C++ support.

**Comment by dragonbook** [comment]
Hi, @rusty1s ,

Thank you for your work! I'm deploying an desktop application with some models based on PyTorch Geometry. As you said, this library is Python only and no libtorch c++ support, so I must to depoly all of my python code which is not allowed. Is there a way to use PyTorch geometry with c++? If not, could you suggest some safer ways to work around this?

Thanks!

**Comment by rusty1s** [comment]
If your model does not depend on scatter_max and pooling algorithms, you should be able to reimplement your model using scatter and gather operations quite easily in C++.

**Comment by dragonbook** [comment]
Thanks! I'll try it.

**Comment by weijian-sun** [comment]
> If your model does not depend on scatter_max and pooling algorithms, you should be able to reimplement your model with scatter_add and gather operations quite easily in C++ using libtorch.

what if my model depends on graph max pooling? is there any solution to work around it in c++ with libtorch?

**Comment by rusty1s** [comment]
Yes, you can build `torch-scatter` for C++, see [here](https://github.com/rusty1s/pytorch_scatter#c-api)
