### ISSUE TITLE
Constructing edge index for graph convolution (Undirected vs directed)

### ISSUE THREAD

**Issue by yutaizhou** [rusty1s/pytorch_geometric#435]
## ❓ Questions & Help

Hello,

Say I were to construct my own edge index to pass into a graph conv layer. If my graph is undirected, then does the edge index need to contain a pair going both ways? Or is one okay?

I will be using the transposed view for my example
Does the edge_index need to be:
`edge_index = [[1,2], [2,1]]`
or is the following okay?
`edge_index = [[1,2]]` or `edge_index = [[2,1]]`

**Comment by rusty1s** [comment]
The `edge_index` needs to contain a pair going both ways.

**Comment by yutaizhou** [comment]
Thank you!
