### ISSUE TITLE
Error during parallelization

### ISSUE THREAD

**Issue by davidsonic** [rusty1s/pytorch_geometric#438]
## ❓ Questions & Help

The model has no problem during training with a single gpu card. However, when it's parallelized with nn.data.DataParallel:
    if torch.cuda.device_count() > 1 and args.multi_gpu:
        model = DataParallel(model)
        print(colored('model parallized', 'red'))
I got the following error:
![image](https://user-images.githubusercontent.com/15846113/59944952-f90dc300-941a-11e9-921a-69addbca6b6a.png)
which complains that no attribute named num_nodes. I assume that this attribute is automatically calculated as in the document? What's the right way to do here?

**Comment by rusty1s** [comment]
You need to use a different dataloader `DataListLoader`. Did you change it?

**Comment by davidsonic** [comment]
Thanks for your prompt reply! I just tried it out. 
![image](https://user-images.githubusercontent.com/15846113/59954237-96c3bb00-9438-11e9-9118-e7f959d12846.png)
It seems that extra efforts are needed when performing online data processing, no?

**Comment by rusty1s** [comment]
See the [example script](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/data_parallel.py). You need to pass in the data_list to the model, and PyG moves the data list to the respective GPUs. Your model then expects a mini-batch data object as usual. This is slightly different to PyTorch since it easier to split data to different GPUs this way

**Comment by Xiaoshunxin** [comment]
> See the [example script](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/data_parallel.py). You need to pass in the data_list to the model, and PyG moves the data list to the respective GPUs. Your model then expects a mini-batch data object as usual. This is slightly different to PyTorch since it easier to split data to different GPUs this way

Hi!
Whether the parallelization setting mentioned above can used for only one single graph?
For instance, the Physics dataset in Coauthor network.
I have runned this dataset in single gpu card, but it raised a memory out problem.
On the other hand, it also raised a error when I try to run in multiple GPU setting.
The setting is shown as 
`    # load dataset
    if args.domain == 'CS':
        dataset = Coauthor(root='/home/amax/xsx/data/gnn_datas/Coauthor/CS', name='CS')
    elif args.domain == 'Physics':
        dataset = Coauthor(root='/home/amax/xsx/data/gnn_datas/Coauthor/Physics', name='Physics')
    else:
        dataset = None
    if dataset is None:
        pdb.set_trace()
    loader = DataListLoader(dataset[0], batch_size=1024, shuffle=True)

.....

 # beging training
    for epoch in range(args.epochs):
        # the steps of training
        for data_list in loader:
            model.train()
            optimizer.zero_grad()
            output = model(data_list)
            print('Outside Model: num graphs: {}'.format(output.size(0)))
`

And the error is 
`
################   0   ################
Traceback (most recent call last):
  File "/home/amax/xsx/code/gnns/ChebNet-pyg/train_mutiple.py", line 138, in <module>
    train()
  File "/home/amax/xsx/code/gnns/ChebNet-pyg/train_mutiple.py", line 50, in train
    for data_list in loader:
  File "/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch_geometric-1.0.3-py3.6.egg/torch_geometric/data/data.py", line 61, in __getitem__
TypeError: getattr(): attribute name must be string

Process finished with exit code 1
`

I want to query whether the parallelization setting can used for single large graph.
If it do, can you give me a example!

Thank for you help!

**Comment by rusty1s** [comment]
Sadly no, we currently do not support multi gpu setups for giant graphs. You can alternatively use the NeighborSampler for giant graph support (like in the reddit example; needs PyG from master)

**Comment by davidsonic** [comment]
Great work! Thanks
