### ISSUE TITLE
FRANKENSTEIN Dataset is having 0 node features

### ISSUE THREAD

**Issue by ekagra-ranjan** [rusty1s/pytorch_geometric#439]
Hi @rusty1s !

I am training a GCN on FRANKENSTEIN dataset. However, the number of features after loading the dataset turns out to be 0 using `dataset.num_features`. Due to this the input hidden of my 1st conv layer is becoming 0 giving me an error. Is the loading process for the FRANKENSTEIN dataset somewhat different than other?

**Comment by rusty1s** [comment]
Hi, the FRANKENSTEIN dataset has no node features (except when using `node_attr=True` in the `TUDataset` constructor). You then need to create synthetic node features using transforms like `torch_geometric.transforms.Constant()` or `torch_geometric.transforms.OneHotDegree()`.

**Comment by ekagra-ranjan** [comment]
Thanks for the clarification! I think we can add this as a note in the dataset docs of PyG especially for the TUDataset. Should I add them or mentioning this as a pointer wouldn't be necessay?

**Comment by rusty1s** [comment]
Sure, feel free to add the additional information to the doc.
