### ISSUE TITLE
Creating a simple dataset

### ISSUE THREAD

**Issue by allchemist** [rusty1s/pytorch_geometric#44]
Hi,

You did excellent job indeed, thanks for the project!

I'm wondering if there is a simple way to create a dataset on-fly. I already have a set of graphs in memory, so i'd like to create Dataset object directly from Data objects. Dumping and restoring the graphs in a recomended way is rather hard in my case, so i cannot use the approach suggested in docs.

Thanks

**Comment by rusty1s** [comment]
Thanks for the issue. I see that this is not very intuitive.
As a simple workaround, I suggest the following pattern (untested):
```python
class Dataset(torch_geometric.data.InMemoryDataset):
    def __init__(self, data_list, transform=None):
        super(Dataset, self).__init__(None, transform)  # we do not have a root folder
        self.data, self.slices = self.collate(data_list)

    def _download(self):
         pass

    def _process(self):
         pass
```
The basic idea is to disable the internally used methods `_download` and `_process`. I will try to make this more convenient in a future release.

**Comment by rusty1s** [comment]
Alternatively, you can simply use the `torch.utils.data.Dataset` class and create the dataset by yourself:
```python
class Dataset(torch.utils.data.Dataset):
    def __init__(self, data_list, transform=None):
        super(dataset, self).__init()__()
        self.data_list = data_list
        self.transform = transform

    def __len__(self):
        return len(self.data_list)

    def __getitem__(self, idx):
        data = self.data_list[idx]
        data = data if self.transform is None else self.transform(data)
        return data
```

**Comment by Guptajakala** [comment]
@rusty1s 
Hi, I'm using the pytorch dataset style. In the "__getitem__" function, do I need to convert data into PyG Data type?
Another question is after I create a dataset like yours and pass it to a PyG dataloader, the enumerated data "batch" number is wrong? Do you have any idea?

**Comment by rusty1s** [comment]
Hi, you need to convert your data to a `Data` object if you want to use the PyG DataLoader, *e.g.* to make use of automatic mini-batching. Otherwise for a single large graph, this is not really needed, but may be convenient due to its helper functions (like transferring all data at once to the GPU).

What do you mean with the enumerated data "batch" number? Can you elaborate?

**Comment by Guptajakala** [comment]
@rusty1s
I have similar dataset:
```
class Dataset(torch.utils.data.Dataset):
    def __init__(self, data_list, transform=None):
        super(Dataset, self).__init__()
        self.data_list = data_list
        self.transform = transform

    def __len__(self):
        return len(self.data_list)

    def __getitem__(self, idx):
        data = Data(x=None, pos=..., norm=..., y=....)   ##Here pos, norm are shape 1028x3
        return data

train_loader = DataLoader(Dataset, batch_size=32, shuffle=True)
for data in train_loader:
  print(data)

```
I get:
`
data: Batch(batch=[1141640], norm=[32896, 3], pos=[32896, 3], y=[32896]
`
You see batch size is wrong.

**Comment by rusty1s** [comment]
Yes, this is totally wrong, but I do not see how this could happen. I tried to reproduce your issue, but without success:
```python
class Dataset(torch.utils.data.Dataset):
    def __init__(self, data_list, transform=None):
        super(Dataset, self).__init__()
        self.data_list = data_list
        self.transform = transform

    def __len__(self):
        return len(self.data_list)

    def __getitem__(self, idx):
        data = Data(x=None, pos=..., norm=..., y=....)   ##Here pos, norm are shape 1028x3
        return data

train_loader = DataLoader(Dataset, batch_size=32, shuffle=True)
for data in train_loader:
    print(data)
```
prints out
```
Batch(batch=[32896], norm=[32896, 3], pos=[32896, 3], y=[32896])
Batch(batch=[32896], norm=[32896, 3], pos=[32896, 3], y=[32896])
Batch(batch=[32896], norm=[32896, 3], pos=[32896, 3], y=[32896])
Batch(batch=[4112], norm=[4112, 3], pos=[4112, 3], y=[4112])
```

**Comment by Guptajakala** [comment]
@rusty1s 
Thanks for your reply. I finally figured out why, I passed another "num_nodes=..." to Data(). This may confused dataloader later.

BTW, this is really cool library and is the best 3D related pytorch deep learning I met so far!

**Comment by rusty1s** [comment]
Yeah, when you manually set `num_nodes` the batch object will be created accordingly and ignores the shape of the other tensors. You do not really need to set it unless PyG prints out a warning that you should :)

Thank you :)
