### ISSUE TITLE
Add Debug Mode functionality

### ISSUE THREAD

**Issue by BjoernLange** [rusty1s/pytorch_geometric#444]
## 🚀 Feature

Pytorch Geometric should warn the user when the input to a `SplineConv` is invalid. This would help tracking down errors and separate usage errors from real bugs.
To circumvent performance issues some kind of "debug mode" could be added and the checks only performed when it is active. This might also be interesting for other operations. Additionally it would improve the way the already present checks in [forward](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/spline_conv.py#L105) work.

I'm especially interested in these checks:
- Dimensionality of input tensors to `forward`
- Dimensionality of input tensors to `forward` matching the values passed to `__init__` (especially `pseudo.size(1) == dim`)
- Value ranges of input tensors to `forward`(especially rework the present check for the pseudo coordinates being in range [0, 1] to be checked on each example and not only the first one)

## Motivation

I've struggled several times with incorrect input to `SplineConv` causing "random" illegal memory access CUDA errors where the cause of the error was not obvious. Additionally, sometimes the CPU version worked with incorrect input data leading me to the wrong conclusion that either my installation might be broken or a bug present in the `SplineConv`code. Finding these errors might be trivial when one knows where to look, but if not they are time consuming and frustrating.

**Comment by rusty1s** [comment]
Hi Björn,

This is a good idea and should be in fact added to all PyG operators. Do you know how this is implemented in other packages? Some random thoughts:
1. We could add a global `debug` flag, *e.g.* `torch_geometric.debug=True`.
2. We could do something similar to PyTorch's [`detech_anomaly`](https://pytorch.org/docs/stable/autograd.html?highlight=anomaly#torch.autograd.detect_anomaly) functionality:
```python
with torch_geometric.debug_mode():
    out = model(...)
```
WDYT? I'm personally in favor of the latter.

**Comment by BjoernLange** [comment]
Hi Matthias,

I think both should be implemented where the global flag serves as a mean to implement the context manager used to enable the debug mode for specific code segments. Actually, this is exactly what is done in PyTorch's [detect_anomaly](https://pytorch.org/docs/stable/_modules/torch/autograd/anomaly_mode.html#detect_anomaly) context manager.

**Comment by rusty1s** [comment]
Yes, you are right :)

**Comment by BjoernLange** [comment]
I can implement the context manager and add the checks to `SplineConv` and open a merge request then if you like.

**Comment by rusty1s** [comment]
I added a first draft of the [debug mode](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/debug.py) and included first checks in [`SplineConv`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/spline_conv.py#L116-L139).

**Comment by rusty1s** [comment]
Ups, didn't saw your comment :(

**Comment by BjoernLange** [comment]
No problem ;)
The first draft looks good.

**Comment by rusty1s** [comment]
I will include more checks in the future. Closing this for now. Thanks :)
