### ISSUE TITLE
from_networkx() gets wrong output on undirected subgraphs

### ISSUE THREAD

**Issue by yutaizhou** [rusty1s/pytorch_geometric#451]
## To Reproduce

`from_networkx()` may have unintended consequence for an **undirected subgraph**. `subgraph()` seems to be working just fine. Edges going both ways are required to represent an undirected graph when passing through a graph conv layer.

I believe this error may stem from `coalesce()`

```
G = nx.complete_graph(5)
```

```
g = pyg.utils.from_networkx(G)
o_sub = pyg.utils.subgraph([0,1,3,4], g.edge_index)[0]  
print(o_sub)
# tensor([[0, 0, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4],
          [1, 3, 4, 0, 3, 4, 0, 1, 4, 0, 1, 3]])
# good!
```

```
O = G.subgraph([0,1,3,4])
o = pyg.utils.from_networkx(O) # gives bad output
print(o.edge_index)
# tensor([[0, 0, 0, 1, 1, 3, 3, 3, 4, 4],
          [1, 3, 4, 3, 4, 0, 1, 4, 1, 3]])
# bad! Missing edges: (1,0), (4,0)
```

**Comment by rusty1s** [comment]
Fixed in master, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/test/utils/test_convert.py#L72-L80).

**Comment by yutaizhou** [comment]
Perfect. Thank you!
