### ISSUE TITLE
Potential CUDA error when using Mini-batches for VGAE models

### ISSUE THREAD

**Issue by joeybose** [rusty1s/pytorch_geometric#458]
It appears as if there's an interesting bug that happens when you use a minibatch > 1 with DataListLoader with a vanilla VGAE model as provided by the library. The error does not happen when you set minibatch=1. The bug triggers a CUDA device side assert: 
`/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [87,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.`
After a bit of digging it appears to be coming from `self.propagate(edge_index, x=x, norm=norm, bias=bias)` in `GCNConv` layer? The CUDA error suggests there is a wrong index somewhere but it's hard to ascertain the source of the error. Is there a proper way to do mini-batching to train a VGAE/GAE model where each data point is a graph rather simply edges?

**Comment by rusty1s** [comment]
The GAE models currently support only a single graph. You need to use the normal `DataLoader` and batch support in the decoder to fix (using the `to_dense_batch` method).

**Comment by joeybose** [comment]
Perhaps, I wasn't super clear in explaining the problem but Although the DataListLoader has multiple graphs (say minibatch=2) even if you do `model.encode(...)` one graph at a time by iterating over the returned list this bug happens always on the 5th graph regardless of dataset.

**Comment by rusty1s** [comment]
Ah I understand. Do you have an example to reproduce the error?

**Comment by joeybose** [comment]
I do, unfortunately I'm afk from my computer for another 12 hours but maybe I can describe it a bit better here before giving the real code snippet
```
dataset = PPI(root, split='train' transform=T.NormalizeFeatures(), use_node_attr=False)
train_loader = DataListLoader(dataset,batchsize=2)
for data_batch in train_loader:
    for data in data_batch:
        data.train_mask = data.val_mask = data.test_mask = data.y = None
        data = model.split_edges(data)
        x, train_pos_edge_index = data.x.to(dev), data.train_pos_edge_index.to(dev)
        data.batch = None
        z = model.encode(x, train_pos_edge_index)
```
This is roughly the high level idea, and it will cause a CUDA assert error roughly at the 4/5th graph. You can also reproduce a similar issue, by running the PPI dataset instead of Cora in the example autoencoder codebase: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py in this case even if u feed 1 graph at a time, the model will break on the second iteration. One way around that problem is if you save the models weights and reload them which somehow circumvents that issue. I think these issues are probably related if not the same.

**Comment by rusty1s** [comment]
Oh, that makes sense, you need to set `cached=False` in the GCN encoder to prevent the caching of the normalization :)

**Comment by joeybose** [comment]
That actually worked! Thanks so much!

**Comment by rusty1s** [comment]
I added a [check](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py#L91-L95) to detect such behaviour in the future.

**Comment by nassarofficial** [comment]
I am also receiving this error but with the EdgePooling example. Does this error "indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [87,0,0], thread: [31,0,0] Assertion srcIndex < srcSelectDimSize" mean there is a wrong edge index?

**Comment by binonteji** [comment]
I am trying to understand the reconstructed loss/accuracy of the input (large) graph via mini-batches using GAE model. I am not splitting any edges for train|val|test. Is it really possible through mini batching ?

**Comment by rusty1s** [comment]
Can you clarify what you mean?

**Comment by binonteji** [comment]
@rusty1s Sorry for the late reply. Following the GAE model, there is an input matrix (**A**) which is encoded into **Z** and the reconstructed matrix (**A_hat**). Normally, the matrix reconstruction is done through the embeddings via **dot_product(Z, Z.T)**. But if we really have a dense/large matrix, the matrix reconstruction looks very expensive operation. 

I am trying to implement the matrix reconstruction operation using mini-batching.

**Comment by rusty1s** [comment]
You can take a look at https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.pool.MIPSKNNIndex.html#torch_geometric.nn.pool.MIPSKNNIndex which allows you to query top-k matches according to dot product in mini-batches.
