### ISSUE TITLE
Proposal for adding a new method for point clouds

### ISSUE THREAD

**Issue by sirbardo** [rusty1s/pytorch_geometric#46]
Hi everyone!

I feel like, for those of us working closer to the field of Computer Graphics, it would be cool if this library also implemented the "EdgeConv" operation from this paper: 

https://arxiv.org/pdf/1801.07829.pdf

**Comment by rusty1s** [comment]
Thanks! Will work on it.

**Comment by rusty1s** [comment]
https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/edge_conv.py
