### ISSUE TITLE
Random Sampling of Negative Edges for Small Graphs can throw an error

### ISSUE THREAD

**Issue by joeybose** [rusty1s/pytorch_geometric#462]
If you have a regular GAE/VGAE model and use the built in method to split edges, the random sampling can break for small graphs. Specifically, the following error  `*** ValueError: Sample larger than population or is negative` is thrown on this line: https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/models/autoencoder.py#L144. One can reproduce, the problem by using the Enzymes dataset from the `TUDataset` class and then if you iterate across the graphs individually then some will throw an error. Minimal code example:

```
dataset = list(TUDataset(path,'ENZYMES',use_node_attr=True,transform=T.NormalizeFeatures()))
train_loader = DataListLoader(dataset, batch_size=args.train_batch_size, shuffle=True)
val_edge_ratio = 0.1
train_edge_ratio = 0.1
for i,data_batch in enumerate(train_loader):
    for idx, data_graph in enumerate(data_batch):
        data_graph.train_mask = data_graph.val_mask = data_graph.test_mask = data_graph.y = None
        data_graph.batch = None
        test_edge_ratio = 1 - val_edge_ratio - train_edge_ratio
        data = model.split_edges(data_graph,val_ratio=val_edge_ratio,test_ratio=test_edge_ratio)
```
Perhaps, there should be a warning that small graphs cannot be used for splitting edges or even return a value to handle this edge case more gracefully?

**Comment by rusty1s** [comment]
Good catch! Fixed in master.
