### ISSUE TITLE
Inconsistent behaviour of TUDataset for different Datasets

### ISSUE THREAD

**Issue by joeybose** [rusty1s/pytorch_geometric#463]
The dataset returned when using `TUDataset` for certain Datasets such as ENZYMES and REDDIT-MULTI-12K is different. The former provides each individual graph and its adjacency matrix in its own separate Data object while the later returns one graph with a combined `edge_index` even thought `len(dataset)` shows the correct number of graphs. I think the former behavior is more desirable as it allows one to individually use graphs for a certain task.

**Comment by rusty1s** [comment]
Can not reproduce and certainly not intended:
```python
from torch_geometric.datasets import TUDataset

dataset = TUDataset('/tmp/redditmulti', 'REDDIT-MULTI-12K')

print(dataset)
print(dataset[0])
print(dataset[1])
```

**Comment by joeybose** [comment]
Weird, the behavior is back to normal. I'll close this issue.
