### ISSUE TITLE
add edge batch attribute to batch class

### ISSUE THREAD

**Issue by MilkshakeForReal** [rusty1s/pytorch_geometric#468]
## Motivation
One can do use batch.batch to get the batch index of each node, but what about the batch index of each edge? 

 I am dealing with a problem of predicting some propoerties of edge and have to get the edge batch index to implenment Set2Set model. 
Have a nice day :）

**Comment by rusty1s** [comment]
Just do
```python
edge_batch = batch[edge_index[0]]
```

**Comment by MilkshakeForReal** [comment]
Whoa ok, that's cool. Thank a lot!
