### ISSUE TITLE
illegal memory access using max_pool_x

### ISSUE THREAD

**Issue by Bawaw** [rusty1s/pytorch_geometric#47]
Hi Matthias,

Thanks for the great library! However, I'm facing some problems when trying to implement my own models using voxel grid clustering technique, followed by max_pool_x layer based on the mnist_voxel_grid.py example. 

Here's one of the model architectures I tried: 
`
class Net(torch.nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(1, 32, dim=3, kernel_size=2)
        self.fc1 = torch.nn.Linear(4 * 32, 2)

    def forward(self, data):
        print(data)
        data.x = F.elu(self.conv1(data.x, data.edge_index, data.edge_attr.float()))
        cluster = voxel_grid(data.pos, data.batch, size=15)
        x = max_pool_x(cluster, data.x, data.batch, size=4)
        x = x.view(-1, self.fc1.weight.size(1))
        x = F.elu(self.fc1(x))
        return F.log_softmax(x, dim=1)`

And the traceback of the error: 
> Traceback (most recent call last):
  File "/media/bawaw/Alpha/Projects/thesis2/Balder/geometric_dl/models/example_model.py", line 80, in <module>
    train(epoch)
  File "/media/bawaw/Alpha/Projects/thesis2/Balder/geometric_dl/models/example_model.py", line 62, in train
    F.nll_loss(model(data), data.y.long()).backward()
  File "/home/bawaw/.conda/envs/gdl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/bawaw/Alpha/Projects/thesis2/Balder/geometric_dl/models/example_model.py", line 38, in forward
    x = max_pool_x(cluster, data.x, data.batch, size=4)
  File "/home/bawaw/.conda/envs/gdl/lib/python3.7/site-packages/torch_geometric/nn/pool/max_pool.py", line 17, in max_pool_x
    return _max_pool_x(cluster, x, (batch.max().item() + 1) * size)
  File "/home/bawaw/.conda/envs/gdl/lib/python3.7/site-packages/torch_geometric/nn/pool/max_pool.py", line 11, in _max_pool_x
    x[x == fill] = 0
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

Kind regards, 
Balder

**Comment by rusty1s** [comment]
Hi,

it seems that your size parameter for `max_pool_x` is wrong. You should only pass a size argument if the number of clusters is known in advance (as it is the case for the MNIST example). For the voxel grid call, you aim for 15 voxels in each dimension, so you actually have a maximum size of `15*15*15`.

**Comment by Bawaw** [comment]
Oh I see, thank you! I got it working by not predefining the number of clusters. Might I still ask:
1. Why it is you know the number of clusters in advance in the MNIST example? Because every image is represented by a different graph (different positioning of the vertices). 
2. If you do not know the size of the cluster, using a view is no longer viable (because the amount of features x may vary) and the only option is to use some kind of global_pooling operator, is this correct?

Thank you for your quick response,
Balder

**Comment by rusty1s** [comment]
Hi,

In MNIST, each node lies in the interval [0,28], so a voxel grid size of 14 results in a maximum of 4 voxels. For more arbitrary models/graphs you need to normalize them first or miss out on the fixed sizes by making use of global pooling, as you correctly pointed out.
