### ISSUE TITLE
Issue with examples/pointnet2_part_seg.py

### ISSUE THREAD

**Issue by imankgoyal** [rusty1s/pytorch_geometric#471]
## ❓ Questions & Help

Hi, 

I was running the pointnet++ part segmentation example with catergory=None (according to https://github.com/rusty1s/pytorch_geometric/pull/359). However, I find the performance to be unusually high (much higher than reported values, https://arxiv.org/pdf/1801.07791.pdf, supplementary page 3 for pointnet++). Am I interpreting the results in the wrong way or is there some bug in the evaluation code? 

Thanks!
<img width="370" alt="Screen Shot 2019-06-30 at 11 11 11 PM" src="https://user-images.githubusercontent.com/23709936/60408354-8c1dca00-9b8c-11e9-818a-def1e52b051c.png">

**Comment by rusty1s** [comment]
Ah, this looks like a bug in the iou computation when not all classes are present in a mini-batch. I will look into it.

**Comment by rusty1s** [comment]
Should be fixed in master. You need to recreate `ShapeNet` dataset in order to test. Sorry for the inconveniences!

**Comment by imankgoyal** [comment]
Thank you so much for the quick response.
