### ISSUE TITLE
About dataloader

### ISSUE THREAD

**Issue by voidspiral** [rusty1s/pytorch_geometric#473]
## ❓ Questions & Help

**The tutorial say simply pass a regular python list holding torch_geometric.data.Data objects and pass them to torch_geometric.data.DataLoader:**
`from torch_geometric.data import Data, DataLoader

data_list = [Data(...), ..., Data(...)]
loader = DataLoader(data_list, batch_size=32)`

**I follow this tutorial** 
`data_list = []
for e, b in zip(pt,label):
    pos = torch.tensor(e, dtype=torch.float)
    y = torch.tensor([b])
    data_list.append(Data(pos=pos, y=y))

tr = DataLoader(data_list, batch_size=32)
for data in tr:
    print(data.pos)`

**I'm facing the following error**
`TypeError                                 Traceback (most recent call last)
<ipython-input-113-7660a7b4055e> in <module>
      6 
      7 tr = DataLoader(data_list, batch_size=32)
----> 8 for data in tr:
      9     print(data.pos)

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    558         if self.num_workers == 0:  # same-process loading
    559             indices = next(self.sample_iter)  # may raise StopIteration
--> 560             batch = self.collate_fn([self.dataset[i] for i in indices])
    561             if self.pin_memory:
    562                 batch = _utils.pin_memory.pin_memory_batch(batch)

/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     68         return [default_collate(samples) for samples in transposed]
     69 
---> 70     raise TypeError((error_msg_fmt.format(type(batch[0]))))

TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'torch_geometric.data.data.Data'>`

How can I fix it?

**Comment by rusty1s** [comment]
Are you sure you are using the PyTorch Geometric DataLoader `torch_geometric.data.DataLoader` instead of the one provided by PyTorch?

**Comment by voidspiral** [comment]
Yeah, you're right. I made a mistake.
Thank you！

**Comment by elevenjiang1** [comment]
Then, if I want to load both tensor and graph at the same time, what can I do?
For example, my data contain an image and a special data structure represent by a graph.

**Comment by rusty1s** [comment]
You can have a `Dataset` that returns tuples, e.g., `(img, graph_data)`. The `DataLoader` will take care of batching this correctly, that is it will return a tuple with batched image data and batched graph data.

**Comment by ZixuWang** [comment]
I load both tensor and graph at the same time successfully without returns tuples, the dataloader automatically returns list

**Comment by rusty1s** [comment]
Can you clarify what you mean?
