### ISSUE TITLE
Question related to the aggregation step of graph convolutional networks

### ISSUE THREAD

**Issue by yorard123** [rusty1s/pytorch_geometric#474]
Hi,

I'm trying to understand the code of the aggregation step of graph convolutional networks, but, I'm a little bit stuck.

As a first step I'm trying to imitate a previous version of NNConv without MessagePassing class, in specific this [one](https://github.com/rusty1s/pytorch_geometric/blob/b3282cbd624adba27253a4635bc1e4ead6818ce7/torch_geometric/nn/conv/nn_conv.py).

Following the logic of this code I created my sample code:

```
import torch
from torch_geometric.data import Data
from torch_geometric.utils import scatter_

x = torch.tensor([[200], [100], [300]], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)

sample_graph = Data(x=x, edge_index=edge_index)

test = scatter_('add', sample_graph.x,, sample_graph.edge_index[0], dim_size=sample_graph.x.size(0))
```

> RuntimeError: shape '[3, 1]' is invalid for input of size 4

As far as I understood, the problem is the mismatch of the input vector size with the index vector size. This mismatch is due to the fact the graph is undirected and the number of edges is different from the number of nodes, right? I understand that it is a problem to the scatter_ method, but I do not understand first at all why it was working in NNConv, and how it is solved this issue in pytorch_geometric.

I would appreciate if you can help me to understand how to solve this issue.

Thanks,

**Comment by rusty1s** [comment]
Hi, the input arguments of the `scatter_` call must match in the first dimension, so you need to map the node features into edge space:
```python
test = scatter_('add', sample_graph.x[sample_graph.edge_index[1]],
                sample_graph.edge_index[0], dim_size=sample_graph.x.size(0))
```

**Comment by yorard123** [comment]
Oh I see!! The magic line was this one in NNConv: `out = torch.matmul(x[col].unsqueeze(1), out).squeeze(1)`. I didn't see the x[col] here. I suppose that `MessagePassing class` is doing something similar right?

**Comment by rusty1s** [comment]
Yes, the `MessagePassing` interface is just a wrapper for this kind of operation.
