### ISSUE TITLE
Proper usage of DataFlow

### ISSUE THREAD

**Issue by duncster94** [rusty1s/pytorch_geometric#477]
Hey @rusty1s thanks for implementing node-wise batching.

I'm not sure what the proper usage of `DataFlow` is. Here's an example of my current usage:

```
for i, data in enumerate(data_flow):

    # Initial `x` is feature matrix.
    if i == 0:
        x = features[data.n_id]
    x = layer(x, data.edge_index)
    x = F.leaky_relu(x, self.alpha)
```
This actually runs, however the shape of `x` does not change between iterations. For example, if the `DataFlow` is `(128<-202<-419<-694)`, the shape of `x` will be always `(694, f)` where `f` is `layer` output dimension. My expectation is that the dimensionality of `x` should be `(128, f)` after the last layer (i.e. only features for the nodes in the batch should be retained).

Is it necessary to reindex `x` each hop? This doesn't seem like the intended usage which is why I'm opening the issue. Additionally, I'm using `GATConv` layers. This differs from the `SAGEConv` layer used in the Reddit example so I'm wondering if that could be the issue.

**Comment by rusty1s** [comment]
Hi, in the moment one can only use GNN operators which can work on bipartite graphs (see https://github.com/rusty1s/pytorch_geometric/issues/430). Will try to implement `GATConv` to work here. This will automatically reduce the node dimension.

However, I like the second approach too (the one where you reindex `x` at each hop). It wouldn't require bipartite graph operators, but would come with a larger memory footprint. However, it might be more intuitive to use. WDYT?

**Comment by rusty1s** [comment]
`GATConv` now supported, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py).
