### ISSUE TITLE
What's the difference between "Superpixel MNIST" and "MNIST"?

### ISSUE THREAD

**Issue by xuehui1991** [rusty1s/pytorch_geometric#480]
## ❓ Questions & Help

Do you have any doc in detail to describe this thing? Thank you~

**Comment by rusty1s** [comment]
The [`MNISTSuperpixels` dataset](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.MNISTSuperpixels) contains the MNIST images, but the images are pre-converted to a superpixel representation.  You can have a look at [Figure 5a](https://arxiv.org/pdf/1711.08920.pdf) for an example of the resulting graphs.
