### ISSUE TITLE
Trying to Run Benchmarks

### ISSUE THREAD

**Issue by EddyWD** [rusty1s/pytorch_geometric#481]
## ❓ Questions & Help
I have been trying to run the benchmark files from the repository, the gcn.py specifically but I get the following error:

`Traceback (most recent call last):
  File "gcn.py", line 6, in <module>
    from citation import get_planetoid_dataset, random_planetoid_splits, run
ModuleNotFoundError: No module named 'citation'`

**Comment by rusty1s** [comment]
You need to install the benchmark suite, as noted [here](https://github.com/rusty1s/pytorch_geometric/tree/master/benchmark).

**Comment by EddyWD** [comment]
My bad, silly mistake, I have installed that now. I now don't know what the correct names for the datasets are. Tried Cora, cora, citation_cora but not sure what else to try. I tried to look at the benchmark suite repository but it must be private. (Sorry new to Python, Pytorch, GitHub and your library as well of course)

**Comment by rusty1s** [comment]
You can run with, *e.g.,
```
python gcn.py --dataset=Cora
python gcn.py --dataset=Cora --random_splits=True

python gat.py --dataset=CiteSeer
python gat.py --dataset=CiteSeer --random_splits=True
```

**Comment by EddyWD** [comment]
I was using a normal argument rather than keyword argument. Thanks

**Comment by EddyWD** [comment]
How can I find the results of these benchmarks?

**Comment by rusty1s** [comment]
In our [paper](https://arxiv.org/abs/1903.02428).

**Comment by EddyWD** [comment]
Sorry, I mean of the ones I have run locally? As I am planning to try to implement a new algorithm, on behalf of my supervisor and/or try to apply to some new datasets.

**Comment by rusty1s** [comment]
I do not fully understand. Which results do you mean?

**Comment by EddyWD** [comment]
I would like to reproduce the accuracy results you have in Table 1 and the training runtime comparison in Table 4 of your paper. Initially on the current algorithms and datasets to understand how it works. I thought running the benchmarks was the way to go about doing this. If it is not, can you point me in the direction of what should I be doing?

**Comment by rusty1s** [comment]
You can run the shell script in the `citation` folder.

**Comment by EddyWD** [comment]
Does this output classifications accuracies and training runtimes? If so where? And if not how do I get those?

**Comment by rusty1s** [comment]
This only outputs classification accuracies. There is also a runtime folder in the benchmark folder.
