### ISSUE TITLE
Attention Quality in GAT

### ISSUE THREAD

**Issue by AneeshaaSC** [rusty1s/pytorch_geometric#482]
Hi Team,

I read the AGNN paper: https://openreview.net/pdf?id=rJg4YGWRb which talks about gauging the attention quality of the model using a relevance score. 

I couldn't understand from the way it is described in the paper. But I'd like to calculate relevance score or find attention quality of a GAT model. Please advise.

**Comment by rusty1s** [comment]
Hi, the AGNN paper evaluates the attention quality by checking which nodes gets high attention scores, dependent on the class of the central node (c_i) and the class of the neighbor node (c_j). That is, we usually want high attention scores for nodes that belong to the same class, and want low (or negative) ones for node-pairs that belong to different classes. 

To evaluate the attention quality of a GAT model, you the attention scores for each edge, and the class to which the source and target node belongs. We currently provide no easy way to access the attention scores, but this should be straightforward if you copy paste the GATConv and add `self.alpha = alpha` to line 104. You can then access the attention scores after the forward pass via `conv.alpha`

**Comment by AneeshaaSC** [comment]
Thank you, but using the GATConv class in the code now gives me problems I did not have before:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-53-517b3f5e7a93> in <module>()
     17 
     18 for epoch in range(1, 201):
---> 19     train()
     20     log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
     21     print(log.format(epoch, *test()))

4 frames
<ipython-input-42-0ba9bf09504b> in forward(self, x, edge_index)
     63         print(x[row].shape)
     64         print(x[col].shape)
---> 65         alpha = torch.cat([x[row], x[col]], dim=-1)
     66         alpha = (alpha * self.att_weight).sum(dim=-1)
     67         alpha = F.leaky_relu(alpha, self.negative_slope)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 3. Got 1 and 2 in dimension 0 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by rusty1s** [comment]
Can you elaborate? What did you change? And what did lines `print(x[row].shape)` and `print(x[col].shape)` output?

**Comment by AneeshaaSC** [comment]
torch.Size([2, 13264, 8, 8])
torch.Size([1, 2708, 8, 8])

when I make

**Comment by rusty1s** [comment]
You need to do
```python
row, col = edge_index
```

**Comment by AneeshaaSC** [comment]
But that is what gave the error actually. row = edge_index[0][0] and col = edge_index[0][1] made that part work

**Comment by rusty1s** [comment]
But that does not make any sense. The code in the colab looks correct to me.

**Comment by rusty1s** [comment]
Which PyTorch Geometric version are you using? Try `edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))` instead of `edge_index = add_self_loops(edge_index, num_nodes=x.size(0))`.

**Comment by AneeshaaSC** [comment]
I think its version 1.3.

Requirement already satisfied: torch-geometric in /usr/local/lib/python3.6/dist-packages (1.3.0)

**Comment by rusty1s** [comment]
Yes, then `edge_index[0][0]` is correct, because it holds the tuple of edge indices and edge weights.

**Comment by AneeshaaSC** [comment]
Thank you so much, it works. I'll try and figure how to find relevance score using the attention weights.
