### ISSUE TITLE
not all tests passed?

### ISSUE THREAD

**Issue by alekseic** [rusty1s/pytorch_geometric#49]
When I run `python setup.py test`, I get figures like that:

----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                                                    Stmts   Miss  Cover
(tested items are enumerated)
TOTAL                                                    3029   1247    59%

For example, I got these figures for Pooling layers:
torch_geometric/nn/pool/avg_pool.py                        27     20    26%
torch_geometric/nn/pool/consecutive.py                      6      0   100%
torch_geometric/nn/pool/global_pool.py                     11      7    36%
torch_geometric/nn/pool/graclus.py                          4      2    50%
torch_geometric/nn/pool/max_pool.py                        26     19    27%
torch_geometric/nn/pool/pool.py                            13      7    46%
torch_geometric/nn/pool/set2set.py                         35     29    17%
torch_geometric/nn/pool/sort_pool.py                       17     14    18%
torch_geometric/nn/pool/topk_pool.py                       58     18    69%
torch_geometric/nn/pool/voxel_grid.py                      17     13    24%

I think it's normal but it's just interesting how you measure the coverage)

**Comment by rusty1s** [comment]
Which tests do not work for you? The test coverage is automatically reported by the python package [coverage] (https://coverage.readthedocs.io/en/v4.5.x/)
