### ISSUE TITLE
Cluster GCN

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#492]
https://arxiv.org/pdf/1905.07953.pdf

Seems cool and not too hard to implement!

**Comment by rusty1s** [comment]
This is an interesting paper, thank you! It contains similar ideas to the [Fast Training of Sparse Graph Neural Networks on Dense Hardware](https://arxiv.org/abs/1906.11786) paper.

I think it could be implemented as a pre-processing step in which a single `Data` object gets processed to a clustered `Batch` object.  We then provide all the tools needed to train on these batches in PyG.
