### ISSUE TITLE
QM9 dataset only has 133246 molecules

### ISSUE THREAD

**Issue by mooninrain** [rusty1s/pytorch_geometric#494]
Hello! I've found that the size of QM9 dataset(133246) downloaded from PyG's url is not consistent with MoleculeNet(133885).

Could you provide the 133885-molecule version of processed torch data? I'm actually re-implementing some papers' splits on QM9 with PyG, so this is troublesome. Thank you.

**Comment by rusty1s** [comment]
Hi, we use `RDKit` to preprocess the QM9 dataset. A few molecules are invalid (`rdkit` outputs `None` when trying to read it) and those molecules are hence omitted. So this is not really troublesome IMO. In addition, the [Gilmer paper](https://arxiv.org/pdf/1704.01212.pdf) reports to only use 130462 molecules (Section 7).

**Comment by mooninrain** [comment]
Thank you! I'll follow Gilmer paper then, it sounds reasonable.

BTW, Actually I was trying to re-implementing PAGTN[1] with PyG, so people seeing this issue shall not use their split_*.txt[2].

[1] Path-Augmented Graph Transformer Network, 2019
[2] https://github.com/benatorc/PA-Graph-Transformer

**Comment by Mario-Liu** [comment]
> 
> 
> Thank you! I'll follow Gilmer paper then, it sounds reasonable.
> 
> BTW, Actually I was trying to re-implementing PAGTN[1] with PyG, so people seeing this issue shall not use their split_*.txt[2].
> 
> [1] Path-Augmented Graph Transformer Network, 2019
> [2] https://github.com/benatorc/PA-Graph-Transformer

`suppl = Chem.SDMolSupplier('data/gdb9.sdf')
hmols = [x for x in suppl if x is not None]
print('valid sdf files',len(hmols))`

well, I preprocess the whole qm9 dataset with '[x for x in suppl if x is not None]', but only find 132480 of 133885 to be valid. While Gilmer only use 130462 molecules and PyG provided 133246, what might be the difference for three of us? 
Should I still delete some wrong molecules according to some rules to make 130462 or there is something wrong with my codes?  Glad if you could help.

**Comment by vthost** [comment]
In terms of the moleculenet datasets, it seems `bbbp, clintox, toxcast` have more samples than mentioned in the original paper. Do you by any chance know what's the difference there?

**Comment by ameya98** [comment]
With the `rdkit` version `2023.03.2`, I get the following:
```
With sanitize=False, removeH=False: Valid SDF files are 133885
With sanitize=True, removeH=True:   Valid SDF files are 133247
With sanitize=True, removeH=False:  Valid SDF files are 132480
```
when running
```
suppl = Chem.SDMolSupplier(data/gdb9.sdf', sanitize=True, removeHs=False)
hmols_sanitize_keepH = [x for x in suppl if x is not None]
```
for example. So the answer seems to depend on sanitization. The number 132480 matches with the [DeepChem](https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html?highlight=qm9#qm9-datasets) library's implementation as well.
