### ISSUE TITLE
No module named 'scatter_cuda'

### ISSUE THREAD

**Issue by alekseic** [rusty1s/pytorch_geometric#50]
I proceeded with the installation instructions. And I have Cuda available on my machine.
However, when I run `python cora.py`, I get the message

File "/home/anaconda/envs/pytorch/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import scatter_cuda
ModuleNotFoundError: No module named 'scatter_cuda'

I tried to clone the `scatter` module from Github separately, and then run `python setup.py install` on it, with same results.

I can find the `scatter_cuda.py` and `scatter_cpu.py` files inside the "egg" named `torch_scatter-1.0.4-py3.6-linux-x86_64.egg`, and I also see the corresponding `.so` files inside that egg. But no such files inside the `torch_scatter` folder.

**Comment by rusty1s** [comment]
Can you post the log of the install command:
rm -rf build && python setup.py install

**Comment by alekseic** [comment]
Matthias, I managed to install everything.

It seems that `pip install` did not work correctly (without any suspicious messages, at least to my newbie eye), and I had to clean all traces of your helper packages in my anaconda site-packages folder - 3 folders by package (the `egg`, the folder itself and the `dist-info`), and go over all the necessary packages, clone them from github, and run `python setup.py install` separately for them.
And now everything works.

I think that the problem was because when I first installed pytorch_geometric, I was also installing CUDA drivers, and there was some mismatch, and so the 'cuda' versions were not created. Afterwards, when I rebooted the system, CUDA became available, but running `pip install` anew did not result in the creation of _cuda files (namely, scatter_cuda, unique_cuda, basis_cuda and graclus_cuda). Maybe because `pip install` thought there was nothing new to install. And only after thorough folder cleaning it did realize that the _cuda files need to be generated.

You may disregard all this rationalization, I'm a total newbie in python packages installations.

**Comment by rusty1s** [comment]
Glad that it‘s now working. It is kinda hard for me to resolve those issues, so thank you for fixing them by yourself.
