### ISSUE TITLE
run benchmark/kernel/main.py fails

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#503]
## ❓ Questions & Help

_**python benchmark/kernel/main.py**_
get following error:
`Traceback (most recent call last):
  File "benchmark/kernel/main.py", line 13, in <module>
    from sag_pool import SAGPool
  File "/home/sxm/ymq/backupspace/pytorch_geometric/benchmark/kernel/sag_pool.py", line 4, in <module>
    from torch_geometric.nn import (GraphConv, SAGPooling, global_mean_pool,
ImportError: cannot import name 'SAGPooling'`

**Comment by rusty1s** [comment]
You need PyTorch Geometric v1.3 to run the `SAGPooling` model :)

**Comment by qslim** [comment]
quick response, thx :)
