### ISSUE TITLE
Memory consumption during training

### ISSUE THREAD

**Issue by ThGravo** [rusty1s/pytorch_geometric#504]
## ❓ Questions & Help

I'm trying to train pointnet_segmentation on my own data set with graphs of roughly 100k nodes, 400k edges, and node features comprised of 6 floats. But even with a batch size of 1, I get an OOM on my GPU with 11GB.

I tried to use pytorch_memlab to asses where the memory is occupied, but only get very limited information:
```
-------------------------------------------------------------------------------
Total Tensors: 44640170 	Used Memory: 225.47M
The allocated memory on cuda:0: 228.88M
Memory differs due to the matrix alignment or invisible gradient buffer tensors
-------------------------------------------------------------------------------
```

What are your recommendations for approaching this problem?

**Comment by rusty1s** [comment]
Sadly, your graph is too big to be processed at once :( You could sample subgraphs during training, but IMO the best approach is to divide your data into many (overlapping) subgraphs as a pre-processing step, *e.g.* like it is done in the [S3DIS dataset](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/s3dis.py).

**Comment by ThGravo** [comment]
Thanks for your input. Unfortunately, it's not straight-forward to divide the graphs without losing valuable information. Can you tell which parts of the model are especially demanding? Or even better how to look into the memory consumption myself? Any specific tool or technique you're using yourself?

**Comment by rusty1s** [comment]
In each layer we create a [num_edges, num_features] matrix that needs to be stored in memory for the complete training cycle, so this is not really efficient but sadly cannot be avoided. I am fairly sure that PyTorch provides ways to access the tensors that are currently referenced, and this should give you a feel about the memory consumption of your model.
