### ISSUE TITLE
Converting a Data object back into a Networkx Graph?

### ISSUE THREAD

**Issue by joeybose** [rusty1s/pytorch_geometric#505]
Is there a simple way to convert a pytorch Data Object of a graph into a Networkx graph and vice-versa? The obvious way is to rebuild the graph by iterating through all the edges and nodes but is there a pre-built method that already does that (I wasn't able to find one with a quick search)?

**Comment by rusty1s** [comment]
Yeah, our documentation search seems to be broken at the moment, but the utils subpackage provides from_networkx and to_networkx functions :)

**Comment by joeybose** [comment]
Thanks, will definitely look at it!
