### ISSUE TITLE
torch-scatter

### ISSUE THREAD

**Issue by tonyandsunny** [rusty1s/pytorch_geometric#506]
## Environment

* OS:
* Python version:3.6
* PyTorch version:1.1.0
* CUDA/cuDNN version:8.0
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context
Hi! I have installed torch-scatter by following your suggestion.But I still met the problem that "undefined symbol: _ZNSt13runtime_errorC2EPKc"

**Comment by rusty1s** [comment]
Can you check that your CUDA versions match?
```
$ python -c "import torch; print(torch.version.cuda)"
$ nvcc --version
```

**Comment by tonyandsunny** [comment]
Yes! And I have solve this problem.
''conda install libgcc'' to update gcc

**Comment by tonyandsunny** [comment]
> Yes! And I have solved this problem.
> ''conda install libgcc'' to update gcc
