### ISSUE TITLE
Suggestions on implementation

### ISSUE THREAD

**Issue by nitinkgp23** [rusty1s/pytorch_geometric#508]
## ❓ Questions & Help

Hello! Thanks for this wonderful library. I have been trying to implement an edge-conditioned convolution on nodes, whose message passing function appears like this:
![CodeCogsEqn](https://user-images.githubusercontent.com/16208882/60967610-65455d80-a31b-11e9-9b66-26528ee7645c.png)

Here, Theta: is a vector that linearly transforms the edge feature into a scalar,
          Phi, is a weight matrix for transforming node representation,
         e (i,j) is the edge feature vector from node i to node j,
        || is the concatenation operator.

I am concatenating the neighborhood representation with the node representation.

I have written the message passing class like this. But, I am not getting the desired results. Could you please have a look and verify whether this is correct?

```
class ECNConv(MessagePassing):
    def __init__(self, in_channels, out_channels, nb_edge_features):
        super(ECNConv, self).__init__(aggr='add')
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.nb_edge_features = nb_edge_features
        self.lin_node = torch.nn.Parameter(torch.Tensor(in_channels, out_channels))
        self.lin_edge = torch.nn.Parameter(torch.Tensor(nb_edge_features))

        self.reset_parameters()

    def reset_parameters(self):
        uniform(self.in_channels, self.lin_node)
        uniform(self.nb_edge_features, self.lin_edge)

    def forward(self, x, edge_index, edge_attr):

        x = torch.matmul(x, self.lin_node)
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x, edge_attr=edge_attr)

    def message(self, x_j, edge_index, size, edge_attr):
        weight_e = torch.matmul(edge_attr, self.lin_edge).unsqueeze(1)
        return weight_e * x_j

    def update(self, aggr_out, x):

        vv = torch.cat((x, aggr_out), 1)
        return vv
```
I am still new to PyG and there might be some mistake here. But I am not able to figure it out.
Thanks a lot for the help.

**Comment by nitinkgp23** [comment]
For a better understanding, I am trying to implement this convolution:
 
![Screenshot from 2019-07-10 14-24-20](https://user-images.githubusercontent.com/16208882/60968913-83f92380-a31e-11e9-80ac-30b1b5557c52.png)

This function basically boils down to the message passing function I wrote above..

**Comment by rusty1s** [comment]
This looks mostly correct, except that you want to concatenate with the non-transformed input:
```python
class ECNConv(MessagePassing):
    def __init__(self, in_channels, out_channels, nb_edge_features):
        super(ECNConv, self).__init__(aggr='add')
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.nb_edge_features = nb_edge_features
        self.lin_node = torch.nn.Parameter(torch.Tensor(in_channels, out_channels))
        self.lin_edge = torch.nn.Parameter(torch.Tensor(nb_edge_features))

        self.reset_parameters()

    def reset_parameters(self):
        uniform(self.in_channels, self.lin_node)
        uniform(self.nb_edge_features, self.lin_edge)

    def forward(self, x, edge_index, edge_attr):
        h = torch.matmul(x, self.lin_node)
        return self.propagate(edge_index, x=x, h=h, edge_attr=edge_attr)

    def message(self, h_j, edge_attr):
        weight_e = torch.matmul(edge_attr, self.lin_edge).unsqueeze(1)
        return weight_e * h_j

    def update(self, aggr_out, x):
        return torch.cat([x, aggr_out], dim=1)
```

**Comment by rusty1s** [comment]
And according to your paper, you want `flow=target_to_source`

**Comment by nitinkgp23** [comment]
Thanks a lot :)
