### ISSUE TITLE
what about the batch of data.face

### ISSUE THREAD

**Issue by guochengqian** [rusty1s/pytorch_geometric#510]
## ❓ Questions & Help

Hi,  rusty1s, thanks for your pytorch geometric. I have a question about the batch feature. Since data.batch shows what the batch NO for data.pos, how do I know the batch NO of data.face?
Many thanks.

**Comment by rusty1s** [comment]
`batch[face[0]]` should do the trick :)

**Comment by guochengqian** [comment]
Oh, sure. Thanks.
