### ISSUE TITLE
Different Input Graph sizes with GCNConv

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#512]
## ❓ Questions & Help

Sorry if this question is basic, but I'm completely new to PyG.
So my task is using graph classification, similar to the [example on GCN](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gcn.py).
But seeing as I'm doing graph classification on graphs of different sizes, i wanted to know how to handle those. 
So for example one Data object would be:
`Data(edge_index=[2, 344], x=[168, 1], y=[1])`
and then the next would be:
`Data(edge_index=[2, 254], x=[162, 1], y=[1])`
And currently i'm getting problems with my first convolution layer:

`Traceback (most recent call last):
  File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 131, in <module>
    train()
  File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 114, in train
    F.nll_loss(model(data), data.y).backward()
  File "C:\Users\sasch\Anaconda3\envs\Thesis\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 90, in forward
    x = F.selu(self.conv1(x, edge_index))
  File "C:\Users\sasch\Anaconda3\envs\Thesis\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\sasch\Anaconda3\envs\Thesis\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 93, in forward
    return self.propagate(edge_index, x=x, norm=norm)
  File "C:\Users\sasch\Anaconda3\envs\Thesis\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 101, in propagate
    tmp = torch.index_select(tmp, 0, edge_index[idx])
RuntimeError: index out of range at ..\aten\src\TH/generic/THTensorEvenMoreMath.cpp:193

`

**Comment by rusty1s** [comment]
Hi, for [mini-batching](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches) we provide a special `DataLoader` that converts a list of `Data` objects to a single `Batch` object, where edge indices are stacked diagonally, containing one big graphs of disconnected subgraphs. Your error, however, indicates that your input data is corrupted. You can test this easily with `data.debug()`. Here, it seems that your `edge_index` contains a value that references a node not in your graph. So for a graph with `168` nodes, we require `edge_index.min() >= 0` and `edge_index.max() < 168`.

**Comment by SaschaStenger** [comment]
Thank you for the fast answer.  I reviewed my dataset and I'm not really sure on what's broken with it, as `data.debug()` returns `none`. But now i decided to test the implementation first with the `TUDataset('PROTEINS')` just to see if anything else might be an issue. 
And in here I get data like this for example: `Data(edge_index=[2, 162], x=[42, 3], y=[1])`

**Comment by SaschaStenger** [comment]
Thank you for the fast response.
Just for testing i switched to the `TUDataset('PROTEINS')` and i appearently still have the same issue with my input dimension being too variable.
`dataset = TUDataset(root='/tmp/PROTEINS', name='PROTEINS')`
`train_dataset = dataset[:900]`
`test_dataset = dataset[900:]`
`train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True)`
`test_loader = DataLoader(
    test_dataset,
    batch_size=4,
    shuffle=False)`

results in the following batches:
`Batch(batch=[234], edge_index=[2, 954], x=[234, 3], y=[4])`

`Batch(batch=[203], edge_index=[2, 622], x=[203, 3], y=[4])`

And the following error
`Traceback (most recent call last):
  File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 135, in <module>`
   ` train()`
  `File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 118, in train`
    `F.nll_loss(model(data), data.y).backward()`
  `File "C:\ProgramData\Anaconda3\envs\Thesis\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__`
    `result = self.forward(*input, **kwargs)`
  `File "C:/Users/sasch/OneDrive/Code/Thesis/3_pyttorch_geometric_test.py", line 94, in forward`
    `x = F.selu(self.conv1(x, edge_index))`
  `File "C:\ProgramData\Anaconda3\envs\Thesis\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__`
   ` result = self.forward(*input, **kwargs)`
  `File "C:\ProgramData\Anaconda3\envs\Thesis\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 95, in forward`
    `self.cached_num_edges, edge_index.size(1)))`
`RuntimeError: Cached 954 number of edges, but found 622
`

**Comment by rusty1s** [comment]
You need to remove the `cached` flag of `GCNConv` when learning on multiple graphs :)

**Comment by SaschaStenger** [comment]
Thank you so much! I feel pretty stupid and relieved at the same time. Best feeling ever =)
