### ISSUE TITLE
Question about the characteristic matrix data.x of data

### ISSUE THREAD

**Issue by PerfectVeo** [rusty1s/pytorch_geometric#514]
## ❓ Questions & Help
Why does the original dataset Cora, Citeseer's data.x contain a lot of floating point data, not just 0 or 1. What does this mean?

Looking forward to your reply~

**Comment by rusty1s** [comment]
The node features of those datasets contain only `0` and `1`, just saved in a dense floating point matrix which eases the use of it in neural networks.
```python
from torch_geometric.datasets import Planetoid

dataset = Planetoid('/tmp/Cora', 'Cora')
data = dataset[0]

print(data.x.numel())
print((data.x == 0).sum().item() + (data.x == 1).sum().item())
```
```
3880564
3880564
```

**Comment by PerfectVeo** [comment]
Thank you for your reply. I have found a feature regularization function that solves my problem.
