### ISSUE TITLE
Encoding Edge Features

### ISSUE THREAD

**Issue by AneeshaaSC** [rusty1s/pytorch_geometric#516]
I wanted to try and modify the GAT to include edge features as well, as suggested in 
[https://arxiv.org/abs/1809.02709] and
[https://www.researchgate.net/publication/327570842_Adaptive_Edge_Features_Guided_Graph_Attention_Networks]

Is there already a way in Pytorch Geometric, to encode the edge directions as multidimensional edge features  as described in the papers?

**Comment by rusty1s** [comment]
Sure, you can simply integrate the edge features to the node features in the `message` function:
```python
def message(self, x_i, x_j, edge_attr):
    ...
```

**Comment by AneeshaaSC** [comment]
But in case of datasets like Cora/Citeseer, the authors suggest encoding the directions of edges as:

![image](https://user-images.githubusercontent.com/32979123/61040973-85cbf100-a3c9-11e9-9644-9ef944e56428.png)

Is there a way to do this in PyG?

**Comment by rusty1s** [comment]
I guess you can map your edge features to this format in a pre-processing step.

**Comment by AneeshaaSC** [comment]
I think the GAT induces structure in these steps:

```
        edge_index,_ = add_self_loops(edge_index, num_nodes=x.size(0))
        print('added self loops:',edge_index.shape)
        row, col = edge_index
        alpha = torch.cat([x[row], x[col]], dim=-1) #concatenates
        print('alpha after concatenate',alpha.shape)
```
But if the edges are now a matrix with features, of shape NxNxP as suggested in the paper, how is the structure supposed to be induced?

**Comment by rusty1s** [comment]
The adjacency matrix is still a sparse matrix with shape `ExP`, and given you have a vector `inv` which maps each edge to its reversed one, you can then compute `alpha`, *e.g.*, by:
```python
row, col = edge_index
alpha = torch.cat([x[row], x[col], edge_attr, edge_attr[inv], edge_attr + edge_attr[inv]], dim=-1)
```

**Comment by AneeshaaSC** [comment]
But, I couldn't find the adjacency matrix used in the GAT.  I pre-processed the edge_index tensor Cora dataset to be an augmented edge matrix of shape : [2708x2708x3] and x  at this point is of shape: [2708, 8, 8].

I was just confused about how I'd concatenate the edge matrix with the data x.

**Comment by AneeshaaSC** [comment]
I mean, to concat I think edge_attr, x[row] and x[col] must match in all dimensions but the last one. But the encoding is such that if there exists a bidirectional edge between node 0 and node 633, and  the augmented edge vector would be [ 1 1 2] (i.e size 1x3).

**Comment by rusty1s** [comment]
Yes, and for all edges you have an edge feature matrix of shape [num_edges, 3], so the dimensions should match and you can concatenate edge_attr with x[row] and x[col].

**Comment by AneeshaaSC** [comment]
'''
        print('out shape before scatter ', out.shape) # torch.Size([13264, 1, 7])
        out = scatter_add(out, row, dim=0, dim_size=x.size(0))
        print('after scatter ',out.shape) #torch.Size([2708, 1, 7])
'''' 
Could you please tell me where I can read about what scatter_add does?

**Comment by rusty1s** [comment]
You can read about it [here](https://pytorch-scatter.readthedocs.io/en/latest/).

**Comment by AneeshaaSC** [comment]
Has the definition or source code of the GATConv changed recently?

**Comment by rusty1s** [comment]
Not recently, but it now also uses the unified MessagePassing interface.

**Comment by AneeshaaSC** [comment]
With the current code, I've been trying to include edge features as well. But I'm unsure of the way I'm injecting these features the right way at: [](https://colab.research.google.com/drive/1daibj3ovfy8wKZWubrT6PhbLY2MTWpUA)

But I'm facing the below issue. Can you please advise on the right way of inducing edge features to the GAT?


---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-70-8eee92b32726> in <module>()
     18 
     19 for epoch in range(1, 200):
---> 20       train()
     21       log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
     22       print(log.format(epoch, *test()))

5 frames
<ipython-input-70-8eee92b32726> in train()
      3       optimizer.zero_grad()
      4       with torch.autograd.set_detect_anomaly(True):
----> 5         F.nll_loss(model(model.edgemat)[data.train_mask], data.y[data.train_mask]).backward()
      6         optimizer.step()
      7 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

<ipython-input-68-319d9b070d05> in forward(self, edgemat)
      8     def forward(self,edgemat): #it performs the actual computation, that is, it outputs a prediction, given the input x
      9         x = F.dropout(data.x, p=0.6, training=self.training)
---> 10         x,e1 = self.conv1(x, data.edge_index,self.edgemat)
     11         x = F.elu(x)
     12         x = F.dropout(x, p=0.6, training=self.training)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

<ipython-input-14-92adc31749e8> in forward(self, x, edge_index, size)
     43                  None if x[1] is None else torch.matmul(x[1], self.weight))
     44 
---> 45         return self.propagate(edge_index, size=size, x=x)
     46 
     47 

/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/message_passing.py in propagate(self, edge_index, size, **kwargs)
     72 
     73         size = [None, None] if size is None else list(size)
---> 74         assert len(size) == 2
     75 
     76         i, j = (0, 1) if self.flow == 'target_to_source' else (1, 0)

AssertionError:

**Comment by rusty1s** [comment]
`return self.propagate(edge_index,edgemat, size=size, x=x)` is no valid format. Please use `return self.propagate(edge_index, size=size, edgemat=edgemat, x=x)`.

**Comment by AneeshaaSC** [comment]
1. edgemat is pre-computed and fed into forward method
```
class newNet(torch.nn.Module): #it defines the parts that make up the model 
    def __init__(self):
        super(newNet, self).__init__()
        self.conv1 = New_GATConv(coradata.num_features, 10, heads=1, dropout=0.6)
        self.conv2 = New_GATConv(10 * 1, coradata.num_classes, heads=1, concat=True, dropout=0.6)
        self.edgemat = edgemat

    def forward(self,edgemat): 
        x = F.dropout(data.x, p=0.6, training=self.training)
.....
.....
   # in the GATConv class: 
    def forward(self,edgemat):
        x = F.dropout(data.x, p=0.6, training=self.training)
        x,e1 = self.conv1(x, data.edge_index,self.edgemat)
        x = F.elu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x,e2 = self.conv2(x, data.edge_index,e1)
        return F.log_softmax(x, dim=1)   # new: return F.log_softmax(x, dim=-1) -1 or 1?
....
....
```

2. forward method calls propagate which is supposed to use edgemat to compute attention:
```
return self.propagate(edge_index, size=size, edgemat=edgemat, x=x)
```
3. propagate calls message internally. I need to return the modified edgemat (edgemat = edgemat*alpha) computed here to the next layer as the new edge features to be used in that layer.
```
def message(self, edge_index_i, x_i, x_j, size_i, edgemat):
...
...
   return x_j * alpha.view(-1, self.heads, 1),edgemat
```
4. I wasn't sure how or where I must include edgemat so I can use it in the next layer as edge features. Currently this is the update function:
```
    def update(self, aggr_out):
....
.....
        return aggr_out
```

Could you please clarify how to go about returning edgemat to the next layer?

**Comment by rusty1s** [comment]
I see. You cannot return a tuple in the `message` function. This is a current limitation, but you can do something like this:
```python
def forward(self, ...)
    out = self.propagate(edge_index, size=size, x=x, edgemat=edgemat)
    edgemat = self.__edgemat__
    self.__edgemat__ = None
    return out, edgemat

def message(self, ..., edgemat):
    ...
    self.__edgemat__ = edgemat
    return x_j * alpha.view(-1, self.heads, 1)

**Comment by AneeshaaSC** [comment]
After making these changes, I get :

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-8eee92b32726> in <module>()
     20       train()
     21       log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
---> 22       print(log.format(epoch, *test()))

1 frames
<ipython-input-15-8eee92b32726> in test()
      9 def test():
     10       model.eval()
---> 11       logits, accs = model(), []
     12       for _, mask in data('train_mask', 'val_mask', 'test_mask'):
     13           pred = logits[mask].max(1)[1]#

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'edgemat'

https://colab.research.google.com/drive/1daibj3ovfy8wKZWubrT6PhbLY2MTWpUA

**Comment by rusty1s** [comment]
Remove the `edgemat` argument from the forward pass `def forward(self,edgemat)`.

**Comment by AneeshaaSC** [comment]
> Not recently, but it now also uses the unified MessagePassing interface.

Is there some place I can read more about the MessagePassing interface, like what it is, why it is used, etc.?

**Comment by rusty1s** [comment]
There is a tutorial about the MessagePassing interface in the documentation. The reason it is used is to simplify and unify the implementation of operators that solely rely on message passing (like any proposed graph convolutional operator). With this interface, we can describe any GNNs by the use of three functions: The message function to compute messages that are sent along the edges, an aggregation function that combines those messages, and an update function to update the central node information based on the aggregated messages.

**Comment by agamemnonc** [comment]
> I see. You cannot return a tuple in the `message` function. This is a current limitation, but you can do something like this:
> 
> ```python
> def forward(self, ...)
>     ...
>     out = self.propagate(edge_index, size=size, x=x, edgemat=edgemat)
>     edgemat = self.__edgemat__
>     self.__edgemat__ = None
>     return out, edgemat
> 
> def message(self, ..., edgemat):
>     ...
>     self.__edgemat__ = edgemat
>     return x_j * alpha.view(-1, self.heads, 1)
> ```

Would edge features updating be supported in that way? Thanks

**Comment by rusty1s** [comment]
Sure, that works too.
