### ISSUE TITLE
Variable length node features

### ISSUE THREAD

**Issue by brunocous** [rusty1s/pytorch_geometric#517]
## ❓ Questions & Help

I have a graph with variable length node feature vectors. Is there a way to incorporate this behavior using the pytorch_geometric data class? According to the documentation, `data.x` has to be of shape `[num_nodes, num_node_features]`, which does not fit my use case nicely.

Ultimately, I would like to embed each variable size node feature vector to a fixed size, in order to apply the layers defined in this library.

**Comment by rusty1s** [comment]
You can use PyTorch to achieve this, e.g., by using padded_sequence.

**Comment by brunocous** [comment]
Cool, will try using that! Thanks!
