### ISSUE TITLE
install problem nvcc

### ISSUE THREAD

**Issue by OPAYA** [rusty1s/pytorch_geometric#519]
## Environment

* OS: Ubuntu
* Python version: 3.6.8
* PyTorch version:1.1.0
* CUDA/cuDNN version: 9.0 / 
* GCC version:  5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [o] I followed the installation guide.
- [o ] I cannot find my error message in the FAQ.
- [ o] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ o] I have cloned the repository and tried a manual installation from source.
- [ o] I do have multiple CUDA versions on my machine.
- [ o] I checked if the official extension example runs on my machine.
- [ ]o The offical extension example runs on my machine.

## Additional context

I've installed using official documentation.
But I see the error message about 'cannot find nvcc'
i checked my path '/usr/local/cuda-9.0/bin/nvcc

But error message is '/usr/local/cuda/bin/nvcc'

I think it is a different path... how can I modification path?

**Comment by rusty1s** [comment]
So do you have the CUDA toolkit installed? Do you have the folder `cuda` in `/usr/local`? Is there a binary called `nvcc` inside the `bin` dir? If all of this is yes, add the `bin` dir to your path:
```
export $PATH=/usr/local/cuda/bin:$PATH
```
If not, please download and install the CUDA toolkit from [here](https://developer.nvidia.com/cuda-toolkit).

**Comment by OPAYA** [comment]
Yes i'm already install CUDA toolkit.  I have a folder called 'cuda-9.0' and have a nvcc inside bin dir.
But when i installed 'torch-geometric sparse', an error message occurs 'cannot find /usr/local/cuda/bin/nvcc'

**Comment by rusty1s** [comment]
Ok, but you do not have it in your path? PyTorch then tries  the default path `/use/local/cuda`. You can also try to symlink your CUDA install to `/usr/local/cuda`.

**Comment by OPAYA** [comment]
Oh! I was mistaken Thanks
