### ISSUE TITLE
dynamic  graph with different edges and nodes on the time dimension 

### ISSUE THREAD

**Issue by ICDI0906** [rusty1s/pytorch_geometric#522]
## ❓ Questions & Help

Hello~, recently I meet some question about the dynamic graph on the time dimension. Is there any solution for this. Looking forward to replying.

**Comment by rusty1s** [comment]
For dynamic graph learning, we provide an [example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/renet.py) using [ReNet](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.models.RENet) on two datasets, although many other approaches should be straightforward to implement.

**Comment by ICDI0906** [comment]
thanks very much. Hope this repo become stronger!

**Comment by leesunfreshing** [comment]
Hi, is there a more generative example for this purpose? To the best of my understanding, the output of ReNet in PGL remains the identical shape through time, which is not a graph structured data. I am wondering how to process the dynamic graph for regular GNN, such as GAT, to produce a graph structured data as well?
