### ISSUE TITLE
A strange global_mean/max_pool bug caused by torch_scatter

### ISSUE THREAD

**Issue by cszhangzhen** [rusty1s/pytorch_geometric#523]
## 🐛 Bug
When performing global_mean_pool operation, it occurs a error as follows:
'RuntimeError: Invalid index in scatterAdd at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:523'

As for global_max_pool operation, a more complicated error occurs:
7efcc88a1000-7efcc88a2000 r--p 00025000 08:25 3674717                    /lib/x86_64-linux-gnu/ld-2.23.so
7efcc88a2000-7efcc88a3000 rw-p 00026000 08:25 3674717                    /lib/x86_64-linux-gnu/ld-2.23.so
7efcc88a3000-7efcc88a4000 rw-p 00000000 00:00 0 
7ffd0f9ea000-7ffd0fa0f000 rw-p 00000000 00:00 0                          [stack]
7ffd0fb42000-7ffd0fb45000 r--p 00000000 00:00 0                          [vvar]
7ffd0fb45000-7ffd0fb47000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

I think this is mainly caused by torch_scatter's implementation.

## To Reproduce

```
import torch 
from torch_geometric.nn import global_mean_pool, global_max_pool

batch_idx_1 = torch.tensor([0, 0, 1, 0, 0, 1, 0, 0, 1, 0])
batch_idx_2 = torch.tensor([1, 1, 0, 1, 1, 0, 0, 0, 0, 1])
# x = torch.randn(10,2)
x = torch.Tensor([[-3.5589e-02,  5.6682e-04],
        [ 1.8057e+00,  1.3927e+00],
        [-5.2732e-01,  2.1215e-01],
        [ 1.0310e+00, -4.1751e-01],
        [-5.6693e-01, -5.2773e-02],
        [-8.8271e-01,  1.4868e-02],
        [ 1.0195e+00, -1.2755e+00],
        [-6.2838e-02,  2.0449e-01],
        [ 1.9478e-01,  6.2411e-01],
        [-4.0343e-01,  5.6862e-01]])
z1 = global_mean_pool(x, batch_idx_1)
z2 = global_mean_pool(x, batch_idx_2)
```
In this case, z1 will give an error, while z2 runs successfully.
What really strange is that this does not always happen.
```
import torch
import numpy as np
from troch_geometric.nn import global_mean_pool

batch_idx = torch.tensor(np.random.randint(2, size=100))
x = torch.randn(100,2)
z = global_mean_pool(x, batch_idx)
```
Some of them may result in giving an error while some are not.

## Expected behavior
```
z1 = tensor([[ 0.3982,  0.0601],
        [-0.4051,  0.2837]])

z2 = tensor([[-0.0517, -0.0440],
        [ 0.3662,  0.2983]]) 
```

## Environment

* OS: Mac OS 10.14.5
* Python version: 3.6
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 10.0
* GCC version: 7.3.0
* Any other relevant information: torch_scatter 1.3.1

## Additional context
However, if I explicitly specify the size like below, it works!
```
z1 = global_mean_pool(x, batch_idx_1, 2)
```

**Comment by rusty1s** [comment]
Are you running PyG v1.3 or master? In v1.3, global pooling expects nodes in one example to be contiguous, and the size parameter is inferred by batch[-1]. In your case, this crashes in half of all tries.

**Comment by cszhangzhen** [comment]
Oh, yes, I'm using PyG v1.3.0
The problem is indeed caused by `size = batch[-1].item() + 1`
The master' implementation `size = batch.max().item() + 1` is more flexible.

Thanks!  This is a really cool package.
