### ISSUE TITLE
Add molecule names to QM9

### ISSUE THREAD

**Issue by MLjian** [rusty1s/pytorch_geometric#524]
Could you offer the molecule name for the qm9 dataset of PYG? Thank you!

**Comment by rusty1s** [comment]
Will see what I can do. The ordering of the molecules is the same as [here](http://moleculenet.ai/) though, so if you do not want to wait, you can extract them by yourself.

**Comment by MLjian** [comment]
Hi, could you send one code processing qm9 from raw dataset? I am not famiIiar with the molecule . And I just want to repeat your processing work for qm9. You can sent to 1069525306@qq.com . or you provide one leaning address. Thankyou!

**Comment by rusty1s** [comment]
Sure, have a look [here](https://gist.github.com/rusty1s/159eeff0d95e0786d220a164c6edd021)

**Comment by MLjian** [comment]
> Sure, have a look here

Thankyou very much

**Comment by Mario-Liu** [comment]
> 
> 
> > Sure, have a look here
> 
> Thankyou very much

perhaps you want this  "m.GetProp('_Name')" for the sdf file.

**Comment by rusty1s** [comment]
Done, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/qm9.py#L202-L205) :)
