### ISSUE TITLE
datasets download error

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#525]
## ❓ Questions & Help

`ssl.CertificateError: hostname 'ls11-www.cs.uni-dortmund.de' doesn't match 'ls11-www.cs.tu-dortmund.de'`
It seems that the downloading site has changed in code, but this change isn't included in provided installation package?

**Comment by rusty1s** [comment]
Try upgrading to PyTorch Geometric v1.3. :)

**Comment by qslim** [comment]
solved, thx :)

**Comment by wxfsd** [comment]
How to upgrade PYG?

**Comment by rusty1s** [comment]
```
pip install --upgrade torch-geometric
```
