### ISSUE TITLE
Might want to change PointConv name in the framework

### ISSUE THREAD

**Issue by lelouedec** [rusty1s/pytorch_geometric#529]
There is a quite recent paper which cam out at cvpr 2019 : https://arxiv.org/abs/1811.07246, called PointConv. Just to avoid confusion, it could be helpful to rename the PointConv operation in the framework.

**Comment by rusty1s** [comment]
Good point. Thank you!

**Comment by QuanticDisaster** [comment]
I would like to up the topic as I got confused too

**Comment by rusty1s** [comment]
Any alternative naming proposals? `PointNetConv`?

**Comment by lelouedec** [comment]
PnConv or PointNetConv could be cool !

**Comment by rusty1s** [comment]
I renamed the `PointConv` to `PointNetConv`, see https://github.com/rusty1s/pytorch_geometric/commit/a675ef9750d034908f52d9a5fe7687b06dec3ecc.

I will deprecate `PointConv` in the next release and will remove it afterwards.
