### ISSUE TITLE
Unnormalized ChebConv

### ISSUE THREAD

**Issue by Stannislav** [rusty1s/pytorch_geometric#530]
## 1. Missing Documentation
It was already discussed in https://github.com/rusty1s/pytorch_geometric/issues/242 that the Laplacian in `ChebConv` is `L = 1 - A_norm` and not `(tilde L) = (2 / lambda_max) L - 1`. In the documentation, however, it says that the convolution is as in the original paper, and that the normalised and scaled Laplacian is used, which is not correct.

I suggest that the documentation in https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.ChebConv makes clear that the normalisation is different, otherwise it's quite hard to spot.

## 2. Wrong Laplacian
As it is now, `ChebConv.norm` computes `L = -A_norm` instead of `L = 1 - A_norm`. I think the following line should be added right before the `return` statement:

```python
        edge_index, norm = add_self_loops(edge_index=edge_index,
                                          edge_weight=norm,
                                          fill_value=1,
                                          num_nodes=num_nodes)
```

**Comment by rusty1s** [comment]
Thank you for this issue, but I still think that the `ChebConv` computation is correct. Given that we have `L = I - A_norm`, the scaled Laplacian `\tilde{L} = 2L / lambda_max - I` can be rewritten to:
```
\tilde{L} = 2(I - A_norm) / 2 - I = - A_norm`
```

**Comment by Stannislav** [comment]
I see, thanks. So is there any motivation for approximating `lambda_max = 2` other than that it simplifies the computation?

It's true that computing the eigenvalues at each convolution would be super expensive, maybe `labmda_max` could be pre-computed and passed as an optional parameter?

**Comment by rusty1s** [comment]
Sounds like a good idea. We could add the argument `lambda_max` to the `forward` function like
```python
def forward(self, x, edge_index, edge_weight=None, batch=None, lambda_max=None)
```
which would expect a scalar or zero-sized tensor for operating on single graphs, and a tensor of shape `[num_graphs]` for working on mini-batches. In addition, we could provide a transform to compute `lambda_max`. Are you interested in submitting a PR for this?

**Comment by Stannislav** [comment]
Yeah sure. I'm tinkering on some models at the moment anyway, so I'll try to implement that as well.
