### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by nassarofficial** [rusty1s/pytorch_geometric#537]
## ❓ Questions & Help

Hello, first thank you for the repo and library. I was wondering what is the best way to start with the examples? I am a bit lost on what each one does, or what the problem they are trying to solve, any pointer on where to start?

**Comment by rusty1s** [comment]
I agree with you that the examples are becoming a bit overwhelming. I will try to add some introductory comments to them and rename them to have a uniform naming convention. The basic scheme of the examples is however straightforward:

Most examples aim to reproduce the results of a specific paper/method. So we have an example for the `GCN` operator called `gcn.py`, an example for the `GAT` operator called `gat.py`, and so on. Those examples are therefore best understood by first reading the specific paper. In addition, some examples just show how to train a specific dataset, *e.g.*, `reddit.py` (which is a huge dataset which cannot be trained as a whole), or combine some general methods into a single example, *e.g.*, `autoencoder.py`. If you follow the list of methods in the README, most of what the examples are doing should be clear by their name.

Feel free to ask if you face any further questions. As I said before, I will try to clean it up to be more intuitive in the future :)

**Comment by nassarofficial** [comment]
Thanks for the quick reply and your effort.
