### ISSUE TITLE
GCNConv execution error

### ISSUE THREAD

**Issue by kekmodel** [rusty1s/pytorch_geometric#538]
## ❓ Questions & Help

    class GCNConv(MessagePassing):
        def __init__(self, in_channels, out_channels):
            super().__init__(aggr='add')
            self.lin = torch.nn.Linear(in_channels, out_channels)
            
        def forword(self, x, edge_index):
            num_nodes = x.shape[0]
            edge_index, _ = add_self_loops(edge_index, num_nodes=num_nodes)
            x = self.lin(x)
            return self.propagate(edge_index, size=(num_nodes, num_nodes), x=x)
    
        def message(self, x_j, edge_index, size):
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        
        def update(self, aggr_out):
            return aggr_out

and then

    device = torch.device('cuda:1')
    conv = GCNConv(16, 32).to(device)
    x = torch.randn(3, 16, device=device)
    edge_index = torch.tensor([[0, 1, 1, 2],
                               [1, 0, 2, 1]], dtype=torch.long, device=device)
    x_ = conv(x, edge_index)

error

    NotImplementedError                       Traceback (most recent call last)
    <ipython-input-9-8ae792540f8a> in <module>
    ----> 1 x_ = conv(x, edge_index)
    
    ~/anaconda3/envs/jdkim/lib/python3.7/site-packages/torch/nn/modules/module.py in         
    __call__(self, *input, **kwargs)
        491             result = self._slow_forward(*input, **kwargs)
        492         else:
    --> 493             result = self.forward(*input, **kwargs)
        494         for hook in self._forward_hooks.values():
        495             hook_result = hook(self, input, result)
    
    ~/anaconda3/envs/jdkim/lib/python3.7/site-packages/torch/nn/modules/module.py in                         
    forward(self, *input)
         86             registered hooks while the latter silently ignores them.
         87         """
    ---> 88         raise NotImplementedError
         89 
         90     def register_buffer(self, name, tensor):
    
    NotImplementedError:

**Comment by kekmodel** [comment]
forword -> forward....................

**Comment by rusty1s** [comment]
`forward` :)
