### ISSUE TITLE
AttributeError: 'FaceToEdge' object has no attribute 'keys'

### ISSUE THREAD

**Issue by JsBlueCat** [rusty1s/pytorch_geometric#547]
from torch_geometric.transforms import FaceToEdge

dataset = ModelNet(root=opt.datasets, name='40',pre_transform=FaceToEdge)

i get error: AttributeError: 'FaceToEdge' object has no attribute 'keys'

**Comment by rusty1s** [comment]
You need to instantiate the transform:
```python
dataset = ModelNet(root=opt.datasets, name='40',pre_transform=FaceToEdge())
```

**Comment by JsBlueCat** [comment]
> ```python
> FaceToEdge
> ```
thanks for help ~ i have fixed this issue
