### ISSUE TITLE
Remove isolated nodes

### ISSUE THREAD

**Issue by JsBlueCat** [rusty1s/pytorch_geometric#548]
is there any function to remove  isolated nodes?
i find that modelNet40 containes much more ioslated nodes

**Comment by rusty1s** [comment]
There currently is no such function in PyTorch Geometric, although this is a good feature request. In the meantime, you can remove isolated nodes by yourself, *e.g.*, with the following (untested) code:
```python
mask = torch.zeros(num_nodes, dtype=torch.uint8)
mask[edge_index.flatten()] = 1
assoc = torch.full((num_nodes, ), -1, dtype=torch.long))
assoc[mask] = torch.arange(mask.sum())

new_edge_index = assoc[edge_index]
```

**Comment by rusty1s** [comment]
Added to [master](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/isolated.py#L24-L67).

**Comment by rusty1s** [comment]
And [a transform](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.RemoveIsolatedNodes) :)

**Comment by cppp** [comment]
Hi, first of all thanks for this greate feature
i use that as bellow:
`
import torch_geometric.transforms as T
transform = T.Compose([T.remove_isolated_nodes.RemoveIsolatedNodes()])
print("1) num nodes: ", pyg_dg.num_nodes, "x size:", pyg_dg.x.size())
pyg_dg = transform(pyg_dg)
print("2) num nodes: ", pyg_dg.num_nodes, "x size:", pyg_dg.x.size())
`
what i get is:
1) num nodes:  97 x size: torch.Size([97, 130])
2) num nodes:  95 x size: torch.Size([97, 130])
there is change in num nodes and code removed 2 isolated nodes
but i think number of features after this transform should be   size: torch.Size([95, 130])
so should i use 
`
pyg_dg.x = pyg_dg.x[:pyg_dg.num_nodes]
`
after transform or i should do something else?

**Comment by rusty1s** [comment]
Mh, that sounds indeed not correct, but I cannot spot any error in `RemoveIsolatedNodes` and we actually test against this. Do you can share your `data` object with us? Which PyG version are you using?

**Comment by cppp** [comment]
`print(torch_geometric.__version__)
`
gives me 
2.1.0
i uploaded two of my graphs in [https://github.com/cppp/mypygGraphs](url)

**Comment by rusty1s** [comment]
Thanks, this is really helpful. I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/6308.

**Comment by AmosDinh** [comment]
Is there a functionality to know, which nodes are removed, meaning a mapping from the data without isolated nodes back to the data with isolated nodes?

**Comment by rusty1s** [comment]
Yeah, filtering is currently only supported for tensor like data :(

**Comment by AmosDinh** [comment]
That is good to know, and probably sensible, thanks.

Matthias Fey ***@***.***> schrieb am Mo., 9. Okt. 2023, 22:50:
