### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by tbright17** [rusty1s/pytorch_geometric#56]
Trying to install pytorch_geometric.

While installing dependencies (cluster, scatter, sparse...) with 0.4.1 pytorch, met the error "fatal error: torch/extension.h: No such file or directory compilation terminated". Based on https://github.com/NVIDIA/apex/issues/83, upgraded pytorch to 1.0. Installations were all ok.

But when I tried to run enzymes_diff_pool.py, it gave me error:

```
Traceback (most recent call last):
  File "enzymes_diff_pool.py", line 157, in <module>
    train_loss = train(epoch)
  File "enzymes_diff_pool.py", line 138, in train
    loss.backward()
  File "/mnt/cephfs2/asr/users/ming.tu/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/cephfs2/asr/users/ming.tu/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

Maybe the code needs to be updated?

Thanks,
Ming

**Comment by rusty1s** [comment]
Hi,
I am currently in the process updating to PyTorch 1.0, just give me a day or two. Sorry!

**Comment by rusty1s** [comment]
Should be fixed. Please reopen if you encounter any issues.

**Comment by tbright17** [comment]
Yes. It works. Thanks a lot!
