### ISSUE TITLE
Documentation about RGCNConv

### ISSUE THREAD

**Issue by zc-alexfan** [rusty1s/pytorch_geometric#561]
## ❓ Questions & Help

Just some clarifications about `RGCNConv`: 

- The formula seems to indicate the layer always uses self-loop. Does it mean we don't need include self-loop edges in `edge_index` and don't need to indicate self-looped edge types in `edge_type`? 

Which of the followings is the correct use of this layer? 
1. Add all edges including self-loop edges into `edge_index` when constructing `Data`. Label the self-looped edges as edge type 0 and the other edges with its associated type in `edge_type`. 
2. Add all edges but **not including** self-loop edges into `edge_index`  when constructing `Data`. Only construct `edge_type` for non-looped edges starting starting from edge type `0`.

**Comment by rusty1s** [comment]
The second one. We could add an argument to the RGCNConv to make this optional though.

**Comment by zc-alexfan** [comment]
So, assuming I am doing option 2: 
1. Even if I don't add self-looped edges, they will be added anyway. 
2. All my other non-looped edges should have an edge type starting from `0` instead of `1`? Even though the formula starting from `0`?

**Comment by rusty1s** [comment]
I see, the formula is indeed misleading and fixed in master. 
1. yes
2. yes
3. yes
In addition, the `RGCNConv` now supports an additional argument `root_weight` to make the transformation of root nodes optional. In case `root_weight=False`, the user needs to manually add self-loops to the graph.

**Comment by zc-alexfan** [comment]
Great! Thanks for always being so responsive!
