### ISSUE TITLE
How to custom Batch.from_data_list to support custom features?

### ISSUE THREAD

**Issue by mooninrain** [rusty1s/pytorch_geometric#562]
## ❓ Questions & Help
I'm trying to add some custom features through transform of InMemoryDataset, like:

```
class add_features(object):
    def __call__(self,data):
         data.feature1 = torch.zeros(data.num_nodes,1)
         data.feature2 = torch.zeros(data.num_edges,1)
         return data
```

But then I found after batching I can't find these custom features. How can I make custom features able to be batched?

**Comment by rusty1s** [comment]
The syntax for transforms is `def __call__(self, data):`. This should work :)

**Comment by mooninrain** [comment]
> 
> 
> The syntax for transforms is `def __call__(self, data):`. This should work :)

Sorry, it was a mistake that github automatically edits '__call__' as 'call', I've revised the question.

So actually it's not the syntax problem... I can observe changes in pre-defined features like
`data.x = torch.zeros(data.num_nodes,1)`
But as for custom features like
`data.some_new_feature = torch.zeros(data.num_nodes,1)`
I can get them when I write like
`print(dataset[0].some_new_feature)`
But I can't get them when batching, like
`
dataloader = DataLoader(dataset, batch_size=16)
for batch in dataloader:
    print(batch.some_new_feature)
`

**Comment by rusty1s** [comment]
I can not reproduce this. The following code works as expected:
```python
import torch
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader


class add_features(object):
    def __call__(self, data):
        data.feature1 = torch.zeros(data.num_nodes, 1)
        data.feature2 = torch.zeros(data.num_edges, 1)
        return data


dataset = TUDataset('/tmp/MUTAG', 'MUTAG', transform=add_features())
loader = DataLoader(dataset, batch_size=128)

for data in loader:
    print(data.feature1.size())
    print(data)

```
