### ISSUE TITLE
gpu usage always under 30% in graph classification task, is this normal?

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#563]
## ❓ Questions & Help

How can improve gpu usage and speed up training process? I tried to set bigger batch_size, but it looks like no help for speeding up. I'm not sure batch_size has any relationship with training speed.

**Comment by rusty1s** [comment]
Can you elaborate with a concrete example? `batch_size` should indeed have a relation to training speed as long as the GPU is not fully utilized.

**Comment by qslim** [comment]
related issue: #566

**Comment by rusty1s** [comment]
Closed in favour of #566
