### ISSUE TITLE
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory when I check /usr/local/cuda/lib64. I found libcudart.so.9.0.

### ISSUE THREAD

**Issue by guoyan1996** [rusty1s/pytorch_geometric#564]
## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [x] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by guoyan1996** [comment]
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
when I check /usr/local/cuda/lib64. I found libcudart.so.9.0.

**Comment by JsBlueCat** [comment]
> ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
> when I check /usr/local/cuda/lib64. I found libcudart.so.9.0.

it may be your cuda version error.  install cuda9.2 with the doc on nvidia website
