### ISSUE TITLE
pytorch_geometric/benchmark/kernel/diff_pool.py  doesn't run properly on gpu?

### ISSUE THREAD

**Issue by qslim** [rusty1s/pytorch_geometric#566]
## ❓ Questions & Help

top
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
 11238 sxm       20   0  0.098t 1.827g 398736 R  1153  2.9   5:14.37 python

very slow. Cpu usage is high and gpu usage is volatile.

**Comment by qslim** [comment]
reproduce:
dataset = IMDB-MULTI

**Comment by rusty1s** [comment]
I checked this and you are right. GPU usage is very low (this is expected because the model and datasets are small), and the bottleneck of the runtime is the `ToDense` transform for DiffPool.
