### ISSUE TITLE
Propogating a value from one layer to another

### ISSUE THREAD

**Issue by AneeshaaSC** [rusty1s/pytorch_geometric#567]
I am creating a modification of the GAT_Conv called EGAT that uses both edge and node features, makes use of attention mechanism and performs node classification.  (Trying to implement: https://arxiv.org/abs/1809.02709)

During Forward prop, I create and initialize a matrix in layer 1 called 'edgemat' that has augmented edge features. I would like to use this very same matrix(I do not want to recreate and initialize it in Layer 2) as edge features in the second layer. How do I go about doing that? 
Code:
https://colab.research.google.com/drive/1tq9idg_hb-aeLD2CCj-4xXF5MeGOhDHp

I'm not sure how to do it, but I made this a Parameter and encounter this error during forward prop in the second layer:

ValueError: Cannot assign non-leaf Tensor to parameter 'edgemat'. Model parameters must be created explicitly. To express 'edgemat' as a function of another Tensor, compute the value in the forward() method.

Forward prop through the first layer is fine.

**Comment by rusty1s** [comment]
Couldn't you create the edge matrix in a pre-processing step, and just input (and return it) it in the `forward` method?

**Comment by AneeshaaSC** [comment]
```
class EGAT(torch.nn.Module):

    def __init__(self,
                 in_channels,
                 out_channels,
                 #edgemat,
                 heads=1,
                 concat=True,
                 negative_slope=0.2,
                 dropout=0,
                 bias=True,):
        super(EGAT, self).__init__()

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.heads = heads
        self.concat = concat
        self.negative_slope = negative_slope
        self.dropout = dropout
        #self.edgemat = edgemat
.....
.....

    def forward(x, edge_index, edgemat):
....
....

# computing the edge matrix outside the forward method

edgemat = torch.zeros((coradata[0].num_nodes,coradata[0].num_nodes,3)).to(device)
row = coradata[0].edge_index[0]
col = coradata[0].edge_index[1]
        
for i in range(0,len(row)):
 
  edgemat[row[i]][col[i]][0] = 1
  edgemat[row[i]][col[i]][1] = 1
  edgemat[row[i]][col[i]][2] = edgemat[row[i]][col[i]][0] + edgemat[row[i]][col[i]][1]
      
# doubly stochastic normalization
edgemat = torch.nn.functional.softmax(edgemat, dim=1) # all rows sum up to 1 now
edgemat = torch.nn.functional.softmax(edgemat, dim=0) # all rows sum up to 1 now


class Net(torch.nn.Module): #it defines the parts that make up the model 
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = EGAT(coradata.num_features, 10,  heads=1, dropout=0.6, concat=False)
        self.conv2 = EGAT(10 * 3, coradata.num_classes,  heads=1, concat=True, dropout=0.6)
        self.edgemat = edgemat

    def forward(self,edgemat): 
        print('edgemat shape',edgemat.shape)
        x = F.dropout(data.x, p=0.6, training=self.training)
        x,e1 = self.conv1(x, data.edge_index, edgemat)
        x = F.elu(x)
        print('x after elu',x.shape)
        x = F.dropout(x, p=0.6, training=self.training)
        print('before 2nd layer',x.shape)
        x,e2 = self.conv2(x, data.edge_index, e1)
        print(x.shape)
        return F.log_softmax(x, dim=1)
      
    def alpha_tracker(self):
        #print(self.conv2.alpha.shape)
        alpha_list.append(self.conv2.alpha)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model, data = Net().to(device), data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

def train():
    model.train()
    optimizer.zero_grad()
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask],edgemat).backward()
    optimizer.step()


def test():
    model.eval()
    logits, accs = model(), []
    for _, mask in data('train_mask', 'val_mask', 'test_mask'):
        pred = logits[mask].max(1)[1]
        acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
        accs.append(acc)
    return accs


for epoch in range(1, 2):
    train()
    log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
    print(log.format(epoch, *test()))

```

I'm not sure I'm sending in edgemat the right way. The above code throws the below error. Please advise.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-78-696b3d316048> in <module>()
     17 
     18 for epoch in range(1, 2):
---> 19     train()
     20     log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
     21     print(log.format(epoch, *test()))

1 frames
<ipython-input-78-696b3d316048> in train()
      2     model.train()
      3     optimizer.zero_grad()
----> 4     F.nll_loss(model()[data.train_mask], data.y[data.train_mask],edgemat).backward()
      5     optimizer.step()
      6 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'edgemat'

**Comment by rusty1s** [comment]
You need to call the `forward` message as `def forward(self, x, edge_index, edgemat)`, although I am unsure why you create a dense `edgemat`. Is this intended? It seems more reasonable to me to only create the edge values for the actual edges in `edge_index`.

**Comment by AneeshaaSC** [comment]
1. edgemat is the E matrix in the picture pasted in your earlier comment. It is an NxNxP matrix which I think of as Source nodes x Destination nodes x Channel. So, if node 0 and node 3 are connected, 
E[0][3][0] =1 , E[0][3][1] = 1 and E[0][3][2] =2 . I've tried to implement this in the code below. 

```
# computing the edge matrix outside the EGAT class

edgemat = torch.zeros((coradata[0].num_nodes,coradata[0].num_nodes,3)).to(device)
row = coradata[0].edge_index[0]
col = coradata[0].edge_index[1]
        
for i in range(0,len(row)):
 
  edgemat[row[i]][col[i]][0] = 1
  edgemat[row[i]][col[i]][1] = 1
  edgemat[row[i]][col[i]][2] = edgemat[row[i]][col[i]][0] + edgemat[row[i]][col[i]][1]

```

2. I've now made the changes you suggested to the forward method. But, I now face the below error. I don't need the derivative of edgemat. I only want to precompute the matrix, modify in layer1 and then pass on this modified value for use in layer 2. How do I make edgemat available to different layers? Is it right to include it in F.nll_loss?

```
def train():
    model.train()
    optimizer.zero_grad()
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask],edgemat).backward()
    optimizer.step()
```



RuntimeError                              Traceback (most recent call last)
<ipython-input-39-696b3d316048> in <module>()
     17 
     18 for epoch in range(1, 2):
---> 19     train()
     20     log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
     21     print(log.format(epoch, *test()))

1 frames
<ipython-input-39-696b3d316048> in train()
      2     model.train()
      3     optimizer.zero_grad()
----> 4     F.nll_loss(model()[data.train_mask], data.y[data.train_mask],edgemat).backward()
      5     optimizer.step()
      6 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1869                          .format(input.size(0), target.size(0)))
   1870     if dim == 2:
-> 1871         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1872     elif dim == 4:
   1873         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: the derivative for 'weight' is not implemented

**Comment by rusty1s** [comment]
1. Yes, but no need to save a dense edge matrix, shape `[E, P]` should be sufficient.
2. I do not understand your model call: Shouldn't it be `model(edge_mat)[data.train_mask]`?

**Comment by AneeshaaSC** [comment]
Regarding #1, I'll try that.

2. I've corrected the call now. But, although the only in-place operations I perform are on edgemat, some variable's gradient seems to face hindrance while being computed. How do I go about finding and correcting this?

 ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-44-99121d4687ea> in <module>()
     17 
     18 for epoch in range(1, 2):
---> 19     train()
     20     log = 'Epoch: {:03d}, Train: {:.4f}, Val: {:.4f}, Test: {:.4f}'
     21     print(log.format(epoch, *test()))

2 frames
<ipython-input-44-99121d4687ea> in train()
      2     model.train()
      3     optimizer.zero_grad()
----> 4     F.nll_loss(model(model.edgemat)[data.train_mask], data.y[data.train_mask]).backward()
      5     optimizer.step()
      6 

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    105                 products. Defaults to ``False``.
    106         """
--> 107         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    108 
    109     def register_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91     Variable._execution_engine.run_backward(
     92         tensors, grad_tensors, retain_graph, create_graph,
---> 93         allow_unreachable=True)  # allow_unreachable flag
     94 
     95 

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor []], which is output 0 of SelectBackward, is at version 39792; expected version 39791 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by AneeshaaSC** [comment]
I"ve resolved the above issue to ensure the model works, but the implementation seems to be very slow and I've noticed that it doesn't learn anything going by the training, validation and test errors.

Any advise would be of immense help.

https://colab.research.google.com/drive/1tq9idg_hb-aeLD2CCj-4xXF5MeGOhDHp

**Comment by rusty1s** [comment]
You can definietely make it faster by reimplementing
```python
alphacap = torch.zeros(edgemat.shape).to(device)
        for p in range(0,3):
          for i in range(0,len(alpha)):
            alphacap[row[i]][col[i]][p]  = edgemat[row[i]][col[i]][p]*alpha[i]
```
with vectorized operations. I am still unsure why you use dense edge matrices instead of sparse ones, so this might be another option to look into. Concerning the learning problems of your model, this can be anything form hyperparameters to bugs in your code. If the training error does not decrease at all, there could be also a bug with the gradient computation (such as an unwanted `detach()`).

**Comment by AneeshaaSC** [comment]
I've now removed this section, and I also use the [E,P] sized edgemat as per your suggestion earlier.
```
        # Sum up neighborhoods.
        alpha = alpha.unsqueeze(dim = 1)   # alpha is [13264x1x3] and x[col] is [13264x1x10]
        out = torch.cat([torch.mul(alpha[:,:,0] , x[col]),torch.mul(alpha[:,:,1] , x[col]),torch.mul(alpha[:,:,2] , x[col])],dim=-1)
        out = scatter_add(out, row, dim=0, dim_size=x.size(0))
```
The torch.cat throws the below runtime error. Is there a better way to achieve this computation as suggested in [https://arxiv.org/abs/1809.02709] ?

![image](https://user-images.githubusercontent.com/32979123/62416259-f82d9b00-b62e-11e9-906f-9aa9bdd95518.png)

RuntimeError: CUDA out of memory. Tried to allocate 6.55 GiB (GPU 0; 11.17 GiB total capacity; 6.62 GiB already allocated; 3.17 GiB free; 4.61 MiB cached)

**Comment by AneeshaaSC** [comment]
Fixed above issue with:

```
        # Sum up neighborhoods.
        alpha = alpha.unsqueeze(1)
        out = torch.cat([alpha[:,:,0] * x[col].squeeze(dim = 1)  ,alpha[:,:,1] * x[col].squeeze(dim = 1)  , alpha[:,:,2] * x[col].squeeze(dim = 1) ], dim=-1)
        out = scatter_add(out, row, dim=0, dim_size=x.size(0))

```
One issue remains: model doesn't learn anything. Attempting to fix that.

![image](https://user-images.githubusercontent.com/32979123/62422777-c3155d00-b6af-11e9-8cb3-89b5bb529388.png)
