### ISSUE TITLE
Is the ShapeNet dataset the same as in the PointNet paper?

### ISSUE THREAD

**Issue by cy69855522** [rusty1s/pytorch_geometric#570]
## ❓ Questions & Help

Thanks for sharing such a wonderful package~ I refer to the example of DGCNN and find that the dataset in PYG is very convenient. I would like to ask, is the configuration of the dataset obtained by ShapeNet (None) in PYG consistent with that in the original PointNet paper? I added the fixpoint function to get 2048 points at random, but I'm not sure if the dataset and data argumentation methods are the same as those in the paper. Or are there any other changes?

**Comment by rusty1s** [comment]
The ShapeNet dataset is consistent with the original PointNet paper. We checked that. The `FixedPoints` transform samples `N` points from the point cloud in case the point cloud does have more than `N` points. This is similar to the DGCNN paper which states: "2,048 points are sampled from each training shape."

**Comment by cy69855522** [comment]
Thx~ I have this question because there are some different versions of ShapeNet, so I'd like to make sure it's consistent. Now I'm relieved, thanks again. By the way, the package installed by pip has some bug. I cannot import i and u from that package, but it works well after I downloading files from github.

**Comment by rusty1s** [comment]
What do you mean by `i` and `u`?

**Comment by cy69855522** [comment]
> What do you mean by `i` and `u`?

The function to calculate class mean iou in DGCNN segmentation example.

**Comment by rusty1s** [comment]
Yes, this function is currently only implemented in master.

**Comment by cy69855522** [comment]
Ok, thank you very much. This is a surprising repo.
