### ISSUE TITLE
Can Batch.from_data_list be made faster?

### ISSUE THREAD

**Issue by arkapal1** [rusty1s/pytorch_geometric#572]
Hello,

First of all, I want to say - great package you guys have put together here!

I've been using the Batch.from_data_list method and noted a while ago that it looks to be implemented with a Python loop, making it pretty slow. Indeed profiling suggests that my code can spend a large proportion of time in that function, especially when the batch size is very large (e.g. during evaluation, across multiple GPUs using DataParallel).

Is there a better way for me to batchify my data with large batch sizes? If not, is there potential to perhaps create a faster implementation of this method (e.g. using Cython)?

**Comment by rusty1s** [comment]
You can increase the number of workers to speed up the DataLoader. Regarding the for loop, there is not much we can do about it. In fact, even the data loading routine in native PyTorch is based on the exact same Python for loop. In case you have really many small graphs and batch sizes greater than 512, it might be reasonable to create nested mini-batches, where your dataset already contains pre-defined batches, which gets packed together using the DataLoader.

**Comment by rusty1s** [comment]
Thank you very much. I will perform some benchmarking as well and will try to update the current implementation.

**Comment by rusty1s** [comment]
I modified the `from_data_list` according to your suggestions. The new implementation is now indeed much faster. Thank you very much!

**Comment by LingxiaoShawn** [comment]
> I modified the `from_data_list` method according to your suggestions. The new implementation is now indeed much faster. Thank you very much!

Glad to help! Looking forward to see your new implementation! If you can paste it here for a quick look that would be great!

**Comment by rusty1s** [comment]
You can find the new `collate` function here: https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/collate.py

Note that there are some additional changes, as we now also support mini-batching of heterogeneous graphs (via `torch_geometric.data.HeteroData`) as well as recursive collating of dictionaries and lists.
