### ISSUE TITLE
Difficulty installing the package dependencies 

### ISSUE THREAD

**Issue by EddyWD** [rusty1s/pytorch_geometric#576]
I can install torch-geometric itself but when I try to run `~$ pip install --verbose --no-cache-dir torch-scatter` I get the error below. Updated cmake, setuptools, wheel and pip.  Not what else to try.

## Environment

* OS: Ubuntu18.04
* Python version: 3.7
* PyTorch version: 1.10
* CUDA/cuDNN version: None
* Any other relevant information: Installed in anaconda environment, majority of packages installed using conda

Error: https://pastebin.com/Aj9aS11a

**Comment by rusty1s** [comment]
You do not have `g++` installed, so please install the Ubuntu developer suite.

**Comment by EddyWD** [comment]
Pretty sure that is fully updated now but still got this error: https://pastebin.com/56uBv4mV

**Comment by rusty1s** [comment]
`virtual memory exhausted: Cannot allocate memory`: Strange error, how much RAM do you have?

**Comment by EddyWD** [comment]
Thank you, resized my 1gb droplet to 3gb and the installs worked. Is it expected that much RAM is needed to install these packages on a dedicated virtual server?

**Comment by rusty1s** [comment]
Surely not expected, but I do not have much influence on this either :)
