### ISSUE TITLE
How can I extract the attention weight of GAT model?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#577]
## ❓ Questions & Help

Hi, after adopting the GAT model, how can I extract the attention weight of GAT model? Is there any code examples?

**Comment by rusty1s** [comment]
There is currently no way, sorry. But you can copy paste the GATConv and save the attention values in an attribute of the Module, e.g., `self.alpha = alpha`, and access them afterwards.

**Comment by mrbeann** [comment]
yeah, I can do it. Thanks
