### ISSUE TITLE
Isolated Graph error

### ISSUE THREAD

**Issue by JsBlueCat** [rusty1s/pytorch_geometric#579]
File "/miniconda/envs/py36/lib/python3.6/site-packages/torch_geometric/utils/undirected.py", line 38, in to_undirected
    row, col = edge_index
ValueError: not enough values to unpack (expected 2, got 0)

# if the edge_index is [ ] , the graph means that every point is isolated.  but it seems you don't take this into accout

**Comment by rusty1s** [comment]
Hi, `[]` is no valid `edge_index` shape. `edge_index` can have zero elements, but it needs shape `[2, 0]` nonetheless.

**Comment by JsBlueCat** [comment]
> nonetheless

your means the edge_index can be None?

**Comment by JsBlueCat** [comment]
> Hi, `[0]` is no valid `edge_index` shape. `edge_index` can have zero elements, but it needs shape `[2, 0]` nonetheless.

oh , i understand , thank for your quickly reply

**Comment by rusty1s** [comment]
No, I mean that `edge_index` always needs `edge_index.size(0)==2`. If you want to encode no edges, a valid format would be `torch.tensor([[], []])`.
