### ISSUE TITLE
Data Slice 

### ISSUE THREAD

**Issue by JsBlueCat** [rusty1s/pytorch_geometric#580]
how to convert [0,0,0,0,1,1,1,2,2,2] to 
[
[0,0,0,0],
[1,1,1],
[2,2,2],
]

because i wan't to find 
[x1,x2,x3...] to 
[
[x1],
[x2],
[x3]
]

i need to get each graph of a batch, but it seems only get  a concat matrix

**Comment by rusty1s** [comment]
Although already closed, here is one approach to tackle this issue:
```python
bins = torch.bincount(x)
xs = torch.split(x, bins.tolist())
```
