### ISSUE TITLE
No module named 'torch_sparse'

### ISSUE THREAD

**Issue by qiulesun** [rusty1s/pytorch_geometric#582]
I have successfully run the installation cmd. But when I run from torch_sparse import coalesce, I got the error.

from torch_sparse import coalesce
ModuledNotFoundError: No module named 'torch_sparse'

## 📚 Installation

$ pip install --verbose --no-cache-dir torch-scatter
$ pip install --verbose --no-cache-dir torch-sparse
$ pip install --verbose --no-cache-dir torch-cluster
$ pip install --verbose --no-cache-dir torch-spline-conv (optional)
$ pip install torch-geometric

## Environment

* OS: Ubuntu 16.04 LTS
* Python version: Python 3.6.6 | Anaconda
* PyTorch version: 1.0.0
* CUDA/cuDNN version: 9.0 / 7.0.5
* GCC version: 5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip

**Comment by rusty1s** [comment]
Thank you, I am closing this in favour of https://github.com/rusty1s/pytorch_geometric/issues/542#issuecomment-516681675

**Comment by qiulesun** [comment]
When I run pip install --verbose --no-cache-dir torch-scatter, the error occurs.
oot@hh-ubuntu:/home/hh# pip install --verbose --no-cache-dir torch-scatter
Created temporary directory: /tmp/pip-ephem-wheel-cache-ybrdqy7e
Created temporary directory: /tmp/pip-req-tracker-iissci7p
Created requirements tracker '/tmp/pip-req-tracker-iissci7p'
Created temporary directory: /tmp/pip-install-kkggeind
Collecting torch-scatter
  1 location(s) to search for versions of torch-scatter:
  * https://pypi.org/simple/torch-scatter/
  Getting page https://pypi.org/simple/torch-scatter/
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/torch-scatter/ HTTP/1.1" 200 1104
  Analyzing links from page https://pypi.org/simple/torch-scatter/
    Found link https://files.pythonhosted.org/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.org/simple/torch-scatter/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.org/simple/torch-scatter/), version: 1.0.2
    Found link https://files.pythonhosted.org/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.org/simple/torch-scatter/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/2d/70/df2bc259d9606f00854ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec004d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.org/simple/torch-scatter/), version: 1.0.4
    Found link https://files.pythonhosted.org/packages/2f/97/c50a6aeaedc6924180c6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.org/simple/torch-scatter/), version: 1.1.0
    Found link https://files.pythonhosted.org/packages/91/5f/eb1d3ef3810cb1165859d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.org/simple/torch-scatter/), version: 1.1.1
    Found link https://files.pythonhosted.org/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.org/simple/torch-scatter/), version: 1.1.2
    Found link https://files.pythonhosted.org/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a0259105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.org/simple/torch-scatter/), version: 1.2.0
    Found link https://files.pythonhosted.org/packages/24/b7/680c3b392a4b55a0ebfb480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.org/simple/torch-scatter/), version: 1.3.0
    Found link https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.org/simple/torch-scatter/), version: 1.3.1
  Using version 1.3.1 (newest of versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1)
  Created temporary directory: /tmp/pip-unpack-0jz27wyz
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz HTTP/1.1" 200 12787
  Downloading https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.org/simple/torch-scatter/)
  Added torch-scatter from https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec to build tracker '/tmp/pip-req-tracker-iissci7p'
  Running setup.py (path:/tmp/pip-install-kkggeind/torch-scatter/setup.py) egg_info for package torch-scatter
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/torch_scatter.egg-info
    writing pip-egg-info/torch_scatter.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch_scatter.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/torch_scatter.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/torch_scatter.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-kkggeind/torch-scatter has version 1.3.1, which satisfies requirement torch-scatter from https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec
  Removed torch-scatter from https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec from build tracker '/tmp/pip-req-tracker-iissci7p'
Installing collected packages: torch-scatter
  Created temporary directory: /tmp/pip-record-dfotp6mk
  Running setup.py install for torch-scatter ...     Running command /usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kkggeind/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dfotp6mk/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/test
    copying test/test_max_min.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
    creating build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    running build_ext
    building 'torch_scatter.scatter_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpu
    gcc -pthread -B /usr/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/anaconda3/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:10:0,
                     from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/utils/pybind.h:5,
                     from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:5,
                     from cpu/scatter.cpp:1:
    cpu/scatter.cpp: In lambda function:
    cpu/scatter.cpp:8:40: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘at::ScalarType’
       AT_DISPATCH_ALL_TYPES(src.scalar_type(), "scatter_mul", [&] {
                                            ^
    /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:70:32: note: in definition of macro ‘AT_DISPATCH_ALL_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^
    cpu/scatter.cpp: In lambda function:
    cpu/scatter.cpp:21:40: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘at::ScalarType’
       AT_DISPATCH_ALL_TYPES(src.scalar_type(), "scatter_div", [&] {
                                            ^
    /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:70:32: note: in definition of macro ‘AT_DISPATCH_ALL_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^
    cpu/scatter.cpp: In lambda function:
    cpu/scatter.cpp:34:40: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘at::ScalarType’
       AT_DISPATCH_ALL_TYPES(src.scalar_type(), "scatter_max", [&] {
                                            ^
    /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:70:32: note: in definition of macro ‘AT_DISPATCH_ALL_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^
    cpu/scatter.cpp: In lambda function:
    cpu/scatter.cpp:51:40: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘at::ScalarType’
       AT_DISPATCH_ALL_TYPES(src.scalar_type(), "scatter_min", [&] {
                                            ^
    /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:70:32: note: in definition of macro ‘AT_DISPATCH_ALL_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^
    **error: command 'gcc' failed with exit status 1
error**
Cleaning up...
  Removing source in /tmp/pip-install-kkggeind/torch-scatter
Removed build tracker '/tmp/pip-req-tracker-iissci7p'
Command "/usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kkggeind/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dfotp6mk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-kkggeind/torch-scatter/
Exception information:
Traceback (most recent call last):
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kkggeind/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-dfotp6mk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-kkggeind/torch-scatter/
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/

**Comment by AymaneZizi** [comment]
if you are in windows 10, you should have installed visual studio build tools and check C++ modules to be install it along.
also note that the pytorch geometric installation documentation suggests that only PyTorch versions 1.4.0, 1.5.0, 1.6.0, 1.7.0, and 1.8.0 are compatible, but does not explicitly say so.
https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
you can install it from here 
https://pytorch.org/get-started/previous-versions/
