### ISSUE TITLE
Reddit data Test/Train/Val Split

### ISSUE THREAD

**Issue by juliecwang** [rusty1s/pytorch_geometric#585]
## ❓ Questions & Help
Hello,
I have been reading into how the reddit data is processed for the reddit example, and it looks like the test, train and validation datasets are split based on node types {1, 2, 3}. This seems like an odd approach to me, shouldn't these datasets be split randomly so that there exists a relatively equal distribution of node types? Please let me know if I'm misunderstanding the process.

<img width="654" alt="Screen Shot 2019-08-01 at 11 23 08 AM" src="https://user-images.githubusercontent.com/26678211/62305913-d675bd80-b44e-11e9-8e78-97b9fe44cc63.png">

**Comment by rusty1s** [comment]
In the `Reddit` dataset, we use the fixed splits from the [GraphSAGE paper](https://arxiv.org/pdf/1706.02216.pdf): "We use the first
20 days for training and the remaining days for testing (with 30% used for validation)". You are free to choose a different split :)

**Comment by juliecwang** [comment]
Thanks for the quick response! 

Yes I was wondering if that was the reason...but I wasn't sure what the node type was encoding, so the node type denotes the range of days in a month when the post was made?

**Comment by rusty1s** [comment]
Yes, this is an already preprocessed version of the data, and the `node_type` just denotes the which nodes maps to which split.

**Comment by juliecwang** [comment]
I see, thanks :)
