### ISSUE TITLE
Problems of reusing processed graph.

### ISSUE THREAD

**Issue by kaka2nd** [rusty1s/pytorch_geometric#588]
## ❓ Questions & Help

Hi. I want to know how to reuse the local graph.

I made a dataset and save all the processed graph at local. And all worked successfully. But the second time when I call the dataset, the graph processing will not be done again because it's already there. And I can use the .get() to get all the graph. 
However, the dataset is showing like 
`xxDataset(0)
`
And when I am using dataloader

```
loader = DataLoader(izone, batch_size=1, shuffle=False)
for data in tqdm(loader):
        output_1 = model(data)
```
The data will not show at this place and codes didn't work. 

So I want to know how to reuse the processed graph. Thanks

**Comment by rusty1s** [comment]
Can you show the (minimal) implementation of your dataset? There seems to be a mistake somewhere.

**Comment by kaka2nd** [comment]
```
class UDataset(Dataset):
    def __init__(self, root, transform=None, pre_transform=None):
        self.len = 0
        super(UDataset, self).__init__(root, transform, pre_transform)

    @property
    def raw_file_names(self):
        return []
    @property
    def processed_file_names(self):
        return ['/home/kaka2nd/UI/UI-processed/graph']
    
    def __len__(self):
        return self.len

    def download(self):
        pass

    def process(self):
        index = 0
        for single_graph_no in tqdm(sub_df['graph_no'].unique()):

            data = Data(x=node_features, edge_index=edge_index ,edge_attr = edge_feature )

            torch.save(data, self.processed_paths[0] + 'data_{}.pt'.format(index))

            self.len +=1

    def get(self, idx):

        data = torch.load(self.processed_paths[0] +  'data_{}.pt'.format(idx))
        return data

```
`izone = UDataset('/home/kaka2nd/UI/UI-processed/')
`

All file in my disk is like 
graphdata_0.pt, graphdata_1.pt.......

**Comment by kaka2nd** [comment]
And sub_df is a dataframe

**Comment by rusty1s** [comment]
So, this should basically work, expect that `self.len = 0` is never updated, and hence your dataset does not contain any examples. You should set `__len__` dynamically based on the number of files in your folder.

**Comment by kaka2nd** [comment]
Thanks very much. That's the problem.
