### ISSUE TITLE
How to deal with graph with different types of nodes?

### ISSUE THREAD

**Issue by JinYang88** [rusty1s/pytorch_geometric#589]
## ❓ Questions & Help

I am working on an item recommendation problem where a user and an item is linked if the user clicked on the item. We can suppose that each user or item is represented by an embedding vector. 
When I am trying graphSAGE, I encounter the problem on negative sampling:

I encode all users and items with "0,1,2,...,N" **together** to build the edge_index, which is to say I can not distinguish the node type between "user" and "item". 
When sampling negative samples, a user's negative samples should be items, and items'  negative samples should be users, but I can not achieve this by only given the edge_index. 

So is there a way to solve the problem? Thank you very much :)!

**Comment by JinYang88** [comment]
I may have to to describe the problem more clear:

I want to calculate the dot production in a network for both positive samples and negative samples, so I can do negative sampling before feeding into the network by checking the type of each node, say, if it is a user, I choose an negative item for the node. 

By doing so, I can get neg_edge_index which can be used in the network. But the graph is huge, I have to use NeighborSampler. After using NeighborSampler, the neg_edge_index attribute in the data object is lost.

**Comment by rusty1s** [comment]
You can always hold the information about the type of a node in a dedicated tensor/mask, *e.g.*:
```python
users = x[mask]
items = x[~mask]
```
and sample from it. I am not sure though how you construct `neg_edge_index`.
