### ISSUE TITLE
error installing pytorch_cluster

### ISSUE THREAD

**Issue by tanismar** [rusty1s/pytorch_geometric#59]
When installing pytorch_cluster from the repo using `python install setup.py`, I gues the following errors:
`In file included from cpu/graclus.cpp:3:0:
cpu/utils.h: In function ‘at::Tensor degree(at::Tensor, int64_t)’:
cpu/utils.h:38:45: error: ‘zeros’ was not declared in this scope
   auto zero = zeros(num_nodes, row.options());`

`In file included from cpu/graclus.cpp:3:0:
cpu/utils.h:39:45: error: ‘ones’ was not declared in this scope
   auto one = ones(row.size(0), row.options());`

`In file included from cpu/graclus.cpp:3:0:
cpu/utils.h:47:50: error: could not convert ‘{<expression error>, row}’ from ‘<brace-enclosed initializer list>’ to ‘at::TensorList {aka c10::ArrayRef<at::Tensor>}’`

**Comment by rusty1s** [comment]
I made a commit which should fix this problem. Please try again :)

**Comment by tanismar** [comment]
Hi Matthias, 
Thanks for the fast response! The previous errors did get fix, but now I am getting the following ones: 
`cpu/grid.cpp: In function ‘at::Tensor grid(at::Tensor, at::Tensor, at::Tensor, at::Tensor)’:
cpu/grid.cpp:11:56: error: ‘empty’ was not declared in this scope
   auto index = empty(size.size(0), num_voxels.options());
`
and 
`cpu/grid.cpp:12:33: error: ‘arange_out’ was not declared in this scope
   arange_out(index, size.size(0));
`
Thanks in advance!

**Comment by rusty1s** [comment]
Updated! I am pretty surprised that i do not have these problems during installation.

**Comment by tanismar** [comment]
Thanks again Matthias! Apparently compilation throws errors file by file, although they all seem to be based on the same underlying reason. After pulling your latest commit, I got similar errors again, this time on the cuda/utils.cuh:
`cuda/utils.cuh(39): error: identifier "zeros" is undefined
cuda/utils.cuh(40): error: identifier "ones" is undefined
cuda/utils.cuh(48): error: identifier "zeros" is undefined
cuda/utils.cuh(56): error: identifier "zeros" is undefined
4 errors detected in the compilation of "/tmp/tmpxft_0000250b_00000000-6_graclus_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
`
But applying the same fix you used for cpu/utils.cpp and cpu/grid.cpp (that is, pre-pending 'at::' to ones and zeros) solved it, and it complied just fine :)

I think the modification is too small for a pull request, but consider applying the change in cuda/utils.cuh too. 
Thanks again!

**Comment by rusty1s** [comment]
Fixed! Thanks :)
