### ISSUE TITLE
How to store `Data` object to disk?

### ISSUE THREAD

**Issue by mrbeann** [rusty1s/pytorch_geometric#590]
## ❓ Questions & Help

I construct a large Data object and want to save it to disk, but `pickle` is not working in this circumstance. What can I do?

**Comment by rusty1s** [comment]
Why is `pickle` not working? Have you tried `torch.save`?

**Comment by mrbeann** [comment]
it yields a memory error, quite strange. maybe I should try `torch.save`

**Comment by mrbeann** [comment]
Thanks, it works.
