### ISSUE TITLE
Mean Class IoU BUG

### ISSUE THREAD

**Issue by cy69855522** [rusty1s/pytorch_geometric#591]
## 🐛 Bug
I see the code `ious = [[]] * len(loader.dataset.categories)` in dgcnn_segmentation example.
I guess you want to put all 'iou' into different elements of 'ious', however, `[[]] * int` does not create a 2D list but only a 1D list including some pointers which point to the same address of `[]`.

![image](https://user-images.githubusercontent.com/33852040/62417833-c814e500-b68c-11e9-8fb4-fe0879e9681e.png)

As a result, we're actually calculating the average instance iou, we can use `[[] for _ in range(5)]` to fix it.

**Comment by rusty1s** [comment]
Wow, you are right. This is on me. Fixed in master.
