### ISSUE TITLE
About batch inputs

### ISSUE THREAD

**Issue by kaka2nd** [rusty1s/pytorch_geometric#594]
## ❓ Questions & Help

Hi, I want to know whether my understanding about designing inputs for batch correct correct.
I want to get the embedding for each graph. Usually for each graph, the edge_index is from 0 to node number. Eg. 
data1's edge_index is from 0 to 2, 
data2's edge_index from 0 to 4, 
data3's edge_index from 0 to 2.

If I want to modify my inputs to batch version, is that mean I need encoding the edge index gloablly. Eg. 
data1's edge_index from 0 to 2, 
data2's edge_index from 3 to 6, 
data3's edge_index from 7 to 10
But I don't need to change any of the nodes.

Plz correct me if I understand uncorrectly.

**Comment by rusty1s** [comment]
Yes, exactly. This is exactly what our `DataLoader` is doing.
