### ISSUE TITLE
gmm_conv fails to run

### ISSUE THREAD

**Issue by Bawaw** [rusty1s/pytorch_geometric#60]
Hi, Matthias

I have another question, Is nn.conv.gmm_conv.py still under construction? It fails to run on my end, crashes at line 44:
```
self.mu = Parameter(in_channels, dim)
```

> _TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not int_

I think this should be:
```
self.mu = Parameter(torch.Tensor(in_channels, dim))
```

Also `self.cov` in line 53 doesn't exist. I'm assuming this should be `self.sigma`. The code however still doesn't run due to `self.mu.view(1, F, D)` and `self.sigma.view(1, F, D)`.
> RuntimeError: shape '[1, 150, 3]' is invalid for input of size 3

Thanks for the awesome lib! Kind regards,
Balder

**Comment by rusty1s** [comment]
Yes, I am currently working on it :D This should be fixed by tomorrow. Sorry!

**Comment by rusty1s** [comment]
hkHi, the `GMMConv` is fixed now.
