### ISSUE TITLE
Batching support for graphs with shared edge_index

### ISSUE THREAD

**Issue by falceeffect** [rusty1s/pytorch_geometric#600]
## ❓ Questions & Help

Hello!

I am working on a project that uses a single huge graph (~11k nodes, more than 410k edges) with different sets of node features. I use 4 GCN layers followed by a 3-layered MLP for node classification. This works very slowly as I can only fit a batch of 13-14 graphs simultaneously into my 12Gb GPU. Is it possible to somehow reduce memory usage by utilizing the fact that the same `edge_index` is shared between all input graphs?

Thank you!

**Comment by rusty1s** [comment]
PyTorch does not provide a batch-wise sparse matrix multiplication, so this is definitely a limitation I can not change. What you can do though is to implement your own `GCNConv` to support this, *e.g.*:
```python
def forward(self, x, edge_index):
    # Pre-compute and cache normalization
    # x has shape [batch_size, num_nodes, num_features]
    # edge_index is a sparse single adjacency matrix
    x = self.lin(x)
    x = x.transpose(0, 1)  # x has shape [num_nodes, batch_size, num_features]
    out = self.propagate(edge_index, x=x, norm=norm)
    out = out.transpose(0, 1)  # out has shape [batch_size, num_nodes, num_features]
```

**Comment by sw-gong** [comment]
> PyTorch does not provide a batch-wise sparse matrix multiplication, so this is definitely a limitation I can not change. What you can do though is to implement your own `GCNConv` to support this, _e.g._:
> 
> ```python
> def forward(self, x, edge_index):
>     # Pre-compute and cache normalization
>     # x has shape [batch_size, num_nodes, num_features]
>     # edge_index is a sparse single adjacency matrix
>     x = self.lin(x)
>     x = x.transpose(0, 1)  # x has shape [num_nodes, batch_size, num_features]
>     out = self.propagate(edge_index, x=x, norm=norm)
>     out = out.transpose(0, 1)  # out has shape [batch_size, num_nodes, num_features]
> ```
> 
> This way you do not replicate your edge indices all the time, which should save quite a bit of memory :)

Do you think if it is possible to implement this across all the conv operators?

**Comment by rusty1s** [comment]
I think this could indeed be possible, but might not be worth it if gains are negligible. I will perform some benchmarking on this in the future.

**Comment by rusty1s** [comment]
Closed in favor of https://github.com/rusty1s/pytorch_geometric/issues/611.
