### ISSUE TITLE
How to use size parameter of propagate?

### ISSUE THREAD

**Issue by pixelite1201** [rusty1s/pytorch_geometric#603]
I have a very simple pooling layer defined as follows

    class Pool(MessagePassing):
       def __init__(self):
           super(Pool, self).__init__()

       def forward(self, x, pool_mat): #pool_mat is sparseTensor of shape 1256*5023
           return self.propagate(edge_index=pool_mat._indices(), x=x, norm=pool_mat._values(), size=.   (pool_mat.size()))

       def message(self, x_j, norm):
           return norm.view(-1, 1) * x_j

Sizes of all the tensors for first iteration is
1. edge_index = 2x1256
2. x = 5023x16
3. norm = 1256
4. pool_mat = 1256x5023

When I run the above code,  I get following error
_ValueError: All tensors which should get mapped to the same source or target nodes must be of same size in dimension 0._

According to documentation, **size** is supposed to be the size of the assignment matrix i.e. pool_mat in my case. Am I wrong?
**size (list or tuple, optional) – The size [N, M] of the assignment matrix. If set to None, the size is tried to get automatically inferred. (default: None)**

**Comment by rusty1s** [comment]
I see. The TLDR answer is: Change your message passing flow to „target_to_source“.

In PyG we provide two message passing flows. The default is „source_to_target“ which means in your case the mapping from 1256 nodes to 5023 nodes. This can be mathematically formulated as A^T @ X. The reason we do it this way is due to the message passing paradigm, where messages are send along the edge direction. This does make more sense for directed graphs, and it does not matter for undirected ones. If you want to implement A @ X, you want inverse message passing flow, and hence you need to change the flow argument.

If you do not want to change flow direction, you need to transpose your pooling matrix to 5023x1256, so that you reduce 5023 nodes to 1256 nodes. Although in your case, a simple torch.matmul call is also sufficient.

**Comment by pixelite1201** [comment]
This is strange. Even after changing the flow to 'target_to_source', I am still getting the same error.

    class Pool(MessagePassing):
        def __init__(self):
            super(Pool, self).__init__(flow='target_to_source')

       def forward(self, x, pool_mat,  dtype=None):
            return self.propagate(edge_index=pool_mat._indices(), x=x, norm=pool_mat._values(), size=(pool_mat.size()))

       def message(self, x_j, norm):
            return norm.view(-1, 1) * x_j

**Comment by pixelite1201** [comment]
> If you do not want to change flow direction, you need to transpose your pooling matrix to 5023x1256, so that you reduce 5023 nodes to 1256 nodes. Although in your case, a simple torch.matmul call is also sufficient.

Since, DataLoader of pytorch geometric return data in following format without any extra dimension for batch, its hard to just do torch.matmul when batch_size =16.
**Batch(batch=[80368], edge_index=[2, 479840], x=[80368, 3], y=[80368, 3])**

Here batch_size = 16 and x=5023x3

**Comment by pixelite1201** [comment]
> If you do not want to change flow direction, you need to transpose your pooling matrix to 5023x1256, so that you reduce 5023 nodes to 1256 nodes. Although in your case, a simple torch.matmul call is also sufficient.

Also, according to Batch class definition in batch.py, a batch is
**A plain old python object modeling a batch of graphs as one big
    (dicconnected) graph.** 
So, basically there is no dimension for batch. If I need to multiply the pool matrix to all the graphs in the batch using torch.matmul, I don't know how to do that in a standard way. Any recommendation will be appreciated.

Thanks

**Comment by pixelite1201** [comment]
> I see. The TLDR answer is: Change your message passing flow to „target_to_source“.
> 
> In PyG we provide two message passing flows. The default is „source_to_target“ which means in your case the mapping from 1256 nodes to 5023 nodes. This can be mathematically formulated as A^T @ X. The reason we do it this way is due to the message passing paradigm, where messages are send along the edge direction. This does make more sense for directed graphs, and it does not matter for undirected ones. If you want to implement A @ X, you want inverse message passing flow, and hence you need to change the flow argument.
> 
> If you do not want to change flow direction, you need to transpose your pooling matrix to 5023x1256, so that you reduce 5023 nodes to 1256 nodes. Although in your case, a simple torch.matmul call is also sufficient.
