### ISSUE TITLE
Use of "self.collate" when building a dataset causes RuntimeError

### ISSUE THREAD

**Issue by JinYang88** [rusty1s/pytorch_geometric#604]
## ❓ Questions & Help

I use InMemoryDataset to build dataset with many graphs (40,000,000 graphs, each of them is small).  The process crashed with the following error when executing 'self.collate(datalist)'

```
Pytorch RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0
```

**Comment by rusty1s** [comment]
This seems likely to be an out-of-memory error. You can try to split up the collate call for your graphs, e.g. only collate 10,000,000 together.

**Comment by JinYang88** [comment]
If I split it up, I will have 4 slices for one dataset object,  on which I can not iterate.
When I do 
```
data = dataset[0]
```
It throws
```

  File "/Users/liujinyang/anaconda3/envs/python36/lib/python3.6/site-packages/torch_geometric-1.3.0-py3.6.egg/torch_geometric/data/in_memory_dataset.py", line 104, in get
    for key in self.data.keys:

AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by JinYang88** [comment]
Oh, I may not have to collate them. Can I just use a list of Data and iterate on the list?
