### ISSUE TITLE
Implementing batching in ChebConv when the edge_index is same for all the graphs

### ISSUE THREAD

**Issue by pixelite1201** [rusty1s/pytorch_geometric#611]
I am using ChebConv layer from pytorch geometric. I am using a fix edge_index for all the graphs, hence fix norm. Because of this instead of calculating norm in forward function, I am passing it as a parameter to forward function. 
So my forward function looks something like this

    def forward(self, x, edge_index, norm, edge_weight=None):

        Tx_0 = x
        out = torch.matmul(Tx_0, self.weight[0])

        if self.weight.size(0) > 1:
            Tx_1 = self.propagate(edge_index, x=x, norm=norm)
            out = out + torch.matmul(Tx_1, self.weight[1])

        for k in range(2, self.weight.size(0)):
            Tx_2 = 2 * self.propagate(edge_index, x=Tx_1, norm=norm) - Tx_0
            out = out + torch.matmul(Tx_2, self.weight[k])
            Tx_0, Tx_1 = Tx_1, Tx_2

        if self.bias is not None:
            out = out + self.bias

        return out

Now, I want to include the option of providing input x with different batch size. Since, my edge_index is fixed, if I increase the batch_size it will just use the x_j from first batch in propagate. Hence, I modified the forward function like this to support batch_size. I have reshaped x to [batch_size, num_nodes, num_features]

    def forward(self, x, edge_index, norm, edge_weight=None): #x_shape = batch_size,num_nodes, num_features
        Tx_0 = x

        out = torch.matmul(Tx_0, self.weight[0])

        x = x.transpose(0,1)
        x = x.reshape(-1, x.shape[-2]*x.shape[-1])
        Tx_0 = x
        if self.weight.size(0) > 1:
            Tx_1 = self.propagate(edge_index, x=x, norm=norm)
            Tx_1_reshaped = Tx_1.reshape(Tx_1.shape[0],-1,self.in_channels).transpose(0,1)
            out = out + torch.matmul(Tx_1_reshaped, self.weight[1])

        for k in range(2, self.weight.size(0)):
            Tx_2 = 2 * self.propagate(edge_index, x=Tx_1, norm=norm) - Tx_0
            Tx_2_reshaped = Tx_2.reshape(Tx_2.shape[0],-1,self.in_channels).transpose(0,1)
            out = out + torch.matmul(Tx_2_reshaped, self.weight[k])
            Tx_0, Tx_1 = Tx_1, Tx_2

        if self.bias is not None:
            out = out + self.bias
        return out

It works find but I just want to make sure if this is the most efficient and elegant way to do it.

**Comment by rusty1s** [comment]
Looks correct to me, although I think the reshaping is not necessary. Propagate can handle any number of dimensions, it only requires the node dimension to be the first one.

**Comment by pixelite1201** [comment]
> Looks correct to me, although I think the reshaping is not necessary. Propagate can handle any number of dimensions, it only requires the node dimension to be the first one.

Initially, I tried by transposing the 0,1 axis of x as shown in the following code, but then I need to transpose again inside message for proper broadcasting dimension. Then, need to transpose again before multiplying by weights. 

    def forward(self, x, edge_index, norm, edge_weight=None):

        Tx_0 = x
        out = torch.matmul(Tx_0, self.weight[0])

        x = x.transpose(0,1)
        Tx_0 = x
        if self.weight.size(0) > 1:
            Tx_1 = self.propagate(edge_index, x=x, norm=norm)
            Tx_1_transpose = Tx_1.transpose(0,1)
            out = out + torch.matmul(Tx_1_transpose, self.weight[1])

        for k in range(2, self.weight.size(0)):
            Tx_2 = 2 * self.propagate(edge_index, x=Tx_1, norm=norm) - Tx_0
            Tx_2_transpose = Tx_2.transpose(0,1)
            out = out + torch.matmul(Tx_2_transpose, self.weight[k])
            Tx_0, Tx_1 = Tx_1, Tx_2

        if self.bias is not None:
            out = out + self.bias

        return out

    def message(self, x_j, norm):
        res = norm.view(-1, 1) * x_j.transpose(0,1)
        return res.transpose(0,1)

**Comment by rusty1s** [comment]
I do not think the transpose inside the message function is necessary, a different reshape of norm should be sufficient. However, I see that all those transposes are quite inelegant, so it might be a good idea to add a dim parameter to the propagate call. I will add this ASAP. In the meantime, you can just replace all propagate calls by
```python
row, col = edge_index
scatter_add(x[:, row] * norm, col, dim=1, dim_size=x.size(0))
```
and omit all transpose calls completely.

**Comment by pixelite1201** [comment]
> I do not think the transpose inside the message function is necessary, a different reshape of norm should be sufficient. However, I see that all those transposes are quite inelegant, so it might be a good idea to add a dim parameter to the propagate call. I will add this ASAP. In the meantime, you can just replace all propagate calls by
> 
> ```python
> row, col = edge_index
> scatter_add(x[:, row] * norm, col, dim=1, dim_size=x.size(0))
> ```
> 
> and omit all transpose calls completely.

**Comment by pixelite1201** [comment]
> I do not think the transpose inside the message function is necessary, a different reshape of norm should be sufficient. However, I see that all those transposes are quite inelegant, so it might be a good idea to add a dim parameter to the propagate call. I will add this ASAP. In the meantime, you can just replace all propagate calls by
> 
> ```python
> row, col = edge_index
> scatter_add(x[:, row] * norm, col, dim=1, dim_size=x.size(0))
> ```
> 
> and omit all transpose calls completely.

I tried this but I don't think its possible to multiply x[:, row] with norm because the shape of x is [batch_size*no_of_rows*in_feature]. We will have to transpose x as follows before doing scatter_add
x = x.transpose(1,2)
