### ISSUE TITLE
dense_diff_pool()

### ISSUE THREAD

**Issue by dtchang** [rusty1s/pytorch_geometric#617]
## To Reproduce

1.
1.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by dtchang** [comment]
When adj contains edge attributes, appearing as an additional dimension, the following throws a RuntimeError:
    out_adj = torch.matmul(torch.matmul(s.transpose(1, 2), adj), s)

**Comment by rusty1s** [comment]
This is to be expected since `DiffPool` can only handle one-dimensional edge weights per definition. How would you incorporate edge attributes to the `DiffPool` module?

**Comment by dtchang** [comment]
Thank you for the prompt response. I don't have a solution, unfortunately, though I need one. My dataset, and many real-world datasets, contain multi-dimensional edge attributes. 

The problem is torch.matmul(torch.matmul(...)) doesn't know it is dealing with s.transpose() * adj * s. I wonder if  there is a PyTorch function that does it by passing in adj and s.

**Comment by rusty1s** [comment]
If you permute your adjacency matrix to `[batch_size, num_edge_features, num_nodes, num_nodes]` and your assignment matrix to `[batch_size, 1, num_nodes, num_clusters]`, and call the transpose function as `transpose(-1, -2)`, the the `matmul` formula should work, computing new adjacency matrices for each edge feature independently.

**Comment by mcbal** [comment]
We recently proposed an approach to pool graphs with edge features in [https://arxiv.org/abs/1908.02065](https://arxiv.org/abs/1908.02065), building on top of Top-K Pooling and Graph U-Nets. Happy to have a go at making our work fit into the PyTorch Geometric framework and create a PR.

**Comment by dtchang** [comment]
Matthias, Thanks for the suggested solution. Rex Ying also has a suggested solution: [RexYing/diffpool] edge attributes (#25). Can you work out with Rex on an agreed solution and incorporate it in dense_diff_pool()? Thanks much!

**Comment by rusty1s** [comment]
This is the same approach👍

**Comment by dtchang** [comment]
I implemented Rex Ying's suggestion and made the following changes in dense_diff_pool():
if adj.dim() == 3:
    out_adj = torch.matmul(torch.matmul(s.transpose(1, 2), adj), s)
else: # adj.dim() == 4
    adj_perm = adj.permute(0, 3, 1, 2)
    s_perm = s.unsqueeze(1)
    s_t = s.transpose(1, 2)
    s_t_perm = s_t.unsqueeze(1)
    out_adj_perm = torch.matmul(torch.matmul(s_t_perm, adj_perm), s_perm)
    out_adj = out_adj_perm.permute(0, 2, 3, 1)
It works fine.

In addition, the following changes are needed before link_loss to avoid RuntimeError in link_loss:
if adj.dim() == 4:
    adj = adj.unbind(3)[0]
This produces good link_loss if the first edge attribute (type) is edge weight or something like it.

**Comment by rusty1s** [comment]
Thank you! Cool that it is working :)
