### ISSUE TITLE
pytorch_geometric: Error due to mismatch in batch sizes at the train and eval time

### ISSUE THREAD

**Issue by anilesec** [rusty1s/pytorch_geometric#619]
## ❓ Questions & Help

I created regression task for predicting labels on each nodes for a graph. I used pytorch_geometric based GCN. I tried to use different batch sizes at train and eval time and I am getting run time error.
RuntimeError: Cached 21000 number of edges, but found 420

Graph of size 21 nodes(fully connected)
I used batch_size of 50, so 21000 edges at the training time
I used batch_size of 1, so 420 edges at the eval time
And I got the above mentioned error.

Any help?
Thanks!

**Comment by rusty1s** [comment]
Yes! You need to remove the `cached=True` flag from the `GCNConv`.

**Comment by anilesec** [comment]
Thanks! I did not understand that flag.

**Comment by rusty1s** [comment]
I will update its doc :)
