### ISSUE TITLE
Default flow direction and spatial transforms

### ISSUE THREAD

**Issue by rubenwiersma** [rusty1s/pytorch_geometric#630]
## 🐛 Bug

First of all: I have really enjoyed and benefited from working with PyTorch Geometric in my thesis. Great work!

Now the issue: The spatial transforms (like transforms.Cartesian and transforms.Polar) compute the coördinates for target nodes relative to the source nodes, i.e. in the tangent plane of the source nodes:
```
 cart = pos[col] - pos[row]
```
However, the default flow for MessagePassing networks is from source to target. For example, for nn.GMMConv, it seems to me that the aggregation step therefore uses the wrong coordinates (target -> src, instead of src -> target).

## Additional context
This issue does not seem to break the performance of GMMConv. I ran into this, as I am working on a technique that assumes we are working in the tangent plane of `src` (as is assumed in Polar and Cartesian transforms) and breaks when this assumption is broken.

## Additional thoughts
It might help to rename `col` and `row` variable names to `src` and `target` to more easily distinguish between the two and know what each index is referring to.

**Comment by rusty1s** [comment]
Isn‘t that correct? Given that row is the source and col is the target node, we compute the Cartesian vector as pos[col] - pos[row], which is the natural formulation in linear algebra (and isn’t even that related to message passing, is it?) In addition, it does not break anything as long as it is consistent.

**Comment by rubenwiersma** [comment]
It’s definitely correct for computing the polar and Cartesian coordinates relative to the source node. I thought (and I’ll recheck this, since I am not 100% sure) that this is not consistent with how GMMConv is currently implemented. I’ll get back to you on this later tonight.

**Comment by rubenwiersma** [comment]
I've looked at it again. TL;DR the issue is (only) semantic and most people will likely not run into it the same way I did. I'm sorry for nitpicking. I thought it would help to clarify, as I found out about this inconsistency through a week of debugging my code.

Now for the issue: GMMConv takes as input some pseudo coordinates, let's denote them as pseudo[i,j]. Per default, _i_ corresponds to the target nodes and _j_ corresponds to the source nodes:
```
# self.flow defaults to 'source to target'
i, j = (0, 1) if self.flow == 'target_to_source' else (1, 0)
```
If we use the cartesian coordinates for pseudo, we would expect to get the following formulation:
```
pseudo[i, j] = pos[j] - pos[i]
```
Since we assumed _i_ corresponds to the target nodes and _j_ to the source nodes, we can write this as:
```
# row = src, col = target
pseudo[i, j] = pos[row] - pos[col]
```
This is the inverse of what is actually computed in transforms.Cartesian and transforms.Polar.

This typically doesn't matter, as most spatial methods do not care if you input pseudo[i, j] or -pseudo[i, j]. I ran into this issue, as I experimented with a random permutation of the polar coordinates for each point, breaking the relation between pseudo[i,j] and pseudo[j,i], so that pseudo[i,j] != -pseudo[j,i].

**Comment by rusty1s** [comment]
Thank you for the detailed description. Nitpicking is good and helps improving the package :)

I see your point, but IMO I would expect Cartesian coordinates to be computed via
```python
pos[i] - pos[j] = pos[col] - pos[row]
```
since this denotes a vector from point j to i (which is equivalent to the default message passing flow). In other words, you would not compute `pseudo[i,j] = pos[j] - pos[i]` in the default message passing flow, but rather `pseudo[j,i] = pos[i] - pos[j]` and save it as an edge feature to the edge `e_{j,i}`. WDYT?

**Comment by rubenwiersma** [comment]
I think I get what you're saying: the vector represented by the cartesian or polar pseudo coordinates should point in the direction of the message passing flow and it is true that this is what happens with the default message passing flow.

I would argue, in the case of GMMConv and other spatial methods, that it should be in the reverse direction, _because that means the coordinates are centered around the point the messages are aggregated to_. This is the way Masci et al. define the convolutional operator in [Geodesic Convolutional Neural Networks on Riemannian Manifolds](https://www.cv-foundation.org/openaccess/content_iccv_2015_workshops/w22/papers/Masci_Geodesic_Convolutional_Neural_ICCV_2015_paper.pdf) (p 39, eq 7) which is followed by Monti et al. for GMM.

It could also be that this seems natural to me, as I had been assuming the default flow to be the other way around (from col to row). This is mainly due to me working within the context of spatial methods, where one tends to aggregate values from neighbors to the 'center point', whereas it is more natural in the message passing paradigm to send messages from the 'center point' to its neighbors.
