### ISSUE TITLE
Error in OSX: Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by pietroastolfi** [rusty1s/pytorch_geometric#636]
### Problem
The installation of all the extensions and of torch_geometric seems to be successful.
But, when importing the extensions: torch_scatter, torch_cluster, torch_sparse, torch_spline_conv, I get the same error: `Symbol not found: __ZN3c105ErrorC1ENS_14SourceLocationERKSs`. (I know that the error is not directly of torch_geometric, but i report it here since it refers to all its extensions).

Looking at the log of the installation I found this warning:
```
                               !! WARNING !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.
See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              !! WARNING !!
```

### Solution adopted
I installed clang inside my conda environment, and I relaunched the installation of the extensions with the prefix CC=clang e.g., `CC=clang pip install --verbose torch-scatter`.
**This solved the problem!!**
Note that the warning was still there, but looking at the compiling command in the verbose log the compiler used was now clang instead of gcc.

## Environment

* OS: MacOS 10.13.6
* Python version: 2.7.14
* PyTorch version: 1.1.0
* CUDA/cuDNN version: None
* GCC version: **4.8.5 [ERROR!!!] --> use Clang**
* How did you try to install PyTorch Geometric and its extensions (pip, source): both
* Any other relevant information: **Anaconda environment**

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [ ] ❌ I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I have cloned the repository and tried a manual installation from source.
- [ ] ❌ I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [ ] ❌ The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
So it is working for you? The warning is sadly always present on macOS, although clang is the right compiler to use.

**Comment by pietroastolfi** [comment]
Yes, it's working. You can close the issue. I wrote it to keep track of the solution (I know it's very simple), and to advise you about this possible error (common if you use macOS + conda).

**Comment by rusty1s** [comment]
Perfect, thank you!
