### ISSUE TITLE
A bug about processing SHREC2016 datasets

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#639]
## 🐛 Bug

I met the bug of processing SHREC2016 dataset. I can generate the ```ref_``` ```.pt```files, but I cannot generate ```train_``` ```.pt``` and ```test_``` ```.pt``` files

## To Reproduce

1. my python code
```python
import torch_geometric.datasets as gdatasets
s = gdatasets.SHREC2016('./SHREC2016', 'Cuts', 'David')
```

2. and the error is (after downloading and extracting the files. i.e. these 2 steps works fine)
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-31-15833c950a50> in <module>
----> 1 s = gdatasets.SHREC2016('./SHREC2016', 'Cuts', 'David')

~/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/shrec2016.py in __init__(self, root, partiality, category, train, transform, pre_transform, pre_filter)
     72         self.cat = category.lower()
     73         super(SHREC2016, self).__init__(root, transform, pre_transform,
---> 74                                         pre_filter)
     75         self.__ref__ = torch.load(self.processed_paths[0])
     76         path = self.processed_paths[1] if train else self.processed_paths[2]

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     54                  pre_filter=None):
     55         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 56                                               pre_filter)
     57         self.data, self.slices = None, None
     58 

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     81 
     82         self._download()
---> 83         self._process()
     84 
     85     @property

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/dataset.py in _process(self)
    125 
    126         makedirs(self.processed_dir)
--> 127         self.process()
    128 
    129         print('Done!')

~/anaconda3/lib/python3.7/site-packages/torch_geometric/datasets/shrec2016.py in process(self)
    143 
    144         torch.save(ref_data, self.processed_paths[0])
--> 145         torch.save(self.collate(train_list), self.processed_paths[1])
    146         torch.save(self.collate(test_list), self.processed_paths[2])
    147 

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py in collate(self, data_list)
    122         r"""Collates a python list of data objects to the internal storage
    123         format of :class:`torch_geometric.data.InMemoryDataset`."""
--> 124         keys = data_list[0].keys
    125         data = data_list[0].__class__()
    126 

IndexError: list index out of range

```

## Environment

* OS: Ubuntu 16.04
* Python version: 3.7.3 (Anaconda)
* PyTorch version: 1.1.0
* CUDA/cuDNN version: NO (CPU)
* GCC version: 5.4.0
* Any other relevant information: NO

## Additional context
![image](https://user-images.githubusercontent.com/37621591/63477495-efa2e480-c4b7-11e9-9c80-dc222e3a6d21.png)

I use ```torch.load``` to load the generated ```refs_``` ```.pt``` files. And loading them is all-right. 

![image](https://user-images.githubusercontent.com/37621591/63477609-79eb4880-c4b8-11e9-9385-ff61452a9647.png)

**Comment by rusty1s** [comment]
Thank you! I cannot debug this at the moment, but it seems that `train_list` and/or `test_list` is an empty list, which may happen due to non-existent `cuts_david_*.off` files in the `raw/` directory. Can you verify? How are they named instead? Does this also apply to other categories?

**Comment by WMF1997** [comment]
hello @rusty1s 
I do not know what is happening on earth. I tried (if it still has the error on Windows) just a few minutes earlier on my Windows OS, and it succeed? (WITHOUT ANY CHANGE)
It is really ??unexplainable?? why windows version succeed? (I really do not understand why)

code (written in vscode 1.37.0  terminal, python 3.6.4 )
![image](https://user-images.githubusercontent.com/37621591/63483479-1caec180-c4cf-11e9-8b2c-40bd7d772119.png)


and the folder is:

![image](https://user-images.githubusercontent.com/37621591/63483577-72836980-c4cf-11e9-92e5-31e8f00a54b3.png)

I will try in another ubuntu system and windows systems to see what is happening.

yours sincerely
@WMF1997

**Comment by rusty1s** [comment]
I fixed the KarateClub dataset, thank you. For the other dataset, there may be something wrong with capitalization.

**Comment by WMF1997** [comment]
@rusty1s :
it's my fault that I forgot to type 
```python
import numpy as np
```
in the first part... I think you have checked that... sorry. 

Next time, I will type all the changed parts. 

very sorry...
yours
@WMF1997

**Comment by rusty1s** [comment]
I should never commit and push to master on a smartphone ;)

**Comment by rusty1s** [comment]
Fixed the SHREC16 bug in master :)
