### ISSUE TITLE
Optional FixedPointSampling without Replacement

### ISSUE THREAD

**Issue by cy69855522** [rusty1s/pytorch_geometric#642]
## To Reproduce

```python
……
    def forward(self, data):
        pos, batch = data.pos, data.batch
        
        N = len(pos)
        psid, ptid = knn_graph(pos, self.k, batch, loop=False, flow=self.flow) # edge_index:[E, 2]
……
```
![image](https://user-images.githubusercontent.com/33852040/63642314-0af83480-c6f0-11e9-998c-58948f591951.png)

## Expected behavior
N * K == len(ptid)

## Environment

* OS: Colab Linux
* Python version: 3
* PyTorch version: 1.2.0
* CUDA/cuDNN version: 10.0
* GCC version:
* Any other relevant information:

## Additional context
data comes from shapenet and FixedPoints(2048)

**Comment by rusty1s** [comment]
I can not reproduce this issue via the following code:
```python
import torch
from torch_cluster import knn_graph

pos = torch.randn(2000, 3)
batch = torch.cat([torch.zeros(1000), torch.ones(1000)]).long())
edge_index = knn_graph(pos.cuda(), 4, batch.cuda(), loop=False)
print(edge_index.size())
```
```
torch.Size([2, 8000])
````
Can you show me the complete code to reproduce this?

**Comment by WMF1997** [comment]
hello @rusty1s:
it is just a type error in the ```batch``` line. ```.long())``` should be ```.long()``` he typed one more ')'

and the code should be 

with my result.

![image](https://user-images.githubusercontent.com/37621591/63644674-013af500-c721-11e9-9fe1-16aec2fac579.png)


yours sincerely, 
@wmf1997

**Comment by cy69855522** [comment]
Thank you @rusty1s @WMF1997 , but I am sure there is a problem. Please see the complete code. This problem seems to have some randomness that doesn't come up every time, so I use a loop.
```python
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.datasets import ShapeNet
import torch_geometric.transforms as T
from torch_geometric.data import DataListLoader, DataLoader
from torch_geometric.utils import intersection_and_union as i_and_u, mean_iou
from torch_geometric.nn import knn_graph, DataParallel, global_max_pool, MessagePassing

os.chdir("/home")
path = 'ShapeNet'
category = None
batch_size = 2
num_workers = 2
num_points = 2048
cuda = torch.cuda.is_available()

# Load data

transform = T.Compose([
    T.FixedPoints(num_points),
])
pre_transform = T.NormalizeScale()

train_dataset = ShapeNet(
    path,
    category,
    train=True,
    transform=transform,
    pre_transform=pre_transform)
test_dataset = ShapeNet(
    path,
    category,
    train=False,
    transform=transform,
    pre_transform=pre_transform)

DLF = DataListLoader if cuda else DataLoader
train_loader = DLF(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    drop_last=True,
    num_workers=num_workers
)
test_loader = DLF(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    drop_last = True,
    num_workers=num_workers
)

class Net(nn.Module):
    def __init__(self, out_channels, k=10):
        super(Net, self).__init__()
        self.k = k
        self.flow = 'source_to_target'
        
    def forward(self, data):
        pos, batch = data.pos, data.batch
        
        N = len(pos)
        psid, ptid = knn_graph(pos, self.k, batch, loop=False, flow=self.flow) # edge_index:[E, 2]
        mid = (pos[psid] + pos[ptid]) / 2
        edge = pos[psid] - pos[ptid]
        dis = torch.norm(edge, dim=1) # dis:[E]
        print(ptid.shape, N * self.k)
        assert ptid.size(0) == N * self.k;

def ttt():
    for data_list in train_loader:
        with torch.no_grad():
            out = model(data_list)
        break
            
device = torch.device('cuda' if cuda else 'cpu')
model = Net(train_dataset.num_classes, k=5)
if cuda: model = DataParallel(model)
model = model.to(device)
while True:
    ttt()
```
```python
output:
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20480]) 20480
torch.Size([20484]) 20480
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-10-8335c94ff45c> in <module>()
     81 model = model.to(device)
     82 while True:
---> 83     ttt()

4 frames
<ipython-input-10-8335c94ff45c> in forward(self, data)
     68         dis = torch.norm(edge, dim=1) # dis:[E]
     69         print(ptid.shape, N * self.k)
---> 70         assert ptid.size(0) == N * self.k;
     71 
     72 def ttt():

AssertionError: 
```
In addition, I've written a new piece of code to replace this function.
```python
def knng(pos, k: int, d: int =3, batch=None, loop=False, flow='source_to_target'):
    # If the "pos" contains points of the same position, the self-loop may be generated even if the loop is set to False
    assert flow in ['source_to_target', 'target_to_source']
    k -= loop
    assert k, 'k must be greater than 0 and greater than 1 for loop to be True'
    
    N = len(pos)
    dev = pos.device
    if batch is None:
        batch = torch.zeros(N, dtype=torch.long, device=dev)
    
    bs = batch[-1].item() + 1
    pos = pos.view(bs, N // bs, -1)
    
    region_idx = []

    for n, qry in enumerate(pos):
        ref = pos[n]
        n, d = ref.size()
        m, d = qry.size()
        mref = ref.expand(m, n, d)
        mqry = qry.expand(n, m, d).transpose(0, 1)
        dist2 = torch.sum((mqry - mref)**2, 2).squeeze()
        _, inds = torch.topk(dist2, k*d + 1, dim = 1, largest=False)
        region_idx.append(inds[:,1::d])

    tid = torch.arange(N, device=dev).view(-1, 1).repeat(1, k + loop).view(-1)
    sid = torch.stack(region_idx, dim = 0).view(-1, k)
    if loop:
        sid = torch.cat([sid, torch.arange(sid.size(0)).view(-1, 1)], dim=1)
    sid = sid.view(-1)
    
    if not flow=='source_to_target':
        sid, tid = tid, sid
    
    return sid, tid
```

**Comment by rusty1s** [comment]
I identified the origin of the issue, and it is caused by the `FixedPoints` transform, which may potentially generate a lot of single duplicated points greater than `k`.

In this case, `torch-cluster.knn` may do stupid things: We actually generate `k+1` connections and remove self-loops in case `loop=False`. So if the self-loop is not in the initial connections, it can not be removed!

I am unsure though how to fix this, and I see it being more a problem with the `FixedPoints` transforms, which samples points *with* replacement. I think we should change this to a sampling strategy without replacement, and sample as long as we obtain the required number of points. WDYT?

**Comment by cy69855522** [comment]
> I identified the origin of the issue, and it is caused by the `FixedPoints` transform, which may potentially generate a lot of single duplicated points greater than `k`.
> 
> In this case, `torch-cluster.knn` may do stupid things: For `knn(loop=False)`, we actually generate `k+1` connections and remove self-loops afterwards . However, iff the self-loop is not in the initial connections, it can not be removed (resulting in an unexpected number of connections). It is fixable by setting `k` to a higher value.
> 
> I am unsure on how to fix this though (is this really a problem of `torch_cluster.knn`?), and I see it being more of a problem with the `FixedPoints` transforms, which samples points _with_ replacement. I think we should change this to a sampling strategy without replacement, and sample as long as we obtain the required number of points. This would heavily reduce the number of duplicated points in the output of the `FixedPoints` transform. WDYT?

I agree with you, and I also noticed that the `KNNG` error comes from the sampling strategy.However, I think `KNNG` should take some measures for this special case, because this sampling method is inevitable. The point set size of some models in `ShapeNet Data Set` is less than 2048. If `replacement` parameter is set as false, point cloud with fixed points cannot be obtained, which is different from the experimental environment of other point cloud models.

**Comment by rusty1s** [comment]
Yes, that is why we need to sample points with `replace=False` in a loop as long as we obtain the desired number of points. For example, if your model has 1024 points, but you require 2048 fixed points, this way you will get a **single** duplicated point for each initial point. If you sample with replacement instead, you might get 10 duplicated points for a single point, and none for another. In this scenario, it is much more unlikely that the above error occurs. In addition, it is a much more intuitive sampling strategy in case `N > number_of_fixed_points`.

**Comment by cy69855522** [comment]
> Yes, that is why we need to sample points with `replace=False` in a loop as long as we obtain the desired number of points. For example, if your model has 1024 points, but you require 2048 fixed points, this way you will get a **single** duplicated point for each initial point. If you sample with replacement instead, you might get 10 duplicated points for a single point, and none for another. In this scenario, it is much more unlikely that the above error occurs. In addition, it is a much more intuitive sampling strategy in case `N > number_of_fixed_points`.

Oh, I see what you mean, it's a good idea, it does reduce the probability of that problem, but it doesn't prevent it, and it should be a new sampling strategy, different from direct random sampling.

**Comment by rusty1s** [comment]
I am not sure I understand what you mean, can you elaborate?

**Comment by cy69855522** [comment]
I know your strategy is feasible, but I'm just worried that this sampling method is different from that of other papers, which may cause some disputes on the fairness of the comparison of model results.

**Comment by rusty1s** [comment]
Ah I see! We could add a flag to the transform to make this optional.

**Comment by cy69855522** [comment]
Thank you~ d=====(￣▽￣*)b

**Comment by cy69855522** [comment]
```python
class FixedPoints(object):
    r"""Samples a fixed number of :obj:`num` points and features from a point
    cloud.
    Args:
        num (int): The number of points to sample.
        balance (bool): When blance is true and num > data.num_nodes, this function will
        samples the complete data and then randomly samples (num % data.num_nodes) points
    """

    def __init__(self, num, balance=True):
        self.num = num
        self.balance = balance

    def __call__(self, data):
        num_nodes = data.num_nodes
        
        if self.balance and num_nodes < self.num:
            div = self.num // num_nodes 
            mod = self.num % num_nodes
            repetition = [np.random.choice(num_nodes, num_nodes, replace=False) for _ in range(div)]
            overflow = [np.random.choice(num_nodes, mod, replace=False)]
            choice = np.concatenate(repetition + overflow, axis=0)
        else:
            choice = np.random.choice(num_nodes, self.num, replace=True)

        for key, item in data:
            if bool(re.search('edge', key)):
                continue
            if torch.is_tensor(item) and item.size(0) == num_nodes:
                data[key] = item[choice]

        return data

    def __repr__(self):
        return '{}({})'.format(self.__class__.__name__, self.num)
```

**Comment by rusty1s** [comment]
Thank you for your code! I finally got to integrate it [into master](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/transforms/fixed_points.py).
