### ISSUE TITLE
Fail to import GraphUNet

### ISSUE THREAD

**Issue by wimwimyam** [rusty1s/pytorch_geometric#648]
## ❓ Questions & Help

I tried to import GraphUNet, but receive errors.

I ran the code in colab with GPU runtime. PyTorch version: 1.1.0. 

----> 1 from torch_geometric.nn import GraphUNet

ImportError: cannot import name 'GraphUNet'

----> 1 from torch_geometric.nn.models import GraphUNet

ImportError: cannot import name 'GraphUNet'

----> 1 from torch_geometric.nn.models.graph_unet import GraphUNet

ModuleNotFoundError: No module named 'torch_geometric.nn.models.graph_unet'

**Comment by rusty1s** [comment]
Yes, the Graph U-Net is currently only supported on master, so you need to install PyG from source (just clone the repo and run python setup.py install) to use it. I will craft a new release soon.

**Comment by wimwimyam** [comment]
Got it, thanks for your prompt reply and looking forward for the new release :)
