### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'

### ISSUE THREAD

**Issue by FreemanG** [rusty1s/pytorch_geometric#65]
I tried to install torch-scatter on my workstation (ubuntu 18.04).

I installed from source (python setup.py install), and it successfully finished. When I import torch_scatter in python3.6, I got an error:
`ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'`

Then I removed folder "build", and `pip uninstall torch-scatter`. And re-installed using:
`pip install torch-scatter`

The  "ModuleNotFoundError" was still there when I tried to import. 
(Also I tried to clear pip cache, nothing changed)

**Comment by rusty1s** [comment]
Can you show me the installation log of:
rm -rf build && python setup.py install

**Comment by FreemanG** [comment]
`running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
creating build/lib.linux-x86_64-3.6/test
copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
copying test/utils.py -> build/lib.linux-x86_64-3.6/test
creating build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
running build_ext
/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'torch_scatter.scatter_cpu' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cpu
gcc -pthread -B /home/hgua8781/anaconda3/envs/pt1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/home/hgua8781/anaconda3/envs/pt1.0/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -B /home/hgua8781/anaconda3/envs/pt1.0/compiler_compat -L/home/hgua8781/anaconda3/envs/pt1.0/lib -Wl,-rpath=/home/hgua8781/anaconda3/envs/pt1.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/scatter.o -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
building 'torch_scatter.scatter_cuda' extension
creating build/temp.linux-x86_64-3.6/cuda
gcc -pthread -B /home/hgua8781/anaconda3/envs/pt1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/hgua8781/anaconda3/envs/pt1.0/include/python3.6m -c cuda/scatter.cpp -o build/temp.linux-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from cuda/scatter.cpp:1:0:
/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/local/cuda-9.0/bin/nvcc -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/hgua8781/anaconda3/envs/pt1.0/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
g++ -pthread -shared -B /home/hgua8781/anaconda3/envs/pt1.0/compiler_compat -L/home/hgua8781/anaconda3/envs/pt1.0/lib -Wl,-rpath=/home/hgua8781/anaconda3/envs/pt1.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cuda/scatter.o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/min.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/std.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/sub.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/gen.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/ext.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/mean.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/mul.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/add.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/max.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/div.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_std.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_backward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/__init__.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_forward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/utils.py -> build/bdist.linux-x86_64/egg/test
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/min.py to min.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/std.py to std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/sub.py to sub.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/gen.py to gen.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/ext.py to ext.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mean.py to mean.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mul.py to mul.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/add.py to add.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/max.py to max.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/div.py to div.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_std.py to test_std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_backward.py to test_backward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_forward.py to test_forward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/utils.py to utils.cpython-36.pyc
creating stub loader for torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
creating stub loader for torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cpu.py to scatter_cpu.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cuda.py to scatter_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torch_scatter.__pycache__.scatter_cpu.cpython-36: module references __file__
torch_scatter.__pycache__.scatter_cuda.cpython-36: module references __file__
creating 'dist/torch_scatter-1.1.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_scatter-1.1.0-py3.6-linux-x86_64.egg
creating /home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch_scatter-1.1.0-py3.6-linux-x86_64.egg
Extracting torch_scatter-1.1.0-py3.6-linux-x86_64.egg to /home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages
Adding torch-scatter 1.1.0 to easy-install.pth file

Installed /home/hgua8781/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch_scatter-1.1.0-py3.6-linux-x86_64.egg
Processing dependencies for torch-scatter==1.1.0
Finished processing dependencies for torch-scatter==1.1.0`

**Comment by FreemanG** [comment]
`running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
creating build/lib.linux-x86_64-3.6/test
copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
copying test/utils.py -> build/lib.linux-x86_64-3.6/test
creating build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
running build_ext
/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'torch_scatter.scatter_cpu' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cpu
gcc -pthread -B /home/xxxx/anaconda3/envs/pt1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/home/xxxx/anaconda3/envs/pt1.0/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -B /home/xxxx/anaconda3/envs/pt1.0/compiler_compat -L/home/xxxx/anaconda3/envs/pt1.0/lib -Wl,-rpath=/home/xxxx/anaconda3/envs/pt1.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/scatter.o -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
building 'torch_scatter.scatter_cuda' extension
creating build/temp.linux-x86_64-3.6/cuda
gcc -pthread -B /home/xxxx/anaconda3/envs/pt1.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/xxxx/anaconda3/envs/pt1.0/include/python3.6m -c cuda/scatter.cpp -o build/temp.linux-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from cuda/scatter.cpp:1:0:
/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/local/cuda-9.0/bin/nvcc -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/TH -I/home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/xxxx/anaconda3/envs/pt1.0/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
g++ -pthread -shared -B /home/xxxx/anaconda3/envs/pt1.0/compiler_compat -L/home/xxxx/anaconda3/envs/pt1.0/lib -Wl,-rpath=/home/xxxx/anaconda3/envs/pt1.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cuda/scatter.o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/min.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/std.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/sub.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/gen.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/ext.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/mean.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/mul.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/add.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/max.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/div.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_std.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_backward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/__init__.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_forward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/utils.py -> build/bdist.linux-x86_64/egg/test
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/min.py to min.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/std.py to std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/sub.py to sub.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/gen.py to gen.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/ext.py to ext.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mean.py to mean.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mul.py to mul.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/add.py to add.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/max.py to max.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/div.py to div.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_std.py to test_std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_backward.py to test_backward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_forward.py to test_forward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/utils.py to utils.cpython-36.pyc
creating stub loader for torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
creating stub loader for torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cpu.py to scatter_cpu.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cuda.py to scatter_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torch_scatter.__pycache__.scatter_cpu.cpython-36: module references __file__
torch_scatter.__pycache__.scatter_cuda.cpython-36: module references __file__
creating 'dist/torch_scatter-1.1.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_scatter-1.1.0-py3.6-linux-x86_64.egg
creating /home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch_scatter-1.1.0-py3.6-linux-x86_64.egg
Extracting torch_scatter-1.1.0-py3.6-linux-x86_64.egg to /home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages
Adding torch-scatter 1.1.0 to easy-install.pth file

Installed /home/xxxx/anaconda3/envs/pt1.0/lib/python3.6/site-packages/torch_scatter-1.1.0-py3.6-linux-x86_64.egg
Processing dependencies for torch-scatter==1.1.0
Finished processing dependencies for torch-scatter==1.1.0`

**Comment by rusty1s** [comment]
Can you test the installation with GCC 4.9 or above?

**Comment by FreemanG** [comment]
My python3.6 use gcc 7.3.0. I build this environment with anaconda. Could it be the gcc version of python that cause this problem?

**Comment by rusty1s** [comment]
I believe you need to reinstall PyTorch when changing compiler versions :(
This is mentioned in the [docs](https://pytorch.org/tutorials/advanced/cpp_extension.html).

**Comment by FreemanG** [comment]
It worked. Thanks a lot!!!

**Comment by HebutAIer** [comment]
> I cannot remember what I have done, but the problem has gone away.
> 
> A new problem has occurred. I run into _Segmentation fault (core dumped)_ when I tried to execute `python cora.py` and `python setup.py test`.
> 
> As for `python setup.py test`, I get output as following:
> `======================================== test session starts ========================================
> platform linux -- Python 3.6.7, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
> rootdir: /data1/PlayGround/branch_graph/pytorch_geometric, inifile: setup.cfg
> plugins: cov-2.6.1
> collected 81 items
> 
> test/data/test_batch.py .
> test/data/test_data.py .
> test/datasets/test_planetoid.py Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.x
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.tx
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.allx
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.y
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.ty
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.ally
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.graph
> Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.citeseer.test.index
> Processing...
> Done!
> .
> test/datasets/test_tu_dataset.py Downloading https://ls11-www.cs.uni-dortmund.de/people/morris/graphkerneldatasets/ENZYMES.zip
> Extracting /tmp/2384087375461660544/test/ENZYMES.zip
> Processing...
> Done!
> .
> test/nn/test_inits.py ..
> test/nn/test_meta.py .
> test/nn/test_reshape.py .
> test/nn/conv/test_agnn_conv.py Segmentation fault (core dumped)`
> 
> While the output of cora.py was just
> 
> > Segmentation fault (core dumped)

I also has the same ploblem that  
` test/nn/conv/test_agnn_conv.py Segmentation fault (core dumped)`
when run 
`python setup.py test`

I reinstall pytorch can not solve this problem

my cuda in /usr/local/cuda-10.1/bin and the version of cuda in /usr/local/cuda/ is 8.0. is it the reason of that error?

**Comment by rusty1s** [comment]
Likely, you need to ensure that the packages get compiled with the same CUDA version PyTorch is using.
