### ISSUE TITLE
GATConv with `edge_index=None`

### ISSUE THREAD

**Issue by zc-alexfan** [rusty1s/pytorch_geometric#650]
## ❓ Questions & Help

In the original GAT paper, they mentioned that it is possible to provide no edge prior to a graph while the edges will be learned entirely through the node features. I am wondering if it is possible for this implemented `GATConv` layer? If not, are there any variance of this provided in this repo? 

My current idea is that, if we supply `edge_index` as a fully connected graph. Then the above feature is implemented?

Thanks in advance!

**Comment by rusty1s** [comment]
Interesting approach, and this can be indeed achieved by using a fully connected graph. The use of a sparse `edge_index` for fully connected graphs is, however, not recommended. In addition, this formulation basically just boils down to the initial attention formulation, so I would simply use the PyTorch Attention module to achieve this.

**Comment by zc-alexfan** [comment]
Thanks for the reply! So if I use GATConv with a fully-connected graph, it still works, but might be slower?

**Comment by rusty1s** [comment]
That‘s correct.
