### ISSUE TITLE
Radius function: local normalized coordinate system

### ISSUE THREAD

**Issue by FraLotito** [rusty1s/pytorch_geometric#651]
# 🚀 Feature

Radius(x,y,r) finds for each element in y all points in x within distance r. It can be useful to have a parameter to return the set x in a local normalized coordinate system:  if a point u in the set x is within distance r from a point v in the set y, then u = (u - v) / r.

## Motivation

This is mainly motivated by a recent paper I'm trying to reproduce using PyTorch Geometric:

[Paper](https://arxiv.org/pdf/1904.09664.pdf) Section 4.2, paragraph "Proposal and classification from vote clusters."
[Code](https://github.com/facebookresearch/votenet)

Thanks.

**Comment by rusty1s** [comment]
Hi, does this really need its own function parameter? I guess you can just compute u in a follow-up step using the `edge_index`, e.g.:
```python
row, col = radius(...)
u = (x[row] - y[col]) / r
```

**Comment by FraLotito** [comment]
Hi! Thanks for your reply!

As far as I understood I think it should be `u = (x[col] - y[row]) / r`, but I get a strange behavior when doing that:
the size of `x` is 163840
the size of 'y' is 16384
the size of `x[row]` is 955375
the size of 'y[col]' is 955375
the max of `row` is 16383
the max of `col` is 163838

**Comment by rusty1s** [comment]
Yes, you are right. It is `(x[col] - y[row])`. I see no strange behavior in your results.

**Comment by FraLotito** [comment]
Why is the size of the input point set increasing?

**Comment by rusty1s** [comment]
Because you map each node feature to an edge feature.
