### ISSUE TITLE
Version 1.3.0 does not correct a mask procedure

### ISSUE THREAD

**Issue by sshojiro** [rusty1s/pytorch_geometric#652]
## 🐛 Bug

Pytorch 1.2.0 has changes in mask behavior according to [release note](https://github.com/pytorch/pytorch/releases):

```python
>>> 1 - (torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2]))
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported.
If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

>>> ~(torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2]))
tensor([False,  True,  True])
```

However, the following error is raised in torch_geometric.utils.loop.py with `torch.__version__` `'1.2.0'`, and `torch_geometric.__version__`, `'1.3.0'`.

```
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported.
If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.
```

As long as I see this repo, master branch already reflected the change in mask of pytorch as follows [torch_geometric.utils.loop.py](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/loop.py#L96),

```python
    if edge_weight is not None:
        assert edge_weight.numel() == edge_index.size(1)
        inv_mask = ~mask
```

between ll. 121-123.

but, the version 1.3.0 of torch_geometric on my miniconda returns the following log.

```python
c:\users\sshojiro\miniconda3\envs\cheminfo\lib\site-packages\torch_geometric\utils\loop.py in add_remaining_self_loops(edge_index, edge_weight, fill_value, num_nodes)
    105     if edge_weight is not None:
    106         assert edge_weight.numel() == edge_index.size(1)
--> 107         inv_mask = 1 - mask
    108         remaining_edge_weight = edge_weight[inv_mask]
    109         if remaining_edge_weight.numel() > 0:
```

## Question

Just question, when will the `master` branch be distributed? Thank you in advance.

## Environment

- OS: Windows 10

**Comment by rusty1s** [comment]
I will upload a new version today.

**Comment by rusty1s** [comment]
Just released it :)
