### ISSUE TITLE
run 'ious' get an error 

### ISSUE THREAD

**Issue by liangzhenm** [rusty1s/pytorch_geometric#655]
## ❓ Questions & Help
hi, i run the 'dgcnn_segmentation' for a test, but get:

"ious=[[ ] for _ in range(loader.dataset.categories)]
TypeError: 'list' object cannot be interpreted as an integer"

can you help me?

**Comment by rusty1s** [comment]
Are you running the latest PyTorch Geometric version?

**Comment by liangzhenm** [comment]
> Are you running the latest PyTorch Geometric version?

i run with 1.3.0, not 1.3.1, should i update to 1.3.1??

**Comment by rusty1s** [comment]
Yes, I believe the ShapeNet dataset changed slightly recently.
