### ISSUE TITLE
Cora performance inconsistence

### ISSUE THREAD

**Issue by gaoji7777** [rusty1s/pytorch_geometric#656]
## ❓ Questions & Help
Hi!

When I run example/cora.py, it gets a 90% test accuracy. However, in the benchmarking paper, it claims only 83% accuracy. What makes the difference?

Thank you!

**Comment by rusty1s** [comment]
This example uses SplineCNN on the Cora dataset with a different split. If you are interested in the GCN example on the Planetoid split, have a look at examples/gcn.py

**Comment by gaoji7777** [comment]
OK, is the split in gcn.py the same as "fixed split" mentioned in the paper?

**Comment by rusty1s** [comment]
Yes, this is the default split.

**Comment by gaoji7777** [comment]
Thanks!

**Comment by zhangsunsuochang** [comment]
i got the error

**Comment by zhangsunsuochang** [comment]
i got the error "AttributeError: module 'torch_geometric.transforms' has no attribute 'RandomNodeSplit'" when i run the example/cora.py, my packages' version are:
torch                     1.7.1                    
torch-cluster             1.5.9                   
torch-geometric           1.7.2                   
torch-scatter             2.0.8                    
torch-sparse              0.6.11                   
torch-spline-conv         1.2.1

**Comment by zhangsunsuochang** [comment]
i got the error "AttributeError: module 'torch_geometric.transforms' has no attribute 'RandomNodeSplit'" when i run the example/cora.py, my packages' version are:
torch 1.7.1
torch-cluster 1.5.9
torch-geometric 1.7.2
torch-scatter 2.0.8
torch-sparse 0.6.11
torch-spline-conv 1.2.1

**Comment by rusty1s** [comment]
Plaese see https://github.com/rusty1s/pytorch_geometric/issues/3074 :)

**Comment by zhangsunsuochang** [comment]
> Plaese see #3074 :)

thanks for your qiuck reply, but i got 80% acc when I remove the "T.RandomNodeSplit(num_val=500, num_test=500)" from emamples/cora.py, which is much lower than original paper("SplineCNN: Fast Geometric Deep Learning with Continuous B-Spline Kernels"). What makes the difference? thanks

**Comment by zhangsunsuochang** [comment]
thanks for your qiuck reply, but i got 80% acc when I remove the "T.RandomNodeSplit(num_val=500, num_test=500)" from emamples/cora.py, which is much lower than original paper("SplineCNN: Fast Geometric Deep Learning with Continuous B-Spline Kernels"). What makes the difference? thanks

**Comment by rusty1s** [comment]
Removing it will result in using a different split than what is utilized in the paper. This script should work as expected on PyG 1.7.2: https://github.com/rusty1s/pytorch_geometric/blob/1.7.2/examples/cora.py#L10-L13

**Comment by zhangsunsuochang** [comment]
it works, thank you very much!!!
