### ISSUE TITLE
Problems of passing new attribute to Data

### ISSUE THREAD

**Issue by kaka2nd** [rusty1s/pytorch_geometric#658]
## ❓ Questions & Help
Hi.
I am trying to pass the name of graph to data, which is used to indexing.
`data = myData(x=node_features, edge_index=edge_index ,edge_attr = edge_feature ,name = single_graph_no)
`
And the data becomes myData(edge_attr=[90, 3], edge_index=[2, 90], name= graph_1, x=[10, 22])

But when I use datalaoder and batch to run the model, there is an error which is 

~/anaconda3/envs/dp/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    558         if self.num_workers == 0:  # same-process loading
    559             indices = next(self.sample_iter)  # may raise StopIteration
--> 560             batch = self.collate_fn([self.dataset[i] for i in indices])
    561             if self.pin_memory:
    562                 batch = _utils.pin_memory.pin_memory_batch(batch)

~/anaconda3/envs/dp/lib/python3.6/site-packages/torch_geometric/data/dataloader.py in <lambda>(data_list)
     30             shuffle,
     31             collate_fn=lambda data_list: Batch.from_data_list(
---> 32                 data_list, follow_batch),
     33             **kwargs)
     34 

~/anaconda3/envs/dp/lib/python3.6/site-packages/torch_geometric/data/batch.py in from_data_list(data_list, follow_batch)
     40         for i, data in enumerate(data_list):
     41             for key in data.keys:
---> 42                 item = data[key] + cumsum.get(key, 0)
     43                 if key in cumsum:
     44                     cumsum[key] += data.__inc__(key, item)

TypeError: must be str, not int

So I hope to know what's the problem?
Thanks.

**Comment by rusty1s** [comment]
Mh, I cannot reproduce this issue. The following code runs without problem for me:
```python
import torch
from torch_geometric.data import Data, DataLoader

data = Data(x=torch.randn(50, 3), name=torch.randn(50, 3))
print(data)

loader = DataLoader([data, data], batch_size=2)
for data in loader:
    print(data)
```
Do you use `torch.tensor` for all your data attributes?

**Comment by rusty1s** [comment]
Oh, I see, you are passing a `str` in your data object. This is not supported (or at least not for batching), but I guess we should do this.

**Comment by kaka2nd** [comment]
Hi. Thanks for reply. Knowing that only it should be tensor is enough for me. I can just pass tensor in it.

Thanks.

**Comment by pietroastolfi** [comment]
> Oh, I see, you are passing a `str` to your data object. This is not supported (or at least not for batching), but I guess we should implement this.

It would be useful :) , also because in common PyTorch dataloader is possibile to pass strings. 
Aw, @kaka2nd my workaround was to use DataListLoader which can get as input a dictionary, BUT this solution is less efficient. It requires to unlist the dictionaries in order to separate the "name" from the "data".
