### ISSUE TITLE
Issues with the installation 

### ISSUE THREAD

**Issue by sportbilly13** [rusty1s/pytorch_geometric#66]
Hi 
I am new to Pytorch. I am trying to install the libraries in Ubuntu 18.04 in a conda environment and I am getting the following error in all of the libraries except the geometric one 

  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

Could you please help me solve the problem.

Many thanks
Vasilis

**Comment by rusty1s** [comment]
You have no compiler installed. Install it via
```
sudo apt install build-essential
```
and you are good to go.

**Comment by sportbilly13** [comment]
Thanks for the quick response. The build-essential was already installed.

The total message is:

    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/home/sportibilly/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-phsd21wk/torch-sparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4xqau56f/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-phsd21wk/torch-sparse/

Thanks

**Comment by sportbilly13** [comment]
Hi 
I have solved it. Removed g++, gcc and build-essential and reinstall them.
Many thanks
