### ISSUE TITLE
How to can I use the DataParalle to support multi-GPU？

### ISSUE THREAD

**Issue by yangfei1223** [rusty1s/pytorch_geometric#663]
## ❓ Questions & Help

Dear authors,
Thank you for your contribution to the PyG. I am now using PyG for the research of GDL. I find out that the input batch size of PyG is actually the number of nodes other than the number of graphs/instance, which is different from the PyTorch. So, if I train my muti-graph data in parallel style with DataPaprallel of PyTorch on 2 more GPUS, a graph in my input data will be divided into 2 different devices, which causes an error. How can I fix this problem? I'll appreciate it.

**Comment by rusty1s** [comment]
Hi, you need to use the `DataParallel` module provided by PyTorch Geometric.

**Comment by yangfei1223** [comment]
@rusty1s Thanks a lot! I'm sorry for my omission about it. I find it now and thank you again.
