### ISSUE TITLE
modelnet dataset issue

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [rusty1s/pytorch_geometric#664]
Hello,

I found that when I convert model net into a graph. There are many small connected components. For example, a graph (converted by a mesh) has 7612 nodes but the size of all the connected components is 

[4, 4, 11, 11, 9, 9, 21, 21, 9, 9, 4, 4, 4, 4, 13, 13, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 20, 20, 20, 20, 20, 20, 4, 4, 20, 20, 4, 4, 4, 4, 5, 5, 26, 26, 4, 4, 4, 4, 26, 26, 38, 38, 26, 26, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 4, 4, 4, 4, 712, 7, 7, 174, 174, 3, 3, 3, 3, 4, 4, 168, 168, 3, 3, 3, 3, 3, 3, 4, 4, 71, 71, 3, 3, 71, 71, 3, 3, 3, 3, 35, 35, 35, 35, 21, 21, 21, 21, 4, 3, 3, 3, 3, 3, 5, 12, 12, 20, 20, 30, 30, 84, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 84, 6, 4, 6, 4, 6, 4, 4, 6, 6, 4, 6, 4, 6, 4, 4, 6, 6, 4, 6, 4, 6, 4, 6, 4, 164, 164, 164, 164, 4, 4, 488, 4, 4, 24, 24, 3, 3, 3, 3, 24, 24, 4, 4, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 18, 18, 94, 94, 94, 94, 49, 49, 49, 49, 12, 4, 164, 164, 164, 164, 4, 4, 488, 4, 4, 24, 24, 3, 3, 3, 3, 24, 24, 4, 4, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 18, 18, 94, 94, 94, 94, 49, 49, 49, 49, 12, 4]

I am not so familiar with shape dataset. Is it really a normal thing? I attached the related code below.

----------------

# modelnet issue
```python
import os.path as osp

import networkx as nx
import numpy as np
from torch_geometric.datasets import ModelNet
from torch_geometric.transforms import FaceToEdge


def torch_geometric_2nx(dataset, print_flag=False):
    """
    :param dataset: a list of pytorch_geometric.dataset
    :param print_flag:
    :return:
    """

    graphs, labels = [], []

    for i in range(len(dataset)):
        edges = dataset[i].edge_index  # tensor of shape [2, n_edges * 2]
        n_edge = edges.shape[1] // 2
        edges = edges.numpy()  # edges = np.array([[ 0,  0,  1,  1 ], [ 1,  9,  0,  2]])
        edges_lis = list(edges.T)
        edge_lis_ = set([edge[0] for edge in edges_lis] + [edge[1] for edge in edges_lis])
        edges_lis = [(edge[0], edge[1]) for edge in edges_lis]
        g = nx.from_edgelist(edges_lis)

        assert len(edge_lis_) == len(g)  # check nx.from_edgelist is right
        assert len(g.edges) == n_edge  # check nx.from_edgelist is right

        graphs.append(g)
        assert len(g.edges) == n_edge
        label = dataset[i].y
        labels.append(int(label))

        if print_flag: print(i)
    return graphs, labels


if __name__ == '__main__':
    version = '10'  # 10 or 40
    idx = 1

    path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data/ModelNet' + version)
    # path = '/home/cai.507/Documents/DeepLearning/ModelNet' + version

    pre_transform, transform = FaceToEdge(), None

    # train_dataset = ModelNet(path, version, True, transform=transform, pre_transform=pre_transform)
    test_dataset = ModelNet(path, version, False, transform=transform, pre_transform=pre_transform)
    data = test_dataset  # train_dataset + test_dataset

    test_data = data[idx]

    data = FaceToEdge()(test_data)
    gs, _ = torch_geometric_2nx([data])
    g = gs[0]
    print(nx.info(g))

    # number of connected components
    size_list = [len(g) for g in nx.connected_components(g)]
    print(size_list)
```

**Comment by Chen-Cai-OSU** [comment]
apologize for the format of the code. I don't know how to make it look good.

**Comment by rusty1s** [comment]
I formatted it properly. You can look at the raw data to see how it is done. Thanks for reporting. I will look into it.

**Comment by rusty1s** [comment]
I replicated this issue. Note that you can also use the `to_networkx` functionality:
```python
import networkx as nx
from torch_geometric.datasets import ModelNet
from torch_geometric.transforms import FaceToEdge
from torch_geometric.utils import to_networkx

path = '/tmp/modelnet10'
test_dataset = ModelNet(path, '10', False)
data = test_dataset
idx = 0
test_data = data[idx]

data = FaceToEdge()(test_data)
print(data)
g = to_networkx(test_data).to_undirected()
print(nx.info(g))

# number of connected components
size_list = [len(g) for g in nx.connected_components(g)]
print(size_list)
```
And yes, you are right. The `ModelNet10` dataset does not seem to contain watertight meshes. It can even hold some isolated nodes. I guess this is intended, and it is not a bug of PyTorch Geometric. I guess that's the reason most papers sample a point cloud from the mesh surface, instead of using the face connectivity directly.

**Comment by Chen-Cai-OSU** [comment]
Thanks for the reply. So for other shape datasets that are included in PyTorch geometric, is there one dataset that does not have such a problem?

**Comment by rusty1s** [comment]
I know for sure that the FAUST models contain watertight meshes, so they shouldn‘t have this problem.
