### ISSUE TITLE
The data required by GCNConv

### ISSUE THREAD

**Issue by tingxueronghua** [rusty1s/pytorch_geometric#669]
## ❓ Questions & Help

When I use the GCNConv in my model, I get the error like this:

File "~/software/anaconda3/envs/new_torch/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 83, in norm
    deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
RuntimeError: copy_if failed to synchronize: device-side assert triggered

This error seemes not to be repeated easily, so I have no idea about where it comes from. I think maybe it's due to the parameters of my network. But I don't know what kind of data may cause this error, can anyone help me?

**Comment by rusty1s** [comment]
Does this happen on GPU or CPU? In case it fails on GPU, please run the code with
```
CUDA_LAUNCH_BLOCKING=1 python ...
```
to verify where the issue occurs.

You are far from the only person having this problem, see https://github.com/facebookresearch/maskrcnn-benchmark/issues/658. It could be related to too large learning rates (though I am unsure why).

**Comment by tingxueronghua** [comment]
> 
> 
> Does this happen on GPU or CPU? In case it fails on GPU, please run the code with
> 
> ```
> CUDA_LAUNCH_BLOCKING=1 python ...
> ```
> 
> to verify where the issue occurs.
> 
> You are far from the only person having this problem, see [facebookresearch/maskrcnn-benchmark#658](https://github.com/facebookresearch/maskrcnn-benchmark/issues/658). It could be related to too large learning rates (though I am unsure why).

Thanks for the reply! I find that the data given to the GCNConv will somehow become nan after the first epoch, so I change the activation function and it seems to become normal.

**Comment by rusty1s** [comment]
Do you normalize your input features, because they are possibly the ones creating the NaNs.

**Comment by tingxueronghua** [comment]
> 
> 
> Do you normalize your input features, because they are possibly the ones creating the NaNs.

Oh, I forgot that, thank you! I will try it!
