### ISSUE TITLE
Sample code for using torch_geometric.nn.MetaLayer

### ISSUE THREAD

**Issue by phil-hawkins** [rusty1s/pytorch_geometric#670]
## ❓ Questions & Help

The [documentation ](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html) provides an example use of the MetaLayer.  It seem to me that in the implementation of forward in NodeModel, scatter_mean incorrectly aggregates around the source nodes of directed edges rather than the destination nodes which would be in keeping with the paper. 

```    
def forward(self, x, edge_index, edge_attr, u, batch): 
        # x: [N, F_x], where N is the number of nodes.
        # edge_index: [2, E] with max entry N - 1.
        # edge_attr: [E, F_e]
        # u: [B, F_u]
        # batch: [N] with max entry B - 1.
        row, col = edge_index
        out = torch.cat([x[col], edge_attr], dim=1)
        out = self.node_mlp_1(out)
        out = scatter_mean(out, row, dim=0, dim_size=x.size(0))
        out = torch.cat([x, out, u[batch]], dim=1)
        return self.node_mlp_2(out)
```

I've been assuming (row, col) of the edge_index refers to (source node indices, destination node indices) however as I write this I realise I might just have that around the wrong way.  Can anyone clear up whether the example is correct with respect to the “Relational Inductive Biases, Deep Learning, and Graph Networks” paper?

**Comment by rusty1s** [comment]
Thanks for noticing. You are indeed right. I fixed it in master :)
