### ISSUE TITLE
Hierarchical/multiple labels

### ISSUE THREAD

**Issue by choltz95** [rusty1s/pytorch_geometric#676]
How hard would it be to support hierarchical/multiple labels? e.g. some graphs have both graph-level and node-level labels & I want to learn both. Is there a quick solution to this?

**Comment by rusty1s** [comment]
There is no limitation. Simply add both to your data object.

**Comment by choltz95** [comment]
Okay I see thanks for the info. I see that dataset() concats node attributes & node labels.

For example, I guess for ENZYMES I should set use_node_attr to true and decompose dataset[i].x into the attribute part & label part before reformatting the label component into a new 1d integer tensor attribute of dataset[i].
