### ISSUE TITLE
install error anaconda pip

### ISSUE THREAD

**Issue by aif2017** [rusty1s/pytorch_geometric#68]
c1xx: fatal error C1083: Cannot open source file: 'cpu/scatter.cpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by rusty1s** [comment]
Can you show me the log of manually installing pytorch_scatter? `python setup.py install`
