### ISSUE TITLE
Different behaviors for modelnet10 versus modelnet40

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [rusty1s/pytorch_geometric#682]
Hello, it seems that the effects of same transform and pretransform on modelnet10 and modelnet40 is different.

```python
from torch_geometric.transforms import FaceToEdge
import torch_geometric.transforms as T
from torch_geometric.datasets import ModelNet
from torch_geometric.transforms import FaceToEdge


def load_modelnet(version='10', point_flag = False):
    assert version in ['10', '40']
    if point_flag:
        pre_transform, transform = T.NormalizeScale(), T.SamplePoints(1024)
    else:
        pre_transform, transform = FaceToEdge(), None

    # path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data/ModelNet' + version)
    path = '/home/cai.507/Documents/DeepLearning/ModelNet' + version

    train_dataset = ModelNet(path, version, True, transform=transform, pre_transform=pre_transform)
    test_dataset = ModelNet(path, version, False, transform=transform, pre_transform=pre_transform)
    return train_dataset, test_dataset

if __name__ == '__main__':
    train_dataset, test_dataset = load_modelnet('10')
    print(test_dataset[1])
    train_dataset, test_dataset = load_modelnet('40')
    print(test_dataset[1])
```
The output is 
Data(pos=[1024, 3], y=[1])

Traceback (most recent call last):
  File "issue2.py", line 25, in <module>
    print(test_dataset[1])
  File "/home/cai.507/anaconda3/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 76, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/home/cai.507/anaconda3/lib/python3.6/site-packages/torch_geometric/transforms/sample_points.py", line 22, in __call__
    pos, face = data.pos, data.face
AttributeError: 'Data' object has no attribute 'face'

**Comment by rusty1s** [comment]
I can not reproduce this issue. Are you sure that that there is no (wrongly) pre-transformed dataset located at the specified path? If `pre_transform` changes, you need to remove the `processed_dir` in order to allow new pre-processing of data.

**Comment by Chen-Cai-OSU** [comment]
Hello,

You are indeed corret! I somehow did wrong transform and save it to the directory and forget to double-check. Thank you very much for your help!

**Comment by rusty1s** [comment]
I will enhance the dataset to make this process more transparent :)
