### ISSUE TITLE
Converting networkx graph to PyG Data issue.

### ISSUE THREAD

**Issue by 130ndim** [rusty1s/pytorch_geometric#685]
## 🐛 Bug

Converting nx.DiGraph to Data raises `ValueError: only one element tensors can be converted to Python scalars`
```
     98     for key, item in data.items():
---> 99         data[key] = torch.tensor(item)
    100 
    101     data['edge_index'] = edge_index
```
## To Reproduce

1. Convert PyG Data to a networkx Graph using `pytorch_geometric.utils.to_networkx` providing edge attributes as a parameter.
2. Try to convert it back to PyG Data.
`
from_networkx(to_networkx(pyg_graph, node_attrs=['pos', 'x'], edge_attrs=['edge_attr']))
`
## Expected behavior

I would expect it to work properly. Also there is no possibility now to convert graph features to `nx.Graph` and back.

## Environment

* OS: Ubuntu 18.04.1 LTS
* Python version: 3.6.9
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 10.0.130
* GCC version: 7.4.0
* Any other relevant information: N/A

## Additional context

N/A

**Comment by youdar** [comment]
@rusty1s 
Hi,
I am trying to go from `Heterogeneous` PyG graph to `networkx` data and back, maintaining all the information.
It looks like I need to do  Heterogeneous -> Homorogeneous -> Networkx -> Homorogeneous -> Heterogeneous

Can you please direct me to an example of how to this, for example with the [Movie data graph from the PyG tutorial](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html#hgtutorial)   

It is not clear to me how to set the edges and nodes attributes we pass between those steps efficiently, in particular if the graph is has more nodes and edges types.

Thanks

**Comment by rusty1s** [comment]
Our heterogeneous graph format differs from the one `networkx` utilizes, and it is hard to convert between them to using existing `to_networkx` and `from_networkx` functionality.

Heterogeneous -> Homorogeneous -> Networkx -> Homorogeneous -> Heterogeneous should indeed work given that all features of very node type have the same dimensionality.

**Comment by kunal-bhadra** [comment]
Hey @rusty1s I am also trying to convert my PyG heterogeneous graph to Networkx for visualization purposes and I'm facing the same issue. I have multiple node types and edges, each having different dimensions. In this situation, can you please suggest me what to do?

It'd be a great help, thanks!

**Comment by rusty1s** [comment]
As long as you do not need `from_networkx` support, you should be able to leverage `data.to_homogeneous()` and then convert via `to_networkx(node_attrs=['node_type'])` as usual. You may want to adjust the node type argument afterwards to show strings rather than integers. Let me know if this works.

**Comment by kunal-bhadra** [comment]
Alright, got it. I hope `data.to_homogenous()` accounts for the different edge weights for different edge types too. I'll give it a shot, and I'll update you here in this thread.

**Comment by rusty1s** [comment]
Yes, it will maintain this information in case the dimensionality of attributes is the same across different types.

**Comment by kunal-bhadra** [comment]
I have converted it into a homogenous Networkx graph and now all nodes/edges are in integers. However, I can't find any documentation on the Networkx homogenous -> heterogenous conversion. Do we have to implement this on our own with the Networkx modules from scratch?
