### ISSUE TITLE
Global Concat Pooling

### ISSUE THREAD

**Issue by tjiagoM** [rusty1s/pytorch_geometric#686]
## ❓ Questions & Help

Hi! First of all, many thanks for such an amazing tool! 

I want to ask what would be the best way to do a global concatenation pooling over a batch of graphs. Basically, I wanted to concat the features of all the nodes in a certain graph for some downstream graph classification. 

Given that there's already a `global_add_pool`, `global_mean_pool`, etc, I don't know whether this should be a feature request for something like `global_concat_pool`, but it's definitely a request for help :p

**Comment by rusty1s** [comment]
Do you really want to do that? Nodes in your graph aren‘t handled permutation invariant that way, and need to be filled with zeros to take varying node sizes into account. However, this is possible by using torch_geometric.utils.to_dense_batch and reshaping the resulting tensor.

**Comment by rusty1s** [comment]
In addition, the sort pooling achieves something similar.

**Comment by tjiagoM** [comment]
Hi, thanks for the prompt reply! Regarding `to_dense_batch`: when concatenation is performed for each graph, the order of the nodes is the same of the node's labellings for each graph? I mean, if I identify my nodes as [N_0, N_1, N_2, ....] (ids used in edge indexes), will the concatenation for each graph also be in the same order?: [F_0 || F_1 || F_2 || ...]

I tried to look to the sort code to understand whether this happens, but I admit there are a few parts which I don't understand yet.

**Comment by rusty1s** [comment]
Yes :)

**Comment by tjiagoM** [comment]
Might be worth to add a sentence in the function's documentation just be clearer.

Thanks a lot, that's all I needed! :)
