### ISSUE TITLE
download ShapeNet dataset failed when I run the example named "pointnet2_segmentation.py "

### ISSUE THREAD

**Issue by YamingZ** [rusty1s/pytorch_geometric#688]
## To Reproduce

1.run the example named "pointnet2_segmentation.py "
1.raise error :urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
1.

## Expected behavior

just run the example named "pointnet2_segmentation.py " without error
## Environment

* OS: ubuntu 16.04
* Python version:3.6.7
* PyTorch version:1.1.0

* CUDA/cuDNN version:9.0/7.3
* GCC version:5.4.0
* Any other relevant information:

**Comment by rusty1s** [comment]
Can you try running `pip install requests` and run your code again?

**Comment by YamingZ** [comment]
Thanks，I have installed this package，I think, will it be because of the website need login？

**Comment by rusty1s** [comment]
The website does not need any login, see [here](https://shapenet.cs.stanford.edu/iccv17/). We just download the point cloud datasets from there, *e.g.*, [the training point clouds](https://shapenet.cs.stanford.edu/iccv17/partseg/train_data.zip). Are you able to download those manually?

**Comment by YamingZ** [comment]
yeah，I can download  manually

**Comment by rusty1s** [comment]
Mh, I do not really know, but maybe [this](https://github.com/ritiek/spotify-downloader/issues/480) is useful to you.

**Comment by YamingZ** [comment]
fine，thanks for your help
