### ISSUE TITLE
```Dimension out of range``` error about ```TUDataset```

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#692]
## 🐛 Bug

hello @rusty1s :

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 

here is a screenshot. (windows)
![image](https://user-images.githubusercontent.com/37621591/65297252-cd28e780-db99-11e9-9bbc-e800f947a274.png)

here is another screenshot. (ubuntu)
![2019-09-20 11-03-04屏幕截图](https://user-images.githubusercontent.com/37621591/65296831-5c350000-db98-11e9-8c28-f55cfa7394b2.png)

## To Reproduce

```python
from torch_geometric.datasets import TUDataset
# NOTE(WMF): not all the datasets have this error. 
# As far as I know: 
# COIL-RAG, SYNTHETICnew, TRIANGLES, TWITTER-Real-Graph-Partial has this error. 
# i.e. other datasets works fine. (Sorry, I tested it on Windows and Linux(Ubuntu))
ds_name = 'COIL-RAG'
a = TUDataset(root=ds_name, name='ds_name')
```

## Expected behavior

No bug here. 

## Environment

* OS: Windows 10 (build 17763)/ Ubuntu 16.04 (with Linux Kernel 4.15.0)
* Python version: 3.7.3 / 3.7.3
* PyTorch version: 1.1.0 / 1.1.0
* CUDA/cuDNN version: None / 9.0
* GCC version: None / 5.4.0
* Any other relevant information: None / None

## Additional context

I guess that in those "error" datasets, a ```pre-transform``` is a must. And this should be mentioned. i will have a try of that. 

since the range is mentioned in the error, what about use a linear transform to "squeeze' again? if that works, ...

yours sincerely, 
@wmf1997

**Comment by rusty1s** [comment]
Thank you! Really not intended and fixed in master. You need to delete the `processed` files in order to see the effect.

**Comment by WMF1997** [comment]
hello @rusty1s 
Does it affect the previous downloaded datasets? 
For example, I downloaded ```ENZYMES``` dataset, and I extracted the dataset with **no** ```pre_transform```. And I have to delete its ```processed``` folder?

**Comment by rusty1s** [comment]
No, only for the datasets which threw an error.

**Comment by WMF1997** [comment]
thank you~
