### ISSUE TITLE
Problems with QM9 dataset

### ISSUE THREAD

**Issue by jenniening** [rusty1s/pytorch_geometric#697]
## ❓ Questions & Help

After detailed check of QM9 data provided by pytorch_geometric (qm9.pt), I found two major problems of this dataset:
#### 1. Unit (Hartree) and Target (Total Energy)
I found the unit of energy terms like (HOMO, LUMO, gap, ZPVE, U0, U, H, G) in qm9.pt is Hartree. However, in the MPNN paper by J. Glimer, they used eV.  Hartree is about 27 times of eV and around 630 times of kcal/mol, thus, if we directly do the regression with these energy terms, and get MAE around 1, that means the error is 27 eV, which is very large compared with chemical accuracy (1kcal/mol)
In addition, in MPNN paper, for U0, U, H, and G, they actually used atomization energy as target, atomization energy can be got using (total energy of molecule - reference energy of all atoms from this molecule). This is also the common way to do molecular energy prediction, since the sum of reference energy of atoms is relative large compared with atomization energy and the reference energies of same atom are same in different molecules. 
Please check this unit and target issue, since if someone directly use their model's performance in qm9.pt to compare with the performance from other published papers for atomization energy prediction with unit as kcal/mol or eV, the result will be misleading.
Actually, in original MoleculeNet dataset used to prepare qm9.pt, they provided the atomization energy of U0, U, H, G in kcal/mol. 
#### 2.  Wrong Molecules. 
Many molecules in QM9 dataset have different number of atoms and different coordinates compared with their initial structures provided by MoleculeNet, which can be considered as wrong molecules. 
For example, molecule with index as 13324 in qm9.pt has 22 atoms, however, it has 19 atoms in its original sdf file (index is 13367) provided by MoleculeNet. The coordinates of the three extra hydrogen atoms are actually the bond type information of this molecule in sdf file, as shown below:
structure in initial sdf file
<img width="500" alt="Screen Shot 2019-09-24 at 10 55 56 AM" src="https://user-images.githubusercontent.com/15790018/65523273-0aeb8000-deba-11e9-8157-e4c14cb88100.png">
coordinates in qm9.pt file (index is 13324) 
<img width="400" alt="Screen Shot 2019-09-24 at 10 58 51 AM" src="https://user-images.githubusercontent.com/15790018/65523484-53a33900-deba-11e9-954f-6e3f195078d1.png">
The reason of this is that in your initial data preparation script (I found it from one request [here](https://gist.github.com/rusty1s/159eeff0d95e0786d220a164c6edd021), you loaded sdf file with no hydrogens(use removeHs=False to load molecules with hydrogens), and used AddH function to add hydrogens. Thus, the number of atoms can be changed since RDKit might add different number of Hs and the Hs order can be different from its original sdf file. <br>Actually, I found in your initial data preparation script, you checked the number of atoms after adding hydrogens, but it seems that you commented this part.
This is a important issue especially some models use coordinates as inputs.

**Comment by rusty1s** [comment]
Thank you for reporting this. This is super helpful. I will investigate this further and come back to you.

**Comment by rusty1s** [comment]
Hi, I fixed the QM9 dataset according to your observations. The preprocessing code is now included in the official dataset implementation, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/qm9.py#L93-L169). It would be really great if you find the time to look into it and validate its correctness.

Concerning the units, how would you suggest to implement it for `QM9`? Shall we add a helper function to manually transform the targets?

**Comment by jenniening** [comment]
Hi, thanks for your reply. The script looks great. 
For the targets, why don't you change [4:16] in the line 95: target = [[float(x) for x in line.split(',')[4:16]], into [4:20], to add the atomization energy of U0, U, H, and G into targets, and provide a description for the units of each target. This file can be found in the raw qm9 package(QM9_README). It would be great if everyone can know what prediction they make. 
In general, when we use QM9, we predict atomization energy for U0, U, H and G(in kcal/mol or eV). However, I'm not sure if anyone wants to directly predict molecular energy. Thus, it might be good to provide all the regression targets and detailed description for them.

**Comment by rusty1s** [comment]
Fixed, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.QM9). Thank you for your detailed explanations :)
