### ISSUE TITLE
setup.py test

### ISSUE THREAD

**Issue by chenyibi752259510** [rusty1s/pytorch_geometric#703]
Hi, when I run the setup.py test.

Problem:
running pytest
Searching for pytest-cov
Best match: pytest-cov 2.7.1
Processing pytest_cov-2.7.1-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/pytest_cov-2.7.1-py3.6.egg
Searching for pytest>=3.6
Best match: pytest 5.1.3
Processing pytest-5.1.3-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/pytest-5.1.3-py3.6.egg
Searching for coverage>=4.4
Best match: coverage 5.0a7
Processing coverage-5.0a7-py3.6-linux-x86_64.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/coverage-5.0a7-py3.6-linux-x86_64.egg
Searching for py>=1.5.0
Best match: py 1.8.0
Processing py-1.8.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/py-1.8.0-py3.6.egg
Searching for pluggy<1.0,>=0.12
Best match: pluggy 0.13.0
Processing pluggy-0.13.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/pluggy-0.13.0-py3.6.egg
Searching for packaging
Best match: packaging 19.2
Processing packaging-19.2-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/packaging-19.2-py3.6.egg
Searching for more-itertools>=4.0.0
Best match: more-itertools 7.2.0
Processing more_itertools-7.2.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/more_itertools-7.2.0-py3.6.egg
Searching for importlib-metadata>=0.12
Best match: importlib-metadata 0.23
Processing importlib_metadata-0.23-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/importlib_metadata-0.23-py3.6.egg
Searching for attrs>=17.4.0
Best match: attrs 19.1.0
Processing attrs-19.1.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/attrs-19.1.0-py3.6.egg
Searching for atomicwrites>=1.0
Best match: atomicwrites 1.3.0
Processing atomicwrites-1.3.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/atomicwrites-1.3.0-py3.6.egg
Searching for zipp>=0.5
Best match: zipp 0.6.0
Processing zipp-0.6.0-py3.6.egg

Using /home/administrator/chens/pytorch_geometric-master/.eggs/zipp-0.6.0-py3.6.egg
running egg_info
writing torch_geometric.egg-info/PKG-INFO
writing dependency_links to torch_geometric.egg-info/dependency_links.txt
writing requirements to torch_geometric.egg-info/requires.txt
writing top-level names to torch_geometric.egg-info/top_level.txt
reading manifest file 'torch_geometric.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_geometric.egg-info/SOURCES.txt'
running build_ext
================================================================= test session starts =================================================================
platform linux -- Python 3.6.8, pytest-5.1.3, py-1.8.0, pluggy-0.13.0
rootdir: /home/administrator/chens/pytorch_geometric-master, inifile: setup.cfg
plugins: cov-2.7.1
collected 160 items

test/test_debug.py .
test/data/test_batch.py .
test/data/test_data.py ..
test/data/test_dataloader.py .
test/data/test_dataset.py .
test/data/test_inherit.py .
test/data/test_sampler.py Fatal Python error: Segmentation fault

Current thread 0x00007f60d7568740 (most recent call first):
File "/home/administrator/

Please advise.

**Comment by rusty1s** [comment]
Can you post the installation log? There must have been an error somewhere. In addition, it helps if you report your python/gcc/cuda settings.

**Comment by chenyibi752259510** [comment]
Thank you for your reply. @rusty1s 
>>> import torch_scatter as tc
>>> print(tc.__version__)
1.3.1
>>> import torch_sparse as ts
>>> print(ts.__version__)
0.4.0
>>> import torch_cluster as tcl
>>> print(tcl.__version__)
1.4.4
>>> import torch_spline_conv as tsc
>>> print(tsc.__version__)
1.1.0
>>> import torch_geometric as tg
INFO:rdflib:RDFLib Version: 4.2.2

python 3.6.8
gcc 4.8.5
cuda 9.0

Please advise.
