### ISSUE TITLE
Radius Graph with Random K-Points Picking

### ISSUE THREAD

**Issue by czha5168** [rusty1s/pytorch_geometric#704]
Dear Matthias,

Thanks for reading my post. I have a quick question regarding the implementation of radius_graph(r, k). As I noticed that scipy.spatial.ckdtree is used, does this function would actually _return the k-nearest-neighbours_ **whose distance w.r.t "src_point" is less than r**? 

I am trying to implement a function to _random pick k points_ from **all neighbours who lie in the distance r**. Does it mean that I cannot use radius_graph() you completed? 

Many thanks!

**Comment by rusty1s** [comment]
Hi, you can still use the `radius_graph` method by setting `max_num_neighbors` to a high value. However, you need to randomly pick `k` neighbors afterwards on your own. We sadly do not provide a functionality for this.

**Comment by rusty1s** [comment]
If you use the `radius_graph` method on the GPU, it is however sufficient to set `max_num_neighbors` to `k` because of non-determinism in the output :)

**Comment by czha5168** [comment]
Thanks for your thunder reply! Just would like to confirm that Is it saying that since the GPU-version of radius_graph() method would not sort the neighbors according to their distances, it is therefore possible for us to use this version to achieve a random picking effects? Thanks!

________________________________

**Comment by rusty1s** [comment]
Yes :)

**Comment by czha5168** [comment]
Thanks Matthias! Have a good day!

________________________________
