### ISSUE TITLE
Getting rid of deprecation warnings thrown by the latest PyTorch 1.2

### ISSUE THREAD

**Issue by luost26** [rusty1s/pytorch_geometric#712]
My PyTorch version is the latest 1.2
when I am running `examples/gcn.py` to test whether I have configured PyG correctly, deprecations warnings keep throwing though the model works as expected. (see the screenshot below)

I guess it might be that some part of the framework is using the deprecated feature. If so, I think it is necessary to get rid of the warnings in the next version. 

and I will appreciate it if someone could tell me which part of the framework I should make some changes to in order to mute those warnings temporarily.

![Screenshot from 2019-10-01 23-51-52](https://user-images.githubusercontent.com/45375360/65978542-79c26d80-e4a6-11e9-9378-0b76c9869c94.png)

**Comment by rusty1s** [comment]
Thanks for reporting. I am aware of this issue and am working to fix it. In the meantime, it is sufficient to convert the train_mask, val_mask and test_mask to dtype torch.bool in order to mute the warnings.

**Comment by rusty1s** [comment]
Fixed in master! I will craft a new minor release soon.
