### ISSUE TITLE
subgraph deprecation warnings

### ISSUE THREAD

**Issue by MCSH** [rusty1s/pytorch_geometric#713]
## 🐛 Bug

When using the utils.subgraph, there is an error saying 
` indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.`

I traced it back and it seems to come from line 46 of `subgraph.py`. Any workaround to stop the warnings until it's fixed?

**Comment by rusty1s** [comment]
Thanks for reporting. Closing this in favor of https://github.com/rusty1s/pytorch_geometric/issues/712.
