### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#718]
## ❓ Questions & Help

Hello

I do have a questions about the structure of data in the dataset class. 
I'm creating my own dataset and so far i wanted to check if i'm doing things correctly, or if i'm on the wrong track.
I have 8 features per node. So far i have encoded them and created a tensor per node in the shape of.
`torch.Size([233, 8])`
Now if i understand the data structure correct, do i just have to stack them, to get a tensor of the shape:
`torch.Size([number_of_nodes, 233, 8])`
or is this an incorrect format?

**Comment by rusty1s** [comment]
Where does the `233` come from? IMO, the correct data structure would be `[number_of_nodes, 8]`.

**Comment by SaschaStenger** [comment]
The `233` is due to the dimensionality of my data. 
So one of my features, for example, is a text embedding, that is `[100,1]` and then i have another feature, that is categorical and has 233 categories. So i padded every other feature to this size and ended at `[233, 8]`

**Comment by rusty1s** [comment]
Ok, so the 8 features actually encode multi-dimensional features. In this case you should concat them to one multi-dimensional feature vector.

**Comment by SaschaStenger** [comment]
ok, thank you very much. Should i still pad them to the same length, or is this not necessary in this case?

**Comment by rusty1s** [comment]
This is not needed.
