### ISSUE TITLE
why does transforms.line_graph not modify the num_nodes attribute?

### ISSUE THREAD

**Issue by szhang104** [rusty1s/pytorch_geometric#721]
## ❓ Questions & Help

Hello,

I noticed that the transformed data instance's num_nodes is still the number of nodes before the transform. When batched together, the batch.batch attribute has an inconsistent dimension with the actual number of nodes (the number of edges previously). Is it intended or simply a neglect in implementation?

**Comment by szhang104** [comment]
After a little digging I found out that data.num_nodes is actually inferred from data.pos if pos exists. So if those things are not touched by the line graph transform process, num_nodes can remain unchanged.

**Comment by rusty1s** [comment]
Thank you for reporting this. This is not intended, and is caused, as you correctly found out, by non-transformed `data.pos` features. The `LineGraph` transform does now manually set the number of nodes, so that this bug shall be fixed in master :)
