### ISSUE TITLE
Support of TensorCore in GPU V100

### ISSUE THREAD

**Issue by YanMY2028** [rusty1s/pytorch_geometric#722]
## ❓ Questions & Help

Hi, I have a question about how to use the TensorCore of GPU V100 in pytorch_geometric?

**Comment by rusty1s** [comment]
Well, we do not make use of cuDNN or cuBLAS in PyTorch Geometric, and instead mostly rely on pure PyTorch functions. Hence, I guess your tensor cores are unused as long as PyTorch does not make use of them.

**Comment by YanMY2028** [comment]
Thanks.
