### ISSUE TITLE
Is it possible to install pytorch_geometric without CUDA?

### ISSUE THREAD

**Issue by david-leon** [rusty1s/pytorch_geometric#733]
## 📚 Installation

On my laptop environment there is no CUDA driver, the installation of torch-scatter/sparse/cluster packages all failed.

## Environment

* OS: MacOS 10.14.6
* Python version: 3.6.8
* PyTorch version: 1.2
* CUDA/cuDNN version: None

**Comment by rusty1s** [comment]
This is possible which is indicated by our [travis script](https://github.com/rusty1s/pytorch_geometric/blob/master/.travis.yml). What is the reason the installation failed?

**Comment by sain** [comment]
> [travis](https://github.com/rusty1s/pytorch_geometric/blob/master/.travis.yml)

Could you explain more?I'm new to it
