### ISSUE TITLE
Broadcast reduced feature, e.g., global_max_pooling, to the original nodes

### ISSUE THREAD

**Issue by BestSonny** [rusty1s/pytorch_geometric#739]
## ❓ Questions & Help

As we use global_max_pooling to reduce the **original features** of **multiple point**s to a **single-point** feature vector.  Now my question is how do we broadcast this feature back to the **original features** , e.g., broadcastAdd, broadcastSub, broadcastCat. 

@rusty1s I do not know whether pytorch_geometric provides similar functions for this. I would appreciate it for any helps

**Comment by rusty1s** [comment]
```python
x_reduced = global_max_pool(x, batch)
x_broadcasted = x[batch]
```

**Comment by BestSonny** [comment]
@rusty1s  Thanks a lot.
