### ISSUE TITLE
Add macOS to CI

### ISSUE THREAD

**Issue by RMeli** [rusty1s/pytorch_geometric#741]
## 🚀 Feature

Add `macOS` to continuous integration.

## Motivation

Test `pytorch_geometric` on `macOS`.

## Additional context

I might be able to provide a PR in the next few days.

**Comment by rusty1s** [comment]
Great issue, I didn't know Travis CI does support macOS. We also build PyG now on [macOS](https://github.com/rusty1s/pytorch_geometric/blob/master/.travis.yml).

**Comment by RMeli** [comment]
That's great! Thank you very much for taking care of this so quickly!

Can I suggest to add Python `3.6` to the CI as well. Issue rusty1s/pytorch_scatter#73 seems to be related only to Python `3.6`.

**Comment by RMeli** [comment]
Is this resolved as of b8e1068204eea7b4a820d1eed20a026cf86f052f
