### ISSUE TITLE
Add cosine argument for point cloud convolutions

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_geometric#745]
Hey there!

Was just looking through the knn_graph generators in XConv and noticed that the cosine argument from torch_cluster knn_graph is not available as an option. Would it be possible to add it as an argument in XConv, etc...? Thanks!

**Comment by rusty1s** [comment]
Fixed in [master](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/x_conv.py#L115).

**Comment by jlevy44** [comment]
Much appreciated, thanks!
