### ISSUE TITLE
Question about Point Cloud's examples. 

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#749]
## ❓ Questions & Help

hello: 

I ran the pointnet's example code provided in the repo, i.e. ```examples/pointnet2_classification.py``` and ```examples/pointnet2_segmentation.py```. I modified some code. Here are details of my training procedure.  

### Classification's details and results

modification details:  
1. I changed the path to my folder. (absolute path)
2. Since my datasets is ```pre-downloaded``` (I downloaded it before running this ```.py``` file), and ```pre-transform``` should never work. 
(P.S. I DO NOT USE ANY ```pre_transform``` in the downloaded datasets)
Then, I "compose" the pre-transform and transform part into one thing. for example:

before: (original code)
```python
pre_transform = torch_geometric.transforms.NormalizeScale()
transform = torch_geometric.transforms.SamplePoints(1024)
```
after: (My modification)
```python
transform = torch_geometric.transforms.Compose([
    torch_geometric.transforms.NormalizeScale(), 
    torch_geometric.transforms.SamplePoints(1024), 
])
```

other settings are the same. 

and I run it on ModelNet10, with a single NVIDIA GeForce 1080 GPU (8GB), with a 8-core Intel Core i7-4790 CPU, 8 GB  Memory, with about 5 hours to finish 200 epochs. 

result might be okay: about 90%'s test accuracy. 

(However, the test accuracy is about 85% after running for 1h, and it slowly moves up, with test accuracy "down and up" (from 82% to 87%), after a long time (~2h), it finally reaches 90%, with 92% the best)

I know that some part of the pointnet (as mentioned in previous issues, ```T-Net```(Transform Net) is not implemented in this example code), and result do affects. (However, the pointnet and pointnet++ paper only provides ModelNet40 's result, and ModelNet40's result can reach 91% that high. So I guess ModelNet10's result should be even higher.) 

So i just want to ask, in this part, is my training and testing "modification" okay?
(I think my word can express enough details, so i do not post screenshots here. )

### Segmentation's details and results
segmentation is implemented on ```ShapeNet``` dataset's ```Airplane``` class. 
```ShapeNet``` still has no pre-transformation, like ```ModelNet10```. And my transformation "method" is the same as above. to be more exactly:

```python
transform = T.Compose([
    T.NormalizeScale(), 
    T.RandomTranslate(0.01),
    T.RandomRotate(15, axis=0),
    T.RandomRotate(15, axis=1),
    T.RandomRotate(15, axis=2)
])
# pre_transform = T.NormalizeScale()
train_dataset = ShapeNet(path, category, train=True, transform=transform)
test_dataset = ShapeNet(path, category, train=False)
```

I commented ```pre_transform```, and put this commented part to ```transform```. 
and there are no other my modifications in segmentation part.  

the result is shown as the screenshots below.  
![2019-10-22 21-15-36屏幕截图](https://user-images.githubusercontent.com/37621591/67300410-7b6cd780-f520-11e9-8ae9-ba5b4a0e8b84.png)

and it really meets "overfitting", since test's metric: iou is declining
final result (after total 30 epochs):
![2019-10-22 21-40-03屏幕截图](https://user-images.githubusercontent.com/37621591/67300553-b3741a80-f520-11e9-97ab-a64054a80822.png)

and I checked the pointnet and pointnet++'s segmentation result on shapenet, and I am totally confused: "It does work on segmentation task, but, ... why does it do not work as good as...?", or, "Does my modification affects? if I do not modifiy any code and run it, what should be the result?"

#### 2. Loading modelnet40 is really a hard thing? (takes a lot of memory? (to be more exact, GPU memory?))
In classification task, at first, I manage to load modelnet40(instead of modelnet10), with batch_size=32, (each batch with a ```fps``` sampling (just for fun), and it failed due to lack of CUDA memory), when i run it with CPU mentioned above, with batch_size=8, and it works. and the result is screenshoted. 
![2019-10-22 21-57-43屏幕截图](https://user-images.githubusercontent.com/37621591/67301285-caffd300-f521-11e9-9dd3-b45fd3da7752.png)
here, 
内存 in chinese = memory in english
交换 in chinese = swap in english

as shown here, it does take a lot memory. what i want to ask is that: how much GPU memory does it take when i load a modelnet40 dataset?

I will try to load modelnet40, with batch_size=8, shuffle=True, on my non-"pre_transform"ed modelnet40 tomorrow. 

finally:
sorry for taking you such a long time to read the long and detail issue. maybe next time, i will split a long detailed issue into smaller, yet still detailed issues. (for example, this issue will be splited into 2 parts -- Classification and Segmentation)

yours sincerely, 
@wmf1997

**Comment by rusty1s** [comment]
Actually, I have never checked the pointnet2 code and simply implemented it based on the descriptions in the paper. You are right that the T-network is missing since it shouldn't be really needed for ModelNet10 as well as same augmentations. Your modifications look fine to me.

The GPU memory should be the same for ModelNet10 and ModelNet40, given that each model has only 1024 sampled points. However, if you do map `face` to the GPU (which you should never do), memory can increase dramatically since the ModelNet40 dataset contains a lot of models with really high triangle count.

**Comment by WMF1997** [comment]
thanks a lot! and i find out why it does not work. (when i set ba)

```python
for one_batch in m40_loader: # m40_loader is the dataloader of modelnet40
    one_batch_1 = one_batch.to(torch.device('cuda'))  # NOTE(wmf): this is the place where the bug occurs!
```
the code above meets CUDAError: lack of memory when the loader's batch_size set to 8.

when i write
```python
for one_batch in m40_loader:
    one_batch = one_batch.to(torch.device('cuda'))  # overwrite
```
this time it is fine when batch_size is set to be 8 and 16. 

and i tried the ```face2edge``` transform, with face deleted after the transform. memory does increase dramatically. 

yours sincerely
@WMF1997

**Comment by rusty1s** [comment]
I am not quite sure why the overwriting does resolve this issue. Do you have any intuition? For `face2edge`, the memory increase is to be expected since `edge_index` is huge for ModelNet data objects.

**Comment by WMF1997** [comment]
First, Sorry for my mistake. 

I failed to transform the test part of ```ShapeNet``` dataset. and this time, it works fine. 
(It trains well, but I misuse the test dataset, i.e. I do not use ```NormalizeScale``` in test part)
![image](https://user-images.githubusercontent.com/37621591/67454742-fc7db900-f65d-11e9-9682-b3bf0cd7973e.png)

finally, it reaches about 80%'s iou (after 1st epoch, test iou can reach 70%~74%?), and the final result is only a little(?3%~5%) lower than the paper's airplane dataset's iou. (I only compare the airplane's shape)
