### ISSUE TITLE
Got stuck in the installation of torch-scatter

### ISSUE THREAD

**Issue by JianJuly** [rusty1s/pytorch_geometric#752]
## Environment

* OS: ubuntu 16.04.1 LTS
* Python version: 3.6.3
* PyTorch version: 1.2.0
* CUDA/cuDNN version: 9.2.148 / 7.6.3
* GCC version: 5.4.0 
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [ x ] I followed the installation guide.
- [ x ] I cannot find my error message in the FAQ.
- [ x ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ x ] I have cloned the repository and tried a manual installation from source.
- [ x ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

`admin@amax:~$ pip install --verbose --no-cache-dir torch-scatter
Created temporary directory: /tmp/pip-ephem-wheel-cache-4tb3_sky
Created temporary directory: /tmp/pip-install-10s3u6d9
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting torch-scatter
  1 location(s) to search for versions of torch-scatter:
  * https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
  Getting page https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
  Starting new HTTPS connection (1): pypi.tuna.tsinghua.edu.cn
  https://pypi.tuna.tsinghua.edu.cn:443 "GET /simple/torch-scatter/ HTTP/1.1" 200 2689
  Analyzing links from page https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 0.3.0
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.2
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.3
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/2d/70/df2bc259d9606f00854ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec004d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.4
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/2f/97/c50a6aeaedc6924180c6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.0
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/91/5f/eb1d3ef3810cb1165859d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.1
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.2
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a0259105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.2.0
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/24/b7/680c3b392a4b55a0ebfb480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.0
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.1
    Found link https://pypi.tuna.tsinghua.edu.cn/packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz#sha256=890e8f9da2d57431912182960b71bf6c56397de42c2464907a6e9c583164bf06 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.2
  Using version 1.3.2 (newest of versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2)
  Created temporary directory: /tmp/pip-unpack-0iar9uhr
  https://pypi.tuna.tsinghua.edu.cn:443 "GET /packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz HTTP/1.1" 200 13563
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz
  Downloading from URL https://pypi.tuna.tsinghua.edu.cn/packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz#sha256=890e8f9da2d57431912182960b71bf6c56397de42c2464907a6e9c583164bf06 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/)
  Running setup.py (path:/tmp/pip-install-10s3u6d9/torch-scatter/setup.py) egg_info for package torch-scatter
    Running command python setup.py egg_info`

Then the installation did not go on.

**Comment by rusty1s** [comment]
Is there no actual error message present in the log? You can try to build from source to see the actual error message.

**Comment by JianJuly** [comment]
> Is there no actual error message present in the log? You can try to build from source to see the actual error message.

Have solved it. There is a network delay. Sorry...
