### ISSUE TITLE
(./examples/pointnet2_classification.py) FileExistError in Microsoft Windows when creating a new ModelNet 10 Dataset.

### ISSUE THREAD

**Issue by WMF1997** [rusty1s/pytorch_geometric#755]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/37621591/67444898-75204d80-f63d-11e9-9823-9cb76410d5a7.png)

The Chinese means:
When the folder exists, you cannot create the folder with same name. 

## To Reproduce

run ./examples/pointnet2_classification.py on Microsoft Windows. 

## Expected behavior

As the error shows, just delete the empty ```./raw``` dir, and rename the ```./ModelNet10``` dir to ```./raw``` dir, re-run the code, problem solved. This is a way of dealing with the problem. 

## Environment

* OS: Microsoft Windows 10, build 17134
* Python version: 3.6.4
* PyTorch version: 1.1.0(+cu90)
* CUDA/cuDNN version: 9.0.176/7.4
* Compiler version: (Visual Studio 2015, with MSVC 14.0)
* Any other relevant information: No

## Additional context

P.S. is num_workers really counts?

![image](https://user-images.githubusercontent.com/37621591/67445421-705c9900-f63f-11e9-86d6-19266f47cb51.png)

👆, After modifying the code below, I run the code, and it throws an error on multiprocessing which is related to ```DataLoader```. 

![image](https://user-images.githubusercontent.com/37621591/67445792-ba924a00-f640-11e9-93b7-d899b0f30fc1.png)

👆, My notebook's CPU is Intel Core i7-8750H, with an NVIDIA GeForce GTX 1060 (6GB) GPU. I am running some webpages on Microsoft Edge when I want to run the code. 

![image](https://user-images.githubusercontent.com/37621591/67445406-5f138c80-f63f-11e9-9679-e6bed0a3b613.png)

👆, This time, after removing ```num_workers=6``` (Sorry to tell you that the previous issue, i also modified this part), it is running. 

I know it should be a PyTorch issue. But... 

Adding a new thing which you might interset. 
Downloading DBP15K dataset: 

directly downloading DBP15K dataset via this URL. 
https://docs.google.com/uc?export=download&id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL 

I checked the code of ```google_drive_downloader``` and I add the ```id``` to the rest part

https://docs.google.com/uc?export=download  & id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL  is the final path. Then you can download it 

yours sincerely, 
@wmf1997

**Comment by rusty1s** [comment]
Does the first error occur for other datasets as well? There seems to be a Windows specific bug in [`makedirs`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/makedirs.py). Maybe you are able to fix this.

**Comment by WMF1997** [comment]
Perhaps No. I re-downloaded ```ShapeNet``` and extracting and processing goes fine.

**Comment by rusty1s** [comment]
So when exactly does this error occur? If you want to download a dataset to a directory where `raw/` already exists? Then `makedirs` should skip the creation of this directory.

**Comment by WMF1997** [comment]
When I re-downloaded the ```ModelNet``` in a new folder. I just run the ```./examples/pointnet2_classificatoin.py``` (without any modification). After downloading the **new** ```ModelNet10```, perhaps in the process of extracting? (sorry i forgot several hour's ago's process)

It is not a big problem. Manually remove the folder and rename it is okay~
