### ISSUE TITLE
Question about input batch graphs

### ISSUE THREAD

**Issue by hanin97** [rusty1s/pytorch_geometric#757]
## ❓ Questions & Help
Hi, 
though the analogous question asked by someone else, i can't understand how to input batch graph. For example, if i have two graphs with 'edges': [[0, 1, 1, 2],\n [1, 0, 2, 0]] and 'edges': [[0, 0, 1, 2],\n [1, 2, 0, 0]], how should i combine them if i want to input both of them at one time after concatenating their features x1 and x2?
Thanks.

**Comment by rusty1s** [comment]
You can use `torch_geomtric.data.Batch.from_data_list` or the `torch_geometric.data.DataLoader` to convert your graphs to batches, *e.g.*:
```python
Batch.from_data_list([data1, data2])
```

**Comment by hoffus** [comment]
thanks a lot.
