### ISSUE TITLE
Superpixels of MNIST

### ISSUE THREAD

**Issue by tonyandsunny** [rusty1s/pytorch_geometric#759]
## ❓ Questions & Help
Hi, 
Is the MNIST downloaded from the code an image that has been split into 75 super-pixel blocks?
If I want a full-grid image, can't I use the data downloaded from the MNISTSuperpixel class?
For the full-grid image, could you give me some advices?

**Comment by tonyandsunny** [comment]
Hi！
What should I do if I want to do a grid-graph?
I look forward to your reply, thank you very much.

**Comment by WMF1997** [comment]
Hello @tonyandsunny 
In fact, there are some methods of converting an "Image"(grid-graph) to some other kinds of graphs (something like ```MNISTSuperPixels```). One kind of method is called "SuperPixel Segmentation" (for example, ```SLIC``` or ```QuickShift``` algorithm). 

👇 is the screenshot of embedded_gcnn repo, which mentions my following words. the repo is: https://github.com/rusty1s/embedded_gcnn 
![image](https://user-images.githubusercontent.com/37621591/67634741-c872f400-f8fa-11e9-8c25-38e4bd795c6a.png)

see the readme.md in that repo. 

If you just want to convert the images to unregular graphs, run the python scripts to download the  datasets, and convert them. If you want to use the "converted graph" in ```PyG``, you have to write a ```torch_geometric.datasets.MyDataset``` (for example, ```CIFAR10``` in nodes and edges)

yours sincerely, 
@wmf1997

**Comment by tonyandsunny** [comment]
@WMF1997 
Thank you very much for your reply, I will try it.

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/716.

**Comment by tonyandsunny** [comment]
I did the MNIST dataset experiment on GCNconv. On data.edge_attr, I used my own method to get it. But the accuracy is always around 0.8, but it feels too low. Do you have any good suggestions to improve accuracy?
      data.x = F.elu(self.conv1(torch.cat((data.x,  data.pos),dim=1),data.edge_index,data.edge_attr))
      data.x = F.elu(self.conv2(data.x, data.edge_index,data.edge_attr))
      

       weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
      
        x, batch = max_pool_x(cluster, data.x, data.batch)
        x = global_mean_pool(x, batch)

        x = F.elu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

**Comment by rusty1s** [comment]
This is actually quite good for GCNConv according to https://arxiv.org/pdf/1611.08402.pdf. I doubt that you can get it much higher.

**Comment by tonyandsunny** [comment]
@rusty1s 
When I modify the code of torch_geometric/datasets, and add some 'class:MNISTSuperpixels_s'. But it tell me that  
Traceback (most recent call last):
  File "mnist_s_gcn.py", line 7, in <module>
    from torch_geometric.datasets import MNISTSuperpixels,MNISTSuperpixels_s
ImportError: cannot import name 'MNISTSuperpixels_s'
When I use the 'pycharm' to run the code, it can do it.
I am confused for it.

**Comment by tonyandsunny** [comment]
@rusty1s 
When I modify the code of torch_geometric/datasets, and add some 'class:MNISTSuperpixels_s'. But it tell me that  
Traceback (most recent call last):
  File "mnist_s_gcn.py", line 7, in <module>
    from torch_geometric.datasets import MNISTSuperpixels,MNISTSuperpixels_s
ImportError: cannot import name 'MNISTSuperpixels_s'
When I use the 'pycharm' to run the code, it can do it.
I am confused for it.
