### ISSUE TITLE
error related to topk

### ISSUE THREAD

**Issue by ThyrixYang** [rusty1s/pytorch_geometric#775]
## 🐛 Bug

I just encountered the same error mention in

https://github.com/inyeoplee77/SAGPool/issues/7

I found that the max index output by topk is larger than score.shape[0], so I think this maybe a bug about topk function.

## To Reproduce

To reproduce, 

1. clone the SAGPool code on https://github.com/inyeoplee77/SAGPool

2. run with "python main.py --dataset PROTEINS"

## Environment

* OS: ubuntu 19.04
* Python version: 3.7.4
* PyTorch version: 1.2
* CUDA/cuDNN version: CUDA 10.0
* GCC version: 7.4.0
* Any other relevant information:

**Comment by rusty1s** [comment]
This is not a PyG error, see my comment in inyeoplee77/SAGPool#7
