### ISSUE TITLE
How to impletement SpiderCNN with pytorch_geometric?

### ISSUE THREAD

**Issue by ganji15** [rusty1s/pytorch_geometric#778]
## 🚀 Feature

I wonder how to implement SpiderCNN with pytorch_geometric.
The corresponding paper URL is: https://arxiv.org/abs/1803.11527

I think the core idea of SpiderCNN is very similar to SplineCNN, since both aim to learn the geometric structures of graphs. However, the main difference between SpiderCNN and SplineCNN may be the graph convolutional filters.

## Motivation

![image](https://user-images.githubusercontent.com/3733327/68024506-3e090680-fce5-11e9-84d3-81f7a2219cb5.png)

The SpiderCNN can efficiently extract geometric features from point clouds. The authors design the filter as a product of a simple step function that captures local geodesic information and a Taylor polynomial that ensures the expressiveness.  The filters of SpiderCNN is defined as follows:

![18141220211234](https://user-images.githubusercontent.com/3733327/68024968-912f8900-fce6-11e9-9194-f51c486e68dd.png)

Could you please show how to implement this filter with torch_geometric? Thanks.

**Comment by rusty1s** [comment]
Implementing `SpiderCNN` should be straightforward in PyTorch Geometric. Here is an untested version:
```python
class SpiderConv(MessagePassing):
    def __init__(self, in_features, out_features, rs, aggr='add'):
        super(SpiderConv, self).__init__(aggr=aggr)

        self.w_S = torch.nn.Parameter(torch.Tensor([len(rs) + 1]))
        self.w_T = torch.nn.Paramter(torch.Tensor([20])
        
        self.reset_parameters()

     def reset_parameters(self):
        # Initialize `w_S` and `w_T`.

    def forward(self, x, edge_index, pos):
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        edge_attr = pos[edge_index[0]] - pos[edge_index[1]]
        return self.propagate(edge_index, x=x, edge_attr=edge_attr)

    def message(self, x_j, edge_attr):
        g_S = self.g_S(edge_attr)
        g_T = self.g_T(edge_attr)
        return x_j * g_S * g_T

    def g_S(self, edge_attr):
        norm = torch.norm(edge_attr, dim=-1, p=2)
        index = torch.full((edge_attr.size(0), ), -1, dtype=torch.long, device=edge_attr.device)
        for i in range(len(self.rs)):
            index[(edge_attr > self.rs[i] & edge_attr < self.rs[i+1])] = i
        return self.w_S[index]

    def g_T(self, edge_attr):
        # Implement g_{w_T}^{Taylor} according to Eq. (7)
```

**Comment by rusty1s** [comment]
Note that this implementation does perform convolution on single channels. The implementation needs to be modified for multiple node channels. I welcome any PRs :)

**Comment by ganji15** [comment]
@rusty1s Cool. I will try to modify the provided codes as far as possible. Thank you very much.
