### ISSUE TITLE
Any official tag release for pytorch v1.3.0 support?

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_geometric#779]
## 🚀 Feature

The pytorch v1.3.0 support in `torch_geometric`.

## Motivation

The pytorch has been officially released `v1.3.0`. 

Is there any official tag release for `torch_geometric` to natively support pytorch `v1.3.0`?

**Comment by mingloo** [comment]
@rusty1s

**Comment by rusty1s** [comment]
As far as I see, there is no need for a new release of PyG for PyTorch 1.3.0 since the API did not change. Our tests all pass with PyTorch version 1.3.0, see [here](https://travis-ci.org/rusty1s/pytorch_geometric).

**Comment by mingloo** [comment]
@rusty1s 

Thanks for your quick response. :)

I'll double check it on my side whether PyG can support PyTorch 1.3.0.

**Comment by mingloo** [comment]
@rusty1s 

Already double checked the `1.3.2` of `torch_geometric` can support pytorch `v1.3.0`.

Closed now.
