### ISSUE TITLE
scatter_ Segmentation Error

### ISSUE THREAD

**Issue by fguney** [rusty1s/pytorch_geometric#78]
in utils.scatter_, the max option produces a segmentation error while the others (mean and add) work fine. It probably has something to do with the fill value for max operation, what is it for exactly?

**Comment by rusty1s** [comment]
This does not seem related to the `fill_value`. The `fill_value` fills the initial output tensor, resulting in `max(x, fill_value)` for `scatter_max`. This seems to be more related to a false installation of `torch_scatter` (eventually produced by multiple CUDA or GCC versions).
