### ISSUE TITLE
questions about examples/enzymes_diff_pool.py

### ISSUE THREAD

**Issue by zechenzhang** [rusty1s/pytorch_geometric#780]
## ❓ Questions & Help
Hi,
I'm reading through the code and try to make use of diffpool. I encounter two questions:

1. Is there any particular reason to use dense mode to implement diffpool? Except the original implementation is done in dense mode. More specifically, why bother pad zeros first to match the dimensions and then use masks to eliminate padded zeros instead of using edge list?

2. In the example code, line 92, I assume this block is the second layer of pooling, shouldn't the num_nodes = pool_ratio^2 * max_nodes?

Thanks for your help!

**Comment by rusty1s** [comment]
Hi,

1. Well, `DiffPool` is a dense operator, so it does not make much sense using sparse GNNs on dense adjacency matrices due to efficiency.
2. Yes, you are right. Fixed in master.

**Comment by zechenzhang** [comment]
Got you, thanks for the quick reply!

**Comment by jiachangliu** [comment]
Hi I have a question. For the file "examples/enzymes_diff_pool.py", the test accuracy is actually pretty low, about 28.33%. However, in the official paper, the result is 62.53%. Why is there such a big mismatch?

**Comment by jiachangliu** [comment]
Hi @rusty1s , I have a question. For the file "examples/enzymes_diff_pool.py", the test accuracy is actually pretty low, about 28.33%. However, in the official paper, the result is 62.53%. Why is there such a big mismatch?

**Comment by rusty1s** [comment]
Yes, I am aware of this. It did work on `ENZYMES` earlier, and it is still working for other datasets such as `PROTEINS`. I believe there might be something up with the `ENZYMES` dataset. The `topk` pooling script does not work on `ENZYMES` either.
