### ISSUE TITLE
Dataset Creation

### ISSUE THREAD

**Issue by seunAdeks** [rusty1s/pytorch_geometric#786]
## ❓ Questions & Help

I have my data objects in a list in the following form:
x.shape = [819, 14] edge_index.shape = [2, 402000] 
x.shape = [701, 14] edge_index.shape = [2, 162000] 

The error appears at data, slices = self.collate(data_list)

I get a RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 819 and 701 in dimension 1 at C:\w\1\s\tmp_conda_3.6_160730\conda\conda-bld\pytorch_1570810118016\work\aten\src\TH/generic/THTensor.cpp:689

I have tried transposing my node features to no avail, its exactly the same error.

**Comment by rusty1s** [comment]
It seems that your shapes do not align with the ones you reported. The DataLoader tries to concatenate `x` in dimension 1, but it encounters unequal sizes (819, 701) in dimension 1.

**Comment by seunAdeks** [comment]
Well, the print for data.num_nodes and data.num_features are correct for the data independently. So I just decided to merge the data first before initializing it as a Data object of pytorch geometric.
