### ISSUE TITLE
Converting graph to undirected

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#789]
## ❓ Questions & Help

There is one other thing I noticed and i'm not sure if it's a bug, a feature request, or if i'm just using it wrong. 
When using the function utils.to_undirected() it produces more edges, then there were originally in the dataset. This is usually no problem, but for when i'm using edge attributes in the graph as well. Then there are now edges, then attributes in the data object, which doesn't work.
Can i use to_undirected on the edge attribute as well?

**Comment by rusty1s** [comment]
No :) `to_undirected` can not infer the edge attributes of your reversed edges. You need to manually add them to your graph.

**Comment by SaschaStenger** [comment]
Does `to_undirected` just add the same edges, but in the reverse source/destination to my `edge_index`? or does it change the order in anyway. Because then i would just add the `edge_attr` vector again.

**Comment by rusty1s** [comment]
No, it reorders your `edge_index` and removes duplicates. Actually, it might be easier to just implement it yourself:
```python
row, col = edge_index
row = torch.cat([row, col])
col = torch.cat([col, row])
edge_index = torch.stack([row, col], dim=0)
edge_attr = torch.cat([edge_attr, edge_attr], dim=0)
```

**Comment by SaschaStenger** [comment]
Great, thanks for the quick help
