### ISSUE TITLE
How to calculate node-wise product within the same graph

### ISSUE THREAD

**Issue by ThyrixYang** [rusty1s/pytorch_geometric#793]
## ❓ Questions & Help

Hi,

Suppose the graphs are in form x, edge_index, edge_attr, batch

And I want to calculate node-wise similarity within the same graph, so if x contains only one graph, I need dot(x, x^T). But now there are many graphs in a batch, how can I do this efficiently(using only x and batch)? 

After some transformation, e.g. pooling or unpooling, the size of graphs will change, say x1, batch1 before pooling and x2, batch2 after pooling. How can I calculate something like dot(x1, x2^T) within each graph?

Thanks.

**Comment by rusty1s** [comment]
You can use the `to_dense_batch`function to convert your features into shape `[batch_size, max_num_nodes, num_features]:
```python
z, z_mask = to_dense_batch(x, batch, fill_value=0)
S = z @ z.transpose(-1, -2)
```

**Comment by ThyrixYang** [comment]
Thanks for replying.
