### ISSUE TITLE
Dynamic batching for different sizes of graph inputs

### ISSUE THREAD

**Issue by mulaixi** [rusty1s/pytorch_geometric#796]
## ❓ Questions & Help

Hi, I'm trying to implement a node classification task by using GCN. I have multiple graphs, and for this case I only saw graph classification examples, but what I wanted to do is node classification.

Let's suppose I have 20 different graphs(with different number of nodes, edges, features). And each node of every graph is labeled.
All the nodes in first 10 graphs are for training, all the nodes of the next 5 graphs are for val, and all the nodes of last 5 graphs are for test, and what I try to do is predicting labels of the nodes for the graphs in test-set. 

As I saw, by the help of block diagonal adjacency matrix, I can batch the nodes. But what I need to do is creating batches for each graph. (for example first graph has 150 nodes, second graph has 200 nodes, so I want to batch them as a whole.) Is it possible to do it by using `pytorch-geometric`?

**Comment by tchaton** [comment]
Hey @mulaixi,

For sure you can.
 The number of nodes and edges doesn't matter. They can be different, it is why you try to classify them :)
They just need to have the same dimension for their features. And even there, you could pad with 0.

Best,
T.C

**Comment by MareArts** [comment]
@tchaton 
Thank you in advanced.
In that case, how can we padding edge_index?
Thank you.

**Comment by Zer0Credibility** [comment]
> @tchaton
> Thank you in advanced.
> In that case, how can we padding edge_index?
> Thank you.

No need to pad the edge_index -- you may want to pad the node features but that will be the same as for any other feature vector.
