### ISSUE TITLE
Do you have any benchmark for those graph-conv layers?

### ISSUE THREAD

**Issue by xuehui1991** [rusty1s/pytorch_geometric#797]
## ❓ Questions & Help

Do you have any benchmark for those graph-conv layers? (in public open source dataset)

**Comment by rusty1s** [comment]
Sure, you can find our complete benchmark suite in `benchmark/`. Results of those experiments are given in [our paper](https://arxiv.org/abs/1903.02428).

**Comment by xuehui1991** [comment]
@rusty1s Thanks~
