### ISSUE TITLE
Improving GPU Usage, decreasing CPU usage

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#811]
## ❓ Questions & Help

Hi

When i'm running my network, I do have a really high CPU load and a rather small GPU load. I would rather turn this around. Are there any general tips, as to how to do that?
Currently i'm using an implementation, that is very close to the [rgcn.py example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/rgcn.py), although I have modified the data loader for my dataset. 

```
dataset = dataset.shuffle()
train_dataset = dataset[:9000]
test_dataset = dataset[9000:]

batch_size = 128

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True)
test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False)
```

I'm training a binary classifier on a dataset of rather small graphs. 
In the dataset there are around 10.000 graphs, but they are rather small with an average of around 20 nodes per graph.
And currently i'm using around 6 of the 12GB on my GPU.

**Comment by rusty1s** [comment]
Setting `num_workers` of the `DataLoader` might help.

**Comment by SaschaStenger** [comment]
Oh, i didn't know it had that property. Is this documented somewhere, as i cant find it [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.DataLoader)?

**Comment by zz-cloud** [comment]
using a single gpu appears this problem，a really high CPU load and a rather small GPU load（around 1%-3%） ， why？code problem or config？thank you

**Comment by SaschaStenger** [comment]
That usually appears, during the preprocessing of the dataset. The cpu is transforming the dataset, before loading it into gpu memory. 
at least that’s my guess. Running the code in debug Mode should enable you to find out, where you currently are in your execution.
