### ISSUE TITLE
convert batch to graph data format on the fly

### ISSUE THREAD

**Issue by rakhimovv** [rusty1s/pytorch_geometric#812]
## ❓ Questions & Help

Hi! I have a batch of graphs with the same "graph structure" (the same number of nodes, the same connectivity matrix, the same node order, but different features). I want to do something like this on the fly:

```
def forward(self, x):
    # some my operations
    # x.size() = (batch_size, num_nodes, num_features)
    x = convert_to_acceptable_format(x)
    x = GCNConv(x, same_edge_index_for_all_graph_in_batch)
    x = convert_back_to_tensor(x) # of size (batch_size, num_nodes, num_features)
    # some my operations
    return x
```

I searched through the documentation but did not found something directly relevant.
Could you recommend a solution, please

**Comment by rusty1s** [comment]
Please see this issue https://github.com/rusty1s/pytorch_geometric/issues/817
