### ISSUE TITLE
Fixed, static graph with varying Node samples

### ISSUE THREAD

**Issue by emanuelazcona** [rusty1s/pytorch_geometric#817]
I'm trying to get started on using this package for an experiment I'm running and I'd like to use the ChebConv class.

My problem uses a fixed, static graph of shape: 

A: _N_ x _N_ (Nodes x Nodes)

and an input of shape:

X: _S_ x _N_ x _F_ (Samples x Nodes x Features)

where what "changes" here is different instances/samples of the same graph (same number of Nodes & Features) for each sample.

**How can I use the Data functions from utils library here?**

I don't want to use a Data object for each Sample because every sample has the same edges and edge features, where the number of nodes is ~= 600k. If I use a Data object for every sample I'd be replicating the same graph _S_-times (one for each sample of _X_)

I just want one object that has my adjacency matrix (2D) and another for my input tensor (3D) and batch over the _Samples_ dimension of the input tensor

**Comment by emanuelazcona** [comment]
I'm not sure if I'm answering my own question here, but:

Should I just create a single Data object of dimensions: _Nodes_ x _Samples_ x _Features_ ?

How would I batch over a single Data object though..

**Comment by emanuelazcona** [comment]
> I'm not sure if I'm answering my own question here, but:
> 
> Should I just create a single Data object of dimensions: _Nodes_ x _Samples_ x _Features_ ?
> 
> How would I batch over a single Data object where my batch dimension is in the middle though..I'm very confused

**Comment by emanuelazcona** [comment]
close was an accident

**Comment by rusty1s** [comment]
This is now supported with the latest commit via the `dim` attribute of `MessagePassing` [1, 2]. If you have batched node features `x` with shape `[B, N, F]` and a sparse single adjacency matrix `edge_index` with shape `[2, E]`, all you need to do is:
```python
conv = GCNConv(in_channels, out_channels, dim=1)
out = conv(x, edge_index)
```
[1] https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L17-L40
[2] https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/conv/test_static_graph.py

**Comment by rusty1s** [comment]
All you need to test if pull PyG from GitHub and run `python setup.py install`. If you encounter any issues with this, please let me know.

**Comment by emanuelazcona** [comment]
> This is now supported with the latest commit via the `node_dim` attribute of `MessagePassing` [1, 2]. If you have batched node features `x` with shape `[B, N, F]` and a sparse single adjacency matrix `edge_index` with shape `[2, E]`, all you need to do is:
> 
> ```python
> conv = GCNConv(in_channels, out_channels, node_dim=1)
> out = conv(x, edge_index)
> ```
> 
> [1] https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L17-L40
> [2] https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/conv/test_static_graph.py

This didn't fix the issue. As it stands, the code works regardless of whether

`node_dim = 0` or `node_dim=1` .

By using the `Batch` operation, my data, `x`, of dimensions `B x N x F`, is now just converted to `B*N x F`

**Comment by emanuelazcona** [comment]
<img width="1028" alt="Screen Shot 2019-12-01 at 2 50 29 PM" src="https://user-images.githubusercontent.com/13724351/69919376-17580000-144a-11ea-8ea1-bd96efbe2f6a.png">

<img width="1024" alt="Screen Shot 2019-12-01 at 2 50 39 PM" src="https://user-images.githubusercontent.com/13724351/69919377-1d4de100-144a-11ea-9b47-6806d3797c9a.png">

**Comment by emanuelazcona** [comment]
<img width="1025" alt="Screen Shot 2019-12-01 at 2 50 52 PM" src="https://user-images.githubusercontent.com/13724351/69919385-2a6ad000-144a-11ea-89f8-6b5f248c9999.png">

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-67-148a90e9dae8> in <module>
     13 out = conv_layer(x = batch2.x,
     14                  edge_index = A_test.edge_index,
---> 15                  edge_weight = A_test.edge_attr)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/cheb_conv.py in forward(self, x, edge_index, edge_weight, batch, lambda_max)
    113         edge_index, norm = self.norm(edge_index, x.size(0), edge_weight,
    114                                      self.normalization, lambda_max,
--> 115                                      dtype=x.dtype, batch=batch)
    116 
    117         Tx_0 = x

/usr/local/lib/python3.6/dist-packages/torch_geometric/nn/conv/cheb_conv.py in norm(edge_index, num_nodes, edge_weight, normalization, lambda_max, dtype, batch)
     90 
     91         edge_index, edge_weight = get_laplacian(
---> 92             edge_index, edge_weight, normalization, dtype, num_nodes)
     93 
     94         if batch is not None and torch.is_tensor(lambda_max):

/usr/local/lib/python3.6/dist-packages/torch_geometric/utils/get_laplacian.py in get_laplacian(edge_index, edge_weight, normalization, dtype, num_nodes)
     42 
     43     row, col = edge_index
---> 44     deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
     45 
     46     if normalization is None:

/usr/local/lib/python3.6/dist-packages/torch_scatter/add.py in scatter_add(src, index, dim, out, dim_size, fill_value)
     73     """
     74     src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
---> 75     return out.scatter_add_(dim, index, src)

RuntimeError: Invalid index in scatterAdd at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721`

**Comment by emanuelazcona** [comment]
This appears to be the same issue as #611

**Comment by rusty1s** [comment]
Are you sure you are working on PyTorch Geometric master? What happens if you run the following test code?
```python
import torch
from torch_geometric.data import Data, Batch
from torch_geometric.nn import MessagePassing, GCNConv, ChebConv


class MyConv(MessagePassing):
    def forward(self, x, edge_index):
        return self.propagate(edge_index, x=x)


def test_static_graph():
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
    x1, x2 = torch.randn(3, 8), torch.randn(3, 8)

    data1 = Data(edge_index=edge_index, x=x1)
    data2 = Data(edge_index=edge_index, x=x2)
    batch = Batch.from_data_list([data1, data2])

    x = torch.stack([x1, x2], dim=0)
    for conv in [MyConv(), GCNConv(8, 16), ChebConv(8, 16, K=2)]:
        out1 = conv(batch.x, batch.edge_index)
        assert out1.size(0) == 6
        conv.node_dim = 1
        out2 = conv(x, edge_index)
        assert out2.size()[:2] == (2, 3)
        assert torch.allclose(out1, out2.view(-1, out2.size(-1)))

test_static_graph()
```

**Comment by emanuelazcona** [comment]
On another note, I'm now getting an error after reinstalling PyTorch Geometric (to ensure it's from master even though I'm sure it is).

`-----------------------------------------------------------------------
RuntimeError                          Traceback (most recent call last)
<ipython-input-1-09a0f6707436> in <module>
     14 
     15 import torch
---> 16 import torch_geometric
     17 
     18 from torch_geometric.transforms import LaplacianLambdaMax

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/__init__.py in <module>
      3 import torch_geometric.data
      4 import torch_geometric.datasets
----> 5 import torch_geometric.transforms
      6 import torch_geometric.utils
      7 

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/__init__.py in <module>
     34 from .delaunay import Delaunay
     35 from .to_superpixels import ToSLIC
---> 36 from .gdc import GDC
     37 
     38 __all__ = [

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py in <module>
      8 
      9 
---> 10 class GDC(object):
     11     r"""Processes the graph via Graph Diffusion Convolution (GDC) from the
     12     `"Diffusion Improves Graph Learning" <https://www.kdd.in.tum.de/gdc>`_

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py in GDC()
    486 
    487     @staticmethod
--> 488     @numba.njit(cache=True)
    489     def __calc_ppr__(indptr, indices, out_degree, alpha, eps):
    490         r"""Calculate the personalized PageRank vector for all nodes

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/decorators.py in wrapper(func)
    192                           **dispatcher_args)
    193         if cache:
--> 194             disp.enable_caching()
    195         if sigs is not None:
    196             # Register the Dispatcher to the type inference mechanism,

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/dispatcher.py in enable_caching(self)
    677 
    678     def enable_caching(self):
--> 679         self._cache = FunctionCache(self.py_func)
    680 
    681     def __get__(self, obj, objtype=None):

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/caching.py in __init__(self, py_func)
    612     def __init__(self, py_func):
    613         self._name = repr(py_func)
--> 614         self._impl = self._impl_class(py_func)
    615         self._cache_path = self._impl.locator.get_cache_path()
    616         # This may be a bit strict but avoids us maintaining a magic number

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/caching.py in __init__(self, py_func)
    347         else:
    348             raise RuntimeError("cannot cache function %r: no locator available "
--> 349                                "for file %r" % (qualname, source_path))
    350         self._locator = locator
    351         # Use filename base name as module name to avoid conflict between

RuntimeError: cannot cache function 'GDC.__calc_ppr__': no locator available for file '/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py'`

**Comment by Boltzmachine** [comment]
> This is now supported with the latest commit via the `node_dim` attribute of `MessagePassing` [1, 2]. If you have batched node features `x` with shape `[B, N, F]` and a sparse single adjacency matrix `edge_index` with shape `[2, E]`, all you need to do is:
> 
> ```python
> conv = GCNConv(in_channels, out_channels, node_dim=1)
> out = conv(x, edge_index)
> ```
> 
> [1] https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/message_passing.py#L17-L40 [2] https://github.com/rusty1s/pytorch_geometric/blob/master/test/nn/conv/test_static_graph.py

Is it safe to use this feature for other Conv module and modules with `edge_weights` or `edge_attr`?

**Comment by rusty1s** [comment]
The GNN operators that support static graphs are defined [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/cheatsheet.html).

**Comment by engmubarak48** [comment]
This was very helpful and smart way to hand the extra dimension. Thank you @rusty1s :)

**Comment by engmubarak48** [comment]
@rusty1s thanks.. for static graphs where we might have (T, N, D) .. does layernom and batchnorm of pyg also support these dimensions?
