### ISSUE TITLE
Dataset split

### ISSUE THREAD

**Issue by SaschaStenger** [rusty1s/pytorch_geometric#818]
## ❓ Questions & Help

Hi

So i'm currently trying to combine two very similar datasets. 
I have them at two distinct locations and my goal would be to load both into the same dataset, using one as the training data and the other one as the test and val data. 
Now when using an `InMemoryDataset`, i thought about using masks for that. 
But as far as i have found in the datasets provided, masks are used to use certain parts of graphs for training and other parts for testing (am i right, or am i misunderstanding them?)

Would there be a way, to declare certain graphs as part of the training data, and others as part of the test data?

Sorry if it's a simple question, but i haven't worked with masks before.

**Comment by rusty1s** [comment]
Just split them into `train` and `test` set and load them separaretly, *e.g.*, like [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/modelnet.py).

**Comment by SaschaStenger** [comment]
Oh
now i feel a little stupid for not looking hard enough. 
Thank you for your fast and accurate reply.

**Comment by SaschaStenger** [comment]
Hi
so I followed the example dataset, that you linked me and the processing does work fine. The two datasets are being saved to disk and when looking at the size i think that they are being saved correctly. 

But, I somehow have trouble loading them. 
So if I try to load my train data like this 
```
from dataset import Dataset_Comparison

train= Dataset_Comparison('dataset', train=True)
```

I get the following error
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/ml-sdstenger/anaconda3/envs/Thesis/lib/python3.7/site-packages/torch/serialization.py", line 227, in _check_seekable
    f.seek(f.tell())
AttributeError: 'tuple' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ml-sdstenger/Thesis/testingground.py", line 293, in <module>
    gossip = Dataset_Comparison('dataset', train=True)
  File "/home/ml-sdstenger/Thesis/dataset.py", line 363, in __init__
    self.data, self.slices = torch.load(path)
  File "/home/ml-sdstenger/anaconda3/envs/Thesis/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ml-sdstenger/anaconda3/envs/Thesis/lib/python3.7/site-packages/torch/serialization.py", line 588, in _load
    _check_seekable(f)
  File "/home/ml-sdstenger/anaconda3/envs/Thesis/lib/python3.7/site-packages/torch/serialization.py", line 230, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/ml-sdstenger/anaconda3/envs/Thesis/lib/python3.7/site-packages/torch/serialization.py", line 223, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'tuple' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

And I have no idea, what this error tells me. 
Because if i just load the data with `torch.load()` from disc, it doesn't complain. 



The dataset code would be:
```
class Dataset_Comparison(InMemoryDataset):
    def __init__(self, root, train=True, transform=None, pre_transform=None):
        super(Dataset_Comparison, self).__init__(root, transform, pre_transform)
        path = self.processed_paths[0] if train else self.processed_paths[1],
        self.data, self.slices = torch.load(path)

    def _download(self):
        pass

    @property
    def processed_file_names(self):
        return ['train.pt', 'test.pt']

    @property
    def raw_file_names(self):
        train= ['dataset/train/raw/{0}'.format(element) for element in os.listdir('dataset/train/raw')]
        politifact = ['dataset/test/raw/{0}'.format(element) for element in os.listdir('dataset/test/raw')]
        return train, test

    def process(self):
        torch.save(self.process_set('train'), self.processed_paths[0])
        torch.save(self.process_set('test), self.processed_paths[1])

    def process_set(self, dataset):
        data_list = []
        if dataset == 'train':
            raw_file_paths = self.raw_file_names[0]
        else:
            raw_file_paths = self.raw_file_names[1]

        for raw_path in raw_file_paths:
              ....lots of processing.....

                data = Data(x=features, y=graph_label, edge_index=edges, edge_attr=edge_features)

                data_list.append(data)

        print('Saved ' + dataset)
        return self.collate(data_list)
```

I did leave out some of the processing that i'm doing, but i can't imagine, that it would interfere in any way.

**Comment by rusty1s** [comment]
So it crashes in the `torch.load` call but it does not crash when you load it manually? I am confused.

**Comment by SaschaStenger** [comment]
Yes, for whatever reason it crashes when i try to load it this way. But I just made a workaround. 
I initialize the encode that i'm using on both datasets beforehand and then pass it to both datasets as an argument, when creating them, so that both are using the same encoder instance.  
It's possible, that i have made a mistake, when coding the above section somewhere, but i cant find it and so i'll just be moving on to this solution.
