### ISSUE TITLE
data loader for the task of graph-level regression

### ISSUE THREAD

**Issue by greenappletree** [rusty1s/pytorch_geometric#838]
## ❓ Questions & Help
Hi, we are focusing on the task of graph-level regression. But we have a question when loading the dataset. We have checked the examples (e.g., qm9_nn_conv.py, colors_topk_pool.py), which are complicated for us. 

When loading the dataset for the task of graph-level regression, can we utilize the template (class MyOwnDataset(InMemoryDataset))? One data object corresponds to one graph. Is it feasible to implement like that?

Thanks.

**Comment by rusty1s** [comment]
Yes, you can use `InMemoryDataset` for this. Instead of inputting a class into `y`, just pass in your regression value.

**Comment by greenappletree** [comment]
> Yes, you can use `InMemoryDataset` for this. Instead of inputting a class into `y`, just pass in your regression value.

Thanks for your reply.
