### ISSUE TITLE
what's the difference between dataset[i] and  for data in dataset?

### ISSUE THREAD

**Issue by 649459021** [rusty1s/pytorch_geometric#839]
## ❓ Questions & Help

```python
for i, data in enumerate(dataset):
    print(dataset[i] == data)
    break
    
print(dataset[0])
for data in dataset:
    print(data)
    break
```
Output:
False
Data(edge_index=[2, 116], x=[18, 136], y=[1])
Data(edge_index=[2, 116], x=[18, 136], y=[1])

Why the answer is false?
The data which is in for loop cannot extend attributes, was it deliberately designed like this?

Thanks for your help

**Comment by 649459021** [comment]
data
```python
dataset = TUDataset(path, 'IMDB-BINARY').shuffle()
data = dataset[0]
print(data == dataset[0])
```
output: False

dataset[i] cannot extend attributes, but data can.
I think maybe the two should not be different.

**Comment by rusty1s** [comment]
Although the data objects hold the same graphs, they are newly created for each call, resulting in data objects that do not share memory. This works as intended, as you would expect a raw data object each time you request a new one. This is also in line with any `torchvision` object and allows, e.g., the usage of `transforms`.

**Comment by 649459021** [comment]
Thanks for your reply. So if I want to extend attributes, I should create a new data list even if PyG has this dataset?

**Comment by rusty1s** [comment]
The easiest would be to use `transforms`, either using the `transform` or `pre_transform` flag. If this is not possible, an alternative would be to just grap each data object once, and add it to a list:
```python
data_list = [data for data in dataset]
# Modify your data.
loader = DataLoader(data_list, ...)
```

**Comment by 649459021** [comment]
Thank you !  Actually I do use the second way.
