### ISSUE TITLE
from_networkx does not add node features

### ISSUE THREAD

**Issue by ashwinvasudevan** [rusty1s/pytorch_geometric#846]
## 🐛 Bug

When trying to import a graph from networkx, networkx node's features are imported as separate attributes inside the data objects when they should available under `Data['x']`
## To Reproduce

```
from torch_geometric.utils.convert import from_networkx
import networkx as nx

# build a nx graph
graph = nx.Graph()
graph.add_node(1, val=2, time=2)
graph.add_node(2, val=3, time=3)
graph.add_node(3, val=4, time=4)
graph.add_edge(1, 2)
graph.add_edge(2, 3)

# Convert into py_g
py_g = from_networkx(graph)
print(py_g)
```

## Output 
```
Data(edge_index=[2, 4], time=[2], val=[2])
```

## Expected behavior
```
Data(edge_index=[2, 4], x=[3, 2])
```

## Fix
Fix is to add the following code to `from_networkx`. It stacks the tensors and assigns the stacked tensor to `Data['x']` 
```
ts = torch.stack([val for val in data.values()], dim=1)
data = Data(x=ts, edge_index=edge_index)
return data
```
```
Data(edge_index=[2, 4], x=[3, 2])
```

Please let me know if this behavior of `network_x` is correct, Will submit a pull. :)

**Comment by rusty1s** [comment]
I think this works as intended. We shouldn't do any magic here in case the user wants to save their features into separate matrices. The fix would be to merge features manually before or after calling `from_networkx`. Are you fine with this?

**Comment by ashwinvasudevan** [comment]
I don't think a fix is required if this is intended. Closing the issue.

**Comment by songsong0425** [comment]
Hi, I have same error during run <from_networkx> and add above two lines of codes into <from_networkx>.
But I faced the error <TypeError: expected Tensor as element 1988 in argument 0, but got int>. (In this case, 1988 (actually, 1986 is the correct number of nods) is the number of nodes)
How can I fix this error?

**Comment by songsong0425** [comment]
I faced same issue and find very simple way: `py_g = from_networkx(graph, group_node_attrs=all)`.
