### ISSUE TITLE
Edgepooling example

### ISSUE THREAD

**Issue by mariolinovIC** [rusty1s/pytorch_geometric#848]
Hi,
Could you add any example that makes use of EdgePooling (and unpooling). I do not know why when I try to incorporate it my code I get an error message during backward propagation:
> RuntimeError: Expected isFloatingType(grads[i].type().scalarType()) to be true, but got false.
Thanks in advance and congratulations for developing PyTorch Geometric.

**Comment by rusty1s** [comment]
I just added `EdgePooling` to the [benchmark suite](https://github.com/rusty1s/pytorch_geometric/tree/master/benchmark/kernel), and it works without your mentioned error.

**Comment by mariolinovIC** [comment]
Thanks, I'll have a look.
