### ISSUE TITLE
Classification of CAD models

### ISSUE THREAD

**Issue by theveloped** [rusty1s/pytorch_geometric#85]
First of all great work on the library! This is some amazing work and awesome to see papers accompanied with their actual implementations!

I'm looking into the use of the library to classify 3D CAD models (e.g. nuts and bolts). SplineCNN seems to do some great work on matching 3D meshes. In my case I also have the original 3D models in unmeshed (NURBS) form, I'm wondering if anyone has any experience with classifiers on this level instead of meshes and if this was ever implemented using pytorch geometric.

I'm completly new in the field of deep learning and have a hard time judging if it would be better to mesh the shapes first. My gut tells me the high level topological information allready has all the geometric data in a very condensed (graph) form and thus would be the ideal starting point.

**Comment by rusty1s** [comment]
Hi and sorry for answering late,

Personally, I do not have any experience with deep learning on 3d models in NURBS format. Therefore, this is currently not implemented within PyTorch Geometric.

However, as you said, this should definitively be possible using tools such as SplineCNN or others. I did a quick google search, but I couldn't find any papers using graph neural networks that uses NURBS as input.

**Comment by theveloped** [comment]
Thanks for the insight! Indeed I could find very little research on this field. There is a lot of classical research on CAD models to perform feature recognition and shape comparison. One of the approaches used is to describe the entire topology in the form of a graph. A very simple graph that conveys nearly all of the topological information is often referred to as the attributed adjacency graph. It is this that my gut feeling tells me would be ideal for deep learning on as it would dramatically decrease the size of the graph needed. 

Thanks again for your insight and the great work on the library. I will most likely start with a meshed implementation to get up and running as you described.
