### ISSUE TITLE
Renaming edge_attr to edge_weights in utils/loop.py

### ISSUE THREAD

**Issue by ekagra-ranjan** [rusty1s/pytorch_geometric#851]
Hi @rusty1s, 

utils/loop.py has 5 functions out of which 2 have `edge_weight` as a parameter whereas the other 2 have `edge_attr`. Wouldn't it be more convenient if all the functions have same name for similar quantities?

https://github.com/rusty1s/pytorch_geometric/blob/5ed10f00aa432d03a208753f2babb3a10ce48e7a/torch_geometric/utils/loop.py#L20

https://github.com/rusty1s/pytorch_geometric/blob/5ed10f00aa432d03a208753f2babb3a10ce48e7a/torch_geometric/utils/loop.py#L39

https://github.com/rusty1s/pytorch_geometric/blob/5ed10f00aa432d03a208753f2babb3a10ce48e7a/torch_geometric/utils/loop.py#L62

https://github.com/rusty1s/pytorch_geometric/blob/5ed10f00aa432d03a208753f2babb3a10ce48e7a/torch_geometric/utils/loop.py#L96-L97

I think renaming `edge_attr` to `edge_weight` would be more consistent. Please let me know your views on it @rusty1s .

**Comment by rusty1s** [comment]
I think you are totally right that this is a bit confusing. We generally refer to `edge_weight` for one-dimensional edge weights, and `edge_attr` for multi-dimensional edge features. In general, `edge_attr` can be an `edge_weight` but vice versa. So, *e.g.*, `remove_self_loops` works for any multi-dimensional edge features, but, *e.g.*, `add_remaining_self_loops` can only handle one-dimensional edge weights.

**Comment by ekagra-ranjan** [comment]
I wasn't aware of the different meanings of `edge_weight` and `edge_attr`. I was using them interchangeably. I now get your motivation for naming them differently. 

Thanks!
