### ISSUE TITLE
Mac OS Catalina installation error torch-scatter

### ISSUE THREAD

**Issue by dcoukos** [rusty1s/pytorch_geometric#854]
## 📚 Installation

Installation of torch-scatter fails with `AssertionError: Torch not compiled with CUDA enabled`

## Environment

* OS: MacOS Catalina 10.15.1
* Python version: 3.6.9
* PyTorch version: 1.3
* CUDA/cuDNN version: NA
* GCC version: 11.0.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): Yes! Pip & Source
* Any other relevant information:

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [X] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The official extension example runs on my machine.

## Additional context
Although I am running on my macbook with no GPU, I have downloaded CUDA and added the cuda directories to the path variables.
`sudo ln -s /usr/local/cuda/lib /usr/local/cuda/lib64

export PATH=/usr/local/cuda/bin:$PATH
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
export CPATH=/usr/local/cuda/include:$CPATH
`

#### Log
<details>
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torch_scatter.scatter_cuda' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dimitricoukos/opt/anaconda3/envs/geo/include -arch x86_64 -I/Users/dimitricoukos/opt/anaconda3/envs/geo/include -arch x86_64 -I/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include -I/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/TH -I/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/Users/dimitricoukos/opt/anaconda3/envs/geo/include/python3.6m -c cuda/scatter.cpp -o build/temp.macosx-10.7-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cuda/scatter.cpp:18:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(src);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:19:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(index);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:20:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(out);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:26:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(src);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:27:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(index);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:28:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(out);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:34:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(src);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:35:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(index);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:36:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(out);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:37:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(arg);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:43:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(src);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:44:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(index);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:45:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(out);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
cuda/scatter.cpp:46:3: warning: 'type' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a
      drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use
      tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  CHECK_CUDA(arg);
  ^
cuda/scatter.cpp:3:36: note: expanded from macro 'CHECK_CUDA'
#define CHECK_CUDA(x) AT_ASSERTM(x.type().is_cuda(), #x " must be CUDA tensor")
                                   ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:241:3: note: 'type' has been explicitly marked
      deprecated here
  C10_DEPRECATED_MESSAGE("Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement...
  ^
/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/include/c10/util/Deprecated.h:28:44: note: expanded from macro
      'C10_DEPRECATED_MESSAGE'
# define C10_DEPRECATED_MESSAGE(message) [[deprecated(message)]]
                                           ^
14 warnings generated.
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    packages=find_packages(),
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 372, in build_extensions
    build_ext.build_extensions(self)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 288, in unix_wrap_compile
    "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1021, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 320, in get_device_capability
    prop = get_device_properties(device)
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 325, in get_device_properties
    _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch/cuda/__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")

</details>

**Comment by rusty1s** [comment]
`torch-scatter` believes you have CUDA installed since it finds the respective cuda directories, but since you have no GPU the installation fails. Try running `python setup.py install --cpu` to fix this :)

**Comment by dcoukos** [comment]
Thank you!!!
