### ISSUE TITLE
Fresh Install, Cannot import pytorch_geometric

### ISSUE THREAD

**Issue by dcoukos** [rusty1s/pytorch_geometric#855]
## 📚 Installation

Importing pytorch_geometric leads to the following error: 
<details>
ImportError: dlopen(/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so, 2): Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
  Referenced from: /Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so
</details>

## Environment

* OS: OSX Catalina 10.15.1
* Python version: 3.6.9
* PyTorch version: 1.3
* CUDA/cuDNN version: N/A
* GCC version: 11.0.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): source
* Any other relevant information:

## Checklist

- [X] I followed the installation guide.
- [X] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [X] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine. --

> > I'm not sure what this means but python gcn.py crashes with same error.

- [ ] The offical extension example runs on my machine.

## Additional context

Just performed all of the installations below, from source, using the following commands:

```
git clone https://github.com/rusty1s/pytorch_scatter.git && \
    cd ./pytorch_scatter && \
    MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install --cpu
```

```
   cd .. && \
    git clone https://github.com/rusty1s/pytorch_sparse.git && \
    cd ./pytorch_sparse && \
    MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install --cpu
```

```    
cd .. && \
    git clone https://github.com/rusty1s/pytorch_cluster.git && \
    cd ./pytorch_cluster && \
    MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install --cpu
```

```
    cd .. && \
    git clone https://github.com/rusty1s/pytorch_spline_conv.git && \
    cd ./pytorch_spline_conv && \
    MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install --cpu

```
```
    cd .. && \
    git clone https://github.com/rusty1s/pytorch_geometric.git && \
    cd ./pytorch_geometric && \
    MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python setup.py install
```

#### log
<details>
>>> import torch_geometric

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/__init__.py", line 2, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/nn/__init__.py", line 2, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/nn/data_parallel.py", line 5, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/data/__init__.py", line 1, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/data/data.py", line 7, in <module>
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_sparse-0.4.3-py3.6-macosx-10.7-x86_64.egg/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_sparse-0.4.3-py3.6-macosx-10.7-x86_64.egg/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: dlopen(/Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so, 2): Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
  Referenced from: /Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/dimitricoukos/opt/anaconda3/envs/geo/lib/python3.6/site-packages/torch_scatter-1.4.0-py3.6-macosx-10.7-x86_64.egg/torch_scatter/scatter_cpu.cpython-36m-darwin.so
</details>

**Comment by rusty1s** [comment]
This error usually indicates that you have multiple PyTorch versions installed. Can you verify that this is not the case?

**Comment by dcoukos** [comment]
Hi rusty, this is the case, thanks for pointing it out!

I completely cleaned the environment, but I still got the above error after doing the following:
- conda installing python 3.6, jupyter, pytorch
- and then installing all the pytorch_* libraries from above, from source as described in the original issue description.

running `conda list` in my environment shows:
\# Name         |           Version         |          Build | Channel
pytorch         |          1.3.1       |            py3.6_0  |  pytorch

running `pip list` in my environment shows:
Package       |        Version            

torch        |         1.3.1     

(Pipes for clarity)

Furthermore: 
running `pip uninstall torch;  python -c "import torch_geometric"`
leads to `ModuleNotFoundError: No module named 'torch'`
<details>
(geo2) dimitricoukos@MacBook-Pro-di-Dimitri pytorch_geometric % python -c "import torch_geometric"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/nn/__init__.py", line 1, in <module>
    from .meta import MetaLayer
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/nn/meta.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
</details>

If I `conda remove pytorch` and I reinstall torch and torchvision with pip,
I get `AttributeError: module 'torch' has no attribute 'nn'`
<details>
(geo2) dimitricoukos@MacBook-Pro-di-Dimitri pytorch_geometric % python -c "import torch_geometric"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/nn/__init__.py", line 1, in <module>
    from .meta import MetaLayer
  File "/Users/dimitricoukos/pytorch_geometric/torch_geometric/nn/meta.py", line 4, in <module>
    class MetaLayer(torch.nn.Module):
AttributeError: module 'torch' has no attribute 'nn'
</details>

I'm not really sure why there are two pytorch versions to begin with, I thought the pip package (torch) might come from my base env, but my base env has no torch versions.

Any suggestions on how to proceed? Thanks!

**Comment by rusty1s** [comment]
No specific suggestions, but any `torch` related error suggests that there is something wrong with your installation. I would try to
1. Start from a clean conda environment once again
2. Install `torch` via conda
3. Install `torch_scatter`, etc, by removing binaries first:
```
rm -rf build/ && python setup.py install
```

**Comment by dcoukos** [comment]
I realized that torch 1.3.1 and pytorch 1.3.1 are not different versions but just different nomenclatures for cataloguing in pip & conda. I confirmed this by checking both after a fresh environment and only conda installing pytorch. Both appeared after this installation.

I did install pytorch 1.4 from source, but that was in a different environment. 

In addition, the steps above unfortunately did not fix the issue. 

I was wondering if you think this might be due to my combination of OS/gcc/pytorch versions. If so, could you post a combination of the parameters above for which pytorch_geometric is confirmed to work? (It would be best to maintain OSX Catalina)

Thanks!

**Comment by rusty1s** [comment]
PyG works on all versions starting from PyTorch >= 1.2.0. For GCC, the default clang compiler works for installation on macOS with the fix mentioned [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#c-cuda-extensions-on-macos). It definitely works on Linux/Windows/Mac but I do not have a list for which exact compiler versions (this is out of my hand anyway). I believe you also should set to `MACOSX_DEVELOPMENT_TARGET` to `10.9` instead of `10.15`.

Which issue are you talking about? Not finding `torch` or not finding `torch_scatter.cpu`? In the latter case, please provide the installation log of `torch-scatter` so I can see where the error occurs.

**Comment by dcoukos** [comment]
It works!

I think the critical difference was the fix to ccompiler.py you linked above.

After a fresh environment, using python 3.7 instead of 3.6, recloning the repositories, and reinstalling it all works! I went with `MACOSX_DEVELOPMENT_TARGET=10.13`.

Thank you!!
