### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by <$HOME>/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by HYDesmondLiu** [rusty1s/pytorch_geometric#858]
## 📚 Installation

Hi expert,
    I failed to import torch_geometric with error, is there anything I can do to make it work?
I've installed and uninstalled several times and it still fails.

ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by <$HOME>/.conda/envs/hliuPython/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so)

## Environment

* OS: CentOS Linux 7 (Core)
* Python version: Python 3.6.8 :: Anaconda custom (64-bit)
* PyTorch version: torch==1.3.1
torch-cluster==1.4.5
torch-geometric==1.3.2
torch-scatter==1.4.0
torch-sparse==0.4.3
torchvision==0.4.2

* CUDA/cuDNN version: 10.1

* GCC version:  gcc (GCC) 5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):
$ pip install --verbose --no-cache-dir torch-scatter
$ pip install --verbose --no-cache-dir torch-sparse
$ pip install --verbose --no-cache-dir torch-cluster
$ pip install torch-geometric

* Any other relevant information:

I've added these paths in my bash

export PATH=/usr/local/cuda-10.1/bin$PATH
export CPATH=/usr/local/cuda-10.1/include/:$CPATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH

**Comment by rusty1s** [comment]
Have you tried googling your error? For example, [this](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) seems related.

**Comment by HYDesmondLiu** [comment]
Hi rusty1s,
    Thanks a lot, I've solved this problem although it's not related to the link pasted above.

**Comment by humayunzaee** [comment]
@HYDesmondLiu  Can you please share what is the solution. I am also facing the same on Centos

**Comment by yiwc** [comment]
conda create -n pyg python=3.8
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cpuonly -c pytorch
conda install pyg -c pyg
conda install pytorch-cluster -c pyg

this works fine for me
