### ISSUE TITLE
transform: failed to synchronize: cudaerrorillegaladdress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by geekboood** [rusty1s/pytorch_geometric#864]
## ❓ Questions & Help
Hi, I want to train a Node2Vec model on my own dataset. I can use CPU to train without error. But when I try to use GPU to train, it reports this error after several iteration. Do you guys have any idea why this error happens?

**Comment by geekboood** [comment]
Now I can confirm the issue. My dataset has 45034 nodes and 273179 edges, and the node number is from 0 to 45033. When I pass the number 45033 to the model, it will trigger the error `index out of range: Tried to access index 5550641 out of table with 45033 rows`.

**Comment by geekboood** [comment]
Okay, I realized that the problem is beacuse I feed a directed graph to Node2Vec model. After I convert the model to undirected, the problem solved.

**Comment by laihaoran** [comment]
Can you tell me what is directed graph and undirected graph?

**Comment by laihaoran** [comment]
Please you tell me how do you convert the model to undirected. Thanks very much.

**Comment by rusty1s** [comment]
`torch_geometric.utils.to_undirected`.

**Comment by laihaoran** [comment]
Thank you. torch_geometric.utils.to_undirected can convert the graph to undirected. In my data, my undirected graph have been processed like this ,so I don't need to do it again. Do you have any operation to convert your model to undirected. I have facing the same problem like you.
