### ISSUE TITLE
Can  SplineConv be used for output at graph level?

### ISSUE THREAD

**Issue by MarkusRosen** [rusty1s/pytorch_geometric#865]
## ❓ Questions & Help
First let me thank you guys very much for this great library! I have a small question: I have 3 dimensional objects that can be represented as undirected graphs. Each graph has a single output which I try to predict using PyTorch geometric. I adapted the GINConv example for my use case and it does work and produces results, but I would really like to try the SplineConvs for my example.  This is my current network:
```python
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        num_features = 3
        dim = 32

        nn1 = Sequential(Linear(num_features, dim), ReLU(), Linear(dim, dim))
        self.conv1 = GINConv(nn1)
        self.bn1 = torch.nn.BatchNorm1d(dim)

        nn2 = Sequential(Linear(dim, dim), ReLU(), Linear(dim, dim))
        self.conv2 = GINConv(nn2)
        self.bn2 = torch.nn.BatchNorm1d(dim)

        self.fc1 = Linear(dim, dim)
        self.fc2 = Linear(dim, 1)

    def forward(self, x, edge_index, batch):

        x = F.relu(self.conv1(x, edge_index))
        x = self.bn1(x)
        for i in range(1, 7):
            x = F.relu(self.conv2(x, edge_index))
            x = self.bn2(x)

        x = global_add_pool(x, batch)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.fc2(x)
        x = torch.squeeze(x, dim=-1)

        return x
```

Unfortunately I was not able to produce outputs at graph level, only at node level. Is there a way to apply SplineConvs to get ouptuts at graph level?

**Comment by rusty1s** [comment]
You can only use `SplineConv` in conjunction with edge features. Do your graphs contain those?

**Comment by MarkusRosen** [comment]
Yes, each edge contains 3 cartesian coordinates as features.

**Comment by rusty1s** [comment]
Then you should additionally input those as `edge_attr` to the `SplineConv`, *e.g.*:
```python
x = F.relu(self.conv2(x, edge_index, cartesian))
```
Note that `cartesian` needs to be in interval `[0,1]` to work with `SplineConv`.

**Comment by MarkusRosen** [comment]
Thanks for your quick help! With your comment as well as the [data-parallel-example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/data_parallel.py) I was able to get my code running without errors!
