### ISSUE TITLE
issues with installation of torch-scatter

### ISSUE THREAD

**Issue by PandaGuang** [rusty1s/pytorch_geometric#87]
the error is as follows:

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
failed building wheel for torch scatter

same issue when trying to install other three.

**Comment by Barnonewdm** [comment]
I meet the same issue.

**Comment by ayhyap** [comment]
I got a similar problem (if not the same problem). 
I'm not very familiar with installing things in general, but I did get a lot of warnings (and eventually errors) during installation using pip.

I logged them and  pasted them here: https://pastebin.com/HijkBwrP, hopefully this helps.

**Comment by benediktwagner** [comment]
I've got the same issue on linux.

**Comment by rusty1s** [comment]
Closed in favour of https://github.com/rusty1s/pytorch_geometric/issues/77

**Comment by ayhyap** [comment]
I solved my problem, though it probably only applies for Windows.

My problem came from a version check in a header file in NVIDIA CUDA, the version of VS I had installed was too new.

Following the instructions from...
https://devtalk.nvidia.com/default/topic/1035535/cuda-setup-and-installation/cuda-9-2-does-not-work-with-visual-studio-2017-15-7-1/3

I just removed the version check and it compiled fine.

**Comment by Mario-Liu** [comment]
> 
> 
> I solved my problem, though it probably only applies for Windows.
> 
> My problem came from a version check in a header file in NVIDIA CUDA, the version of VS I had installed was too new.
> 
> Following the instructions from...
> https://devtalk.nvidia.com/default/topic/1035535/cuda-setup-and-installation/cuda-9-2-does-not-work-with-visual-studio-2017-15-7-1/3
> 
> I just removed the version check and it compiled fine.

could you please show us the details about  VS version, PYtorch version, Cuda version and so on?
much thanks!

**Comment by ayhyap** [comment]
> could you please show us the details about VS version, PYtorch version, Cuda version and so on?
> much thanks!

My system was a bit outdated compared to what you mentioned in your thread, but anyway:
Win10
Python 3.6
PyTorch 1.0.0
Cuda 9.0
Microsoft Visual Studio Community 2017 Version 15.9.9
gcc 5.4.0 (MinGW-W64)

(honestly i'm not sure how to check VS version, so I assume that's the one)

**Comment by JeremyLinky** [comment]
Did anyone install the cpu version and meet the same question?
