### ISSUE TITLE
Graph Autoencoder

### ISSUE THREAD

**Issue by iam-armanahmed** [rusty1s/pytorch_geometric#874]
## ERROR:  implementing the below model but getting an error 

I am trying to implement the below architechture 
`
class Net(torch.nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(3, 16)
        self.conv2 = GCNConv(16, 3)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = self.conv2(x, edge_index)
        return x
`

device = 'cuda'
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters())

epochs = 150

for e in range(epochs):
    running_loss = 0
    accuracy = 0    
    for data in loader:        
        data = data.to(device)        
        optimizer.zero_grad()        
        out = model(data)           
        loss = F.mse_loss(data.x, data.x)
##### GETTING ERROR on below line  (IMAGE ATTACHED)
        **loss.backward()**       
#####       ERROR ->>>  **RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn**

![image](https://user-images.githubusercontent.com/33535723/71449500-58b69500-2702-11ea-9523-0705890899a1.png)

**Comment by rusty1s** [comment]
You need to compute mse based on out and data.y.

**Comment by iam-armanahmed** [comment]
Oh!! Missed it thanks @rusty1s
