### ISSUE TITLE
GCNConv

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#878]
```
    def forward(self, x, edge_index, edge_weight=None):
        """"""
        x = torch.matmul(x, self.weight)

        if self.cached and self.cached_result is not None:
            if edge_index.size(1) != self.cached_num_edges:
                raise RuntimeError(
                    'Cached {} number of edges, but found {}. Please '
                    'disable the caching behavior of this layer by removing '
                    'the `cached=True` argument in its constructor.'.format(
                        self.cached_num_edges, edge_index.size(1)))
```
I wonder if it is necessary to change this part of the code. Normally, `self.cached_num_edges` > `edge_index.size(1)` since `self.cached_num_edges` adds selfloops to the `edge_index`. Perhaps you can save the original number of edges from `edge_index.size(1)` to `self.cached_num_edges` rather than the one including selfloops.

**Comment by rusty1s** [comment]
Hi,

We do already save the original number of edges from `edge_index` to `cached_num_edges`, so I see no problem here. Am I misunderstanding something?

**Comment by sw-gong** [comment]
my mistake
