### ISSUE TITLE
Best way to concatenate two datasets

### ISSUE THREAD

**Issue by RobinFrcd** [rusty1s/pytorch_geometric#88]
Hi,
I've created to DataSets based on `InMemoryDataset` and I'd like to know what's the best way to concatenate them.

```python
print(dataset_1.slices['x'].shape)
print(dataset_2.slices['x'].shape)
>> torch.Size([1001])
>> torch.Size([5001])

dataset3_data, dataset3_slices = \
    rex_dataset.RexDataset.collate(None, [dataset_1.data, dataset_1.data])

print(dataset3_slices['x'].shape)
>> torch.Size([3])
```

I don't think collate is the right function to use here. I guess I could concatenate everything with a torch.cat but is there a function somewhere in the package to do that ?

Thanks,

**Comment by rusty1s** [comment]
Good question! Currently there is no method which provides such functionality.
What you can do is the following:
```python
data_list_1 = [data for data in dataset_1]
data_list_2 = [data for data in dataset_2]
data, slices = dataset.collate(data_list_1 + data_list_2)
```

**Comment by RobinFrcd** [comment]
Perfect, thank you very much!
