### ISSUE TITLE
apply transform on DynamicFAUST dataset

### ISSUE THREAD

**Issue by yairkit** [rusty1s/pytorch_geometric#889]
when run the following code for:

`dataset = DynamicFAUST(root=d_faust_path, subjects=subjects, categories=categories, transform=T.RandomShear(0.07))`

`dataset[0]`

I get:

> AssertionError: Node position matrix and transformation matrix have incompatible shape.

this is due to the fact that
**transform()** expect **data['pos']** to be of shape **[num_of_ponts, dim]**
but **DynamicFaust** returns **data['pos']** of shape **[num_of_frames, num_of_ponts, dim]**

is there another built-in way to use augmentations transform for this dataset?

Thanks!

**Comment by rusty1s** [comment]
Thanks! We should definitely support broadcasting here. I will work on it, but feel free to open a PR if you like. In the meantime, you can implement your own transform to achieve this :)

**Comment by yairkit** [comment]
Thanks!
I would love to have your official implementation once it's ready.
(in the meanwhile I am editing it myself :))

**Comment by rusty1s** [comment]
Should be fixed in master :)
