### ISSUE TITLE
More torch-scatter issues

### ISSUE THREAD

**Issue by nmank** [rusty1s/pytorch_geometric#89]
I'm running Mac OS without coda. I ran 

pip3 install torch torchvision

then

pip install --upgrade torch-scatter

and had this error:

  /anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef' file not found
  #include <cstddef>
           ^~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for torch-scatter

**Comment by rusty1s** [comment]
Have you tried [this](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#c-cuda-extensions-on-macos)?

**Comment by jiangjiawen** [comment]
you can try export MACOSX_DEPLOYMENT_TARGET=10.9，according to [this](https://github.com/thoughtbot/capybara-webkit/issues/1071)

**Comment by rusty1s** [comment]
Closed due to inactivity. Feel free to reopen.
