### ISSUE TITLE
Different Splits for Cross-Validation

### ISSUE THREAD

**Issue by Kqiii** [rusty1s/pytorch_geometric#894]
## ❓ Questions & Help
Hi,

Could you please tell me how to conduct cross-validation with different splits?

I noticed in [the GCN paper](https://openreview.net/pdf?id=SJU4ayYgl) that the authors conducted a 5-fold cross-validation experiment with 5 different train/test split.

However, the train/validation/test split provided by Pytorch_Geometric seems to be fixed. So do we need to split the datasets manually if we want to conduct the cross-validation, or can this be simply achieved by Pytorch_Geometric? 

If we need to manually achieve this, could you please tell me how the datasets should be split? I did not find any detail in the paper, eg. how many train/test points in total, how many train/test points per category, etc.

Thank you very much!

**Comment by rusty1s** [comment]
Creating random splits needs to be done manually, but this is [really trivial](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/citation/train_eval.py#L19-L40):
```python
perm = torch.randperm(data.num_nodes)
train_idx = perm[:140]
mask = torch.zeros(data.num_nodes, dtype=torch.bool)
mask[train_idx] = 1
```
I do not know which split ratio the authors are using though.

**Comment by Kqiii** [comment]
@rusty1s Thank you very much!
