### ISSUE TITLE
Is there any support for sparse input?

### ISSUE THREAD

**Issue by sqlkrad** [rusty1s/pytorch_geometric#899]
## ❓ Questions & Help

I saw there is only input_channel parameter for GCNConv. Is there any support for sparse input?

**Comment by rusty1s** [comment]
`GNCConv` works with sparse input node feature matrices :)

**Comment by sqlkrad** [comment]
Sorry, do you mean **GCNConv**? But I can't see the support of sparse feature from the source code https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py

**Comment by rusty1s** [comment]
Yes, `torch.matmul` works for both dense and sparse input features.

**Comment by sqlkrad** [comment]
wow, thanks!
