### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by kenyonke** [rusty1s/pytorch_geometric#9]
When I try to install torch-scatter, it always comes with this problem.
I tried 'pip install --upgrade setuptools', but it doesn't work. 
Anyone can help me fix this problem???  Thanks a lot!
![image](https://user-images.githubusercontent.com/34250873/41678141-31459118-74c2-11e8-9401-e5bef77081e3.png)

**Comment by rusty1s** [comment]
Hello Lee,

PyTorch Geometric (and the old PyTorch FFI interface) currently do not support Windows. We are actually calling a bash script to compile the CUDA kernel in the installation script and there may be some path issues. This should be fixed if all dependencies are updated to the new extension API (e.g. `torch-unique` should install fine).

I do not own a Windows machine by myself, so currently I can't help you, I'm really sorry!

**Comment by kenyonke** [comment]
Got it and thank you for your reply! Looking forward to your better PyTorch.
