### ISSUE TITLE
Sparse concat

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_geometric#903]
Hi,
I would like to ask if at this moment there is implemented any method to do a "sparse concat". What I'm trying to do is something like this:

Imagine that I have the following tensors x and ind:

x_1=[0,1,2,3,5]
x_2=[6,7,8, 9]

ind_1=[3, 2, 0, 1,4]
ind_2=[2, 1, 0, 3]

My expected result would be this one:
res = [[2, 8], [3, 7], [1,6], [0,9],[5]]

I was wondering if is this functionality already implemented. I checked the pytorch_geometric documentation and pytorch_scatter and I didn't find anything, but I would like to be sure before that I implement my own method.

Thanks

**Comment by rusty1s** [comment]
I am not sure I understand your example. Are `x_*` values of a 1-d sparse vector with indices `ind_*`?

**Comment by dhorka** [comment]
`x_*` are values of a 1-d sparse vector yes, but `ind_*` are the indices where I want to put the values of x_*. In fact I thing the easy solution of this problem is this one:

```
res = torch.ones(5,2)

res[ind_1, 0] = x_1
res[ind_2, 1] = x_2
```

However, I'm not sure if this is backpropagating properly, for this reason I asked if there is any implementation of this "sparse concat".

**Comment by rusty1s** [comment]
Ok, I see. Your implementation is the best solution to this problem, and it supports backpropagation too :)

**Comment by dhorka** [comment]
Thanks!
