### ISSUE TITLE
Add documentation option for latest release

### ISSUE THREAD

**Issue by arkanum** [rusty1s/pytorch_geometric#904]
## 🚀 Feature

Allow docs to select any release version, not just latest and 1.3.0

## Motivation

The _latest_ docs don't reflect the state of the latest release (1.3.2) and are ahead of the version listed on PyPi and in the releases tab.

## Additional context

For example in the latest version of the code (current main branch HEAD) dataset.raw_dir is a property, but in release 1.3.2 it is a class variable.
So, if you follow the _latest_ docs/tutorial, your custom dataset will throw an error.

**Comment by rusty1s** [comment]
Docs for 1.3.2 and 1.3.1 are building :) Can you show me the snippet that throws an error? I can not find it.

**Comment by arkanum** [comment]
Its not a snipped from the docs, that throws the error.

I attempted to overload the raw_dir property as seen [here](https://github.com/rusty1s/pytorch_geometric/blob/75f23d5304cef26f844f14e0bbdd7d011d8980bf/torch_geometric/data/dataset.py#L105) but the version you download from PyPi has raw_dir defined [here](https://github.com/rusty1s/pytorch_geometric/blob/881d5ba2aefc26328eeeaa17fd7ef6daaae06ef4/torch_geometric/data/dataset.py#L81)

Which means when you call super __init__() you get an error.

Does that help explain the problem I was having?

I'm going to close this issue if thats okay, because you've resolved the main issue :)

**Comment by rusty1s** [comment]
We can also add the setter method back to `raw_dir` :)

**Comment by arkanum** [comment]
Yeah, that would also be nice, but its fine as it is in HEAD.
If you need to change raw_dir, you can just overload the property definition.
