### ISSUE TITLE
Question about architecture decision used in `enzymes_diff_pool.py`

### ISSUE THREAD

**Issue by tjiagoM** [rusty1s/pytorch_geometric#908]
## ❓ Questions & Help

Hi!

I'm a bit stuck in the architecture used in the example file `enzymes_diff_pool.py`, and have a question about it. I hope you can help me!

In specific, I'm a bit confused with the `forward()` pass in the `GNN` class. In your implementation you are running 3 `GraphSAGE`s, but instead of returning the last `x3`, you return a concatenation of the 3 separate runs of `GraphSAGE`s to have the final feature representation of those nodes. This looks to me as some sort of residual or jumping connections, but I am not finding it in the original paper. Why did you do this, then? 

Sorry if I am misunderstanding something in the original paper or in your implementation.

"P.S.:" You probably can also remove the line `batch_size, num_nodes, in_channels = x.size()` as this is done in the bn() function?

Once again, thank you so much for this amazing tool and your support!

**Comment by rusty1s** [comment]
This is not mentioned in the paper, but you can find it in the official repo: https://github.com/RexYing/diffpool/blob/master/encoders.py#L144

**Comment by tjiagoM** [comment]
Ah, I see, thanks for the clarification!
