### ISSUE TITLE
Batch Size = Num Graph Nodes vs Batch Size = Num Graphs?

### ISSUE THREAD

**Issue by aligholami** [rusty1s/pytorch_geometric#921]
I wonder why you have chosen the interpretation of batch size to be the total number of nodes in all graphs? For example, In a batch I might have 128 graphs, and each of these graphs corresponds to an image (which makes 128 images in this case). Assuming there can be a different number of nodes per image for example (object region features per image as nodes), wouldn't it be better to interpret the batch size as the number of graphs instead of number of graph nodes?

**Comment by rusty1s** [comment]
I am not sure I understand. The batch size corresponds to the number of graphs, it is just that we combine the batch dimension and the node dimension into a single dimension to allow the batching of arbitrarily sized graphs.

**Comment by aligholami** [comment]
If we combine those dimensions, then how do we distinguish which nodes are in which graph?

**Comment by rusty1s** [comment]
Via the `batch` vector which holds the example idx for each node.

**Comment by aligholami** [comment]
Got it, thanks!
