### ISSUE TITLE
Run on different GPU types with same install?

### ISSUE THREAD

**Issue by jaredsagendorf** [rusty1s/pytorch_geometric#922]
Hi, I am working on a cluster which has several types of GPUs (k20, k40, p100 and v100).

I installed all the packages on a p100 node, and everything works great on p100s. However, when trying to use other nodes I get the error:

RuntimeError: CUDA error: no kernel image is available for execution on the device

I was wondering if it's possible to install the package in a way that it can run on multiple GPU types? If not then I suppose I can set up a different conda environment for each GPU type and switch environments depending on what GPU is available.

**Comment by rusty1s** [comment]
Interesting question. I believe that using different conda environments is a good workaround. Eventually, you can fix it by setting fixed compute capabilities via
```
export TORCH_CUDA_ARCH_LIST=6.1
```

**Comment by fdiehl** [comment]
I recently faced this issue when building a singularity image to both run on my laptop and a separate computation server. As @rusty1s mentioned, simply doing an

```
export TORCH_CUDA_ARCH_LIST="5.0 6.1"
```
before compiling and installing `pytorch-scatter`, `pytorch-sparse`, etc worked well. You can find the compute capability by using the `deviceQuery` script with CUDA, for example running

``` 
/usr/local/cuda-10.1/extras/demo_suite/deviceQuery | grep 'CUDA Capability'
```

**Comment by jaredsagendorf** [comment]
Great to know, thanks!
