### ISSUE TITLE
Send global attributes on every nodes (≈ inverse of scatter_)

### ISSUE THREAD

**Issue by cvignac** [rusty1s/pytorch_geometric#925]
## 🚀 Feature

Hello, is there currently an inverse operation of scatter_? I mean a function that sends a global attribute of the graph on every node. Given two graphs with N1 and N2 nodes, it would be something that maps a tensor of shape (2, F) to a tensor of shape (N1 x N2, F).

## Motivation
One use case would be the following: 
- Use one layer of message-passing
- Perform mean_global_pooling and send this information to every node
- Process this value and use new layers of message passing

## Additional context
It seems that one way to do it would be to create a new batch object, but it seems quite inefficient. We have already access to data.edge_index and data.batch, it would be much better if we did not have to create new ones.

Sorry if such a function already exists, but I could not find it in the docs. Thanks!

Clément

**Comment by rusty1s** [comment]
The inverse of `scatter` is the `gather` operation. Implementing your idea is straightforward:
```python
x = conv(x, edge_index) # Compute node embeddings
x_global = global_mean_pool(x, batch) # Perform global pooling
x = torch.cat([x, x[batch]], dim=-1) # Lift it to node features
```

**Comment by cvignac** [comment]
Thank you. Why do we need the cat? Is `x = x_global[batch]` not enough?

**Comment by rusty1s** [comment]
There is no need for the `cat`. It's just that if you want to continue with message passing, you need to re-inject the local information :)

**Comment by cvignac** [comment]
Perfect.
