### ISSUE TITLE
DataListLoader and per-epoch transforms.

### ISSUE THREAD

**Issue by dcoukos** [rusty1s/pytorch_geometric#928]
## ❓ Questions & Help

Hello, 
First of all thank you for the work on this amazing library.
I am training a model on multiple GPUs for surface classification on polygon files. I would like to apply the RandomRotation transform every epoch on the training data. I have been concatenating my node features with my position and normals like so:

```
x = torch.stack((x, pos, norm), dim=1)
x = x.reshape(-1, 9)
data = Data(x=x, pos=pos, face=face, norm=norm, y=y)
```

The rotation transform, however modifies only the positional data and the norms, so I have to update the training features manually, perhaps with some code like the one below: 

```
for epoch in range(1, epochs+1):
    # rotate the structures between epochs

    remove_positional_data_from_features(train_loader)
    rotator = RandomRotate(90)
    train_loader = [rotator(data) for data in train_loader]
    add_positional_data_to_features(train_loader)
```

Is there a way to do load and modify the training features or apply a transform on the training data without iterating through the training DataListLoader?

Thanks!

**Comment by rusty1s** [comment]
What's preventing you from using regular transforms? You can even change the transform on every epoch:
```python
for epoch in range(epochs):
    dataset.transform = T.Compose([..., RandomRotate(90, ...])
    loader = DataLoader(dataset, ...)
    for data in loader:
        ...
```

**Comment by dcoukos** [comment]
Thanks for the tip! Although it makes perfect sense now, I had not thought of initializing the Dataloader inside the epoch loop
