### ISSUE TITLE
Mixing graph and non-graph data in a dataset

### ISSUE THREAD

**Issue by THinnerichs** [rusty1s/pytorch_geometric#929]
## ❓ Questions & Help

I am currently trying to predict interactions of two different kinds of entities, one of them represented as nodes in a large graph, the other represented by a plain feature vector. 
However, I am struggling to build a proper dataset for this problem, as the geometric ```DataLoader``` expects the whole input to be a single ```Data``` object, and the plain torch loader obviously cannot handle the graph object.

Any sort of help is highly welcome as I also cannot find any help within the doumentation.

**Comment by rusty1s** [comment]
You can just add your global feature vector to the `Data` object, *e.g.*:
```python
data.global_features = torch.tensor(...) # Shape [1, num_features].
```
This way PyG batching will produce a tensor of shape `[batch_size, num_features]`.

**Comment by THinnerichs** [comment]
It is not mandatory for this feature to be 1D, right?
I would highly appreciate this being added to the documentation under the point of "Build your own Dataset", as its both quite simple and very helpful.

**Comment by rusty1s** [comment]
No, it does not need to be one-dimensional. Will try to add it to the docs :)

**Comment by THinnerichs** [comment]
Thanks a lot for the quick reply!
