### ISSUE TITLE
Handle datasets with many small graphs

### ISSUE THREAD

**Issue by RobinFrcd** [rusty1s/pytorch_geometric#93]
Hi,
I've created my first dataset based on `InMemoryDataset` it works pretty well and working with it is really smooth. 

More recently, I've added many more examples and features to my dataset it doesn't fit in RAM anymore. I've created another class based on [Dataset](https://rusty1s.github.io/pytorch_geometric/build/html/notes/create_dataset.html#creating-larger-datasets) but I now have more than 500K+ tiny files (~15ko each) in my dataset folder. But now, when I try to load them it's much slower (even with 8 dataloader workers), I guess my HDD is can't handle this I/O rate. 

How do you handle such kind of datasets ? Is there a simple/clean solution to save let's say 100 or 1000 graphs inside a single file in order to limit the total amount of tiny files ?

Thanks,

**Comment by rusty1s** [comment]
Interesting question! In fact, PyTorch datasets are quite limited for this special case :(
I think your proposed solution is the way to go, but we currently do not have a clean solution.
However, I hope this snippet helps you (untested/pseudo code):

```python
def process(self):
    data_list = []
    for i in range(num_graph):
        ...
        data_list.append(data)
        if i % 99 == 0:
             torch.save((self.collate(data_list), 'path_{}'.format(i // 100)
             data_list = []

def get(self, idx):
       self.data, self.slice = torch.load('path_{}'.format(idx // 100)
       return super(MyDataset, self).get(idx % 99)
```

Let me know if this fastens up things.

**Comment by RobinFrcd** [comment]
Alright, thanks for your help!
I'm trying to rewrite this to save files of size=`batch_size` on my disk. I'll then use a data loader with `batch_size=1` to be able to use PyTorch data loaders features like queues and multi workers (don't if multi workers are useful with a bach_size=1 tho), hope this I'll help! 

I'll keep you in touch!

**Comment by rusty1s** [comment]
Actually, you can use batch sizes greater than `1`. You simply need to unite the `mini_batch` vector from the data objects with the `batch` vector generated from the dataloader, e.g.,

```python
forward(self, data):
    batch = data.batch * data.mini_batch.max() + data.mini_batch
```

**Comment by RobinFrcd** [comment]
I'm now storing my data set as batches, it's now ~10 times faster than before. So it was definitely worth it, thanks!

**Comment by tformal** [comment]
Facing related issues, I followed the same recipe and I confirm it's definitely worth it ! 

But if I am not mistaken, to unite the `mini_batch` vector from the data objects with the `batch` vector from the dataloader, you actually need to ? 

```python
forward(self, data):
    batch = data.batch * (data.mini_batch.max() + 1) + data.mini_batch
```

**Comment by rusty1s** [comment]
Yes, thank you :)
