### ISSUE TITLE
The docker images of pytorch_geometric

### ISSUE THREAD

**Issue by shengwenLeong** [rusty1s/pytorch_geometric#94]
Hi,
   I have established the docker images of pytorch_geometric. The image contains this project and supports NVIDIA GPU with cuda-9.0. 

The link is:
docker pull shengwenliang/pytorch_graph

**Comment by rusty1s** [comment]
Excellent! But I can not find [it](https://hub.docker.com/search?q=pytorch_graph&type=image).

**Comment by shengwenLeong** [comment]
Hi, I have modified my repository to enable docker hub to find it via searching. Now you can find my repository and test it. If has any problems, please free contact to me. Thanks.

The link is [pytorch_graph](https://hub.docker.com/r/shengwenliang/pytorch_graph)

**Comment by rusty1s** [comment]
Excellent, I will link it in the README. Thanks!
