### ISSUE TITLE
Different input feature lengths

### ISSUE THREAD

**Issue by legohyl** [rusty1s/pytorch_geometric#944]
## ❓ Questions & Help

hi, i'm trying to create a model that takes in 2 different types of features, both of which have different feature lengths. additionally, it's a bipartite graph, so the neighbors of one would be of the other feature type. effectively, i'd like to learn an embedding (ie. put a dense layer ontop of each feature) and propagate the messages through something already pre-defined like GCN. any suggestion on how to do this?

**Comment by legohyl** [comment]
![image](https://user-images.githubusercontent.com/16208802/73898827-8aa44500-48c5-11ea-9612-8f8d10bcff9a.png)

perhaps the above image would help. features of nodes in U (blue nodes) have a length of [1, 933], while in V (green nodes) they have a length of [1,950]. my original idea would be to pass the features first through their own dense layers to get a transformed output of maybe [1, 512], stack these together, recompute their edge_index (as they now are in one matrix), then pass them through like a normal GCN

**Comment by rusty1s** [comment]
Your solution sounds good to me. If you only want to exchange messages in one direction, you can encode your bipartite graph as an assignment matrix in `edge_index` and make use of directional message passing, *e.g.*:
```python
edge_index = ... # Encodes an assignment matrix of dense shape [N_blue, N_green]
x_blue = torch.randn(N_blue, 933)
x_green = torch.randn(N_green, 950)
x_blue = self.lin1(x_blue) # Map node features to same dimensionality
x_green = self.lin2(x_green)
conv1 = SAGEConv(512, 512, normalize=False)
out = conv1((x_blue, x_green), edge_index, size=(N_blue, N_green))
# out now has shape [N_green, 512]
```

**Comment by legohyl** [comment]
Ah, that's interesting. I was wondering how to get all the data points working with the DataLoader class, as I thought the edge index should be given by [2, num_edges] in shape. Additionally, I have 2 separate data frames for x here (x_blue and x_green). When you talk about directional message passing, does that mean my edges can't be undirected edges?

**Comment by rusty1s** [comment]
They can be undirected, but overall, PyG only knows about directed graphs. That's why for undirected edges, we need to hold both directions in `edge_index`.

**Comment by legohyl** [comment]
I see. Would the `to_undirected` function help with that then? I guess it takes an `edge_index` and converts it to twice the length such that it looks like there's 2 way?

**Comment by rusty1s** [comment]
Yes, the `to_undirected` method is meant for this :)

**Comment by legohyl** [comment]
I see alright. So i guess when I construct the Data object, I'd have something like `x= [N_blue, feat_len1], edge_index=[N_blue, N_green], x2=[N_green, feat_len2]` ?

**Comment by rusty1s** [comment]
Well, no :) your `edge_index` is still `[2, num_edges]`, it just encodes dense matrix of shape `[N_blue, N_green]`. You either need to convert it to shape `[N_blue + N_green, N_blue + N_green]` as you suggested, or need to pass messages twice, from blue to green and from green to blue.

**Comment by legohyl** [comment]
Ah okay, I sort of get it. Basically, we can create an edge index of size `[2, N_blue+N_green]`, and use that to index the `X` matrix. However, I'm a bit confused on how to stack the `X_blue` and `X_green` together, as the node feature length is different.

**Comment by rusty1s** [comment]
You need to transform them to the same node feature length via separate MLPs.

**Comment by legohyl** [comment]
Yup, I understand that part. But will the `Data` object accept that? From my understanding, `Dataset` class constructs a data set whereby we pass in a list of `Data` objects. These objects should have things like the node features and the edge_index. These `Data` objects are also what we can use to create mini-batches. Hence, I was wondering how to batch `X_blue` and `X_green` such that during the training phase, I can map them via separate MLPs, stack them back, then pass into the GNN.

**Comment by rusty1s** [comment]
They get concatenated independently, hence, there is no mismatch in shapes. So if you initialize your data as `Data(x_blue=..., x_green, edge_index=...)` everything should work as expected. However, you need to ensure that `edge_index` gets increased as expected in a mini-batch scenario. You want `edge_index[0]` to be increased by the number of nodes in `x_blue`, and `edge_index[1]` to be increased by the number of nodes in `x_green`. This is best achieved by overriding the `__inc__` method in the `Data` class:
```python
class MyBipartiteData(Data):
    def __inc__(self, key, value):
        if key == 'edge_index`
            return torch.tensor([self.x_blue.size(0), self.x_green.size(0)])
        return 0

**Comment by legohyl** [comment]
Hmm ok! This sounds like a good idea. Thanks for all the follow-ups! I'll reach out if I need more help.
