### ISSUE TITLE
PointNet++ size mismatch error

### ISSUE THREAD

**Issue by schakrab** [rusty1s/pytorch_geometric#949]
Hi,

I am running pointnet2_segmentation.py (I haven't changed the code at all) and get the following error in the very first layer when the fully connected operation is applied:

`RuntimeError: size mismatch, m1: [398902 x 3], m2: [6 x 64] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:273`

Is the first linear layer supposed to take concatenated point locations as input? I believe in the original implementation the first layer had 3 input channels, but I may be wrong. 

Appreciate the help!

**Comment by tchaton** [comment]
You might be running the code on shapenet with normals. You can change the input and add +3 to make it work.

Best,
T.C

**Comment by schakrab** [comment]
I changed the input dimension of the first layer to 3 and it seems to work.
