### ISSUE TITLE
can't install torch-scatter and torch-sparse

### ISSUE THREAD

**Issue by xlfzjmm** [rusty1s/pytorch_geometric#954]
## 📚 Installation

I plan to upgrade the PyTorch Geometric to 1.4.1. However, when upgrading torch-scatter (2.0.2) and torch-sparse (0.5.0), I find that 
______
line 47, sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
^
SyntaxError: invalid syntax
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
________

I can install torch-cluster and torch-spline-conv.

## Environment

* OS: ubuntu 16.04
* Python version: 3.5
* PyTorch version: 1.4.0 + cu100
* CUDA/cuDNN version: cuda 10.0
* GCC version: 5.4
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information: none

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I have cloned the repository and tried a manual installation from source.
- [x] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9cp1g2ln/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9cp1g2ln/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9cp1g2ln/torch-scatter/pip-egg-info
         cwd: /tmp/pip-install-9cp1g2ln/torch-scatter/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9cp1g2ln/torch-scatter/setup.py", line 47
        sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
                                                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ucasiggcas** [comment]
how to deal with the problem ,dear
could you pls help me ?
thx

**Comment by rusty1s** [comment]
You need to upgrade to Python 3.6 since we are making use of f-strings.
