### ISSUE TITLE
Windows: No file or directory cl.exe

### ISSUE THREAD

**Issue by Professoroo** [rusty1s/pytorch_geometric#955]
(base) C:\WINDOWS\system32>pip install --verbose --no-cache-dir torch-scatter
Created temporary directory: C:\Users\user\AppData\Local\Temp\pip-ephem-wheel-
cache-ngmmj5o1
Created temporary directory: C:\Users\user\AppData\Local\Temp\pip-req-tracker-
9x2esplb
Created requirements tracker 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-t
racker-9x2esplb'
Created temporary directory: C:\Users\user\AppData\Local\Temp\pip-install-52vk
92ny
Collecting torch-scatter
  1 location(s) to search for versions of torch-scatter:
  * https://pypi.org/simple/torch-scatter/
  Getting page https://pypi.org/simple/torch-scatter/
  Found index url https://pypi.org/simple
  Getting credentials from keyring for https://pypi.org/simple
  Getting credentials from keyring for pypi.org
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/torch-scatter/ HTTP/1.1" 200 1373
  Analyzing links from page https://pypi.org/simple/torch-scatter/
    Found link https://files.pythonhosted.org/packages/29/96/566ac314e796d4b0720
9a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e
5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.
org/simple/torch-scatter/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/6a/b0/ecffacddf573c147c70
c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda
794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.
org/simple/torch-scatter/), version: 1.0.2
    Found link https://files.pythonhosted.org/packages/08/09/07b106f3e74246f4ecf
6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626
993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.
org/simple/torch-scatter/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/2d/70/df2bc259d9606f00854
ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec00
4d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.
org/simple/torch-scatter/), version: 1.0.4
    Found link https://files.pythonhosted.org/packages/2f/97/c50a6aeaedc6924180c
6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534
cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.
org/simple/torch-scatter/), version: 1.1.0
    Found link https://files.pythonhosted.org/packages/91/5f/eb1d3ef3810cb116585
9d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7
f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.
org/simple/torch-scatter/), version: 1.1.1
    Found link https://files.pythonhosted.org/packages/d4/83/67eeea00c2db1959e2f
f95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c
2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.
org/simple/torch-scatter/), version: 1.1.2
    Found link https://files.pythonhosted.org/packages/07/c0/f7ac424496f4a3bcb31
aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a02
59105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.
org/simple/torch-scatter/), version: 1.2.0
    Found link https://files.pythonhosted.org/packages/24/b7/680c3b392a4b55a0ebf
b480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d
561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.
org/simple/torch-scatter/), version: 1.3.0
    Found link https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d
05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cb
ad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.
org/simple/torch-scatter/), version: 1.3.1
    Found link https://files.pythonhosted.org/packages/30/d9/1d5fd4d183dabd9e0a1
f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz#sha256=890e
8f9da2d57431912182960b71bf6c56397de42c2464907a6e9c583164bf06 (from https://pypi.
org/simple/torch-scatter/), version: 1.3.2
    Found link https://files.pythonhosted.org/packages/b8/c3/8bad887ffa55c86f120
ef5ae252dc0e357b3bd956d9fbf45242bacc46290/torch_scatter-1.4.0.tar.gz#sha256=5999
ef256154e5a99445118c1a53f95cf0f95ef7b5cd8d3b256101125479cc2e (from https://pypi.
org/simple/torch-scatter/), version: 1.4.0
    Found link https://files.pythonhosted.org/packages/28/f7/fa4e61587169924203a
32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz#sha256=49d3
059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 (from https://pypi.
org/simple/torch-scatter/), version: 2.0.2
  Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  Given no hashes to check 13 links for project 'torch-scatter': discarding no c
andidates
  Using version 2.0.2 (newest of versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.
1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2)
  Created temporary directory: C:\Users\user\AppData\Local\Temp\pip-unpack-jir
ugdmm
  Getting credentials from keyring for files.pythonhosted.org
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/28/f7/fa4e61587169924203a324
16f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz HTTP/1.1" 200
22431
  Downloading https://files.pythonhosted.org/packages/28/f7/fa4e61587169924203a3
2416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/28/f7/fa4e6158716
9924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz#sha
256=49d3059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 (from https
://pypi.org/simple/torch-scatter/)
  Added torch-scatter from https://files.pythonhosted.org/packages/28/f7/fa4e615
87169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz
#sha256=49d3059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 to buil
d tracker 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-tracker-9x2esplb'
    Running setup.py (path:C:\Users\user\AppData\Local\Temp\pip-install-52vk92
ny\torch-scatter\setup.py) egg_info for package torch-scatter
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info\torch_scatter.egg-info
    writing pip-egg-info\torch_scatter.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\torch_scatter.egg-info\dependency_l
inks.txt
    writing top-level names to pip-egg-info\torch_scatter.egg-info\top_level.txt

    writing manifest file 'pip-egg-info\torch_scatter.egg-info\SOURCES.txt'
    reading manifest file 'pip-egg-info\torch_scatter.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\torch_scatter.egg-info\SOURCES.txt'
  Source in c:\users\user\appdata\local\temp\pip-install-52vk92ny\torch-scatte
r has version 2.0.2, which satisfies requirement torch-scatter from https://file
s.pythonhosted.org/packages/28/f7/fa4e61587169924203a32416f7835939fdd79994eaa429
b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz#sha256=49d3059b7be93d3f2c328fdc6daa3a8
479e3dc4a50c8247aef913177122db671
  Removed torch-scatter from https://files.pythonhosted.org/packages/28/f7/fa4e6
1587169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.
gz#sha256=49d3059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 from
build tracker 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-tracker-9x2esplb
'
Building wheels for collected packages: torch-scatter
  Created temporary directory: C:\Users\user\AppData\Local\Temp\pip-wheel-ilyg
ru5u
  Building wheel for torch-scatter (setup.py) ...   Destination directory: C:\Us
ers\user\AppData\Local\Temp\pip-wheel-ilygru5u
  Running command 'C:\Users\user\Anaconda3\python.exe' -u -c 'import sys, setu
ptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pi
p-install-52vk92ny\\torch-scatter\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ismai
l\\AppData\\Local\\Temp\\pip-install-52vk92ny\\torch-scatter\\setup.py'"'"';f=ge
tattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdi
st_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-ilygru5u' --python-tag
 cp37
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\test
  copying test\test_broadcasting.py -> build\lib.win-amd64-3.7\test
  copying test\test_gather.py -> build\lib.win-amd64-3.7\test
  copying test\test_multi_gpu.py -> build\lib.win-amd64-3.7\test
  copying test\test_scatter.py -> build\lib.win-amd64-3.7\test
  copying test\test_segment.py -> build\lib.win-amd64-3.7\test
  copying test\test_zero_tensors.py -> build\lib.win-amd64-3.7\test
  copying test\utils.py -> build\lib.win-amd64-3.7\test
  copying test\__init__.py -> build\lib.win-amd64-3.7\test
  creating build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\scatter.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\utils.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\__init__.py -> build\lib.win-amd64-3.7\torch_scatter
  creating build\lib.win-amd64-3.7\torch_scatter\composite
  copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.7\torch_
scatter\composite
  copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.7\torch_sc
atter\composite
  copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.7\torch_scatte
r\composite
  copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.7\torch_s
catter\composite
  running build_ext
  C:\Users\user\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:209:
UserWarning: Error checking compiler version for cl: [WinError 2] The system can
not find the file specified
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler,
error))
  building 'torch_scatter._scatter' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\Users
  creating build\temp.win-amd64-3.7\Release\Users\user
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-
install-52vk92ny
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-
install-52vk92ny\torch-scatter
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-
install-52vk92ny\torch-scatter\csrc
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-
install-52vk92ny\torch-scatter\csrc\cpu
  creating build\temp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-
install-52vk92ny\torch-scatter\csrc\cuda
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IC:\Users\user\AppDa
ta\Local\Temp\pip-install-52vk92ny\torch-scatter\csrc -IC:\Users\user\Anaconda
3\lib\site-packages\torch\include -IC:\Users\user\Anaconda3\lib\site-packages\
torch\include\torch\csrc\api\include -IC:\Users\user\Anaconda3\lib\site-packag
es\torch\include\TH -IC:\Users\user\Anaconda3\lib\site-packages\torch\include\
THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\include" -IC:\Users\user\
Anaconda3\include -IC:\Users\user\Anaconda3\include /EHsc /TpC:\Users\user\A
ppData\Local\Temp\pip-install-52vk92ny\torch-scatter\csrc\scatter.cpp /Fobuild\t
emp.win-amd64-3.7\Release\Users\user\AppData\Local\Temp\pip-install-52vk92ny\t
orch-scatter\csrc\scatter.obj /MD /wd4819 /EHsc -O0 /MP -DTORCH_API_INCLUDE_EXTE
NSION_H -DTORCH_EXTENSION_NAME=_scatter -D_GLIBCXX_USE_CXX11_ABI=0
  error: command 'cl.exe' failed: No such file or directory
error
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
  Running command 'C:\Users\user\Anaconda3\python.exe' -u -c 'import sys, setu
ptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pi
p-install-52vk92ny\\torch-scatter\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ismai
l\\AppData\\Local\\Temp\\pip-install-52vk92ny\\torch-scatter\\setup.py'"'"';f=ge
tattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' cle
an --all
Cleaning up...
  Removing source in C:\Users\user\AppData\Local\Temp\pip-install-52vk92ny\tor
ch-scatter
Removed build tracker 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-tracker-
9x2esplb'

****** Note: *********
I have:
Python --version= 3.7.4
Pytorch version = 1.4.0
conda --version = 4.8.2
cuda --version = 10.1
windows = 8.1

Before this installation,  I also tried with visual studio 2019 and it couldn't find stddef.h because it is located in the Windows kit. After adding the appropriate environment variables (Include, bin, Lib), it caused cl.exe error. 

Any suggestions?

**Comment by Professoroo** [comment]
Further to my previous issue, I have downloaded torch-scatter, torch-sparse from amazon cloud wheels links provided by @rusty1s  , It works fine and I still need to download torch-cluster. 

Is there any link for building wheel for torch-cluster?

**Comment by rusty1s** [comment]
Not yet, I am working on it! PyG on master does not require `torch-cluster` though with the latest commit. It is now an optional dependency.

**Comment by Professoroo** [comment]
Based on your reply, Data function will not work anymore, however PyG works fine.
from torch_geometric.data import Data: this is not going to work?

**Comment by rusty1s** [comment]
Are you in the `pytorch_geometric` dictionary when running the command? This may lead to this strange error.

**Comment by Professoroo** [comment]
import torch
import torch_geometric
----------
<ipython-input-11-d481781ab360> in <module>
      4 
      5 import torch
----> 6 import torch_geometric
      7 from torch_sparse import coalesce
      8 
 1 from .debug import is_debug_enabled, debug, set_debug
----> 2 import torch_geometric.nn
      3 import torch_geometric.data
      4 import torch_geometric.datasets
      5 import torch_geometric.transforms

 1 from .meta import MetaLayer
----> 2 from .data_parallel import DataParallel
      3 from .reshape import Reshape
      4 from .conv import *  # noqa
      5 from .norm import *  # noqa


 3 
      4 import torch
----> 5 from torch_geometric.data import Batch
      6 
      7 
<module>
      4 from .in_memory_dataset import InMemoryDataset
      5 from .dataloader import DataLoader, DataListLoader, DenseDataLoader
----> 6 from .sampler import NeighborSampler
      7 from .download import download_url
      8 from .extract import extract_tar, extract_zip, extract_bz2, extract_gz

 3 
      4 import torch
----> 5 from torch_cluster import neighbor_sampler
      6 import torch_geometric
      7 from torch_geometric.data import Data

ModuleNotFoundError: No module named 'torch_cluster'

**Comment by rusty1s** [comment]
You need to install PyG from source. Did you do that? Just clone the repo and run`python setup.py install` inside of it.

**Comment by Professoroo** [comment]
Thank you a lot, Very appreciated.

After cloning the repo from source and running python setup.py instead of (pip install torch-geometric), everything works fine
