### ISSUE TITLE
Is it possible to choose which cuda version used to install pytorch geometric?

### ISSUE THREAD

**Issue by tjiagoM** [rusty1s/pytorch_geometric#958]
## ❓ Questions & Help

I have a GPU with CUDA version 10.2.  However, when installing pytorch I install using the cudatoolkit 10.1 (if I try cudatoolkit 10.2 my anaconda environment forces me to downgrade to pytorch version 1.0...). It looks like for every task I have, this mismatch of pytorch cuda version and actual gpu version never gave me an issue.

However, now that I've upgraded pytorch and pytorch_geometric, this mismatch is not fine anymore. After upgrading things, I receive an error now when importing things:
`RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_scatter has CUDA version 10.2. Please reinstall the torch_scatter that matches your PyTorch install.`

So, my question is: when doing pip install of all packages needed for pytorch geometric, is there some global variable that I can use which could make pytorch_geometric to be tricked to think I have cuda 10.1? Or, maybe, somehow stop this check hoping that the mismatch will not be an issue on the tasks I have?

The thing is that I was using pytorch geometric in this setting before (before the new 1.4.1 release) and I had no problem, but it looks like the new version of pytorch geometric is much more careful :)

**Comment by w00zie** [comment]
Went into this today, I solved following author's [readme](https://github.com/rusty1s/pytorch_scatter#Installation).

Just use `pip install torch-scatter==latest+cu101 -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com
`

**Comment by tjiagoM** [comment]
Damn, I missed that! Thanks a lot, it looks like it solved my problem :)

**Comment by tjiagoM** [comment]
I would like to add in case someone has the same problem. I had an issue with torch_cluster after these updates. So I just had to remove it and install torch-cluster again using `--no-cache-dir`.
