### ISSUE TITLE
Windows and Cloud Notebook Install Experience

### ISSUE THREAD

**Issue by matt-erhart** [rusty1s/pytorch_geometric#966]
Windows 10: pytorch works without a system wide cuda install somehow. Would be great to get that with pyg. Based on other issues, it's is possible to compile on windows after getting visual studio and cuda and python to talk to each other at the system level. I'm just trying things out so I moved on to notebooks after fixing a few compile errors. 
Kaggle Notebook: takes a long time to pip install / build, but it will import the readme example without error. Select GPU mode first else loose your install when you switch. 
Azure Notebook: fails immediately. Maybe this wasn't linux?
Google Colab: fails on some package (forgot which) at the wheel build step

Maybe for now, point windows users to a kaggle notebook to quickly start learning/testing out examples?

**Comment by rusty1s** [comment]
I am actually in the process of achieving this. There are now already Python wheels available for torch-scatter and torch-sparse.

**Comment by matt-erhart** [comment]
Awesome, hope this helps get even more users. 

For those that googled for a cloud notebook first but the cuda version is off, you need ```$ pip install torch-scatter==latest+${CUDA} torch-sparse==latest+${CUDA} -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html``` from the torch-geometric readme. 

Also I believe ```pip install torch-cluster (optional)``` is actually required to import torch-geometric, and was the source of most of my compile issues on windows.

**Comment by rusty1s** [comment]
That looks good. Note that `torch-cluster` is no longer mandatory on master, but is still required in the latest release.
