### ISSUE TITLE
dgcnn_segmentation.py Example Errors

### ISSUE THREAD

**Issue by EddyDavies** [rusty1s/pytorch_geometric#981]
## To Reproduce

Steps to reproduce the behaviour:

1. Ran the dgcnn_segmentation.py example provided in the repo

[210/235] Loss: 0.3474, Train Accuracy: 0.8728
[220/235] Loss: 0.2646, Train Accuracy: 0.9023
[230/235] Loss: 0.2900, Train Accuracy: 0.8948
Traceback (most recent call last):
  File "dgcnn_segmentation.py", line 121, in <module>
    acc, iou = test(test_loader)
  File "dgcnn_segmentation.py", line 107, in test
    i = intersection[j, loader.dataset.y_mask[category[j]]]
IndexError: The shape of the mask [50] at index 0 does not match the shape of the indexed tensor [4] at index 0

## Expected behavior

Finish the run of Epochs without any errors

## Environment

* OS: CentOS Linux release 7.7.1908 (Core)
* Python version: 3.7
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.0
* GCC version: 5.5.0
* Any other relevant information:

**Comment by FENGA1** [comment]
Hi, I also encountered this problem while running dgcnn_segmentation.py. How did you solve it? Thanks

**Comment by mayurmallya** [comment]
@EddyDavies Could you please share your solution?
Thanks!
