### ISSUE TITLE
Not sure how to Implement a Custom Datatset

### ISSUE THREAD

**Issue by dcoukos** [rusty1s/pytorch_geometric#984]
## ❓ Questions & Help

Hi @rusty1s , thanks so much for this powerful library. I apologize for this basic question, but I can't figure out how to implement the Dataset class. 

You can find my code below. Once I instantiate my StructuresDataset class and try to access the first element of the class I get a FileNotFoundError.

<details>
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-9b7c4a596534> in <module>
----> 1 train[0]

~/opt/anaconda3/envs/geo/lib/python3.7/site-packages/torch_geometric-1.3.2-py3.7.egg/torch_geometric/data/dataset.py in __getitem__(self, idx)
    164         r"""Gets the data object at index :obj:`idx` and transforms it (in case
    165         a :obj:`self.transform` is given)."""
--> 166         data = self.get(idx)
    167         data = data if self.transform is None else self.transform(data)
    168         return data

~/Desktop/Drawer/LPDI/masif-tools/dataset.py in get(self, idx)
    290 
    291     def get(self, idx):
--> 292         data = torch.load(osp.join(self.processed_dir, 'data_{}.pt'.format(idx)))
    293         return data

~/opt/anaconda3/envs/geo/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    417             (sys.version_info[0] == 2 and isinstance(f, unicode)):
    418         new_fd = True
--> 419         f = open(f, 'rb')
    420     elif (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    421         new_fd = True

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/full_train_ds/processed/data_0.pt'
</details>

This confuses me a bit, because, as I understand it, the purpose of the processed_file_names function is to check whether the dataset has already been processed, so it would be normal that the data files are not there yet. 

For clarity, my directory is structured like this:
- project directory/
     - sandbox.py
     - datasets/
          - full_train_ds/
             - raw/
                 - full_structure_1.pt
                 - full_structure_2.pt 
                 - ......
            - processed/

What am I misunderstanding? 

Thank you.

**Here is my non-functional implementation:** 

```
class StructuresDataset(Dataset):
    '''
    Structures class for datasets that do not fit into memory.
    '''
    def __init__(self, root='./datasets/{}/'.format(p.dataset), pre_transform=None, transform=None):
        super(StructuresDataset, self).__init__(root, transform, pre_transform)
        self.has_nan = []
        self.device = torch.device('cpu')

    @property
    def raw_file_names(self):
        n_files = len(glob('./datasets/{}/raw/full_structure_*'.format(p.dataset)))
        return ['full_structure_{}.pt'.format(idx) for idx in range(0, n_files)]

    @property
    def processed_file_names(self):
        return ['data_{}.pt'.format(idx) for idx in range(0, 9390)] 

    def download(self):
        pass

    def process(self):
        from utils import has_nan

        i = 0
        for raw_path in self.raw_paths:
            data = torch.load(raw_path, map_location=self.device)

            if self.pre_filter is not None:
                if max(torch.isnan(data.shape_index)):
                    self.has_nan.append(i)
                    continue

            if self.pre_transform is not None:
                data = self.pre_transform(data)

            torch.save(data, osp.join(self.processed_dir, 'data_{}.pt'.format(i)))
            i += 1

    def len(self):
        return len(self.processed_file_names)

    def get(self, idx):
        data = torch.load(osp.join(self.processed_dir, 'data_{}.pt'.format(idx)))
        return data

```
And this is how I call it in a sandbox implementation: 
(I'm just trying to preprocess the data for now, without actually using it)

```
from dataset import StructuresDataset
from torch_geometric.transforms import *
from transforms import *
from torch_geometric.data import DataLoader


train = StructuresDataset(root='./datasets/full_train_ds/',
                          pre_transform=Compose((Center(), FaceAttributes(),
                          NodeCurvature(), FaceToEdge(),
                          TwoHop(), AddShapeIndex())))
loader = DataLoader(train)

for l in loader:
    l.y = l.x
```

**Comment by rusty1s** [comment]
This seems weird. Do you can verify if the files are actually existing on the disk? Does the `process` method even gets called?

**Comment by dcoukos** [comment]
The files do seem to exist, 
<img width="239" alt="Screen Shot 2020-02-22 at 1 09 41 PM" src="https://user-images.githubusercontent.com/13315281/75092123-2051fc80-5575-11ea-8d34-c15e68ef0cf6.png">

The process function is called, but the function does not seem to enter the loop for the self.raw_paths.

**Comment by rusty1s** [comment]
Yes, because raw_file_names is empty because the glob needs to be dependent on self.root.

**Comment by dcoukos** [comment]
This fixed it, thanks!
