### ISSUE TITLE
Using NeighborSampler (with InMemoryDatasets)

### ISSUE THREAD

**Issue by dcoukos** [rusty1s/pytorch_geometric#987]
## ❓ Questions & Help

Hi @rusty1s , I am trying to use the Neighbor Sampler to collect information about the patches around nodes on molecular surfaces. I have tried to implement a minimal example based on the [reddit example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py), but I am running into some curious errors. After consulting the original [feature request](https://github.com/rusty1s/pytorch_geometric/issues/64) re neighborhood sampling and the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/reddit.html#Reddit) on the Reddit example  I have not been able to figure out why. 

I load my training set as an InMemoryDataset, as in the reddit example. They have x, y, and edge_index, as well as other attributes. I load a single structure, and then initialize a NeighborSampler with it. I need to use a larger patch than in the examples, so my n_hops is 9. 

When I try to create a dataflow using the Neighbor sampler, I get AttributeError: 'Data' object has no attribute 'dtype'. This seems strange to me, but if I manually give the structure a dtype attribute I get AttributeError: 'Data' object has no attribute 'split'. 
A similar error occurs if I use a DataLoader to load my structures.

Here is the (very) minimal example: 

```
data = trainset[0]
ns = NeighborSampler(data, 0.1, 9, batch_size=100, add_self_loops=True)
for dataflow in ns(data):
    print('loop')

```
And the traceback:
<details>
AttributeError                            Traceback (most recent call last)
<ipython-input-40-d8248563c07c> in <module>
----> 1 for dataflow in ns(data):
      2     print('loop')

~/opt/anaconda3/envs/geo/lib/python3.7/site-packages/torch_geometric-1.3.2-py3.7.egg/torch_geometric/data/sampler.py in __call__(self, subset)
    261             produce = self.__produce_subgraph__
    262 
--> 263         for n_id in self.__get_batches__(subset):
    264             yield produce(n_id)

~/opt/anaconda3/envs/geo/lib/python3.7/site-packages/torch_geometric-1.3.2-py3.7.egg/torch_geometric/data/sampler.py in __get_batches__(self, subset)
    146             subset = torch.randperm(self.data.num_nodes)
    147         else:
--> 148             if subset.dtype == torch.bool or subset.dtype == torch.uint8:
    149                 subset = subset.nonzero().view(-1)
    150             if self.shuffle:

AttributeError: 'Data' object has no attribute 'dtype'
</details>

What am I doing wrong here? Thank you!

**Comment by rusty1s** [comment]
This line is wrong:
```
for dataflow in ns(data):
```
You either pass in nothing, our the indices of the nodes you want to iterate over.

**Comment by dcoukos** [comment]
Thank you!
