### ISSUE TITLE
Changed behaviour in InMemoryDataset slicing after pytorch_geometric update?

### ISSUE THREAD

**Issue by tjiagoM** [rusty1s/pytorch_geometric#989]
## ❓ Questions & Help

Hello, I'm having a different behaviour in some of my code after I've updated to the new version of pytorch_geometric, but I cannot be sure whether this is something that changed with pytorch_geometric or in the new version of pytorch. I have saved the environment with the previous versions so I was able to see that this specific behaviour is different.

Any help in finding whether this is my own mistake or a bug would be very much appreciated!

So, I have my own InMemoryDataset, and I split it in train/test indexes. `dataset` is my InMemoryDataset, and `train_index` is a list of indexes to slice from my dataset. Before (previous version of pytorch_geometric/pytorch), this would be the output of my code:

```
>> type(train_index)
<class 'list'>
>> len(train_index)
2999
>> X_train_out = dataset[torch.tensor(train_index)]
>> X_train_out.data.y.shape
torch.Size([2999])
>> dataset.data.y.shape
torch.Size([3752])
>> len(X_train_out)
2999
```

However, with my new environment, for the same code, I'm having this behaviour:
```
>> type(train_index)
<class 'list'>
>> len(train_index)
2999
>> X_train_out = dataset[torch.tensor(train_index)]
>> X_train_out.data.y.shape
torch.Size([3752])
>> dataset.data.y.shape
torch.Size([3752])
>> len(X_train_out)
2999
```

Notice that now, there's no mismatch in the length of my output variable (`y`) in the sliced dataset (`X_train_out`) and original dataset; in other words, `X_train_out`'s output variable was kept like the original dataset instead of being equally sliced. However, if I call `len()` on the sliced dataset, it returns an expected value. It looks like new code is not slicing everything while before it was?

**Comment by tjiagoM** [comment]
I have checked the source code and noticed that in the new version of InMemoryDataset, the previous methods `__getitem__`, `__len__`, and `__indexing__` don't exist anymore so I guess the code is now using some default ones from pytorch directly? 

Was there any reasoning to remove these methods?

**Comment by tjiagoM** [comment]
I have checked the source code and noticed that in the new version of InMemoryDataset, the previous methods `__getitem__`, `__len__`, and `__indexing__` don't exist anymore and were "transferred" to the parent class, but the implementation now is different and actually `__indexing__` doesn't exist anymore.

I'm not very familiar with pytorch geometric's source code, but I think maybe the problem is that with the new __getitem__, the previous code line `if isinstance(idx, slice):` does not exist anymore. 

Was there any reasoning to change this? I wonder whether other people were using the __getitem__ the way I'm doing and are not aware yet of this change?

**Comment by rusty1s** [comment]
Hi and thank you for the issue. The `indexing` functionality moved to the `Dataset` class, and you can now also easily shuffle and slice out of memory datasets. For `InMemoryDataset`s, they now do not get copied when using slicing or shuffling. So that is very convenient. The issue that you are seeing is that you work directly on the `dataset.data` object which you really shouldn't. It actually should be marked as a private attribute `__data__`. If you want to access your data, use `len(dataset)` and `dataset[i]`.

**Comment by tjiagoM** [comment]
Hi, thanks for your prompt reply!

I'm not sure I understand. I'm already slicing the original dataset as you say, right?:
`X_train_out = dataset[torch.tensor(train_index)]`

(So, even if they are not copied, they should still have a correct new size?)

**Comment by rusty1s** [comment]
They are correctly sliced as indicated by the output of `len(dataset)` and `dataset[i]`. It is just that there are no more modifications to the `dataset.data` object to achieve that :)

**Comment by tjiagoM** [comment]
Ok, but in that case, if `data` object is something I should not work with, what would be the correct way to access my output labels of all my original `dataset`? Right now I'm doing `dataset.data.y` but you are saying this is also wrong?

Also, if I want to get the sliced `y` (and some other sliced variables) from the original dataset, should I use `dataset.data.y[[torch.tensor(train_index)]]`, or is there a more correct way to do so? In other words, if I wanted the sliced versions of all variables, I need to slice each one manually?

**Comment by rusty1s** [comment]
`dataset.data.y[[torch.tensor(train_index)]]` works fine in this case. I just wanted to let you know that `data` is only intended as an efficient storage format, not to work on directly. A IMO better way to handle it would be
```python
ys = torch.tensor([data.y for data in dataset])
```

**Comment by tjiagoM** [comment]
Ok, thanks a lot! I was just afraid that given these mismatches, the DataLoader wouldn't get the correct labels/info for the batch.

Thanks so much for your continuous support! If we ever meet I need to get you a pint or some beverage of your choice!!
