### ISSUE TITLE
RENet PreTransform data process

### ISSUE THREAD

**Issue by adtabia** [rusty1s/pytorch_geometric#992]
## ❓ How can i use the pre_transform function given by the RENet model in a Data object?

Im trying to implement the **RENet** model similar to the example [renet.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/renet.py), but using my own data. In the example the **ICEWS18** dataset downloads the raw data and takes the **RENet.pre_transform** function to create the h_sub, h_sub_t, h_obj, h_obj_t tensors, but if i try to use this in my own **Data** object (that contains the tensor sub, rel, obj and t) i get this error.

`RENet.pre_transform(seq_len=3)(data)`
`RuntimeError: bool value of Tensor with more than one value is ambiguous`

Then i thought that the process is been made using each interaction from sub, rel, obj and t. So i tried to iterate this changing the source code, but it launchs me a **Data** object with empety tensors in h_sub, h_sub_t, h_obj and h_obj_t.

This is the modification that i made:
```
def __call__(self, data):
      for sub, rel, obj, t in zip(data.sub, data.rel, data.obj, data.t):

            while max(sub, obj) + 1 > len(self.sub_hist):  # pragma: no cover
                self.sub_hist = self.increase_hist_node_size(self.sub_hist)
                self.obj_hist = self.increase_hist_node_size(self.obj_hist)

            # Delete last timestamp in history.
            if t > self.t_last:
                self.sub_hist = self.step(self.sub_hist)
                self.obj_hist = self.step(self.obj_hist)
                self.t_last = t

            # Save history in data object.
            data.h_sub, data.h_sub_t = self.get_history(self.sub_hist, sub, rel)
            data.h_obj, data.h_obj_t = self.get_history(self.obj_hist, obj, rel)

            # Add new event to history.
            self.sub_hist[sub][-1].append([obj, rel])
            self.obj_hist[obj][-1].append([sub, rel])

        return data

```

This is the result i got:
`Data(h_obj=[0], h_obj_t=[0], h_sub=[0], h_sub_t=[0], obj=[98861], rel=[98861], sub=[98861], t=[98861])`

It's clear that i didn't actually understood how this pre_transform process is made and i would need a little help please.

Thanks!

**Comment by pinillalumenai** [comment]
Hello. Did you manage to solve it? Could you post the solution? I am having the same issue. Thanks!
