### ISSUE TITLE
cuda101 no available for dependencies

### ISSUE THREAD

**Issue by 1byxero** [rusty1s/pytorch_geometric#995]
## Environment

* OS: xubuntu 16.04
* Python version: 3.7
* PyTorch version: 1.4
* CUDA/cuDNN version: 10.1
* GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [Yes] I followed the installation guide.
- [?] I cannot find my error message in the FAQ.
- [Yes] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [No] I have cloned the repository and tried a manual installation from source.
- [Yes?] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context
Tried installing with instructions on https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html, got following errorss
```
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+cu100 (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2)
ERROR: No matching distribution found for torch-scatter==latest+cu101
```

**Comment by rusty1s** [comment]
Can you access https://pytorch-geometric.com/whl/torch-1.4.0.html?

**Comment by 1byxero** [comment]
Yes

**Comment by rusty1s** [comment]
And
```
pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
```
does not work?

**Comment by 1byxero** [comment]
Nope, It does not

**Comment by rusty1s** [comment]
That's interesting, and I do not really know what is causing this. But note that you can always install via pip by just providing the link to the wheel, *e.g.*:
```
pip install https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-2.0.4%2Bcu101-cp37-cp37m-linux_x86_64.whl
```

**Comment by aaront97** [comment]
I've tried this, and I got:
`torch_scatter-2.0.4+cu101-cp37-cp37m-linux_x86_64.whl` is not a supported wheel on this platform.`


> That's interesting, and I do not really know what is causing this. But note that you can always install via pip by just providing the link to the wheel, _e.g._:
> 
> ```
> pip install https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-2.0.4%2Bcu101-cp37-cp37m-linux_x86_64.whl
> ```

**Comment by rusty1s** [comment]
Mh, I see. This might be because you are using xubuntu, and that needs a `manylinux` wheel? I am not sure and I will look into it. Your best option in the meantime would be to try to install these packages from source.

**Comment by 1byxero** [comment]
Sure thing!
Thanks for such fast responses
Also, can you redirect to some extensive tutorials/blogs which could be helpful for newbies?

**Comment by 1byxero** [comment]
I was able to install it today without using the wheels.
Looks like you added manylinux wheel
I'll go ahead and close this
