### ISSUE TITLE
Torch Jit compatibility for torch geometric and dependencies?

### ISSUE THREAD

**Issue by lgray** [rusty1s/pytorch_geometric#997]
## 🚀 Feature

In order to use pytorch geometric models as a service, we need to be able to package models such that they can be sent entirely over a network, received by a worker node unpacked, loaded and then receive data to perform inference on.

This can be done either by being ONNX compatible or by extending all C++ modules in torch geometric/scatter/cluster/spline/sparse to have torch jit hooks.

## Motivation

I'm a scientist at a US national lab working on the Large Hadron Collider. Graph neural networks (especially edge convolutional networks) are incredibly well suited to our data. We'd like to be able to deploy graph neural networks at scale. I really like pytorch for model development and torch geometric has been great for learning graph networks to the point I can make new network types (first arxiv posting soon, hopefully). 

However, if we want to get beyond the research we're doing being just cute toys at small scale, we absolutely need to be able to do inference as a service as it vastly simplifies our software packaging and is more scalable than each worker node needing to do inference having a GPU.

## Additional context

I am proposing to do the extension work myself and wonder if it would be a welcome contribution. Similarly, if it's already been done and I missed it please point me that way!

**Comment by rusty1s** [comment]
That is definitely something that I am very interested in! I already started with this procedure by making scatter/sparse/spline `torch.jit.script` compatible. `torch-cluster` support is coming soon. However, I did not make any changes to PyG concerning this yet.

**Comment by lgray** [comment]
Alright, cool. I'll focus on PyG then. I'll leave you to finish with torch cluster.
I have one more week on another task and then I'll start this in earnest.

**Comment by pierthodo** [comment]
Any update on this? I am looking to convert my model to onnx for performance purposes during inference.

Thanks

**Comment by lgray** [comment]
Hey - I'm working on making a new function in the message passing base class that analyzes your class and spits out a jitable model. Work's just a little slow with the quarantine but I'm making progress.

**Comment by lgray** [comment]
Finally some real progress here. I will start a WIP PR soon.

Within a module using pytorch_geometric convs:
```python
self.conv1 = DynamicEdgeConv(MLP([2 * 3, 64, 64, 64]), k, aggr)
self.conv2 = DynamicEdgeConv(MLP([2 * 64, 128]), k, aggr)
self.lin1 = MLP([128 + 64, 1024])

self.conv1.jittable(x=init_data.pos, batch=init_data.batch)
tempx = self.conv1(x=init_data.pos, batch=init_data.batch)
self.conv2.jittable(x=tempx, batch=init_data.batch)
```

Emits a new propagate function tailored to the operation:
```python
def propagate_7c83e75c8e6411ea820b9801a7b520cf(self, edge_index, size=None, x=None):
    in_kwargs = {'x': x}
    mp_type, size = self.__determine_type_and_size__(edge_index, size)
    kwargs = self.__collect__(edge_index, size, mp_type, in_kwargs)
    
    out = self.message(x_i=kwargs['x_i'], x_j=kwargs['x_j'])

    if self.__explain__:
        edge_mask = self.__edge_mask__.sigmoid()
        if out.size(0) != edge_mask.size(0):
            loop = edge_mask.new_ones(size[0])
            edge_mask = torch.cat([edge_mask, loop], dim=0)
        assert out.size(0) == edge_mask.size(0)
        out = out * edge_mask.view(-1, 1)

    out = self.aggregate(inputs=out, index=kwargs['index'], ptr=kwargs['ptr'], dim_size=kwargs['dim_size'])

    out = self.update(inputs=out, )

    return out
```

Once a few issues are sorted out with some CPU implementations of things, I think I'll have a PR to try.

Right now it needs to semi-trace the forward() calls but I can get around this with some mocking, etc. I do have to use `exec` but it's not exposed to the user directly.

I am happy to take suggestions on interface and setup.

**Comment by lgray** [comment]
The propagate function is this re-bound to the existing object. 
It's more or less a dynamic monkey patch, but it seems reasonable for what we want to achieve.

**Comment by rusty1s** [comment]
This looks awesome. Looking forward to your PR!

**Comment by lgray** [comment]
Closing this, since it's in now and moving to #1283
